### ISSUE TITLE
Sporadic Build failure

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#1065]
**Problem description**
Encountered following error once in the build. Unable to reproduce it locally. 
java.lang.AssertionError
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.emc.pravega.controller.request.RequestTest.testScaleRequest(RequestTest.java:136)

**Problem location**

**Suggestions for an improvement**
Need more investigation and hopefully a reproduction.

**Comment by shiveshr** [comment]
we have not reproduced it for a while. And the test has also gone through some changes. 
Will reopen if it happens again.
