### ISSUE TITLE
Occasional non-descriptive exception on when creating reader

### ISSUE THREAD

**Issue by StephanEwen** [pravega/pravega#1174]
**Problem description**

Creating a reader (`ClientFactory.createReader(...)`) occasionally fails with a non-descriptive exception.
I observed this once in a while when running the tests for the `FlinkExactlyOncePravegaReader` tests.

```
Caused by: java.lang.RuntimeException: io.pravega.shared.protocol.netty.ConnectionFailedException
	at io.pravega.common.concurrent.FutureHelpers.getAndHandleExceptions(FutureHelpers.java:124)
	at io.pravega.stream.impl.segment.SegmentInputStreamImpl.fetchCurrentStreamLength(SegmentInputStreamImpl.java:172)
	at io.pravega.state.impl.RevisionedStreamClientImpl.readFrom(RevisionedStreamClientImpl.java:93)
	at io.pravega.state.impl.StateSynchronizerImpl.fetchUpdates(StateSynchronizerImpl.java:64)
	at io.pravega.state.impl.StateSynchronizerImpl.conditionallyWrite(StateSynchronizerImpl.java:134)
	at io.pravega.state.impl.StateSynchronizerImpl.updateState(StateSynchronizerImpl.java:94)
	at io.pravega.stream.impl.ReaderGroupStateManager.initializeReader(ReaderGroupStateManager.java:98)
	at io.pravega.stream.impl.ClientFactoryImpl.createReader(ClientFactoryImpl.java:130)
	at io.pravega.stream.impl.ClientFactoryImpl.createReader(ClientFactoryImpl.java:117)
	at io.pravega.connectors.flink.FlinkExactlyOncePravegaReader.run(FlinkExactlyOncePravegaReader.java:158)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:87)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:55)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.run(SourceStreamTask.java:95)
	at org.apache.flink.streaming.runtime.tasks.StoppableSourceStreamTask.run(StoppableSourceStreamTask.java:39)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:262)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:700)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException
	at io.pravega.stream.impl.segment.AsyncSegmentInputStreamImpl$ResponseProcessor.connectionDropped(AsyncSegmentInputStreamImpl.java:74)
	at io.pravega.stream.impl.netty.ClientConnectionInboundHandler.channelUnregistered(ClientConnectionInboundHandler.java:70)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1312)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:826)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:752)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	... 1 more
```

**Problem location**

**Comment by tkaitchuck** [comment]
This should be resolved.
