### ISSUE TITLE
Unable to open-fence error observed when container ownership changes 

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#1198]
**Problem description**
When multiple hosts are coming up one after another and container ownership changes from one host to another, following exception is thrown:
2017-05-03 21:09:47,387 20985 [segment-store-5] INFO  i.p.c.c.AbstractThreadPoolService - StorageWriter[1]: Stopped.
2017-05-03 21:09:47,396 20994 [BookKeeperClientWorker-orderedsafeexecutor-7-0] WARN  o.a.bookkeeper.client.LedgerHandle - Conditional update ledger metadata for ledger 7 failed.
2017-05-03 21:09:47,397 20995 [BookKeeperClientWorker-orderedsafeexecutor-8-0] WARN  o.a.bookkeeper.client.LedgerHandle - Conditional update ledger metadata for ledger 8 failed.
2017-05-03 21:09:47,403 21001 [segment-store-26] ERROR i.p.s.s.i.bookkeeper.BookKeeperLog - Log[0]: Unable to close LedgerHandle for Ledger 8.
io.pravega.service.storage.DurableDataLogException: Unable to open-fence ledger 8.
        at io.pravega.service.storage.impl.bookkeeper.Ledgers.close(Ledgers.java:108)
        at io.pravega.service.storage.impl.bookkeeper.BookKeeperLog.close(BookKeeperLog.java:149)
        at io.pravega.service.server.logs.DurableLog.lambda$doStop$1(DurableLog.java:184)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.bookkeeper.client.BKException$BKMetadataVersionException: null
        at org.apache.bookkeeper.client.BKException.create(BKException.java:82)
        at org.apache.bookkeeper.client.LedgerHandle.close(LedgerHandle.java:239)
        at io.pravega.common.Exceptions.handleInterrupted(Exceptions.java:53)
        at io.pravega.service.storage.impl.bookkeeper.Ledgers.close(Ledgers.java:106)
        ... 9 common frames omitted
2017-05-03 21:09:47,403 21001 [segment-store-29] ERROR i.p.s.s.i.bookkeeper.BookKeeperLog - Log[1]: Unable to close LedgerHandle for Ledger 7.
io.pravega.service.storage.DurableDataLogException: Unable to open-fence ledger 7.
        at io.pravega.service.storage.impl.bookkeeper.Ledgers.close(Ledgers.java:108)
        at io.pravega.service.storage.impl.bookkeeper.BookKeeperLog.close(BookKeeperLog.java:149)

**Problem location**
Durablelog ownership handover.

**Suggestions for an improvement**
Nothing. There is a chance this is just part of startup.

**Comment by skrishnappa** [comment]
>> "converges in a few attempts": this is not a solution to the problem. Such convergence is likely going to take exponentially longer with a higher number of machines or containers.

Here the start was very slow and taking a long time, hence the next attempt will wait until this start operation completes. There is no exponential wait here, just waiting for the existing start operation to complete. 

I will close this issue, since this is as per the current design where there could be temporary failure logs when start operation is stuck and we try to move this container to another host. Enhancement to prevent even these are discussed here https://github.com/pravega/pravega/issues/154
