### ISSUE TITLE
ContainerReadIndexTests fails in jenkins

### ISSUE THREAD

**Issue by Prabha-Veerubhotla** [pravega/pravega#1281]
**Problem description**
ContainerReadIndexTests  fails with the following
Error Logs:
```
java.lang.AssertionError: Unexpected error happened while processing Segment 85: io.pravega.service.contracts.StreamSegmentNotExistsException: [Segment 'Segment_85'] The StreamSegment does not exist.
	at org.junit.Assert.fail(Assert.java:88)
	at io.pravega.service.server.reading.ContainerReadIndexTests.testFutureReads(ContainerReadIndexTests.java:415)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```
**Problem location**
ContainerReadIndexTests.testFutureReads

**Suggestions for an improvement**

**Comment by fpj** [comment]
We aren't observing this test case failing, so I'm closing this issue.
