### ISSUE TITLE
Sporadic unit test failures

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#1283]
**Failure 1**
```
io.pravega.service.server.host.SegmentStoreIntegrationTest > testEndToEnd FAILED
    java.util.concurrent.ExecutionException: io.pravega.service.contracts.StreamSegmentNotExistsException: [Segment 'Segment_7#transaction.f6cbccd1a4eb48b4adb4b149c35fefec'] The StreamSegment does not exist.
        Caused by:
        io.pravega.service.contracts.StreamSegmentNotExistsException: [Segment 'Segment_7#transaction.f6cbccd1a4eb48b4adb4b149c35fefec'] The StreamSegment does not exist.
            Caused by:
            java.io.FileNotFoundException: Segment_7#transaction.f6cbccd1a4eb48b4adb4b149c35fefec
```

**Comment by Abhijeet-Jadhav** [comment]
Observed this on local build failure:
```
io.pravega.service.server.containers.StreamSegmentContainerTests > testSegmentDelete FAILED
    java.lang.IllegalStateException: Expected the service StreamSegmentContainer [FAILED] to be TERMINATED, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
        at com.google.common.util.concurrent.AbstractService.awaitTerminated(AbstractService.java:293)
        at io.pravega.service.server.containers.StreamSegmentContainerTests.testSegmentDelete(StreamSegmentContainerTests.java:602)

       Caused by:
        java.util.concurrent.TimeoutException
```
