### ISSUE TITLE
Append to commitstream fails with HDFS APPEND_FILE errors sporadically

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#1287]
**Problem description**
Appends to commitstream segments fail due to HDFS failure. This causes the dependent scale operations to fail. Here is the stack trace of the problem.
```
2017-05-08 06:24:49,663 130487 [epollEventLoopGroup-3-4] DEBUG i.p.s.s.c.StreamSegmentContainer - SegmentContainer[3]: getStreamSegmentInfo [testReadAutoScale1664541741/testScaleUp/0#transaction.0e874aa8a00647c685d0244a36e3f385]
2017-05-08 06:24:49,668 130492 [segment-store-21] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[2]: Iteration[143].Error.
org.apache.hadoop.ipc.RemoteException: Failed to APPEND_FILE /_system/_commitStream/0_0_1 for DFSClient_NONMAPREDUCE_-265796288_65 on 44.128.0.3 because DFSClient_NONMAPREDUCE_-265796288_65 is already the current lease holder.
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.recoverLeaseInternal(FSNamesystem.java:2882)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInternal(FSNamesystem.java:2683)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInt(FSNamesystem.java:2982)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFile(FSNamesystem.java:2950)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.append(NameNodeRpcServer.java:654)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.append(ClientNamenodeProtocolServerSideTranslatorPB.java:421)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:969)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2049)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2045)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2043)

        at org.apache.hadoop.ipc.Client.call(Client.java:1475)
        at org.apache.hadoop.ipc.Client.call(Client.java:1412)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
        at com.sun.proxy.$Proxy13.append(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.append(ClientNamenodeProtocolTranslatorPB.java:328)
        at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
        at com.sun.proxy.$Proxy14.append(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.callAppend(DFSClient.java:1808)
        at org.apache.hadoop.hdfs.DFSClient.append(DFSClient.java:1877)
        at org.apache.hadoop.hdfs.DFSClient.append(DFSClient.java:1847)
        at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:340)
        at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:336)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.append(DistributedFileSystem.java:348)
        at org.apache.hadoop.hdfs.DistributedFileSystem.append(DistributedFileSystem.java:318)
        at org.apache.hadoop.fs.FileSystem.append(FileSystem.java:1166)
        at io.pravega.service.storage.impl.hdfs.WriteOperation.run(WriteOperation.java:64)
        at io.pravega.service.storage.impl.hdfs.HDFSStorage.lambda$runAsync$0(HDFSStorage.java:213)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

**Problem location**
io.pravega.service.storage.impl.hdfs.WriteOperation.run(WriteOperation.java:64)

**Suggestions for an improvement**

**Comment by arvindkandhare** [comment]
The following stacktrace is the root cause of the errors. I think the reason deployment. We need a multi instance deployment of HDFS. Will keep this around just in case multinode deployment also does show this error.

017-05-09 09:23:43,493 76981 [segment-store-9] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[3]: Iteration[11].Error.
   5513 java.io.IOException: Failed to replace a bad datanode on the existing pipeline due to no more good datanodes being available to try. (Nodes: current=[DatanodeI        nfoWithStorage[9.0.0.130:50010,DS-ae1d67e3-2162-4fce-9a7a-833bb90d2ac1,DISK]], original=[DatanodeInfoWithStorage[9.0.0.130:50010,DS-ae1d67e3-2162-4fce-9a7a-833        bb90d2ac1,DISK]]). The current failed datanode replacement policy is DEFAULT, and a client may configure this via 'dfs.client.block.write.replace-datanode-on-f        ailure.policy' in its configuration.
   5514         at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.findNewDatanode(DFSOutputStream.java:925)
   5515         at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.addDatanode2ExistingPipeline(DFSOutputStream.java:988)
   5516         at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.setupPipelineForAppendOrRecovery(DFSOutputStream.java:1156)
   5517         at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:454)

**Comment by fpj** [comment]
Maybe the problem is as @arvindkandhare points out, but the logic seems broken here. The stack trace originally reported indicates an issue with the lease holder, while the second is related to insufficient replication. How are we supposed to connect the two? Again, I'm not saying this is not the problem, but I'm not following the logic here.

**Comment by arvindkandhare** [comment]
Here is the reasoning for this. There is a chance this may be wrong. That's why I am keeping the issue around.
1. A quick preview of how HDFS leasing works: The namenode creates a temporary file for the client. If any client is trying to open the HDFS file again, this lease is checked against. The lease file is deleted which the owner closes the stream. Continuous heartbeat ensures that the owner is still alive. In case the owner has not closed the file and some other open call is received for the file: the lease is broken. When the lease is broken, the namenode waits for the original owner to send heartbeat for designated time and if it is not received, breaks the lease. (There is a pending discussion to be had for using this behavior for HDFS locking). 
Now the interesting part is the waiting period. In case of a different client than the current owner the wait period is 1 minute. If the owner is same, the wait period is one hour. 

2. With the second stacktrace - something bad happens in the container which is running one instance of everything HDFS. The datanode (and maybe the namenode) is not accessible after this error in the second stack trace. Because of which the owner can not write to the file as well as close the stream. The lease is not released in the usual way. Now the namenode/datanode recovers and is available. Any further attempt to open is a lease breaking operation. And as we are doing it from the same client - the wait period is one hour.
In case of multiple datanode the assumption is that a bad datanode is replaced and namenode ensures that the lease is maintained properly. The writes and close never fail the way they are failing here and we will never be in this situation. 
I recommend keeping the issue around as there are multiple places where this explanation may be wrong and the issue may still appear in case of a multinode HDFS deployment.
