### ISSUE TITLE
ControllerFailoverTest failing

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1314]
**Problem description**
```
io.pravega.test.integration.ControllerFailoverTest > testStop FAILED
    java.lang.AssertionError: Failed starting controllerWrapper
        at org.junit.Assert.fail(Assert.java:88)
        at io.pravega.test.integration.ControllerFailoverTest.testStop(ControllerFailoverTest.java:169)
```

**Problem location**
ControllerFailoverTest 

**Suggestions for an improvement**
Reproduce and debug issue cause

**Comment by shiveshr** [comment]
@bhargav-gulavani is this issue done?
i see PR #1329 which unmasked the error.
