### ISSUE TITLE
testCacheEviction failure

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1327]
**Problem description**
I observed this test case failure in our internal jenkins:

```
Error Message

java.lang.AssertionError: Unexpected CacheKey.SegmentOffset at index 23 for SegmentId 52. expected:<4800> but was:<4900>
Stacktrace

java.lang.AssertionError: Unexpected CacheKey.SegmentOffset at index 23 for SegmentId 52. expected:<4800> but was:<4900>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at io.pravega.segmentstore.server.reading.ContainerReadIndexTests.checkOffsets(ContainerReadIndexTests.java:959)
	at io.pravega.segmentstore.server.reading.ContainerReadIndexTests.testCacheEviction(ContainerReadIndexTests.java:796)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Problem location**
Segment store, test case failure.

**Suggestions for an improvement**
Track the issue and fix it.

**Comment by andreipaduroiu** [comment]
I tried to repro this many times locally, including running the unit test in an infinite loop. So far, no luck. If no further instances of this failure appear until June 30, 2017, I will close this issue.
