### ISSUE TITLE
Intermittent test failure StreamSegmentContainerTests.testSegmentDelete

### ISSUE THREAD

**Issue by bhargav-gulavani** [pravega/pravega#1343]
**Problem description**
Intermittent failure of test `StreamSegmentContainerTests.testSegmentDelete` on Travis. Below is the stack trace of the failure. 
```io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testSegmentDelete FAILED
    java.lang.IllegalStateException: Expected the service StreamSegmentContainer [FAILED] to be TERMINATED, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
        at com.google.common.util.concurrent.AbstractService.awaitTerminated(AbstractService.java:293)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testSegmentDelete(StreamSegmentContainerTests.java:609)
        Caused by:
        io.pravega.common.ObjectClosedException: Object 'BlockingDrainingQueue' has been closed and cannot be accessed anymore.
```
**Problem location**
StreamSegmentContainerTests

**Suggestions for an improvement**
Fix the test so that it succeeds always.

**Comment by Abhijeet-Jadhav** [comment]
Observed the same failure on travis today:
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testSegmentDelete FAILED
    java.lang.IllegalStateException: Expected the service StreamSegmentContainer [FAILED] to be TERMINATED, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
        at com.google.common.util.concurrent.AbstractService.awaitTerminated(AbstractService.java:293)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testSegmentDelete(StreamSegmentContainerTests.java:613)
        Caused by:
        io.pravega.common.ObjectClosedException: Object 'BlockingDrainingQueue' has been closed and cannot be accessed anymore.
```
