### ISSUE TITLE
ContainerReadIndexTests failure on Jenkins

### ISSUE THREAD

**Issue by vroy** [pravega/pravega#1381]
**Problem description**

The following test failure was seen on our internal Jenkins while attempting to build 43f88f80 of PR #1337:

```
io.pravega.segmentstore.server.reading.ContainerReadIndexTests > testCacheEviction FAILED
    java.lang.AssertionError: Unexpected CacheKey.SegmentOffset at index 33 for SegmentId 65. expected:<5800> but was:<5900>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at io.pravega.segmentstore.server.reading.ContainerReadIndexTests.checkOffsets(ContainerReadIndexTests.java:959)
        at io.pravega.segmentstore.server.reading.ContainerReadIndexTests.testCacheEviction(ContainerReadIndexTests.java:796)
```

**Comment by Abhijeet-Jadhav** [comment]
Observed this on local build as well.
```
io.pravega.segmentstore.server.reading.ContainerReadIndexTests > testCacheEviction FAILED
    java.lang.AssertionError: Unexpected CacheKey.SegmentOffset at index 13 for SegmentId 20. expected:<3800> but was:<3900>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at io.pravega.segmentstore.server.reading.ContainerReadIndexTests.checkOffsets(ContainerReadIndexTests.java:959)
        at io.pravega.segmentstore.server.reading.ContainerReadIndexTests.testCacheEviction(ContainerReadIndexTests.java:796)
```

**Comment by fpj** [comment]
We aren't observing this test failing any longer, so I'm closing it.
