### ISSUE TITLE
Intermittent failure of StreamSegmentContainerTests.testMetadataCleanupRecovery on Travis

### ISSUE THREAD

**Issue by bhargav-gulavani** [pravega/pravega#1390]
**Problem description**
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testMetadataCleanupRecovery FAILED
    java.lang.IllegalStateException: Expected the service MetadataCleanupContainer [FAILED] to be RUNNING, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
        at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:266)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testMetadataCleanupRecovery(StreamSegmentContainerTests.java:918)
        Caused by:
        java.lang.IllegalArgumentException: newMetadata: New Metadata Deletion Flag is different from existing one.
```

**Problem location**
`StreamSegmentContainerTests.testMetadataCleanupRecovery`

**Suggestions for an improvement**
Remove intermittent failure of test `StreamSegmentContainerTests.testMetadataCleanupRecovery`

**Comment by skrishnappa** [comment]
Observed this again on travis but a slightly different stack trace:

io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testMetadataCleanupRecovery FAILED
    java.lang.IllegalStateException: Expected the service MetadataCleanupContainer [FAILED] to be TERMINATED, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
        at com.google.common.util.concurrent.AbstractService.awaitTerminated(AbstractService.java:293)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testMetadataCleanupRecovery(StreamSegmentContainerTests.java:911)
        Caused by:
        io.pravega.segmentstore.server.DataCorruptionException: Unable to retrieve CacheContents for 'AggregatedAppend: SegmentId = 3, Offsets = [4806-4810), SeqNo = 4903'.
