### ISSUE TITLE
StreamManager.create URI Validation

### ISSUE THREAD

**Issue by chrisdail** [pravega/pravega#1398]
**Problem description**

If you pass just the controller `host:port` into StreamManager.create without `tcp://` you end up with a null pointer exception:

`StreamManager.create('host:9090')`

```
Caused by: java.lang.NullPointerException
    at io.pravega.shaded.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
    at io.pravega.shaded.com.google.common.base.Splitter.splitToList(Splitter.java:408)
    at io.pravega.client.stream.impl.ControllerResolverFactory.newNameResolver(ControllerResolverFactory.java:66)
    at io.pravega.shaded.io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:461)
    at io.pravega.shaded.io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:396)
    at io.pravega.shaded.io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:295)
    at io.pravega.client.stream.impl.ControllerImpl.<init>(ControllerImpl.java:98)
    at io.pravega.client.stream.impl.ControllerImpl.<init>(ControllerImpl.java:81)
    at io.pravega.client.admin.impl.StreamManagerImpl.<init>(StreamManagerImpl.java:30)
    at io.pravega.client.admin.StreamManager.create(StreamManager.java:28)
```

**Problem location**

ControllerImpl.java

**Suggestions for an improvement**

URI does not require a protocol. So maybe this should take a URL if we specifically need the protocol. Either that or it should do proper validation giving an error message if it does not recognize what was passed in.

**Comment by ShwethaSNayak** [comment]
This is addressed as part of PR #6559
