### ISSUE TITLE
BookKeeper error handling

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#1414]
After #1330 is done, the following fixes & improvements need to be done to `BookKeeperLog`:
1. Be able to properly recover from a BookKeeper error. For example, if BookKeeper closes a ledger, the `BookKeeperLog` does not reopen it.
2. Handle Operations With Unknown Outcomes. These can happen when connection to BK/ZK is lost during a write; the write eventually times out or fails with an exception, however the write has been committed to the ledger. 

Both of these can take advantage of the retry mechanism in `BookKeeperLog`:
- All writes are queued up and we have a write processor that goes through them and attempts/reattempts to execute them (Existing Behavior).
- When a `LedgerClosedException` is caught (which is the result of a rollover), trigger a new Ledger Rollover. This will close the current ledger (no-op if already closed) and create a new one.
- When a write fails, usually we get back the attempted entry id for that write. If it happens to be before the `lastAddConfirmed` for its attempted ledger, then this write succeeded. Otherwise it needs to be retried.

**Comment by maddisondavid** [comment]
During recent test runs we hit what I believe to be this particular issue with closed ledgers whereby Bookkeeper (for some reason to be determined)  closed the ledgers.  On retrying our test, it was unable to correctly open and start re-writing to segments as Bookkeeper threw exceptions regarding closed ledgers.

The following log shows the segment store hitting this error
[segmentstore_2017-06-07.0.txt](https://github.com/pravega/pravega/files/1061644/segmentstore_2017-06-07.0.txt)

On restart the client is unable to open the stream for writing.
`2017-06-08 15:51:14,853 176890590 [segment-store-36] ERROR i.p.s.s.h.handler.AppendProcessor - Error (Segment = 'hulk/_RGHulkSmallTest/0', Operation = 'append')
io.pravega.segmentstore.storage.DurableDataLogException: General exception while accessing BookKeeper.
    at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.handleWriteException(BookKeeperLog.java:354)
    at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.lambda$tryAppend$3(BookKeeperLog.java:295)
    at org.apache.bookkeeper.client.LedgerHandle$3.safeRun(LedgerHandle.java:690)
    at org.apache.bookkeeper.util.SafeRunnable.run(SafeRunnable.java:31)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.bookkeeper.client.BKException$BKLedgerClosedException: null
    at org.apache.bookkeeper.client.BKException.create(BKException.java:70)
    at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.handleWriteException(BookKeeperLog.java:338)
    ... 8 common frames omitted`
