### ISSUE TITLE
Sporadic test failure ScaleRequestHandlerTest > testScaleRequest

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#1490]
https://travis-ci.org/pravega/pravega/builds/247616180?utm_source=github_status&utm_medium=notification

```
io.pravega.controller.server.eventProcessor.ScaleRequestHandlerTest > testScaleRequest FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 20000 milliseconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1695)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1775)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
        at io.pravega.common.concurrent.FutureHelpers.lambda$await$0(FutureHelpers.java:70)
        at io.pravega.common.concurrent.FutureHelpers$$Lambda$300/574829317.run(Unknown Source)
        at io.pravega.common.Exceptions.handleInterrupted(Exceptions.java:47)
        at io.pravega.common.concurrent.FutureHelpers.await(FutureHelpers.java:68)
        at io.pravega.common.concurrent.FutureHelpers.await(FutureHelpers.java:55)
        at io.pravega.controller.server.eventProcessor.ScaleRequestHandlerTest.testScaleRequest(ScaleRequestHandlerTest.java:192)
```

**Comment by shiveshr** [comment]
ran the test locally and it was taking upward of 15 seconds on average.. 20 second timeout makes it pretty cut to cut esp on travis where multiple tests might be running concurrently or it may be generally resource starved.
so increasing the timeout to 30 seconds.
