### ISSUE TITLE
StreamSegmentContainer Unable to start

### ISSUE THREAD

**Issue by maddisondavid** [pravega/pravega#1528]
**Problem description**
SegmentStore is failing to start stopping internal streams from being created

[1491-Controller.txt](https://github.com/pravega/pravega/files/1121971/1491-Controller.txt)
[1491-Segment-Store.txt](https://github.com/pravega/pravega/files/1121972/1491-Segment-Store.txt)

**Problem location**
It looks like the initial startup is timing out here
```
2017-07-04 02:41:26,203 124801 [segment-store-16] WARN  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[3]: DurableLog failed. Shutting down StreamSegmentContainer.
java.util.concurrent.TimeoutException: null
    at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
    at io.pravega.segmentstore.server.logs.DurableLog.lambda$doStart$0(DurableLog.java:156)
2017-07-04 02:41:27,601 126199 [segment-store-1] WARN  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[2]: Failed due to component failure.
```

**Suggestions for an improvement**
Investigate reason for segment stores not starting

**Comment by maddisondavid** [comment]
Bookkeeper logs from the cluster in question.

[bookkeeper-1-stdout.txt](https://github.com/pravega/pravega/files/1122112/bookkeeper-1-stdout.txt)
[bookkeeper-2-stdout.txt](https://github.com/pravega/pravega/files/1122114/bookkeeper-2-stdout.txt)
[bookkeeper-0-stdout.txt](https://github.com/pravega/pravega/files/1122113/bookkeeper-0-stdout.txt)

**Comment by andreipaduroiu** [comment]
Unfortunately this log is only INFO level and the logs are polluted with useless stack traces from auto scaling. Were you able to repro this using DEBUG level logging (TRACE would be ideal).

**Comment by maddisondavid** [comment]
Unfortunately the error is not always seen, in fact most times things work fine, however we did see another failure this morning on our test system.

[stdout-Controller-1.txt](https://github.com/pravega/pravega/files/1144558/stdout-Controller-1.txt)
[stdout-SegStore-1.txt](https://github.com/pravega/pravega/files/1144557/stdout-SegStore-1.txt)

**Comment by skrishnappa** [comment]
The containers took 3 minutes each to start, but it did get created successfully. Also after the containers were started the internal stream got created ( cc @shiveshr ). @maddisondavid from the logs seems like everything is fine except for the initial delay in starting the containers. Are you seeing any errors on this setup even now?

Segment Store container start logs:
2017-07-13 03:23:08,462 38800 [segment-store-0] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Starting Container 0.
2017-07-13 03:23:15,365 45703 [segment-store-0] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Starting Container 1.
2017-07-13 03:23:16,665 47003 [segment-store-0] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Starting Container 2.
2017-07-13 03:23:21,761 52099 [segment-store-0] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Starting Container 3.

2017-07-13 03:26:25,262 235600 [segment-store-6] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container 0 has been registered.
2017-07-13 03:26:25,661 235999 [segment-store-27] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container 3 has been registered.
2017-07-13 03:26:25,660 235998 [segment-store-48] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container 2 has been registered.
2017-07-13 03:26:25,861 236199 [segment-store-31] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container 1 has been registered.

Controller stream creation logs:
2017-07-13 03:27:05,168 477907 [controllerpool-53] INFO  i.p.c.s.e.ControllerEventProcessors - Created stream _system/_commitStream
2017-07-13 03:27:05,168 477907 [controllerpool-53] INFO  i.p.c.s.e.ControllerEventProcessors - Created stream _system/_requeststream
2017-07-13 03:27:05,469 478208 [controllerpool-33] INFO  i.p.c.s.e.ControllerEventProcessors - Created stream _system/_abortStream
2017-07-13 03:28:10,565 543304 [ControllerEventProcessors STARTING] INFO  i.p.c.s.e.ControllerEventProcessors - Controller event processors startUp complete
2017-07-13 03:28:10,660 543399 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - Awaiting start of controller cluster listener

**Comment by maddisondavid** [comment]
Interesting, I just retried stream creation and it worked, thanks for looking.

I guess the problem is that we have no way of knowing when Pravega is initialised and ready.  Our tests deploy pravega wait for the controller HTTP port to be available at which point we assume tests can commence.

Is there a better way of indicating that Pravega is initialised and ready?

**Comment by fpj** [comment]
> Is there a better way of indicating that Pravega is initialised and ready?

yeah, this is heated topic of discussion in the group currently. :-)

**Comment by shiveshr** [comment]
Closing this issue as it has not been reported again.
