### ISSUE TITLE
filesystemintegration test fails spuriously with uexpected value from getStreamSegmentOffset

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#1577]
**Problem description**
io.pravega.segmentstore.server.host.FileSystemIntegrationTest > testEndToEnd FAILED
    java.lang.AssertionError: Unexpected value from getStreamSegmentOffset for segment Segment_7 expected:<2048> but was:<2917>

**Problem location**
FileSystemIntegrationTest.java

**Suggestions for an improvement**
None.

**Comment by Prabha-Veerubhotla** [comment]
Also fails with timeout
```
Stacktrace

java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.testEndToEnd(StreamSegmentStoreTestBase.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```
