### ISSUE TITLE
Intermittent failure in ControllerRestApiTest

### ISSUE THREAD

**Issue by skrishnappa** [pravega/pravega#1588]
**Problem description**
Integration test fails intermittently with following exception:

io.pravega.test.integration.ControllerRestApiTest > classMethod FAILED
    java.lang.IllegalStateException: Expected the service ControllerServiceStarter [FAILED] to be RUNNING, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
        at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:266)
        at com.google.common.util.concurrent.AbstractIdleService.awaitRunning(AbstractIdleService.java:175)
        at io.pravega.test.integration.demo.ControllerWrapper.awaitRunning(ControllerWrapper.java:144)
        at io.pravega.test.integration.utils.SetupUtils.startAllServices(SetupUtils.java:99)
        at io.pravega.test.integration.ControllerRestApiTest.setup(ControllerRestApiTest.java:90)
        Caused by:
        java.lang.IllegalStateException: Expected the service GRPCServer [FAILED] to be RUNNING, but the service has FAILED
            Caused by:
            java.io.IOException: Failed to bind
                Caused by:
                java.net.BindException: Address already in use
io.pravega.test.integration.ControllerRestApiTest > classMethod FAILED
    java.lang.IllegalStateException: Expected the service ControllerServiceMain [FAILED] to be TERMINATED, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
        at com.google.common.util.concurrent.AbstractService.awaitTerminated(AbstractService.java:293)
        at com.google.common.util.concurrent.AbstractExecutionThreadService.awaitTerminated(AbstractExecutionThreadService.java:239)
        at io.pravega.test.integration.demo.ControllerWrapper.close(ControllerWrapper.java:162)
        at io.pravega.test.integration.utils.SetupUtils.stopAllServices(SetupUtils.java:117)
        at io.pravega.test.integration.ControllerRestApiTest.tearDown(ControllerRestApiTest.java:95)
        Caused by:
        java.lang.IllegalStateException: Expected the service ControllerServiceStarter [FAILED] to be RUNNING, but the service has FAILED
            Caused by:
            java.lang.IllegalStateException: Expected the service GRPCServer [FAILED] to be RUNNING, but the service has FAILED
                Caused by:
                java.io.IOException: Failed to bind
                    Caused by:
                    java.net.BindException: Address already in use

**Problem location**
io.pravega.test.integration.ControllerRestApiTest

**Suggestions for an improvement**
Investigate and fix the failure

**Comment by shrids** [comment]
Not observing this issue hence closing it.
