### ISSUE TITLE
ArrayIndexOutOfBounds during readNextEvent

### ISSUE THREAD

**Issue by maddisondavid** [pravega/pravega#1596]
**Problem description**
During recent stress tests the readers failed with ArrayIndexOutOfBounds during readNextEvent.

Test had been running for 1 day and 23 hours and the readers at this point had read 2,763,000 events.

**Problem location**

The following stack traces show the issue, unfortunately I have no other information from the environment.

```
java.lang.ArrayIndexOutOfBoundsException: -1
java.util.ArrayList.elementData(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at io.pravega.client.stream.impl.Orderer.nextSegment(Orderer.java:35)
at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:86)
at com.emc.nautilus.pravega.taskexecutor.workers.readers.PravegaReader.start(PravegaReader.java:78)
at com.emc.nautilus.pravega.taskexecutor.workers.readers.ReaderWorkerManager.lambda$start$0(ReaderWorkerManager.java:117)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
```

and another run:

```
java.lang.ArrayIndexOutOfBoundsException: -3
at java.util.ArrayList.elementData(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at io.pravega.client.stream.impl.Orderer.nextSegment(Orderer.java:35)
at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:86)
at com.emc.nautilus.pravega.taskexecutor.workers.readers.PravegaReader.start(PravegaReader.java:78)
at com.emc.nautilus.pravega.taskexecutor.workers.readers.ReaderWorkerManager.lambda$start$0(ReaderWorkerManager.java:117)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
```

**Suggestions for an improvement**

Handle whatever issue causes the IndexOutOfBounds

**Comment by tkaitchuck** [comment]
I have a fix, that is linked in the RP above, but I'm a little surprised the test was able to reproduce this so quickly. It read 2.7M events. How many times was getNextEvent() called? IE: did it return null a lot?
 Also how many segments were in the stream?

**Comment by maddisondavid** [comment]
Unfortunately I don't have the environment or the data anymore so I'm not sure how many segments there were.  As for Nulls, I'm not sure, we don't really process the data, it's more of a load test.
