### ISSUE TITLE
StateSynchronizerImpl  continues to try to connect to old SSS post SSS failover

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#1601]
**Problem description**
StateSynchronizerImpl continues to connect to old SSS even though SSS has failed over and old SSS no longer exists. 
This results in client getting CFE. 

**Problem location**
StateSynchronizerImpl
`io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(...): /<OldIp>:12345
        at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:207)
        at io.pravega.client.segment.impl.SegmentMetadataClientImpl.fetchCurrentStreamLength(SegmentMetadataClientImpl.java:243)
        at io.pravega.client.state.impl.RevisionedStreamClientImpl.readFrom(RevisionedStreamClientImpl.java:102)
        at io.pravega.client.state.impl.StateSynchronizerImpl.fetchUpdates(StateSynchronizerImpl.java:75)
        at io.pravega.client.stream.impl.ReaderGroupStateManager.fetchUpdatesIfNeeded(ReaderGroupStateManager.java:261)
        at io.pravega.client.stream.impl.ReaderGroupStateManager.acquireNewSegmentsIfNeeded(ReaderGroupStateManager.java:251)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.acquireSegmentsIfNeeded(EventStreamReaderImpl.java:170)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.updateGroupStateIfNeeded(EventStreamReaderImpl.java:143)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:82)
        at io.pravega.controller.eventProcessor.impl.EventProcessorCell$Delegate.run(EventProcessorCell.java:98)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(...): /<OldIP>:12345
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
        at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:669)
        at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:1997)
        at io.pravega.client.segment.impl.SegmentMetadataClientImpl.getSegmentInfo(SegmentMetadataClientImpl.java:187)
        at io.pravega.client.segment.impl.SegmentMetadataClientImpl.lambda$fetchCurrentStreamLength$7(SegmentMetadataClientImpl.java:244)
        at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:190)
        ... 12 common frames omitted
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(...): /172.16.24.3:12345
        at io.pravega.client.netty.impl.ConnectionFactoryImpl$2.operationComplete(ConnectionFactoryImpl.java:125)
        at io.pravega.client.netty.impl.ConnectionFactoryImpl$2.operationComplete(ConnectionFactoryImpl.java:119)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.fulfillConnectPromise(AbstractEpollStreamChannel.java:910)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.finishConnect(AbstractEpollStreamChannel.java:929)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollOutReady(AbstractEpollStreamChannel.java:946)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:384)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        ... 1 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(...): /172.16.24.3:12345
`

**Suggestions for an improvement**
Handle all CFE scenarios and ensure segment address is refreshed from controller in case of a connection failure.

**Comment by shiveshr** [comment]
Additional information: 
logs: root@10.63.13.121:/root/Debug/systemTest-466
Note: controller has all the logs for the client.. 
you will notice that we have three readergroups namely commitStreamReaders, abortStreamReaders, scaleGroup
scalegroup and abortstreamreader are trying to connect to 172.16.24.3:12345
while commitStreamReaders is trying to connect to 172.16.24.11:12345

they never change even though SSS has failed over from these hosts and last seen it was running on 172.16.24.16 ..
