### ISSUE TITLE
Tier2 filesystem implementation should not treat AccessDeniedException as SegmentSealedException always

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#1606]
**Problem description**
Tier2 filesystem implementation converts all `AccessDeniedException` to `SegmentSealedException`. This should be done according to the context and a different exception should be thrown in case.

**Problem location**
`Storage` contract and `FileSystemStorage` implementation.

**Suggestions for an improvement**
Define an exception if required which covers this case and update the contract and implementation.

**Comment by fpj** [comment]
Here is the specific stack trace we have observed:

```
Caused by: java.nio.file.AccessDeniedException: /nfs/_system
segmentstore_1  |   at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
segmentstore_1  |   at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
segmentstore_1  |   at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
segmentstore_1  |   at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
segmentstore_1  |   at java.nio.file.Files.createDirectory(Files.java:674)
segmentstore_1  |   at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
segmentstore_1  |   at java.nio.file.Files.createDirectories(Files.java:767)
segmentstore_1  |   at io.pravega.segmentstore.storage.impl.filesystem.FileSystemStorage.syncCreate(FileSystemStorage.java:272)
segmentstore_1  |   at io.pravega.segmentstore.storage.impl.filesystem.FileSystemStorage.lambda$create$5(FileSystemStorage.java:148)
segmentstore_1  |   at io.pravega.segmentstore.storage.impl.filesystem.FileSystemStorage.lambda$supplyAsync$10(FileSystemStorage.java:385)
```
