### ISSUE TITLE
StreamSegmentContainerTests#testTransactionOperations fails in Jenkins

### ISSUE THREAD

**Issue by Prabha-Veerubhotla** [pravega/pravega#1625]
**Problem description**
Jenkins test failure:

Error Message

```
io.pravega.segmentstore.server.IllegalContainerStateException: Container 1234567 is in an invalid state for this operation. Expected: RUNNING; Actual: STOPPING.
Stacktrace

io.pravega.segmentstore.server.IllegalContainerStateException: Container 1234567 is in an invalid state for this operation. Expected: RUNNING; Actual: STOPPING.
	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.ensureRunning(StreamSegmentContainer.java:436)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.append(StreamSegmentContainer.java:239)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testTransactionOperations(StreamSegmentContainerTests.java:645)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Problem location**
StreamSegmentContainerTests#testTransactionOperations

**Suggestions for an improvement**

**Comment by andreipaduroiu** [comment]
I have not seen this ever since. If it doesn't recur by Sept 30th, I will close this issue.
