### ISSUE TITLE
Client fails fatally during scale operation

### ISSUE THREAD

**Issue by vroy** [pravega/pravega#1635]
**Problem description**

While running a slightly modified version of https://github.com/pravega/pravega-samples/tree/master/anomaly-detection against pravega `ef925d0`, the client fatally fails with this exception around the same time as a scale event.

```
2017-07-21 16:59:41,905 WARN  io.pravega.shaded.io.netty.channel.ChannelOutboundBuffer      - Failed to mark a promise as failure because it has succeeded already: DefaultChannelPromise@542a5946(success)
java.nio.channels.ClosedChannelException
	at io.pravega.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.close(...)(Unknown Source)
2017-07-21 16:59:41,905 WARN  io.pravega.client.segment.impl.SegmentOutputStreamImpl        - Connection failed due to: null
2017-07-21 16:59:51,635 ERROR org.apache.flink.streaming.runtime.tasks.StreamTask           - Error during disposal of stream operator.
io.pravega.common.util.RetriesExhaustedException: io.pravega.shared.protocol.netty.ConnectionFailedException
	at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:188)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl.getConnection(SegmentOutputStreamImpl.java:355)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl.lambda$flush$17(SegmentOutputStreamImpl.java:403)
	at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:171)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl.flush(SegmentOutputStreamImpl.java:402)
	at io.pravega.client.stream.impl.EventStreamWriterImpl.flushInternal(EventStreamWriterImpl.java:312)
	at io.pravega.client.stream.impl.EventStreamWriterImpl.flush(EventStreamWriterImpl.java:301)
	at io.pravega.connectors.flink.FlinkPravegaWriter.flushAndVerify(FlinkPravegaWriter.java:194)
	at io.pravega.connectors.flink.FlinkPravegaWriter.close(FlinkPravegaWriter.java:140)
	at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:43)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.dispose(AbstractUdfStreamOperator.java:126)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.disposeAllOperators(StreamTask.java:428)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:333)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:702)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by tkaitchuck** [comment]
These log lines don't align with the line numbers in master. What version did this come from?

**Comment by tkaitchuck** [comment]
I synced to that version and the line numbers are not matching up. Is there something pre-processing the source or code that could be mangling the line numbers? And are we sure that is the right CL?

**Comment by vroy** [comment]
This is how I'm building the application:

```
~/nautilus/pravega HEAD
❯ ls ~/.m2/repository/io/pravega/
ls: /Users/vincentroy/.m2/repository/io/pravega/: No such file or directory

~/nautilus/pravega HEAD
❯ git rev-parse HEAD
ef925d0bd7ffac448b83502e62e88d0e31a9409a

~/nautilus/pravega HEAD
❯ ./gradlew install
...

~/nautilus/flink-connectors master
❯ git rev-parse HEAD
405b9afcdde279323fa90f657777b564eaa5a78a

~/nautilus/flink-connectors master
❯ ./gradlew install
...

~/nautilus/pravega HEAD
❯ ls ~/.m2/repository/io/pravega/
pravega-client                    pravega-segmentstore-server       pravega-shared-controller-api     pravega-test-system
pravega-common                    pravega-segmentstore-server-host  pravega-shared-metrics            pravega-test-testcommon
pravega-connectors-flink_2.11     pravega-segmentstore-storage      pravega-shared-protocol
pravega-controller                pravega-segmentstore-storage-impl pravega-standalone
pravega-segmentstore-contracts    pravega-shared                    pravega-test-integration

~/nautilus/pravega-samples
❯ ./gradlew installDist
...
```

As far as I can tell, this should result in having the correct version of the client in the Flink application. I'm not aware of anything that would mangle the line numbers but these are the standard builds of `pravega`, `flink-connectors` and `pravega-samples`.

We just moved to master. I'm going to try again with HEAD of master.

**Comment by vroy** [comment]
Still seeing the same on master (`2191dd2`) when using the same steps.

**Comment by chrisdail** [comment]
I have not seen this with some of the recent client fixes. Closing this.
