### ISSUE TITLE
grpc keepalive failures cause client to fail fatally

### ISSUE THREAD

**Issue by vroy** [pravega/pravega#1670]
**Problem description**

```
java.lang.RuntimeException: io.grpc.StatusRuntimeException: UNAVAILABLE: Keepalive failed. The connection is likely gone
	at io.pravega.common.concurrent.FutureHelpers.getAndHandleExceptions(FutureHelpers.java:166)
	at io.pravega.client.stream.impl.ReaderGroupStateManager.handleEndOfSegment(ReaderGroupStateManager.java:156)
	at io.pravega.client.stream.impl.EventStreamReaderImpl.handleEndOfSegment(EventStreamReaderImpl.java:193)
	at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:96)
	at com.emc.nautilus.pravega.taskexecutor.workers.readers.PravegaReader.start(PravegaReader.java:78)
	at com.emc.nautilus.pravega.taskexecutor.workers.readers.ReaderWorkerManager.lambda$start$0(ReaderWorkerManager.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Keepalive failed. The connection is likely gone
	at io.grpc.Status.asRuntimeException(Status.java:543)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
	... 3 more
```

**Suggestions for an improvement**

It was mentioned in person that the client should not let this bubble up and try to recover from this.

**Comment by andreipaduroiu** [comment]
Is this in any way related to this error:

```
Aug 01, 2017 10:44:33 AM io.grpc.netty.NettyClientHandler$1 onGoAwayReceived
WARNING: Received GOAWAY with ENHANCE_YOUR_CALM. Debug data: {1}
Aug 01, 2017 10:44:33 AM io.grpc.internal.AtomicBackoff$State backoff
WARNING: Increased keepalive time nanos to 720,000,000,000
```
0:06:23.922 'Create Transaction: Stream0' failed with java.lang.RuntimeException: 
```
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Bandwidth exhausted
HTTP/2 error code: ENHANCE_YOUR_CALM
Received Goaway
too_many_pings.
```

**Comment by tkaitchuck** [comment]
This should be fixed in https://github.com/pravega/pravega/pull/1717
