### ISSUE TITLE
Sporadic build failure: EventProcessorTest > testInitialize

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#1706]
**Problem description**
`io.pravega.controller.eventProcessor.impl.EventProcessorTest > testInitialize FAILED
    java.lang.IllegalStateException: Expected the service EventProcessorGroup[readerGroup] to be RUNNING, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
        at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:266)
        at com.google.common.util.concurrent.AbstractIdleService.awaitRunning(AbstractIdleService.java:175)
        at io.pravega.controller.eventProcessor.impl.EventProcessorTest.testInitialize(EventProcessorTest.java:391)
        Caused by:
        java.lang.IllegalStateException: Expected the service Delegate [FAILED] to be RUNNING, but the service has FAILED
            Caused by:
            java.lang.NullPointerException
	at io.pravega.controller.eventProcessor.impl.EventProcessorCell$Delegate.shutDown(EventProcessorCell.java:133)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:84)
	... 2 more`
**Problem location**

EventProcessorTest,testInitialize mocks clientFactory.createReader. 
In this it returns a sequence answer. 
In the test we create 3 event processors and each gets a reader from the mock. However, since we pass only 1 reader to the mock sequence answer, two event processors are created without a reader.. 
hence they get NPE during shutdown. 

**Suggestions for an improvement**
Fix the test issue. Also add preconditions on eventprocessor cell contructor.

**Comment by tkaitchuck** [comment]
I also saw this:
```
io.pravega.controller.eventProcessor.impl.EventProcessorTest > testInitialize FAILED
    java.lang.IllegalStateException: Expected the service EventProcessorGroup[readerGroup] to be RUNNING, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
        at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:266)
        at com.google.common.util.concurrent.AbstractIdleService.awaitRunning(AbstractIdleService.java:175)
        at io.pravega.controller.eventProcessor.impl.EventProcessorTest.testInitialize(EventProcessorTest.java:391)
        Caused by:
        java.lang.IllegalStateException: Expected the service Delegate [FAILED] to be RUNNING, but the service has FAILED
            Caused by:
            java.lang.NullPointerException
```

**Comment by shiveshr** [comment]
merged
