### ISSUE TITLE
Occasional build failure

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1713]
**Problem description**
```
io.pravega.controller.eventProcessor.impl.EventProcessorTest > testInitialize FAILED
    java.lang.IllegalStateException: Expected the service EventProcessorGroup[readerGroup] to be RUNNING, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
        at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:266)
        at com.google.common.util.concurrent.AbstractIdleService.awaitRunning(AbstractIdleService.java:175)
        at io.pravega.controller.eventProcessor.impl.EventProcessorTest.testInitialize(EventProcessorTest.java:391)
        Caused by:
        java.lang.IllegalStateException: Expected the service Delegate [FAILED] to be RUNNING, but the service has FAILED
            Caused by:
            java.lang.NullPointerException
```

**Problem location**
io.pravega.controller.eventProcessor.impl.EventProcessorTest

**Suggestions for an improvement**
Debug issue and prevent test failure.

**Comment by fpj** [comment]
I don't think we are seeing this test failure any longer, so I'm closing this issue.
