### ISSUE TITLE
Can not write data to standalone pravega launch from docker image

### ISSUE THREAD

**Issue by wangzhizheng** [pravega/pravega#1722]
**Problem description**
I started the docker pravega image with command "docker run -p 9090:9090 pravega/pravega standalone"
It looks fine from stdout But I can not write data to it from pravega client
When I write the data, I have the error

`[main] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[addrs=[/10.32.2.30:9090], attrs={}]]
[main] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Fetching endpoint for segment examples/wangzzStream/0
[grpc-default-executor-0] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=0.0.0.0, port=12345) for examples/wangzzStream/0
[nioEventLoopGroup-5-1] INFO io.pravega.client.netty.impl.ClientConnectionInboundHandler - Connection established ChannelHandlerContext(ClientConnectionInboundHandler#0, [id: 0x82786cfb]) 
[nioEventLoopGroup-5-1] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection for segment examples/wangzzStream/0 failed due to: null
[main] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Fetching endpoint for segment examples/wangzzStream/0
[grpc-default-executor-0] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=0.0.0.0, port=12345) for examples/wangzzStream/0
[nioEventLoopGroup-5-2] INFO io.pravega.client.netty.impl.ClientConnectionInboundHandler - Connection established ChannelHandlerContext(ClientConnectionInboundHandler#0, [id: 0xebcf6f03]) 
[clientInternal-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Fetching endpoint for segment examples/wangzzStream/0
[nioEventLoopGroup-5-2] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection for segment examples/wangzzStream/0 failed due to: null
[grpc-default-executor-0] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=0.0.0.0, port=12345) for examples/wangzzStream/0
[nioEventLoopGroup-5-3] INFO io.pravega.client.netty.impl.ClientConnectionInboundHandler - Connection established ChannelHandlerContext(ClientConnectionInboundHandler#0, [id: 0xb61f0c72]) 
[main] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Fetching endpoint for segment examples/wangzzStream/0
[nioEventLoopGroup-5-3] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection for segment examples/wangzzStream/0 failed due to: null
[clientInternal-1] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - 22c2da42-25a5-43ca-93f8-d87b5102cadd Failed to connect: 
java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /0.0.0.0:12345
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniRun(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /0.0.0.0:12345
	at io.pravega.common.concurrent.FutureHelpers.getAndHandleExceptions(FutureHelpers.java:166)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl.setupConnection(SegmentOutputStreamImpl.java:407)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl.lambda$failConnection$3(SegmentOutputStreamImpl.java:467)
	... 10 more
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /0.0.0.0:12345
	at io.pravega.client.netty.impl.ConnectionFactoryImpl$2.operationComplete(ConnectionFactoryImpl.java:125)
	at io.pravega.client.netty.impl.ConnectionFactoryImpl$2.operationComplete(ConnectionFactoryImpl.java:119)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:630)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	... 1 more
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /0.0.0.0:12345
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	... 7 more
[grpc-default-executor-0] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=0.0.0.0, port=12345) for examples/wangzzStream/0
[nioEventLoopGroup-5-4] INFO io.pravega.client.netty.impl.ClientConnectionInboundHandler - Connection established ChannelHandlerContext(ClientConnectionInboundHandler#0, [id: 0xdb8dbb2f]) 
[clientInternal-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Fetching endpoint for segment examples/wangzzStream/0
[nioEventLoopGroup-5-4] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection for segment examples/wangzzStream/0 failed due to: null
[grpc-default-executor-0] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=0.0.0.0, port=12345) for examples/wangzzStream/0
[nioEventLoopGroup-5-5] INFO io.pravega.client.netty.impl.ClientConnectionInboundHandler - Connection established ChannelHandlerContext(ClientConnectionInboundHandler#0, [id: 0x4e6afb88]) 
[clientInternal-1] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - 22c2da42-25a5-43ca-93f8-d87b5102cadd Failed to connect: 
[nioEventLoopGroup-5-5] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection for segment examples/wangzzStream/0 failed due to: null
[main] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Fetching endpoint for segment examples/wangzzStream/0
java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /0.0.0.0:12345
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniRun(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /0.0.0.0:12345
	at io.pravega.common.concurrent.FutureHelpers.getAndHandleExceptions(FutureHelpers.java:166)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl.setupConnection(SegmentOutputStreamImpl.java:407)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl.lambda$failConnection$3(SegmentOutputStreamImpl.java:467)
	... 10 more
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /0.0.0.0:12345
	at io.pravega.client.netty.impl.ConnectionFactoryImpl$2.operationComplete(ConnectionFactoryImpl.java:125)
	at io.pravega.client.netty.impl.ConnectionFactoryImpl$2.operationComplete(ConnectionFactoryImpl.java:119)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:630)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	... 1 more
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /0.0.0.0:12345
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	... 7 more`

From docker output, there are some message like these
`2017-08-10 20:09:25,217 176829 [grpc-default-executor-2] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getCurrentSegments called for stream examples/wangzzStream.
2017-08-10 20:09:25,253 176865 [grpc-default-executor-2] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getURI called for segment examples/wangzzStream/0.
2017-08-10 20:09:26,402 178014 [grpc-default-executor-2] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getURI called for segment examples/wangzzStream/0.
2017-08-10 20:09:27,452 179064 [grpc-default-executor-2] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getURI called for segment examples/wangzzStream/0.
2017-08-10 20:09:28,499 180111 [grpc-default-executor-2] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getURI called for segment examples/wangzzStream/0.
2017-08-10 20:09:29,552 181164 [grpc-default-executor-2] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getURI called for segment examples/wangzzStream/0.`

it looks getURI return the 0.0.0.0 for connecting 0.0.0.0:12345 and the connection refused.

**Comment by jonny-miller** [comment]
You need to provide a `HOST_IP` environment variable that gives the externally accessible IP address of your host in order to run it this way, and also map the `12345` port from the host to the container.

`docker run -it -e HOST_IP=<ip> -p 9090:9090 -p 12345:12345 pravega/pravega:latest standalone`

This is described in the Running Pravega Locally docs:
https://github.com/pravega/pravega/blob/master/docs/deployment/run-local.md

**Comment by wangzhizheng** [comment]
Thank you @jonny-miller , it works for me
