### ISSUE TITLE
Pravega deployment works with only four containers

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#1754]
**Problem description**
1. Change the configuration `CONTAINER_COUNT` in `controller/src/main/resources/reference.conf` to 3.
2. Change the configuration `pravegaservice.containerCount` in `config\config.properties` to the same value. (This can also be set using `-Dpravegaservice.containerCount`).
3. Deploy this branch using AWS (other deployments also will follow the same path).

The segmentstores keep throwing exceptions. `ContainerNotFound` for creating any of the internal streams. The container id that is missing is 3. This represents the 4th container.
Here is the stacktrace:
```
2017-08-17 15:25:57,135 687692 [epollEventLoopGroup-3-29] ERROR i.p.s.s.h.h.PravegaRequestProcessor - Error (Segment = '_system/_abortStream/0', Operation = 'Create segment')
io.pravega.segmentstore.contracts.ContainerNotFoundException: [Container 3] Container Id does not exist..
        at io.pravega.segmentstore.server.store.StreamSegmentContainerRegistry.getContainer(StreamSegmentContainerRegistry.java:96)
        at io.pravega.segmentstore.server.store.StreamSegmentService.invoke(StreamSegmentService.java:161)
        at io.pravega.segmentstore.server.store.StreamSegmentService.createStreamSegment(StreamSegmentService.java:101)
        at io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor.createSegment(PravegaRequestProcessor.java:336)
        at io.pravega.shared.protocol.netty.DelegatingRequestProcessor.createSegment(DelegatingRequestProcessor.java:72)
        at io.pravega.shared.protocol.netty.WireCommands$CreateSegment.process(WireCommands.java:884)
        at io.pravega.segmentstore.server.host.handler.ServerConnectionInboundHandler.channelRead(ServerConnectionInboundHandler.java:47)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:748)
```

**Problem location**
Controlller/segmentstore startup.

**Suggestions for an improvement**
None.

**Comment by fpj** [comment]
> Change the configuration CONTAINER_COUNT in controller/src/main/resources/reference.conf to 3.

I think this is not the right place to change. According to the gradle config:
```
applicationDistribution.from('src/conf') {
        into "conf"
        rename "application.conf", "controller.conf"
    }
```

and the the config file under `src/conf` is this one:
https://github.com/pravega/pravega/blob/master/controller/src/conf/application.conf

in which case, we should set the environment variable `CONTAINER_COUNT`:

```
containerCount = ${CONTAINER_COUNT}
```

does it make sense?

**Comment by arvindkandhare** [comment]
This happens only on the AWS deployment. The script picks up this number from the deployment branch and not the built binaries. The right way to do it is to change `config.properties` on the machine and branch where we are running the terraform script from.
