### ISSUE TITLE
Sporadic build error: HDFSIntegrationTest > testEndToEnd 

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#1757]
**Problem description**

```
java.util.concurrent.ExecutionException: io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment 'Segment_7#transaction.3d53c241b89a462cbc14a45cc1f335b8'] The StreamSegment does not exist.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.checkReads(StreamSegmentStoreTestBase.java:632)
	at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.testEndToEndWithFencing(StreamSegmentStoreTestBase.java:339)
Caused by: io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment 'Segment_7#transaction.3d53c241b89a462cbc14a45cc1f335b8'] The StreamSegment does not exist.
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSExceptionHelpers.convertException(HDFSExceptionHelpers.java:41)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.openRead(HDFSStorage.java:230)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.openHandle(RollingStorage.java:648)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.openRead(RollingStorage.java:124)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$openRead$7(AsyncStorageWrapper.java:130)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.execute(AsyncStorageWrapper.java:221)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$supplyAsync$13(AsyncStorageWrapper.java:181)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
Caused by: java.io.FileNotFoundException: Segment_7#transaction.3d53c241b89a462cbc14a45cc1f335b8
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSExceptionHelpers.segmentNotExistsException(HDFSExceptionHelpers.java:68)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.findStatusForSegment(HDFSStorage.java:546)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.openRead(HDFSStorage.java:226)
	... 13 more


```

**Problem location**
Unit test

**Suggestions for an improvement**

**Comment by ManishKumarKeshri** [comment]
On running HDFSIntegrationTest.TestEndToEnd, once in like 600 or 700 times, similar issue arises at the same location.
Attached a snippet of the log here:
```
java.util.concurrent.ExecutionException: java.util.concurrent.CompletionException: org.apache.hadoop.hdfs.BlockMissingException: Could not obtain block: BP-1554706414-10.0.2.15-1572730324624:blk_1073741862_1221 file=/Segment_0$header_sealed

        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
        at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.testEndToEnd(StreamSegmentStoreTestBase.java:280)
        at sun.reflect.GeneratedMethodAccessor144.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
        at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:67)
        at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
        at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.util.concurrent.CompletionException: org.apache.hadoop.hdfs.BlockMissingException: Could not obtain block: BP-1554706414-10.0.2.15-1572730324624:blk_1073741862_1221 file=/Segment_0$header_sealed
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:186)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1590)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
        at java.util.concurrent.FutureTask.run(FutureTask.java)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```
