### ISSUE TITLE
Readers of a dynamic scale stream fail with RetriesExhaustedException

### ISSUE THREAD

**Issue by vroy** [pravega/pravega#1767]
**Problem description**

We have a "longevity" test that runs 3 clients and 3 writers against a stream. Each writer writes ~10 events per second and each events are 100 character strings.

> Scaling: Dynamic
> Retention: 50 GB
> Min Segments: 1
> Scaling Trigger: Incoming Event Rate
> Scaling Target Rate: 3 Events / second
> Scaling Factor: 2

After a couple of hours, the reader workers die with `io.pravega.common.util.RetriesExhaustedException`.

We have another test that is configured the same way except that it uses a static stream with 3 segments and we never see this issue.

Attached ([retries-exhausted-with-scale-client.zip](https://github.com/pravega/pravega/files/1239741/retries-exhausted-with-scale-client.zip)) are all of the relevant logs that I could gather surrounding this issue has it is happening in our environment.

**Comment by tkaitchuck** [comment]
I think #1764 should help with this on the client read side. I'll have to look into what is going on on the server a bit more. It looks as if the segment is being unexpectedly sealed for some reason.

**Comment by vroy** [comment]
#1764 looks promising so far. I built that branch last night and it has been running for 13 hours so far with no failures as opposed to the usual 2 to 6 hours before seeing a failure.

**Comment by vroy** [comment]
Talked too soon. It failed with:

```
java.lang.RuntimeException: io.grpc.StatusRuntimeException: UNAVAILABLE
	at io.pravega.common.concurrent.FutureHelpers.getAndHandleExceptions(FutureHelpers.java:181)
	at io.pravega.client.stream.impl.ReaderGroupStateManager.handleEndOfSegment(ReaderGroupStateManager.java:156)
	at io.pravega.client.stream.impl.EventStreamReaderImpl.handleEndOfSegment(EventStreamReaderImpl.java:196)
	at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:96)
	at com.emc.nautilus.pravega.taskexecutor.workers.readers.PravegaReader.start(PravegaReader.java:78)
	at com.emc.nautilus.pravega.taskexecutor.workers.readers.ReaderWorkerManager.lambda$start$0(ReaderWorkerManager.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE
	at io.grpc.Status.asRuntimeException(Status.java:543)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
	... 3 more
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	... 1 more
```

Should I file a separate bug for this one?

**Comment by vroy** [comment]
I had filed #1670 for that same error.

**Comment by vroy** [comment]
Going to close this. I have not seen this specific error since #1764 was merged.
