### ISSUE TITLE
Txn segment seal isn't idempotent in PravegaRequestProcessor

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1772]
**Problem description**
To commit a txn, we first seal the txn segments and next we merge the segments into the corresponding parent segments. The problem we observed in the way this is being processed is the following.

The service receives a request to commit a transaction while stopping a container. A segment of the txn is successfully sealed, but it errors on the merge because the container is gone. After that point, the controller keeps trying to complete the commit unsuccessfully as the requests keep failing on the segment sealed.

*Detail*:
From a system test run:

1- The service catches a signal indicating that it should stop. This is correct as we are simulating a server going down (not crashing).

```
2017-08-21 11:43:33,584 139103 [Thread-1] INFO  i.p.s.server.host.ServiceStarter - Caught interrupt signal...
```

2- We next get a request to commit a transaction
```
2017-08-21 11:43:33,614 139133 [epollEventLoopGroup-3-7] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Processing request: WireCommands.CommitTransaction(type=COMMIT_TRANSACTION, requestId=5128,
 segment=testMultiReaderWriterTxnScope49076720/testMultiReaderWriterTxnStream/3, txid=a6700241-1bcd-49c3-9e22-022bde8236eb)
```

3- As part of committing, we first seal the txn segment, which makes sense, that's what we should do in general.

```
2017-08-21 11:43:33,614 139133 [epollEventLoopGroup-3-7] DEBUG i.p.s.s.c.StreamSegmentContainer - SegmentContainer[1]: sealStreamSegment [testMultiReaderWriterTxnScope49076720/testMultiReaderWriterTx
nStream/3#transaction.a67002411bcd49c39e22022bde8236eb]
```

4- I observe the segment container stopping.

```
2017-08-21 11:43:33,642 139161 [Thread-1] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[1]: Stopping.
```
5- When merging the segment, we get an error that the container doesn't exist, though
```
2017-08-21 11:43:33,658 139177 [segment-store-40] ERROR i.p.s.s.h.h.PravegaRequestProcessor - Error (Segment = 'testMultiReaderWriterTxnScope49076720/testMultiReaderWriterTxnStream/3#transaction.a670
02411bcd49c39e22022bde8236eb', Operation = 'Commit transaction')
io.pravega.segmentstore.contracts.ContainerNotFoundException: [Container 1] Container Id does not exist..
        at io.pravega.segmentstore.server.store.StreamSegmentContainerRegistry.getContainer(StreamSegmentContainerRegistry.java:96)
        at io.pravega.segmentstore.server.store.StreamSegmentService.invoke(StreamSegmentService.java:161)
        at io.pravega.segmentstore.server.store.StreamSegmentService.mergeTransaction(StreamSegmentService.java:118)
        at io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor.lambda$commitTransaction$20(PravegaRequestProcessor.java:417)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at io.pravega.common.function.CallbackHelpers.invokeSafely(CallbackHelpers.java:34)
        at io.pravega.segmentstore.server.logs.operations.CompletableOperation.complete(CompletableOperation.java:85)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at io.pravega.segmentstore.server.logs.OperationProcessor$QueueProcessingState.commit(OperationProcessor.java:501)
        at io.pravega.segmentstore.server.logs.DataFrameBuilder.lambda$handleDataFrameComplete$0(DataFrameBuilder.java:186)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)2

```

6- From this point onwards, the controller keeps trying to commit this txn unsuccessfully.
```
2017-08-21 11:49:31,014 1283211 [epollEventLoopGroup-2-4] DEBUG i.p.c.n.i.ClientConnectionInboundHandler - 172.16.19.13 processing reply: WireCommands.SegmentIsSealed(type=SEGMENT_IS_SEALED, requestI
d=5655, segment=testMultiReaderWriterTxnScope49076720/testMultiReaderWriterTxnStream/3#transaction.a67002411bcd49c39e22022bde8236eb)

```
**Problem location**
`PravegaRequestProcessor`,  Segment store API.

**Suggestions for an improvement**
Change `PravegaRequestProcessor.commitTransaction` so that sealing the txn segment is idempotent.

**Comment by fpj** [comment]
From @andreipaduroiu:

Discussed offline:
- The SSS is whatever implements `StreamSegmentService`. It exposes an API and the PravegaRequestProcessor and AppendProcessor use it.
- The SSS treats txns and segments about the same, and it is best not to add any txn-specific code in there for isolation and to avoid unnecessary complexity.
- I propose to change `PravegaRequestProcessor.commitTransaction` so that, when it commits a txn, it ignores the StreamSegmentSealedException if it encounters one during the Seal part.
