### ISSUE TITLE
Writer failed with Connection not yet established.

### ISSUE THREAD

**Issue by vroy** [pravega/pravega#1785]
**Problem description**

We have observed a writer die with `IllegalStateException: 172.16.33.13 Connection not yet established.` after a few hours of running and encountering a "Connection reset by peer" error. No servers were restarted and this appeared to be a minor network blip as the other writers continued on.

This might 

```
2017-08-24 11:24:57,462 57951064 [epollEventLoopGroup-2-1] ERROR i.p.s.p.n.ExceptionLoggingHandler - Uncaught exception on connection 172.16.33.13
io.netty.channel.unix.Errors$NativeIoException: syscall:read(...)() failed: Connection reset by peer
        at io.netty.channel.unix.FileDescriptor.readAddress(...)(Unknown Source)
2017-08-24 11:24:57,463 57951065 [epollEventLoopGroup-2-1] WARN  i.p.c.s.i.SegmentOutputStreamImpl - Connection for segment hulk/smallScale/563 failed due to: io.netty.channel.unix.Errors$NativeIoException: syscal
l:read(...)() failed: Connection reset by peer
2017-08-24 11:24:57,463 57951065 [epollEventLoopGroup-2-1] WARN  i.p.c.s.i.SegmentOutputStreamImpl - Connection for segment hulk/smallScale/563 failed due to: null
2017-08-24 11:24:57,463 57951065 [clientInternal-2] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Fetching endpoint for segment hulk/smallScale/563
2017-08-24 11:24:57,465 57951067 [pool-4-thread-1] ERROR c.e.n.p.t.w.writers.PravegaWriter - Writer finished with Error
java.lang.IllegalStateException: 172.16.33.13 Connection not yet established.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
        at io.pravega.client.netty.impl.ClientConnectionInboundHandler.getChannel(ClientConnectionInboundHandler.java:159)
        at io.pravega.client.netty.impl.ClientConnectionInboundHandler.send(ClientConnectionInboundHandler.java:114)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl.write(SegmentOutputStreamImpl.java:382)
        at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEventInternal(EventStreamWriterImpl.java:126)
        at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEvent(EventStreamWriterImpl.java:110)
        at com.emc.nautilus.pravega.taskexecutor.workers.writers.PravegaWriter.writeEvent(PravegaWriter.java:248)
        at com.emc.nautilus.pravega.taskexecutor.workers.writers.PravegaWriter.start(PravegaWriter.java:157)
        at com.emc.nautilus.pravega.taskexecutor.workers.writers.WriterWorkerManager.lambda$start$0(WriterWorkerManager.java:121)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

This includes all of the controller, segmentstore and client logs: 
[connection-not-yet-established.zip](https://github.com/pravega/pravega/files/1249076/connection-not-yet-established.zip)

**Suggestions for an improvement**

It does not appear to have been retried. I think that connection errors such as connection reset by peer should be retried.

**Comment by fpj** [comment]
Correct, when invoking send, it expects a `ConnectionFailedException`, in which case it reconnects. `IllegalStateException` is just propagated up. The expectation is that at that point the connection is already established.

**Comment by tkaitchuck** [comment]
The problem is the send call already called getConnection and so it still has a reference to the old connection. THe "Not yet established" is misleading, it was established it just failed.

The solution is simple; it needs to throw ConnectionFailedException rather than IllegalStateException.
