### ISSUE TITLE
Suspicious warnings in ControllerImplTest

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1788]
**Problem description**
Observed the following output in Jenkins:

```
13:40:56 io.pravega.client.stream.impl.ControllerImplTest > testKeepAlive STANDARD_ERROR
13:40:56     Aug 24, 2017 1:40:56 PM io.grpc.netty.NettyClientHandler$1 onGoAwayReceived
13:40:56     WARNING: Received GOAWAY with ENHANCE_YOUR_CALM. Debug data: {1}
13:40:56     Aug 24, 2017 1:40:56 PM io.grpc.internal.AtomicBackoff$State backoff
13:40:56     WARNING: Increased keepalive time nanos to 20,000,000,000
13:41:36 
13:41:36 io.pravega.client.stream.impl.ControllerImplTest > testUpdateStream STANDARD_ERROR
13:41:36     Aug 24, 2017 1:41:36 PM io.grpc.internal.SerializingExecutor run
13:41:36     SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2@22c5e545
13:41:36     java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
13:41:36     	at io.pravega.controller.stream.api.grpc.v1.Controller$UpdateStreamStatus$Status.getNumber(Controller.java:1826)
13:41:36     	at io.pravega.controller.stream.api.grpc.v1.Controller$UpdateStreamStatus$Builder.setStatus(Controller.java:2212)
13:41:36     	at io.pravega.client.stream.impl.ControllerImplTest$1.updateStream(ControllerImplTest.java:203)
13:41:36     	at io.pravega.controller.stream.api.grpc.v1.ControllerServiceGrpc$MethodHandlers.invoke(ControllerServiceGrpc.java:1113)
13:41:36     	at io.grpc.stub.ServerCalls$1$1.onHalfClose(ServerCalls.java:148)
13:41:36     	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:267)
13:41:36     	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2.runInContext(ServerImpl.java:573)
13:41:36     	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
13:41:36     	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
13:41:36     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
13:41:36     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
13:41:36     	at java.lang.Thread.run(Thread.java:745)
13:41:36 
```

**Problem location**
Client, Controller implementation.

**Suggestions for an improvement**
Investigate whether this is an issue.

**Comment by shrids** [comment]
Closing this issue as the fix for this is #1901
