### ISSUE TITLE
ReadWithAutoScaleTest failure

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1793]
**Problem description**
We observed a failure of `ReadWithAutoScaleTest` due to the following:

1- Creating txns fails because of this exception

```
2017-08-25 19:51:33,582 13453 [ForkJoinPool.commonPool-worker-1] WARN  i.p.t.system.ReadWithAutoScaleTest - test exception writing events in a transaction.
java.lang.RuntimeException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: INTERNAL: io.pravega.controller.task.Stream.StreamTransactionMetadataTasks not yet ready
    at io.pravega.common.concurrent.FutureHelpers.getAndHandleExceptions(FutureHelpers.java:182)
    at io.pravega.client.stream.impl.EventStreamWriterImpl.beginTxn(EventStreamWriterImpl.java:305)
    at io.pravega.test.system.ReadWithAutoScaleTest.createTransaction(ReadWithAutoScaleTest.java:280)
    at io.pravega.test.system.ReadWithAutoScaleTest.lambda$null$7(ReadWithAutoScaleTest.java:260)
    at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:194)
    at io.pravega.test.system.ReadWithAutoScaleTest.lambda$startNewTxnWriter$8(ReadWithAutoScaleTest.java:260)
    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: INTERNAL: io.pravega.controller.task.Stream.StreamTransactionMetadataTasks not yet ready
    at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$5(Retry.java:266)
    at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
    at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
    at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
    at io.pravega.client.stream.impl.ControllerImpl$RPCAsyncCallback.onError(ControllerImpl.java:826)
    at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
    at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
    at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: INTERNAL: io.pravega.controller.task.Stream.StreamTransactionMetadataTasks not yet ready
    at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
    at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
    at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
    at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:899)
    ... 14 common frames omitted
Caused by: io.grpc.StatusRuntimeException: INTERNAL: io.pravega.controller.task.Stream.StreamTransactionMetadataTasks not yet ready
    at io.grpc.Status.asRuntimeException(Status.java:543)
    ... 11 common frames omitted
```

b. if you note the message leading the stack trace, it is the same printed here:

```
               } catch (Throwable e) {
                    log.warn("test exception writing events in a transaction.", e);
                    break;
                }
```

which causes the writer loop to break. there were precisely 6 of these messages in the logs, which indicate that all writers stopped writing after throwing this exception.

c. as such, the scaling didn’t happen and the test case failed.

**Problem location**
System tests.

**Suggestions for an improvement**
Such scenarios with the controller not being available could be temporary and we don't need to fail immediately upon not being able to reach the controller. Note that this test case extends `AbstractScaleTests` which changes the retry attempts value to 1, so we aren't really retrying.

**Comment by fpj** [comment]
This issue is stale, closing it for now.
