### ISSUE TITLE
DataLogNotAvailableException: Unable to create new BookKeeper Ledger

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1830]
**Problem description**
While running the system tests we are seeing:
```
2017-08-27 09:17:29,178 140168399 [segment-store-49] ERROR i.p.s.s.i.bookkeeper.BookKeeperLog - {}: Rollover failure; log may be unusable.
io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to create new BookKeeper Ledger.
        at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.create(Ledgers.java:52)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.rollover(BookKeeperLog.java:688)
        at io.pravega.common.concurrent.SequentialAsyncProcessor.lambda$runAsync$0(SequentialAsyncProcessor.java:72)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: null
        at org.apache.bookkeeper.client.BKException.create(BKException.java:58)
        at org.apache.bookkeeper.client.BookKeeper.createLedger(BookKeeper.java:556)
        at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.lambda$create$0(Ledgers.java:45)
        at io.pravega.common.Exceptions.handleInterrupted(Exceptions.java:70)
        at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.create(Ledgers.java:44)
        ... 9 common frames omitted
2017-08-27 09:17:29,178 140168399 [segment-store-49] ERROR o.a.b.client.LedgerCreateOp - Not enough bookies to create ledger
2017-08-27 09:17:29,178 140168399 [segment-store-49] ERROR o.a.bookkeeper.client.BookKeeper - Error while creating ledger : -6
2017-08-27 09:17:29,178 140168399 [segment-store-49] ERROR i.p.s.s.i.bookkeeper.BookKeeperLog - {}: Rollover failure; log may be unusable.
io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to create new BookKeeper Ledger.
        at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.create(Ledgers.java:52)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.rollover(BookKeeperLog.java:688)
        at io.pravega.common.concurrent.SequentialAsyncProcessor.lambda$runAsync$0(SequentialAsyncProcessor.java:72)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: null
        at org.apache.bookkeeper.client.BKException.create(BKException.java:58)
        at org.apache.bookkeeper.client.BookKeeper.createLedger(BookKeeper.java:556)
        at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.lambda$create$0(Ledgers.java:45)
        at io.pravega.common.Exceptions.handleInterrupted(Exceptions.java:70)
        at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.create(Ledgers.java:44)
        ... 9 common frames omitted
```

**Problem location**
SSS

**Suggestions for an improvement**
We need to create a test case to repro this.

**Comment by tkaitchuck** [comment]
More info https://emcnautilus.slack.com/archives/C3ZFFL5SM/p1504202094000195?thread_ts=1504180538.000312&channel=C3ZFFL5SM

**Comment by andreipaduroiu** [comment]
This was due to not enough bookies being available for the operation. Not much that can be done in our code.
