### ISSUE TITLE
io.pravega.test.integration.ReadWriteTest fails with timeout

### ISSUE THREAD

**Issue by giorgio-v** [pravega/pravega#1864]
**Problem description**
I’m seeing a failing test on the `master` branch:
```
io.pravega.test.integration.ReadWriteTest > readWriteTest FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at io.pravega.test.integration.ReadWriteTest.readWriteTest(ReadWriteTest.java:174)
```

**Problem location**
See stack trace. Also, I‘ve noticed similar behaviour with `ZKTaskMetadataStoreTests`: the execution hangs there for a relatively long time and then goes on.

```
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1611
```

```
> java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```
**Suggestions for an improvement**
I suspect some kind of bad or rather incorrect setup on my machine. However, this suggests some improvements to the README file.

**Comment by fpj** [comment]
hey @giorgio-v , could you share logs so that we can try to debug, please? just share them here if that's ok.

**Comment by giorgio-v** [comment]
@fpj Here it is

https://gist.github.com/giorgio-v/ae05561e898dbede968caaf759d3e95d

**Comment by giorgio-v** [comment]
Any hints on this issue? I don’t know if I’m able to tackle this alone, but maybe with some help from you I can help in some way. Lemme know. :)

**Comment by tkaitchuck** [comment]
Is there an unusual network configuration? Perhaps running in some container with networking completely disabled? It seems strange for it to be unable to make a connection to localhost. Both the library and ZK are seeing similar errors.

**Comment by giorgio-v** [comment]
Ouch, seems I completely messed up my GitHub notifications. 😬 I’ll get back to you ASAP. Sorry again.

**Comment by fpj** [comment]
That test fails for me occasionally when I'm on VPN. I haven't explored enough to tell, but it seems to be a networking issue at least for me.

**Comment by giorgio-v** [comment]
@tkaitchuck `startServer` breaks with:
```
2018-01-02 21:12:04,411 249  [main] ERROR i.p.s.server.host.ServiceStarter - Could not create a Service with default config, Aborting.
java.io.FileNotFoundException: config.properties (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at io.pravega.segmentstore.server.store.ServiceBuilderConfig$Builder.include(ServiceBuilderConfig.java:128)
        at io.pravega.segmentstore.server.host.ServiceStarter.main(ServiceStarter.java:212)
:test:integration:startServer FAILED
```

I’ve tried hardcoding the properties file located in `./config/config.properties`, but it assumes an already running instance of ZooKeeper. I’m not sure the two problems (assuming starting the server in this way is correct / supported) are related.

**Comment by fpj** [comment]
We haven't been able to reproduce it. I have just run it on a Mac:

```
io.pravega.test.integration.endtoendtest.EndToEndReaderGroupTest > testMultiScopeReaderGroup PASSED

io.pravega.test.integration.endtoendtest.EndToEndReaderGroupTest > testGenerateStreamCuts PASSED

io.pravega.test.integration.endtoendtest.EndToEndReaderGroupTest > testReaderOffline PASSED

io.pravega.test.integration.endtoendtest.EndToEndReaderGroupTest > testGenerateStreamCutsWithScaling PASSED

io.pravega.test.integration.endtoendtest.EndToEndReaderGroupTest > testReaderOfflineWithSilentCheckpoint PASSED
```

If this manifests again, please reopen the issue.
