### ISSUE TITLE
Test failure testAppendTransientZooKeeperFailure

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1951]
**Problem description**
Observed test failure with the following error:

```
java.lang.AssertionError: Unexpected sequence number. expected:<55834574848> but was:<51539607570>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at io.pravega.segmentstore.storage.DurableDataLogTestBase.verifyReads(DurableDataLogTestBase.java:377)
	at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogTests.testAppendTransientZooKeeperFailure(BookKeeperLogTests.java:339)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Problem location**
Segment store, BookKeeper log tests.

**Suggestions for an improvement**
Logs for the test case failure.
[testAppendTransientZooKeeperFailure.txt](https://github.com/pravega/pravega/files/1368667/testAppendTransientZooKeeperFailure.txt)

**Comment by andreipaduroiu** [comment]
This hasn't happened since. If it does, we should reopen this.
