### ISSUE TITLE
Error while creating a docker based Bookkeeper cluster with Bridged networking mode.

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#1955]
**Problem description**
Observing the following error in the bookkeeper node while trying to create a 3 node instance of bk.
https://gist.github.com/shrids/83a482b4a5902ef89d21eb6c5060bdb1

The hosts ips on which the bk docker images was is deployed range between 172.16.20.21 to 172.16.20.25.

```
2017-10-11 04:56:48,131 - ERROR - [main:Bookie@391] - Couldn't access cookie in zookeeper
org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /pravega/pravega-cluster/bookkeeper/ledgers/cookies/172.17.0.2:3181
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
```
Note: 172.17.0.2 is not part of the cluster.

**Problem location**
Bookkeeper config/ Docker image.

**Suggestions for an improvement**
Fix the issue as this will enable us to deploy a multi bk instance deployment with pravega.

**Comment by shrids** [comment]
Bookeeper uses `new InetSocketAddress(DNS.getDefaultHost(iface), conf.getBookiePort());` to update in zk during init phase Link: https://git.io/vdKws
This implies that we cannot use Bookkeeper docker image in bridged mode. i.e bookkeeper docker image runs only with "Host" networking mode.

**Comment by shrids** [comment]
Closing the issue based on the above comment.
