### ISSUE TITLE
Sporadic build failure: StreamMetadataTasksTest > updateStreamTest

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#1966]
**Problem description**
io.pravega.controller.task.Stream.StreamMetadataTasksTest > updateStreamTest FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
        at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
        at io.pravega.controller.task.Stream.StreamMetadataTasksTest.updateStreamTest(StreamMetadataTasksTest.java:230)

**Problem location**
StreamMetadataTasksTest

**Suggestions for an improvement**
Find the cause and fix the issue

**Comment by shiveshr** [comment]
Fixed with #1988
