### ISSUE TITLE
EndToEndWithScale integration test failure

### ISSUE THREAD

**Issue by Prabha-Veerubhotla** [pravega/pravega#1975]
**Problem description**
Travis Stack trace:
```
io.pravega.test.integration.endtoendtest.EndToEndWithScaleTest > testScale FAILED
    java.lang.AssertionError: expected:<txntest2> but was:<null>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.pravega.test.integration.endtoendtest.EndToEndWithScaleTest.testScale(EndToEndWithScaleTest.java:137)
```
**Problem location**
`io.pravega.test.integration.endtoendtest.EndToEndWithScaleTest.testScale`

**Suggestions for an improvement**

**Comment by shrids** [comment]
Closed with PR #1984
