### ISSUE TITLE
Flaky unit test: StreamMetadataTasksTest.updateStreamTest

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#1981]
```
io.pravega.controller.task.Stream.StreamMetadataTasksTest > updateStreamTest FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertFalse(Assert.java:64)
        at org.junit.Assert.assertFalse(Assert.java:74)
        at io.pravega.controller.task.Stream.StreamMetadataTasksTest.updateStreamTest(StreamMetadataTasksTest.java:228)
```

https://travis-ci.org/pravega/pravega/builds/289190649?utm_source=github_status&utm_medium=notification

**Comment by andreipaduroiu** [comment]
Duplicate of #1966
