### ISSUE TITLE
Flaky unit test: EndToEndWithScaleTest.testScale

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#1983]
```
io.pravega.test.integration.endtoendtest.EndToEndWithScaleTest > testScale FAILED
    java.lang.AssertionError: expected:<txntest2> but was:<null>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.pravega.test.integration.endtoendtest.EndToEndWithScaleTest.testScale(EndToEndWithScaleTest.java:137)
```

https://travis-ci.org/pravega/pravega/builds/289190660?utm_source=github_status&utm_medium=notification

**Comment by shrids** [comment]
Closed with PR #1984
