### ISSUE TITLE
Unable to create scope when using ECS as Tier2 storage

### ISSUE THREAD

**Issue by vijikarthi** [pravega/pravega#2015]
[logs.zip](https://github.com/pravega/pravega/files/1408454/logs.zip)
Unable to create "scope" from Nautilus UI having ECS configured as Tier2 storage. Attached both controller and segment store logs.

**Comment by fpj** [comment]
From the logs, it looks like BK is struggling based on the errors reported by the bk client, e.g., :

```
2017-10-23 17:21:25,591 70807 [main-EventThread] ERROR o.a.b.c.BookieWatcher$ReadOnlyBookieWatcher - Not able to read readonly bookies : 
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.bookkeeper.client.BookieWatcher$ReadOnlyBookieWatcher.processResult(BookieWatcher.java:399)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$28$1.processResult(ZooKeeperClient.java:1215)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:584)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)
```

or 

```
2017-10-23 17:21:45,382 90598 [segment-store-9] ERROR i.p.s.server.logs.DurableLog - DurableLog[2] Recovery FAILED.
io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to create new BookKeeper Ledger.
	at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.create(Ledgers.java:52)
	at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.initialize(BookKeeperLog.java:199)
	at io.pravega.segmentstore.server.logs.DurableLog.performRecovery(DurableLog.java:329)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: null
	at org.apache.bookkeeper.client.BKException.create(BKException.java:58)
	at org.apache.bookkeeper.client.BookKeeper.createLedger(BookKeeper.java:556)
	at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.lambda$create$0(Ledgers.java:45)
	at io.pravega.common.Exceptions.handleInterrupted(Exceptions.java:70)
	at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.create(Ledgers.java:44)
	... 10 common frames omitted
```

I'm seeing session expiration errors:
```
rg.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
	at org.apache.bookkeeper.client.BookieWatcher$ReadOnlyBookieWatcher.processResult(BookieWatcher.java:399)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$28$1.processResult(ZooKeeperClient.java:1215)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:584)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)
```

which could be an indication that zk is struggling and everyone else as a consequence.

**Comment by arvindkandhare** [comment]
This issue is not observed anymore. Closing this as no repro.
