### ISSUE TITLE
HDFSStorage potential corruption due to zombie processes

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#2052]
**Problem description**
Suppose we have two instances of the `HDFSStorage` for the same Container, one with epoch A and one with epoch B = A+1, each running on different hosts. Call them HA and HB. HA and HB should never run concurrently if we do a graceful container failover, however it is possible that they are both running at the same time, and writing to the same Segments, if HA's host loses connection to ZK/BK and still thinks it's the leader for the Container. In that case, both HA and HB will be competing to modify the same Segment, thus leading to issues. 

Most of these issues are resolved using the fencing mechanism built into `HDFSStorage`. However, there is a case that is not handled:
1. HA has an ongoing write to Segment X.
2. While the write is happening, HB open-writes Segment X, which causes the last file of X to be marked as read-only, and after that, its length is retrieved.
3. HA completes the write to Segment X, altering it (and increasing its length) after it was marked as read-only.
4. HB now has the wrong information about the state of Segment X, because one of the files has been modified behind the scenes without it knowing about.

This can lead to a number of issues. See **Example Problematic Stack Traces** below for observed issues.

**Problem location**
HDFSStorage.java

**Suggestions for an improvement**
This is due to the fact that setting permissions in HDFS is not atomic, or even serializable with other writes. They can happen concurrently and any permission change will not affect ongoing writes.

We need to make `FileSystemOperation.makeReadOnly` provide a guarantee that, after its successful completion, the target file will never change. This means it should be able to wait for ongoing writes, if possible. Note that due to the fact that there is no known server-side feature to support this, any solution may not work well in a general case, but it should solve the use case that the Segment Store is concerned about (on each Container there is a single StorageWriter accessing a Segment, and we can only solve this for two SegmentContainer zombie instances competing for the same Segment).
1. We introduce a new XAttr named "WritingInProgress"
2. During a write, we set this XAttr (to `true`) on the target file right before we are about to open the write stream, and clear it when we're done (whether successfully or not).
3. `makeReadOnly` will check for this XAttr's existence after it marks the file as read-only. If it's set, it will need to wait until it's cleared (or a timeout expires).

This should make`makeReadOnly` provide enough guarantees that the file will not change after it returns successfully and the rest of the HDFS fencing code in the SegmentStore should work as expected.

**Example Problematic Stack Traces**
```
java.util.concurrent.CompletionException: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.HadoopIllegalArgumentException): concat: source file /Segment_1000_3 is invalid or empty or underConstruction
	at org.apache.hadoop.hdfs.server.namenode.FSDirConcatOp.verifySrcFiles(FSDirConcatOp.java:160)
	at org.apache.hadoop.hdfs.server.namenode.FSDirConcatOp.concat(FSDirConcatOp.java:68)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.concat(FSNamesystem.java:1855)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.concat(NameNodeRpcServer.java:983)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.concat(ClientNamenodeProtocolServerSideTranslatorPB.java:579)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorageTest.testZombies(HDFSStorageTest.java:105)
Caused by: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.HadoopIllegalArgumentException): concat: source file /Segment_1000_3 is invalid or empty or underConstruction
	at org.apache.hadoop.hdfs.server.namenode.FSDirConcatOp.verifySrcFiles(FSDirConcatOp.java:160)
	at org.apache.hadoop.hdfs.server.namenode.FSDirConcatOp.concat(FSDirConcatOp.java:68)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.concat(FSNamesystem.java:1855)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.concat(NameNodeRpcServer.java:983)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.concat(ClientNamenodeProtocolServerSideTranslatorPB.java:579)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.hdfs.DistributedFileSystem.concat(DistributedFileSystem.java:676)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorageTest$FileSystemFixer.concat(HDFSStorageTest.java:217)
	at io.pravega.segmentstore.storage.impl.hdfs.FileSystemOperation.combine(FileSystemOperation.java:196)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.cleanup(OpenWriteOperation.java:140)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.fenceOut(OpenWriteOperation.java:123)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.call(OpenWriteOperation.java:68)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.call(OpenWriteOperation.java:24)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.lambda$supplyAsync$1(HDFSStorage.java:233)


java.util.concurrent.CompletionException: io.pravega.segmentstore.storage.impl.hdfs.SegmentFilesCorruptedException: Segment 'Segment' has invalid file 'hdfs://localhost:36964/Segment_1000_4'. Declared offset is '1000' but should be '2000'.
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorageTest.testZombies(HDFSStorageTest.java:110)
Caused by: io.pravega.segmentstore.storage.impl.hdfs.SegmentFilesCorruptedException: Segment 'Segment' has invalid file 'hdfs://localhost:36964/Segment_1000_4'. Declared offset is '1000' but should be '2000'.
	at io.pravega.segmentstore.storage.impl.hdfs.FileSystemOperation.findAll(FileSystemOperation.java:113)
	at io.pravega.segmentstore.storage.impl.hdfs.FileSystemOperation.checkForFenceOut(FileSystemOperation.java:133)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.fenceOut(OpenWriteOperation.java:103)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.call(OpenWriteOperation.java:68)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.call(OpenWriteOperation.java:24)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.lambda$supplyAsync$1(HDFSStorage.java:233)


java.util.concurrent.CompletionException: java.lang.AssertionError: New file list would not be contiguous. Combined file ends at offset 3000; Last file begins at 2000.
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorageTest.testZombies(HDFSStorageTest.java:110)
Caused by: java.lang.AssertionError: New file list would not be contiguous. Combined file ends at offset 3000; Last file begins at 2000.
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.cleanup(OpenWriteOperation.java:143)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.fenceOut(OpenWriteOperation.java:123)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.call(OpenWriteOperation.java:68)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.call(OpenWriteOperation.java:24)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.lambda$supplyAsync$1(HDFSStorage.java:233)
```

**Comment by fpj** [comment]
@andreipaduroiu thanks for the thorough investigation and explanation.

> HA completes the write to Segment X, altering it (and increasing its length) after it was marked as read-only.

This point doesn't make sense to me. I can understand the scenario in which HA issues a write concurrently with marking the file read-only, the write goes through, and the file is marked read-only after the write. The write being performed after the file is marked read-only sounds broken.

This point is important because there is a difference between the length being accurate after the confirmation that the file is read-only or being inaccurate.

> makeReadOnly will check for this XAttr's existence after it marks the file as read-only. If it's set, it will need to wait until it's cleared (or a timeout expires).

I think there is a chance that HB performs the XAttr's attribute check before HA actually sets it, which gives us the possibility of a race. How do we prevent that?

Also, having a timeout means that our promise can be broken in the presence of a slow system. Before we go down this route, I'd like to understand why the length is not accurate after setting the last file to read-only.

**Comment by tkaitchuck** [comment]
The model for which we based the HDFS implementation on was that there are no operations that offer strong consistency. As such this proposal doesn't solve the problem for the same reason it does not work now. 
The model for how to deal with weak consistency was to use the file time to contain the offset and the epoch. IE: <segmentName>-<startingOffset>-<epoch>
Then when a new host takes over it simply starts writing to a new file named for its starting offset.
If there is an old host still writing, it may write some redundant data but it is irrelevant. 

The implementation seems to have gone away from this plan and made the false assumption that it can somehow 'fence' the data being written so it can use the same file. This is never the case as there is no universal way in HDFS to do this. 

Instead of trying to correct this 'fencing' we should remove it, and use the appropriate naming scheme so that the ambiguity does not exist in the first place.

**Comment by andreipaduroiu** [comment]
> The implementation seems to have gone away from this plan and made the false assumption that it can somehow 'fence' the data being written so it can use the same file.

It doesn't reuse the file. It marks it as read-only and then it gets its length so it can compute the starting offset of the next file. If that (older) file's length changes afterwards due to a concurrent write finishing off, then the offsets will not match the sum of lengths before that.

There is, however, a way by which the file is indeed used. After a successful open-write (fencing), the Segment's files are auto-compacted. This means that empty files are deleted (except last one, since it was just created), and multiple files are concatenated into the first file, to avoid having an excessive number of smaller files sitting around.

> use the appropriate naming scheme so that the ambiguity does not exist in the first place.
We are using the naming scheme we originally agreed upon. But it gets very hairy in some cases. Suppose you have this, for segment "a" (this assumes no auto-compaction is done, to explain how the very very original proposal would've worked):
```
a_0_1 (read-only, length 100)
a_100_2 (read-only, length 0)
a_100_3 (read-only, length 50)
a_100_4 (read-write, variable length)
```
This gets very confusing. If you want to read byte 100, do you read from third or fourth file?

With auto-compaction still off, *and the changes proposed in this issue on* , we'd have this situation 
```
a_0_1 (read-only, length 100)
a_100_2 (read-only, length 0)
a_100_3 (read-only, length 50)
a_150_4 (read-write, variable length)
```
This makes it very clear where we want to read byte 101 (it's the third file).

With auto-compaction on (again, auto-compaction is already in the code), it looks like this:
```
a_0_1 (read-only, length 150)
a_150_4 (read-write, variable length)
```

**Comment by tkaitchuck** [comment]
> With auto-compaction still off, and the changes proposed in this issue on , we'd have this situation

Yes. If you waited long enough. But at the end of the day, how long to wait is just a heuristic that probably prevents the problem. If the host died while it was writing it will never unset the property, and as long a the property is still set you can't guarantee that some append won't happen just after your timeout. 

Where as, it the above case reading from the 4th file for the 100th byte is always correct. It just so happens it has the same content as the 3rd file at the same offset, but is of no relevance to anyone. 

I do however like the use of the attribute to know when there is no ambiguity. (IE: If when writing an attribute is set, and it is cleared on completion.) Then we can compact the files that don't have the attribute set. So in the worst case there is one file plus one for each previous time this segment had its host die mid-write.
