### ISSUE TITLE
ReadTest#testEventPointer fails in jenkins

### ISSUE THREAD

**Issue by Prabha-Veerubhotla** [pravega/pravega#2083]
**Problem description**
Test failure stack Trace
```
io.pravega.test.integration.ReadTest > testEventPointer FAILED
    org.junit.ComparisonFailure: expected:<Hello world 9[2]> but was:<Hello world 9[5]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.pravega.test.integration.ReadTest.testEventPointer(ReadTest.java:258)
```
**Problem location**
io.pravega.test.integration.ReadTest#testEventPointer 
**Suggestions for an improvement**

**Comment by shrids** [comment]
Similar to #2114 .
