### ISSUE TITLE
NPE in io.pravega.test.integration.ReadTest.testEventPointer

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#2140]
**Problem description**
we had an integration test failure with NPE with following stack
```
`java.lang.NullPointerException
    at io.pravega.client.segment.impl.SegmentOutputStreamImpl.write(SegmentOutputStreamImpl.java:433)
    at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEventInternal(EventStreamWriterImpl.java:127)
    at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEvent(EventStreamWriterImpl.java:105)
    at io.pravega.test.integration.ReadTest.testEventPointer(ReadTest.java:244)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
    at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.lang.Thread.run(Thread.java:745)`


```
**Problem location**
ReadTest.testEventPointer

**Suggestions for an improvement**
Fix the bug.
See if it is related to issue 2083 and 2114

**Comment by tkaitchuck** [comment]
This appears to be because in `ConnectionSetupComplete` the `connection` is accessed outside of the lock. Should be an easy fix.
