### ISSUE TITLE
ReaderCheckPointTest : Failure to read all events between 100 to 200 once the reader is reset to check point

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#2142]
**Problem description**
ReaderCheckpointTest fails with the following exception:
```
2017-11-29 07:46:16,556 12060 [main] ERROR i.p.t.system.SingleJUnitTestRunner - Error while executing the test
io.pravega.test.system.framework.TestFrameworkException: Exception while running test method: readerCheckpointTest
    at io.pravega.test.system.SingleJUnitTestRunner.runMethod(SingleJUnitTestRunner.java:49)
    at io.pravega.test.system.SingleJUnitTestRunner.execute(SingleJUnitTestRunner.java:57)
    at io.pravega.test.system.SingleJUnitTestRunner.main(SingleJUnitTestRunner.java:69)
Caused by: java.lang.AssertionError: Check for number of events: 200, 100, 68 expected:<100> but was:<68>
```
Details: 
1. The test writes event from 100 to 200
2. It reads them back successfully.(all events from 100 to 200)
3. The reader check point is reset to 100 checkpoint
4. Now the reader starts reading from event 100. This time it reads only 68 !!!

**Problem location**
Under Investigation:
- One possible reason is that the reader has a timeout of 30 seconds. If the reader is not able to read events for 30 seconds then the reader thread stops reading and exits.
- SSS performance

**Suggestions for an improvement**
[readerCheckpointTest_838.zip](https://github.com/pravega/pravega/files/1517145/readerCheckpointTest_838.zip)

**Comment by shrids** [comment]
Fixed as part of #2153
