### ISSUE TITLE
Integration Test failure: ReadTest.testEventPointer with ConnectionFailedException

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#2143]
**Problem description**
Build failure caused by ReadTest failure with CFE:

```
io.pravega.shared.protocol.netty.ConnectionFailedException`
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl$ResponseProcessor.connectionDropped(SegmentOutputStreamImpl.java:282)
	at io.pravega.client.netty.impl.ClientConnectionInboundHandler.channelUnregistered(ClientConnectionInboundHandler.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1337)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:835)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:771)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
```

**Problem location**
integration.ReadTest

**Suggestions for an improvement**
Fix the issue

**Comment by shiveshr** [comment]
full standard output
[issue2143.txt](https://github.com/pravega/pravega/files/1517185/issue2143.txt)

**Comment by tkaitchuck** [comment]
The exception is "Wrong host" (we could improve the logging a bit.) But did anything in the deployment change while the test was running? Maybe a container was moved from one host to another?

**Comment by shiveshr** [comment]
This is integration test and not system test. So there is one single host.

**Comment by tkaitchuck** [comment]
It the log above the are a number of failures to connect to the process. Did something go wrong with it's initialization? Perhaps a port conflict? Do we have logs of the SSS process?

**Comment by shiveshr** [comment]
I have attached all the logs from the standard output of this test. Thats all we have unfortunately.

**Comment by shrids** [comment]
The logs are truncated (Snippet from the test log)
```

at io.netty.channel.epoll.EpollEve
...[truncated 16100 chars]...
ultChannelPipeline.java:1326)
```
Will see if I can simulate it locally...

**Comment by shiveshr** [comment]
Stale issue. Closing
