### ISSUE TITLE
Controlller loses the host-container mapping

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2145]
**Problem description**
After a while stream creation fails with
```
2017-11-30 16:00:28,226 774963245 [controllerpool-43] WARN  i.p.c.s.r.r.StreamMetadataResourceImpl - createStream failed for : Dave/Test1
2017-11-30 16:00:33,946 774968965 [clientInternal-10] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Fetching endpoint for segment _system/_RGcommitStreamReaders/0, writerID: aafb3c13-9ab7-47e3-8c8f-c63424ff7ca7
2017-11-30 16:00:33,947 774968966 [clientInternal-10] WARN  i.p.c.s.i.SegmentOutputStreamImpl - aafb3c13-9ab7-47e3-8c8f-c63424ff7ca7 Failed to connect: 
java.util.concurrent.CompletionException: io.pravega.controller.store.host.HostStoreException: Could not find host for container id: 3
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
    at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961)
    at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
    at io.pravega.common.concurrent.Futures.lambda$delayedFuture$17(Futures.java:466)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.controller.store.host.HostStoreException: Could not find host for container id: 3
    at io.pravega.controller.store.host.ZKHostStore.getHostForContainer(ZKHostStore.java:112)
    at io.pravega.controller.store.host.ZKHostStore.getHostForSegment(ZKHostStore.java:124)
    at io.pravega.controller.server.SegmentHelper.getSegmentUri(SegmentHelper.java:44)
    at io.pravega.controller.server.ControllerService.getURI(ControllerService.java:228)
    at io.pravega.controller.server.eventProcessor.LocalController.getEndpointForSegment(LocalController.java:349)
    at io.pravega.client.segment.impl.SegmentOutputStreamImpl.lambda$null$4(SegmentOutputStreamImpl.java:520)
    at io.pravega.common.concurrent.Futures.lambda$delayedFuture$19(Futures.java:486)
    at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
    ... 10 common frames omitted
```

Looks like controller is losing host-container mapping which stops all the further operations. This situation is recovered when the controller is restarted.

**Problem location**
host-container mapping on controller.

**Suggestions for an improvement**

**Comment by shiveshr** [comment]
> java.util.concurrent.CompletionException: io.pravega.controller.store.host.HostStoreException: Could not find host for container id: 3
From my understanding, this can happen iff controller doesnt find any "alive" hosts to rebalance an orphaned container to. Which should only happen if all segment stores had crashed intermittently. 
And the moment a segment container comes online and controller detects it, it should rebalance and do the assignment.  

Do you have any more information than this?

**Comment by shiveshr** [comment]
Can this still be reproduced? Otherwise we are closing this.
