### ISSUE TITLE
System test: readerCheckpointTest failed

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#2152]
**Problem description**
We have observed a test failure in a run of the system tests in which the last event was not read after the second time we reset to a checkpoint in the test. Specifically, the readers did not read event 299, although it had been read during the previous reset to a checkpoint:

```
2017-12-02 21:48:28,399 83521 [main] ERROR i.p.t.s.f.TestFrameworkException - TestFramework Exception. Type: InternalError, Details: Exception while running test method: readerCheckpointTest
java.lang.AssertionError: Check for last event: 298, 300
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.pravega.test.system.ReaderCheckpointTest.verifyEvents(ReaderCheckpointTest.java:235)
        at io.pravega.test.system.ReaderCheckpointTest.readEventsAndVerify(ReaderCheckpointTest.java:217)
        at io.pravega.test.system.ReaderCheckpointTest.readerCheckpointTest(ReaderCheckpointTest.java:177)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

Attaching the logs for the test case.

[readercheckpointtest.txt](https://github.com/pravega/pravega/files/1524651/readercheckpointtest.txt)

**Problem location**
System tests, resetting to a checkpoint.

**Suggestions for an improvement**
Track and fix the bug.

**Comment by fpj** [comment]
My analysis so far.

Start to verify after resetting to checkpoint:

```
2017-12-02 21:48:26,262 81384 [Time-limited test] INFO  i.p.t.system.ReaderCheckpointTest - Read and Verify events between [100,300)
```

Last time we read event 299:

```
2017-12-02 21:48:24,085 79207 [readerCheckpointTest-reader-1] INFO  i.p.t.system.ReaderCheckpointTest - Read event 299
```

Relevant events of the segment:

```
2017-12-02 21:48:26,595 81717 [readerCheckpointTest-reader-2] TRACE i.p.c.stream.impl.ControllerImpl - ENTER getEndpointForSegment@6026135387243 [scope1732126059/checkPointTestStream/1].
2017-12-02 21:48:26,601 81723 [clientInternal-1] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Sending read request WireCommands.ReadSegment(type=READ_SEGMENT, segment=scope1732126059/checkPointTestStream/1, offset=0, suggestedLength=65536)
2017-12-02 21:48:26,601 81723 [epollEventLoopGroup-25-6] TRACE i.p.s.protocol.netty.CommandEncoder - Encoding message to send over the wire WireCommands.ReadSegment(type=READ_SEGMENT, segment=scope1732126059/checkPointTestStream/1, offset=0, suggestedLength=65536)
2017-12-02 21:48:26,601 81723 [clientInternal-1] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Sending read request WireCommands.ReadSegment(type=READ_SEGMENT, segment=scope1732126059/checkPointTestStream/1, offset=3560, suggestedLength=65536)
2017-12-02 21:48:26,601 81723 [epollEventLoopGroup-25-6] TRACE i.p.s.protocol.netty.CommandEncoder - Encoding message to send over the wire WireCommands.ReadSegment(type=READ_SEGMENT, segment=scope1732126059/checkPointTestStream/1, offset=3560, suggestedLength=65536)
2017-12-02 21:48:26,762 81884 [epollEventLoopGroup-25-6] TRACE i.p.s.protocol.netty.CommandDecoder - Decode a message on connection: 172.16.18.21/172.16.18.21:12345. Message was WireCommands.SegmentRead(type=SEGMENT_READ, segment=scope1732126059/checkPointTestStream/1, offset=0, atTail=true, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=9968 cap=9968])
2017-12-02 21:48:26,762 81884 [epollEventLoopGroup-25-6] DEBUG i.p.c.n.i.ClientConnectionInboundHandler - 172.16.18.21 processing reply: WireCommands.SegmentRead(type=SEGMENT_READ, segment=scope1732126059/checkPointTestStream/1, offset=0, atTail=true, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=9968 cap=9968])
2017-12-02 21:48:26,762 81884 [epollEventLoopGroup-25-6] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Received read result WireCommands.SegmentRead(type=SEGMENT_READ, segment=scope1732126059/checkPointTestStream/1, offset=0, atTail=true, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=9968 cap=9968])
2017-12-02 21:48:26,762 81884 [epollEventLoopGroup-25-6] TRACE i.p.s.protocol.netty.CommandDecoder - Decode a message on connection: 172.16.18.21/172.16.18.21:12345. Message was WireCommands.SegmentRead(type=SEGMENT_READ, segment=scope1732126059/checkPointTestStream/1, offset=3560, atTail=true, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=6408 cap=6408])
2017-12-02 21:48:26,762 81884 [epollEventLoopGroup-25-6] DEBUG i.p.c.n.i.ClientConnectionInboundHandler - 172.16.18.21 processing reply: WireCommands.SegmentRead(type=SEGMENT_READ, segment=scope1732126059/checkPointTestStream/1, offset=3560, atTail=true, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=6408 cap=6408])
2017-12-02 21:48:26,762 81884 [epollEventLoopGroup-25-6] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Received read result WireCommands.SegmentRead(type=SEGMENT_READ, segment=scope1732126059/checkPointTestStream/1, offset=3560, atTail=true, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=6408 cap=6408])
```

When readers started:
```
2017-12-02 21:48:26,480 81602 [readerCheckpointTest-reader-2] INFO  i.p.t.system.ReaderCheckpointTest - Reading events from scope1732126059/checkPointTestStream with readerId: reader-0
2017-12-02 21:48:26,766 81888 [readerCheckpointTest-reader-1] INFO  i.p.t.system.ReaderCheckpointTest - Reading events from scope1732126059/checkPointTestStream with readerId: reader-2
2017-12-02 21:48:26,864 81986 [readerCheckpointTest-reader-3] INFO  i.p.t.system.ReaderCheckpointTest - Reading events from scope1732126059/checkPointTestStream with readerId: reader-1
```

Last event was read at (only reader 0 read events):
```
2017-12-02 21:48:26,690 81812 [readerCheckpointTest-reader-2] INFO  i.p.t.system.ReaderCheckpointTest - Read event 295
```

I’m not sure why these requests to read data did not return event 299:
```
2017-12-02 21:48:26,762 81884 [epollEventLoopGroup-25-6] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Received read result WireCommands.SegmentRead(type=SEGMENT_READ, segment=scope1732126059/checkPointTestStream/1, offset=0, atTail=true, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=9968 cap=9968])
2017-12-02 21:48:26,762 81884 [epollEventLoopGroup-25-6] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Received read result WireCommands.SegmentRead(type=SEGMENT_READ, segment=scope1732126059/checkPointTestStream/1, offset=3560, atTail=true, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=6408 cap=6408])
```

**Comment by fpj** [comment]
Requests to read data from segment 1:

```
2017-12-02 21:48:26,601 81723 [clientInternal-1] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Sending read request WireCommands.ReadSegment(type=READ_SEGMENT, segment=scope1732126059/checkPointTestStream/1, offset=0, suggestedLength=65536)
2017-12-02 21:48:26,601 81723 [epollEventLoopGroup-25-6] TRACE i.p.s.protocol.netty.CommandEncoder - Encoding message to send over the wire WireCommands.ReadSegment(type=READ_SEGMENT, segment=scope1732126059/checkPointTestStream/1, offset=0, suggestedLength=65536)
2017-12-02 21:48:26,601 81723 [clientInternal-1] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Sending read request WireCommands.ReadSegment(type=READ_SEGMENT, segment=scope1732126059/checkPointTestStream/1, offset=3560, suggestedLength=65536)
2017-12-02 21:48:26,601 81723 [epollEventLoopGroup-25-6] TRACE i.p.s.protocol.netty.CommandEncoder - Encoding message to send over the wire WireCommands.ReadSegment(type=READ_SEGMENT, segment=scope1732126059/checkPointTestStream/1, offset=3560, suggestedLength=65536)
```

Events read during this phase of the test case:
```
2017-12-02 21:48:26,677 81799 [readerCheckpointTest-reader-2] INFO  i.p.t.system.ReaderCheckpointTest - Read event 106
…
2017-12-02 21:48:26,690 81812 [readerCheckpointTest-reader-2] INFO  i.p.t.system.ReaderCheckpointTest - Read event 295
```

The response to the read segment requests only come after those events are read and no further events are read by the readers, why?
```
2017-12-02 21:48:26,762 81884 [epollEventLoopGroup-25-6] TRACE i.p.s.protocol.netty.CommandDecoder - Decode a message on connection: 172.16.18.21/172.16.18.21:12345. Message was WireCommands.SegmentRead(type=SEGMENT_READ, segment=scope1732126059/checkPointTestStream/1, offset=0, atTail=true, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=9968 cap=9968])
2017-12-02 21:48:26,762 81884 [epollEventLoopGroup-25-6] DEBUG i.p.c.n.i.ClientConnectionInboundHandler - 172.16.18.21 processing reply: WireCommands.SegmentRead(type=SEGMENT_READ, segment=scope1732126059/checkPointTestStream/1, offset=0, atTail=true, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=9968 cap=9968])
2017-12-02 21:48:26,762 81884 [epollEventLoopGroup-25-6] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Received read result WireCommands.SegmentRead(type=SEGMENT_READ, segment=scope1732126059/checkPointTestStream/1, offset=0, atTail=true, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=9968 cap=9968])
2017-12-02 21:48:26,762 81884 [epollEventLoopGroup-25-6] TRACE i.p.s.protocol.netty.CommandDecoder - Decode a message on connection: 172.16.18.21/172.16.18.21:12345. Message was WireCommands.SegmentRead(type=SEGMENT_READ, segment=scope1732126059/checkPointTestStream/1, offset=3560, atTail=true, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=6408 cap=6408])
2017-12-02 21:48:26,762 81884 [epollEventLoopGroup-25-6] DEBUG i.p.c.n.i.ClientConnectionInboundHandler - 172.16.18.21 processing reply: WireCommands.SegmentRead(type=SEGMENT_READ, segment=scope1732126059/checkPointTestStream/1, offset=3560, atTail=true, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=6408 cap=6408])
2017-12-02 21:48:26,762 81884 [epollEventLoopGroup-25-6] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Received read result WireCommands.SegmentRead(type=SEGMENT_READ, segment=scope1732126059/checkPointTestStream/1, offset=3560, atTail=true, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=6408 cap=6408])
```

**Comment by shrids** [comment]
io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl@6d76aaae This was never able to read events as canReadWithoutBlocking() always returned false.
This caused the following events to not be read.
```
101, 102, 104, 108, 109, 112, 117, 119, 132, 137, 141, 142, 143, 145, 148, 149, 155, 156, 157, 158, 166, 171, 175, 176, 177, 179, 182, 183, 184, 186, 188, 189, 192, 193, 195, 199
```

**Comment by shrids** [comment]
On reading a checkpoint the test stop reading hence, the issue.

**Comment by tkaitchuck** [comment]
I have opened a separate issues for the redundant read call question:
https://github.com/pravega/pravega/issues/2154

do we need to keep this open?

**Comment by fpj** [comment]
OK, let's close this for now and reopen if needed.
