### ISSUE TITLE
outstandingRequest can be null in SegmentInputStreamImpl

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#2159]
**Problem description**
I don't understand how we guarantee that `outstandingRequest` is not null upon an invocation of:

```
read -> readEventData -> handleRequest
```

In fact, we have observed an NPE in the r0.1 branch, which might still be present in master:

```
java.lang.NullPointerException: null
    at io.pravega.client.segment.impl.SegmentInputStreamImpl.handleRequest(SegmentInputStreamImpl.java:160)
    at io.pravega.client.segment.impl.SegmentInputStreamImpl.readEventData(SegmentInputStreamImpl.java:148)
    at io.pravega.client.segment.impl.SegmentInputStreamImpl.read(SegmentInputStreamImpl.java:111) 
    at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:94) 
```

**Problem location**
Client, reader.

**Suggestions for an improvement**
Fix the NPE if it is there in master.

**Comment by fpj** [comment]
I've been able to repro this by changing `ReadTest`.
