### ISSUE TITLE
Scaling stopped working after a couple of days

### ISSUE THREAD

**Issue by glounder** [pravega/pravega#2163]
**Problem description**
We have a stream that stopped processing data after a couple of days.  The stream has scaled down to one segment, and that segment would get 1 event written once in a few minutes (while it has ca. 50 events/s thrown at it).

(Mind you, there is another stream with fixed scaling policy, and that other stream does not show any problems).
All pravega components report themselves healthy (none of them has failed).

All readers and writers are active.

These are the errors in segmentstore logs (there is only one SS in the cluster).

```
2017-11-30 14:51:13,408 151174581 [epollEventLoopGroup-3-12] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection: 
java.lang.IllegalStateException: Data from unexpected connection: 9bb6bc22-0852-4879-b509-9107afa16b1c.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:518)
	at io.pravega.segmentstore.server.host.handler.AppendProcessor.append(AppendProcessor.java:368)
	at io.pravega.shared.protocol.netty.Append.process(Append.java:49)
	at io.pravega.segmentstore.server.host.handler.ServerConnectionInboundHandler.channelRead(ServerConnectionInboundHandler.java:47)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:797)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
2017-11-30 14:51:13,409 151174582 [epollEventLoopGroup-3-7] INFO  i.p.s.s.h.handler.AppendProcessor - Received hello from connection: [id: 0x9ffa8793, L:/172.16.26.21:12345 - R:/172.16.26.21:41444]
2017-11-30 14:51:13,409 151174582 [epollEventLoopGroup-3-7] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: 7a7e70ac-4f08-4c2b-a232-9e736c4b41c5 on segment: hulk/smallScale/862
2017-11-30 14:51:13,409 151174582 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x6c8345c6, L:/172.16.26.21:12345] READ: [id: 0x0204b7e9, L:/172.16.26.21:12345 - R:/172.16.26.21:41572]
2017-11-30 14:51:13,409 151174582 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x6c8345c6, L:/172.16.26.21:12345] READ: [id: 0x608ef733, L:/172.16.26.21:12345 - R:/172.16.26.21:41574]
2017-11-30 14:51:13,409 151174582 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x6c8345c6, L:/172.16.26.21:12345] READ COMPLETE
2017-11-30 14:51:13,410 151174583 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x6c8345c6, L:/172.16.26.21:12345] READ: [id: 0x1fac749e, L:/172.16.26.21:12345 - R:/172.16.26.21:41576]
2017-11-30 14:51:13,410 151174583 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x6c8345c6, L:/172.16.26.21:12345] READ COMPLETE
2017-11-30 14:51:13,412 151174585 [epollEventLoopGroup-3-4] INFO  i.p.s.s.h.handler.AppendProcessor - Received hello from connection: [id: 0xae93f766, L:/172.16.26.21:12345 - R:/172.16.26.21:41466]
2017-11-30 14:51:13,412 151174585 [epollEventLoopGroup-3-4] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: 3f610043-c003-4a3e-bdc0-dab65ee673b1 on segment: hulk/smallScale/1054
2017-11-30 14:51:13,413 151174586 [segment-store-32] INFO  i.p.s.s.h.handler.AppendProcessor - Segment 'hulk/smallScale/1099' is sealed and 7fe54475-4439-4118-a8b6-0c2b3804a640 cannot perform operation 'appending data'
2017-11-30 14:51:13,414 151174587 [epollEventLoopGroup-3-9] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection: 
java.lang.IllegalStateException: Data from unexpected connection: 7fe54475-4439-4118-a8b6-0c2b3804a640.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:518)
	at io.pravega.segmentstore.server.host.handler.AppendProcessor.append(AppendProcessor.java:368)
	at io.pravega.shared.protocol.netty.Append.process(Append.java:49)
	at io.pravega.segmentstore.server.host.handler.ServerConnectionInboundHandler.channelRead(ServerConnectionInboundHandler.java:47)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:797)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:394)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

It looks like maybe store lost all writer ids to event number mappings?

**Problem location**

**Suggestions for an improvement**

**Comment by fpj** [comment]
@glounder what is the commit id for what you are running? we have fixed a couple of bugs related to that recently, so it is possible that a more recent version will solve your issue.

**Comment by glounder** [comment]
The version we saw this in was 0.2.0-1687.fc1525d which was built on Nov 21.

**Comment by jkhalack** [comment]
The commit id is https://github.com/pravega/pravega/commit/fc1525d861fe45e6a9142a9f60b567a639aa2718

**Comment by fpj** [comment]
This issue is related to #2150 .

**Comment by shengkaisun** [comment]
This issue should be labeled as a bug. Looks like the priority should be high.
