### ISSUE TITLE
StorageWriter fails post-recovery with partially written appends

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#2168]
**Problem description**
We have observed the following exception in the segment store while running some tests:

```
2017-12-07 18:35:51,305 80300529 [segment-store-3] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[2]: Iteration[9376].Error.
java.lang.IllegalArgumentException: startOffset must refer to an offset beyond the Segment's StorageLength offset.
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
    at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.readDirect(StreamSegmentReadIndex.java:581)
    at io.pravega.segmentstore.server.reading.ContainerReadIndex.readDirect(ContainerReadIndex.java:176)
    at io.pravega.segmentstore.server.writer.StorageWriterFactory$StorageWriterDataSource.getAppendData(StorageWriterFactory.java:123)
    at io.pravega.segmentstore.server.writer.SegmentAggregator.getFlushArgs(SegmentAggregator.java:649)
    at io.pravega.segmentstore.server.writer.SegmentAggregator.flushPendingAppends(SegmentAggregator.java:598)
    at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$flushExcess$14(SegmentAggregator.java:579)
    at io.pravega.common.concurrent.FutureHelpers$Loop.call(FutureHelpers.java:642)
    at io.pravega.common.concurrent.FutureHelpers$Loop.call(FutureHelpers.java:611)
    at io.pravega.common.concurrent.FutureHelpers.runOrFail(FutureHelpers.java:524)
    at io.pravega.common.concurrent.FutureHelpers$Loop.run(FutureHelpers.java:655)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

This error has been found against our 0.1 release, so it is possible that it is not an issue any longer, but I couldn't find a related issue. Unfortunately, we don't have for now any more information that this stack trace for now, although it seems to be related to an issue with BookKeeper.

**Problem location**
Segment store.

**Suggestions for an improvement**
Determine whether it is an issue or not and fix in the case it is.

**Comment by tkaitchuck** [comment]
This looks to be a straightforward bug:
`AegmentAggregator.reconcileAppendOperation` is calling `dataSource.getAppendData` which is calling `StreamSegmentReadIndex.readDirect` which is asserting that the data is not stored in tier-2 but of course it is in this case, otherwise it would not be trying to reconcile it.

**Comment by arvindkandhare** [comment]
This error is observed in the perf test runs too. The scneario there is that BK becomes unavailable for some time during which following OOM is observed. The segmentstore restarts and then above mentioned exception is observed. It is also observed that the segmentstore recovers from this error.
```
2017-12-12 03:38:00,684 39987486 [epollEventLoopGroup-3-2] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection: 
io.netty.handler.codec.DecoderException: java.lang.OutOfMemoryError: GC overhead limit exceeded
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:797)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by andreipaduroiu** [comment]
The fact that it happens when BK crashes, when the Segment Store restarts or in any other time is coincidence. The root cause of this is a scenario along these lines:
1. StorageWriter processes offset O1 of Segment S
2. We truncate S at offset O2 > O1 ( + 1 )
3. StorageWriter processes offset O1+1 of Segment S, but the ReadIndex rejects it due to it having being truncated. 

This is a race that is best handled in the StorageWriter by  better detecting when such a problem occurs.

**Comment by tkaitchuck** [comment]
This is occurring in the absence of truncation.

**Comment by andreipaduroiu** [comment]
Oh, never mind then. I misread the error message. This is something else indeed.
