### ISSUE TITLE
Controller isn't recovering after ZK session expiry

### ISSUE THREAD

**Issue by dsrw** [pravega/pravega#2174]
**Problem description**

After a ZooKeeper session expiry, the pravega controller didn't recover. However, the `/ping` endpoint came back healthy, so mesos didn't restart it.

It seems that we had some sort connectivity issue to zookeeper. Our health checks started failing, and the ZK session expired. However, a short time later the health check started passing again, but the controller remained non responsive and the log was filled with zookeeper `session expired` messages for the remainder of its life.

```
2017-12-08 16:08:13,589 29686730 [epollEventLoopGroup-2-42] INFO  i.p.c.s.i.SegmentMetadataClientImpl - Closing connection with exception: null
2017-12-08 16:08:13,589 29686730 [epollEventLoopGroup-2-42] INFO  i.p.c.s.i.SegmentMetadataClientImpl - SegmentMetadata connection failed due to a null.
INFO  2017-12-08 16:08:35,232 [pool-2-thread-1] com.mesosphere.sdk.executor.CheckHandler$CheckRunner:run(174): Running Health check process: $MESOS_SANDBOX/scripts/http_check.py http://localhost:10080/ping
ERROR 2017-12-08 16:08:41,637 [pool-2-thread-1] com.mesosphere.sdk.executor.CheckHandler$CheckRunner:run(204): Health check failed with exception: environment { variables { name: "CONTROLLER_SERVER_PORT" value: "9091" } variables { name: "FRAMEWORK_HOST" value: "pravega.autoip.dcos.thisdcos.directory" } variables { name: "FRAMEWORK_NAME" value: "pravega" } variables { name: "JAVA_OPTS" value: "-Dlog.level=INFO -Dconfig.controller.metricenableStatistics=true -Dconfig.controller.metricstatsDHost=$STATSD_UDP_HOST -Dconfig.controller.metricstatsDPort=$STATSD_UDP_PORT -Dconfig.controller.metricstatsOutputFrequencySeconds=10 -Dbookkeeper.bkEnsembleSize=3 -Dbookkeeper.bkAckQuorumSize=3 -Dbookkeeper.bkWriteQuorumSize=3 -Dpravegaservice.zkSessionTimeoutMs=30000\n-Xmx512m" } variables { name: "POD_INSTANCE_INDEX" value: "0" } variables { name: "REST_SERVER_PORT" value: "10080" } variables { name: "TASK_NAME" value: "pravega_controller-0-server" } variables { name: "ZK_SESSION_TIMEOUT_MS" value: "30000" } variables { name: "ZK_URL" value: "zookeeper.pravega.l4lb.thisdcos.directory:31886" } variables { name: "pravega_controller-0-server" value: "true" } } value: "$MESOS_SANDBOX/scripts/http_check.py http://localhost:10080/ping"
java.lang.IllegalThreadStateException: process hasn't exited
    at java.lang.UNIXProcess.exitValue(UNIXProcess.java:423) ~[?:1.8.0_131]
    at com.mesosphere.sdk.executor.CheckHandler$ProcessRunner.run(CheckHandler.java:273) ~[executor-0.30.1-1615.2b7b6b7.jar:?]
    at com.mesosphere.sdk.executor.CheckHandler$CheckRunner.run(CheckHandler.java:175) [executor-0.30.1-1615.2b7b6b7.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_131]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_131]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
INFO  2017-12-08 16:09:05,431 [pool-2-thread-1] com.mesosphere.sdk.executor.CheckHandler$CheckRunner:run(174): Running Health check process: $MESOS_SANDBOX/scripts/http_check.py http://localhost:10080/ping
ERROR 2017-12-08 16:09:11,232 [pool-2-thread-1] com.mesosphere.sdk.executor.CheckHandler$CheckRunner:run(204): Health check failed with exception: environment { variables { name: "CONTROLLER_SERVER_PORT" value: "9091" } variables { name: "FRAMEWORK_HOST" value: "pravega.autoip.dcos.thisdcos.directory" } variables { name: "FRAMEWORK_NAME" value: "pravega" } variables { name: "JAVA_OPTS" value: "-Dlog.level=INFO -Dconfig.controller.metricenableStatistics=true -Dconfig.controller.metricstatsDHost=$STATSD_UDP_HOST -Dconfig.controller.metricstatsDPort=$STATSD_UDP_PORT -Dconfig.controller.metricstatsOutputFrequencySeconds=10 -Dbookkeeper.bkEnsembleSize=3 -Dbookkeeper.bkAckQuorumSize=3 -Dbookkeeper.bkWriteQuorumSize=3 -Dpravegaservice.zkSessionTimeoutMs=30000\n-Xmx512m" } variables { name: "POD_INSTANCE_INDEX" value: "0" } variables { name: "REST_SERVER_PORT" value: "10080" } variables { name: "TASK_NAME" value: "pravega_controller-0-server" } variables { name: "ZK_SESSION_TIMEOUT_MS" value: "30000" } variables { name: "ZK_URL" value: "zookeeper.pravega.l4lb.thisdcos.directory:31886" } variables { name: "pravega_controller-0-server" value: "true" } } value: "$MESOS_SANDBOX/scripts/http_check.py http://localhost:10080/ping"
java.lang.IllegalThreadStateException: process hasn't exited
    at java.lang.UNIXProcess.exitValue(UNIXProcess.java:423) ~[?:1.8.0_131]
    at com.mesosphere.sdk.executor.CheckHandler$ProcessRunner.run(CheckHandler.java:273) ~[executor-0.30.1-1615.2b7b6b7.jar:?]
    at com.mesosphere.sdk.executor.CheckHandler$CheckRunner.run(CheckHandler.java:175) [executor-0.30.1-1615.2b7b6b7.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_131]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_131]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
2017-12-08 16:09:21,832 29754973 [controllerpool-23] WARN  i.p.c.f.ControllerClusterListener - java.lang.RuntimeException: sweeper not ready
2017-12-08 16:09:21,846 29754987 [ControllerServiceMain-SendThread(zookeeper.pravega.l4lb.thisdcos.directory:31886)] WARN  org.apache.zookeeper.ClientCnxn - Client session timed out, have not heard from server in 68163ms for sessionid 0x20000cd26d20007
2017-12-08 16:09:21,934 29755075 [ControllerEventProcessors STARTING] INFO  i.p.c.stream.impl.ClientFactoryImpl - Creating writer for stream: _commitStream with configuration: EventWriterConfig(initalBackoffMillis=1, maxBackoffMillis=20000, retryAttempts=10, backoffMultiple=10, transactionTimeoutTime=3600000, transactionTimeoutScaleGracePeriod=3600000)
2017-12-08 16:09:22,034 29755175 [ControllerServiceMain-SendThread(zookeeper.pravega.l4lb.thisdcos.directory:31886)] INFO  org.apache.zookeeper.ClientCnxn - Client session timed out, have not heard from server in 68163ms for sessionid 0x20000cd26d20007, closing socket connection and attempting reconnect
2017-12-08 16:09:23,281 29756422 [ControllerServiceMain-SendThread(zookeeper.pravega.l4lb.thisdcos.directory:31886)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server zookeeper.pravega.l4lb.thisdcos.directory/11.6.245.168:31886. Will not attempt to authenticate using SASL (unknown error)
2017-12-08 16:09:23,283 29756424 [ControllerServiceMain-SendThread(zookeeper.pravega.l4lb.thisdcos.directory:31886)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /11.6.245.168:56032, server: zookeeper.pravega.l4lb.thisdcos.directory/11.6.245.168:31886
2017-12-08 16:09:23,297 29756438 [ControllerServiceMain-SendThread(zookeeper.pravega.l4lb.thisdcos.directory:31886)] WARN  org.apache.zookeeper.ClientCnxn - Unable to reconnect to ZooKeeper service, session 0x20000cd26d20007 has expired
2017-12-08 16:09:23,297 29756438 [ControllerServiceMain-SendThread(zookeeper.pravega.l4lb.thisdcos.directory:31886)] INFO  org.apache.zookeeper.ClientCnxn - Unable to reconnect to ZooKeeper service, session 0x20000cd26d20007 has expired, closing socket connection
2017-12-08 16:09:23,298 29756439 [ControllerServiceMain-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x20000cd26d20007
2017-12-08 16:09:31,852 29764993 [controllerpool-62] WARN  i.p.c.f.ControllerClusterListener - java.lang.RuntimeException: sweeper not ready
INFO  2017-12-08 16:09:35,160 [pool-2-thread-1] com.mesosphere.sdk.executor.CheckHandler$CheckRunner:run(174): Running Health check process: $MESOS_SANDBOX/scripts/http_check.py http://localhost:10080/ping
INFO  2017-12-08 16:09:35,205 [pool-2-thread-1] com.mesosphere.sdk.executor.CheckHandler$CheckRunner:run(190): Health check succeeded: $MESOS_SANDBOX/scripts/http_check.py http://localhost:10080/ping
INFO  2017-12-08 16:09:35,208 [pool-2-thread-1] com.mesosphere.sdk.executor.TaskStatusUtils:sendStatus(71): Sending task status update: task_id { value: "pravega_controller-0-server__5bbcdfc7-804d-4fdd-99a0-8e6bff629834" } state: TASK_RUNNING message: "Health check passed" slave_id { value: "c1f032e7-ad58-4ccf-a440-ed45732ad84a-S0" } executor_id { value: "pravega_controller__c64fe022-b4a8-43b1-83a0-2c39fa1ce749" } healthy: true source: SOURCE_EXECUTOR
2017-12-08 16:09:41,853 29774994 [controllerpool-62] WARN  i.p.c.f.ControllerClusterListener - java.lang.RuntimeException: sweeper not ready
2017-12-08 16:09:51,853 29784994 [controllerpool-62] WARN  i.p.c.f.ControllerClusterListener - java.lang.RuntimeException: sweeper not ready
2017-12-08 16:10:01,853 29794994 [controllerpool-62] WARN  i.p.c.f.ControllerClusterListener - java.lang.RuntimeException: sweeper not ready
INFO  2017-12-08 16:10:05,158 [pool-2-thread-1] com.mesosphere.sdk.executor.CheckHandler$CheckRunner:run(174): Running Health check process: $MESOS_SANDBOX/scripts/http_check.py http://localhost:10080/ping
INFO  2017-12-08 16:10:05,194 [pool-2-thread-1] com.mesosphere.sdk.executor.CheckHandler$CheckRunner:run(190): Health check succeeded: $MESOS_SANDBOX/scripts/http_check.py http://localhost:10080/ping
2017-12-08 16:10:11,854 29804995 [controllerpool-62] WARN  i.p.c.f.ControllerClusterListener - java.lang.RuntimeException: sweeper not ready
2017-12-08 16:10:18,248 29811389 [grpc-default-executor-66] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - createScope called for scope ConnectedCars12seg.
2017-12-08 16:10:21,854 29814995 [controllerpool-62] WARN  i.p.c.f.ControllerClusterListener - java.lang.RuntimeException: sweeper not ready
2017-12-08 16:10:27,206 29820347 [Curator-Framework-0] INFO  o.a.c.f.s.ConnectionStateManager - State change: LOST
2017-12-08 16:10:27,206 29820347 [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background operation retry gave up
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:131)
    at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:831)
    at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:623)
    at org.apache.curator.framework.imps.ExistsBuilderImpl$1.processResult(ExistsBuilderImpl.java:166)
    at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:581)
    at org.apache.zookeeper.ClientCnxn$EventThread.queuePacket(ClientCnxn.java:479)
    at org.apache.zookeeper.ClientCnxn.finishPacket(ClientCnxn.java:711)
    at org.apache.zookeeper.ClientCnxn.conLossPacket(ClientCnxn.java:745)
    at org.apache.zookeeper.ClientCnxn.queuePacket(ClientCnxn.java:1554)
    at org.apache.zookeeper.ClientCnxn.queuePacket(ClientCnxn.java:1529)
    at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1965)
    at org.apache.curator.framework.imps.ExistsBuilderImpl.performBackgroundOperation(ExistsBuilderImpl.java:175)
    at org.apache.curator.framework.imps.OperationAndData.callPerformBackgroundOperation(OperationAndData.java:84)
    at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:934)
    at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:912)
    at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:70)
    at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:316)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
2017-12-08 16:10:27,208 29820349 [ControllerEventProcessors STARTING] WARN  i.p.c.s.e.ControllerEventProcessors - Error creating commit event processor group
java.lang.RuntimeException: io.pravega.controller.store.stream.StoreException$StoreConnectionException: /store/_system/_commitStream/state
    at io.pravega.common.concurrent.Futures.getAndHandleExceptions(Futures.java:180)
    at io.pravega.client.stream.impl.SegmentSelector.refreshSegmentEventWriters(SegmentSelector.java:98)
    at io.pravega.client.stream.impl.EventStreamWriterImpl.<init>(EventStreamWriterImpl.java:99)
    at io.pravega.client.stream.impl.ClientFactoryImpl.createEventWriter(ClientFactoryImpl.java:117)
    at io.pravega.controller.eventProcessor.impl.EventProcessorGroupImpl.<init>(EventProcessorGroupImpl.java:77)
    at io.pravega.controller.eventProcessor.impl.EventProcessorSystemImpl.createEventProcessorGroup(EventProcessorSystemImpl.java:68)
    at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.lambda$initialize$24(ControllerEventProcessors.java:349)
    at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:194)
    at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.initialize(ControllerEventProcessors.java:348)
    at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.startUp(ControllerEventProcessors.java:148)
    at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
    at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
    at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.controller.store.stream.StoreException$StoreConnectionException: /store/_system/_commitStream/state
    at io.pravega.controller.store.stream.StoreException.create(StoreException.java:105)
    at io.pravega.controller.store.stream.StoreException.create(StoreException.java:70)
    at io.pravega.controller.store.stream.ZKStoreHelper.lambda$callback$22(ZKStoreHelper.java:315)
    at org.apache.curator.framework.imps.Backgrounding$1$1.run(Backgrounding.java:158)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    ... 1 common frames omitted
```

[stdout_controller.log](https://github.com/pravega/pravega/files/1547996/stdout_controller.log)

**Problem location**

Perhaps here? https://github.com/pravega/pravega/blob/fa3c917df3f92b1486d399a27b0f29438e55a83b/controller/src/main/java/io/pravega/controller/server/ControllerServiceMain.java#L104

Following the code it does look like the cluster listener should be enabled, but the `ZKWatcher` definitely isn't doing the right thing. Either I'm mistaken about the cluster listener being enabled, or something around the `ZKWatcher` isn't working the way we expect.

**Comment by shiveshr** [comment]
I followed the code, and the possible line of reasoning is as following:
Upon encountering ZK session expiry, while attempting a shutdown, if an exception was thrown, the ControllerServiceMain can reach failed state and main thread will exit. 
However, it may mean that executor is not shutdown and other threads continue to run in the background whereby the service never exits. 

However, i am not able to corroborate this with the shared logs (which are partial) which means one of the two things:
EITHER above conjuncture transpired before the shared log window
OR controller did not attempt a shutdown as ZKWatcher did not get Session Expiry event. 


-  Shutdown attempted, but Exception thrown during shutdown. 
we can do the following to mitigate this situation: 
1. During shutdown, retry if an exception gets thrown. 
2. once retries exhaust, do a force System.exit(errorCode)

This will ensure that controller either does a graceful or a forced shutdown. 
However, we dont have proof that this is what happened as we dont have logs to conclude that. 
So @dsrw if you get a reproduction of this issue, it would be great if we could get complete controller logs. 

- ControllerServiceMain fails to get notification for ZKSessionExpiry. (Problem with ZKwatch failing to give this notification. )
We will need more investigation if this is the case. Logically this should just work.
