### ISSUE TITLE
Does pravega container works for controller's REST API?

### ISSUE THREAD

**Issue by wangzhizheng** [pravega/pravega#2178]
**Problem description**
I started a pravega container as standalone mode and try send REST API to it, but failed.

**Problem location**
I started pravega container with this command
`docker run -it -e HOST_IP=10.62.130.162 -p 9090:9090 -p 12345:12345 -p 9091:9091 -p 10000:10000 pravega/pravega:latest standalone`

Then I send a REST for test but failed.
```
[root@TestMachine ~]# curl http://10.62.130.162:9090/scops
HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 474554202f73636f707320485454502f312e310d0a557365
```
there is also same error printed in container log
```
Dec 13, 2017 5:29:02 AM io.grpc.netty.NettyServerTransport notifyTerminated
SEVERE: Transport failed
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 474554202f73636f707320485454502f312e310d0a557365
        at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:277)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:217)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:401)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)
```

I am not sure this is a bug for pravega container or my command syntax is incorrect?

**Suggestions for an improvement**

**Comment by shrids** [comment]
Took a look at this, my current findings are as follows

* The REST server runs on port `9091 `and the example urls are listed at https://git.io/vbgdw
 
Regarding running standalone there are two ways to run it.

* Running standalone locally:
We can run standalone locally using the command` ./gradlew startstandalone`
Once the standalone starts we access the controller's REST API
```
e.g: 
 curl http://localhost:9091/v1/scopes
 curl http://localhost:9091/ping --> Returns a 200 if everything is fine.
```
	  
* Running standAlone using a docker container.
We can fetch the `pravega/pravega:latest `docker image from docker hub or build the latest docker image locally by 
`./gradlew buildPravegaImage` and run the container e:g:
`docker run --rm -it -e HOST_IP=10.0.2.15 -p 9090:9090 -p 12345:12345 -p 9091:9091 -p 10000:10000 pravega/pravega:latest standalone`

When a pravega container is configured to run in standalone mode REST server does not work due to a jar conflict  between JAX-RS-1 and JAX-RS 2 library. 
Controller uses JAX-RS-2 while hadoop (Used by segmentstore )related jars have a dependency JAX-RS-1. Inside the container both the versions of the jar are present.
This causes the REST server inside a container in standAlone mode to throw the following exception.

```
java.lang.NoSuchMethodError: javax.ws.rs.core.Application.getProperties()Ljava/util/Map;
        at org.glassfish.jersey.server.ResourceConfig$WrappingResourceConfig.mergeApplications(ResourceConfig.java:1134)
        at org.glassfish.jersey.server.ResourceConfig$WrappingResourceConfig.<init>(ResourceConfig.java:1054)
        at org.glassfish.jersey.server.ResourceConfig.forApplication(ResourceConfig.java:315)
        at io.pravega.controller.server.rest.RESTServer.<init>(RESTServer.java:61)
        at io.pravega.controller.server.ControllerServiceStarter.startUp(ControllerServiceStarter.java:223)
        at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
        at java.lang.Thread.run(Thread.java:745)
```
Will investigate further on how it can be resolved ...

**Comment by fpj** [comment]
@wangzhizheng could you verify that the PR that @shrids is proposing works for you?

**Comment by wangzhizheng** [comment]
@fpj @shrids 
Regard PR I have the new error this time.
`[root@TestMachine ~]# curl http://10.62.130.162:9091/v1/scopes
curl: (7) Failed connect to 10.62.130.162:9091; Connection refused

[root@TestMachine ~]# curl http://10.62.130.162:9090/v1/scopes
4Unexpected HTTP/1.x request: GET /v1/scopes`

Here is the exception stack in container.

`Dec 14, 2017 10:10:44 AM io.grpc.netty.NettyServerTransport notifyTerminated
INFO: Transport failed
io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: GET /v1/scopes
        at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:304)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:241)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:433)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:745)`



It looks 9090 is the open port for HTTP...........

**Comment by shrids** [comment]
Tested it by running the below commands and seeing the REST API work. Could you please share the steps you are following to start standalone?
```
 ./gradlew clean buildPravegaImage
docker run --rm -it -e HOST_IP=X.X.X.X -p 9090:9090 -p 12345:12345 -p 9091:9091 -p 10000:10000 pravega/pravega:latest standalone 
````

Command to invoke the REST API :
``` curl http://localhost:9091/v1/scopes```

Output :
``` {"scopes":[{"scopeName":"_system"}]} ```

**Comment by wangzhizheng** [comment]
here is what I have done:
1, git clone https://github.com/pravega/pravega.git
2, cd pravega
3, ./gradlew clean buildPravegaImage
4, docker run --rm -it -e HOST_IP=10.62.130.162 -p 9090:9090 -p 12345:12345 -p 9091:9091 -p 10000:10000 pravega/pravega:latest standalone
and test 9091,9090 port
`[root@TestMachine ~]# curl http://10.62.130.162:9091/v1/scopes
curl: (7) Failed connect to 10.62.130.162:9091; Connection refused

[root@TestMachine ~]# curl http://10.62.130.162:9090/v1/scopes
4Unexpected HTTP/1.x request: GET /v1/scopes`

**Comment by shrids** [comment]
Could you retry with the following steps once you are inside Pravega directory? This would ensure you are using the changes done in the pull request. 
```
2a. git checkout -b shrids-issue-2178-standaloneREST master
2b. git pull https://github.com/shrids/pravega.git issue-2178-standaloneREST
3, ./gradlew clean buildPravegaImage
4, docker run --rm -it -e HOST_IP=10.62.130.162 -p 9090:9090 -p 12345:12345 -p 9091:9091 -p 10000:10000 pravega/pravega:latest standalone
```

**Comment by wangzhizheng** [comment]
sorry for late response,
@shrids your branch works fine!
[root@TestMachine ~]# curl http://10.62.130.162:9091/v1/scopes
{"scopes":[{"scopeName":"_system"}]}
