### ISSUE TITLE
ReaderGroupConfig/state changes and serialization 

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#2181]
**Problem description**
To avoid dependencies the reader group state just uses Java serialization. This how has the limitation that a reader group can't easily be upgraded to a new version of the client:
```
pravega/pravega_controller  STDOUT     at io.pravega.client.stream.impl.JavaSerializer.deserialize(JavaSerializer.java:55)
pravega/pravega_controller  STDOUT 2017-12-11 17:54:11,030 529294 [ControllerEventProcessors STARTING] WARN  i.p.c.s.e.ControllerEventProcessors - Error creating commit event processor group
pravega/pravega_controller  STDOUT java.lang.RuntimeException: java.io.InvalidClassException: io.pravega.client.stream.ReaderGroupConfig; local class incompatible: stream classdesc serialVersionUID = 1530787269718366152, local class serialVersionUID = -7435346079857745183
pravega/pravega_controller  STDOUT     at io.pravega.client.state.impl.UpdateOrInitSerializer.deserialize(UpdateOrInitSerializer.java:65)
pravega/pravega_controller  STDOUT     at io.pravega.client.state.impl.UpdateOrInitSerializer.deserialize(UpdateOrInitSerializer.java:24)
pravega/pravega_controller  STDOUT     at io.pravega.client.state.impl.RevisionedStreamClientImpl$StreamIterator.next(RevisionedStreamClientImpl.java:149)
pravega/pravega_controller  STDOUT     at io.pravega.client.stream.impl.JavaSerializer.deserialize(JavaSerializer.java:26)
pravega/pravega_controller  STDOUT     at io.pravega.client.stream.impl.ReaderGroupStateManager.initializeReaderGroup(ReaderGroupStateManager.java:101)
pravega/pravega_controller  STDOUT     at io.pravega.client.state.impl.RevisionedStreamClientImpl$StreamIterator.next(RevisionedStreamClientImpl.java:116)
pravega/pravega_controller  STDOUT     at io.pravega.client.state.impl.StateSynchronizerImpl.fetchUpdates(StateSynchronizerImpl.java:77)
pravega/pravega_controller  STDOUT     at io.pravega.client.state.impl.StateSynchronizerImpl.initialize(StateSynchronizerImpl.java:127)
pravega/pravega_controller  STDOUT     at io.pravega.client.stream.impl.ReaderGroupImpl.initializeGroup(ReaderGroupImpl.java:87)
pravega/pravega_controller  STDOUT     at io.pravega.controller.eventProcessor.impl.EventProcessorGroupImpl.createIfNotExists(EventProcessorGroupImpl.java:110)
pravega/pravega_controller  STDOUT     at io.pravega.client.admin.impl.ReaderGroupManagerImpl.createReaderGroup(ReaderGroupManagerImpl.java:87)
pravega/pravega_controller  STDOUT     at io.pravega.controller.eventProcessor.impl.EventProcessorGroupImpl.initialize(EventProcessorGroupImpl.java:97)
pravega/pravega_controller  STDOUT     at io.pravega.controller.eventProcessor.impl.EventProcessorSystemImpl.createEventProcessorGroup(EventProcessorSystemImpl.java:71)
pravega/pravega_controller  STDOUT     at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.lambda$initialize$24(ControllerEventProcessors.java:349)
pravega/pravega_controller  STDOUT     at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.initialize(ControllerEventProcessors.java:348)
pravega/pravega_controller  STDOUT     at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.startUp(ControllerEventProcessors.java:148)
pravega/pravega_controller  STDOUT     at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:194)
pravega/pravega_controller  STDOUT     at java.lang.Thread.run(Thread.java:748)
pravega/pravega_controller  STDOUT Caused by: java.io.InvalidClassException: io.pravega.client.stream.ReaderGroupConfig; local class incompatible: stream classdesc serialVersionUID = 1530787269718366152, local class serialVersionUID = -7435346079857745183
```
**Problem location**
ReaderGroupState

**Suggestions for an improvement**
These should be switched to be externalizeable so that we can control the upgrade process.

**Comment by fpj** [comment]
@tkaitchuck I'm not sure what you are proposing, how is it compared to what is proposed here in #2177 ?

**Comment by tkaitchuck** [comment]
This is related to https://github.com/pravega/pravega/issues/2177
in that the missing ID is causing the exception. But even if we had the ID the code would sill not be forward compatible as there is no code to ensure continuity across versions of the client.

**Comment by tkaitchuck** [comment]
This was resolved some time back.
