### ISSUE TITLE
Possible Tier1 log data corruption

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#2198]
**Problem description**
See stack trace
```
java.lang.IllegalArgumentException: streamSegmentName: Cannot be an empty string.
    at io.pravega.common.Exceptions.checkArgument(Exceptions.java:166)
    at io.pravega.common.Exceptions.checkNotNullOrEmpty(Exceptions.java:132)
    at io.pravega.segmentstore.server.containers.StreamSegmentMetadata.<init>(StreamSegmentMetadata.java:88)
    at io.pravega.segmentstore.server.logs.ContainerMetadataUpdateTransaction.createSegmentMetadata(ContainerMetadataUpdateTransaction.java:609)
    at io.pravega.segmentstore.server.logs.ContainerMetadataUpdateTransaction.getOrCreateSegmentUpdateTransaction(ContainerMetadataUpdateTransaction.java:570)
    at io.pravega.segmentstore.server.logs.ContainerMetadataUpdateTransaction.deserializeSegmentMetadata(ContainerMetadataUpdateTransaction.java:817)
    at io.pravega.segmentstore.server.logs.ContainerMetadataUpdateTransaction.deserializeFrom(ContainerMetadataUpdateTransaction.java:678)
    at io.pravega.segmentstore.server.logs.ContainerMetadataUpdateTransaction.processMetadataOperation(ContainerMetadataUpdateTransaction.java:426)
    at io.pravega.segmentstore.server.logs.ContainerMetadataUpdateTransaction.preProcessOperation(ContainerMetadataUpdateTransaction.java:337)
    at io.pravega.segmentstore.server.logs.OperationMetadataUpdater.preProcessOperation(OperationMetadataUpdater.java:224)
    at io.pravega.segmentstore.server.logs.DurableLog.recoverOperation(DurableLog.java:414)
    at io.pravega.segmentstore.server.logs.DurableLog.recoverFromDataFrameLog(DurableLog.java:392)
    at io.pravega.segmentstore.server.logs.DurableLog.performRecovery(DurableLog.java:327)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
```

**Problem location**
Segment Store.

**Suggestions for an improvement**
None so far.

**Comment by andreipaduroiu** [comment]
Possible causes:
1. Tier1/DataFrame/Operation serialization corruption. This can be ruled out since `MetadataCheckpointOperation` serializes via a `GZipOutputStream` which has a header and checksum; if the serialization is truncated at the beginning, end or is missing parts, the deserialization would fail with a different error.
2. Threading issues during serialization. Possible, however after several code inspections I could not find any place where this could happen. Any metadata updates that could possible cause this are done under the same lock that is acquired during serialization.
3. It is possible the cluster where this is running was created using an older version of Pravega and it has recently been upgraded to the latest. The latest includes a new field in the serialization which was not there before; if an attempt is made to read an old serialization with the new code, such misalignments (resulting in unreadable data) can occur.

**Comment by fpj** [comment]
@andreipaduroiu 

From your description, I understand that you are discarding a problem on the bookkeeper side. Given that BK checksums the entries, I don't think it is possible that it loses bytes of an entry. Part of the reason for me to ask is that we are using BK 4.5.0 and there is a version 4.5.1 out, but checking the release notes:

http://bookkeeper.apache.org/docs/4.5.1/overview/releaseNotes/

This issue called my attention as it is related to ledger recovery, though:

https://github.com/apache/bookkeeper/issues/343 

but again, I can't think of a reason for that being the root cause.

> It is possible the cluster where this is running was created using an older version of Pravega and it has recently been upgraded to the latest. The latest includes a new field in the serialization which was not there before; if an attempt is made to read an old serialization with the new code, such misalignments (resulting in unreadable data) can occur.

But, would the deserialization even work with an older metadata versioning? We should in any case introduce versioning to the metadata to be able to manage compatibility across versions.

**Comment by andreipaduroiu** [comment]
> But, would the deserialization even work with an older metadata versioning? We should in any case introduce versioning to the metadata to be able to manage compatibility across versions.

Well, there is a version flag there. It just was never incremented with this addition since, per my understanding, we were not going to make this backwards compatible with v0.1.0.

**Comment by andreipaduroiu** [comment]
Root cause is described in #2233. That has been fixed and merged in.
