### ISSUE TITLE
Controller service is failing in InProcPravegaCluster 

### ISSUE THREAD

**Issue by vijikarthi** [pravega/pravega#2207]
**Problem description**
Controller service is not working when Pravega is running using `InProcPravegaCluster` mode due to jersey version mismatch.

```
2017-12-19 09:05:11,279 1542 [ControllerServiceMain] ERROR i.p.c.server.ControllerServiceMain - Controller Service Main thread exited exceptionally
java.lang.IllegalStateException: Expected the service ControllerServiceStarter [FAILED] to be RUNNING, but the service has FAILED
	at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
	at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:266)
	at com.google.common.util.concurrent.AbstractIdleService.awaitRunning(AbstractIdleService.java:175)
	at io.pravega.controller.server.ControllerServiceMain.run(ControllerServiceMain.java:132)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AbstractMethodError: javax.ws.rs.core.UriBuilder.uri(Ljava/lang/String;)Ljavax/ws/rs/core/UriBuilder;
	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:120)
	at io.pravega.controller.server.rest.RESTServer.<init>(RESTServer.java:49)
	at io.pravega.controller.server.ControllerServiceStarter.startUp(ControllerServiceStarter.java:221)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	... 2 common frames omitted
```

**Problem location**
Observed while running `flink-connector` build which is using in-memory Pravega for the test module code.

**Comment by shrids** [comment]
fixed with #2209
