### ISSUE TITLE
NPE in ZkStoreRetentionTest

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#2210]
**Problem description**
While building locally, I have hit a test failure with this stack:

```
io.pravega.controller.server.retention.ZkStoreRetentionTest > testRetentionService FAILED
    java.lang.IllegalStateException: Timed out waiting for watch removal
        at org.apache.curator.test.TestingZooKeeperMain.blockUntilStarted(TestingZooKeeperMain.java:146)
        at org.apache.curator.test.TestingZooKeeperServer.start(TestingZooKeeperServer.java:167)
        at org.apache.curator.test.TestingServer.<init>(TestingServer.java:117)
        at org.apache.curator.test.TestingServer.<init>(TestingServer.java:100)
        at org.apache.curator.test.TestingServer.<init>(TestingServer.java:41)
        at io.pravega.test.common.TestingServerStarter.start(TestingServerStarter.java:29)
        at io.pravega.controller.server.retention.ZkStoreRetentionTest.setup(ZkStoreRetentionTest.java:54)

    java.lang.NullPointerException
        at io.pravega.controller.server.retention.StreamCutServiceTest.tearDown(StreamCutServiceTest.java:73)
        at io.pravega.controller.server.retention.ZkStoreRetentionTest.tearDown(ZkStoreRetentionTest.java:66)
```
[TEST-io.pravega.controller.server.retention.ZkStoreRetentionTest.txt](https://github.com/pravega/pravega/files/1574594/TEST-io.pravega.controller.server.retention.ZkStoreRetentionTest.txt)

**Problem location**
Controller tests.

**Suggestions for an improvement**
Fix it.

**Comment by shiveshr** [comment]
Closing it as we have not been able to reproduce it again.
