### ISSUE TITLE
IllegalStateException in SegmentOutputStreamImpl

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#2211]
**Problem description**
Writers logs the following warning repeatedly.
```
2017-12-20 07:12:20,141 527693 [clientInternal-4] WARN  i.p.c.s.i.SegmentOutputStreamImpl - f0976f52-7627-478b-8c1c-440cf5ac6516 Failed to connect: 
java.util.concurrent.CompletionException: java.lang.IllegalStateException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.pravega.common.concurrent.Futures.lambda$delayedFuture$17(Futures.java:466)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl.lambda$null$4(SegmentOutputStreamImpl.java:522)
	at io.pravega.common.concurrent.Futures.lambda$delayedFuture$19(Futures.java:486)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	... 10 common frames omitted
```

**Problem location**
SegmentoutputStreamImpl.

**Suggestions for an improvement**

Fix the issue.
Logs: 
[readwriteandscalewithfailovertest.log.log.zip](https://github.com/pravega/pravega/files/1575506/readwriteandscalewithfailovertest.log.log.zip)

**Comment by shrids** [comment]
Current analysis:
1. 
```
2017-12-20 07:12:19,126 526678 [clientInternal-1] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=172.16.18.22, port=12345) for testReadWriteAndScaleScope102044663/testReadWriteAndScaleStream/1, writerID: f0976f52-7627-478b-8c1c-440cf5ac6516
2017-12-20 07:12:19,127 526679 [grpc-default-executor-4] TRACE i.p.c.stream.impl.ControllerImpl - LEAVE getEndpointForSegment@9532513524498 (elapsed=21661us).
2017-12-20 07:12:19,127 526679 [epollEventLoopGroup-4-4] INFO  i.p.c.n.i.ClientConnectionInboundHandler - Connection established ChannelHandlerContext(ClientConnectionInboundHandler#0, [id: 0x39769dda]) 
2017-12-20 07:12:19,127 526679 [epollEventLoopGroup-4-4] TRACE i.p.s.protocol.netty.CommandEncoder - Encoding message to send over the wire WireCommands.Hello(type=HELLO, highVersion=4, lowVersion=1)
2017-12-20 07:12:19,128 526680 [epollEventLoopGroup-4-4] DEBUG i.p.c.n.impl.ConnectionFactoryImpl - Connect operation completed for channel:39769dda, local address:/172.17.0.2:36202, remote address:172.16.18.22/172.16.18.22:12345
===> The above line indicates the connection is established.
```

2. 
```
2017-12-20 07:12:19,133 526685 [epollEventLoopGroup-4-4] ERROR i.p.s.p.n.ExceptionLoggingHandler - Uncaught exception on connection 172.16.18.22
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(...)(Unknown Source)
===> Now an exception call back is received for this writer
2017-12-20 07:12:19,134 526686 [epollEventLoopGroup-4-4] WARN  i.p.c.s.i.SegmentOutputStreamImpl - Connection for segment testReadWriteAndScaleScope102044663/testReadWriteAndScaleStream/1 failed due to: java.nio.channels.ClosedChannelException
===> this is logged in SegmentOutputStreamImpl.State#failConnection and this implies connection == null (!!!)

2017-12-20 07:12:19,134 526686 [epollEventLoopGroup-4-4] DEBUG i.p.c.s.i.SegmentOutputStreamImpl - (Re)connect invoked, Segment: testReadWriteAndScaleScope102044663/testReadWriteAndScaleStream/1, writerID: f0976f52-7627-478b-8c1c-440cf5ac6516
==> Next a reconnect is invoked.
```
	
3.
```
2017-12-20 07:12:20,141 527693 [clientInternal-4] DEBUG i.p.c.s.i.SegmentOutputStreamImpl - Running reconnect for segment:testReadWriteAndScaleScope102044663/testReadWriteAndScaleStream/1 writerID: f0976f52-7627-478b-8c1c-440cf5ac6516
2017-12-20 07:12:20,141 527693 [clientInternal-3] TRACE i.p.c.stream.impl.ControllerImpl - ENTER getEndpointForSegment@9533549293804 [testReadWriteAndScaleScope102044663/testReadWriteAndScaleStream/1].
2017-12-20 07:12:20,141 527693 [clientInternal-4] WARN  i.p.c.s.i.SegmentOutputStreamImpl - f0976f52-7627-478b-8c1c-440cf5ac6516 Failed to connect: 
java.util.concurrent.CompletionException: java.lang.IllegalStateException
===> Illegal state exception is thrown because connection is not null. (why is it not null is the question?)
```

4. From this point onwards `state.connection` is not null, i.e. it will retry until infinity.

**Comment by tkaitchuck** [comment]
See https://github.com/pravega/pravega/pull/2212#issuecomment-353234435
