### ISSUE TITLE
Sporadic build failure: ExtendedS3IntegrationTest.testEndToEnd

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#2227]
**Problem description**
We got this test case failing in an internal build and the stack trace is this one:

```
java.util.concurrent.CancellationException: OperationProcessor is shutting down.
	at io.pravega.segmentstore.server.logs.OperationProcessor.doStop(OperationProcessor.java:125)
	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:242)
	at io.pravega.common.concurrent.Services.stopAsync(Services.java:61)
	at io.pravega.segmentstore.server.logs.DurableLog.doStop(DurableLog.java:170)
	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:242)
	at io.pravega.common.concurrent.Services.stopAsync(Services.java:61)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.doStop(StreamSegmentContainer.java:183)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.doStop(StreamSegmentContainer.java:165)
	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:242)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.lambda$shutdownWhenStopped$19(StreamSegmentContainer.java:471)
	at io.pravega.common.concurrent.Services$ShutdownListener.failed(Services.java:119)
	at com.google.common.util.concurrent.AbstractService$5.call(AbstractService.java:531)
	at com.google.common.util.concurrent.AbstractService$5.call(AbstractService.java:528)
	at com.google.common.util.concurrent.ListenerCallQueue.run(ListenerCallQueue.java:121)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Problem location**
Segment store, extended S3 binding, test failure.

**Suggestions for an improvement**
Track the bug.

**Comment by andreipaduroiu** [comment]
This looks somewhat expected to me. An operation in flight is going to be failed with `CancellationException` when the Container/DurableLog/OperationProcessor are shutting down.

**Comment by fpj** [comment]
@andreipaduroiu ok, from what you are saying, it looks like this is a false positive. would it make sense to change the test case to avoid the spurious failure?

**Comment by andreipaduroiu** [comment]
I ran this a large number of times and I couldn't repro it. This doesn't look like it was introduced by a recent change. 

The stack trace indicates the container is shutting down due to some previous failure; this is just the aftermath. However we do not have logs for unit tests so I can't tell where this is coming from. Will keep an eye out for it .
