### ISSUE TITLE
Cannot delete Scope

### ISSUE THREAD

**Issue by addprs** [pravega/pravega#2237]
**Problem description**
Scope cannot be deleted, though the stream is successfully sealed and deleted 
Exception occurred:  Cannot delete non empty scope.

I make a rest call to check if the streams are really deleted are not, the streams are all deleted.No Streams exist  in the particular scope.

**Problem location**
Stack Trace
```
2018-01-05 13:53:58,636 1258 [grpc-default-executor-0] INFO io.pravega.client.stream.impl.ControllerImpl  -  Successfully sealed stream: psearch2018-01-05 13:53:58,751 1373 [grpc-default-executor-0] INFO io.pravega.client.stream.impl.ControllerImpl  -  Successfully deleted stream: psearch2018-01-05 13:53:58,758 1380 [grpc-default-executor-0] WARN io.pravega.client.stream.impl.ControllerImpl  -  Cannot delete non empty scope: psearch2018-01-05 13:53:58,759 1381 [grpc-default-executor-0] WARN io.pravega.client.stream.impl.ControllerImpl  -  deleteScope failed: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Scope psearch is not empty.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
```
**Suggestions for an improvement**
NOTE: There is an indefinite wait time to receive a message, if scope is deleted or not when error message does not pop up. 
May be  a api usage method for deletion of scope test case should be given for the client

**Comment by addprs** [comment]
Able to delete the scope, this issue was on 0.3.2, but on 0.4.0 candidate release this works fine. Able to delete the scope.
