### ISSUE TITLE
Sporadic build failure in ExtendedS3IntegrationTest.testEndToEnd

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#2248]
**Problem description**

```Error Message

io.pravega.segmentstore.storage.CacheException: Unable to initialize RocksDB instance (CacheId=Container_0).

Stacktrace

io.pravega.segmentstore.storage.CacheException: Unable to initialize RocksDB instance (CacheId=Container_0).
at io.pravega.segmentstore.storage.impl.rocksdb.RocksDBCache.convert(RocksDBCache.java:246)
at io.pravega.segmentstore.storage.impl.rocksdb.RocksDBCache.openDatabase(RocksDBCache.java:216)
at io.pravega.segmentstore.storage.impl.rocksdb.RocksDBCache.initialize(RocksDBCache.java:103)
```

**Problem location**
ExtendedS3IntegrationTest

**Suggestions for an improvement**
Fix the issue

**Comment by fpj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix ExtendedS3 end-to-end test](https://trello.com/c/pwVYQJlj/1-fix-extendeds3-end-to-end-test)

**Comment by Prabha-Veerubhotla** [comment]
Travis failure :
```
io.pravega.segmentstore.server.host.ExtendedS3IntegrationTest > testEndToEnd FAILED
    java.util.concurrent.TimeoutException
```

**Comment by shrids** [comment]
Travis build failure
```
io.pravega.segmentstore.server.host.ExtendedS3IntegrationTest > testEndToEndWithFencing FAILED
    java.lang.AssertionError: Unexpected Read Index length for segment Segment_5 expected:<2050> but was:<2106>
```

**Comment by arvindkandhare** [comment]
This is a new type of failure for the same test case. Looking into this. Will get back if I find anything interesting.

**Comment by fpj** [comment]
It  doesn't seem to be an issue any longer, so I'm closing this issue for now.
