### ISSUE TITLE
error: scala.reflect.internal.MissingRequirementError

### ISSUE THREAD

**Issue by Terry1504** [pravega/pravega#2253]
$ ./gradlew installDist

> Task :flink-examples:compileScala 
error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
        at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
        at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
        at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
        at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
        at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
        at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
        at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1390)
        at scala.tools.nsc.Global$Run.<init>(Global.scala:1242)
        at scala.tools.nsc.Driver.doCompile(Driver.scala:31)
        at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
        at scala.tools.nsc.Driver.process(Driver.scala:51)
        at scala.tools.nsc.Main.process(Main.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at sbt.compiler.RawCompiler.apply(RawCompiler.scala:33)
        at sbt.compiler.AnalyzingCompiler$$anonfun$compileSources$1$$anonfun$apply$2.apply(AnalyzingCompiler.scala:159)
        at sbt.compiler.AnalyzingCompiler$$anonfun$compileSources$1$$anonfun$apply$2.apply(AnalyzingCompiler.scala:155)
        at sbt.IO$.withTemporaryDirectory(IO.scala:358)
        at sbt.compiler.AnalyzingCompiler$$anonfun$compileSources$1.apply(AnalyzingCompiler.scala:155)
        at sbt.compiler.AnalyzingCompiler$$anonfun$compileSources$1.apply(AnalyzingCompiler.scala:152)
        at sbt.IO$.withTemporaryDirectory(IO.scala:358)
        at sbt.compiler.AnalyzingCompiler$.compileSources(AnalyzingCompiler.scala:152)
        at sbt.compiler.IC$.compileInterfaceJar(IncrementalCompiler.scala:58)
        at sbt.compiler.IC.compileInterfaceJar(IncrementalCompiler.scala)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory.getCompilerInterface(ZincScalaCompilerFactory.java:119)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory.access$200(ZincScalaCompilerFactory.java:48)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory$2.apply(ZincScalaCompilerFactory.java:90)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory$2.apply(ZincScalaCompilerFactory.java:87)
        at com.typesafe.zinc.Cache.get(Cache.scala:41)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory.createCompiler(ZincScalaCompilerFactory.java:87)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory.access$100(ZincScalaCompilerFactory.java:48)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory$1.create(ZincScalaCompilerFactory.java:76)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory$1.create(ZincScalaCompilerFactory.java:72)
        at org.gradle.internal.SystemProperties.withSystemProperty(SystemProperties.java:141)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory.createParallelSafeCompiler(ZincScalaCompilerFactory.java:72)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompiler$Compiler.execute(ZincScalaCompiler.java:64)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompiler.execute(ZincScalaCompiler.java:52)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompiler.execute(ZincScalaCompiler.java:38)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerRunnable.run(AbstractDaemonCompiler.java:87)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:36)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:46)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:30)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:100)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:844)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flink-examples:compileScala'.
> org.gradle.internal.serialize.PlaceholderException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9m 22s
8 actionable tasks: 8 executed

**Comment by fpj** [comment]
hey @Terry1504 , this is actually an issue for the `pravega-samples` project:

https://github.com/pravega/pravega-samples

Also, I have tried it today making sure that I have merged with master and it works for me. Is it possible that it is something with your setting?

```
$ ./gradlew clean installDist
:anomaly-detection:clean
:flink-examples:clean
:standalone-examples:clean
:anomaly-detection:compileJava
Note: /Users/junquf/code/pravega-samples/anomaly-detection/src/main/java/io/pravega/anomalydetection/event/pipeline/PravegaAnomalyDetectionProcessor.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/junquf/code/pravega-samples/anomaly-detection/src/main/java/io/pravega/anomalydetection/event/pipeline/PravegaAnomalyDetectionProcessor.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:anomaly-detection:processResources
:anomaly-detection:classes
:anomaly-detection:jar
:anomaly-detection:shadowJar
:anomaly-detection:startScripts
:anomaly-detection:installDist
:flink-examples:compileJava
Note: /Users/junquf/code/pravega-samples/flink-examples/src/main/java/io/pravega/examples/flink/iot/TurbineHeatProcessor.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:flink-examples:compileScala
/Users/junquf/code/pravega-samples/flink-examples/src/main/scala/io/pravega/examples/flink/iot/TurbineHeatProcessorScala.scala:95: method fold in class WindowedStream is deprecated: use [[aggregate()]] instead
      .fold(SensorAggregate.nothing)(SensorAggregate.fold)
       ^
one warning found
:flink-examples:processResources UP-TO-DATE
:flink-examples:classes
:flink-examples:shadowJar
:flink-examples:installDist
:standalone-examples:compileJava
Note: /Users/junquf/code/pravega-samples/standalone-examples/src/main/java/io/pravega/example/iot/TurbineHeatSensor.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/junquf/code/pravega-samples/standalone-examples/src/main/java/io/pravega/example/iot/TurbineHeatSensor.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:standalone-examples:processResources
:standalone-examples:classes
:standalone-examples:jar
:standalone-examples:scriptConsoleReader
:standalone-examples:scriptConsoleWriter
:standalone-examples:scriptHelloWorldReader
:standalone-examples:scriptHelloWorldWriter
:standalone-examples:scriptNoopReader
:standalone-examples:scriptSharedConfigCli
:standalone-examples:scriptTurbineSensor
:standalone-examples:installDist

BUILD SUCCESSFUL

Total time: 29.591 secs
```

**Comment by Terry1504** [comment]
thanks, @fpj, it might be some issue with my setting, :), not sure where. 
I would close this one and open the issue in pravega-samples project.
