### ISSUE TITLE
Reader does not respond post Segment container migration.

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#2273]
**Problem description**
It was observed that the Controller's AbortEvent processor is not able to read events from _abortStream when the Segment container migration happen. (This issue was observed during the ControllerFailover system test run.) 
On further investigation it was observed that the `reader.readNextEvent(timeout)` is blocked for more than 10 mins i.e the AbortEvent was never read from the _abortStream.

The logs found during the current investigation are listed below.

1) Test logs: test aborts the transaction.
```2018-01-23 06:40:04,075 9802 [Time-limited test] INFO  i.p.t.system.ControllerFailoverTest - Trying to abort transaction 7a16b5ca-14b4-4f53-8fe0-a2f2057e0e77, by sending request to controller at tcp://172.16.18.21:9092```

2)Controller writes to abortStream.
```scrambler-slave-1-container-2/controller.log:2018-01-23 06:40:04,133 2922513 [controllerpool-3] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Transaction 7a16b5ca-14b4-4f53-8fe0-a2f2057e0e77, sent request to _abortStream
scrambler-slave-1-container-2/controller.log:2018-01-23 06:42:09,594 3047974 [controllerpool-63] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Transaction 7a16b5ca-14b4-4f53-8fe0-a2f2057e0e77, sent request to _abortStream
```
3) Controller reads the abort stream event @ 06:57 17 mins after the event was written.
```scrambler-slave-1-container-2/controller_2018-01-23.21.log:2018-01-23 06:57:27,101 3965481 [controllerpool-59] DEBUG i.p.c.s.e.r.AbortRequestHandler - Aborting transaction 7a16b5ca-14b4-4f53-8fe0-a2f2057e0e77 on stream testFailoverScopegepsh/testFailoverStreamJscoF
scrambler-slave-1-container-2/controller_2018-01-23.21.log:2018-01-23 06:57:27,304 3965684 [controllerpool-11] DEBUG i.p.c.s.e.r.AbortRequestHandler - Aborting transaction 7a16b5ca-14b4-4f53-8fe0-a2f2057e0e77 on stream testFailoverScopegepsh/testFailoverStreamJscoF
```

4) The additional logging indicates the client read @ 06:36:12 never completed.

``` scrambler-slave-1-container-2/controller_2018-01-23.21.log:2018-01-23 06:36:12,963 2691343 [EventProcessor[abortStreamReaders:0]] DEBUG i.p.c.e.impl.EventProcessorCell - ==> Attempt to read event EventProcessor[abortStreamReaders:0]
scrambler-slave-1-container-2/controller_2018-01-23.21.log:2018-01-23 06:57:15,383 3953763 [EventProcessor[abortStreamReaders:0]] DEBUG i.p.c.e.impl.EventProcessorCell - ==> Attempt to read event EventProcessor[abortStreamReaders:0]
scrambler-slave-1-container-2/controller_2018-01-23.21.log:2018-01-23 06:57:27,043 3965423 [EventProcessor[abortStreamReaders:0]] DEBUG i.p.c.e.impl.EventProcessorCell - ==> Event read EventProcessor[abortStreamReaders:0] is EventReadImpl(eventSequence=Sequence(highOrder=0, lowOrder=307), event=null, position=PositionImpl(ownedSegments=[Segment(scope=_system, streamName=_abortStream, segmentNumber=1), Segment(scope=_system, streamName=_abortStream, segmentNumber=0)]), eventPointer=null, checkpointName=921294f9-3db9-4b41-906e-4c6fcf51323f) 
```
5) 
After the read request @06:36:12, the reader loses connection to _abortStream/0. 
Then it receives
```2018-01-23 06:36:14,809 2693189 [EventProcessor[abortStreamReaders:0]] WARN  i.p.c.s.impl.SegmentInputStreamImpl - Encountered an exception while reading for Segment(scope=_system, streamName=_abortStream, segmentNumber=1)
io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
```
After this there are 12 such attempts to connect to the _abortStream/1 and then there are no logs related to connection attempts.
```
2018-01-23 06:38:38,817 2837197 [epollEventLoopGroup-2-6] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Closing connection to segment Segment(scope=_system, streamName=_abortStream, segmentNumber=0) with exception: {}
io.pravega.shared.protocol.netty.ConnectionFailedException: null
    at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.connectionDropped(AsyncSegmentInputStreamImpl.java:58)
```

Interestingly this issue was never seen once the controller disabled automatic checkpointing.

[controller_2018-01-23.21.log.zip](https://github.com/pravega/pravega/files/1662530/controller_2018-01-23.21.log.zip)

**Problem location**
Reader.

**Suggestions for an improvement**
Investigate further and fix the issue.

**Comment by tkaitchuck** [comment]
t might be as simple as the following race condition:
Inside of `AsyncSegmentOutputStreamImpl.read()` it first calls `getConnection()` which returns the future for the connection.  The connection is setup and so the future is completed successfully.
Then an error arrives from the server causing it to drop the connection. 
There is nothing yet in flight so it does not propagate up to any futures in the `outstandingRequests` map.
Now `sendRequestOverConnection()` is invoked. The connection it is using is bad, but `sendAsync` does not throw. (We saw this earlier on the writer).
As such there is now an outstanding future, that the caller of read() may eventually end up blocking on, which if it is in `fillBuffer()` will ignore any timeout parameters, but the connection is already failed, so no error will ever come.

That would be fairly straightforward. But I have no idea what is has to do with Automatic checkpoints.

**Comment by shrids** [comment]
Run 957 analysis. (Relevant controller log attached )
[controller_2018-01-30.9.log.zip](https://github.com/pravega/pravega/files/1681397/controller_2018-01-30.9.log.zip)


1. Test logs:
```
2018-01-30 07:43:17,553 9015 [Time-limited test] INFO  i.p.t.system.ControllerFailoverTest - Trying to abort transaction 2fbe96e4-6a77-4b50-9c06-29a67fa9077d, by sending request to controller at tcp://172.16.18.22:9092
```

2. Controller logs:Abort Event written @ 07:43
```
scrambler-slave-2-container-2/controller_2018-01-30.9.log:2018-01-30 07:43:17,612 2669985 [controllerpool-49] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Transaction 2fbe96e4-6a77-4b50-9c06-29a67fa9077d, sent request to _abortStream
scrambler-slave-2-container-2/controller_2018-01-30.9.log:2018-01-30 07:45:23,590 2795963 [controllerpool-12] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Transaction 2fbe96e4-6a77-4b50-9c06-29a67fa9077d, sent request to _abortStream
```

3. AbortEvent read at 07:57:18...
```
scrambler-slave-2-container-2/controller_2018-01-30.10.log:2018-01-30 07:57:18,587 3510960 [controllerpool-20] DEBUG i.p.c.s.e.r.AbortRequestHandler - Aborting transaction 2fbe96e4-6a77-4b50-9c06-29a67fa9077d on stream testFailoverScopefLGrv/testFailoverStreamRHgYv
scrambler-slave-2-container-2/controller_2018-01-30.10.log:2018-01-30 08:00:50,223 3722596 [controllerpool-60] DEBUG i.p.c.s.e.r.AbortRequestHandler - Aborting transaction 2fbe96e4-6a77-4b50-9c06-29a67fa9077d on stream testFailoverScopefLGrv/testFailoverStreamRHgYv
```

4: Thread dump: triggered @ 2018-01-30 07:39:48,289 , AbortStreamReader thread is blocked for 10+ mins from this point.

```
"EventProcessor[abortStreamReaders:0]"
   java.lang.Thread.State: WAITING
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
        at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.handleRequest(SegmentInputStreamImpl.java:174)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.readEventData(SegmentInputStreamImpl.java:142)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.read(SegmentInputStreamImpl.java:117)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:103)
        at io.pravega.controller.eventProcessor.impl.EventProcessorCell$Delegate.run(EventProcessorCell.java:109)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by tkaitchuck** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix race causing integration tests to fail when automatic checkpointing is on.](https://trello.com/c/98CAUXVv/25-fix-race-causing-integration-tests-to-fail-when-automatic-checkpointing-is-on)

**Comment by tkaitchuck** [comment]
The race I pointed out above does not appear to be an issue. (Updated the comment)
@shrids That stack trace comes in at 7:39:48 which is 20 seconds after the last call to poll. This is what we should expect. The time it is using the delay is 2 * the default timeout which is set to 2sec. And at 7:39 there weren't any events in the stream to be read, so it is blocking waiting for the data to arrive. This is not surprising. (There is a minor bug here of ignoring the timeout, but this is because of the failed request) 

The question is why doesn't the server respond with the data at 7:43 and unblock the request?

**Comment by tkaitchuck** [comment]
At 7:57:18,411 we do see "Restarting event processor: EventProcessor[abortStreamReaders:0] due to exception: {}" which does not have the exception logged but it indicates that the read call finally threw an exception which in turn caused it to resume. This explains why it unblocked and read the event.

**Comment by tkaitchuck** [comment]
I can also see from the log there was a RetriesExhaustedException.
```
2018-01-30 07:37:14,246 2306619 [EventProcessor[abortStreamReaders:0]] WARN  i.p.c.s.impl.SegmentInputStreamImpl - Encountered an exception while reading for Segment(scope=_system, streamName=_abortStream, segmentNumber=1)
io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
        at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$6(Retry.java:266)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.failAllInflight(AsyncSegmentInputStreamImpl.java:228)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.closeConnection(AsyncSegmentInputStreamImpl.java:200)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.access$100(AsyncSegmentInputStreamImpl.java:39)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.connectionDropped(AsyncSegmentInputStreamImpl.java:58)
        at io.pravega.client.netty.impl.ClientConnectionInboundHandler.channelUnregistered(ClientConnectionInboundHandler.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1337)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:835)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:771)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
        at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
        at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:899)
        ... 33 common frames omitted
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: null
        ... 28 common frames omitted
```
This does explain why the stack trace was in the state in was in at the time of the dump.

**Comment by shrids** [comment]
>The question is why doesn't the server respond with the data at 7:43 and unblock the request?

- abortStream reader is responsible from reading from two segments(`S0`, `S1`). Now while reading from `S1` if it encounters an error then `SegmentInputStreamImpl#issueRequestIfNeeded` would
fire a new read request to SSS and wait for it to complete `SegmentInputStreamImpl#handleRequest`. But SSS does not respond to it since it does not have data. 

- Now the other segment S1 has new data due to write @ 7:43 and it responds to it.
```
Write data =>
scrambler-slave-4-container-3/segmentstore_2018-01-30.115.log:2018-01-30 07:43:17,587 2649264 [epollEventLoopGroup-3-4] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Processing request: Append(segment=_system/_abortStream/0, writerId=b7130875-606b-41c1-b48a-6449c6cdc6ff, eventNumber=4, eventCount=1, data=CompositeByteBuf(ridx: 0, widx: 282, cap: 282, components=1), expectedLength=null)
Respond with data =>
scrambler-slave-2-container-2/controller_2018-01-30.9.log:2018-01-30 07:43:17,612 2669985 [epollEventLoopGroup-2-5] DEBUG i.p.c.n.i.ClientConnectionInboundHandler - 172.16.18.24 processing reply: WireCommands.SegmentRead(type=SEGMENT_READ, segment=_system/_abortStream/0, offset=921, atTail=false, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=282 cap=282])
```
But the client thread is stuck waiting for S1's response for READ_SEGMENT.
