### ISSUE TITLE
Test failure: testStartAndStopContainer

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#2295]
**Problem description**
Test failure: testStartAndStopContainer. The stack trace is:

```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.pravega.segmentstore.server.host.ZKSegmentContainerMonitorTest.testStartAndStopContainer(ZKSegmentContainerMonitorTest.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Problem location**
Starting and stopping containers in the segment store.

**Suggestions for an improvement**
Here are the logs:
[io.pravega.segmentstore.server.host.ZKSegmentContainerMonitorTest.testStartAndStopContainer.txt](https://github.com/pravega/pravega/files/1685517/io.pravega.segmentstore.server.host.ZKSegmentContainerMonitorTest.testStartAndStopContainer.txt)

**Comment by shiveshr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: Test failure: testStartAndStopContainer](https://trello.com/c/P3FqK8bX/35-bug-test-failure-teststartandstopcontainer)

**Comment by shiveshr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: Test failure: testStartAndStopContainer](https://trello.com/c/P3FqK8bX/35-bug-test-failure-teststartandstopcontainer)

**Comment by shiveshr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: Test failure: testStartAndStopContainer](https://trello.com/c/P3FqK8bX/35-bug-test-failure-teststartandstopcontainer)

**Comment by shiveshr** [comment]
Closing this as we have not had this failure observed in a while. It can be reopened if the issue surfaces.
