### ISSUE TITLE
Unit test failure in Jenkins

### ISSUE THREAD

**Issue by Prabha-Veerubhotla** [pravega/pravega#2300]
**Problem description**
`io.pravega.segmentstore.server.reading.ContainerReadIndexTests.testCacheEviction` failed with
log message :
`java.lang.AssertionError: Unexpected CacheKey.SegmentOffset at index 11 for SegmentId 79. expected:<3600> but was:<3700>`

Stack trace:
```
java.lang.AssertionError: Unexpected CacheKey.SegmentOffset at index 11 for SegmentId 79. expected:<3600> but was:<3700>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at io.pravega.segmentstore.server.reading.ContainerReadIndexTests.checkOffsets(ContainerReadIndexTests.java:1042)
	at io.pravega.segmentstore.server.reading.ContainerReadIndexTests.testCacheEviction(ContainerReadIndexTests.java:879)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```
**Problem location**

**Suggestions for an improvement**

**Comment by Prabha-Veerubhotla** [comment]
Same as #1327
