### ISSUE TITLE
travis failure: Timeout observed in io.pravega.controller.server.eventProcessor.ScaleRequestHandlerTest > testScaleRequest

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2402]
**Problem description**
Hit this failure during travis build. I see that this is a transient error.

io.pravega.controller.server.eventProcessor.ScaleRequestHandlerTest > testScaleRequest FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 20000 milliseconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1695)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1775)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
        at io.pravega.common.concurrent.Futures.lambda$await$0(Futures.java:68)
        at io.pravega.common.concurrent.Futures$$Lambda$138/50801066.run(Unknown Source)
        at io.pravega.common.Exceptions.handleInterrupted(Exceptions.java:90)
        at io.pravega.common.concurrent.Futures.await(Futures.java:66)
        at io.pravega.common.concurrent.Futures.await(Futures.java:53)
        at io.pravega.controller.server.eventProcessor.ScaleRequestHandlerTest.testScaleRequest(ScaleRequestHandlerTest.java:197)

**Problem location**
Travis build. io.pravega.controller.server.eventProcessor.ScaleRequestHandlerTest > testScaleRequest

**Suggestions for an improvement**

**Comment by shiveshr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: Timeout observed in io.pravega.controller.server.eventProcessor.ScaleRequestHandlerTest > testScaleRequest](https://trello.com/c/b6YyN8LH/34-bug-timeout-observed-in-iopravegacontrollerservereventprocessorscalerequesthandlertest-testscalerequest)
