### ISSUE TITLE
Segmentstore service builder should call shutdownnow() on the ScheduledExecutorService

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2504]
**Problem description**
The `ServiceBuilder` implementation calls `shutdown` to stop the executor service. This just stops executing any new tasks. But still tries to finish the existing tasks.
This is not expected behavior. Especially in case of unit tests where we are stopping and starting multiple instances of ServiceBuilder, such dangling executions can cause unexpected and unintended side effects.
e.g. These stack trace may be because of such an event.

```
2018-04-20 00:45:41,254 ERROR [core-13] server.NIOServerCnxnFactory (NIOServerCnxnFactory.java:uncaughtException(92)) - Thread Thread[core-13,5,FailOnTimeoutGroup] died
java.lang.NullPointerException
    at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.siftDown(ScheduledThreadPoolExecutor.java:903)
    at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.finishPoll(ScheduledThreadPoolExecutor.java:1055)
    at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1085)
    at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
    at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

```
Caused by: java.lang.NullPointerException
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.compareTo(ScheduledThreadPoolExecutor.java:254)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.compareTo(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.siftUp(ScheduledThreadPoolExecutor.java:881)
    at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.offer(ScheduledThreadPoolExecutor.java:1020)
    at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.add(ScheduledThreadPoolExecutor.java:1037)
    at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.add(ScheduledThreadPoolExecutor.java:809)
    at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:328)
    at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
    at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622)
    at com.google.common.util.concurrent.ListenerCallQueue.execute(ListenerCallQueue.java:87)
    at com.google.common.util.concurrent.AbstractService.executeListeners(AbstractService.java:479)
    at com.google.common.util.concurrent.AbstractService.startAsync(AbstractService.java:216)
    at io.pravega.common.concurrent.Services.startAsync(Services.java:44)
    at io.pravega.segmentstore.server.logs.DurableLog.lambda$tryStartOnce$4(DurableLog.java:201)
```

It is possible that this can be the root cause of #2488, #2250, #2249, #2248.

These changes were made locally and it was observed that timeout is not observed during debugging through IDE.

**Problem location**
`close` method of `ServiceBuilder`.

**Suggestions for an improvement**
Replace `shutdown()` with `shutdownnow()` followed by `awaitTermination`.

**Comment by arvindkandhare** [comment]
This is fixed in #2508.
