### ISSUE TITLE
Error on late reads from an old sealed segment that never had writes to it

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#2512]
**Problem description**
We are running a longevity test that writes to a stream with scaling triggered by event rate. Distribution of the data within the routing key space is such that some of the dynamically created segments never get any data written to them.
At some point in time we are resetting a reader group to start reading the stream from the beginning:
```
// reset reader group
ReaderGroupConfig resetConfig = ReaderGroupConfig.builder()
    .disableAutomaticCheckpoints()
    .stream(readerGroup.getScope() + "/" + stream)
    .build();
readerGroup.resetReaderGroup(resetConfig);
...
// recreate reader
readerId = //new id
eventStreamReader = clientFactory.createReader(readerId, readerGroup.getGroupName(), SERIALIZER, readerConfig);
```

After resetting the reader group, the readers start failing when they supposed to read from a segment that never had any writes to it:
```
2018-04-25 18:00:52,097 8808157 [epollEventLoopGroup-5-17] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Received noSuchSegment No such segment: hulk/smallScale/35
2018-04-25 18:00:52,098 8808158 [epollEventLoopGroup-5-16] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Received noSuchSegment No such segment: hulk/smallScale/21
2018-04-25 18:00:52,104 8808164 [pool-8-thread-1] ERROR c.e.n.h.t.w.readers.PravegaReader - Reader finished with Error
java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.client.segment.impl.SegmentTruncatedException: Segment no longer exists.
    at java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
    at java.util.concurrent.CompletableFuture.join(Unknown Source)
    at io.pravega.client.segment.impl.SegmentInputStreamImpl.handleRequest(SegmentInputStreamImpl.java:167)
    at io.pravega.client.segment.impl.SegmentInputStreamImpl.readEventData(SegmentInputStreamImpl.java:136)
    at io.pravega.client.segment.impl.SegmentInputStreamImpl.read(SegmentInputStreamImpl.java:111)
    at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:103)
    at com.emc.nautilus.hulk.taskexecutor.workers.readers.PravegaReader.start(PravegaReader.java:96)
...
``` 

**Problem location**
Client

**Suggestions for an improvement**
The readers should not fail when trying to read from old empty sealed segments.

**Comment by shrids** [comment]
related to issue #2441

**Comment by shengkaisun** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Stream reset bug](https://trello.com/c/RiQ79Nkp/16-stream-reset-bug)
