### ISSUE TITLE
Standalone/emulator throws NullPointerException at startup

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2519]
**Problem description**
The emulator throws an exception at startup:
```
java.lang.NullPointerException
    at io.pravega.common.util.ConfigBuilder.with(ConfigBuilder.java:77)
    at io.pravega.local.InProcPravegaCluster.startLocalSegmentStore(InProcPravegaCluster.java:250)
    at io.pravega.local.InProcPravegaCluster.startLocalSegmentStores(InProcPravegaCluster.java:229)
    at io.pravega.local.InProcPravegaCluster.start(InProcPravegaCluster.java:187)
    at io.pravega.connectors.flink.utils.SetupUtils$InProcPravegaGateway.start(SetupUtils.java:263)
    at io.pravega.connectors.flink.utils.SetupUtils.startAllServices(SetupUtils.java:85)
    at io.pravega.connectors.flink.FlinkPravegaInputFormatITCase.setupPravega(FlinkPravegaInputFormatITCase.java:50)
```

I believe this may be related to the fix in #2476, because the `keyFile` property previously had a default value.

**Problem location**
In `InProcPravegaCluster`:
```
    private void startLocalSegmentStore(int segmentStoreId) throws Exception {
        ServiceBuilderConfig.Builder configBuilder = ServiceBuilderConfig
                .builder()
                .include(System.getProperties())
                .include(ServiceConfig.builder()
                        ...
                        .with(ServiceConfig.KEY_FILE, this.keyFile)
```

Fails due to an assumption that the value is never null:
```
public <V> ConfigBuilder<T> with(Property<V> property, V value) {
        String key = String.format("%s.%s", this.namespace, property.getName());
        this.properties.setProperty(key, value.toString());
        return this;
    }
```

**Suggestions for an improvement**

**Comment by arvindkandhare** [comment]
The workaround for this issue is to set `keyFile` for `InProcPravegaCluster` through the `builder()` call. Will have a fix for this so that these variables are set only when `tls` is enabled.
