### ISSUE TITLE
EndToEndChannelLeakTest  test failure

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#2523]
**Problem description**
EndToEndChannelLeakTest  fails sporadically.
```
io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest > testDetectChannelLeakMultiReader FAILED
    java.lang.AssertionError: expected:<5> but was:<4>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest.testDetectChannelLeakMultiReader(EndToEndChannelLeakTest.java:207)
```
**Problem location**
EndToEndChannelLeakTest.java

**Suggestions for an improvement**
Fix the race condition in the test.

**Comment by shiveshr** [comment]
i found this issue resurface recently

https://travis-ci.org/pravega/pravega/builds/390323352?utm_source=slack&utm_medium=notification

io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest > testDetectChannelLeakMultiReader FAILED
    java.lang.AssertionError: expected:<6> but was:<7>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest.testDetectChannelLeakMultiReader(EndToEndChannelLeakTest.java:214)

**Comment by shiveshr** [comment]
another reproduction

**Comment by tkaitchuck** [comment]
This test seems prone to races, because in some code paths the cleanup is being done in a background thread, while the main thread is asserting there have been no resource leaks.  Perhaps we need to add a hook into the threadpool to allow the main thread to block on its work.

**Comment by tkaitchuck** [comment]
I just saw the issue again. Apparently we aren't through with it:
```
io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest > testDetectChannelLeakSegmentSealed FAILED
    java.lang.AssertionError: expected:<10> but was:<9>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest.testDetectChannelLeakSegmentSealed(EndToEndChannelLeakTest.java:155)
```

**Comment by RaulGracia** [comment]
Observing this failure frequently in the new Jenkins environment, which may be related to this issue:
```
io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest.testDetectChannelLeakMultiReader
Error Message
java.lang.AssertionError: expected:<6> but was:<7>
Stacktrace
java.lang.AssertionError: expected:<6> but was:<7>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest.assertEventuallyEquals(EndToEndChannelLeakTest.java:271)
	at io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest.testDetectChannelLeakMultiReader(EndToEndChannelLeakTest.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
