### ISSUE TITLE
Test failure due to incorrect controller URI in Segment Store.

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#2534]
**Problem description**
*Observations*: ( Stream Name: testAutoScale2021607227/testTxnScaleUpWithRead)

1. Scale event from AutoScaleProcessor in SSS.
```
vagrant@INENSHRIDSL5C:/mnt/c/Sandeep/logs/archive-1062/archive/results/logs$ grep -r "sending request for scale" | grep "testAutoScale2021607227/testTxnScaleUpWithRead"                               
scrambler-slave-5-container-1/segmentstore_2018-04-24.364.log:2018-04-24 21:03:58,569 6103723 [core-22] INFO  i.p.s.s.h.stat.AutoScaleProcessor - sending request for scale up for testAutoScale2021607227/testTxnScaleUpWithRead/0
scrambler-slave-5-container-1/segmentstore_2018-04-24.368.log:2018-04-24 21:04:38,570 6143724 [cache-maintenance-0] INFO  i.p.s.s.h.stat.AutoScaleProcessor - sending request for scale down for testAutoScale2021607227/testTxnScaleUpWithRead/0
```

2. The writer(`id: 09986380-7a3f-43c0-9710-ce6738688d0f`) is not able to write events to `_system/_requeststream`.
```
2018-04-24 21:03:58,569 6103723 [core-22] DEBUG i.p.s.s.h.stat.AutoScaleProcessor - cool down period elapsed for testAutoScale2021607227/testTxnScaleUpWithRead/0
2018-04-24 21:03:58,569 6103723 [core-22] DEBUG i.p.s.s.h.stat.AutoScaleProcessor - triggering scale up for testAutoScale2021607227/testTxnScaleUpWithRead/0 with number of splits 100
2018-04-24 21:03:58,569 6103723 [core-22] INFO  i.p.s.s.h.stat.AutoScaleProcessor - sending request for scale up for testAutoScale2021607227/testTxnScaleUpWithRead/0
2018-04-24 21:03:58,573 6103727 [core-22] DEBUG i.p.c.s.i.SegmentOutputStreamImpl - (Re)connect invoked, Segment: _system/_requeststream/0, writerID: 09986380-7a3f-43c0-9710-ce6738688d0f
```

3.
The getEndpointForSegment call fails as with GRPC error `UNAVAILABLE`.
```
2018-04-24 21:03:33,730 6078884 [clientInternal-3] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Fetching endpoint for segment _system/_requeststream/0, writerID: 09986380-7a3f-43c0-9710-ce6738688d0f
2018-04-24 21:03:33,732 6078886 [grpc-default-executor-12] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call failed with server error: UNAVAILABLE```
```Retries fail to connect to Controller.
2018-04-24 21:05:04,925 6170079 [grpc-default-executor-12] WARN  i.p.c.stream.impl.ControllerImpl - getEndpointForSegment failed:
java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: UNAVAILABLE
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 172.16.18.23/172.16.18.23:9092
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) 
```
```2018-04-24 21:05:04,925 6170079 [grpc-default-executor-12] WARN  i.p.c.s.i.SegmentOutputStreamImpl - 09986380-7a3f-43c0-9710-ce6738688d0f Failed to connect:
java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: UNAVAILABLE 
```

**Problem location**
To be investigated.
(Why is Segment store configured with a non -existent controller?)

**Suggestions for an improvement**
Fix the issue.

**Comment by shrids** [comment]
Based on the available logs and discussions with @Prabha-Veerubhotla and @RaulGracia 
Multicontroller test is one of the possible cause for a new controller being spawned without its corresponding Segmentstore being updated.
The issues in MulticontrollerTest are 

1. Multi-controller test brings the controller instance count to 0. (This was not the case in the previous version of the test ref: https://git.io/vpgre ).
2. It does not test the discover based controller uris (with pattern  "pravega://" ).

**Comment by RaulGracia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix system test build (scaleTestsWithReader failing consistently)](https://trello.com/c/2lGk7O8o/18-fix-system-test-build-scaletestswithreader-failing-consistently)
