### ISSUE TITLE
Hot segment not scaling due to input mismatch

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#2543]
**Problem description**
In our scaling test with a variable event rate on a stream with event-rate triggered scaling policy we observe one of the segment (number 4604) not being scaled up despite being hot:
![midscale_7d](https://user-images.githubusercontent.com/25368596/39585310-dd6aff78-4eca-11e8-9c83-2858d9ff1f4d.png)

The controller logs have a repeating error of the kind:
```
2018-05-03 14:36:57,946 675370275 [controllerpool-44] ERROR i.p.c.s.stream.PersistentStreamBase - scale input invalid [4604] [0.1706574888245243=0.4395872725666938, 0.4395872725666938=0.7085170563088632]
2018-05-03 14:36:57,946 675370275 [controllerpool-44] WARN  i.p.c.s.e.r.ScaleOperationTask - processing scale request for hulk/midScale segments [4604] failed {}
io.pravega.controller.store.stream.ScaleOperationExceptions$ScaleInputInvalidException: null
    at io.pravega.controller.store.stream.PersistentStreamBase.lambda$null$69(PersistentStreamBase.java:489)
    at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
    at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
    at io.pravega.controller.store.stream.ZKStoreHelper.lambda$null$8(ZKStoreHelper.java:156)
    at io.pravega.controller.store.stream.ZKStoreHelper.lambda$callback$24(ZKStoreHelper.java:326)
    at org.apache.curator.framework.imps.Backgrounding$1$1.run(Backgrounding.java:158)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
2018-05-03 14:36:57,946 675370275 [controllerpool-72] WARN  i.p.c.e.i.ConcurrentEventProcessor - ConcurrentEventProcessor Processing failed java.util.concurrent.CompletionException
2018-05-03 14:36:57,951 675370280 [controllerpool-72] ERROR i.p.c.e.i.ConcurrentEventProcessor - ConcurrentEventProcessor Processing failed, exiting {}
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.ScaleOperationExceptions$ScaleInputInvalidException
    at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
    at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
    at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
    at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:899)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
    at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
    at io.pravega.controller.eventProcessor.impl.SerializedRequestHandler.lambda$run$1(SerializedRequestHandler.java:94)
...
```
The scaling-events API reports this segment as `{"number":4604,"epoch":3007,"start":1525197396380,"keyStart":0.1706574888245243,"keyEnd":0.7085170563088633}`,
so the key end is 
`0.7085170563088632` in the logs, but 
`0.7085170563088633` when reported by the controller API. 

**Problem location**
Controller

**Suggestions for an improvement**
There should be no input mismatch when processing a segment key range

**Comment by shiveshr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: Hot segment not scaling due to input mismatch](https://trello.com/c/8zsPTP7F/39-bug-hot-segment-not-scaling-due-to-input-mismatch)
