### ISSUE TITLE
StreamSegmentContainerTests failure

### ISSUE THREAD

**Issue by Prabha-Veerubhotla** [pravega/pravega#2555]
**Problem description**
Unit test failure : io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testExtendedAttributesConditionalUpdates

Stacktrace :
```
java.lang.AssertionError: Unexpected value for attribute 01257154-db51-4582-b998-5ce2da28681c for segment Segment_0 expected:<2> but was:<-9223372036854775808>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testExtendedAttributesConditionalUpdates(StreamSegmentContainerTests.java:516)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```
**Problem location**

**Suggestions for an improvement**

**Comment by RaulGracia** [comment]
I have been able to reproduce the error in my VM: with my current understanding, in `testExtendedAttributesConditionalUpdates` there is a `setSegmentMetadataExpiration` set to 250ms. In the case of having a powerful CPU machine, 250ms may be enough for allowing the code to reach `localContainer.triggerMetadataCleanup(segmentNames).get(TIMEOUT.toMillis(), TimeUnit.MILLISECONDS);` (line 512) and set up the callback that will be executed when each attribute expires. However, in a loaded or low CPU machine, this is not always the case and when some of the callbacks related to metadata expiration are lost, then the condition `if (remainingSegments.size() == 0)`(line 1863) is never met (infinite loop). In my VM, I increased the timeout to 1 second and now it works. Hope this helps.
