### ISSUE TITLE
Suppress spurious warnings from `AsyncSegmentInputStreamImpl` on close

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2599]
**Problem description**
When you close the reader, spurious warnings are emitted about the connection being closed.   

```
2018-05-17 00:55:08,644 WARN  io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl    - Exception while reading from Segment : examples/wordcount/0
io.pravega.client.stream.impl.ConnectionClosedException
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.close(AsyncSegmentInputStreamImpl.java:149)
	at io.pravega.client.segment.impl.SegmentInputStreamImpl.close(SegmentInputStreamImpl.java:242)
	at io.pravega.client.stream.impl.EventStreamReaderImpl.close(EventStreamReaderImpl.java:250)
	at io.pravega.connectors.flink.FlinkPravegaReader.run(FlinkPravegaReader.java:170)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:86)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:55)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.run(SourceStreamTask.java:94)
	at org.apache.flink.streaming.runtime.tasks.StoppableSourceStreamTask.run(StoppableSourceStreamTask.java:40)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:264)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:718)
	at java.lang.Thread.run(Thread.java:748)
```

**Problem location**
The spurious warning originates in `AsyncSegmentInputStreamImpl::read`.   

**Suggestions for an improvement**
If `ConnectionClosedException` is a planned event (as opposed to an unplanned connection failure) then perhaps the warning should simply not be emitted when that exception type is seen.  Also note that `SegmentInputStreamImpl::close` cancels the outstanding async request before closing the underlying async stream.

**Comment by EronWright** [comment]
A simple repro is to call `createReaderGroup`, which causes a spurious warning as briefly initializes the synchronizer stream:
```
10:23:55,868 WARN  io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl    - Exception while reading from Segment : examples/_RGflinkguijeycgx0nmpl2a1omd/0
io.pravega.client.stream.impl.ConnectionClosedException
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.close(AsyncSegmentInputStreamImpl.java:149)
	at io.pravega.client.segment.impl.SegmentInputStreamImpl.close(SegmentInputStreamImpl.java:242)
	at io.pravega.client.state.impl.RevisionedStreamClientImpl.close(RevisionedStreamClientImpl.java:201)
	at io.pravega.client.state.impl.StateSynchronizerImpl.close(StateSynchronizerImpl.java:251)
	at io.pravega.client.admin.impl.ReaderGroupManagerImpl.createReaderGroup(ReaderGroupManagerImpl.java:91)
	at io.pravega.connectors.flink.FlinkPravegaReader.createReaderGroup(FlinkPravegaReader.java:232)
```
