### ISSUE TITLE
High read latency when there is no backlog and idle segments

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2609]
**Problem description**
When reading a stream that has numerous segments, and a subset of those segments are idle (has no data), the `EventStreamReaderImpl` spends considerable time blocking on the idle segment(s), leading to poor overall read performance.

Below is a trace that demonstrates the issue.  This example involves a stream with two fixed segments, and works by creating a feedback loop involving a single routing key.   The program is writing to the same stream that it is reading from, therefore we expect to read back a given event almost immediately after writing it.  By using a single routing key, one of the two segments is always idle.

The poor performance stems from the fact that once the orderer selects a given segment, the reader blocks on that segment for up to one second (`TIME_UNIT`), even if data becomes available sooner on another segment.  In the example, the orderer examines all segments, realizes that none are readable without blocking, and then makes a round-robin selection.   Just afterward, data becomes available on the segment that wasn't selected, but the reader has already committed to a 1-second nap.

```
16:22:36,668 TRACE io.pravega.client.segment.impl.SegmentOutputStreamImpl        - Sending append request: Append(segment=examples/ourboros-bf24bb45-b31e-4879-afa6-fcbe4d892aea/0, writerId=51f7dbfc-f1a0-402f-bc52-6c9e436134e3, eventNumber=11, eventCount=1, data=UnpooledHeapByteBuf(ridx: 0, widx: 19, cap: 19/19), expectedLength=null)
16:22:36,669 TRACE io.pravega.client.stream.impl.EventStreamReaderImpl           - ENTER readNextEvent@1326077567568736 [].

  16:22:36,669 TRACE io.pravega.client.stream.impl.Orderer                         - ENTER nextSegment@1326077567732493 [].
    16:22:36,669 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - canReadWithoutBlocking false
    16:22:36,669 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - Filling buffer SegmentInputStreamImpl(asyncInput=io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl@992bc0f, readLength=65536, buffer=io.pravega.common.util.CircularBuffer@5a669c29, headerReadingBuffer=java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], offset=0, endOffset=9223372036854775807, receivedEndOfSegment=false, receivedTruncated=false, outstandingRequest=java.util.concurrent.CompletableFuture@2890521c[Not completed])
    16:22:36,669 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - canReadWithoutBlocking false
    16:22:36,669 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - Filling buffer SegmentInputStreamImpl(asyncInput=io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl@4b131692, readLength=65536, buffer=io.pravega.common.util.CircularBuffer@3a0901b8, headerReadingBuffer=java.nio.HeapByteBuffer[pos=8 lim=8 cap=8], offset=288, endOffset=9223372036854775807, receivedEndOfSegment=false, receivedTruncated=false, outstandingRequest=java.util.concurrent.CompletableFuture@498fb16d[Not completed])
  16:22:36,669 TRACE io.pravega.client.stream.impl.Orderer                         - LEAVE nextSegment@1326077567732493 (elapsed=166us).

  16:22:36,669 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - ENTER read@1326077567917282 [].
    16:22:36,669 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - Read called at offset 0
    16:22:36,669 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - Filling buffer SegmentInputStreamImpl(asyncInput=io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl@992bc0f, readLength=65536, buffer=io.pravega.common.util.CircularBuffer@5a669c29, headerReadingBuffer=java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], offset=0, endOffset=9223372036854775807, receivedEndOfSegment=false, receivedTruncated=false, outstandingRequest=java.util.concurrent.CompletableFuture@2890521c[Not completed])
    16:22:36,670 TRACE io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl    - Received read result WireCommands.SegmentRead(type=SEGMENT_READ, segment=examples/ourboros-bf24bb45-b31e-4879-afa6-fcbe4d892aea/0, offset=288, atTail=false, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=27 cap=27])
  16:22:37,675 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - LEAVE read@1326077567917282 (elapsed=1005457us).

  16:22:37,677 TRACE io.pravega.client.stream.impl.Orderer                         - ENTER nextSegment@1326078575627035 [].
    16:22:37,677 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - canReadWithoutBlocking true
  16:22:37,677 TRACE io.pravega.client.stream.impl.Orderer                         - LEAVE nextSegment@1326078575627035 (elapsed=92us).

  16:22:37,677 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - ENTER read@1326078575737608 [].
    16:22:37,677 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - Read called at offset 288
    16:22:37,677 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - Filling buffer SegmentInputStreamImpl(asyncInput=io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl@4b131692, readLength=65536, buffer=io.pravega.common.util.CircularBuffer@3a0901b8, headerReadingBuffer=java.nio.HeapByteBuffer[pos=8 lim=8 cap=8], offset=288, endOffset=9223372036854775807, receivedEndOfSegment=false, receivedTruncated=false, outstandingRequest=java.util.concurrent.CompletableFuture@498fb16d[Completed normally])
  16:22:37,677 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - LEAVE read@1326078575737608 (elapsed=212us).

  16:22:37,677 TRACE io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl    - Sending read request WireCommands.ReadSegment(type=READ_SEGMENT, segment=examples/ourboros-bf24bb45-b31e-4879-afa6-fcbe4d892aea/0, offset=315, suggestedLength=65536, delegationToken=)

16:22:37,678 TRACE io.pravega.client.stream.impl.EventStreamReaderImpl           - LEAVE readNextEvent@1326077567568736 (elapsed=1009001us).

...

16:22:37,679 TRACE io.pravega.client.stream.impl.EventStreamReaderImpl           - ENTER readNextEvent@1326078577418736 [].
16:22:37,679 TRACE io.pravega.client.stream.impl.Orderer                         - ENTER nextSegment@1326078577605328 [].
16:22:37,679 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - canReadWithoutBlocking false
16:22:37,679 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - Filling buffer SegmentInputStreamImpl(asyncInput=io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl@992bc0f, readLength=65536, buffer=io.pravega.common.util.CircularBuffer@5a669c29, headerReadingBuffer=java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], offset=0, endOffset=9223372036854775807, receivedEndOfSegment=false, receivedTruncated=false, outstandingRequest=java.util.concurrent.CompletableFuture@2890521c[Not completed])
16:22:37,679 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - canReadWithoutBlocking false
16:22:37,679 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - Filling buffer SegmentInputStreamImpl(asyncInput=io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl@4b131692, readLength=65536, buffer=io.pravega.common.util.CircularBuffer@3a0901b8, headerReadingBuffer=java.nio.HeapByteBuffer[pos=8 lim=8 cap=8], offset=315, endOffset=9223372036854775807, receivedEndOfSegment=false, receivedTruncated=false, outstandingRequest=java.util.concurrent.CompletableFuture@1783163f[Not completed])
16:22:37,679 TRACE io.pravega.client.stream.impl.Orderer                         - LEAVE nextSegment@1326078577605328 (elapsed=167us).
16:22:37,679 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - ENTER read@1326078577788314 [].
16:22:37,679 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - Read called at offset 0
16:22:37,679 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - Filling buffer SegmentInputStreamImpl(asyncInput=io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl@992bc0f, readLength=65536, buffer=io.pravega.common.util.CircularBuffer@5a669c29, headerReadingBuffer=java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], offset=0, endOffset=9223372036854775807, receivedEndOfSegment=false, receivedTruncated=false, outstandingRequest=java.util.concurrent.CompletableFuture@2890521c[Not completed])
16:22:37,680 TRACE io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl    - Received read result WireCommands.SegmentRead(type=SEGMENT_READ, segment=examples/ourboros-bf24bb45-b31e-4879-afa6-fcbe4d892aea/0, offset=315, atTail=false, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=27 cap=27])
16:22:38,681 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - LEAVE read@1326078577788314 (elapsed=1001515us).
16:22:38,681 TRACE io.pravega.client.stream.impl.Orderer                         - ENTER nextSegment@1326079579545161 [].
16:22:38,681 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - canReadWithoutBlocking true
16:22:38,681 TRACE io.pravega.client.stream.impl.Orderer                         - LEAVE nextSegment@1326079579545161 (elapsed=63us).
16:22:38,681 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - ENTER read@1326079579643715 [].
16:22:38,681 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - Read called at offset 315
16:22:38,681 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - Filling buffer SegmentInputStreamImpl(asyncInput=io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl@4b131692, readLength=65536, buffer=io.pravega.common.util.CircularBuffer@3a0901b8, headerReadingBuffer=java.nio.HeapByteBuffer[pos=8 lim=8 cap=8], offset=315, endOffset=9223372036854775807, receivedEndOfSegment=false, receivedTruncated=false, outstandingRequest=java.util.concurrent.CompletableFuture@1783163f[Completed normally])
16:22:38,681 TRACE io.pravega.client.segment.impl.SegmentInputStreamImpl         - LEAVE read@1326079579643715 (elapsed=150us).
16:22:38,681 TRACE io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl    - Sending read request WireCommands.ReadSegment(type=READ_SEGMENT, segment=examples/ourboros-bf24bb45-b31e-4879-afa6-fcbe4d892aea/0, offset=342, suggestedLength=65536, delegationToken=)
16:22:38,682 TRACE io.pravega.client.stream.impl.EventStreamReaderImpl           - LEAVE readNextEvent@1326078577418736 (elapsed=1002903us).
```

For reference: [EventStreamReaderImpl.java](https://github.com/pravega/pravega/blob/6e338b4a20072e834b51f62351716d7769a6725a/client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java#L83)

**Problem location**

**Suggestions for an improvement**
- Rework `EventStreamReaderImpl` to use async segment reads, using `CompletableFuture::anyOf` to wait for the next event from any assigned segment.
- Factor out the framing logic within `SegmentInputStreamImpl` to a new class, e.g. `AsyncFrameDecoderImpl`, that would decode in an async way to support the above.
- Reconcile the semantic irregularity between `SegmentInputStream` and `AsyncSegmentInputStream`; the latter produces raw segment data, the former deals with event framing.

**Comment by tkaitchuck** [comment]
What should our goal be in this case?

It already takes care of the case where one one the segments is non-empty. So if the reader is not at the tail of all segments there will be no delay.

It's trivial to change the constant but that's obviously a tradeoff against CPU. But what level is acceptable?
I don't relish the idea of implementing a selector, because that would necessarily break encapsulation and force bi-directional call stacks. 

Additionally how should ordering affect this. IE: If we have PDP-28 or some similar scheme, it seems likely that delays in such a case would be needed. What policy should we set for when and how they are acceptable?

**Comment by arvindkandhare** [comment]
> It already takes care of the case where one one the segments is non-empty. So if the reader is not at the tail of all segments there will be no delay.
There will be a delay if all the readers are at the tail of all the segments and then data becomes available on the segments on which the reader is not blocked. There is definite CPU cost if we solve this issue by just fiddling with the constant.

As @EronWright suggests, I think this is the right way to fix this:
```
Rework EventStreamReaderImpl to use async segment reads, using CompletableFuture::anyOf to wait for the next event from any assigned segment.
```

**Comment by EronWright** [comment]
I made some incremental progress on reworking `EventStreamReaderImpl` to directly use async segment reads.  I particular I wrote `AsyncSegmentFrameDecoder` that provides an async, event-oriented interface over `AsyncSegmentInputStream`.

I envision the next step being to rework `EventStreamReaderImpl` to maintain a collection of decoders and associated future reads, and then to leverage `CompletableFuture::anyOf` to block on available data.

Feedback welcome:
https://github.com/pravega/pravega/compare/issue-2609-async-eventreader?expand=1

**Comment by EronWright** [comment]
To assess the severity of the issue, I suppose one could add a metric to `EventStreamReaderImpl::read` to ascertain whether the blocking time is reasonable given the workload.

**Comment by jkhalack** [comment]
I started a longevity test with the above branch (three writers, three readers, autoscaling triggered by the event rate, pravega auth turned off) and got one of the readers die 21 minutes into the test with an error: 
```
2018-05-28 18:30:24,661 1206381 [pool-8-thread-1] ERROR c.e.n.h.t.w.readers.PravegaReader - Reader finished with Error
io.pravega.common.ObjectClosedException: Object 'AsyncSegmentInputStreamImpl' has been closed and cannot be accessed anymore.
	at io.pravega.common.Exceptions.checkNotClosed(Exceptions.java:230)
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.read(AsyncSegmentInputStreamImpl.java:160)
	at io.pravega.client.segment.impl.AsyncSegmentEventReaderImpl.issueRequest(AsyncSegmentEventReaderImpl.java:295)
	at io.pravega.client.segment.impl.AsyncSegmentEventReaderImpl.handleRequest(AsyncSegmentEventReaderImpl.java:335)
	at io.pravega.client.segment.impl.AsyncSegmentEventReaderImpl.issueRequestIfNeeded(AsyncSegmentEventReaderImpl.java:283)
	at io.pravega.client.segment.impl.AsyncSegmentEventReaderImpl.readAsync(AsyncSegmentEventReaderImpl.java:128)
	at io.pravega.client.stream.impl.EventStreamReaderImpl$AcquiredReader.readNext(EventStreamReaderImpl.java:348)
	at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:130)
	at com.emc.nautilus.hulk.taskexecutor.workers.readers.PravegaReader.start(PravegaReader.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
(Hope this helps)

**Comment by jkhalack** [comment]
Since we started measuring the time lag between event write time and and the read time, we observe that the tail readers are not getting more than 2 seconds behind under the normal flow.
