### ISSUE TITLE
Build failure: SynchronousStreamSegmentStoreTests.testEndToEndWithFencing 

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#2621]
**Problem description**

```
io.pravega.segmentstore.server.mocks.SynchronousStreamSegmentStoreTests > testEndToEndWithFencing FAILED
    io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.ExecutionException: io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment 'Segment_0#transaction.5cd2bd074e1547518ab82445d58e8770'] The StreamSegment does not exist.

        Caused by:
        java.util.concurrent.ExecutionException: io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment 'Segment_0#transaction.5cd2bd074e1547518ab82445d58e8770'] The StreamSegment does not exist.

            Caused by:
            io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment 'Segment_0#transaction.5cd2bd074e1547518ab82445d58e8770'] The StreamSegment does not exist.
```
**Problem location**
SynchronousStreamSegmentStoreTests 

**Suggestions for an improvement**
Fix the issue

**Comment by shrids** [comment]
Observing this issue in the latest build... 
(Based on my understanding PR: https://github.com/pravega/pravega/pull/2630 should fix it)
```
io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment 'Segment_3#transaction.05666b39a7b74aeb982291e2ff681835'] The StreamSegment does not exist.
	at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:193)
	at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.checkReads(StreamSegmentStoreTestBase.java:617)
	at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.testEndToEndWithFencing(StreamSegmentStoreTestBase.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)```

**Comment by andreipaduroiu** [comment]
tracking with #2629
