### ISSUE TITLE
Reader group initialization should respect truncation point

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2644]
**Problem description**
When a reader group is created (or reset) with a configuration not containing a start position, the start position is implicitly set to the head of the stream.   Issue: the underlying calculation is not respecting segment truncation and simply assumes an offset of zero for the available segments.   In reality the offset may be non-zero.  

The issue causes a truncation exception, such as seen below (following a reset of the RG with name `hulksmallScaleforgetful0`).  Observe that the initial offset of `hulk/smallScale/53` is `0` yet the subsequent response of `SegmentIsTruncated` makes clear that `startOffset` is `1189328`.

```
2018-05-30 00:36:13,589 10806536 [pool-8-thread-4] INFO  c.e.n.h.t.w.readers.PravegaReader - Added Reader HulkSmallScale7d669bdb9f2f4e7fbd9c35969f9ec4f9 To ReaderGroup hulksmallScaleforgetful0

2018-05-30 00:36:13,602 10806549 [pool-8-thread-4] INFO  i.p.c.s.impl.EventStreamReaderImpl - EventStreamReaderImpl( id=HulkSmallScale7d669bdb9f2f4e7fbd9c35969f9ec4f9) acquiring segments {hulk/smallScale/76=0, hulk/smallScale/79=0, hulk/smallScale/74=0, hulk/smallScale/70=0, hulk/smallScale/96=0, hulk/smallScale/97=0, hulk/smallScale/98=0, hulk/smallScale/67=0, hulk/smallScale/92=0, hulk/smallScale/93=0, hulk/smallScale/94=0, hulk/smallScale/95=0, hulk/smallScale/88=0, hulk/smallScale/89=0, hulk/smallScale/90=0, hulk/smallScale/58=0, hulk/smallScale/91=0, hulk/smallScale/84=0, hulk/smallScale/53=0, hulk/smallScale/86=0, hulk/smallScale/87=0, hulk/smallScale/81=0, hulk/smallScale/82=0}

2018-05-30 00:36:14,028 10806975 [epollEventLoopGroup-5-4] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Received segmentIsTruncated WireCommands.SegmentIsTruncated(type=SEGMENT_IS_TRUNCATED, requestId=0, segment=hulk/smallScale/53, startOffset=1189328)
2018-05-30 00:36:14,028 10806975 [epollEventLoopGroup-5-4] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/53
io.pravega.client.segment.impl.SegmentTruncatedException: null
```

**Problem location**
`ReaderGroupImpl::getSegmentsForStreams` -> `ControllerService::getSegmentsAtTime`

**Suggestions for an improvement**
- Adjust `ControllerService::getSegmentsAtTime` to return the `startOffset` of the respective segment.
- undo the duplicative logic that was added to BatchClient in #2551

**Comment by RaulGracia** [comment]
Related issue: https://github.com/pravega/pravega/issues/2546

**Comment by Prabha-Veerubhotla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Correct the number of segments for request stream](https://trello.com/c/3JLxWxFn/46-correct-the-number-of-segments-for-request-stream)

**Comment by jkhalack** [comment]
This is what happens now on a scaling test with one reader group consisting of one forgetful reader (it starts off as a TAIL reader, then gets reset to read from the beginning).

The last truncation happens here:
```
2018-06-04 22:00:58,014 11284431 [controllerpool-72] INFO  i.p.c.s.e.r.TruncateStreamTask - Truncating stream hulk/smallScaleOld at stream cut: {96=238497, 97=239645, 98=248542, 99=225582, 68=1208557, 100=235627, 101=458913, 102=159285, 77=0, 79=0, 82=844354, 83=576583, 84=566251, 85=557354, 86=574287, 87=0, 90=538699, 91=564242, 92=534394, 93=569121, 94=580027, 95=572278}
```

The Reader is asked to reset while at this position:
```
2018-06-04 22:03:10,231 10807488 [pool-8-thread-1] INFO  c.e.n.h.t.w.readers.PravegaReader - Resetting ReaderGroup hulksmallScaleOldforgetful0 at position hulk/smallScaleOld/128=1000482, hulk/smallScaleOld/116=0, hulk/smallScaleOld/107=1639631, hulk/smallScaleOld/131=678468, hulk/smallScaleOld/133=655508, hulk/smallScaleOld/122=0, hulk/smallScaleOld/143=927584, hulk/smallScaleOld/132=0, hulk/smallScaleOld/121=642593, hulk/smallScaleOld/124=0, hulk/smallScaleOld/123=648620, hulk/smallScaleOld/148=626234, hulk/smallScaleOld/147=617624, hulk/smallScaleOld/125=658091, hulk/smallScaleOld/151=596960, hulk/smallScaleOld/150=0
```

Then there is a bunch of `segmentIsTruncated` messages on segments from the last stream cut:
```
2018-06-04 22:03:10,952 10808209 [epollEventLoopGroup-5-1] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Received segmentIsTruncated WireCommands.SegmentIsTruncated(type=SEGMENT_IS_TRUNCATED, requestId=0, segment=hulk/smallScaleOld/85, startOffset=557354)
2018-06-04 22:03:10,953 10808210 [epollEventLoopGroup-5-1] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScaleOld/85
io.pravega.client.segment.impl.SegmentTruncatedException: null
...
2018-06-04 22:03:10,986 10808243 [epollEventLoopGroup-5-2] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Received segmentIsTruncated WireCommands.SegmentIsTruncated(type=SEGMENT_IS_TRUNCATED, requestId=0, segment=hulk/smallScaleOld/86, startOffset=574287)
2018-06-04 22:03:10,987 10808244 [epollEventLoopGroup-5-2] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScaleOld/86
o.pravega.client.segment.impl.SegmentTruncatedException: null
...
2018-06-04 22:03:11,008 10808265 [epollEventLoopGroup-5-3] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Received segmentIsTruncated WireCommands.SegmentIsTruncated(type=SEGMENT_IS_TRUNCATED, requestId=0, segment=hulk/smallScaleOld/91, startOffset=564242)
2018-06-04 22:03:11,008 10808265 [epollEventLoopGroup-5-3] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScaleOld/91
io.pravega.client.segment.impl.SegmentTruncatedException: null
...
```

Then there is an error for (empty) segment 122 that is about to be sealed (actually happened at 22:04:10 in the  controller log):
```
2018-06-04 22:04:03,056 10860313 [epollEventLoopGroup-5-13] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Closing connection to segment hulk/smallScaleOld/122 with exception: {}
io.pravega.shared.protocol.netty.ConnectionFailedException: null
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.connectionDropped(AsyncSegmentInputStreamImpl.java:60)
	at io.pravega.client.netty.impl.ClientConnectionInboundHandler.channelUnregistered(ClientConnectionInboundHandler.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
...
2018-06-04 22:04:03,056 10860313 [epollEventLoopGroup-5-13] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Connection failed due to a io.pravega.shared.protocol.netty.ConnectionFailedException. Read requests will be retransmitted.
2018-06-04 22:04:03,058 10860315 [epollEventLoopGroup-5-13] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScaleOld/122
io.pravega.shared.protocol.netty.ConnectionFailedException: null
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.connectionDropped(AsyncSegmentInputStreamImpl.java:60)
	at io.pravega.client.netty.impl.ClientConnectionInboundHandler.channelUnregistered(ClientConnectionInboundHandler.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
...
```
Then things go normally for a while, and later we see this (segment `85` makes sense, but the `null`s don't) :
```
2018-06-04 22:04:52,674 10909931 [pool-8-thread-1] INFO  i.p.c.s.i.SegmentMetadataClientImpl - Closing segment metadata connection for hulk/smallScaleOld/85
2018-06-04 22:04:52,674 10909931 [pool-8-thread-1] INFO  i.p.c.s.i.SegmentMetadataClientImpl - Closing connection with exception: null
2018-06-04 22:04:52,674 10909931 [pool-8-thread-1] INFO  i.p.client.netty.impl.RawClient - Closing connection with exception: null
2018-06-04 22:04:52,680 10909937 [pool-8-thread-1] ERROR c.e.n.h.t.w.readers.PravegaReader - Reader finished with Error
io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
	at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$6(Retry.java:245)
	at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at io.pravega.client.netty.impl.RawClient.closeConnection(RawClient.java:111)
	at io.pravega.client.netty.impl.RawClient.access$200(RawClient.java:35)
	at io.pravega.client.netty.impl.RawClient$ResponseProcessor.connectionDropped(RawClient.java:62)
	at io.pravega.client.netty.impl.ClientConnectionInboundHandler.channelUnregistered(ClientConnectionInboundHandler.java
...
```

Then there is this error about reader positions mismatch, so the reader has not been reassigned :
```
2018-06-04 22:04:52,739 10909996 [pool-8-thread-1] ERROR c.e.n.h.t.w.readers.PravegaReader - Couldn't cleanup finished reader HulkSmallScaleOld19c461ab474f44dcbe3cd9412213c982 at position hulk/smallScaleOld/128=1000482, hulk/smallScaleOld/116=0, hulk/smallScaleOld/107=1639631, hulk/smallScaleOld/131=678468, hulk/smallScaleOld/133=655508, hulk/smallScaleOld/122=0, hulk/smallScaleOld/143=927584, hulk/smallScaleOld/132=0, hulk/smallScaleOld/121=642593, hulk/smallScaleOld/124=0, hulk/smallScaleOld/123=648620, hulk/smallScaleOld/148=626234, hulk/smallScaleOld/147=617624, hulk/smallScaleOld/125=658091, hulk/smallScaleOld/151=596960, hulk/smallScaleOld/150=0
java.lang.IllegalArgumentException: When shutting down a reader: Given position does not match the segments it was assigned: 
[hulk/smallScaleOld/87, hulk/smallScaleOld/85, hulk/smallScaleOld/86, hulk/smallScaleOld/91, hulk/smallScaleOld/92, hulk/smallScaleOld/90, hulk/smallScaleOld/95, hulk/smallScaleOld/96, hulk/smallScaleOld/93, hulk/smallScaleOld/94, hulk/smallScaleOld/99, hulk/smallScaleOld/100, hulk/smallScaleOld/68, hulk/smallScaleOld/97, hulk/smallScaleOld/98, hulk/smallScaleOld/101, hulk/smallScaleOld/102, hulk/smallScaleOld/79, hulk/smallScaleOld/77, hulk/smallScaleOld/83, hulk/smallScaleOld/84, hulk/smallScaleOld/82] 
 vs 
 [hulk/smallScaleOld/151, hulk/smallScaleOld/150, hulk/smallScaleOld/123, hulk/smallScaleOld/124, hulk/smallScaleOld/121, hulk/smallScaleOld/122, hulk/smallScaleOld/128, hulk/smallScaleOld/125, hulk/smallScaleOld/131, hulk/smallScaleOld/132, hulk/smallScaleOld/133, hulk/smallScaleOld/107, hulk/smallScaleOld/143, hulk/smallScaleOld/147, hulk/smallScaleOld/148, hulk/smallScaleOld/116]
	at io.pravega.client.stream.impl.ReaderGroupStateManager.lambda$readerShutdown$1(ReaderGroupStateManager.java:148)
	at io.pravega.client.state.impl.StateSynchronizerImpl.lambda$updateState$0(StateSynchronizerImpl.java:137)
	at io.pravega.client.state.impl.StateSynchronizerImpl.conditionallyWrite(StateSynchronizerImpl.java:218)
	at io.pravega.client.state.impl.StateSynchronizerImpl.updateState(StateSynchronizerImpl.java:135)
	at io.pravega.client.stream.impl.ReaderGroupStateManager.readerShutdown(ReaderGroupStateManager.java:139)
	at io.pravega.client.stream.impl.ReaderGroupImpl.readerOffline(ReaderGroupImpl.java:94)
	at com.emc.nautilus.hulk.taskexecutor.workers.readers.PravegaReader.finished(PravegaReader.java:154)
	at com.emc.nautilus.hulk.taskexecutor.workers.readers.PravegaReader.start(PravegaReader.java:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2018-06-04 22:04:52,740 10909997 [pool-8-thread-1] ERROR c.e.n.h.t.w.r.ReaderWorkerManager - Reader Finished with Error
io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
	at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$6(Retry.java:245)
	at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at io.pravega.client.netty.impl.RawClient.closeConnection(RawClient.java:111)
	at io.pravega.client.netty.impl.RawClient.access$200(RawClient.java:35)
```



[thor.smalScaleOld.controller_server_2018-06-04.17.log](https://github.com/pravega/pravega/files/2073535/thor.smalScaleOld.controller_server_2018-06-04.17.log)

[pravega-pravega_controller.txt](https://github.com/pravega/pravega/files/2073554/pravega-pravega_controller--572b8b31-d678-4b47-8ae5-a9a344bf46fe.txt)

**Comment by shrids** [comment]
https://github.com/pravega/pravega/blob/master/test/integration/src/test/java/io/pravega/test/integration/BoundedStreamReaderTest.java#L293

This test verifies the behavior of a Reader Group which is reset using the `ReaderGroup.resetReaderGroup(..)`.
The test truncates the stream at `offset 60` and resets the ReaderGroup (api: `resetReaderGroup(..)`) to a start `StreamCut` pointing to `offset 30`. 

Now when the reader (`reader2`) invokes `readNextEvent(..)` it will receive a `TruncatedDataException` indicating to the user that the stream was truncated. A subsequent read will ensure that the next available event is read by the reader.

The behavior of the current code is similar if `ReaderGroup.resetReaderGroup(..)` is invoked without providing the start stream cuts.

i.e.
```
 rg.resetReaderGroup(ReaderGroupConfig.builder().disableAutomaticCheckpoints()
                                             .stream(Stream.of(SCOPE, STREAM3))
                                             .build());
			
...			
 assertThrows(TruncatedDataException.class, () -> reader2.readNextEvent(10000)); 
 //subsequent read should return data present post truncation, Event3 is returned here since stream was truncated @ offset 30 * 2.
 readAndVerify(reader2, 3);
```

So the issue here is that since the resetReaderGroup was not bounded (no custom streamCuts) there should be no `TruncatedDataException` because the user didn't actually specify a point that was truncated away. 
(Also, this change would reduce the number of calls to the SegmentStore to find right offset for HEAD StreamCut in BatchClient.)

**Comment by fpj** [comment]
@shrids I don't understand what this is saying:

> So the issue here is that since the resetReaderGroup was not bounded (no custom streamCuts) there should be no TruncatedDataException because the user didn't actually specify a point that was truncated away.
> (Also, this change would reduce the number of calls to the SegmentStore to find right offset for HEAD StreamCut in BatchClient.)

The behavior is that we throw truncated exception in the case no start position is provided so that the application is aware that some data is gone, but we still enable the application to continue reading if it chooses too. What are suggesting precisely?

**Comment by shrids** [comment]
Yes, the behavior is that the readers throw a `SegmentTruncatedException`on seeing that the stream is truncated and on a retry it will read from the next available offset.

**Comment by jkhalack** [comment]
With my above comment I tried to provide the logs on where the truncation point was, where the reader group was trying to be reset to (just segments, no offsets), and what happened as a result.

**Comment by jkhalack** [comment]
I agree that the readers that start from an **arbitrary** stream cut should be informed about truncation, so `SegmentTruncationException` would be a good way of doing that.
However, the reader groups reinitialized by Pravega to the current HEAD of the stream should be provided with the stream cut that takes the truncation into the account so that they should not get into a situation where they encounter `SegmentTruncationException` right after being reset .

**Comment by jkhalack** [comment]
> Yes, the behavior is that the readers throw a SegmentTruncatedException on seeing that the stream is truncated and on a retry it will read from the next available offset.

How should the code look like then?
Right now we are doing
```
           ReaderGroupConfig resetConfig = ReaderGroupConfig.builder()
                .disableAutomaticCheckpoints()
                .stream(readerGroup.getScope() + "/" + stream)
                .build();
            LOG.info("Resetting ReaderGroup {} at position {}", readerGroup.getGroupName(), lastPosition);
            readerGroup.resetReaderGroup(resetConfig);
```
and then for the reader (there is only one reader in the reader group):
```
       ReaderConfig readerConfig = ReaderConfig.builder()
            .build();

       eventStreamReader = clientFactory.createReader(readerId, readerGroup.getGroupName(), SERIALIZER, readerConfig);
```

How do we get the **offset** information to feed it to the reader?

**Comment by EronWright** [comment]
@fpj says:
> The behavior is that we throw truncated exception in the case no start position is provided so that the application is aware that some data is gone, but we still enable the application to continue reading if it chooses too.

Despite the design goal mentioned by Flavio, Pravega does not reliably produce a truncated exception when the client attempts to read from the head of a truncated stream.  For example, if a 'clean' truncation occurred wherein old segments were dropped but no segments were partially truncated, then the client would not receive a truncation exception; it would simply read from the head. 

I agree with @jkhalack's statement that, in the absence of a specific start point, the semantic should be 'earliest available' as opposed to 'absolute zero':
> I agree that the readers that start from an arbitrary stream cut should be informed about truncation, so SegmentTruncationException would be a good way of doing that.
However, the reader groups reinitialized by Pravega to the current HEAD of the stream should be provided with the stream cut that takes the truncation into the account so that they should not get into a situation where they encounter SegmentTruncationException right after being reset.

**Comment by shrids** [comment]
> How do we get the offset information to feed it to the reader?

There is no need to provide offset information to the reader.  Invoking the `readNextEvent()` again after receiving the `TruncatedDataException` the reader will read the next available data.

The below flow describes the steps that need be performed when resetReaderGroup is invoked. 

1. Reset the reader group.
```
rg.resetReaderGroup(ReaderGroupConfig.builder().disableAutomaticCheckpoints()
                                             .stream(Stream.of(SCOPE, STREAM3))
                                             .build());
```
2.  All existing readers will throw a `ReinitializationException` on  performing `existingReader.readNextEvent()` post a `resetReaderGroupOperation`.    On this exception close the existingReader  `existingReader.close()` and create a new readers.

3. Create a new Reader.
```
EventStreamReader<String> reader = clientFactory.createReader("readerId2", "group", serializer,
                ReaderConfig.builder().build());
```
4. Invoke `reader.readNextEvent( timeout)` 

- Step 4 will throw a `TruncatedDataException` if the reader observes that the Segment it is reading from is truncated. 

5.  Invoking `reader.readNextEvent(timeout)` again would read from the next available data. 
i.e. if no action needs to be taken on receiving `TruncatedDataExcecption` then this exception can be ignored and reader.readNextEvent() can be invoked again to fetch the next available data.

**Comment by jkhalack** [comment]
In case when there is more than one segment per reader (like we have 20+ segments and only one reader in our test), there would be more than one `TruncatedDataException` thrown at one reader after initializing the reader group to a truncated head. 
So `reader.readNextEvent(timeout)` in step 5 can either throw another `TruncatedDataException` or give a normal read, depending on whether the reader would try to read the next event from another segment or from the new one. And then there could/would be another exception thrown in steps 6, and so on... 

As an app would not know the number of segments that would be assigned to one reader after initializing to a truncated head, there is no way to know the number of times the `TruncatedDataException` should be simply caught.

Maybe I'm missing something though and there is a way to distinguish between the  `TruncatedDataException` got by a reader when it gets initialized to a truncated head and when it gets such exception in the middle of the stream when acting as a TAIL reader (the latter definitely should not be just caught with `reader.readNextEvent( timeout)`).

**Comment by jkhalack** [comment]
I see the point that the app should be informed if a reader group gets initialized to a truncated head.
However, there should be an option for it to get the stream cut information with all the correct offsets for the new readers to start from existing data points without any extra hassle?

For example, is it possible for the default `rg.resetReaderGroup(...)` to throw something like `TruncatedStreamException` and then the app would have an option to catch this exception and knowingly call `rg.resetReaderGroupWithTruncation(...)` (or something like that) to start the readers from the exact streamCut were the data was truncated?

**Comment by jkhalack** [comment]
We added a try/catch block to catch all instances of `TruncatedDataException` on  `reader.readNextEvent(...)`. It did not help. 
The reader never gets the exception. Then it fails with the same scenario that I posted  above.

**Comment by shrids** [comment]
From `phalanx.smallScale.controller-server.June_20.log` file.
```
2018-06-20 20:56:26,171 6111592 [pool-8-thread-4] ERROR c.e.n.h.t.w.readers.PravegaReader - Reader finished with Error
io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
	at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$6(Retry.java:245)
	at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
```
This is similar to issue #2658 .

**Comment by jkhalack** [comment]
A log from another test that only had one reader group consisting of one reader that was being reset to the head (hopefully it is easier to debug)
[phalanx.smallScaleOld.controller_server_2018-06-21.0.log](https://github.com/pravega/pravega/files/2127463/phalanx.smallScaleOld.controller_server_2018-06-21.0.log)

**Comment by shrids** [comment]
Thanks for posting this log, will look into it in more detail.
The reader failed with 
```
2018-06-21 15:59:58,478 10908715 [pool-8-thread-1] ERROR c.e.n.h.t.w.readers.PravegaReader - Reader finished with Error
io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
	at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$6(Retry.java:245)
	at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
```
This is similar to issue #2658

**Comment by shiveshr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 2644: Controller sends default offset (0) even for segments involved in truncation point](https://trello.com/c/2TEo2xiL/40-issue-2644-controller-sends-default-offset-0-even-for-segments-involved-in-truncation-point)
