### ISSUE TITLE
Exceptions during unmarshalling of grpc auth headers pollute logs

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2653]
**Problem description**
These harmless exceptions are polluting the logs.
```
2018-05-25 16:51:00,826 2784156 [grpc-default-executor-19] WARN  i.p.c.s.rpc.auth.PravegaInterceptor - Error while marshalling some of the headers
java.lang.IllegalArgumentException: ASCII header is named grpc-trace-bin.  Only binary headers may end with -bin
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:146)
    at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:740)
    at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:734)
    at io.grpc.Metadata$Key.of(Metadata.java:591)
    at io.grpc.Metadata$Key.of(Metadata.java:587)
    at io.pravega.controller.server.rpc.auth.PravegaInterceptor.lambda$interceptCall$0(PravegaInterceptor.java:55)
    at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at io.pravega.controller.server.rpc.auth.PravegaInterceptor.interceptCall(PravegaInterceptor.java:52)
    at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:229)
    at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startCall(ServerImpl.java:520)
    at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$1700(ServerImpl.java:345)
    at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInContext(ServerImpl.java:460)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
```

**Problem location**
`PravegaInterceptor.java`. 

**Suggestions for an improvement**
Drop the log or move it to `trace`.

**Comment by tkaitchuck** [comment]
Why are these errors happening?
Can we prevent the exception?

**Comment by arvindkandhare** [comment]
1. Reduced the log to a single line
2. Filtered the binary keys out
