### ISSUE TITLE
Readers failing with RetriesExhaustedException on empty segments

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#2658]
**Problem description**
![screen shot 2018-06-04 at 5 12 31 pm](https://user-images.githubusercontent.com/25368596/40939252-8559cbde-681a-11e8-8f3b-78b8e9173fb4.png)

On a stream with dynamic scaling, number of routing keys smaller than the average number of active segments (so that some segments remain empty), and time limited retention policy we see readers failing with 
```
2018-06-04 14:16:45,137 5216698 [pool-8-thread-3] ERROR c.e.n.h.t.w.readers.PravegaReader - Reader finished with Error
java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
	at java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
	at java.util.concurrent.CompletableFuture.join(Unknown Source)
	at io.pravega.client.segment.impl.SegmentInputStreamImpl.handleRequest(SegmentInputStreamImpl.java:179)
	at io.pravega.client.segment.impl.SegmentInputStreamImpl.readEventData(SegmentInputStreamImpl.java:148)
	at io.pravega.client.segment.impl.SegmentInputStreamImpl.read(SegmentInputStreamImpl.java:119)
	at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:104)
	at com.emc.nautilus.hulk.taskexecutor.workers.readers.PravegaReader.start(PravegaReader.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
	at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$6(Retry.java:245)
	at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.failAllInflight(AsyncSegmentInputStreamImpl.java:239)
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.closeConnection(AsyncSegmentInputStreamImpl.java:211)
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.access$100(AsyncSegmentInputStreamImpl.java:40)
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.connectionDropped(AsyncSegmentInputStreamImpl.java:60)
	at io.pravega.client.netty.impl.ClientConnectionInboundHandler.channelUnregistered(ClientConnectionInboundHandler.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1337)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:835)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:830)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	... 1 common frames omitted
```

Before the failure, there are a lot of exceptions while trying to connect to empty segments:
```
2018-06-04 14:16:45,119 5216680 [epollEventLoopGroup-5-8] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Closing connection to segment hulk/smallScaleYoung/16 with exception: {}
io.pravega.shared.protocol.netty.ConnectionFailedException: null
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.connectionDropped(AsyncSegmentInputStreamImpl.java:60)
	at io.pravega.client.netty.impl.ClientConnectionInboundHandler.channelUnregistered(ClientConnectionInboundHandler.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1337)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:835)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:830)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Unknown Source)
```

[namor.smallScaleYoung.controller_server_2018-06-04.14.log](https://github.com/pravega/pravega/files/2069819/namor.smallScaleYoung.controller_server_2018-06-04.14.log)

**Problem location**
Client

**Suggestions for an improvement**
Readers should keep reading when encountering empty segments

**Comment by shrids** [comment]
From the client logs posted it can be seen that the connection to the SegmentStore is disconnected. 
```
2018-06-04 14:16:45,119 5216680 [epollEventLoopGroup-5-8] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScaleYoung/16
io.pravega.shared.protocol.netty.ConnectionFailedException: null
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.connectionDropped(AsyncSegmentInputStreamImpl.java:60)
```
The segment store drops the connection in case of an error. 
Could you share the segmentstore logs?

**Comment by shrids** [comment]
Logs: [ReadersThrowingRetriesExhaustedException.zip](https://github.com/pravega/pravega/files/2127943/ReadersThrowingRetriesExhaustedException.zip)


1. Hulk logs: Reader failed with Error.
```
2018-06-22 13:02:39,537 10909195 [epollEventLoopGroup-5-14] DEBUG i.p.client.netty.impl.RawClient - Sending request: WireCommands.GetStreamSegmentInfo(type=GET_STREAM_SEGMENT_INFO, requestId=9, segmentName=hulk/smallScaleOld/59.#epoch.32, delegationToken=null)
2018-06-22 13:02:39,539 10909197 [epollEventLoopGroup-5-14] INFO  i.p.client.netty.impl.RawClient - Closing connection with exception: null
2018-06-22 13:02:39,540 10909198 [pool-8-thread-1] INFO  i.p.c.s.i.SegmentMetadataClientImpl - Closing segment metadata connection for hulk/smallScaleOld/59.#epoch.32
2018-06-22 13:02:39,540 10909198 [pool-8-thread-1] INFO  i.p.c.s.i.SegmentMetadataClientImpl - Closing connection with exception: null
2018-06-22 13:02:39,540 10909198 [pool-8-thread-1] INFO  i.p.client.netty.impl.RawClient - Closing connection with exception: null
2018-06-22 13:02:39,542 10909200 [pool-8-thread-1] ERROR c.e.n.h.t.w.readers.PravegaReader - Reader finished with Error
io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
        at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$6(Retry.java:245)
        at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
        at io.pravega.client.netty.impl.RawClient.closeConnection(RawClient.java:111)
        at io.pravega.client.netty.impl.RawClient.access$200(RawClient.java:35)
        at io.pravega.client.netty.impl.RawClient$ResponseProcessor.connectionDropped(RawClient.java:62)
        at io.pravega.client.netty.impl.ClientConnectionInboundHandler.channelUnregistered(ClientConnectionInboundHandler.java:86)
		
```

2. The reader tried many times to fetch information about this segment and failed.

```
2018-06-22 13:02:09,510 10879168 [epollEventLoopGroup-5-13] DEBUG i.p.client.netty.impl.RawClient - Sending request: WireCommands.GetStreamSegmentInfo(type=GET_STREAM_SEGMENT_INFO, requestId=8, segmentName=hulk/smallScaleOld/59.#epoch.32, delegationToken=null)
2018-06-22 13:02:09,511 10879169 [epollEventLoopGroup-5-13] INFO  i.p.client.netty.impl.RawClient - Closing connection with exception: null
2018-06-22 13:02:09,511 10879169 [epollEventLoopGroup-5-13] DEBUG io.pravega.common.util.Retry - Retrying command. Retry #9, timestamp=2018-06-22T13:02:09.511Z

```

3. There are no error logs on the PravegaRequestProcessor indicating why the connection to this segment was closed.
```
Line 3495: 2018-06-22 12:37:56,661 10008533 [core-28] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[15]: MapStreamSegment SegmentId = 4911, Name = 'hulk/smallScaleOld/59.#epoch.32', Active = 5
Line 7179: 2018-06-22 13:00:58,244 11390116 [core-4] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[15]: MapStreamSegment SegmentId = 4911, Name = 'hulk/smallScaleOld/59.#epoch.32', Active = 3
Line 7180: 2018-06-22 13:00:58,244 11390116 [core-4] INFO  i.p.s.server.CacheManager - CacheManager Registered ReadIndex[15-4911] (hulk/smallScaleOld/59.#epoch.32).
Line 8722: 2018-06-22 13:06:36,990 11728862 [core-6] INFO  i.p.s.server.CacheManager - CacheManager Unregistered ReadIndex[15-4911] (hulk/smallScaleOld/59.#epoch.32).
```

@tkaitchuck The PravegaRequestProcessor logs do not inform the reason on why the connection was closed, Could you check it too?

**Comment by shrids** [comment]
The connections are closed due to `delegationToken` being empty. Since the connection is closed the reader retries to connect and then throws a `RetriesExhaustedException` after all the configured retries have failed.

```
2018-06-22 19:58:24,070 6689361 [epollEventLoopGroup-3-7] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Processing request: WireCommands.GetStreamSegmentInfo(type=GET_STREAM_SEGMENT_INFO, requestId=9, segmentName=hulk/smallScaleOld/5.#epoch.3, delegationToken=)
2018-06-22 19:58:24,071 6689362 [epollEventLoopGroup-3-7] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection:
        at io.pravega.segmentstore.server.host.delegationtoken.TokenVerifierImpl.verifyToken(TokenVerifierImpl.java:36)
        at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:541)
        at io.jsonwebtoken.lang.Assert.hasText(Assert.java:135)
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:479)
        at io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor.getStreamSegmentInfo(PravegaRequestProcessor.java:348)
        at io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor.verifyToken(PravegaRequestProcessor.java:182)
        at io.pravega.shared.protocol.netty.DelegatingRequestProcessor.getStreamSegmentInfo(DelegatingRequestProcessor.java:60)
        at io.pravega.segmentstore.server.host.handler.ServerConnectionInboundHandler.channelRead(ServerConnectionInboundHandler.java:46)
        at io.pravega.shared.protocol.netty.WireCommands$GetStreamSegmentInfo.process(WireCommands.java:860)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
...

```
```
2018-06-22 13:00:58,272 11390144 [epollEventLoopGroup-3-13] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection: 
java.lang.IllegalArgumentException: JWT String argument cannot be null or empty.
	at io.jsonwebtoken.lang.Assert.hasText(Assert.java:135)
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:479)
	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:541)
	at io.pravega.segmentstore.server.host.delegationtoken.TokenVerifierImpl.verifyToken(TokenVerifierImpl.java:36)
	at io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor.verifyToken(PravegaRequestProcessor.java:182)
	at io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor.getStreamSegmentInfo(PravegaRequestProcessor.java:348)
	at io.pravega.shared.protocol.netty.DelegatingRequestProcessor.getStreamSegmentInfo(DelegatingRequestProcessor.java:60)
	at io.pravega.shared.protocol.netty.WireCommands$GetStreamSegmentInfo.process(WireCommands.java:860)
	at io.pravega.segmentstore.server.host.handler.ServerConnectionInboundHandler.channelRead(ServerConnectionInboundHandler.java:46)```

**Comment by shrids** [comment]
Findings from longevity run #922 

1. The hulk tests creates readers on the fly (hulk test started @ `2018-06-26 13:35:24,102 247`) this reader was created @ `2018-06-26 22:35:32,606`

```
controller_server_2018-06-26.160.log:2018-06-26 22:35:32,606 32408751 [pool-8-thread-4] INFO  i.p.c.stream.impl.ClientFactoryImpl - Creating reader: HulkSmallScale0b21af6b5c2a406f8bbc57dffff01b0c under readerGroup: hulksmallScaleforgetful0 with configuration: ReaderConfig(initialAllocationDelay=0)
```

2. The reader was assigned segments to read from.
```
controller_server_2018-06-26.160.log:2018-06-26 22:35:33,047 32409192 [pool-8-thread-4] INFO  i.p.c.s.impl.EventStreamReaderImpl - EventStreamReaderImpl( id=HulkSmallScale0b21af6b5c2a406f8bbc57dffff01b0c) acquiring segments {hulk/smallScale/448.#epoch.285=0, hulk/smallScale/458.#epoch.292=0, hulk/smallScale/459.#epoch.292=0, hulk/smallScale/462.#epoch.294=0, hulk/smallScale/461.#epoch.293=0, hulk/smallScale/463.#epoch.294=0, hulk/smallScale/460.#epoch.293=0, hulk/smallScale/457.#epoch.291=0, hulk/smallScale/456.#epoch.290=0, hulk/smallScale/453.#epoch.289=0, hulk/smallScale/452.#epoch.288=0, hulk/smallScale/455.#epoch.290=0, hulk/smallScale/445.#epoch.283=0, hulk/smallScale/454.#epoch.289=0, hulk/smallScale/444.#epoch.283=0, hulk/smallScale/441.#epoch.281=0, hulk/smallScale/439.#epoch.279=0, hulk/smallScale/443.#epoch.282=0, hulk/smallScale/436.#epoch.277=0, hulk/smallScale/446.#epoch.284=0, hulk/smallScale/451.#epoch.288=0, hulk/smallScale/428.#epoch.272=0, hulk/smallScale/429.#epoch.273=0, hulk/smallScale/389.#epoch.248=0, hulk/smallScale/465.#epoch.296=0, hulk/smallScale/464.#epoch.295=0}
```

3. The reader encountered a `SegmentTruncatedException`

```
controller_server_2018-06-26.160.log:2018-06-26 22:35:34,826 32410971 [pool-8-thread-4] INFO  i.p.c.s.impl.EventStreamReaderImpl - EventStreamReaderImpl( id=HulkSmallScale0b21af6b5c2a406f8bbc57dffff01b0c) encountered truncation for segment hulk/smallScale/458.#epoch.292
```
(As I understand the test code for a forgetful reader retries on seeing a truncation exception.).

4. On seeing that the segment is truncated the reader tries to fetch the segment info of segment `4458.#epoch.292`. But the `delegationToken` is `null` since the current code only updates the delegationToken on seeing a `EndOfSegmentException`.

Also, PRP closes the connection on seeing that the request has a null `delegationToken` causing the Reader to retry to establish the connection. The Reader then throws a `RetriesExhaustedException` on failing to connect to PRP.

**Comment by jkhalack** [comment]
> (As I understand the test code for a forgetful reader retries on seeing a truncation exception.).
The test code is not even getting the truncation exception. 
It seems that pravega client deals with it in some way.

**Comment by shrids** [comment]
Fixed with https://github.com/pravega/pravega/pull/2732
