### ISSUE TITLE
Sporadic build failure: ScaleRequestHandlerTest.testScaleRequest

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#2685]
**Problem description**
```
io.pravega.controller.server.eventProcessor.ScaleRequestHandlerTest > testScaleRequest FAILED
    java.lang.AssertionError: expected:<1> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.pravega.controller.server.eventProcessor.ScaleRequestHandlerTest.testScaleRequest(ScaleRequestHandlerTest.java:218)
```

**Problem location**
ScaleRequestHandlerTest

**Suggestions for an improvement**
Fix the issue.

**Comment by shrids** [comment]
Observed this again with PR : https://github.com/pravega/pravega/pull/2799

 https://travis-ci.org/pravega/pravega/builds/410145510?utm_source=github_status&utm_medium=notification

**Comment by shiveshr** [comment]
closing as it has been over a year since this is observed
