### ISSUE TITLE
Pravega doesn't always log unhandled exceptions

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2736]
**Problem description**
I observe that `PravegaRequestProcessor::handleException` doesn't log unhandled exceptions.   This is due to faulty logging code.  For example:
```
        } else {
            log.error("Error (Segment = '{}', Operation = '{}')", segment, operation, u);
            connection.close(); // Closing connection should reinitialize things, and hopefully fix the problem
            throw new IllegalStateException("Unknown exception.", u);
        }

```

Observe that the `error` method call is to the 'format string' overload, not the `Throwable` overload.

**Problem location**
There seem to be dozens of sites where the wrong overload of `error` or `warn` is used.   Here's a list that was generated with the following command (with obvious false positives removed):
```
grep -R --include=*.java -P -i 'log.(warn|error)\(.*\{.*,.*,.*\)' .
```

```
./client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java:            log.warn("Exception while reading from Segment : {}", segmentId, ex);
./client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java:            log.warn("gRPC call for {} with trace id {} failed with server error.", method, traceId, t);
./client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java:                log.warn("Flush on segment {} failed due to {}, it will be retried.", writer.getSegmentName(), e.getMessage());
./client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java:                        log.warn("Close failed due to {}, it will be retried.", e.getMessage());
./client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java:                    log.error("Error while fetching successors for segment: {}", sealedSegment, t);
./controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java:                    log.warn("Restarting event processor: {} due to exception: {}", objectId, e);
./controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java:                    log.warn("Stopping event processor: {} due to exception: {}", objectId, e);
./controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CommitRequestHandler.java:                            log.error("Exception while attempting to commit transaction on epoch {} on stream {}/{}", epoch, scope, stream, e);
./controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/DeleteStreamTask.java:                    log.error("{}/{} stream delete workflow threw exception.", scope, stream, e);
./controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/ScaleOperationTask.java:                        log.warn("processing scale request for {}/{} segments {} failed {}", request.getScope(), request.getStream(),
./controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java:            log.warn("Create scope for {} failed due to authentication failure {}.", createScopeRequest.getScopeName(), e);
./controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java:            log.warn("createScope for scope: {} failed, exception: {}", createScopeRequest.getScopeName(), exception);
./controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java:                    log.warn("createStream for {}/{} failed {}: ", scopeName, streamConfiguration.getStreamName(),
./controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java:            log.warn("deleteScope for {} failed with exception: {}", scopeName, exception);
./controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java:           log.warn("deleteStream for {} failed with exception: {}", streamName, exception);
./controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java:            log.warn("getReaderGroup for {} failed with exception: ", readerGroupName, exception);
./controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java:                        log.warn("getScope for {} failed with exception: {}", scopeName, exception);
./controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java:                        log.warn("getStream for {}/{} failed with exception: {}", scopeName, streamName, exception);
./controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java:                        log.warn("listReaderGroups for {} failed with exception: ", scopeName, exception);
./controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java:                        log.warn("listStreams for {} failed with exception: {}", scopeName, exception);
./controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java:            log.warn("updateStream for {}/{} failed with exception: {}", scopeName, streamName, exception);
./controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java:            log.warn("updateStreamState for {} failed with exception: {}", streamName, exception);
./controller/src/main/java/io/pravega/controller/server/retention/StreamCutBucketService.java:                e -> log.warn("exception thrown getting streams for bucket {}, e = {}", bucketId, e), executor)
./controller/src/main/java/io/pravega/controller/server/retention/StreamCutBucketService.java:                    log.warn("Exception thrown while performing auto retention for stream {} ", stream, e);
./controller/src/main/java/io/pravega/controller/server/retention/StreamCutBucketService.java:                    log.warn("Unable to perform retention for stream {}. Ignoring, retention will be attempted in next cycle.", stream, e);
./controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaAuthManager.java:                        log.warn("Exception while initializing auth handler {}", handler, e);
./controller/src/main/java/io/pravega/controller/server/SegmentHelper.java:                log.error("CreateSegment {} threw exception", qualifiedStreamSegmentName, error);
./controller/src/main/java/io/pravega/controller/server/SegmentHelper.java:                log.error("truncateSegment {} error", qualifiedName, error);
./controller/src/main/java/io/pravega/controller/server/SegmentHelper.java:                log.error("deleteSegment {} failed", qualifiedName, error);
./controller/src/main/java/io/pravega/controller/server/SegmentHelper.java:                log.error("sealSegment {} failed", qualifiedName, error);
./controller/src/main/java/io/pravega/controller/server/SegmentHelper.java:                log.error("createTransaction {} failed", transactionName, error);
./controller/src/main/java/io/pravega/controller/server/SegmentHelper.java:                log.error("commitTransaction {} failed", transactionName, error);
./controller/src/main/java/io/pravega/controller/server/SegmentHelper.java:                log.error("getSegmentInfo {} failed", qualifiedName, error);
./controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java:                log.warn("unable to close watch on bucket {} with exception {}", bucket, e);
./controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java:                                    log.warn("Scale for stream {}/{} failed with exception {}", scope, stream, cause);
./controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java:                log.warn("exception while posting event {} {}", e.getClass().getName(), e.getMessage());
./controller/src/main/java/io/pravega/controller/task/Stream/TxnSweeper.java:                log.warn("Host={}, Caught exception sweeping orphaned transactions", failedHost, e);
./segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/delegationtoken/TokenVerifierImpl.java:                log.warn("Claim verification failed for resource {} because {}", resource, e);
./segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java:            log.error("Append processor: Error {} on segment = '{}'", doingWhat, segment, exception);
./segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java:            log.warn("Bad attribute update by {} on segment {}.", writerId, segment, u);
./segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java:            log.warn("Token check failed while being written by {} on segment {}.", writerId, segment, u);
./segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java:            log.warn("Unsupported Operation '{}'.", doingWhat, u);
./segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java:            log.error("Error (Segment = '{}', Operation = 'append')", segment, u);
./segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java:            log.error("Error (Segment = '{}', Operation = '{}')", segment, operation, exception);
./segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java:            log.warn("Unsupported Operation '{}'.", operation, u);
./segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java:            log.error("Error (Segment = '{}', Operation = '{}')", segment, operation, u);
./segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java:                            log.error("exception while computing stats while merging txn {}", mergeSegments, e);
./segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/SegmentStatsRecorderImpl.java:            log.warn("Record statistic for {} for data: {} and events:{} threw exception", streamSegmentName, dataLength, numOfEvents, e);
./segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java:                                log.warn("Stopping container {} failed: {}", containerId, throwable);
./segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java:                                log.warn("Starting container {} failed: {}", containerId, ex);
./segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java:                log.warn("{}: Snapshot serialized to attribute segment, but failed to update snapshot location or truncate Attribute Segment.", this.traceObjectId, ex);
./segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java:            log.error("{}: Error.", TRACE_OBJECT_ID, ex);
./segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java:                log.warn("{} Unable to update client {}. {}", TRACE_OBJECT_ID, c, ex);
./segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java:            log.warn("{}: {} failed. Shutting down StreamSegmentContainer.", this.traceObjectId, componentName, cause);
./segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java:                        log.warn("{}: Missing or corrupt State File for existing Segment '{}'; recreating.", this.traceObjectId, segmentName, ex);
./segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLog.java:            log.error("{} Recovery FAILED.", this.traceObjectId, ex);
./segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLog.java:                    log.warn("{}: Unable to disable log after DataCorruptionException during recovery.", this.traceObjectId, disableEx);
./segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLog.java:                        log.warn("{}: Error caught while waiting for {}: {}.", this.traceObjectId, ProbeOperation.class.getSimpleName(), ex);
./segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLog.java:        log.warn("{}: QueueProcessor failed with exception {}", this.traceObjectId, cause);
./segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java:        log.warn("{}: Cancelling {} operations with exception: {}.", this.traceObjectId, cancelCount, failException.toString());
./segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java:            log.error("{}: MemoryStateUpdater.process failure.", traceObjectId, ex);
./segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/StreamSegmentContainerRegistry.java:        log.error("Critical failure for SegmentContainer {}. {}", containerWithHandle, exception);
./segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java:            log.error("{}: Iteration[{}].CriticalError.", this.traceObjectId, this.state.getIterationId(), ex);
./segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java:            log.error("{}: Iteration[{}].Error.", this.traceObjectId, this.state.getIterationId(), ex);
./segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java:        log.warn("{}: Iteration[{}].HandledError {}", this.traceObjectId, this.state.getIterationId(), ex.toString());
./segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java:        log.warn("{}: Too many write processor failures; closing.", this.traceObjectId, exception);
./segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java:        log.warn("{}: Too many rollover failures; closing.", this.traceObjectId, exception);
./segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java:                    log.error("{}: Unable to close LedgerHandle for Ledger {}.", this.traceObjectId, writeLedger.ledger.getId(), bkEx);
./segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java:                log.warn("{}: Unable to delete orphan empty ledger {}.", this.traceObjectId, id, ex);
./segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java:                log.warn("{}: Not running WriteProcessor as part of callback due to BookKeeperLog being closed.", this.traceObjectId, ex);
./segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java:            log.warn("{}: Caught ObjectClosedException but not closed; closing now.", this.traceObjectId, ex);
./segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java:                log.error("{}: Unable to delete truncated ledger {}.", this.traceObjectId, lm.getLedgerId(), ex);
./segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java:                log.warn("{}: Unable to delete newly created ledger {}.", this.traceObjectId, newLedger.getId(), deleteEx);
./segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogReader.java:                    log.error("Unable to close LedgerHandle for Ledger {}.", this.currentLedger.handle.getId(), bkEx);
./segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/RollingStorage.java:                    log.warn("Could not create Header Segment for '{}', rolling back.", segmentName, ex);
./segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/RollingStorage.java:                    log.warn("Attempted to delete concat source Header '{}' but it doesn't exist.", source.getHeaderHandle().getSegmentName(), ex);
./shared/metrics/src/main/java/io/pravega/shared/metrics/StatsLoggerImpl.java:            log.warn("createStats failure: {}", statName, e);
./shared/metrics/src/main/java/io/pravega/shared/metrics/StatsLoggerImpl.java:            log.warn("createCounter failure: {}", statName, e);
./shared/metrics/src/main/java/io/pravega/shared/metrics/StatsLoggerImpl.java:            log.warn("registerGauge failure: {}", statName, e);
./shared/metrics/src/main/java/io/pravega/shared/metrics/StatsLoggerImpl.java:            log.warn("createMeter failure: {}", statName, e);
./standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java:                log.warn("Not able to delete path {} . Exception {}", path, e.getMessage());
./test/system/src/main/java/io/pravega/test/system/framework/TestFrameworkException.java:        log.error("TestFramework Exception. Type: {}, Details: {}", type, reason, cause);
./test/system/src/test/java/io/pravega/test/system/AbstractScaleTests.java:                log.error("test {} failed with exception {}", testName, e);
./test/system/src/test/java/io/pravega/test/system/ReaderCheckpointTest.java:            log.error("Exception while reading event using readerId: {}", readerId, e);
./test/system/src/test/java/io/pravega/test/system/ReaderCheckpointTest.java:                t -> log.error("Error observed while reading events for reader id :{}", readerId, t));
./test/system/src/test/java/io/pravega/test/system/ReaderCheckpointTest.java:                    log.error("Exception while reading event using readerId: {}", readerId, e);
```

**Suggestions for an improvement**

**Comment by EronWright** [comment]
```
// error(String format, Object... arguments)
log.error("Error (Segment = '{}', Operation = '{}')\n{}", segment, operation, u.getStackTrace());
```

```
// error(String msg, Throwable t)
log.error(String.format("Error (Segment = '{}', Operation = '{}')", segment, operation), u);
```

```
// two calls
log.error("Error (Segment = '{}', Operation = '{}')", segment, operation);
log.error("", u);
```

```
// a wrapper
ExceptionUtils.logError(log, u, "Error (Segment = '{}', Operation = '{}')", segment, operation);
private void logError(Logger log, Throwable th, String format, Object... args) { ... }
```

**Comment by adrianmo** [comment]
I'd rather go for the second approach. It's the only method overload that takes `Throwable` as an argument and to me it looks cleaner than the other approaches. 

Any more opinions about this?

**Comment by adrianmo** [comment]
I've been investigating this issue and according to this [StackOverflow thread](https://stackoverflow.com/questions/5951209/how-to-log-exception-and-message-with-placeholders-with-slf4j) and the [SLF4J FAQ](https://www.slf4j.org/faq.html#paramException), SLF4J >= 1.6.0 should deal correctly with exceptions in the last position.

I tried that with our current slf4j version (i.e. 1.7.25) and exceptions are logged correctly including the stacktrace using the following two method overloads (including other log levels):
- error(String format, Object arg1, Object arg2)
- error(String format, Object... arguments)

 @EronWright where are you experiencing this? Maybe you were using an older version of slf4j?

**Comment by EronWright** [comment]
That's funny.   It shouldn't be difficult to confirm the behavior either way by deliberately misconfiguring Pravega or adding some naughty code.   Originally this came out of an investigation involving tier-2 storage and the request processor (see description).

**Comment by fpj** [comment]
I see, so according to the FAQ, this call:

https://www.slf4j.org/api/org/slf4j/Logger.html#error(java.lang.String,%20java.lang.Object,%20java.lang.Object)

will behave as we expect. Is this still an issue or should we close it?

**Comment by adrianmo** [comment]
Correct, as an example, the line below, which uses the `warn(String format, Object arg1, Object arg2)` overload method

https://github.com/pravega/pravega/blob/3f3008b727e39e1d6dd1bbfa90cfd0087af3c208/segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java#L450

generates the following log:

```
2018-07-18 10:52:56,741 WARN handler.PravegaRequestProcessor (PravegaRequestProcessor.java:handleException(450)) - Unsupported Operation 'Create segment'.
java.lang.UnsupportedOperationException: createStreamSegment is unsupported on ReadOnlySegmentContainer
	at io.pravega.segmentstore.server.containers.ReadOnlySegmentContainer.unsupported(ReadOnlySegmentContainer.java:195)
	at io.pravega.segmentstore.server.containers.ReadOnlySegmentContainer.createStreamSegment(ReadOnlySegmentContainer.java:171)
	at io.pravega.segmentstore.server.store.StreamSegmentService.lambda$createStreamSegment$6(StreamSegmentService.java:112)
	at io.pravega.segmentstore.server.store.StreamSegmentService.invoke(StreamSegmentService.java:174)
	at io.pravega.segmentstore.server.store.StreamSegmentService.createStreamSegment(StreamSegmentService.java:110)
	at io.pravega.segmentstore.server.mocks.SynchronousStreamSegmentStore.createStreamSegment(SynchronousStreamSegmentStore.java:81)
	at io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor.createSegment(PravegaRequestProcessor.java:399)
	at io.pravega.segmentstore.server.host.handler.PravegaRequestProcessorTest.testUnsupportedOperation(PravegaRequestProcessorTest.java:493)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

The same happens with the `error/warn/info/debug(String format, Object... arguments)` overload methods. Example:

https://github.com/pravega/pravega/blob/3f3008b727e39e1d6dd1bbfa90cfd0087af3c208/segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java#L456

```
2018-07-18 11:01:09,956 ERROR handler.PravegaRequestProcessor (PravegaRequestProcessor.java:handleException(456)) - Error (Segment = 'testSegmentAttribute', Operation = 'Update attribute')
io.pravega.segmentstore.contracts.BadAttributeUpdateException: [Segment 'testSegmentAttribute'] Bad Attribute Update (AttributeId = 94735710-2919-47a7-868d-f6936882ca25, Value = 5, UpdateType = ReplaceIfEquals): Expected existing value to be '-9223372036854775808', actual '1'..
	at io.pravega.segmentstore.server.logs.SegmentMetadataUpdateTransaction.preProcessAttributes(SegmentMetadataUpdateTransaction.java:429)
	at io.pravega.segmentstore.server.logs.SegmentMetadataUpdateTransaction.preProcessOperation(SegmentMetadataUpdateTransaction.java:274)
	at io.pravega.segmentstore.server.logs.ContainerMetadataUpdateTransaction.preProcessOperation(ContainerMetadataUpdateTransaction.java:321)
	at io.pravega.segmentstore.server.logs.OperationMetadataUpdater.preProcessOperation(OperationMetadataUpdater.java:224)
	at io.pravega.segmentstore.server.logs.OperationProcessor.processOperation(OperationProcessor.java:364)
	at io.pravega.segmentstore.server.logs.OperationProcessor.processOperations(OperationProcessor.java:283)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at io.pravega.test.common.InlineExecutor.execute(InlineExecutor.java:34)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:653)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.pravega.common.util.BlockingDrainingQueue.add(BlockingDrainingQueue.java:115)
	at io.pravega.segmentstore.server.logs.OperationProcessor.process(OperationProcessor.java:216)
	at io.pravega.segmentstore.server.logs.DurableLog.add(DurableLog.java:298)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.processAttributeUpdaterOperation(StreamSegmentContainer.java:563)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.lambda$updateAttributes$8(StreamSegmentContainer.java:330)
	at io.pravega.segmentstore.server.containers.StreamSegmentMapper.getOrAssignStreamSegmentId(StreamSegmentMapper.java:286)
...
```

**Comment by fpj** [comment]
Not an issue.
