### ISSUE TITLE
BookieFailoverTest sporadic failure

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#2783]
**Problem description**
`BookieFailoverTest` sporadically fails as some readers get `RetriesExhaustedException`. Note this failure is not consistent: in a Jarvis cluster the current version of the test passes consistently, whereas this does not happen in Jenkins system test builds. Writers and readers process all the events correctly.

**Problem location**
`BookieFailoverTest.java`

**Suggestions for an improvement**
This could related to an excessive sleep timeout for a Bookie failover test.

**Comment by shrids** [comment]
Segment container recovery took a long time, causing the readers to fail.
```
// test failed. one reader threw  RetriesExhaustedException
2018-07-23 17:46:34,379 189581 [BookieFailoverTest-main-6] ERROR i.p.t.system.AbstractFailoverTests - Test exception in reading events: 
io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=38, segment=testBookieFailoverScope2114160398/_RGtestBookieFailoverReaderGroup189839522/0.#epoch.0, correctHost=)
```
```
// failure detected on segment store
2018-07-23 17:44:51,274 6688045 [bookkeeper-io-3] ERROR o.a.b.proto.PerChannelBookieClient - Could not connect to bookie: [id: 0x5a2cbdd6, L:/172.16.18.21:54080]/172.16.18.21:3181, current state CONNECTING :
io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection reset by peer: /172.16.18.21:3181
        at io.netty.channel.unix.Errors.throwConnectException(Errors.java:107)
        at io.netty.channel.unix.Socket.finishConnect(Socket.java:267)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:695)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:672)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:552)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection reset by peer
        ... 9 common frames omitted
```

**Comment by RaulGracia** [comment]
Here is my take on the issue: Despite all the events are written/read, the cause of the test failure is that readers are getting a handful of `RetriesExhaustedException` that make the test to fail, as no exceptions are expected from an application's perspective (in `AbstractFailoverTests`). Readers are getting such exceptions because the interval between the Bookie failure and its recovery is too long, thus exceeding the default reader retry timeout (+1 minute approx). That is, the test executes 2 sleeps between the Bookie failure and its recovery to assert that no successful writes are performed while the Bookie is down. However, the timeout used for each sleep is `40s`, which means that readers and writers are executing retries for at least `80s`. On top of that, there is a lapse of time between the test instantiates a new Bookie until the segment store can process client requests again (measured in `20s` approx.). Therefore, the period of time for which the system is unavailable seems too long.
