### ISSUE TITLE
SegmentSealedException on transaction segments

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#2790]
**Problem description**
Since we started running longevity tests with pravega commit `c619054`, we keep getting failed transactions on our `smallTx` test that has one writer writing transactions into a `hulk/smallTx` stream with one segment and a fixed scaling policy. Half of the transactions are committed, half of the transactions are aborted. We are expecting the transactions that should be committed to be actually committed to the stream.

```
2018-07-25 15:36:24,596 140825293 [pool-4-thread-1] ERROR c.e.n.h.t.w.w.PravegaWriterState - TX Failed to commit
io.pravega.client.stream.TxnFailedException: io.pravega.client.segment.impl.SegmentSealedException: SegmentSealed Exception for segment:hulk/smallTx/0.#epoch.0#transaction.00000000000000000000000000026067 sealed for writer 49c79dac-5095-4077-a5cb-1b06c2b78458
	at io.pravega.client.stream.impl.SegmentTransactionImpl.flush(SegmentTransactionImpl.java:94)
	at io.pravega.client.stream.impl.SegmentTransactionImpl.close(SegmentTransactionImpl.java:100)
	at io.pravega.client.stream.impl.EventStreamWriterImpl$TransactionImpl.commit(EventStreamWriterImpl.java:248)
	at com.emc.nautilus.hulk.taskexecutor.workers.writers.PravegaWriterState.afterWrite(PravegaWriterState.kt:75)
	at com.emc.nautilus.hulk.taskexecutor.workers.writers.PravegaWriter.start(PravegaWriter.java:151)
	at com.emc.nautilus.hulk.taskexecutor.workers.writers.WriterWorkerManager.lambda$start$0(WriterWorkerManager.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: io.pravega.client.segment.impl.SegmentSealedException: SegmentSealed Exception for segment:hulk/smallTx/0.#epoch.0#transaction.00000000000000000000000000026067 sealed for writer 49c79dac-5095-4077-a5cb-1b06c2b78458
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl.flush(SegmentOutputStreamImpl.java:493)
	at io.pravega.client.stream.impl.SegmentTransactionImpl.flush(SegmentTransactionImpl.java:88)
```
Earlier in the log file there is a mention of the transaction segment being truncated (should it ever be?):
```
2018-07-25 15:36:24,581 140825278 [epollEventLoopGroup-2-14] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Segment being written to hulk/smallTx/0.#epoch.0#transaction.00000000000000000000000000026067 by writer 49c79dac-5095-4077-a5cb-1b06c2b78458 no longer exists due to Stream Truncation, resending to the newer segment.
```
And then there is a mention of the main segment being sealed (which is very strange, as the stream has a fixed scaling policy):
```
2018-07-25 15:36:24,583 140825280 [ScalingRetransmition-hulk/smallTx-3] INFO  i.p.c.s.impl.EventStreamWriterImpl - Sealing segment hulk/smallTx/0.#epoch.0 

```
[gargoyle.smallTx.controller-server.log](https://github.com/pravega/pravega/files/2232740/gargoyle.smallTx.controller-server.log)

**Problem location**
Segmentstore?

**Suggestions for an improvement**
Transaction segments should not be truncated

**Comment by jkhalack** [comment]
Pravega logs for the time of the transaction failure:
[gargoyle.smallTx.pravega_logs.zip](https://github.com/pravega/pravega/files/2232856/gargoyle.smallTx.pravega_logs.zip)

**Comment by jkhalack** [comment]
```
2018-07-25 15:36:22,342 141416588 [epollEventLoopGroup-3-8] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[11]: DeleteStreamSegment 2151370 ('hulk/smallTx/0.#epoch.0#transaction.00000000000000000000000000026067').
```

There was something in ZK:
```
2018-07-25 15:36:22,335 [myid:0] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@841] - Got user-level KeeperException when processing sessionid:0x1782d8000f type:delete cxid:0x5f6832 zxid:0x1001e95c9 txntype:-1 reqpath:n/a Error Path:/pravega/pravega-cluster/hostTxnIndex/172.16.15.22-ba4d874b-2e36-4bc3-82a8-e19784afa125 Error:KeeperErrorCode = Directory not empty for /pravega/pravega-cluster/hostTxnIndex/172.16.15.22-ba4d874b-2e36-4bc3-82a8-e19784afa125
```

**Comment by shiveshr** [comment]
IMO following two logs are misleading. 
A deleted transaction segment is logged by writer as truncated incorrectly. 
```
 2018-07-25 15:36:24,581 140825278 [epollEventLoopGroup-2-14] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Segment being written to hulk/smallTx/0.#epoch.0#transaction.00000000000000000000000000026067 by writer 49c79dac-5095-4077-a5cb-1b06c2b78458 no longer exists due to Stream Truncation, resending to the newer segment.
```

This is also out of place because client never requests to seal any segment. 
```
2018-07-25 15:36:24,583 140825280 [ScalingRetransmition-hulk/smallTx-3] INFO  i.p.c.s.impl.EventStreamWriterImpl - Sealing segment hulk/smallTx/0.#epoch.0 
```

**Comment by tkaitchuck** [comment]
@shiveshr 
That sealing segment log actually means the client is handling the fact that that segment was already sealed. So we know that the main segment was sealed at or prior to 15:36:24

**Comment by tkaitchuck** [comment]
I don't see any logs from the pinging thread in those 3 minutes.

**Comment by shiveshr** [comment]
@tkaitchuck 
>  That sealing segment log actually means the client is handling the fact that that segment was already sealed. So we know that the main segment was sealed at or prior to 15:36:24

Since there is only one main segment `0.epoch.0` as can be seen in the logs, so I think this is a stream with no scaling policy enabled.  

So i suspect this log is misplaced 
```impl.EventStreamWriterImpl - Sealing segment hulk/smallTx/0.#epoch.0 ```
I have opened issue #2801 and assigned to @tkaitchuck

**Comment by tkaitchuck** [comment]
I'm closing this, as 2801 has been resolved. If this reoccurs in a newer version, feel free to re-open.
