### ISSUE TITLE
StreamSegments validation fails.

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#2813]
**Problem description**

The below exception was observed during system tests and longevity tests. 
```2018-08-01 07:26:39,187 587848 [ScalingRetransmition-testReadWriteAndAutoScaleScope1853030827/testReadWriteAndAutoScaleStream-4] ERROR i.p.c.s.impl.EventStreamWriterImpl - Encountered excemption when handeling a sealed segment: 
java.lang.IllegalArgumentException: Inconsistant replaced replacement segments io.pravega.client.stream.impl.StreamSegmentsWithPredecessors@631a568f
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
	at io.pravega.client.stream.impl.StreamSegments.verifyReplacementRange(StreamSegments.java:108)
	at io.pravega.client.stream.impl.StreamSegments.withReplacementRange(StreamSegments.java:71)
	at io.pravega.client.stream.impl.SegmentSelector.updateSegmentsUponSealed(SegmentSelector.java:143)
	at io.pravega.client.stream.impl.SegmentSelector.refreshSegmentEventWritersUponSealed(SegmentSelector.java:98)
	at io.pravega.client.stream.impl.EventStreamWriterImpl.lambda$null$1(EventStreamWriterImpl.java:155)
	at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:173)
	at io.pravega.client.stream.impl.EventStreamWriterImpl.lambda$handleLogSealed$2(EventStreamWriterImpl.java:142)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Logs: 
[FilteredLogs_withControllerResponses.zip](https://github.com/pravega/pravega/files/2256228/FilteredLogs_withControllerResponses.zip)

**Problem location**
Client ? 
(No issue was observed from the controller end as per current investigation).

**Suggestions for an improvement**
Fix the issue.

**Comment by shrids** [comment]
These assertions were added as part of https://github.com/pravega/pravega/pull/2799
