### ISSUE TITLE
Token verification fails during longevity.

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#2816]
**Problem description**

Token verification failure causes readers to throw RetriesExhaustedException on a longevity setup. The failure was observed after 3days 16hours into the test.

```
2018-08-04 20:29:06,796 317897935 [epollEventLoopGroup-3-1] INFO  i.p.s.s.h.h.PravegaRequestProcessor - Received delegationtoken: eyJhbGciOiJIUzUxMiJ9.eyJodWxrL3NtYWxsU2NhbGUiOiJSRUFEX1VQREFURSJ9.K2M3OZ8ViXZmVDo-mSFyEyJ-FkN7UJN6VUVAbuy2lygEZlyut2WyokimCadV4_um4YEiD4aolj3AGWn91YR4ng for segment: hulk/smallScaleSlow/4679.#epoch.3038 and operation: Read Segment
2018-08-04 20:29:06,796 317897935 [epollEventLoopGroup-3-1] INFO  i.p.s.s.h.d.TokenVerifierImpl - Could not find a matching claim READ for resource hulk/smallScaleSlow/4679.#epoch.3038 in claims header={alg=HS512},body={hulk/smallScale=READ_UPDATE},signature=K2M3OZ8ViXZmVDo-mSFyEyJ-FkN7UJN6VUVAbuy2lygEZlyut2WyokimCadV4_um4YEiD4aolj3AGWn91YR4ng
2018-08-04 20:29:06,796 317897935 [epollEventLoopGroup-3-1] WARN  i.p.s.s.h.h.PravegaRequestProcessor - Delegation token verification failed for segment: hulk/smallScaleSlow/4679.#epoch.3038, token: eyJhbGciOiJIUzUxMiJ9.eyJodWxrL3NtYWxsU2NhbGUiOiJSRUFEX1VQREFURSJ9.K2M3OZ8ViXZmVDo-mSFyEyJ-FkN7UJN6VUVAbuy2lygEZlyut2WyokimCadV4_um4YEiD4aolj3AGWn91YR4ng, operation: Read Segment
2018-08-04 20:29:06,797 317897936 [epollEventLoopGroup-3-1] WARN  i.p.s.s.h.h.PravegaRequestProcessor - Authentication error during 'Read Segment' on Segment = hulk/smallScaleSlow/4679.#epoch.3038.
io.pravega.common.auth.AuthenticationException: Token verification failed
    at io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor.verifyToken(PravegaRequestProcessor.java:186)
    at io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor.readSegment(PravegaRequestProcessor.java:167)
    at io.pravega.shared.protocol.netty.DelegatingRequestProcessor.readSegment(DelegatingRequestProcessor.java:45)
    at io.pravega.shared.protocol.netty.WireCommands$ReadSegment.process(WireCommands.java:665)
    at io.pravega.segmentstore.server.host.handler.ServerConnectionInboundHandler.channelRead(ServerConnectionInboundHandler.java:46)

```
Logs: 
[a9dd4541-b6c3-4b43-a6eb-3e5453d7473f-1533414547110.zip](https://github.com/pravega/pravega/files/2265724/a9dd4541-b6c3-4b43-a6eb-3e5453d7473f-1533414547110.zip)

**Problem location**
Security.

**Suggestions for an improvement**
Fix the issue.

**Comment by arvindkandhare** [comment]
In this particular case the token sent across is `body={hulk/smallScale=READ_UPDATE}` where as the expected token should have `body={hulk/smallScaleSlow=READ_UPDATE}`. The token extraction works fine. Two unknowns here:
1. Why wrong claim is sent in the header
2. Why this happens only after long duration

Looking into this.

**Comment by arvindkandhare** [comment]
This is because The `delegationToken` https://github.com/pravega/pravega/blob/15b92eb8158052ab9dd15df2e417f3a1078635c3/controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java#L43 should be per grpc `Context`. Right now it is per `PravegaInterceptor` because of which in case of two concurrent calls it may be overwritten. That is the reason we are receiving a different token. Will fix this and add a test case.

**Comment by arvindkandhare** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Longetivity run failure due to verifyToken failure.](https://trello.com/c/RDMKXlIm/30-longetivity-run-failure-due-to-verifytoken-failure)

**Comment by arvindkandhare** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Delegation token handling refactoring](https://trello.com/c/HEVhxEAP/32-delegation-token-handling-refactoring)
