### ISSUE TITLE
Running with docker-compose, segmentstore constantly throws gRPC exception

### ISSUE THREAD

**Issue by bfrggit** [pravega/pravega#2836]
**Problem description**

I am running Pravega locally using docker-compose, as is instructed here:
http://pravega.io/docs/latest/deployment/run-local/

However, when everything appears to have started, at some constant rate (every few seconds), controller throws ERROR "io.pravega.controller.store.stream.StoreException$IllegalStateException: Stream: _requeststream State: CREATING"; and segmentstore throws WARN "i.p.c.stream.impl.ControllerImpl - gRPC call for getCurrentSegments with trace id 0 failed with server error."

These two look correlated but not sure which one is the cause.

```
controller_1    | 2018-08-16 23:02:06,053 146122 [controllerpool-30] ERROR i.p.c.s.r.g.v.ControllerServiceImpl - Controller api failed with error:
controller_1    | java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$IllegalStateException: Stream: _requeststream State: CREATING
controller_1    |       at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
controller_1    |       at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
controller_1    |       at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
controller_1    |       at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
controller_1    |       at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
controller_1    |       at io.pravega.controller.store.stream.PersistentStreamBase.verifyLegalState(PersistentStreamBase.java:1339)
controller_1    |       at io.pravega.controller.store.stream.PersistentStreamBase.getActiveSegments(PersistentStreamBase.java:391)
controller_1    |       at io.pravega.controller.store.stream.AbstractStreamMetadataStore.lambda$getActiveSegments$9(AbstractStreamMetadataStore.java:346)
controller_1    |       at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
controller_1    |       at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
controller_1    |       at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
controller_1    |       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
controller_1    |       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
controller_1    |       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
controller_1    |       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
controller_1    |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
controller_1    |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
controller_1    |       at java.lang.Thread.run(Thread.java:745)
controller_1    | Caused by: io.pravega.controller.store.stream.StoreException$IllegalStateException: Stream: _requeststream State: CREATING
controller_1    |       at io.pravega.controller.store.stream.StoreException.create(StoreException.java:99)
controller_1    |       at io.pravega.controller.store.stream.StoreException.create(StoreException.java:70)
controller_1    |       at io.pravega.controller.store.stream.PersistentStreamBase.lambda$verifyLegalState$186(PersistentStreamBase.java:1341)
controller_1    |       at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
controller_1    |       ... 15 common frames omitted
segmentstore_1  | 2018-08-16 23:02:06,076 108531 [grpc-default-executor-0] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getCurrentSegments with trace id 0 failed with server error.
segmentstore_1  | io.grpc.StatusRuntimeException: INTERNAL: Stream: _requeststream State: CREATING
segmentstore_1  |       at io.grpc.Status.asRuntimeException(Status.java:526)
segmentstore_1  |       at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:418)
segmentstore_1  |       at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
segmentstore_1  |       at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:663)
segmentstore_1  |       at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
segmentstore_1  |       at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
segmentstore_1  |       at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:443)
segmentstore_1  |       at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
segmentstore_1  |       at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:525)
segmentstore_1  |       at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:446)
segmentstore_1  |       at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:557)
segmentstore_1  |       at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
segmentstore_1  |       at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
segmentstore_1  |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
segmentstore_1  |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
segmentstore_1  |       at java.lang.Thread.run(Thread.java:745)
```

**Problem location**
Might be docker-compose or individual docker images.

**Suggestions for an improvement**
Fix it?

**Comment by bfrggit** [comment]
Docker images:
```
pravega/pravega      latest              022c79c8613f        2 weeks ago         758MB
pravega/bookkeeper   latest              214f4f0cf757        2 weeks ago         777MB
dsrw/hdfs            2.7.3-1             bc9e9d722567        15 months ago       1.44GB
jplock/zookeeper     3.5.2-alpha         670020c6d187        2 years ago         153MB
```

**Comment by bfrggit** [comment]
After increasing VM RAM to 4 GB (and disabling firewall "iptables"), the issue appears gone.
Same exceptions still appear for once or twice but do not recur.

**Comment by bfrggit** [comment]
Though this issue is gone when VM RAM is increased -- only a few times we see this kind of exception at the beginning now.
