### ISSUE TITLE
Cannot build Pravega on JDK10

### ISSUE THREAD

**Issue by eolivelli** [pravega/pravega#2896]
**Problem description**
Trying to build Pravega on JDK10, I get

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':common:compileJava'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
.....
Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.code.TypeTags
        at lombok.launch.ShadowClassLoader.loadClass(ShadowClassLoader.java:422)
        at lombok.javac.JavacTreeMaker$SchroedingerType.getFieldCached(JavacTreeMaker.java:156)
        at lombok.javac.JavacTreeMaker$TypeTag.typeTag(JavacTreeMaker.java:245)
        at lombok.javac.Javac.<clinit>(Javac.java:155)
        ... 156 more

**Problem location**
Lombok does not support JDK10 with the features used by Pravega
The problems seems related to https://github.com/rzwitserloot/lombok/issues/1651.

I have trying to move to latest and greatest Lombok and Gradle (4.10, and trying also with 4.8.1).
 

**Suggestions for an improvement**
Wait for https://github.com/rzwitserloot/lombok/issues/1651 and upgrade

**Comment by eolivelli** [comment]
We need to upgrade BookKeeper AT LEAST to 4.6.2, due to problems with Netty + JDK9

This commit fix weird issues when running BK client and/or servers on JDK9 onwards.
https://github.com/apache/bookkeeper/commit/ae3f58d3336d75bfd1cbe088d4704be073883987

I recommend upgrading to 4.7.2 (current stable) or the upcoming 4.8.0

**Comment by eolivelli** [comment]
current master builds on jdk10 and we are close to make the build pass on jdk11.
This is can be closed now
