### ISSUE TITLE
Sporadic Failure in HDFSIntegrationTest.testEndToEndWithFencing

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#2933]
**Problem description**
The exception causing the test failure is:
```
java.util.concurrent.TimeoutException
    at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
    at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.testEndToEndWithFencing(StreamSegmentStoreTestBase.java:296)
```
Following the flow of the test, it can be seen that everything goes as expected until it executes `waitForSegmentsInStorage`, which is the point where the timeout exception arises.

When the test gets into this method, we start observing `BadOffsetException` messages related with a particular transaction segment:

```
2018-09-18 06:01:51,980 INFO  [storage-io-2] writer.SegmentAggregator (SegmentAggregator.java:setState(1549)) - StorageWriter[3-556]: State changed from Writing to ReconciliationNeeded.
2018-09-18 06:01:51,980 ERROR [storage-io-2] writer.StorageWriter (StorageWriter.java:logError(457)) - StorageWriter[3]: Iteration[2].Error.
io.pravega.segmentstore.contracts.BadOffsetException: [Segment 'Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0'] Bad Offset. Expected 1700, given 0.
    at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.write(HDFSStorage.java:360)
    at io.pravega.segmentstore.storage.rolling.RollingStorage.write(RollingStorage.java:322)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$write$2(AsyncStorageWrapper.java:100)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$runAsync$15(AsyncStorageWrapper.java:206)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.execute(AsyncStorageWrapper.java:221)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$supplyAsync$13(AsyncStorageWrapper.java:181)
```
As well as `IllegalArgumentException` in storage writer related to offsets:
```
2018-09-18 06:01:52,997 INFO  [IPC Server handler 6 on 51943] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=listStatus    src=/    dst=null    perm=null    proto=rpc
2018-09-18 06:01:53,022 ERROR [core-4] writer.StorageWriter (StorageWriter.java:logError(457)) - StorageWriter[3]: Iteration[3].Error.
java.lang.IllegalArgumentException: Offset 0 is beyond the last offset 0 of the segment.
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:323)
    at io.pravega.segmentstore.storage.rolling.RollingStorage.read(RollingStorage.java:151)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$read$8(AsyncStorageWrapper.java:135)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.execute(AsyncStorageWrapper.java:221)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$supplyAsync$13(AsyncStorageWrapper.java:181)
```
The test continues trying to read the `SegmentProperties` of segments in HDFS until the `120s` timeout for `waitForSegmentsInStorage` is exhausted and the test fails.

**Problem location**
`HDFSIntegrationTest.testEndToEndWithFencing`

**Suggestions for an improvement**
Make the test to pass consistently.

**Comment by RaulGracia** [comment]
[Full log](https://github.com/pravega/pravega/files/2424810/testEndToEndWithFencing.txt) for further analysis.

**Comment by RaulGracia** [comment]
I would like to share some insights regarding this issue after some analysis.
The problem seems related to transaction `bf2cc480df7546f39eddaacf227a1a8a`, and in particular, with transaction segment `Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3`.

While the test executes writes over transactions, the rolling mechanism takes place as usual. There is a specific point in which a HDFS client (probably `DFSClient_NONMAPREDUCE_2144198447_7088`) performs the following `rename` operation:

```
2018-09-18 06:01:49,853 INFO  [IPC Server handler 0 on 51943] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=rename    src=/Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_2    dst=/Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3    perm=root:supergroup:rw-------    proto=rpc
```

Which seems to start its execution, but it is not closed at this point by the client:

```
2018-09-18 06:01:49,934 INFO  [IPC Server handler 2 on 51943] namenode.FSNamesystem (FSNamesystem.java:checkBlocksComplete(2697)) - BLOCK* blk_1073741945_1222 is COMMITTED but not COMPLETE(numNodes= 0 <  minimum = 1) in file /Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3
```

Immediately afterwards, another HDFS client (`DFSClient_NONMAPREDUCE_1981959463_7705`) steps in and attempts to append data to that very same transaction segment, which results in a failure (`AlreadyBeingCreatedException`) given that the write lease for that segment is hold by another client (`DFSClient_NONMAPREDUCE_2144198447_7088`):

```
2018-09-18 06:01:50,191 WARN  [IPC Server handler 9 on 51943] hdfs.StateChange (FSDirAppendOp.java:appendFile(138)) - DIR* NameSystem.append: Failed to APPEND_FILE /Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3 for DFSClient_NONMAPREDUCE_1981959463_7705 on 127.0.0.1 because this file lease is currently owned by DFSClient_NONMAPREDUCE_2144198447_7088 on 127.0.0.1
2018-09-18 06:01:50,191 INFO  [IPC Server handler 9 on 51943] ipc.Server (Server.java:logException(2492)) - IPC Server handler 9 on 51943, call Call#39511 Retry#0 org.apache.hadoop.hdfs.protocol.ClientProtocol.append from 127.0.0.1:49016: org.apache.hadoop.hdfs.protocol.AlreadyBeingCreatedException: Failed to APPEND_FILE /Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3 for DFSClient_NONMAPREDUCE_1981959463_7705 on 127.0.0.1 because this file lease is currently owned by DFSClient_NONMAPREDUCE_2144198447_7088 on 127.0.0.1
```

One second later, it seems that the new HDFS client (`DFSClient_NONMAPREDUCE_1981959463_7705`) acquired the write lease and wrote some data (`1700` bytes) to the transaction segment:

```2018-09-18 06:01:51,945 INFO  [IPC Server handler 3 on 51943] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=append    src=/Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3    dst=null    perm=null    proto=rpc
2018-09-18 06:01:51,955 INFO  [DataXceiver for client DFSClient_NONMAPREDUCE_1981959463_7705 at /127.0.0.1:34952 [Receiving block BP-629685074-10.247.93.25-1537264893675:blk_1073741945_1222]] datanode.DataNode (DataXceiver.java:writeBlock(704)) - Receiving BP-629685074-10.247.93.25-1537264893675:blk_1073741945_1222 src: /127.0.0.1:34952 dest: /127.0.0.1:35859
2018-09-18 06:01:51,955 INFO  [DataXceiver for client DFSClient_NONMAPREDUCE_1981959463_7705 at /127.0.0.1:34952 [Receiving block BP-629685074-10.247.93.25-1537264893675:blk_1073741945_1222]] impl.FsDatasetImpl (FsDatasetImpl.java:append(1148)) - Appending to FinalizedReplica, blk_1073741945_1222, FINALIZED
  getNumBytes()     = 1700
  getBytesOnDisk()  = 1700
  getVisibleLength()= 1700
  getVolume()       = /tmp/IntegrationTest2005876775130030016/data/data1/current
  getBlockFile()    = /tmp/IntegrationTest2005876775130030016/data/data1/current/BP-629685074-10.247.93.25-1537264893675/current/finalized/subdir0/subdir0/blk_1073741945
2018-09-18 06:01:51,971 INFO  [IPC Server handler 8 on 51943] namenode.FSNamesystem (FSNamesystem.java:updatePipeline(5559)) - updatePipeline(blk_1073741945_1222, newGS=1228, newLength=1700, newNodes=[127.0.0.1:35859], client=DFSClient_NONMAPREDUCE_1981959463_7705)
2018-09-18 06:01:51,971 INFO  [IPC Server handler 8 on 51943] namenode.FSNamesystem (FSNamesystem.java:updatePipeline(5578)) - updatePipeline(blk_1073741945_1222 => blk_1073741945_1228) success
2018-09-18 06:01:51,978 INFO  [PacketResponder: BP-629685074-10.247.93.25-1537264893675:blk_1073741945_1228, type=LAST_IN_PIPELINE] DataNode.clienttrace (BlockReceiver.java:finalizeBlock(1449)) - src: /127.0.0.1:34952, dest: /127.0.0.1:35859, bytes: 1700, op: HDFS_WRITE, cliID: DFSClient_NONMAPREDUCE_1981959463_7705, offset: 0, srvID: 37f22823-04c7-4d23-8e59-ad2c5bf39e2a, blockid: BP-629685074-10.247.93.25-1537264893675:blk_1073741945_1228, duration: 5901892
2018-09-18 06:01:51,978 INFO  [PacketResponder: BP-629685074-10.247.93.25-1537264893675:blk_1073741945_1228, type=LAST_IN_PIPELINE] datanode.DataNode (BlockReceiver.java:run(1422)) - PacketResponder: BP-629685074-10.247.93.25-1537264893675:blk_1073741945_1228, type=LAST_IN_PIPELINE terminating
2018-09-18 06:01:51,980 INFO  [IPC Server handler 4 on 51943] hdfs.StateChange (FSDirWriteFileOp.java:completeFile(605)) - DIR* completeFile: /Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3 is closed by DFSClient_NONMAPREDUCE_1981959463_7705
```

However, it seems that this situation left the segment store with an inconsistent view of the state of that segment:

```
2018-09-18 06:01:51,980 WARN  [DataStreamer for file /Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3] hdfs.DataStreamer (DataStreamer.java:closeResponder(929)) - Caught exception
java.lang.InterruptedException
    at java.lang.Object.wait(Native Method)
    at java.lang.Thread.join(Thread.java:1249)
    at java.lang.Thread.join(Thread.java:1323)
    at org.apache.hadoop.hdfs.DataStreamer.closeResponder(DataStreamer.java:927)
    at org.apache.hadoop.hdfs.DataStreamer.endBlock(DataStreamer.java:578)
    at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:755)
2018-09-18 06:01:51,980 INFO  [storage-io-2] writer.SegmentAggregator (SegmentAggregator.java:setState(1549)) - StorageWriter[3-556]: State changed from Writing to ReconciliationNeeded.
2018-09-18 06:01:51,980 ERROR [storage-io-2] writer.StorageWriter (StorageWriter.java:logError(457)) - StorageWriter[3]: Iteration[2].Error.
io.pravega.segmentstore.contracts.BadOffsetException: [Segment 'Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0'] Bad Offset. Expected 1700, given 0.
    at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.write(HDFSStorage.java:360)
    at io.pravega.segmentstore.storage.rolling.RollingStorage.write(RollingStorage.java:322)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$write$2(AsyncStorageWrapper.java:100)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$runAsync$15(AsyncStorageWrapper.java:206)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.execute(AsyncStorageWrapper.java:221)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$supplyAsync$13(AsyncStorageWrapper.java:181)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
...
```

Apparently, the segment store is attempting to write to the offset `0` of that transaction segment, whereas there has been a successful write to that segment that appended `1700` bytes of data.
I also see that the old HDFS client (`DFSClient_NONMAPREDUCE_2144198447_7088`) has no more activity since `2018-09-18 06:01:50,191`, whereas the new HDFS client (`DFSClient_NONMAPREDUCE_1981959463_7705`) continues until closing the transaction segment at `2018-09-18 06:01:51,980`. Does this correspond to a segment ownership change between segment store instances related with fencing?

As a possible explanation for this error, I thought that maybe the `AlreadyBeingCreatedException` is a very specific case of a race among HDFS clients that has not been considered in the fencing mechanism. That is, I see in the code careful handlers for HDFS exceptions such as `FileNotFoundException` or  `FileAlreadyExistsException`, but I don't see that `AlreadyBeingCreatedException` has been considered as well.

According to the documentation of `AlreadyBeingCreatedException`:
```
* The exception that happens when you ask to create a file that already
 * is being created, but is not closed yet.
```

Could this be similar case than for `FileAlreadyExistsException`? If so, maybe we can add this exception to `HDFSExceptionHelpers.convertException` as an equivalent to `StreamSegmentExistsException` to ensure that we handle it. Otherwise, if they are conceptually different, perhaps we will need additional code to handle this.

**Comment by fpj** [comment]
I'm seeing this issue again, here is a log file out of a failed run:

[testEndToEndWithFencing.txt](https://github.com/pravega/pravega/files/2615676/testEndToEndWithFencing.txt)

I have observed the `Bad offset` error in the logs.

**Comment by andreipaduroiu** [comment]
This is a brutal test, by design. I saw Raul's explanation about it and it makes perfect sense to me. It is consistent with my own investigation on how `rename` works in HDFS, in that it will not cancel an ongoing write operation. At this time I do not know how to fix this test to pass 100% consistently, short of inventing some new "fencing" mechanism for HDFS Tier 2 files.

**Comment by fpj** [comment]
Here is some relevant output to this discussion, which I'm not seeing in previous comments:

```
# grep 'Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_' testEndToEndWithFencing.txt
2018-09-18 06:01:49,057 INFO  [IPC Server handler 8 on 51943] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true	ugi=root (auth:SIMPLE)	ip=/127.0.0.1	cmd=create	src=/Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_0	dst=null	perm=root:supergroup:rw-------	proto=rpc
2018-09-18 06:01:49,071 INFO  [IPC Server handler 3 on 51943] hdfs.StateChange (FSDirWriteFileOp.java:completeFile(605)) - DIR* completeFile: /Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_0 is closed by DFSClient_NONMAPREDUCE_2144198447_7088
2018-09-18 06:01:49,698 INFO  [IPC Server handler 3 on 51943] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true	ugi=root (auth:SIMPLE)	ip=/127.0.0.1	cmd=rename	src=/Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_0	dst=/Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_2	perm=root:supergroup:rw-------	proto=rpc
2018-09-18 06:01:49,701 INFO  [IPC Server handler 7 on 51943] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true	ugi=root (auth:SIMPLE)	ip=/127.0.0.1	cmd=append	src=/Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_2	dst=null	perm=null	proto=rpc
2018-09-18 06:01:49,797 INFO  [IPC Server handler 0 on 51943] hdfs.StateChange (FSDirWriteFileOp.java:logAllocatedBlock(725)) - BLOCK* allocate blk_1073741945_1222, replicas=127.0.0.1:35859 for /Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_2
2018-09-18 06:01:49,853 INFO  [IPC Server handler 0 on 51943] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true	ugi=root (auth:SIMPLE)	ip=/127.0.0.1	cmd=rename	src=/Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_2	dst=/Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3	perm=root:supergroup:rw-------	proto=rpc
2018-09-18 06:01:49,934 INFO  [IPC Server handler 2 on 51943] namenode.FSNamesystem (FSNamesystem.java:checkBlocksComplete(2697)) - BLOCK* blk_1073741945_1222 is COMMITTED but not COMPLETE(numNodes= 0 <  minimum = 1) in file /Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3
2018-09-18 06:01:50,191 WARN  [IPC Server handler 9 on 51943] hdfs.StateChange (FSDirAppendOp.java:appendFile(138)) - DIR* NameSystem.append: Failed to APPEND_FILE /Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3 for DFSClient_NONMAPREDUCE_1981959463_7705 on 127.0.0.1 because this file lease is currently owned by DFSClient_NONMAPREDUCE_2144198447_7088 on 127.0.0.1
2018-09-18 06:01:50,191 INFO  [IPC Server handler 9 on 51943] ipc.Server (Server.java:logException(2492)) - IPC Server handler 9 on 51943, call Call#39511 Retry#0 org.apache.hadoop.hdfs.protocol.ClientProtocol.append from 127.0.0.1:49016: org.apache.hadoop.hdfs.protocol.AlreadyBeingCreatedException: Failed to APPEND_FILE /Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3 for DFSClient_NONMAPREDUCE_1981959463_7705 on 127.0.0.1 because this file lease is currently owned by DFSClient_NONMAPREDUCE_2144198447_7088 on 127.0.0.1
2018-09-18 06:01:50,335 INFO  [IPC Server handler 7 on 51943] hdfs.StateChange (FSDirWriteFileOp.java:completeFile(605)) - DIR* completeFile: /Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_2 is closed by DFSClient_NONMAPREDUCE_2144198447_7088
org.apache.hadoop.hdfs.protocol.AlreadyBeingCreatedException: Failed to APPEND_FILE /Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3 for DFSClient_NONMAPREDUCE_1981959463_7705 on 127.0.0.1 because this file lease is currently owned by DFSClient_NONMAPREDUCE_2144198447_7088 on 127.0.0.1
Caused by: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.hdfs.protocol.AlreadyBeingCreatedException): Failed to APPEND_FILE /Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3 for DFSClient_NONMAPREDUCE_1981959463_7705 on 127.0.0.1 because this file lease is currently owned by DFSClient_NONMAPREDUCE_2144198447_7088 on 127.0.0.1
2018-09-18 06:01:51,945 INFO  [IPC Server handler 3 on 51943] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true	ugi=root (auth:SIMPLE)	ip=/127.0.0.1	cmd=append	src=/Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3	dst=null	perm=null	proto=rpc
2018-09-18 06:01:51,980 INFO  [IPC Server handler 4 on 51943] hdfs.StateChange (FSDirWriteFileOp.java:completeFile(605)) - DIR* completeFile: /Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3 is closed by DFSClient_NONMAPREDUCE_1981959463_7705
2018-09-18 06:01:51,980 WARN  [DataStreamer for file /Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3] hdfs.DataStreamer (DataStreamer.java:closeResponder(929)) - Caught exception
```

Now why I find these relevant:

1- Note that we start a block allocation with `_2`, rename it from `_2` to `_3`, and commit the block in `_3`:

```
2018-09-18 06:01:49,797 INFO  [IPC Server handler 0 on 51943] hdfs.StateChange (FSDirWriteFileOp.java:logAllocatedBlock(725)) - BLOCK* allocate blk_1073741945_1222, replicas=127.0.0.1:35859 for /Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_2
2018-09-18 06:01:49,853 INFO  [IPC Server handler 0 on 51943] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true	ugi=root (auth:SIMPLE)	ip=/127.0.0.1	cmd=rename	src=/Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_2	dst=/Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3	perm=root:supergroup:rw-------	proto=rpc
2018-09-18 06:01:49,934 INFO  [IPC Server handler 2 on 51943] namenode.FSNamesystem (FSNamesystem.java:checkBlocksComplete(2697)) - BLOCK* blk_1073741945_1222 is COMMITTED but not COMPLETE(numNodes= 0 <  minimum = 1) in file /Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3
```

This is strange as `rename` is supposed to be an atomic operation wrt the file system metadata and adding a a , but it is harmless as no data is being added.

2- The first attempt to append I see fails:

```
2018-09-18 06:01:50,191 WARN  [IPC Server handler 9 on 51943] hdfs.StateChange (FSDirAppendOp.java:appendFile(138)) - DIR* NameSystem.append: Failed to APPEND_FILE /Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3 for DFSClient_NONMAPREDUCE_1981959463_7705 on 127.0.0.1 because this file lease is currently owned by DFSClient_NONMAPREDUCE_2144198447_7088 on 127.0.0.1
```

and I assume this is the result of the rename, but I don't know that for sure.

3- There is a bit later another attempt to append that succeeds:

```
2018-09-18 06:01:51,945 INFO  [IPC Server handler 3 on 51943] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true	ugi=root (auth:SIMPLE)	ip=/127.0.0.1	cmd=append	src=/Segment_0#transaction.bf2cc480df7546f39eddaacf227a1a8a$offset.0_3	dst=null	perm=null	proto=rpc
```

and I have not evidence that this append started before the rename, in fact, it looks like it started after the rename and targeted the new file.

**Comment by andreipaduroiu** [comment]
Yes, we can't tell for sure when one of our `append` operations begins and when it ends, because the HDFS client does a lot behind the scenes.

For instance, the way we append is by opening up a `FsDataOutputStream` (I don't remember the exact name), writing to it, then closing it. That stream can flush data at any time and it will flush remaining data upon close.

The rename may be initiated at any time after opening the stream and before the closing concludes. It is really hard to time these events to see how it behaves in various scenarios, which is why this seems to fail randomly. There must be a combination/timing where things do not go as we expect them to.

**Comment by fpj** [comment]
Here is a new log file from a failed build:

[testEndToEndWithFencing.txt](https://github.com/pravega/pravega/files/2692070/testEndToEndWithFencing.txt)

**Comment by fpj** [comment]
I observed a failure of this test case again, here are the logs:

[testEndToEndWithFencing.txt](https://github.com/pravega/pravega/files/3232729/testEndToEndWithFencing.txt)

**Comment by RaulGracia** [comment]
This test has been disabled in #4346 and soon will be removed as per PDP-34.
