### ISSUE TITLE
HDFS append errors observed in segment stores 

### ISSUE THREAD

**Issue by kmgowda** [pravega/pravega#2967]
**Problem description**
Even though Pravega is funtional/operating.. 
during segment writes, the segment store is throwing following errors:

```
2018-10-08 08:43:29,099 540577 [storage-io-16] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[8]: Iteration[361].Error.
org.apache.hadoop.hdfs.protocol.AlreadyBeingCreatedException: Failed to APPEND_FILE /Scope/StreamName-4/0.#epoch.0$attributes$offset.0_2 for DFSClient_NONMAPREDUCE_-293683934_124 on 10.240.135.50 because DFSClient_NONMAPREDUCE_-293683934_124 is already the current lease holder.
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.recoverLeaseInternal(FSNamesystem.java:3140)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInternal(FSNamesystem.java:2935)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInt(FSNamesystem.java:3247)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFile(FSNamesystem.java:3216)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.append(NameNodeRpcServer.java:767)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.append(ClientNamenodeProtocolServerSideTranslatorPB.java:433)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:640)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2351)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2347)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1869)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2347)
        at sun.reflect.GeneratedConstructorAccessor30.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
        at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:110)
        at io.pravega.segmentstore.storage.impl.hdfs.HDFSExceptionHelpers.convertException(HDFSExceptionHelpers.java:37)
        at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.write(HDFSStorage.java:382)
        at io.pravega.segmentstore.storage.rolling.RollingStorage.write(RollingStorage.java:322)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$write$2(AsyncStorageWrapper.java:100)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$runAsync$15(AsyncStorageWrapper.java:206)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.execute(AsyncStorageWrapper.java:221)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$supplyAsync$13(AsyncStorageWrapper.java:181)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.ipc.RemoteException: Failed to APPEND_FILE /Scope/StreamName-4/0.#epoch.0$attributes$offset.0_2 for DFSClient_NONMAPREDUCE_-293683934_124 on 10.240.135.50 because DFSClient_NONMAPREDUCE_-293683934_124 is already the current lease holder.
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.recoverLeaseInternal(FSNamesystem.java:3140)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInternal(FSNamesystem.java:2935)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInt(FSNamesystem.java:3247)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFile(FSNamesystem.java:3216)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.append(NameNodeRpcServer.java:767)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.append(ClientNamenodeProtocolServerSideTranslatorPB.java:433)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:640)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2351)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2347)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1869)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2347)
        at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1481)
        at org.apache.hadoop.ipc.Client.call(Client.java:1427)
        at org.apache.hadoop.ipc.Client.call(Client.java:1337)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:227)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
        at com.sun.proxy.$Proxy13.append(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.append(ClientNamenodeProtocolTranslatorPB.java:324)
        at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:398)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:163)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:155)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:335)
        at com.sun.proxy.$Proxy14.append(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.callAppend(DFSClient.java:1366)
        at org.apache.hadoop.hdfs.DFSClient.callAppend(DFSClient.java:1388)
        at org.apache.hadoop.hdfs.DFSClient.append(DFSClient.java:1457)
        at org.apache.hadoop.hdfs.DFSClient.append(DFSClient.java:1427)
        at org.apache.hadoop.hdfs.DistributedFileSystem$5.doCall(DistributedFileSystem.java:362)
        at org.apache.hadoop.hdfs.DistributedFileSystem$5.doCall(DistributedFileSystem.java:358)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.append(DistributedFileSystem.java:370)
        at org.apache.hadoop.hdfs.DistributedFileSystem.append(DistributedFileSystem.java:339)
        at org.apache.hadoop.fs.FileSystem.append(FileSystem.java:1177)
        at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.write(HDFSStorage.java:356)
        ... 13 common frames omitted

```

**Problem location**
segment store

This an issue HDFS Write and its already reported here : 
https://issues.apache.org/jira/browse/HDFS-11367

**Suggestions for an improvement**

So, this link : https://issues.apache.org/jira/browse/HDFS-11367

suggest that to use

                   writer.close();
                   writerMap.remove(outputFile.toUri().getPath());

in the segment store  appropriately to close the writer stream

this should examined 

resolving this issue may improve the performance too.

**Comment by kmgowda** [comment]
with isilon as HDFS storage , these error/warnings are not observed

**Comment by arvindkandhare** [comment]
The writer is opened with `try-with-resources` block. So all the paths it takes will always ensure that it is closed. We do not have the `writerMap`.

**Comment by RaulGracia** [comment]
@kmgowda could you perform the same test with a newer version of Pravega? In PR #2988 we added the handling of `AlreadyBeingCreatedException` similarly to `StreamSegmentExistsException`. Let's see if this kind of HDFS exceptions are minimized.

**Comment by sachin-j-joshi** [comment]
- This issue is related to HDFS setup. In this case our cluster is very small cluster (n<= 3).
- **The root cause** of this exception is the fact that we are using small cluster and any network glitches or data node being unresponsive causes failures in setup of data pipeline. We get following exception

>  java.io.IOException: Failed to replace a bad datanode on the existing pipeline due to no more good datanodes being available to try.

- The **workaround/ solution** is to set hdfs.replaceDataNodesOnFailure = false for SegmentStore config (similar to what we do for docker and mesos based tests.). This sets dfs.client.block.write.replace-datanode-on-failure.policy = NEVER for the hdfs client in SegmentStore. 
- Also please note that I have made sure that this issue is not cause by concurrent access to same segment due to scheduling bug in segment store .(Basically just to be absolutely sure - I made all methods on HDFSStorage synchronized, ran simple test with only one segment store. I still get the same error when running against a single node HDFS deployment.)

**Comment by sachin-j-joshi** [comment]
@vijikarthi @kmgowda  Based on my understanding of the underlying issue , the root cause is the tiny size of the HDFS cluster which eventually causes some/all data nodes being considered "bad" and unable to be replaced.  

Without explicitly setting dfs.client.block.write.replace-datanode-on-failure.policy = NEVER, this is unavoidable situation given the tiny cluster size.

I have double checked that this is not cause by any scheduling problems with tier-2 writes.

I recommend setting hdfs.replaceDataNodesOnFailure = false in the perf tests. 


[See also - https://github.com/pravega/pravega/issues/3400]

**Comment by kmgowda** [comment]
Thanks Sachin
