### ISSUE TITLE
Sporadic build failures: ControllerServiceWithZKStreamTest streamCutTests 

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#2972]
**Problem description**

```
io.pravega.controller.server.ControllerServiceWithZKStreamTest > streamCutTests FAILED
    java.util.concurrent.ExecutionException: io.pravega.controller.store.stream.StoreException$DataNotFoundException: Segment : 8589934596
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at io.pravega.controller.server.ControllerServiceWithZKStreamTest.testEmptyFrom(ControllerServiceWithZKStreamTest.java:409)
        at io.pravega.controller.server.ControllerServiceWithZKStreamTest.streamCutTests(ControllerServiceWithZKStreamTest.java:261)
        Caused by:
        io.pravega.controller.store.stream.StoreException$DataNotFoundException: Segment : 8589934596

```
**Problem location**

**Suggestions for an improvement**

**Comment by tkaitchuck** [comment]
Another log:
```
io.pravega.controller.server.ControllerServiceWithZKStreamTest > streamCutTests FAILED
    java.util.concurrent.ExecutionException: io.pravega.controller.store.stream.StoreException$DataNotFoundException: Segment : 8589934596
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at io.pravega.controller.server.ControllerServiceWithZKStreamTest.testEmptyFrom(ControllerServiceWithZKStreamTest.java:409)
        at io.pravega.controller.server.ControllerServiceWithZKStreamTest.streamCutTests(ControllerServiceWithZKStreamTest.java:261)
        Caused by:
        io.pravega.controller.store.stream.StoreException$DataNotFoundException: Segment : 8589934596
```
Does 8589934596 mean something in the context of the test?

**Comment by shrids** [comment]
Observing a similar stack trace during Travis build.

```
io.pravega.controller.server.ControllerServiceWithZKStreamTest > streamCutTests FAILED
    java.util.concurrent.ExecutionException: io.pravega.controller.store.stream.StoreException$DataNotFoundException: Segment : 8589934596
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at io.pravega.controller.server.ControllerServiceWithZKStreamTest.testEmptyFrom(ControllerServiceWithZKStreamTest.java:412)
        at io.pravega.controller.server.ControllerServiceWithZKStreamTest.streamCutTests(ControllerServiceWithZKStreamTest.java:264)
        Caused by:
        io.pravega.controller.store.stream.StoreException$DataNotFoundException: Segment : 8589934596
```

**Comment by shiveshr** [comment]
We havent seen this in a while. Closing it.
