### ISSUE TITLE
ConcurrentEventProcessorTest logs exceptions

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#3018]
**Problem description**
There appears to be some sort of race condition with shutdown or startup in ConcurrentEventProcessorTest. 
```
io.pravega.controller.eventProcessor.impl.ConcurrentEventProcessorTest > testFailedProcessingNonRetryable PASSED
io.pravega.controller.eventProcessor.impl.ConcurrentEventProcessorTest > testWriteBackFailed PASSED
io.pravega.controller.eventProcessor.impl.ConcurrentEventProcessorTest > testFailedProcessingRetryable PASSED
io.pravega.controller.eventProcessor.impl.ConcurrentEventProcessorTest > testConcurrentEventProcessor PASSED
2018-10-25 01:33:46,188 325244 [pool-300-thread-1] ERROR i.p.c.s.stream.ZKGarbageCollector - Exception thrown during Garbage Collection iteration for completedTxnGC. Log and ignore.
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$UnknownException: /garbagecollection/completedTxnGC/guard
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:943)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:997)
	at java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2135)
	at io.pravega.controller.store.stream.ZKGarbageCollector.process(ZKGarbageCollector.java:133)
	at io.pravega.common.concurrent.Futures.lambda$delayedFuture$21(Futures.java:536)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.pravega.common.concurrent.Futures.lambda$delayedFuture$19(Futures.java:516)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.controller.store.stream.StoreException$UnknownException: /garbagecollection/completedTxnGC/guard
	at io.pravega.controller.store.stream.StoreException.create(StoreException.java:108)
	at io.pravega.controller.store.stream.ZKStoreHelper.setData(ZKStoreHelper.java:183)
	at io.pravega.controller.store.stream.ZKGarbageCollector.process(ZKGarbageCollector.java:132)
	... 12 common frames omitted
Caused by: java.lang.IllegalStateException: instance must be started before calling this method
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.setData(CuratorFrameworkImpl.java:442)
	at io.pravega.controller.store.stream.ZKStoreHelper.setData(ZKStoreHelper.java:178)
	... 13 common frames omitted
2018-10-25 01:33:46,203 325259 [pool-284-thread-1] ERROR i.p.c.s.stream.ZKGarbageCollector - Exception thrown during Garbage Collection iteration for completedTxnGC. Log and ignore.
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$UnknownException: /garbagecollection/completedTxnGC/guard
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:943)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:997)
	at java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2135)
	at io.pravega.controller.store.stream.ZKGarbageCollector.process(ZKGarbageCollector.java:133)
	at io.pravega.common.concurrent.Futures.lambda$delayedFuture$21(Futures.java:536)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.pravega.common.concurrent.Futures.lambda$delayedFuture$19(Futures.java:516)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.controller.store.stream.StoreException$UnknownException: /garbagecollection/completedTxnGC/guard
	at io.pravega.controller.store.stream.StoreException.create(StoreException.java:108)
	at io.pravega.controller.store.stream.ZKStoreHelper.setData(ZKStoreHelper.java:183)
	at io.pravega.controller.store.stream.ZKGarbageCollector.process(ZKGarbageCollector.java:132)
	... 12 common frames omitted
Caused by: java.lang.IllegalStateException: instance must be started before calling this method
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.setData(CuratorFrameworkImpl.java:442)
	at io.pravega.controller.store.stream.ZKStoreHelper.setData(ZKStoreHelper.java:178)
	... 13 common frames omitted
```

**Comment by shrids** [comment]
Closing this since we have not observed this issue in the recent past, please reopen if observed again.
