### ISSUE TITLE
Controller increasing memory consumption and crash

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#3042]
**Problem description**
We executed a battery of longevity runs in a small cluster (3 nodes) under a light write/read workload (`mediumScale`) with Pravega `0.3.3`. As can be observed in the figure below, the Controller process (dotted red line) is slowly consuming memory along time:
![mem_usage_per_process_time_series](https://user-images.githubusercontent.com/717112/47737408-2b429880-dc71-11e8-8099-f11e2ce0fa37.jpg)

Interestingly, these experiments do not consist of managing multiple Streams or heavily work with Transactions; they are mainly IO operations, so the Controller workload should be limited.

**Problem location**
Controller.

**Suggestions for an improvement**
Profile the memory consumption of Controller to detect a possible memory leak.

**Comment by RaulGracia** [comment]
Next, we provide a plot from a longevity run in the same execution environment but with a more intensive workload (`smash`) to reproduce the issue.

In this case, we observe that the controller process suddenly starts consuming a large amount of memory after `16.5h` of experiment. This abrupt spike in memory consumption contrasts with the more stable profile exhibited up to this point. Moreover, a similar (but even more drastic) phenomenon is observed regarding CPU consumption. After some time in this abnormal state, the Controller process dies and a new one is spawned.

![cpu_vs_mem_controller_time_series](https://user-images.githubusercontent.com/717112/47907965-93b99180-de8c-11e8-9144-cbf400b8d3bd.jpg)

**Comment by RaulGracia** [comment]
In our attempts to identify the root cause of the controller crash, I found the following problem that may be related to this issue (and perhaps other recently reported issues).

_Goal_: Reproduce the Controller issue that makes the process to crash. 

_Scenario_: One client executing `updateStream()` operations against the Contoller. This forces the Controller to perform a high number of interactions against ZK. We also ran a ZK and a Segment Store instance.

_Result_: I observed that after few minutes of execution, the Controller i) lost the ZK session, and ii) got stuck trying to restart, iii) meanwhile the client was blocked.

i) As visible in the logs, the Controller stops serving `updateStream` requests and gets a `KeeperException$SessionExpiredException`. 
```
2018-11-26 16:01:40,701 821160 [nioEventLoopGroup-3-3] INFO  i.p.c.n.i.ClientConnectionInboundHandler - Connection established ChannelHandlerContext(ClientConnectionInboundHandler#0, [id: 0x540abf3a]) 
2018-11-26 16:01:40,708 821167 [nioEventLoopGroup-3-3] INFO  i.p.s.p.netty.FailingReplyProcessor - Received hello: WireCommands.Hello(type=HELLO, highVersion=5, lowVersion=5)
2018-11-26 16:01:40,715 821174 [nioEventLoopGroup-3-3] INFO  i.p.controller.server.SegmentHelper - updatePolicy examples/helloStream3/0.#epoch.0 SegmentPolicyUpdated
2018-11-26 16:01:40,716 821175 [nioEventLoopGroup-3-3] WARN  i.p.controller.server.SegmentHelper - updatePolicy examples/helloStream3/0.#epoch.0 connectionDropped
2018-11-26 16:01:40,772 821231 [grpc-default-executor-4] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - updateStream called for stream examples/helloStream3.
2018-11-26 16:01:40,779 821238 [nioEventLoopGroup-3-1] INFO  i.p.c.t.Stream.StreamMetadataTasks - event posted successfully
2018-11-26 16:01:41,702 822161 [nioEventLoopGroup-3-5] INFO  i.p.c.n.i.ClientConnectionInboundHandler - Connection established ChannelHandlerContext(ClientConnectionInboundHandler#0, [id: 0x4743d864]) 
2018-11-26 16:01:41,710 822169 [nioEventLoopGroup-3-5] INFO  i.p.s.p.netty.FailingReplyProcessor - Received hello: WireCommands.Hello(type=HELLO, highVersion=5, lowVersion=5)
2018-11-26 16:01:41,711 822170 [nioEventLoopGroup-3-5] INFO  i.p.controller.server.SegmentHelper - updatePolicy examples/helloStream3/0.#epoch.0 SegmentPolicyUpdated
2018-11-26 16:01:41,713 822172 [nioEventLoopGroup-3-5] WARN  i.p.controller.server.SegmentHelper - updatePolicy examples/helloStream3/0.#epoch.0 connectionDropped
2018-11-26 16:01:41,748 822207 [grpc-default-executor-4] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - updateStream called for stream examples/helloStream3.
2018-11-26 16:01:41,754 822213 [nioEventLoopGroup-3-1] INFO  i.p.c.t.Stream.StreamMetadataTasks - event posted successfully
2018-11-26 16:01:42,743 823202 [nioEventLoopGroup-3-4] INFO  i.p.c.n.i.ClientConnectionInboundHandler - Connection established ChannelHandlerContext(ClientConnectionInboundHandler#0, [id: 0xd275f7d0]) 
2018-11-26 16:01:53,152 833611 [ControllerServiceMain-SendThread(localhost:2181)] WARN  org.apache.zookeeper.ClientCnxn - Client session timed out, have not heard from server in 10417ms for sessionid 0x10009f378040001
2018-11-26 16:01:53,155 833614 [ControllerServiceMain-SendThread(localhost:2181)] INFO  org.apache.zookeeper.ClientCnxn - Client session timed out, have not heard from server in 10417ms for sessionid 0x10009f378040001, closing socket connection and attempting reconnect
2018-11-26 16:01:53,202 833661 [nioEventLoopGroup-3-4] INFO  i.p.s.p.netty.FailingReplyProcessor - Received hello: WireCommands.Hello(type=HELLO, highVersion=5, lowVersion=5)
2018-11-26 16:01:53,203 833662 [nioEventLoopGroup-3-4] INFO  i.p.controller.server.SegmentHelper - updatePolicy examples/helloStream3/0.#epoch.0 SegmentPolicyUpdated
2018-11-26 16:01:53,211 833670 [nioEventLoopGroup-3-4] WARN  i.p.controller.server.SegmentHelper - updatePolicy examples/helloStream3/0.#epoch.0 connectionDropped
2018-11-26 16:01:53,703 834162 [ControllerServiceMain-SendThread(localhost:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
2018-11-26 16:01:53,704 834163 [ControllerServiceMain-SendThread(localhost:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /0:0:0:0:0:0:0:1:52570, server: localhost/0:0:0:0:0:0:0:1:2181
2018-11-26 16:01:53,720 834179 [ControllerServiceMain-SendThread(localhost:2181)] WARN  org.apache.zookeeper.ClientCnxn - Unable to reconnect to ZooKeeper service, session 0x10009f378040001 has expired
2018-11-26 16:01:53,722 834181 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - ZK session expired
2018-11-26 16:01:53,723 834182 [ControllerServiceMain-SendThread(localhost:2181)] INFO  org.apache.zookeeper.ClientCnxn - Unable to reconnect to ZooKeeper service, session 0x10009f378040001 has expired, closing socket connection
2018-11-26 16:01:53,724 834183 [ControllerServiceMain-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x10009f378040001
2018-11-26 16:01:53,728 834187 [Curator-Framework-0] INFO  o.a.c.f.imps.CuratorFrameworkImpl - backgroundOperationsLoop exiting
2018-11-26 16:01:53,750 834209 [ControllerServiceMain] ERROR org.apache.zookeeper.ClientCnxn - Exception when removing watcher
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /zookeeper/config
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:131)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper$ZKWatchManager.removeWatches(ZooKeeper.java:419)
	at org.apache.zookeeper.ZooKeeper$ZKWatchManager.removeWatcher(ZooKeeper.java:318)
	at org.apache.zookeeper.WatchDeregistration.unregister(WatchDeregistration.java:58)
	at org.apache.zookeeper.ClientCnxn.finishPacket(ClientCnxn.java:683)
	at org.apache.zookeeper.ClientCnxn.conLossPacket(ClientCnxn.java:745)
	at org.apache.zookeeper.ClientCnxn.queuePacket(ClientCnxn.java:1554)
	at org.apache.zookeeper.ZooKeeper.removeWatches(ZooKeeper.java:2840)
	at org.apache.zookeeper.ZooKeeper.removeWatches(ZooKeeper.java:2749)
	at org.apache.curator.framework.imps.RemoveWatchesBuilderImpl.performBackgroundOperation(RemoveWatchesBuilderImpl.java:339)
	at org.apache.curator.framework.imps.OperationAndData.callPerformBackgroundOperation(OperationAndData.java:84)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:934)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:614)
	at org.apache.curator.framework.imps.RemoveWatchesBuilderImpl.pathInBackground(RemoveWatchesBuilderImpl.java:223)
	at org.apache.curator.framework.imps.RemoveWatchesBuilderImpl.internalRemoval(RemoveWatchesBuilderImpl.java:83)
	at org.apache.curator.framework.imps.WatcherRemovalManager.removeWatchers(WatcherRemovalManager.java:71)
	at org.apache.curator.framework.imps.WatcherRemovalFacade.removeWatchers(WatcherRemovalFacade.java:68)
	at org.apache.curator.framework.imps.EnsembleTracker.close(EnsembleTracker.java:102)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.close(CuratorFrameworkImpl.java:376)
	at io.pravega.controller.store.client.ZKStoreClient.close(ZKStoreClient.java:37)
	at io.pravega.controller.server.ControllerServiceMain.run(ControllerServiceMain.java:148)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.lang.Thread.run(Thread.java:748)
```

ii) In this situation, the Controller tries to restart and faces multiple failures during the shutdown process due to the ZKClient crash (expired session):
```
2018-11-26 16:01:53,757 834216 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - Stopping ControllerServiceStarter
2018-11-26 16:01:53,766 834225 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - Awaiting termination of ControllerServiceStarter
2018-11-26 16:01:53,767 834226 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Initiating controller service shutDown
2018-11-26 16:01:53,770 834229 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Stopping controller event processors
2018-11-26 16:01:53,771 834230 [RESTServer STOPPING] INFO  i.p.c.server.rest.RESTServer - Stopping REST server listening on port: 9091
2018-11-26 16:01:53,771 834230 [GRPCServer STOPPING] INFO  i.p.c.server.rpc.grpc.GRPCServer - Stopping gRPC server listening on port: 9090
2018-11-26 16:01:53,773 834232 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Stopping the segment container monitor
2018-11-26 16:01:53,775 834234 [ControllerEventProcessors STOPPING] INFO  i.p.c.s.e.ControllerEventProcessors - Stopping controller event processors
2018-11-26 16:01:53,777 834236 [ControllerEventProcessors STOPPING] INFO  i.p.c.s.e.ControllerEventProcessors - Stopping commit event processors
2018-11-26 16:01:53,777 834236 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Stopping controller cluster listener
2018-11-26 16:01:53,780 834239 [Curator-LeaderSelector-0] WARN  i.p.c.fault.SegmentMonitorLeader - Leadership interrupted, releasing monitor thread
2018-11-26 16:01:53,780 834239 [ControllerEventProcessors STOPPING] INFO  i.p.c.s.e.ControllerEventProcessors - Stopping abort event processors
2018-11-26 16:01:53,782 834241 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Controller cluster listener shutdown
2018-11-26 16:01:53,784 834243 [ControllerClusterListener STOPPING] INFO  i.p.c.f.ControllerClusterListener - Deregistering host 10.41.19.127:9090:7ef0bc88-72f4-42ae-8657-91a4585af449 from controller cluster
2018-11-26 16:01:53,784 834243 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Stopping auto retention service
2018-11-26 16:01:53,784 834243 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.e.i.EventProcessorGroupImpl - Attempting to seal the reader group entry from checkpoint store
2018-11-26 16:01:53,785 834244 [ControllerEventProcessors STOPPING] INFO  i.p.c.s.e.ControllerEventProcessors - Stopping request event processors
2018-11-26 16:01:53,787 834246 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.e.i.EventProcessorGroupImpl - Attempting to seal the reader group entry from checkpoint store
2018-11-26 16:01:53,793 834252 [GRPCServer STOPPING] INFO  i.p.c.server.rpc.grpc.GRPCServer - Awaiting termination of gRPC server
2018-11-26 16:01:53,794 834253 [ControllerEventProcessors STOPPING] INFO  i.p.c.s.e.ControllerEventProcessors - Awaiting termination of commit event processors
2018-11-26 16:01:53,799 834258 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.e.i.EventProcessorGroupImpl - Attempting to seal the reader group entry from checkpoint store
2018-11-26 16:01:53,797 834256 [ControllerClusterListener STOPPING] ERROR i.p.c.cluster.zkImpl.ClusterZKImpl - Error while closing resource
java.io.IOException: java.lang.IllegalStateException: instance must be started before calling this method
	at org.apache.curator.framework.recipes.nodes.PersistentNode.close(PersistentNode.java:353)
	at io.pravega.common.cluster.zkImpl.ClusterZKImpl.close(ClusterZKImpl.java:169)
	at io.pravega.common.cluster.zkImpl.ClusterZKImpl.deregisterHost(ClusterZKImpl.java:104)
	at io.pravega.controller.fault.ControllerClusterListener.shutDown(ControllerClusterListener.java:150)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$2.run(AbstractIdleService.java:79)
	at com.jprofiler.agent.callee.RunnableTracking.run(ejt:20)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: instance must be started before calling this method
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.delete(CuratorFrameworkImpl.java:418)
	at org.apache.curator.framework.recipes.nodes.PersistentNode.deleteNode(PersistentNode.java:416)
	at org.apache.curator.framework.recipes.nodes.PersistentNode.close(PersistentNode.java:348)
	... 7 common frames omitted
2018-11-26 16:01:53,831 834290 [ControllerClusterListener STOPPING] INFO  i.p.c.f.ControllerClusterListener - Controller cluster listener shutDown complete
2018-11-26 16:01:53,845 834304 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Closing stream metadata tasks
2018-11-26 16:01:53,817 834276 [Curator-LeaderSelector-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background exception was not retry-able or retry gave up
java.lang.IllegalStateException: Client is not started
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:139)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:938)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:614)
...
```

ii) At some point, the shutdown process completes but the Controller remains stuck for several minutes:

```
2018-11-26 16:01:55,556 836015 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.e.i.EventProcessorGroupImpl - Shutdown of EventProcessorGroup[commitStreamReaders] complete
2018-11-26 16:01:55,556 836015 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.s.i.SegmentMetadataClientImpl - Closing segment metadata connection for _system/_RGabortStreamReaders/0.#epoch.0
2018-11-26 16:01:55,556 836015 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.s.i.SegmentMetadataClientImpl - Closing segment metadata connection for _system/_RGscaleGroup/0.#epoch.0
2018-11-26 16:01:55,557 836016 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.s.i.SegmentMetadataClientImpl - Closing connection with exception: null
2018-11-26 16:01:55,557 836016 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.s.i.SegmentMetadataClientImpl - Closing connection with exception: null
2018-11-26 16:01:55,558 836017 [ControllerEventProcessors STOPPING] INFO  i.p.c.s.e.ControllerEventProcessors - Awaiting termination of abort event processors
2018-11-26 16:01:55,559 836018 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Closing reader for _system/_RGabortStreamReaders/0.#epoch.0
2018-11-26 16:01:55,559 836018 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Closing connection to segment: _system/_RGabortStreamReaders/0.#epoch.0
2018-11-26 16:01:55,560 836019 [nioEventLoopGroup-3-1] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Closing connection to segment: _system/_RGabortStreamReaders/0.#epoch.0
2018-11-26 16:01:55,560 836019 [nioEventLoopGroup-3-1] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Connection failed due to a io.pravega.shared.protocol.netty.ConnectionFailedException. Read requests will be retransmitted.
2018-11-26 16:01:55,559 836018 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Closing reader for _system/_RGscaleGroup/0.#epoch.0
2018-11-26 16:01:55,561 836020 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Closing connection to segment: _system/_RGscaleGroup/0.#epoch.0
2018-11-26 16:01:55,562 836021 [nioEventLoopGroup-3-8] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Closing connection to segment: _system/_RGscaleGroup/0.#epoch.0
2018-11-26 16:01:55,562 836021 [nioEventLoopGroup-3-8] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Connection failed due to a io.pravega.shared.protocol.netty.ConnectionFailedException. Read requests will be retransmitted.
2018-11-26 16:01:55,563 836022 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Connection failed due to a io.pravega.client.stream.impl.ConnectionClosedException. Read requests will be retransmitted.
2018-11-26 16:01:55,563 836022 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Connection failed due to a io.pravega.client.stream.impl.ConnectionClosedException. Read requests will be retransmitted.
2018-11-26 16:01:55,564 836023 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.e.i.EventProcessorGroupImpl - Shutdown of EventProcessorGroup[abortStreamReaders] complete
2018-11-26 16:01:55,564 836023 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.e.i.EventProcessorGroupImpl - Shutdown of EventProcessorGroup[scaleGroup] complete
2018-11-26 16:01:55,565 836024 [ControllerEventProcessors STOPPING] INFO  i.p.c.s.e.ControllerEventProcessors - Awaiting termination of request event processors
2018-11-26 16:01:55,566 836025 [ControllerEventProcessors STOPPING] INFO  i.p.c.s.e.ControllerEventProcessors - Controller event processors shutDown complete
(Controller gets stuck here)
```

iv) Meanwhile, the client is block and not able to proceed or to crash. After some time, the Controller restarts (with problems) but the client is not able to proceed:

```
2018-11-26 16:27:49,436 2389895 [clientInternal-2] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Fetching endpoint for segment _system/_abortStream/1.#epoch.0, writerID: 9e14bb2f-27e2-4218-8461-2477aa364006
2018-11-26 16:27:49,438 2389897 [clientInternal-2] WARN  i.p.c.s.i.SegmentOutputStreamImpl - 9e14bb2f-27e2-4218-8461-2477aa364006 Failed to connect: 
java.util.concurrent.CompletionException: io.pravega.controller.store.host.HostStoreException: Failed to fetch segment container map from zookeeper
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.pravega.common.concurrent.Futures.lambda$delayedFuture$19(Futures.java:516)
	at com.jprofiler.agent.callee.CallableTracking.call(ejt:22)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.controller.store.host.HostStoreException: Failed to fetch segment container map from zookeeper
	at io.pravega.controller.store.host.ZKHostStore.getCurrentHostMap(ZKHostStore.java:81)
	at io.pravega.controller.store.host.ZKHostStore.getHostForContainer(ZKHostStore.java:106)
	at io.pravega.controller.store.host.ZKHostStore.getHostForSegment(ZKHostStore.java:125)
	at io.pravega.controller.server.SegmentHelper.getSegmentUri(SegmentHelper.java:52)
	at io.pravega.controller.server.ControllerService.getURI(ControllerService.java:243)
	at io.pravega.controller.server.eventProcessor.LocalController.getEndpointForSegment(LocalController.java:367)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl.lambda$null$4(SegmentOutputStreamImpl.java:535)
	at io.pravega.common.concurrent.Futures.lambda$delayedFuture$21(Futures.java:536)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	... 11 common frames omitted
Caused by: java.lang.IllegalStateException: instance must be started before calling this method
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getData(CuratorFrameworkImpl.java:434)
	at io.pravega.controller.store.host.ZKHostStore.getCurrentHostMap(ZKHostStore.java:79)
	... 19 common frames omitted
2018-11-26 16:27:49,439 2389898 [clientInternal-3] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Fetching endpoint for segment _system/_requeststream/1.#epoch.0, writerID: ab372e32-3ee9-4e69-bfe9-bbf8041880cb
2018-11-26 16:27:49,441 2389900 [clientInternal-3] WARN  i.p.c.s.i.SegmentOutputStreamImpl - ab372e32-3ee9-4e69-bfe9-bbf8041880cb Failed to connect: 
java.util.concurrent.CompletionException: io.pravega.controller.store.host.HostStoreException: Failed to fetch segment container map from zookeeper
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.pravega.common.concurrent.Futures.lambda$delayedFuture$19(Futures.java:516)
	at com.jprofiler.agent.callee.CallableTracking.call(ejt:22)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.controller.store.host.HostStoreException: Failed to fetch segment container map from zookeeper
	at io.pravega.controller.store.host.ZKHostStore.getCurrentHostMap(ZKHostStore.java:81)
	at io.pravega.controller.store.host.ZKHostStore.getHostForContainer(ZKHostStore.java:106)
	at io.pravega.controller.store.host.ZKHostStore.getHostForSegment(ZKHostStore.java:125)
	at io.pravega.controller.server.SegmentHelper.getSegmentUri(SegmentHelper.java:52)
	at io.pravega.controller.server.ControllerService.getURI(ControllerService.java:243)
	at io.pravega.controller.server.eventProcessor.LocalController.getEndpointForSegment(LocalController.java:367)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl.lambda$null$4(SegmentOutputStreamImpl.java:535)
	at io.pravega.common.concurrent.Futures.lambda$delayedFuture$21(Futures.java:536)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	... 11 common frames omitted
Caused by: java.lang.IllegalStateException: instance must be started before calling this method
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getData(CuratorFrameworkImpl.java:434)
	at io.pravega.controller.store.host.ZKHostStore.getCurrentHostMap(ZKHostStore.java:79)
	... 19 common frames omitted
```

The reason to report this problem is that it matches the characteristics of the original issue:
i) Involve ZK client errors: Such as session expiration (see #3077). 
ii) Malfunction for a period of time: In this experiment, the Controller gets stuck for several minutes while trying to restart. Note that meanwhile, the process may continue accumulating requests from other clients, which could explain the sustained memory spike. 
iii) Restart the process: In this experiment the Controller process restarts, which also happens in the original issue.

cc/ @shiveshr

**Comment by RaulGracia** [comment]
I reproduced the previous situation twice today. After 400 to 600 `updateStream` operations we hit this problem. This also happens even after upgrading Apache Curator client from `4.0.0` to `4.0.1`.

**Comment by shiveshr** [comment]
the reason for controller service to take a very long time to shutdown is following:
we use grpc.shutdown which waits for all ongoing grpc requests to complete before shutting down grpc service. 

There is an ongoing grpc call, in this case `updateStream` which hasnt completed.
The reason for its failure to complete is on the curator though.

following is the pattern we use for making zk calls in the store:

```
grpcService -> store -> getData(path) {
    curatorClient.getData().inBackground(callback, executor).forPath(path)
}
```

If zk session has expired, the curator sends interrupt to the background work. this doesnt result in the callback being invoked. 

If i remove the asynchronous curator client call with a synchronous call then the curator immediately throws IllegalStateException and our future is completed and grpc returns failure to the caller.

**Comment by RaulGracia** [comment]
Thanks @shiveshr, this may be an important step forward to address this problem. Apart from that, we may assume that there is a small probability of having a request that takes too long to complete (e.g., due to some problem in the ZK client). To deal with this, would it make sense to add timeouts to ZK operations (shorter than ZK session timeout) to avoid the ZK session expiration errors? In the case a request takes too long, we may just consider it as failed.

**Comment by shiveshr** [comment]
Update: curator doesnt have a problem as assumed earlier.. 
The problem is with the `ExponentialBackoffRetry` policy we use for retries in curator client. 
The value we supply is 500ms as base and 10 retries. 
The logic for exponential retry in curator is as follows:
```        long sleepMs = baseSleepTimeMs * Math.max(1, random.nextInt(1 << (retryCount + 1)));
```
So in worst case this sleepMs across 10 retries would be: 500 * 2 + 500 * 4 + 500 * 8 + ....  + 500 * 1024 ~= 2048 * 500ms ~= `1000 seconds`.

The moment we reduce our input parameters for retry we get the curator calling the callback method and grpc call completing.

**Comment by fpj** [comment]
Awesome catch, @shiveshr ! If I recall it right, we use curator in a way that we provide the zk client instance to prevent it from creating new clients under the hood. We keep providing the same instance to avoid the problem of transparent session creation, but the side-effect of this scheme that curator will keep retrying expecting that we provide a new client. Ideally, if the session expired, we should simply make curator bail out.

**Comment by shiveshr** [comment]
Yes @fpj that’s absolutely right.

**Comment by RaulGracia** [comment]
With the recent related PRs merged, as well as the changes in the Controller metadata management and testing infrastructure, the original problem that motivated this issue seems fixed. That is, after executing the same `mediumScale` workload for 3 days, the Controller is actually consuming around 400MB of memory (600MB committed). The memory increase trend is less pronounced than in the original issue, despite we need to further analyze the stabilization point. Moreover, the sustained spike of CPU/Memory that preceded the Controller crash has been fixed due to the improvements in the zk session management. I'm inclined to close this issue. If we find new resource problems in the Controller, they can be reported in separate issues.
