### ISSUE TITLE
NPE observed after scaling up Zookeeper on PKS cluster

### ISSUE THREAD

**Issue by deenav** [pravega/pravega#3105]
**Curator throws NullPointerException on controller logs after scaling up Zookeeper on PKS cluster**

In a PKS cluster, started moderate IO with Pravega Benchmark tool and tried scale up of Zookeeper from 3 to 5 using ``` kubectl edit zk nautilus-pravega-zookeeper ```.  Observed ``` ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background exception was not retry-able or retry gave up
java.lang.NullPointerException: null ``` NullPointerException on controller log file and after that no further logging happened.

**Steps Followed**
1. Created PKS cluster and deployed `Pravega Build : 0.4.0-rc1` by using `PravegaOperator` method 
2. Started moderate IO with Pravega Benchmark tool 
3. Used ` kubectl edit PravegaCluster <cluster-name>` to scale up pravega components, Segmentstore from 3 to 10 and Bookies from 3 to 10
4. Now, tried to scale up of Zookeeper from 3 to 5 using ``` kubectl edit zk nautilus-pravega-zookeeper ```
5. Observed ``` ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background exception was not retry-able or retry gave up
java.lang.NullPointerException: null ```

**Log Snip**

``` 2018-11-14 09:17:29,613 83780487 [ControllerServiceMain-EventThread] INFO  o.a.c.f.imps.EnsembleTracker - New config event received: {server.1=nautilus-pravega-zookeeper-0.nautilus-pravega-zookeeper-headless.default.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, version=1000437ce, server.5=nautilus-pravega-zookeeper-4.nautilus-pravega-zookeeper-headless.default.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, server.4=nautilus-pravega-zookeeper-3.nautilus-pravega-zookeeper-headless.default.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, server.3=nautilus-pravega-zookeeper-2.nautilus-pravega-zookeeper-headless.default.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, server.2=nautilus-pravega-zookeeper-1.nautilus-pravega-zookeeper-headless.default.svc.cluster.local:2888:3888:participant;0.0.0.0:2181}
2018-11-14 09:17:29,614 83780488 [ControllerServiceMain-EventThread] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background exception was not retry-able or retry gave up
java.lang.NullPointerException: null
        at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:179)
        at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:200)
        at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50)
        at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:144)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:852)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:629)
        at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152)
        at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:587)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:499)
2018-11-14 10:01:10,316 86401190 [pool-6-thread-1] INFO  i.p.c.s.stream.ZKGarbageCollector - Acquired guard, starting GC iteration for completedTxnG 
```

**Comment by deenav** [comment]
@adrianmo Yes, I encountered this error while scaling up ZK.  I will check and update whether the problem persists with the latest ZK operator or not.

**Comment by deenav** [comment]
Hi @adrianmo, We have encountered this NPE error again with latest pravega-operator: `adrianmo/pravega-operator:pr-145-2` and ZK-operator `spiegela/zookeeper-operator:latest` and Pravega image `zk-closed-client-issue-0.5.0-2162.0bbfa42`

Test steps followed:
1.	pravega-longevity running with small scale test
2.	restart the Pravega-zookeeper with “kubectl delete po/ pravega-zk-2” command

Controller log sinp:
```
2019-03-28 07:24:31,756 49592619 [grpc-default-executor-994] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getURI called for segment longevity/smallScale/2856153252867.
2019-03-28 07:24:33,442 49594305 [ControllerServiceMain-EventThread] INFO  o.a.c.f.imps.EnsembleTracker - New config event received: {server.1=pravega-zk-0.pravega-zk-headless.default.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, version=30000013b, server.3=pravega-zk-2.pravega-zk-headless.default.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, server.2=pravega-zk-1.pravega-zk-headless.default.svc.cluster.local:2888:3888:participant;0.0.0.0:2181}
2019-03-28 07:24:33,444 49594307 [ControllerServiceMain-EventThread] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background exception was not retry-able or retry gave up
java.lang.NullPointerException: null
        at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:179)
        at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:200)
        at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50)
        at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:144)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:865)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:635)
        at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152)
        at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:587)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:499)
```

**Comment by deenav** [comment]
@adrianmo This issue is reproducible even with latest pravega `pravega/pravega-operator:0.3.2` and Zk `pravega/zookeeper-operator:0.2.1` operators.

```
2019-03-28 15:43:50,850 1438821 [ControllerServiceMain-EventThread] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background exception was not retry-able or retry gave up
java.lang.NullPointerException: null
        at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:179)
        at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:200)
        at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50)
        at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:144)
```

**Comment by RaulGracia** [comment]
This should go to the https://github.com/pravega/zookeeper-operator repo.
