### ISSUE TITLE
listScopes returns 500 when auth is enabled

### ISSUE THREAD

**Issue by sarlaccpit** [pravega/pravega#3108]
**Problem description**

When auth is enabled on the controller and segment store, listScopes returns 500.  Create scope and get one scope behave normally.

This is using the built-in basic auth handler with password file.

```
Get scopes without credentials, 401 as expected

usxxcbalczunm1:pravega-auth cbalczun$ curl http://...:10080/v1/scopes -H "Content-Type: application/json" -i
HTTP/1.1 401 Unauthorized
Content-Length: 0

Now passing the right credentials:

usxxcbalczunm1:pravega-auth cbalczun$ curl http://...:10080/v1/scopes -H "Authorization: Basic YWRtaW46MTExMV9hYWFh" -H "Content-Type: application/json" -i
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Length: 0

Create a scope

usxxcbalczunm1:pravega-auth cbalczun$ curl http://...:10080/v1/scopes -H "Authorization: Basic YWRtaW46MTExMV9hYWFh" -H "Content-Type: application/json" -i -d "{ \"scopeName\": \"myscope\"}"
HTTP/1.1 201 Created
Content-Type: application/json
Content-Length: 23

{"scopeName":"myscope"}

Get one scope:

usxxcbalczunm1:pravega-auth cbalczun$ curl http://...:10080/v1/scopes/myscope -H "Authorization: Basic YWRtaW46MTExMV9hYWFh" -H "Content-Type: application/json" -i
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 23

{"scopeName":"myscope"}

But list all scopes:

usxxcbalczunm1:pravega-auth cbalczun$ curl http://...:10080/v1/scopes -H "Authorization: Basic YWRtaW46MTExMV9hYWFh" -H "Content-Type: application/json" -i
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Length: 0
```

When the 500 occurs, this can be observed in the controller logs:

```
2018-11-15 02:13:02,124 77882 [controllerpool-10] WARN  i.p.c.s.r.r.StreamMetadataResourceImpl - listScopes failed with exception:
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Not inside a request scope.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.pravega.controller.store.stream.ZKStoreHelper.lambda$getChildren$9(ZKStoreHelper.java:155)
	at io.pravega.controller.store.stream.ZKStoreHelper.lambda$callback$23(ZKStoreHelper.java:305)
	at org.apache.curator.framework.imps.Backgrounding$1$1.run(Backgrounding.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Not inside a request scope.
	at org.glassfish.jersey.internal.guava.Preconditions.checkState(Preconditions.java:169)
	at org.glassfish.jersey.process.internal.RequestScope.current(RequestScope.java:177)
	at org.glassfish.jersey.inject.hk2.RequestContext.findOrCreate(RequestContext.java:79)
	at org.jvnet.hk2.internal.MethodInterceptorImpl.internalInvoke(MethodInterceptorImpl.java:89)
	at org.jvnet.hk2.internal.MethodInterceptorImpl.invoke(MethodInterceptorImpl.java:125)
	at org.jvnet.hk2.internal.MethodInterceptorInvocationHandler.invoke(MethodInterceptorInvocationHandler.java:62)
	at com.sun.proxy.$Proxy56.getRequestHeader(Unknown Source)
	at io.pravega.controller.server.rest.resources.StreamMetadataResourceImpl.authorize(StreamMetadataResourceImpl.java:170)
	at io.pravega.controller.server.rest.resources.StreamMetadataResourceImpl.lambda$null$25(StreamMetadataResourceImpl.java:516)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at io.pravega.controller.server.rest.resources.StreamMetadataResourceImpl.lambda$listScopes$26(StreamMetadataResourceImpl.java:514)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 13 common frames omitted
```

**Problem location**

Controller rest api (I think).

**Suggestions for an improvement**

Return 200 with the list of authorized-to-see scopes.

**Comment by EronWright** [comment]
This might affect only the REST API, as opposed to the gRPC API.
