### ISSUE TITLE
Docker Swarm System Tests execution failures

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#3153]
**Problem description**
We are observing issues in the current Docker Swarm deployment for system tests (hardware cluster). Apparently, they may be related to deployment issues, which may call for additional checks from the framework on it deploys/shuts down instances. For instance, this is system test run executed:

```
CONTAINER ID  IMAGE     COMMAND  CREATED   STATUS    PORTS     NAMES
a6e6be36073d  java:8    "sh -c 'java -Dmas..." 18 hours ago  Exited (0) 18 hours ago     zkTest.testJob
d9bf57f48bcf  java:8    "sh -c 'java -Dmas..." 18 hours ago  Exited (0) 18 hours ago     testStreamsAndScopesManagement.testJob
e28f9b97f10b  java:8    "sh -c 'java -Dmas..." 18 hours ago  Exited (0) 18 hours ago     streamCutsTest.testJob
91301a3e8eb3  java:8    "sh -c 'java -Dmas..." 18 hours ago  Exited (0) 18 hours ago     retentionTest.testJob
bdee699a9ebf  java:8    "sh -c 'java -Dmas..." 18 hours ago  Exited (0) 18 hours ago     readerCheckpointTest.testJob
8910168d1976  java:8    "sh -c 'java -Dmas..." 18 hours ago  Exited (0) 18 hours ago     generateStreamCutsTest.testJob
614e9c635c49  java:8    "sh -c 'java -Dmas..." 18 hours ago  Exited (1) 18 hours ago     scaleTestsWithReader.testJob
a57e4183d5a6  java:8    "sh -c 'java -Dmas..." 18 hours ago  Exited (0) 18 hours ago     readTxnWriteScaleWithFailoverTest.testJob
c44b881ca36c  java:8    "sh -c 'java -Dmas..." 18 hours ago  Exited (0) 18 hours ago     readTxnWriteAutoScaleWithFailoverTest.testJob
118829f41c15  java:8    "sh -c 'java -Dmas..." 18 hours ago  Exited (0) 18 hours ago     simpleTest.testJob
612c704e90b8  java:8    "sh -c 'java -Dmas..." 18 hours ago  Exited (0) 18 hours ago     segmentStoreTest.testJob
ba9db2c617ec  java:8    "sh -c 'java -Dmas..." 18 hours ago  Exited (0) 18 hours ago     controllerTest.testJob
713aacf281fc  java:8    "sh -c 'java -Dmas..." 18 hours ago  Exited (0) 18 hours ago     offsetTruncationTest.testJob
244574f7f6ae  java:8    "sh -c 'java -Dmas..." 19 hours ago  Exited (0) 18 hours ago     testMultiSegmentStores.testJob
4eb70af0bf61  java:8    "sh -c 'java -Dmas..." 19 hours ago  Exited (0) 19 hours ago     multiReaderWriterWithFailOverTest.testJob
090bc2d98f9c  java:8    "sh -c 'java -Dmas..." 19 hours ago  Exited (0) 19 hours ago     multiReaderTxnWriterWithFailOverTest.testJob
624c177825d7  java:8    "sh -c 'java -Dmas..." 19 hours ago  Exited (0) 19 hours ago     restApiTests.testJob
aa001d6fc864  java:8    "sh -c 'java -Dmas..." 19 hours ago  Exited (0) 19 hours ago     failoverTest.testJob
0709ea0bb2ae  java:8    "sh -c 'java -Dmas..." 19 hours ago  Exited (0) 19 hours ago     byteClientTest.testJob
01dc7ceccdf6  java:8    "sh -c 'java -Dmas..." 19 hours ago  Exited (0) 19 hours ago     bkTest.testJob
7c921710eb41  java:8    "sh -c 'java -Dmas..." 19 hours ago  Exited (0) 19 hours ago     bookieFailoverTest.testJob
ea62132467b4  java:8    "sh -c 'java -Dmas..." 19 hours ago  Exited (0) 19 hours ago     batchClientSimpleTest.testJob
034a95ba7ec1  java:8    "sh -c 'java -Dmas..." 19 hours ago  Exited (0) 19 hours ago     scaleTests.testJob
```

While most of the tests passed, there are at least three problems:
1) `multiControllerTest` is the first test that has not been executed (it is not in the list). However, the `gadle` task started the test, as we observed a `multicontroller` service running:

``` 
ID  NAME MODE  REPLICAS  IMAGE
7vabqfdlaw0o  multicontroller  replicated  2/2 ***:***/***/pravega:0.5.0-2022.b7c3a5c
b7rojujk1tf6  controller replicated  3/3 ***:***/***/pravega:0.5.0-2022.b7c3a5c
hc39hw1n6een  bookkeeper replicated  3/3 ***:***/nautilus/bookkeeper:0.5.0-2022.b7c3a5c
ja6sokgkrs20  zookeeper  replicated  1/1 jplock/zookeeper:3.5.1-alpha
qs4qmtqsj8cv  hdfs replicated  1/1 dsrw/hdfs:2.7.3-1
vwwmqmrycruh  segmentstore replicated  3/3 ***:***/***/pravega:0.5.0-2022.b7c3a5c
```

Unfortunately, we observed that these instances were instantiated in nodes with `controller` instances already running:
```
CONTAINER ID  IMAGE  COMMAND  CREATED STATUS PORTS
 NAMES
076adcf1ad3b  ***:***/***/pravega@sha256:9d7702ee2b03c4814fb16af09a58f87e133cc2be1f3b19f9836cbae3c85765ac "/opt/pravega/scri..." 3 minutes ago Up 3 minutes (healthy) 10000/tcp, 0.0.0.0:9090-9091->9090-9091/tcp, 12345/tcp  controller.1.k7bqyo1wrzmk5r0uea9xk8nw9
85a85a52cfbc  ***:***/***/pravega@sha256:9d7702ee2b03c4814fb16af09a58f87e133cc2be1f3b19f9836cbae3c85765ac "/opt/pravega/scri..." 4 minutes ago Up 4 minutes (healthy) 9090-9091/tcp, 10000/tcp, 12345/tcp, 0.0.0.0:9093-9094->9093-9094/tcp multicontroller.1.azgu071mpgss9s31075kc5ymw
```

This collision may explain why the `multicontroller` test was not even executed:

2) The previous situation may leave the Swarm in a bad state that may explain that the execution of other tests is missing as well: `ReadWriteAndAutoScaleWithFailoverTest` and `ReadWriteAndScaleWithFailoverTest`

```
io.pravega.test.system.ReadWriteAndAutoScaleWithFailoverTest.readWriteAndAutoScaleWithFailoverTest() throws java.lang.Exception
    2018-11-27 05:44:06,878 2434760 [ForkJoinPool.commonPool-worker-44] ERROR i.p.t.s.f.DockerBasedTestExecutor - Exception in starting container 
    com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST http://***:***/images/create?fromImage=java&tag=8: 500, body: {"message":"Get https://registry-1.docker.io/v2/library/java/manifests/8: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fjava%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io on ***:***: server misbehaving"}
...
io.pravega.test.system.ReadWriteAndAutoScaleWithFailoverTest > readWriteAndAutoScaleWithFailoverTest FAILED
    java.util.concurrent.ExecutionException: java.lang.AssertionError: Unable to start the container to invoke the test.Test failure

        Caused by:
        java.lang.AssertionError: Unable to start the container to invoke the test.Test failure
```

3) `scaleTestsWithReader` failed during its execution due to similar reasons:
```
io.pravega.test.system.ReadWithAutoScaleTest > scaleTestsWithReader STANDARD_OUT
    2018-11-27 05:44:06,366 2434248 [Test worker] DEBUG c.s.d.client.DockerConfigReader - Using configfile: /root/.dockercfg 
    2018-11-27 05:44:06,377 2434259 [Test worker] DEBUG i.p.t.s.f.DockerBasedTestExecutor - Starting test execution for method: public void io.pravega.test.system.ReadWithAutoScaleTest.scaleTestsWithReader()
    2018-11-27 05:44:06,531 2434413 [ForkJoinPool.commonPool-worker-44] ERROR i.p.t.s.f.DockerBasedTestExecutor - Exception in starting container 
    com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST http://10.246.154.201:2375/images/create?fromImage=java&tag=8: 500, body: {"message":"Get https://registry-1.docker.io/v2/library/java/manifests/8: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fjava%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io on ***:***: server misbehaving"}
at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2691)
        at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2630)
        at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1247)
        at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1224)
        at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1218)
        at io.pravega.test.system.framework.DockerBasedTestExecutor.lambda$startTest$10(DockerBasedTestExecutor.java:127)
        at io.pravega.common.Exceptions.handleInterrupted(Exceptions.java:90)
        at io.pravega.test.system.framework.DockerBasedTestExecutor.startTest(DockerBasedTestExecutor.java:127)
        at io.pravega.test.system.framework.DockerBasedTestExecutor.lambda$startTestExecution$1(DockerBasedTestExecutor.java:75)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
    Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
...
io.pravega.test.system.ReadWithAutoScaleTest > scaleTestsWithReader FAILED
    java.util.concurrent.ExecutionException: java.lang.AssertionError: Unable to start the container to invoke the test.Test failure

        Caused by:
        java.lang.AssertionError: Unable to start the container to invoke the test.Test failure
```

**Problem location**
Docker Swarm system tests.

**Suggestions for an improvement**
Maybe implementing validation checks/recovery tasks would avoid tests to fail due deployment issues unrelated with the code.

**Comment by RaulGracia** [comment]
Docker Swarm runs in current `r0.4` are more stable now, specially after re-creating the swarm and cherry picking #3336 and #3335. Any further system test failure in this environment will be reported separately.
