### ISSUE TITLE
Test failure TimeoutServiceTest 

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#3159]
**Problem description**
```
io.pravega.controller.timeout.TimeoutServiceTest > testControllerTimeout FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.pravega.controller.timeout.TimeoutServiceTest.testControllerTimeout(TimeoutServiceTest.java:176)
```
Observed this failure during travis build.
**Problem location**
TimeoutServiceTest

**Suggestions for an improvement**
fix the issue

**Comment by tkaitchuck** [comment]
I saw a potentially related error: 
```
java.lang.AssertionError: expected:<MAX_EXECUTION_TIME_EXCEEDED> but was:<OK>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.pravega.controller.timeout.TimeoutServiceTest.testControllerPingFailureMaxExecutionTimeExceeded(TimeoutServiceTest.java:395)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by shiveshr** [comment]
Closing the issue as we have not observed this in a while
