### ISSUE TITLE
ControllerMetricsTest.streamMetricsTest failure

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#3160]
**Problem description**
The test case failed with the following stack trace:

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at io.pravega.test.integration.ControllerMetricsTest.streamMetricsTest(ControllerMetricsTest.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

See logs here:
[streamMetricsTest.txt](https://github.com/pravega/pravega/files/2639555/streamMetricsTest.txt)

**Problem location**
Metrics unit tests.

**Suggestions for an improvement**
Investigate and fix the bug.

**Comment by RaulGracia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New Pravega Metrics are being reported as Histograms](https://trello.com/c/OEk8u3Vu/33-new-pravega-metrics-are-being-reported-as-histograms)

**Comment by RaulGracia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New Pravega Metrics are being reported as Histograms](https://trello.com/c/OEk8u3Vu/33-new-pravega-metrics-are-being-reported-as-histograms)
