### ISSUE TITLE
Log spam when performing conditional appends

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#3164]
**Problem description**
When a conditional attribute update fails it logs at ERROR level. Example:
```
ERROR i.p.s.s.h.h.PravegaRequestProcessor - [requestId=1075] Error (Segment = 'longevity/_RGlongevitysmallScaleforgetful0/0.#epoch.0', Operation = 'updateSegmentAttribute')
io.pravega.segmentstore.contracts.BadAttributeUpdateException: [Segment 'longevity/_RGlongevitysmallScaleforgetful0/0.#epoch.0'] Bad Attribute Update (AttributeId = 7df9a874-246c-c9d6-9397-cdd19ead68c5, Value = 1054480, UpdateType = ReplaceIfEquals): Expected existing value to be '-9223372036854775808', actual '557151'..
        at io.pravega.segmentstore.server.logs.SegmentMetadataUpdateTransaction.preProcessAttributes(SegmentMetadataUpdateTransaction.java:429)
        at io.pravega.segmentstore.server.logs.SegmentMetadataUpdateTransaction.preProcessOperation(SegmentMetadataUpdateTransaction.java:274)
        at io.pravega.segmentstore.server.logs.ContainerMetadataUpdateTransaction.preProcessOperation(ContainerMetadataUpdateTransaction.java:321)
        at io.pravega.segmentstore.server.logs.OperationMetadataUpdater.preProcessOperation(OperationMetadataUpdater.java:224)
        at io.pravega.segmentstore.server.logs.OperationProcessor.processOperation(OperationProcessor.java:364)
        at io.pravega.segmentstore.server.logs.OperationProcessor.processOperations(OperationProcessor.java:283)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Problem location**
SegmentStore

**Suggestions for an improvement**
Log at debug without the stack trace.

**Comment by andreipaduroiu** [comment]
This looks related to #2686
