### ISSUE TITLE
testSegmentNotifications failure

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#3166]
**Problem description**
Test case failed on travis with a timeout:

```
io.pravega.test.integration.ReaderGroupNotificationTest > testSegmentNotifications FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 40000 milliseconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at io.pravega.test.integration.ReaderGroupNotificationTest.testSegmentNotifications(ReaderGroupNotificationTest.java:176)
```

**Problem location**
Controller, tests.

**Suggestions for an improvement**
Try to repro the test failure and debug.

**Comment by shrids** [comment]
Tried to simulate this test failure locally on different environments. Was not able to simulate a failure even after multiple hours of run. Closing this issue for now.
