### ISSUE TITLE
Encounter OOM when running search longevity test, after restarted bookie in k8s the other services still using the old endpoint

### ISSUE THREAD

**Issue by jingjinglll** [pravega/pravega#3193]
**Problem description**
When running psearch longevity test in PKS environment for 3 hours, I run into the issues: 
1. Pravega is not reachable due to WrongHost from controller log.
2. Checked segmentstore logs and found many BKNotEnoughBookiesException.
3. Checked bookie logs and found bookie-0 encountered OutOfMemory and didn't restart automatically.
4. So I restarted the bookie-0, from the bookie-1 logs I saw the bookie-1 still connects to the old ip address.

I was using branch r0.4.

**Problem location**
wrong host from controller log:
```
2018-12-11 07:19:31,827 903994 [epollEventLoopGroup-4-2] WARN  i.p.c.s.i.SegmentOutputStreamImpl - Connection for segment _system/_requeststream/0.#epoch.0 on writer 12a42037-c6ef-4c97-81cb-32ce8443d171 failed due to: WireCommands.WrongHost(type=WRONG_HOST, requestId=50, segment=_system/_requeststream/0.#epoch.0, correctHost=, serverStackTrace=)
2018-12-11 07:19:31,827 903994 [epollEventLoopGroup-4-2] WARN  i.p.c.s.i.SegmentOutputStreamImpl - 12a42037-c6ef-4c97-81cb-32ce8443d171 Failed to connect: 
java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=50, segment=_system/_requeststream/0.#epoch.0, correctHost=, serverStackTrace=)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:874)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl$State.failConnection(SegmentOutputStreamImpl.java:202)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl$State.access$700(SegmentOutputStreamImpl.java:94)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl.failConnection(SegmentOutputStreamImpl.java:514)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl.access$500(SegmentOutputStreamImpl.java:70)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl$ResponseProcessor.wrongHost(SegmentOutputStreamImpl.java:291)
	at io.pravega.shared.protocol.netty.WireCommands$WrongHost.process(WireCommands.java:118)
	at io.pravega.shared.protocol.netty.ReplyProcessor.process(ReplyProcessor.java:20)
	at io.pravega.client.netty.impl.ClientConnectionInboundHandler.channelRead(ClientConnectionInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:797)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=50, segment=_system/_requeststream/0.#epoch.0, correctHost=, serverStackTrace=)
```

Not enough bookie from segment store:
```
2018-12-11 07:19:41,601 913768 [core-1] INFO  i.p.s.s.impl.bookkeeper.Ledgers - Log[0]: Fenced out Ledger Id = 74, Sequence = 8, Status = Unknown.
2018-12-11 07:19:41,602 913769 [core-1] INFO  i.p.s.s.impl.bookkeeper.Ledgers - Log[0]: Fenced out Ledger Id = 50, Sequence = 7, Status = Unknown.
2018-12-11 07:19:41,602 913769 [core-1] ERROR o.a.b.client.LedgerCreateOp - Not enough bookies to create ledger
2018-12-11 07:19:41,602 913769 [core-1] ERROR i.p.s.server.logs.DurableLog - DurableLog[0] Recovery FAILED.
io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to create new BookKeeper Ledger.
    at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.create(Ledgers.java:55)
    at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.initialize(BookKeeperLog.java:230)
    at io.pravega.segmentstore.server.logs.DurableLog.performRecovery(DurableLog.java:213)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: null
    at org.apache.bookkeeper.client.SynchCallbackUtils.finish(SynchCallbackUtils.java:63)
    at org.apache.bookkeeper.client.BookKeeper$SyncCreateCallback.createComplete(BookKeeper.java:1336)
    at org.apache.bookkeeper.client.LedgerCreateOp.createComplete(LedgerCreateOp.java:200)
    at org.apache.bookkeeper.client.LedgerCreateOp.initiate(LedgerCreateOp.java:115)
    at org.apache.bookkeeper.client.BookKeeper.asyncCreateLedger(BookKeeper.java:710)
    at org.apache.bookkeeper.client.BookKeeper.createLedger(BookKeeper.java:795)
    at org.apache.bookkeeper.client.BookKeeper.createLedger(BookKeeper.java:769)
    at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.lambda$create$0(Ledgers.java:48)
    at io.pravega.common.Exceptions.handleInterrupted(Exceptions.java:113)
    at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.create(Ledgers.java:47)
    ... 10 common frames omitted
2018-12-11 07:19:41,604 913771 [core-25] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Stopping.
2018-12-11 07:19:41,604 913771 [core-19] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[0]: Closed.
```

oom from bookie:
```
2018-12-10 11:44:34,941 - ERROR - [main-EventThread:ClientCnxn$EventThread@526] - Error while calling watcher 
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at io.netty.util.concurrent.ThreadPerTaskExecutor.execute(ThreadPerTaskExecutor.java:33)
	at io.netty.util.concurrent.SingleThreadEventExecutor.doStartThread(SingleThreadEventExecutor.java:847)
	at io.netty.util.concurrent.SingleThreadEventExecutor.shutdownGracefully(SingleThreadEventExecutor.java:585)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.shutdownGracefully(MultithreadEventExecutorGroup.java:163)
	at io.netty.util.concurrent.AbstractEventExecutorGroup.shutdownGracefully(AbstractEventExecutorGroup.java:70)
	at org.apache.bookkeeper.client.BookKeeper.close(BookKeeper.java:1315)
	at org.apache.bookkeeper.replication.Auditor.shutdown(Auditor.java:731)
	at org.apache.bookkeeper.replication.AuditorElector.shutdown(AuditorElector.java:350)
	at org.apache.bookkeeper.replication.AutoRecoveryMain.shutdown(AutoRecoveryMain.java:161)
	at org.apache.bookkeeper.replication.AutoRecoveryMain.access$100(AutoRecoveryMain.java:59)
	at org.apache.bookkeeper.replication.AutoRecoveryMain$1.process(AutoRecoveryMain.java:94)
	at org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase.notifyEvent(ZooKeeperWatcherBase.java:180)
	at org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase.process(ZooKeeperWatcherBase.java:146)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:524)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:499)
2018-12-10 11:44:34,969 - WARN  - [main-EventThread:BookieWatcher@177] - Failed to schedule reading bookies task : 
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@36c68b3f rejected from java.util.concurrent.ScheduledThreadPoolExecutor@705d3702[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:729)
	at org.apache.bookkeeper.client.BookieWatcher.processResult(BookieWatcher.java:175)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$31$1.processResult(ZooKeeperClient.java:1349)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:610)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:499)
2018-12-10 11:44:34,979 - ERROR - [main-EventThread:BookieWatcher$ReadOnlyBookieWatcher@417] - Not able to read readonly bookies : 
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:131)
	at org.apache.bookkeeper.client.BookieWatcher$ReadOnlyBookieWatcher.processResult(BookieWatcher.java:417)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$31$1.processResult(ZooKeeperClient.java:1349)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:610)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:499)
```

Connect to old host after restart bookie:
```
2018-12-11 08:03:43,411 - ERROR - [bookkeeper-io-1:PerChannelBookieClient$ConnectionFutureListener@2095] - Could not connect to bookie: [id: 0x2ee8241a, L:/10.200.69.108:41292]/pravega-bookie-0.pravega-bookie-headless.default.svc.cluster.local:3181, current state CONNECTING : 
io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Host is unreachable: pravega-bookie-0.pravega-bookie-headless.default.svc.cluster.local/10.200.68.98:3181
    at io.netty.channel.unix.Errors.throwConnectException(Errors.java:107)
    at io.netty.channel.unix.Socket.finishConnect(Socket.java:255)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.doFinishConnect(AbstractEpollStreamChannel.java:917)
    at io.netty.channel.epoll.EpollSocketChannel$EpollSocketChannelUnsafe.doFinishConnect(EpollSocketChannel.java:222)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.finishConnect(AbstractEpollStreamChannel.java:884)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollOutReady(AbstractEpollStreamChannel.java:907)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:391)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: finishConnect(..) failed: Host is unreachable
    ... 10 more`
```

**Suggestions for an improvement**
1. Fix the oom issue
2. Bookie should be terminated and rebooted by k8s if encountered oom issue
3. Delete a bookie in k8s and let k8s to start a new container, other service should use the new endpoint.

**Comment by adrianmo** [comment]
@jingjinglll can you check if the problem still persists after the changes made in https://github.com/pravega/pravega-operator/commit/3c7ea47306f64c194564975d6c41522c8d7cbd7d ? 

Thank you.

**Comment by RaulGracia** [comment]
@jingjinglll please, if it does persist, please collect all the logs (including ZK/BK ones), so we can understand the root cause of the problem.
