### ISSUE TITLE
`[Curator-ConnectionStateManager-0] ERROR- Could not inject session expiration` Exception on Controller due to ZK session expiry

### ISSUE THREAD

**Issue by deenav** [pravega/pravega#3202]
**Problem description**

After ~21 hrs of longevity run with moderate IO workload on `master - 0.5.0-2050.68e7bf0` branch, started observing errors related to zookeeper session expiry in Controller logs.

**Controller log snips**
```
2018-12-11 18:17:32,896 89525847 [Curator-ConnectionStateManager-0] ERROR o.a.c.f.s.ConnectionStateManager - Could not inject session expiration
java.lang.IllegalArgumentException: connectString differs
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at io.pravega.controller.store.client.StoreClientFactory$ZKClientFactory.newZooKeeper(StoreClientFactory.java:118)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl$2.newZooKeeper(CuratorFrameworkImpl.java:191)
        at org.apache.curator.HandleHolder$1.getZooKeeper(HandleHolder.java:101)
        at org.apache.curator.HandleHolder.getZooKeeper(HandleHolder.java:57)
        at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:99)
        at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:141)
        at org.apache.curator.framework.state.ConnectionStateManager.checkSessionExpiration(ConnectionStateManager.java:310)
        at org.apache.curator.framework.state.ConnectionStateManager.processEvents(ConnectionStateManager.java:284)
        at org.apache.curator.framework.state.ConnectionStateManager.access$000(ConnectionStateManager.java:44)
        at org.apache.curator.framework.state.ConnectionStateManager$1.call(ConnectionStateManager.java:120)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
```
2018-12-11 18:17:54,661 89547612 [Curator-LeaderSelector-0] ERROR o.a.c.f.r.leader.LeaderSelector - The leader threw an exception
java.lang.IllegalStateException: instance must be started before calling this method
        at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.delete(CuratorFrameworkImpl.java:418)
        at org.apache.curator.framework.recipes.locks.LockInternals.deleteOurPath(LockInternals.java:340)
        at org.apache.curator.framework.recipes.locks.LockInternals.releaseLock(LockInternals.java:124)
        at org.apache.curator.framework.recipes.locks.InterProcessMutex.release(InterProcessMutex.java:154)
        at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:449)
        at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:466)
        at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:65)
        at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:246)
        at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:240)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by deenav** [comment]
Please find the Pravega cluster logs attached
[pravega-k8s-logging-2018-12-12-04-41-10.zip](https://github.com/pravega/pravega/files/2672808/pravega-k8s-logging-2018-12-12-04-41-10.zip)
