### ISSUE TITLE
Pravega fails to start up in standalone mode when TLS is enabled

### ISSUE THREAD

**Issue by ravisharda** [pravega/pravega#3228]
**Problem description**

1) Enable SSL/TLS in standalone-config.properties:
```
singlenode.certFile=../config/cert.pem
singlenode.keyFile=../config/key.pem
singlenode.enableTls=true
```
2) Start Pravega in standalone mode:
```
./gradlew startStandalone
```
The Gradle build task fails with the following messages: 

```
> Task :standalone:startStandalone FAILED
...
2018-12-27 00:56:01,668 914  [main] ERROR i.p.local.LocalPravegaEmulator - Exception occurred running emulator
java.lang.NullPointerException: null
        at java.util.Hashtable.put(Hashtable.java:460)
        at java.util.Properties.setProperty(Properties.java:166)
        at java.lang.System.setProperty(System.java:796)
        at io.pravega.segmentstore.storage.impl.bookkeeper.ZooKeeperServiceRunner.initialize(ZooKeeperServiceRunner.java:94)
        at io.pravega.local.InProcPravegaCluster.startLocalZK(InProcPravegaCluster.java:204)
        at io.pravega.local.InProcPravegaCluster.start(InProcPravegaCluster.java:177)
        at io.pravega.local.LocalPravegaEmulator.start(LocalPravegaEmulator.java:142)
        at io.pravega.local.LocalPravegaEmulator.main(LocalPravegaEmulator.java:118)
2018-12-27 00:56:01,675 921  [Thread-1] WARN  i.p.local.LocalPravegaEmulator - Exception running local Pravega emulator: null

FAILURE: Build failed with an exception.
```

**Problem location**
LocalPravegaEmulator.java, SingleNodeConfig.java, standalone-config.properties

**Suggestions for an improvement**
The "startStandalone" Gradle task runs the LocalPravegaEmulator class, the properties of which are loaded from the config/standalone-config.properties file. Some of the LocalPravegaEmulator's properties that are necessary for bootstrapping it are not being set. Fix that.

**Comment by ravisharda** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [3228 - TLS-enabled standalone mode startup](https://trello.com/c/Q7EqPf0V/8-3228-tls-enabled-standalone-mode-startup)
