### ISSUE TITLE
nfs provisioner restarted causes pravega failed and can't recover

### ISSUE THREAD

**Issue by jingjinglll** [pravega/pravega#3236]
**Problem description**
We started search longevity test in gke environment, nfs-server-provisioner may be restarted after a few hours. If that happends, all workloads failed and can't be recovered.
```
2018-12-30 01:54:06,127 86575179 [storage-io-14] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[2]: Iteration[4981].Error.
java.nio.file.FileSystemException: /mnt/tier2/psearchTranslogScope/psearch-51604de9-c848-41d8-a6aa-15c5640cabd1-request/0.#epoch.0$header: Stale file handle
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:218)
	at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:131)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at io.pravega.storage.filesystem.FileSystemStorage.doGetStreamSegmentInfo(FileSystemStorage.java:260)
	at io.pravega.storage.filesystem.FileSystemStorage.lambda$getStreamSegmentInfo$2(FileSystemStorage.java:135)
	at io.pravega.storage.filesystem.FileSystemStorage.execute(FileSystemStorage.java:404)
	at io.pravega.storage.filesystem.FileSystemStorage.getStreamSegmentInfo(FileSystemStorage.java:135)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.getHeaderInfo(RollingStorage.java:680)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.openHandle(RollingStorage.java:641)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.openWrite(RollingStorage.java:289)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$openWrite$0(AsyncStorageWrapper.java:83)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-12-30 01:54:07,129 86576181 [storage-io-8] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[2-253]: State changed from NotInitialized to Closed.
2018-12-30 01:54:07,129 86576181 [storage-io-8] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[2]: Iteration[4982].Error.
java.nio.file.FileSystemException: /mnt/tier2/psearchTranslogScope/psearch-51604de9-c848-41d8-a6aa-15c5640cabd1-request/0.#epoch.0$header: Stale file handle
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:218)
	at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:131)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at io.pravega.storage.filesystem.FileSystemStorage.doGetStreamSegmentInfo(FileSystemStorage.java:260)
	at io.pravega.storage.filesystem.FileSystemStorage.lambda$getStreamSegmentInfo$2(FileSystemStorage.java:135)
	at io.pravega.storage.filesystem.FileSystemStorage.execute(FileSystemStorage.java:404)
	at io.pravega.storage.filesystem.FileSystemStorage.getStreamSegmentInfo(FileSystemStorage.java:135)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.getHeaderInfo(RollingStorage.java:680)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.openHandle(RollingStorage.java:641)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.openWrite(RollingStorage.java:289)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$openWrite$0(AsyncStorageWrapper.java:83)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-12-30 01:54:08,131 86577183 [storage-io-15] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[2-253]: State changed from NotInitialized to Closed.
2018-12-30 01:54:08,131 86577183 [storage-io-15] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[2]: Iteration[4983].Error.
java.nio.file.FileSystemException: /mnt/tier2/psearchTranslogScope/psearch-51604de9-c848-41d8-a6aa-15c5640cabd1-request/0.#epoch.0$header: Stale file handle
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:218)
	at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:131)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at io.pravega.storage.filesystem.FileSystemStorage.doGetStreamSegmentInfo(FileSystemStorage.java:260)
	at io.pravega.storage.filesystem.FileSystemStorage.lambda$getStreamSegmentInfo$2(FileSystemStorage.java:135)
	at io.pravega.storage.filesystem.FileSystemStorage.execute(FileSystemStorage.java:404)
	at io.pravega.storage.filesystem.FileSystemStorage.getStreamSegmentInfo(FileSystemStorage.java:135)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.getHeaderInfo(RollingStorage.java:680)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.openHandle(RollingStorage.java:641)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.openWrite(RollingStorage.java:289)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$openWrite$0(AsyncStorageWrapper.java:83)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-12-30 01:54:08,507 86577559 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xf7714ef6, L:/10.8.7.49:12345] READ: [id: 0x3072f71c, L:/10.8.7.49:12345 - R:/10.8.0.81:49514]
2018-12-30 01:54:08,507 86577559 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xf7714ef6, L:/10.8.7.49:12345] READ COMPLETE
2018-12-30 01:54:08,508 86577560 [epollEventLoopGroup-3-1] INFO  i.p.s.s.h.handler.AppendProcessor - Received hello from connection: [id: 0x3072f71c, L:/10.8.7.49:12345 - R:/10.8.0.81:49514]
2018-12-30 01:54:08,508 86577560 [epollEventLoopGroup-3-1] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: 72afe045-579a-4563-870b-9bec9551727d on segment: psearchClusterMapScope/workloadSharedMapStream/0.#epoch.0
2018-12-30 01:54:08,509 86577561 [storage-io-18] ERROR i.p.s.s.h.handler.AppendProcessor - Error (Segment = 'psearchClusterMapScope/workloadSharedMapStream/0.#epoch.0', Operation = 'append')
java.nio.file.FileSystemException: /mnt/tier2/psearchClusterMapScope/workloadSharedMapStream/0.#epoch.0$attributes.index$header: Stale file handle
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:218)
	at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:131)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at io.pravega.storage.filesystem.FileSystemStorage.doGetStreamSegmentInfo(FileSystemStorage.java:260)
	at io.pravega.storage.filesystem.FileSystemStorage.lambda$getStreamSegmentInfo$2(FileSystemStorage.java:135)
	at io.pravega.storage.filesystem.FileSystemStorage.execute(FileSystemStorage.java:404)
	at io.pravega.storage.filesystem.FileSystemStorage.getStreamSegmentInfo(FileSystemStorage.java:135)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.getHeaderInfo(RollingStorage.java:680)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.openHandle(RollingStorage.java:641)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.openWrite(RollingStorage.java:289)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$openWrite$0(AsyncStorageWrapper.java:83)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
**Problem location**

**Suggestions for an improvement**
Pravega should be working even NFS provisioner is restarted.

**Comment by jingjinglll** [comment]
I built the images from master branch on Dec 12.

**Comment by sachin-j-joshi** [comment]
@jingjinglll @hyffrank 
I have some basic questions and probably need some additional info for us to determine whether this is result of either (a) segment store not able to handle transient failures or (b) the remounting of the nfs after restart not really working as expected.

The stack trace indicates that the segment store is throwing exceptions while trying to write the file to the Tier 2 storage during append operations. 

Recall that Pravega is designed so that any user writes are acknowledged only when written synchronously to Tier 1. However, data to Tier 2 is always written asynchronously (batching data and with lots of retries to handle any transient errors ).

Based on the scenario you are describing above, the nfs-server-provisioner is restarted which should make nfs mount inaccessible and unreachable during the restart. As expected the segment store finds nfs mount missing and **reports the errors in log and keeps on retrying**.  

> java.nio.file.FileSystemException:

>  /mnt/tier2/psearchTranslogScope/psearch-51604de9-c848-41d8-a6aa-15c5640cabd1-request/0.#epoch.0$header: **Stale file handle**
> 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
> 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)

Segment store is going to retry multiple times until it succeeds. ( I believe indefinitely as of today)

Now, I would say the logs actually look "normal" - in a sense that we did encounter the error and report the error and retried - as expected and as designed.

What certainly does not seem to be normal is that your experience that "all workloads failed and can't be recovered".

1. One possibility is that the nfs-server-provisioner actually did not recover properly and did not correctly mount the nfs back in k8 container. Therefore segment store could not check the attributes on the given nfs path. It doesn't exist, the inode for mount is stale and possibly recycled. This is what logs seem to indicate.
In this case the issue isn't the segment code, and we need to investigate root cause for restart of nfs-server-provisioner.

2. The other possibility is that nfs mount recovers but the pravega segment store is caching file handles somewhere. This does not seem to be case here . We are simply calling _java.nio.file.Files.readAttributes(Path p,..)_ passing the string path. So really I don't think it is segment store that is failing to recover.

Question - 

- Is there a way for us to validate/verify that the nfs mount actually recovers successfully after restart and 
 nfs mounts exists and accessible after restart? 
- The logs above are generated during "append" operation.  For lack of better words they are looking "as expected". But is your workload seeing any other segment create/delete failures in the log ?

**Comment by sachin-j-joshi** [comment]
@jingjinglll @hyffrank 
To further clarify - 
Pravega absolutely needs persistent storage to be available _eventually_ and the guarantee that data is actually stored persistently for long term. If nfs is available/accessible after restart but the data itself is gone then that is a critical and permanent failure that pravega can not recover from.

In other words, Pravega MUST be able handle any _transient_ connectivity issues and recover from it gracefully. However, if the persistent storage itself does not recover or is  unavailable or otherwise _permanently fails_ then Pravega can not recover. 

I think in this case the nfs server does not recover fully after restart and that the data persisted previously is completely wiped out after the restart. If 

According to documentation for [NFS Server Provisioner ](https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner) it is an alpha level feature and more specifically **not intended for connecting to pre-existing NFS server**

Moreover the documentation specifically warns 
> **Warning**: While installing in the default configuration will work, any data stored on
the dynamic volumes provisioned by this chart will not be persistent!

I would like us to investigate further and answer following questions
- Is nfs storage mounted back after restart?
- Is data written before restart actually persisted and not wiped clean after restart.

Would you be able to repro the problem again and provide logs for pravega before, during and after the restart?

**Comment by jingjinglll** [comment]
Seems the nfs storage wasn't mounted back.
Is there a workaround?

Filesystem           1K-blocks      Used Available Use% Mounted on
overlay               98868448   4181948  94670116   4% /
tmpfs                  1893800         0   1893800   0% /dev
tmpfs                  1893800         0   1893800   0% /sys/fs/cgroup
/dev/sda1             98868448   4181948  94670116   4% /dev/termination-log
df: /mnt/tier2: Stale file handle
/dev/sda1             98868448   4181948  94670116   4% /etc/resolv.conf
/dev/sda1             98868448   4181948  94670116   4% /etc/hostname
/dev/sda1             98868448   4181948  94670116   4% /etc/hosts
shm                      65536         0     65536   0% /dev/shm
/dev/sdb              82045336     57560  77777088   0% /tmp/pravega/cache
tmpfs                  1893800        12   1893788   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                  1893800         0   1893800   0% /proc/kcore
tmpfs                  1893800         0   1893800   0% /proc/timer_list
tmpfs                  1893800         0   1893800   0% /sys/firmware
