### ISSUE TITLE
Sporadic unit test failure: ContainerKeyIndexTests.testRecovery

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#3247]
**Problem description**
`ContainerKeyIndexTests.testRecovery` fails occasionally due to the unpredictable nature of callback execution order of `CompletableFuture.thenCompose`.

**Problem location**
`ContainerKeyIndexTests`.

**Suggestions for an improvement**
Fix unit test.

**Comment by shiveshr** [comment]
Reopening issue because encountered failure on travis:
```
io.pravega.segmentstore.server.tables.ContainerKeyIndexTests > testRecovery FAILED

    java.lang.AssertionError: Expected getBucketOffsets() to block.

        at org.junit.Assert.fail(Assert.java:88)

        at org.junit.Assert.assertTrue(Assert.java:41)

        at org.junit.Assert.assertFalse(Assert.java:64)

        at io.pravega.segmentstore.server.tables.ContainerKeyIndexTests.testRecovery(ContainerKeyIndexTests.java:469)
```
