### ISSUE TITLE
ZK and controller keep restarting

### ISSUE THREAD

**Issue by jingjinglll** [pravega/pravega#3261]
**Problem description**
Running search longevity test for 6 hours on gke, one of the two zookeeper crashed, and then zk instance and Pravega controller keep restarting.
```
NAME                                          READY   STATUS             RESTARTS   AGE
controller-0                                  1/1     Running            1          6h
controller-1                                  1/1     Running            1          6h
indexworker-0                                 1/1     Running            0          6h
jmeter-rcpg2                                  1/1     Running            0          6h
pravega-bookie-0                              1/1     Running            0          6h
pravega-bookie-1                              1/1     Running            0          6h
pravega-bookie-2                              1/1     Running            0          2h
pravega-operator-674bd86d4f-kdlb9             1/1     Running            0          6h
pravega-pravega-controller-5ffb586bdf-tzxqv   0/1     Running            40         6h
pravega-pravega-controller-5ffb586bdf-whhc2   0/1     Running            40         6h
pravega-pravega-segmentstore-0                1/1     Running            0          6h
pravega-pravega-segmentstore-1                1/1     Running            0          6h
pravega-pravega-segmentstore-2                1/1     Running            0          6h
psearch-operator-869566c7c8-624sd             1/1     Running            0          6h
queryworker-0                                 1/1     Running            0          6h
resthead-0                                    1/1     Running            0          6h
shardworker-0                                 1/1     Running            2          6h
zk-0                                          0/1     CrashLoopBackOff   55         2h
zk-1                                          1/1     Running            0          6h
zookeeper-operator-5d4647886b-m9s45           1/1     Running            2          6h

```
controller log:
```
2019-01-09 08:00:32,564 18568 [ControllerServiceMain-SendThread(zk-client:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /10.8.7.5:43234, server: zk-client/10.11.255.85:2181
2019-01-09 08:00:32,566 18570 [ControllerServiceMain-SendThread(zk-client:2181)] INFO  org.apache.zookeeper.ClientCnxn - Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect
2019-01-09 08:00:32,584 18588 [Curator-Framework-0] WARN  o.a.c.retry.ExponentialBackoffRetry - Sleep extension too large (15000). Pinning to 1000
2019-01-09 08:00:33,586 19590 [Curator-Framework-0] WARN  o.a.c.retry.ExponentialBackoffRetry - Sleep extension too large (70000). Pinning to 1000
2019-01-09 08:00:34,484 20488 [ControllerServiceMain-SendThread(zk-client:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server zk-client/10.11.255.85:2181. Will not attempt to authenticate using SASL (unknown error)
2019-01-09 08:00:34,485 20489 [ControllerServiceMain-SendThread(zk-client:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /10.8.7.5:43240, server: zk-client/10.11.255.85:2181
2019-01-09 08:00:34,486 20490 [ControllerServiceMain-SendThread(zk-client:2181)] INFO  org.apache.zookeeper.ClientCnxn - Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect
2019-01-09 08:00:34,587 20591 [Curator-Framework-0] WARN  o.a.c.retry.ExponentialBackoffRetry - Sleep extension too large (100000). Pinning to 1000
2019-01-09 08:00:35,589 21593 [Curator-Framework-0] INFO  o.a.c.f.s.ConnectionStateManager - State change: SUSPENDED
2019-01-09 08:00:35,594 21598 [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background operation retry gave up
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:831)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:960)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:912)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:70)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:316)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-01-09 08:00:35,598 21602 [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background retry gave up
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:941)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:912)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:70)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:316)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-01-09 08:00:36,110 22114 [ControllerServiceMain-SendThread(zk-client:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server zk-client/10.11.255.85:2181. Will not attempt to authenticate using SASL (unknown error)
2019-01-09 08:00:36,111 22115 [ControllerServiceMain-SendThread(zk-client:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /10.8.7.5:43248, server: zk-client/10.11.255.85:2181
2019-01-09 08:00:36,112 22116 [ControllerServiceMain-SendThread(zk-client:2181)] INFO  org.apache.zookeeper.ClientCnxn - Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect
```
zk log:
```
+ source /conf/env.sh
++ DOMAIN=zk-headless.default.svc.cluster.local
++ QUORUM_PORT=2888
++ LEADER_PORT=3888
++ CLIENT_PORT=2181
+ source /usr/local/bin/zookeeperFunctions.sh
++ set -ex
++ hostname -s
+ HOST=zk-0
+ DATA_DIR=/data
+ MYID_FILE=/data/myid
+ LOG4J_CONF=/conf/log4j-quiet.properties
+ DYNCONFIG=/data/zoo.cfg.dynamic
+ [[ zk-0 =~ (.*)-([0-9]+)$ ]]
+ NAME=zk
+ ORD=0
+ MYID=1
+ WRITE_CONFIGURATION=true
+ REGISTER_NODE=true
+ '[' -f /data/myid ']'

++ cat /data/myid
+ EXISTING_ID=1
+ [[ 1 == \1 ]]
+ WRITE_CONFIGURATION=false
+ set +e
+ nslookup zk-headless.default.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve
+ [[ 0 -eq 1 ]]
+ set -e
+ set +e
++ zkConnectionString
+++ awk '{print $4}'
+++ nslookup zk-headless.default.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve
Name:      zk-headless.default.svc.cluster.local
Address 1: 10.8.2.8 zk-1.zk-headless.default.svc.cluster.local
++ HOSTS='

zk-1.zk-headless.default.svc.cluster.local'
++ ZK_CONNECTION_STRING=
++ for i in $HOSTS
++ [[ '' == '' ]]
++ ZK_CONNECTION_STRING=zk-1.zk-headless.default.svc.cluster.local:2181
++ [[ zk-1.zk-headless.default.svc.cluster.local:2181 == '' ]]
++ echo zk-1.zk-headless.default.svc.cluster.local:2181
+ ZKURL=zk-1.zk-headless.default.svc.cluster.local:2181
+ set -e
++ java -Dlog4j.configuration=file:/conf/log4j-quiet.properties -jar /root/zu.jar get-all zk-1.zk-headless.default.svc.cluster.local:2181
Connecting to Zookeeper zk-1.zk-headless.default.svc.cluster.local:2181

```

**Problem [location**]

**Suggestions for an improvement**
I have two zk instances, one crash but the other is running, is it fault-tolerant? And when zk restarts, controllers should be able to connect to the new zk instance and keep working.

**Comment by fpj** [comment]
@jingjinglll this seems like an operator issue, please open an issue in the operator repo, not here.

**Comment by jingjinglll** [comment]
ok

**Comment by fpj** [comment]
Please reopen if this is a Pravega issue and not an operator issue.
