### ISSUE TITLE
Controller test failure: testZkSessionExpiryRetry

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#3271]
**Problem description**
Observed the following test case failure in a Travis job:

```
io.pravega.controller.store.client.StoreClientFactoryTest > testZkSessionExpiryRetry FAILED
    java.lang.RuntimeException: Exception of the wrong type. Was expecting class org.apache.zookeeper.KeeperException$SessionExpiredException but got: org.apache.zookeeper.KeeperException$NoNodeException
        at io.pravega.test.common.AssertExtensions.assertThrows(AssertExtensions.java:54)
        at io.pravega.controller.store.client.StoreClientFactoryTest.testZkSessionExpiryRetry(StoreClientFactoryTest.java:66)
        Caused by:
        org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /test/test
            at org.apache.zookeeper.KeeperException.create(KeeperException.java:115)
            at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
            at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:2019)
            at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:327)
            at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:316)
            at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64)
            at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)
            at org.apache.curator.framework.imps.GetDataBuilderImpl.pathInForeground(GetDataBuilderImpl.java:313)
            at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:304)
            at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:35)
            at io.pravega.controller.store.client.StoreClientFactoryTest.lambda$testZkSessionExpiryRetry$2(StoreClientFactoryTest.java:66)
            at io.pravega.test.common.AssertExtensions.assertThrows(AssertExtensions.java:43)
            ... 1 more
```

**Problem location**
Controller unit tests.

**Suggestions for an improvement**
Track and fix intermittent test failure.

**Comment by shiveshr** [comment]
i dont see whats wrong with the test here. we inject a session expiration and wait for session expiration handler to be invoked. 
once it does, only then do we attempt any calls on the client and expect session expiration response.
but the curator client is able to connect to zk server rather than honour session expiration. 
PS: It is important to note that the session has not expired on zookeeper. The test is mimicking the session expiration by letting client think it has expired. 
Following is the test code
```
        Consumer<Void> expirationHandler = x -> sessionExpiry.complete(null);

        CuratorFramework client = StoreClientFactory.createZKClient(ZKClientConfigImpl.builder().connectionString(zkServer.getConnectString())
                .namespace("test").maxRetries(10).initialSleepInterval(10).secureConnectionToZooKeeper(false).sessionTimeoutMs(15000).build(),
                canRetrySupplier, expirationHandler);
        
        client.getZookeeperClient().getZooKeeper().getTestable().injectSessionExpiration();
        
        sessionExpiry.join();
        
        // verify that we fail with session expiry and we fail without retrying.
        AssertExtensions.assertThrows(KeeperException.SessionExpiredException.class, () -> client.getData().forPath("/test"));
```

**Comment by fpj** [comment]
I've have just observed this failing again in a jenkins build.

[testZkSessionExpiryRetry.txt](https://github.com/pravega/pravega/files/3009610/testZkSessionExpiryRetry.txt)

**Comment by shiveshr** [comment]
This is a unit test only issue as the test in question doesnt really test any pravega specific implementation but how curator's factory method reacts to session expiration. And injection of session expiration had been sporadic in nature. 
We have not observed this issue in past few months. 
Moving this issue to 0.6.

**Comment by shiveshr** [comment]
We have not observed this issue in sometime. I am not sure why that is the case though as nothing has changed in this test or other relevant code. 
I will close this for now and reopen if its observed again.
