### ISSUE TITLE
Error on BookKeeper + jdk11 due to old commons-lang dependency 

### ISSUE THREAD

**Issue by eolivelli** [pravega/pravega#3301]
**Problem description**
I am seeing this error during tests with jdk11:
```

> Task :segmentstore:storage:impl:test

io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogTests$RegularBookKeeperLogTests > classMethod FAILED
    java.lang.ExceptionInInitializerError
        at org.apache.bookkeeper.proto.BookieNettyServer.<init>(BookieNettyServer.java:115)
        at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:98)
        at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:90)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperServiceRunner.runBookie(BookKeeperServiceRunner.java:242)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperServiceRunner.runBookies(BookKeeperServiceRunner.java:207)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperServiceRunner.startAll(BookKeeperServiceRunner.java:173)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogTests.setUpBookKeeper(BookKeeperLogTests.java:104)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogTests$RegularBookKeeperLogTests.startUp(BookKeeperLogTests.java:426)

        Caused by:
        java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 2
            at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
            at java.base/java.lang.String.substring(String.java:1874)
            at org.apache.commons.lang.SystemUtils.getJavaVersionAsFloat(SystemUtils.java:1133)
            at org.apache.commons.lang.SystemUtils.<clinit>(SystemUtils.java:818)

```

**Problem location**
Obsolete third party library common-lang on the classpath

**Suggestions for an improvement**
Upgrade BookKeeper or force explicit dependency to latest common-lang 2.x.

**Comment by eolivelli** [comment]
@adrianmo this issue will be fixed in #3192 

@tkaitchuck I wonder why I did not see such error before, It has been weeks that I am running tests on JDK11.
Anyway we are already working on the solution.
It is only a matter of time

**Comment by adrianmo** [comment]
@eolivelli we have upgraded BK to 4.7.3 and common-lang to 2.6, the latest 2.x at the moment. Can you check if the issue has already been resolved?

**Comment by eolivelli** [comment]
I see tests passing on JDK11, so we can close this issue.

**Comment by eolivelli** [comment]
@adrianmo please commit #3262 in order to prove this at every PR check on Travis
