### ISSUE TITLE
Sporadic build failure: TlsEnabledInProcPravegaClusterTest

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#3342]
**Problem description**
Encountered following test failure during travis build:
```
io.pravega.local.TlsEnabledInProcPravegaClusterTest > testWriteAndReadEventWhenConfigurationIsProper FAILED
    java.lang.AssertionError: expected:<Test event over TLS channel> but was:<null>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.pravega.local.TlsEnabledInProcPravegaClusterTest.testWriteAndReadEventWhenConfigurationIsProper(TlsEnabledInProcPravegaClusterTest.java:121)
```

**Problem location**
TLS enabled cluster test

**Suggestions for an improvement**
Fix the test

**Comment by ravisharda** [comment]
@Shivesh I am working on it and will submit a PR which avoids this issue shortly.

**Comment by fpj** [comment]
@ravisharda There are a lot of stack traces in the logs, what's going on with this test case?

[TEST-io.pravega.local.TlsEnabledInProcPravegaClusterTest.xml.zip](https://github.com/pravega/pravega/files/2844661/TEST-io.pravega.local.TlsEnabledInProcPravegaClusterTest.xml.zip)

**Comment by tkaitchuck** [comment]
This is reoccuring.
