### ISSUE TITLE
Fix ping tests in the 0.4 branch

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#3355]
**Problem description**
The certificate expiration issue (#3345) was also present in the `0.4` branch. Cherry-picking the commit for that issue:

https://github.com/pravega/pravega/commit/49603bf4af95418ab01ead428c7236a8f1c3c571

was not sufficient as the following test cases fail:

```
io.pravega.controller.rest.v1.PingTest$SecurePingTest > test FAILED
    java.lang.NullPointerException
        at io.pravega.controller.rest.v1.PingTest$SecurePingTest.getResourcePath(PingTest.java:106)
        at io.pravega.controller.rest.v1.PingTest$SecurePingTest.getServerConfig(PingTest.java:124)
    java.lang.NullPointerException

io.pravega.controller.rest.v1.PingTest$FailingSecurePingTest > test FAILED
    java.lang.NullPointerException
        at io.pravega.controller.rest.v1.PingTest$SecurePingTest.getResourcePath(PingTest.java:106)
        at io.pravega.controller.rest.v1.PingTest$FailingSecurePingTest.getServerConfig(PingTest.java:140)
    java.lang.NullPointerException
```
They fail due to missing key and trust store files.

**Problem location**
Controller ping tests.

**Suggestions for an improvement**
Cherry pick the commit of PR #3235 :

https://github.com/pravega/pravega/commit/f48a00aea5e18db464e526c855717d79cdf71978

This commit fixes an issue with standalone and add the missing files to fix this issue.

**Comment by RaulGracia** [comment]
This has been already `cherry-picked` to `r0.4`.
