### ISSUE TITLE
Controller Failing to start due to java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#3391]
**Problem description**
It was observed that the controller docker is failing to start due to 
```
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at io.pravega.common.util.CircularBuffer.clear(CircularBuffer.java:40)
	at io.pravega.common.util.CircularBuffer.<init>(CircularBuffer.java:36)
	at io.pravega.client.segment.impl.SegmentInputStreamImpl.<init>(SegmentInputStreamImpl.java:70)
	at io.pravega.client.segment.impl.SegmentInputStreamFactoryImpl.getEventSegmentReader(SegmentInputStreamFactoryImpl.java:53)
	at io.pravega.client.segment.impl.SegmentInputStreamFactoryImpl.getEventSegmentReader(SegmentInputStreamFactoryImpl.java:47)
	at io.pravega.client.segment.impl.SegmentInputStreamFactoryImpl.createEventReaderForSegment(SegmentInputStreamFactoryImpl.java:37)
	at io.pravega.client.segment.impl.SegmentInputStreamFactoryImpl.createEventReaderForSegment(SegmentInputStreamFactoryImpl.java:27)
	at io.pravega.client.stream.impl.ClientFactoryImpl.createRevisionedStreamClient(ClientFactoryImpl.java:176)
	at io.pravega.client.stream.impl.ClientFactoryImpl.createStateSynchronizer(ClientFactoryImpl.java:203)
	at io.pravega.client.admin.impl.ReaderGroupManagerImpl.createReaderGroup(ReaderGroupManagerImpl.java:95)
	at io.pravega.controller.eventProcessor.impl.EventProcessorGroupImpl.createIfNotExists(EventProcessorGroupImpl.java:107)
	at io.pravega.controller.eventProcessor.impl.EventProcessorGroupImpl.initialize(EventProcessorGroupImpl.java:95)
	at io.pravega.controller.eventProcessor.impl.EventProcessorSystemImpl.createEventProcessorGroup(EventProcessorSystemImpl.java:71)
	at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.lambda$initialize$24(ControllerEventProcessors.java:339)
	at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:173)
	at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.initialize(ControllerEventProcessors.java:338)
	at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.startUp(ControllerEventProcessors.java:144)
```
**Problem location**
Build.

**Suggestions for an improvement**
Fix the issue. The issue is due to building code with JDK9+ with target version as Java 8 and running it with Java 8

**Comment by shrids** [comment]
Attaching the logs of the failed controller [controller_restart.log](https://github.com/pravega/pravega/files/2882680/controller_restart.log)

**Comment by shrids** [comment]
Reopening the issue as the same issue was observed with docker image for `5.0-2134.4701d0e` 
With this docker image we are observing the issue consistently. 

The pravega code was built using Java 1.8.
```
16:09:33 Starting a Gradle Daemon (subsequent builds will be faster)
16:09:38 
16:09:38 > Configure project :
16:09:38 Build JVM Version is : 1.8.0_181 (Oracle Corporation 25.181-b13)
```
A docker image was created for Pravega (controller) with `openjdk:8-jre-alpine` as the base image with the jar built using 1.8 java.

Now when the controller starts up 
```
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at io.pravega.common.util.CircularBuffer.clear(CircularBuffer.java:40)
        at io.pravega.common.util.CircularBuffer.<init>(CircularBuffer.java:36)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.<init>(SegmentInputStreamImpl.java:70)
```
this message is thrown causing the controller to shutdown...

**Comment by jkhalack** [comment]
It looks like the latest `openjdk:8-jre-alpine` has `1.8.0_191` java:
```
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (IcedTea 3.10.0) (Alpine 8.191.12-r0)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```
So we have `1.8.0_181` build being run in `1.8.0_191` environment.
