### ISSUE TITLE
Tier2 append write failing with bulk writes

### ISSUE THREAD

**Issue by vijikarthi** [pravega/pravega#3400]
**Problem description**

When tested for bulk writes (3 node Pravega cluster with Apache stock HDFS, 10K event size, 50 parallel writers for a total of 1M events), I have noticed below stack trace in the segment store logs. I was able to reproduce it when I tried it multiple times.

Pravega configurations used:
```
pravegaservice.containerCount		32
pravegaservice.threadPoolSize		128
pravegaservice.storageThreadPoolSize	200
pravegaservice.cacheMaxSize		4294967296 (4 GB)
hdfs.blockSize				67108864 (64 MB)
rocksdb.writeBufferSizeMB		512
rocksdb.readCacheSizeMB			512
rocksdb.cacheBlockSizeKB		64
readindex.storageReadAlignment		33554432 (32 MB)
writer.flushThresholdBytes		67108864 (64 MB)
writer.flushThresholdMillis		2000(2 sec)
writer.maxFlushSizeBytes		67108864(64 MB)
writer.minReadTimeoutMillis		200
```

Exception stacktrace from segment store log
```
2019-02-21 18:32:57,151 5587064 [storage-io-133] ERROR i.p.s.s.rolling.RollingStorage - ENTER write@12049379109221783 [foo1/bar1/8.#epoch.0 (Not Sealed, RW, SegmentChunks=1), 150996155, 27691475].
2019-02-21 18:32:57,154 5587067 [storage-io-133] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[22]: Iteration[5761].Error.
io.pravega.segmentstore.contracts.StreamSegmentExistsException: [Segment 'foo1/bar1/8.#epoch.0$offset.0'] The StreamSegment exists already
        at io.pravega.storage.hdfs.HDFSExceptionHelpers.convertException(HDFSExceptionHelpers.java:44)
        at io.pravega.storage.hdfs.HDFSStorage.write(HDFSStorage.java:382)
        at io.pravega.segmentstore.storage.rolling.RollingStorage.write(RollingStorage.java:322)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$write$2(AsyncStorageWrapper.java:93)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$runAsync$12(AsyncStorageWrapper.java:171)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hdfs.protocol.AlreadyBeingCreatedException: Failed to APPEND_FILE /proot/foo1/bar1/8.#epoch.0$offset.0_1 for DFSClient_NONMAPREDUCE_2002420152_180 on 10.240.135.49 because DFSClient_NONMAPREDUCE_2002420152_180 is already the current lease holder.
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.recoverLeaseInternal(FSNamesystem.java:3140)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInternal(FSNamesystem.java:2935)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInt(FSNamesystem.java:3247)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFile(FSNamesystem.java:3216)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.append(NameNodeRpcServer.java:767)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.append(ClientNamenodeProtocolServerSideTranslatorPB.java:433)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:640)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2351)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2347)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1869)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2347)

        at sun.reflect.GeneratedConstructorAccessor35.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
        at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:110)
        at io.pravega.storage.hdfs.HDFSExceptionHelpers.convertException(HDFSExceptionHelpers.java:38)
        ... 13 common frames omitted

```

**Problem location**
Found with the latest master build `Praveag 0.5.0-SNAPSHOT`

**Suggestions for an improvement**

**Comment by sachin-j-joshi** [comment]
Additional references -
https://github.com/pravega/pravega/issues/1287

https://github.com/pravega/pravega/pull/1781

**Comment by sachin-j-joshi** [comment]
- This issue is related to HDFS setup. In this case our cluster is very small cluster (n<= 3).
- **The root cause** of this exception is the fact that we are using small cluster and any network glitches or data node being unresponsive causes failures in setup of data pipeline. We get following exception

>  java.io.IOException: Failed to replace a bad datanode on the existing pipeline due to no more good datanodes being available to try.

- The **workaround/ solution** is to set hdfs.replaceDataNodesOnFailure = false for SegmentStore config (similar to what we do for docker and mesos based tests.). This sets dfs.client.block.write.replace-datanode-on-failure.policy = NEVER for the hdfs client in SegmentStore. 
- Also please note that I have made sure that this issue is not cause by concurrent access to same segment due to scheduling bug in segment store .(Basically just to be absolutely sure - I made all methods on HDFSStorage synchronized, ran simple test with only one segment store. I still get the same error when running against a single node HDFS deployment.)

**Comment by sachin-j-joshi** [comment]
@vijikarthi @kmgowda  Based on my understanding of the underlying issue , the root cause is the tiny size of the HDFS cluster which eventually causes some/all data nodes being considered "bad" and unable to be replaced.  

Without explicitly setting dfs.client.block.write.replace-datanode-on-failure.policy = NEVER, this is unavoidable situation given the tiny cluster size.

I have double checked that this is not cause by any scheduling problems with tier-2 writes.

I recommend setting hdfs.replaceDataNodesOnFailure = false in the perf tests. 


[See also - https://github.com/pravega/pravega/issues/2967]

**Comment by vijikarthi** [comment]
@sachin-j-joshi I think the configuration `hdfs.replaceDataNodesOnFailure` is not documented/exposed in the `config.properties` though `HDFSStorageConfig` makes use of this property. I think we need to fix the configuration file to include this property. Also, were you able to test and confirm with/without this configuration?

**Comment by andreipaduroiu** [comment]
Not all the configuration items are present in the config.properties file. There are quite a few that are defaulted in the code but we haven't paid our due diligence to keep these documented in two places. The `HDFSConfig` class does document that properly. 

But I agree with you. I think it's a good user experience to keep the config.properties file up-to-date as that will be used as a reference by the user when they set up their cluster.

**Comment by sachin-j-joshi** [comment]
I'll update the config.properties file.
Yes. I have ran and verified the setting against HDFS (in k8s system tests).

**Comment by sachin-j-joshi** [comment]
@vijikarthi  @andreipaduroiu config.properties updated here https://github.com/pravega/pravega/pull/3680

**Comment by sachin-j-joshi** [comment]
@vijikarthi @kmgowda okay to close this issue ?

**Comment by vijikarthi** [comment]
closed https://github.com/pravega/pravega/pull/3680
