### ISSUE TITLE
Longevity test: moderate IO workload failed after ~6 days of run due to errors on ZK 

### ISSUE THREAD

**Issue by deenav** [pravega/pravega#3408]
**Problem description**
While running longevity test in PKS cluster with moderate IO (medium-scale) workload on `pravega:issue-3227-controller-zk-connection-recovery-0.5.0-2126.f190425` branch, observed client workload eventually stopped after `~6 days` due to some correlated errors seen on Zookeeper logs at `2019-02-20 21:50:00`

From @RaulGracia's  early investigation, the problem arises as below,

1) Zookeeper logs show some correlated failures at `2019-02-20 21:50:00`:
```
(zookeeper-0)
2019-02-20 21:50:00,308 [myid:1] - WARN  [QuorumPeer[myid=1](plain=/0.0.0.0:2181)(secure=disabled):Follower@96] - Exception when following the leader
java.io.EOFException
    at java.io.DataInputStream.readInt(DataInputStream.java:392)
    at org.apache.jute.BinaryInputArchive.readInt(BinaryInputArchive.java:63)
    at org.apache.zookeeper.server.quorum.QuorumPacket.deserialize(QuorumPacket.java:85)
    at org.apache.jute.BinaryInputArchive.readRecord(BinaryInputArchive.java:99)
    at org.apache.zookeeper.server.quorum.Learner.readPacket(Learner.java:157)
    at org.apache.zookeeper.server.quorum.Follower.followLeader(Follower.java:92)
    at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:1214)
2019-02-20 21:50:00,310 [myid:1] - INFO  [QuorumPeer[myid=1](plain=/0.0.0.0:2181)(secure=disabled):MBeanRegistry@128] - Unregister MBean [org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Follower]
2019-02-20 21:50:00,312 [myid:1] - INFO  [QuorumPeer[myid=1](plain=/0.0.0.0:2181)(secure=disabled):Follower@201] - shutdown called
java.lang.Exception: shutdown Follower
    at org.apache.zookeeper.server.quorum.Follower.shutdown(Follower.java:201)
    at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:1218) 
```

```
(zookeeper-1)
2019-02-20 21:57:07,946 [myid:2] - WARN  [SyncThread:2:SendAckRequestProcessor@64] - Closing connection to leader, exception during packet send
java.net.SocketException: Broken pipe (Write failed)
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
    at org.apache.zookeeper.server.quorum.Learner.writePacket(Learner.java:143)
    at org.apache.zookeeper.server.quorum.SendAckRequestProcessor.flush(SendAckRequestProcessor.java:62)
    at org.apache.zookeeper.server.SyncRequestProcessor.flush(SyncRequestProcessor.java:186)
    at org.apache.zookeeper.server.SyncRequestProcessor.run(SyncRequestProcessor.java:113)
2019-02-20 21:57:08,246 [myid:2] - WARN  [QuorumPeer[myid=2](plain=/0.0.0.0:2181)(secure=disabled):Follower@96] - Exception when following the leader
java.net.SocketException: Broken pipe (Write failed)
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
    at org.apache.zookeeper.server.quorum.Learner.writePacket(Learner.java:143)
    at org.apache.zookeeper.server.quorum.Learner.ping(Learner.java:637)
    at org.apache.zookeeper.server.quorum.Follower.processPacket(Follower.java:119)
    at org.apache.zookeeper.server.quorum.Follower.followLeader(Follower.java:93)
    at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:1214)
2019-02-20 21:57:08,245 [myid:2] - INFO  [NIOServerCxnFactory.AcceptThread:/0.0.0.0:2181:NIOServerCnxnFactory$AcceptThread@296] - Accepted socket connection from /172.24.71.13:32838
2019-02-20 21:57:08,485 [myid:2] - WARN  [NIOWorkerThread-14:NIOServerCnxn@366] - Unable to read additional data from client sessionid 0x3000c71a4a5000c, likely client has closed socket
2019-02-20 21:57:08,484 [myid:2] - INFO  [QuorumPeer[myid=2](plain=/0.0.0.0:2181)(secure=disabled):MBeanRegistry@128] - Unregister MBean [org.apache.ZooKeeperService:name0=ReplicatedServer_id2,name1=replica.2,name2=Follower]
2019-02-20 21:57:08,504 [myid:2] - INFO  [QuorumPeer[myid=2](plain=/0.0.0.0:2181)(secure=disabled):Follower@201] - shutdown called
java.lang.Exception: shutdown Follower
    at org.apache.zookeeper.server.quorum.Follower.shutdown(Follower.java:201)
    at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:1218)
2019-02-20 21:57:08,504 [myid:2] - INFO  [NIOWorkerThread-14:MBeanRegistry@128] - Unregister MBean [org.apache.ZooKeeperService:name0=ReplicatedServer_id2,name1=replica.2,name2=Follower,name3=Connections,name4=172.24.71.9,name5=0x3000c71a4a5000c]
2019-02-20 21:57:08,505 [myid:2] - INFO  [NIOWorkerThread-14:NIOServerCnxn@627] - Closed socket connection for client /172.24.71.9:55964 which had sessionid 0x3000c71a4a5000c
2019-02-20 21:57:08,504 [myid:2] - INFO  [NIOWorkerThread-9:ZooKeeperServer@1041] - Client attempting to establish new session at /172.24.71.13:32838
2019-02-20 21:57:08,504 [myid:2] - INFO  [QuorumPeer[myid=2](plain=/0.0.0.0:2181)(secure=disabled):MBeanRegistry@128] - Unregister MBean [org.apache.ZooKeeperService:name0=ReplicatedServer_id2,name1=replica.2,name2=Follower,name3=Connections,name4=172.24.71.7,name5=0x2000c71c3dcac18]
```
```
2019-02-20 21:57:08,506 [myid:2] - INFO  [QuorumPeer[myid=2](plain=/0.0.0.0:2181)(secure=disabled):NIOServerCnxn@627] - Closed socket connection for client /172.24.71.7:40732 which had sessionid 0x2000c71c3dcac18
2019-02-20 21:57:08,506 [myid:2] - INFO  [QuorumPeer[myid=2](plain=/0.0.0.0:2181)(secure=disabled):NIOServerCnxn@627] - Closed socket connection for client /172.24.71.13:32838 which had sessionid 0x2000c71c3dcac1c
2019-02-20 21:57:08,546 [myid:2] - ERROR [FollowerRequestProcessor:2:ZooKeeperCriticalThread@48] - Severe unrecoverable error, from thread : FollowerRequestProcessor:2
java.net.SocketException: Socket closed
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:118)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
    at org.apache.zookeeper.server.quorum.Learner.writePacket(Learner.java:143)
    at org.apache.zookeeper.server.quorum.Learner.request(Learner.java:192)
    at org.apache.zookeeper.server.quorum.FollowerRequestProcessor.run(FollowerRequestProcessor.java:102)
```

2) This problem impacts the Bookkeeper service, as they do not receive more IO from the segment store (rest of BK log lines are related to compaction until `2019-02-21 06:22:09`):
```
(bookie-0)
2019-02-20 21:57:19,266 - INFO  - [ZKC-connect-executor-0-SendThread(nautilus-pravega-zookeeper-client:2181):ClientCnxn$SendThread@879] - Socket connection established to nautilus-pravega-zookeeper-client/10.100.200.233:2181, initiating session
2019-02-20 21:57:19,306 - INFO  - [ZKC-connect-executor-0-SendThread(nautilus-pravega-zookeeper-client:2181):ClientCnxn$SendThread@1303] - Session establishment complete on server nautilus-pravega-zookeeper-client/10.100.200.233:2181, sessionid = 0x3000c71a4a5acbb, negotiated timeout = 10000
2019-02-20 21:57:19,446 - INFO  - [ZKC-connect-executor-0-EventThread:ZooKeeperWatcherBase@130] - ZooKeeper client is connected now.
2019-02-20 21:57:19,786 - INFO  - [ZKC-connect-executor-0:ZooKeeperClient$1$1@130] - ZooKeeper session 3000c71a4a5acbb is created to nautilus-pravega-zookeeper-client:2181.
2019-02-20 21:57:40,222 - INFO  - [BookieHighPriorityThread-3181-OrderedExecutor-2-0:ReadEntryProcessorV3@206] - Ledger fence request received for ledger: 1706 from address: /172.24.71.10:44568
2019-02-20 21:57:40,421 - INFO  - [BookieHighPriorityThread-3181-OrderedExecutor-3-0:ReadEntryProcessorV3@206] - Ledger fence request received for ledger: 1707 from address: /172.24.71.10:44568
2019-02-20 21:59:48,170 - INFO  - [BookieHighPriorityThread-3181-OrderedExecutor-6-0:ReadEntryProcessorV3@206] - Ledger fence request received for ledger: 1702 from address: /172.24.71.14:47652
2019-02-20 22:01:20,918 - ERROR - [BookieWriteThreadPool-OrderedExecutor-0-0:WriteEntryProcessorV3@138] - Ledger fenced while writing entry:344 to ledger:1702
org.apache.bookkeeper.bookie.BookieException$LedgerFencedException
    at org.apache.bookkeeper.bookie.BookieException.create(BookieException.java:57)
    at org.apache.bookkeeper.bookie.Bookie.addEntry(Bookie.java:1240)
    at org.apache.bookkeeper.proto.WriteEntryProcessorV3.getAddResponse(WriteEntryProcessorV3.java:123)
    at org.apache.bookkeeper.proto.WriteEntryProcessorV3.safeRun(WriteEntryProcessorV3.java:163)
    at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
2019-02-20 22:01:35,071 - INFO  - [BookieHighPriorityThread-3181-OrderedExecutor-4-0:ReadEntryProcessorV3@206] - Ledger fence request received for ledger: 1708 from address: /172.24.71.12:58362
2019-02-20 22:02:11,190 - INFO  - [GarbageCollectorThread-8-1:GarbageCollectorThread@567] - Extracting entry log meta from entryLogId: 1687
```
```
(bookie-1)
2019-02-20 22:01:17,796 - INFO  - [ZKC-connect-executor-0-SendThread(nautilus-pravega-zookeeper-client:2181):ClientCnxn$SendThread@1162] - Unable to read additional data from server sessionid 0x10005eaf60b228f, likely server has closed socket, closing socket connection and attempting reconnect
2019-02-20 22:01:17,784 - INFO  - [BookieHighPriorityThread-3181-OrderedExecutor-6-0:ReadEntryProcessorV3@206] - Ledger fence request received for ledger: 1702 from address: /172.24.71.14:56160
2019-02-20 22:01:21,544 - INFO  - [ZKC-connect-executor-0-EventThread:ZooKeeperWatcherBase@134] - ZooKeeper client is disconnected from zookeeper now, but it is OK unless we received EXPIRED event.
2019-02-20 22:01:21,545 - INFO  - [ZKC-connect-executor-0-EventThread:ZooKeeperWatcherBase@134] - ZooKeeper client is disconnected from zookeeper now, but it is OK unless we received EXPIRED event.
2019-02-20 22:01:21,545 - INFO  - [ZKC-connect-executor-0-EventThread:ZooKeeperWatcherBase@134] - ZooKeeper client is disconnected from zookeeper now, but it is OK unless we received EXPIRED event.
2019-02-20 22:01:21,559 - ERROR - [BookieWriteThreadPool-OrderedExecutor-0-0:WriteEntryProcessorV3@138] - Ledger fenced while writing entry:344 to ledger:1702
org.apache.bookkeeper.bookie.BookieException$LedgerFencedException
    at org.apache.bookkeeper.bookie.BookieException.create(BookieException.java:57)
    at org.apache.bookkeeper.bookie.Bookie.addEntry(Bookie.java:1240)
    at org.apache.bookkeeper.proto.WriteEntryProcessorV3.getAddResponse(WriteEntryProcessorV3.java:123)
    at org.apache.bookkeeper.proto.WriteEntryProcessorV3.safeRun(WriteEntryProcessorV3.java:163)
    at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
2019-02-20 22:01:23,411 - INFO  - [ZKC-connect-executor-0-SendThread(nautilus-pravega-zookeeper-client:2181):ClientCnxn$SendThread@1029] - Opening socket connection to server nautilus-pravega-zookeeper-client/10.100.200.233:2181. Will not attempt to authenticate using SASL (unknown error)
```

3) And from that point onwards, the segment instances have problems to write to BK:
```
(segmentstore-0)
2019-02-20 21:57:35,144 549914491 [core-21] WARN  i.p.s.s.i.bookkeeper.BookKeeperLog - Log[1]: Too many rollover failures; closing.
java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to create new BookKeeper Ledger.
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
    at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:874)
    at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
    at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
    at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:690)
    at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to create new BookKeeper Ledger.
    at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$3(Retry.java:214)
    at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
    ... 12 common frames omitted
Caused by: java.util.concurrent.CompletionException: io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to create new BookKeeper Ledger.
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
    ... 8 common frames omitted
Caused by: io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to create new BookKeeper Ledger.
    at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.create(Ledgers.java:55)
    at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.rollover(BookKeeperLog.java:851)
    at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705)
    ... 9 common frames omitted
Caused by: org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: Not enough non-faulty bookies available
    at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:83)
    at org.apache.bookkeeper.client.SyncCallbackUtils$SyncCreateCallback.createComplete(SyncCallbackUtils.java:106)
    at org.apache.bookkeeper.client.LedgerCreateOp.createComplete(LedgerCreateOp.java:240)
    at org.apache.bookkeeper.client.LedgerCreateOp.initiate(LedgerCreateOp.java:144)
    at org.apache.bookkeeper.client.BookKeeper.asyncCreateLedger(BookKeeper.java:879)
    at org.apache.bookkeeper.client.BookKeeper.createLedger(BookKeeper.java:965)
    at org.apache.bookkeeper.client.BookKeeper.createLedger(BookKeeper.java:938)
    at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.lambda$create$0(Ledgers.java:48)
    at io.pravega.common.Exceptions.handleInterruptedCall(Exceptions.java:138)
    at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.create(Ledgers.java:47)
    ... 11 common frames omitted
```

4) In turn, this makes Container recovery to fail:
```
2019-02-20 21:59:12,443 550011790 [core-18] ERROR i.p.s.server.logs.DurableLog - DurableLog[2] Recovery FAILED.
io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to create new BookKeeper Ledger.
    at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.create(Ledgers.java:55)
    at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.initialize(BookKeeperLog.java:229)
    at io.pravega.segmentstore.server.logs.DurableLog.performRecovery(DurableLog.java:212)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: Not enough non-faulty bookies available
    at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:83)
    at org.apache.bookkeeper.client.SyncCallbackUtils$SyncCreateCallback.createComplete(SyncCallbackUtils.java:106)
    at org.apache.bookkeeper.client.LedgerCreateOp.createComplete(LedgerCreateOp.java:240)
    at org.apache.bookkeeper.client.LedgerCreateOp.initiate(LedgerCreateOp.java:144)
    at org.apache.bookkeeper.client.BookKeeper.asyncCreateLedger(BookKeeper.java:879)
    at org.apache.bookkeeper.client.BookKeeper.createLedger(BookKeeper.java:965)
    at org.apache.bookkeeper.client.BookKeeper.createLedger(BookKeeper.java:938)
    at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.lambda$create$0(Ledgers.java:48)
    at io.pravega.common.Exceptions.handleInterruptedCall(Exceptions.java:138)
    at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.create(Ledgers.java:47)
    ... 10 common frames omitted
```

5) While bookies are still alive, segmentstore instances seem to not be able to recover from this state and the client workload eventually stops.

**Comment by RaulGracia** [comment]
Probably related to #3218.

**Comment by fpj** [comment]
Is this still an issue?

**Comment by RaulGracia** [comment]
Since we started using the `headless` Zookeeper endpoints, I have observed less connectivity problems with Zookeeper in the logs (see discussion in #3651). Moreover, due to major recent changes in Pravega, it has not been possible to sustain a longevity workload for 6 days until now. Thus, we need to observe the logs of Bookkeeper and Zookeeper in current longevity runs to check if this kind of errors are still present.

**Comment by RaulGracia** [comment]
I have checked the logs of Bookkeeper used in longevity runs and I haven't seen any of the previous exceptions in few days (from `2019-05-27 09:41:09` to `2019-06-04 06:37:58,77`). I'm closing this issue, as apparently using the `headless` endpoints is making the system much more stable.
