### ISSUE TITLE
EventStreamWriter#flush does not block in case an inflight event is being written to a SealedSegment

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#3425]
**Problem description**
This issue occurs when we have a `flush` and `seal` happening at the same time. The `flush` invokes `selector.getSegments()` which is synchronized and the scaling retransmit worker thread calls `selector.updateSegmentsUponSealed()` which is also synchronized. However scaling retransmit worker thread releases the lock upon return of the method before the events are added to the inflight on the new segment.

**Problem location**
EventStreamWriter.

**Suggestions for an improvement**
Fix the issue.

**Comment by shrids** [comment]
Details of the issue:

*Summary* :
`ReadWriteAndAutoScaleWithFailoverTest` failed since the test could not read 1 event out of `20552` events that were written. This was because a connection to a segment was closed when a resend on sealed was invoked.
```2019-02-28 02:21:35,141 811376 [ScalingRetransmition-testReadWriteAndAutoScaleScope1032645466/testReadWriteAndAutoScaleStream-5] ERROR i.p.c.s.impl.EventStreamWriterImpl - Encountered exception when handling a sealed segment: 
java.lang.IllegalStateException: SegmentOutputStream is already closed
```

*Details:*

1. The eventstreamWriter.write() is invoked for event `27dadb9a-2b9f-43a0-a4a1-0654b523094e:0`. This is followed by eventstreamWriter.flush().

2. The segmentwriter for this event is `c986dc81-5abd-4815-aa9d-e7808ef7a395` segment `testReadWriteAndAutoScaleStream/5.#epoch.2`
```
2019-02-28 02:21:35,077 811312 [ReadWriteAndAutoScaleWithFailoverTest-main-1] DEBUG i.p.t.system.AbstractReadWriteTest - Event write count before write call 20547
2019-02-28 02:21:35,078 811313 [ReadWriteAndAutoScaleWithFailoverTest-main-1] TRACE i.p.c.s.i.SegmentOutputStreamImpl - Adding event 908 to inflight on writer c986dc81-5abd-4815-aa9d-e7808ef7a395
```
3. This writer encounters a SegmentSealed and it immediately puts it in the `sealedSegmentQueue`. In the mean time since flush is invoked the client is continuously checking if all the entries are durably persisted by Pravega (this is happening on the test thread `[ReadWriteAndAutoScaleWithFailoverTest-main-1]`).

4. The restransmit of inflight events causes the client to fetch the successors of (`5.#epoch2`).
```
2019-02-28 02:21:35,082 811317 [ScalingRetransmition-testReadWriteAndAutoScaleScope1032645466/testReadWriteAndAutoScaleStream-5] INFO  i.p.c.s.impl.EventStreamWriterImpl - Sealing segment testReadWriteAndAutoScaleScope1032645466/testReadWriteAndAutoScaleStream/5.#epoch.2
``` 
5. The controller returns segments
```
12884901894L - 6.#epoch.3 [0.75 - 0.875)
12884901895L - 7.#epoch.3 [0.875-1.0)
```
 6. Now the event will be written using the writer to segment `6.#epoch.3` in the retransmit thread.
```
2019-02-28 02:21:35,125 811360 [ScalingRetransmition-testReadWriteAndAutoScaleScope1032645466/testReadWriteAndAutoScaleStream-5] DEBUG i.p.c.stream.impl.SegmentSelector - Creating writer for segment testReadWriteAndAutoScaleScope1032645466/testReadWriteAndAutoScaleStream/6.#epoch.3

2019-02-28 02:21:35,139 811374 [ScalingRetransmition-testReadWriteAndAutoScaleScope1032645466/testReadWriteAndAutoScaleStream-5] INFO  i.p.c.s.impl.EventStreamWriterImpl - Resending 1 events
```
7. Now at this time the test thread which was waiting at flush() sees that the segmentwriters are updated and their inflight is 0. Hence it stops waiting.
Next the test immediately invokes `EventStreamWriter.stop()` causing a close of all connections.

8.The resend event causes fails with
```
2019-02-28 02:21:35,141 811376 [ScalingRetransmition-testReadWriteAndAutoScaleScope1032645466/testReadWriteAndAutoScaleStream-5] ERROR i.p.c.s.impl.EventStreamWriterImpl - Encountered excemption when handeling a sealed segment: 
java.lang.IllegalStateException: SegmentOutputStream is already closed
    at io.pravega.client.segment.impl.SegmentOutputStreamImpl.getConnection(SegmentOutputStreamImpl.java:454)
    at io.pravega.client.segment.impl.SegmentOutputStreamImpl.write(SegmentOutputStreamImpl.java:431)
    at io.pravega.client.stream.impl.EventStreamWriterImpl.resend(EventStreamWriterImpl.java:187)
    at io.pravega.client.stream.impl.EventStreamWriterImpl.lambda$null$1(EventStreamWriterImpl.java:156)
    at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:173)
    at io.pravega.client.stream.impl.EventStreamWriterImpl.lambda$handleLogSealed$2(EventStreamWriterImpl.java:143)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```
The causes the event to be not written and hence the test was not able to read it...

Logs:
[completeLogs-readwriteandautoscalewithfailovertest-tamly- (1).zip](https://github.com/pravega/pravega/files/2930760/completeLogs-readwriteandautoscalewithfailovertest-tamly-.1.zip)
[reducedLogs.zip](https://github.com/pravega/pravega/files/2930761/reducedLogs.zip)

**Comment by shrids** [comment]
Invariants for `SegmentWriter#flush()`
-  It will block until inflight is empty.
-  It will through a SegmentSealedException only after `getUnackedEventsOnSeal()` is method is invoked.

Invariants of `EventStreamWriterImpl#handleLogSealed`:
- Multiple threads can invoke this method concurrently and invocation of this will ensure `sealedSegmentQueue` has an additional entry.
- The resend logic(update segment writers and resend) events to the new segments and invoke a flush on current segments.
- During this resend new writes are blocked i.e. The inflight events of all the writers will sent and cleared.
- The resend logic invokes `getUnackedEventsOnSeal`only when the newer Segment writers are fetched.

Invariants of `EventStreamWriterImpl#flush`
- No new writes (EventStreamWriterImpl#write) can happen when flush is invoked.
- It invokes a `SegmentWriter#flush` on the current segments.
- if any of the segment writer throw a `SealedSegmentException` then it retries doing a flush on all refreshed current segments.

With the above invariants in context the issue here is that `SegmentOutputStreamImpl#flush()` does not throw a `SealedSegmentException` if the segment is sealed and num of inflight events is 0.
