### ISSUE TITLE
Pravega client continues to ping the same transaction forever

### ISSUE THREAD

**Issue by claudiofahey** [pravega/pravega#3463]
**Problem description**

The Pravega client repeatedly shows messages such as the one below. The message is repeated several times a minute over at least an 8 hour period. All transactions that have ever been opened in the client process are included. This suggests that the transaction pinger is never removing transactions from the list of transactions to ping, even after they have been committed.

```
WARN  [2019-03-14 09:26:08.088] [grpc-default-executor-11] i.p.c.stream.impl.ControllerImpl: gRPC call for pingTransaction with trace id 0 failed with server error.
io.grpc.StatusRuntimeException: INTERNAL: /transactions/activeTx/examples20/STREAMPROCESSING2/0/00000000-0000-0000-0000-000000000001
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:418)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:663)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:443)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:525)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:446)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:557)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

The following code reproduces this error:
https://github.com/claudiofahey/pravega-samples/blob/issue-191-streamprocessing/pravega-client-examples/src/main/java/io/pravega/example/streamprocessing/ExactlyOnceMultithreadedProcessor.java#L420

Of particular note, the client that begins the transaction does not commit or abort it. It relies on another process to get the transaction by transaction ID and commit it. For this reason, the client never calls `Pinger.stopPing`, causing transactions to never be removed from the Pinger list.

This occurs with Pravega 0.4.0. Other versions have not been tested. Pravega was started using `docker-compose up`.

**Problem location**

Possibly `io.pravega.client.stream.impl.Pinger.pingTransactions`.

**Suggestions for an improvement**

`io.pravega.client.stream.impl.Pinger.pingTransactions` should remove non-open transactions from `txnList`. It should not rely on the client calling `abort` or `commit`.
Alternatively, make `Transaction` closeable and add `stopPing` to the `close`. This allows the pinger to stop pinging the transaction even when we don't want that client to abort or commit.

**Comment by claudiofahey** [comment]
See related issue https://github.com/pravega/pravega/issues/2830.
