### ISSUE TITLE
Data corruption exception in System tests.

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#3464]
**Problem description**
In some system test runs such as ReadTxnWriteScaleWithFailoverTest, when bookies are repeatedly failing, a `DataCorruptionException` occurs. Example:

```
segmentstore_2019-03-14.59.log:2019-03-14 06:25:48,526 1412251 [core-18] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 1, 2, 3], Current = [0, 1, 2, 3], PendingTasks = [], ToStart = [], ToStop = [].
2019-03-14 06:25:52,893 1416618 [core-25] WARN  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[1]: Writer failed. Shutting down StreamSegmentContainer.
java.util.concurrent.CompletionException: io.pravega.segmentstore.server.DataCorruptionException: Unable to retrieve CacheContents for 'AggregatedAppend: SegmentId = 1, Offsets = [892517-2320514), Se
qNo = 18494'.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
  Caused by: io.pravega.segmentstore.server.DataCorruptionException: Unable to retrieve CacheContents for 'AggregatedAppend: SegmentId = 1, Offsets = [892517-2320514), SeqNo = 18494'.
        at io.pravega.segmentstore.server.writer.SegmentAggregator.getFlushArgs(SegmentAggregator.java:826)
        at io.pravega.segmentstore.server.writer.SegmentAggregator.flushPendingAppends(SegmentAggregator.java:754)
        at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$flushExcess$14(SegmentAggregator.java:696)
        ... 11 common frames omitted
        
segmentstore_2019-03-14.60.log:2019-03-14 06:25:58,526 1422251 [core-24] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 1, 2, 3], Current = [0, 2, 3], PendingTasks = [], ToStart = [1], ToStop = [].
```

**Comment by tkaitchuck** [comment]
If this prevents data from being moved to tier-2 then this would also explain the 'to many active segments' issue we are seeing later on.

**Comment by fpj** [comment]
It is not clear what the relation is, and it might not be the cause at all, but we started observing this after we have re-enabled transactions in system tests. Could it be at all related to transactions or is it a red herring?

**Comment by fpj** [comment]
Also, this `DataCorruption` problem described here might be an issue, but I just analyzed another system test run, and I don’t see any of this `DataCorruption` exception, I see instead a lot of:

```io.pravega.segmentstore.contracts.TooManyActiveSegmentsException: [Container 0] The maximum number of active Segments (10000) has been reached.```

**Comment by andreipaduroiu** [comment]
Repro scenario (from logs):

Failure: (attempts to read at offset 5106016).
```
2019-03-15 21:34:26,152 8155747 [core-4] DEBUG i.p.s.s.reading.ContainerReadIndex - ReadIndex[0]: readDirect (StreamSegmentId = 1, Offset = 5106016, Length = 3000724).
2019-03-15 21:34:26,215 8155810 [core-11] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[0]: Iteration[760].CriticalError.
io.pravega.segmentstore.server.DataCorruptionException: Unable to retrieve CacheContents for 'AggregatedAppend: SegmentId = 1, Offsets = [5106016-8106740), SeqNo = 97816'.
```

This causes the container to shut down and restart. The recovery logs gives a priceless view into the  state of Segment Id 1:
```
2019-03-15 21:34:34,498 8164093 [core-27] DEBUG i.p.s.server.logs.RecoveryProcessor - RecoveryProcessor[0] Recovering UpdateAttributesOperation: SequenceNumber = 97816, SegmentId = 1, Attributes = 5.
2019-03-15 21:34:34,499 8164094 [core-27] DEBUG i.p.s.server.logs.RecoveryProcessor - RecoveryProcessor[0] Recovering StreamSegmentAppendOperation: SequenceNumber = 97818, SegmentId = 1, Offset = 5462066, Length = 136, Attributes = 0.
2019-03-15 21:34:34,499 8164094 [core-27] DEBUG i.p.s.server.logs.RecoveryProcessor - RecoveryProcessor[0] Recovering UpdateAttributesOperation: SequenceNumber = 97820, SegmentId = 1, Attributes = 5.
2019-03-15 21:34:34,499 8164094 [core-27] DEBUG i.p.s.server.logs.RecoveryProcessor - RecoveryProcessor[0] Recovering StreamSegmentAppendOperation: SequenceNumber = 97821, SegmentId = 1, Offset = 5462202, Length = 371, Attributes = 0.

... (skipped over a lot more) ....
```

It looks like the first recovered append starts at offset 5462066, which is above the first offset the StorageWriter is attempting to read at (5106016).

Need to investigate where the gap is coming from.

**Comment by tkaitchuck** [comment]
Correct, too many active segments, issue is unrelated.
