### ISSUE TITLE
Handle ZK-related exceptions from HostStore when shutting down Controller

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#3477]
**Problem description**
The fix for the ZK session expiration with different connection parameters issue (#3387) uncovered another problem: It seems that the modules using `ZKHostStore` will throw `HostStoreException` because of ZK session expiration. These exceptions seem not to be properly handled during the `shutDown()` process of `ControllerServiceStarter`, and then the graceful restart does not work (the process terminates):

1) Detect session expiration with different ZK connection parameters
``` 
2019-03-14 17:12:42,390 118846521 [ControllerServiceMain-EventThread] WARN  i.p.c.s.client.StoreClientFactory - Input argument for new ZooKeeper client (A:2181,B:2181,C:2181, 10000, false) changed with respect to existing client (X:2181, 10000, false).
java.lang.IllegalArgumentException: connectString differs
```
2) As expected, after the expiration the Controller now is able to initiate a graceful restart:
```
2019-03-14 17:12:42,393 118846524 [Curator-ConnectionStateManager-0] INFO  o.a.zookeeper.ZooKeeperTestable - injectSessionExpiration() called
2019-03-14 17:12:42,393 118846524 [ControllerServiceMain-EventThread] INFO  o.a.c.f.s.ConnectionStateManager - State change: LOST
2019-03-14 17:12:42,393 118846524 [controllerpool-63] ERROR i.p.c.cluster.zkImpl.ClusterZKImpl - Connection lost with Zookeeper
2019-03-14 17:12:42,393 118846524 [Curator-ConnectionStateManager-0] INFO  i.p.c.fault.SegmentMonitorLeader - Zookeeper connection state changed to: LOST
2019-03-14 17:12:42,393 118846524 [Curator-ConnectionStateManager-0] WARN  i.p.c.fault.SegmentContainerMonitor - Connection to zookeeper lost, attempting to interrrupt the leader thread
2019-03-14 17:12:42,393 118846524 [Curator-PathChildrenCache-0] WARN  i.p.c.s.b.ZooKeeperBucketManager - RetentionService: Received connectivity error
2019-03-14 17:12:42,394 118846525 [controllerpool-63] INFO  i.p.c.f.ControllerClusterListener - Received error event when monitoring the controller host cluster, ignoring...
2019-03-14 17:12:42,394 118846525 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - ZK session expired
2019-03-14 17:12:42,394 118846525 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - Stopping ControllerServiceStarter
2019-03-14 17:12:42,410 118846541 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - Awaiting termination of ControllerServiceStarter
2019-03-14 17:12:42,411 118846542 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Initiating controller service shutDown
2019-03-14 17:12:42,411 118846542 [RESTServer STOPPING] INFO  i.p.c.server.rest.RESTServer - Stopping REST server listening on port: 10080
2019-03-14 17:12:42,411 118846542 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Stopping controller event processors
2019-03-14 17:12:42,411 118846542 [GRPCServer STOPPING] INFO  i.p.c.server.rpc.grpc.GRPCServer - Stopping gRPC server listening on port: 9090
2019-03-14 17:12:42,413 118846544 [GRPCServer STOPPING] INFO  i.p.c.server.rpc.grpc.GRPCServer - Awaiting termination of gRPC server
2019-03-14 17:12:42,443 118846574 [ControllerServiceMain-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x10002a4c8ea00e1
2019-03-14 17:12:42,443 118846574 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Stopping the segment container monitor
2019-03-14 17:12:42,443 118846574 [ControllerEventProcessors STOPPING] INFO  i.p.c.s.e.ControllerEventProcessors - Stopping controller event processors
2019-03-14 17:12:42,443 118846574 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Stopping controller cluster listener
2019-03-14 17:12:42,444 118846575 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Controller cluster listener shutdown
2019-03-14 17:12:42,444 118846575 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Stopping auto retention service
```

3) However, the Event Processors using `ZKHostStore` do not properly handle the fact that the ZK client is closed, and they throw `HostStoreException`:
```
2019-03-14 17:12:57,460 118861591 [EventProcessorGroupImpl STOPPING] WARN  i.p.c.e.i.EventProcessorGroupImpl - Error sealing reader group EventProcessorGroup[scaleGroup]
io.pravega.controller.store.checkpoint.CheckpointStoreException: org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /pravega/pravega/eventProcessors/YYY-2b26df87-4c14-4197-b522-7ebf2daed64f/scaleGroup
	at io.pravega.controller.store.checkpoint.ZKCheckpointStore.sealReaderGroup(ZKCheckpointStore.java:114)
	at io.pravega.controller.eventProcessor.impl.EventProcessorGroupImpl.shutDown(EventProcessorGroupImpl.java:164)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$2.run(AbstractIdleService.java:79)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /pravega/pravega/eventProcessors/YYY-2b26df87-4c14-4197-b522-7ebf2daed64f/scaleGroup
...
2019-03-14 17:12:59,803 118863934 [Delegate] WARN  i.p.c.e.impl.EventProcessorCell - Restarting event processor: EventProcessor[commitStreamReaders:0] due to exception: {}
io.pravega.controller.store.host.HostStoreException: Failed to fetch segment container map from zookeeper
	at io.pravega.controller.store.host.ZKHostStore.getCurrentHostMap(ZKHostStore.java:81)
	at io.pravega.controller.store.host.ZKHostStore.getHostForContainer(ZKHostStore.java:106)
	at io.pravega.controller.store.host.ZKHostStore.getHostForSegment(ZKHostStore.java:125)
Caused by: org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /pravega/pravega/cluster/segmentContainerHostMapping
```

4) In the presence of any exception during shutdown, the `ControllerServiceStarter` will terminate the process:
```
java.lang.IllegalStateException: Expected the service ControllerServiceMain [FAILED] to be TERMINATED, but the service has FAILED
```

Moreover, we have not detected this issue with the test added in `testZKSessionExpiry()` in `ZKControllerServiceMainTest` because the mock Controller being instantiated does not initialize event processors (i.e., `eventProcessorConfig(Optional.empty()`), as it would require to create also a segment store for the internal streams.

**Problem location**
Controller restart process.

**Suggestions for an improvement**
Handle the case of a full graceful restart when ZK session is expired.

**Comment by sumit-bm** [comment]
Related issue found during testing in Pravega Operator: https://github.com/pravega/pravega-operator/issues/138

**Comment by RaulGracia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Handle ZK-related exceptions from HostStore when shutting down Controller](https://trello.com/c/JhT7BxR2/153-handle-zk-related-exceptions-from-hoststore-when-shutting-down-controller)
