### ISSUE TITLE
Observing Pravega controller restart issue with "ReaderGroupStateManager.readerShutdown()" while closing the ReaderGroup

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega#3510]
While running IO work load for 1+ days (writer: 1, reader: 1, size: 100 bytes, events/sec: 1, segments: 1000, streams: 2)  experienced both controllers restart in Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.
[pravega-controller_logs.zip](https://github.com/pravega/pravega/files/2996326/pravega-controller_logs.zip)

Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Pravega version: zk-closed-client-issue-0.5.0-2161.60655bf
Zookeeper Operator : spiegela/zookeeper-operator:latest
Pravega Operator: adrianmo/pravega-operator:issue-134-5
```
Found Exceptions like following: -
```
2019-03-20 17:14:49,939 11357031 [Delegate] INFO  i.p.c.e.impl.EventProcessorCell - Event processor SHUTDOWN EventProcessor[scaleGroup:0], state=STOPPING
2019-03-20 17:14:49,939 11357031 [Delegate] INFO  i.p.c.e.impl.EventProcessorCell - Closing reader for EventProcessor[scaleGroup:0]
2019-03-20 17:14:49,939 11357031 [Delegate] INFO  i.p.c.s.impl.EventStreamReaderImpl - Closing reader EventStreamReaderImpl( id=df58a1ff-a799-4220-98af-2f1ad293c009)
2019-03-20 17:14:49,960 11357052 [Delegate] INFO  i.p.c.e.impl.EventProcessorCell - Event processor SHUTDOWN EventProcessor[abortStreamReaders:0], state=STOPPING
2019-03-20 17:14:49,960 11357052 [Delegate] INFO  i.p.c.e.impl.EventProcessorCell - Closing reader for EventProcessor[abortStreamReaders:0]
2019-03-20 17:14:49,960 11357052 [Delegate] INFO  i.p.c.s.impl.EventStreamReaderImpl - Closing reader EventStreamReaderImpl( id=c7ec643f-1286-443f-918d-99c2da052e14)
2019-03-20 17:15:03,638 11370730 [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background operation retry gave up
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:844)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:972)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:925)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:73)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:322)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by RaulGracia** [comment]
Thanks @SomeshJoshi19. This seems to be relates with the problem we exploring this problem here: #3477 and https://github.com/pravega/pravega-operator/issues/138. We added more logs to the point in which `EventProcessorCell` is closing the reader to understand how to fix this. The main problem seems to be that this error is preventing the Controller to gracefully restart upon a Zookeeper expiration error.

**Comment by RaulGracia** [comment]
The Controller is working fine until there is a session loss with ZK:
```
2019-03-20 17:14:18,530 11325622 [ControllerServiceMain-EventThread] WARN  o.a.z.client.StaticHostProvider - No IP address found for server: pravega-example-zk-client:2181
java.net.UnknownHostException: pravega-example-zk-client: Try again
...
2019-03-20 17:14:18,531 11325623 [Curator-PathChildrenCache-3] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background exception was not retry-able or retry gave up
java.lang.IllegalArgumentException: A HostProvider may not be empty!
```
Interestingly, the Controller is not able to resolve that name, or at least it has problems to work with the Zookeeper servers behind `zookeeper-client` load balancer. 

This has been recently mitigated by using the headless endpoints for the different Zookeeper nodes (`zkUri: zookeeper-0.headless...`) instead of the service endpoint (`zookeeper-client`). Apart from that, this issue looks related to the problems we are seeing in the Zookeeper operator to recover the cluster after pod deletions: https://github.com/pravega/zookeeper-operator/issues/72.
