### ISSUE TITLE
Sporadic travis build failure: ControllerServiceWithZKStreamTest 

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#3517]
**Problem description**
```
io.pravega.controller.server.ControllerServiceWithZKStreamTest > streamCutTests FAILED
    java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at io.pravega.controller.server.ControllerServiceWithZKStreamTest.testEmptyFrom(ControllerServiceWithZKStreamTest.java:414)
        at io.pravega.controller.server.ControllerServiceWithZKStreamTest.streamCutTests(ControllerServiceWithZKStreamTest.java:266)
        Caused by:
        java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
```

**Problem location**
ControllerServiceWithZKStreamTest 

**Suggestions for an improvement**
Fix the test

**Comment by shiveshr** [comment]
not able to reproduce. Closing the issue. Reopen if it surfaces again.
