### ISSUE TITLE
StreamSegmentContainerTests fails with unexpected exception

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#3538]
**Problem description**
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testWriteFenceOut FAILED
    java.lang.AssertionError: Original container did not reject an append operation after being fenced out. Exception thrown was of unexpected type: io.pravega.common.ObjectClosedException: Object 'BlockingDrainingQueue' has been closed and cannot be accessed anymore.
        at org.junit.Assert.fail(Assert.java:88)
        at io.pravega.test.common.AssertExtensions.assertSuppliedFutureThrows(AssertExtensions.java:118)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testWriteFenceOut(StreamSegmentContainerTests.java:1444)
```

**Problem location**
`StreamSegmentContainerTests.testWriteFenceOut`

**Suggestions for an improvement**
Add `ObjectClosedException` object closed exception to list of acceptable exceptions for the method to throw.

**Comment by derekm** [comment]
@tkaitchuck @andreipaduroiu -- I saw a timeout failure on this test in a travis build just now:
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testWriteFenceOut FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 100000 milliseconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
        at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
        at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
        at com.google.common.util.concurrent.Monitor.enterIf(Monitor.java:679)
        at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:264)
        at io.pravega.common.concurrent.Services.stopAsync(Services.java:61)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainer.close(StreamSegmentContainer.java:189)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests$TestContext.close(StreamSegmentContainerTests.java:2231)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testWriteFenceOut(StreamSegmentContainerTests.java:1492)
```
