### ISSUE TITLE
Bookie-0 shows - Error polling ZK for the available nodes

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#3569]
Deployed
Pravega-Operator image: pravega/pravega-operator:0.3.2
Pravega build used : 0.5.0-2189.cabe11b
Zookeeper-operator image: pravega/zookeeper-operator:0.2.1
Ran small i/o workload (Total - 4 readers, 3 writers, 120 events/sec, ~ 100 KB/sec IO)

Environment details: PKS / K8 with medium cluster:
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
10 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend 
```

See this error on bookie-0
```
2019-04-05 08:33:58,937 - ERROR - [main-EventThread:ZkUtils$6$1@279] - Error polling ZK for the available nodes:
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /pravega/pravega/bookkeeper/ledgers/00/0003
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:114)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at org.apache.bookkeeper.util.ZkUtils$6$1.processResult(ZkUtils.java:280)
        at org.apache.bookkeeper.zookeeper.ZooKeeperClient$30$1.processResult(ZooKeeperClient.java:1336)
        at org.apache.bookkeeper.zookeeper.ZooKeeperClient$29$1.processResult(ZooKeeperClient.java:1297)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:595)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:508)
2019-04-05 08:33:58,945 - INFO  - [bookie-io-1-2:BookieRequestHandler@61] - Channels disconnected: [id: 0x1563567f, L:/172.24.2.12:3181 ! R:/172.24.2.12:35426]

```

[bookie_logs.zip](https://github.com/pravega/pravega/files/3047489/bookie_logs.zip)

**Comment by RaulGracia** [comment]
This is an interaction between Zookeeper and Bookkeeper. While this can be a transient issue, one possibility to observe this error is a malfunctioning in the Zookeeper operator, which has been fixed here: https://github.com/pravega/zookeeper-operator/pull/69. Please, reproduce this experiment using the latest Zookeeper image published in the Pravega dockerhub and re-open the issue if you see the error again. If so, please add more details on the workload used as well as the severity of the problem (e.g., if IO is still working).
