### ISSUE TITLE
Sporadic unit test failure: BasicMetricTest.testOpStatsLoggerCreationException

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#3573]
**Problem description**
```
io.pravega.shared.metrics.BasicMetricTest > testOpStatsLoggerCreationException FAILED
    java.util.ConcurrentModificationException
        at java.util.IdentityHashMap$IdentityHashMapIterator.nextIndex(IdentityHashMap.java:735)
        at java.util.IdentityHashMap$KeyIterator.next(IdentityHashMap.java:826)
        at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
        at io.pravega.shared.metrics.StatsProviderImpl.startWithoutExporting(StatsProviderImpl.java:74)
        at io.pravega.shared.metrics.StatsProviderProxy.startWithoutExporting(StatsProviderProxy.java:45)
        at io.pravega.shared.metrics.BasicMetricTest.setUp(BasicMetricTest.java:33)
```

**Problem location**

**Suggestions for an improvement**

**Comment by kevinhan88** [comment]
Per @andreipaduroiu - problem triggered by `./gradlew check` on local computer,

**Comment by kevinhan88** [comment]
The failure happened in master branch, just to be clear as there are some issues on r0.5 meanwhile.
