### ISSUE TITLE
Critical failure for SegmentContainer after running IO for more than 3d17h.

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#3584]
**Problem description**
Following Error was found in Segment store after running small IO for more than 3d.

Deployment details:
Pravega-Operator image: pravega/pravega-operator:0.3.2
Pravega build used : 0.5.0-2189.cabe11b
Zookeeper-operator image: pravega/zookeeper-operator:0.2.1
Ran small i/o workload (Total - 4 readers, 3 writers, 120 events/sec, ~ 100 KB/sec IO)

Environment details: PKS / K8 with medium cluster:

```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
10 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
``` 
Following is the Segment store logs:

```
2019-04-05 15:06:35,133 15327639 [core-17] INFO  i.p.s.s.s.StreamSegmentContainerRegistry - Unregistered SegmentContainer 0.
2019-04-05 15:06:35,133 15327639 [core-17] ERROR i.p.s.s.s.StreamSegmentContainerRegistry - Critical failure for SegmentContainer Container Id = 0, State = FAILED. {}
io.pravega.segmentstore.contracts.StreamingException: OperationProcessor stopped unexpectedly (no error) but DurableLog was not currently stopping.
        at io.pravega.segmentstore.server.logs.DurableLog.queueStoppedHandler(DurableLog.java:405)
        at io.pravega.common.concurrent.Services$ShutdownListener.terminated(Services.java:120)
        at com.google.common.util.concurrent.AbstractService$3.call(AbstractService.java:95)
        at com.google.common.util.concurrent.AbstractService$3.call(AbstractService.java:92)
        at com.google.common.util.concurrent.ListenerCallQueue$PerListenerQueue.run(ListenerCallQueue.java:205)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: io.pravega.segmentstore.storage.DurableDataLogException: General exception while accessing BookKeeper.
                at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.handleWriteException(BookKeeperLog.java:638)
                at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.addCallback(BookKeeperLog.java:570)
                at org.apache.bookkeeper.client.AsyncCallback$AddCallback.addCompleteWithLatency(AsyncCallback.java:91)
                at org.apache.bookkeeper.client.PendingAddOp.submitCallback(PendingAddOp.java:361)
                at org.apache.bookkeeper.client.LedgerHandle.errorOutPendingAdds(LedgerHandle.java:1546)
                at org.apache.bookkeeper.client.LedgerHandle$5.safeRun(LedgerHandle.java:523)
                at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                ... 1 common frames omitted
        Caused by: org.apache.bookkeeper.client.BKException$ZKException: Error while using ZooKeeper
                at org.apache.bookkeeper.client.BKException.create(BKException.java:74)
                at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.handleWriteException(BookKeeperLog.java:618)
                ... 10 common frames omitted
2019-04-05 15:06:36,951 15329457 [CacheManager RUNNING] INFO  i.p.s.server.CacheManager - CacheManager Current Generation = 3030, Oldest Generation = 3030, Clients = 53,  CacheSize = 0 MB
2019-04-05 15:06:36,970 15329476 [main-SendThread(pravega-zk-client:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server pravega-zk-client/10.100.200.28:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-05 15:06:36,971 15329477 [main-SendThread(pravega-zk-client:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /172.24.2.19:60006, server: pravega-zk-client/10.100.200.28:2181
2019-04-05 15:06:36,974 15329480 [main-SendThread(pravega-zk-client:2181)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server pravega-zk-client/10.100.200.28:2181, sessionid = 0x1001048838d0041, negotiated timeout = 10000
2019-04-05 15:06:36,974 15329480 [main-EventThread] INFO  o.a.b.z.ZooKeeperWatcherBase - ZooKeeper client is connected now.
2019-04-05 15:06:41,670 15334176 [main-SendThread(172.24.2.5:2181)] WARN  org.apache.zookeeper.ClientCnxn - Client session timed out, have not heard from server in 6669ms for sessionid 0x30011363a830000
2019-04-05 15:06:41,670 15334176 [main-SendThread(172.24.2.5:2181)] INFO  org.apache.zookeeper.ClientCnxn - Client session timed out, have not heard from server in 6669ms for sessionid 0x30011363a830000, closing socket connection and attempting reconnect
2019-04-05 15:06:41,770 15334276 [main-EventThread] INFO  o.a.c.f.s.ConnectionStateManager - State change: SUSPENDED
2019-04-05 15:06:41,876 15334382 [main-SendThread(pravega-zk-client:2181)] INFO  org.apache.zookeeper.ClientCnxn - Unable to read additional data from server sessionid 0x1001048838d0041, likely server has closed socket, closing socket connection and attempting reconnect
2019-04-05 15:06:41,884 15334390 [epollEventLoopGroup-11-5] WARN  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=71086003716096] Wrong host. Segment = 'longevity/smallScale/2944.#epoch.1920' (Container 0) is not owned. Operation = 'readSegment').
```
Raising this issue in continuation of previous issue:
[(https://github.com/pravega/pravega/issues/2818)]

**Comment by andreipaduroiu** [comment]
ZooKeeper failed, thus BookKeeper failed and we couldn't write. This is a transient issue and would have gone back to normal once ZooKeeper was available again.
