### ISSUE TITLE
Segment store Error: Unable to close LedgerHandle for Ledger

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#3585]
> Problem Description

After running small IO on following cluster for more than 3d:

Deployment details:
Pravega-Operator image: pravega/pravega-operator:0.3.2
Pravega build used : 0.5.0-2189.cabe11b
Zookeeper-operator image: pravega/zookeeper-operator:0.2.1
Ran small i/o workload (Total - 4 readers, 3 writers, 120 events/sec, ~ 100 KB/sec IO)

Environment details: PKS / K8 with medium cluster:
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
10 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Following is the Segment store logs:

```
2019-04-05 15:07:35,833 15388339 [core-24] ERROR i.p.s.s.i.bookkeeper.BookKeeperLog - Log[4]: Unable to close LedgerHandle for Ledger 35536.
io.pravega.segmentstore.storage.DurableDataLogException: Unable to close ledger 35536.
        at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.close(Ledgers.java:132)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.close(BookKeeperLog.java:174)
        at io.pravega.segmentstore.server.logs.DurableLog.lambda$doStop$5(DurableLog.java:249)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.bookkeeper.client.BKException$BKMetadataVersionException: Bad ledger metadata version
        at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:83)
        at org.apache.bookkeeper.client.SyncCallbackUtils$SyncCloseCallback.closeComplete(SyncCallbackUtils.java:298)
        at org.apache.bookkeeper.client.LedgerHandle$5$1CloseCb$1.safeOperationComplete(LedgerHandle.java:568)
        at org.apache.bookkeeper.client.LedgerHandle$5$1CloseCb$1.safeOperationComplete(LedgerHandle.java:539)
        at org.apache.bookkeeper.util.OrderedGenericCallback$1.safeRun(OrderedGenericCallback.java:61)
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 common frames omitted

```

**Comment by RaulGracia** [comment]
This test is 100 commits behind the current version of `0.5`. Among others, since the version used in this experiment there have been important fixes in the Zookeeper membership management, as well as a fix for Bookkeeper metadata versioning. Please, try to reproduce the problem with the upcoming release candidate and re-open the issue if the problem persists.
