### ISSUE TITLE
Sporadic failure: EndToEndTruncationTest timedout while closing writer : SegmentOutputStreamImpl.flush

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#3598]
**Problem description**
```
io.pravega.test.integration.endtoendtest.EndToEndTruncationTest > testWriteDuringScaleAndTruncation FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 50000 milliseconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at io.pravega.common.concurrent.Futures.getThrowingException(Futures.java:152)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl.flush(SegmentOutputStreamImpl.java:497)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl.close(SegmentOutputStreamImpl.java:480)
        at io.pravega.client.stream.impl.EventStreamWriterImpl.close(EventStreamWriterImpl.java:387)
        at io.pravega.test.integration.endtoendtest.EndToEndTruncationTest.testWriteDuringScaleAndTruncation(EndToEndTruncationTest.java:326)
```

The test timesout while closing the writer, where it is flushing all unsent events. 

**Problem location**
SegmentOutputStreamImpl.flush

**Suggestions for an improvement**
Fix the issue

**Comment by shrids** [comment]
Closing this issue as I am not able to simulate this error on the latest master even after 500+ iterations.
Also, we have not seen this issue in the recent past.
