### ISSUE TITLE
Sporadic unit test failure: ReadTest : readThroughStreamClient 

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#3613]
**Problem description**
```
io.pravega.test.integration.ReadTest > readThroughStreamClient FAILED
    java.lang.AssertionError: expected:<Hello world
    > but was:<null>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.pravega.test.integration.ReadTest.readThroughStreamClient(ReadTest.java:288)
```

**Problem location**
ReadTest

**Suggestions for an improvement**
Fix the sporadic nature of test

**Comment by shrids** [comment]
Tried verifying this issue with the latest master and  different environment settings (to mimick our travis/jenkins setup). Not able to simulate this issue after running it for couple of hours . Also, we have not observed this issue in the latest builds of Pravega.

Closing this issue based on the above points.
