### ISSUE TITLE
BookieFailoverTest is failing consistently in docker swarm environment

### ISSUE THREAD

**Issue by anishakj** [pravega/pravega#3630]
**Problem description**
1. Test is started with 3 bookie instances
2. Scaling down the bookie instances to `2`  is successful
Issue:
 writes are not failing even if the bookies are scaled down to `2`.
Build used:  `Pravega ​Version: ​0.5.0-2216.23be70a`
Logs:
```
2019-04-15 06:02:58,359 59050 [BookieFailoverTest-main-5] DEBUG i.p.t.system.AbstractReadWriteTest - Event write count 2232
2019-04-15 06:02:58,362 59053 [epollEventLoopGroup-4-1] TRACE i.p.s.protocol.netty.CommandEncoder - Encoding message to send over the wire io.pravega.shared.protocol.netty.CommandEncoder$BlockTimeout@84c355b
2019-04-15 06:02:58,363 59054 [Time-limited test] INFO  i.p.test.system.BookieFailoverTest - Write count is 2232 after 20 seconds sleep after bookie failover.
2019-04-15 06:02:58,363 59054 [Time-limited test] INFO  i.p.test.system.BookieFailoverTest - Sleeping for 20 seconds.
2019-04-15 06:02:58,367 59058 [BookieFailoverTest-main-2] DEBUG i.p.t.system.AbstractReadWriteTest - Event write count before write call 2232
2019-04-15 06:02:58,367 59058 [BookieFailoverTest-main-2] TRACE i.p.c.s.i.SegmentOutputStreamImpl - Adding event 31 to inflight on writer 4ecfd1f2-ca65-4fd8-9233-b40afeb85d5d
2019-04-15 06:02:58,367 59058 [BookieFailoverTest-main-2] TRACE i.p.c.s.i.SegmentOutputStreamImpl - Sending append request: Append(segment=testBookieFailoverScope102988181/testBookieFailoverStream/1.#epoch.0, writerId=4ecfd1f2-ca65-4fd8-9233-b40afeb85d5d, eventNumber=31, eventCount=1, data=CompositeByteBuf(ridx: 0, widx: 54, cap: 54, components=2), expectedLength=null, flowId=8589934592)
2019-04-15 06:02:58,367 59058 [epollEventLoopGroup-4-1] TRACE i.p.s.protocol.netty.CommandEncoder - Encoding message to send over the wire Append(segment=testBookieFailoverScope102988181/testBookieFailoverStream/1.#epoch.0, writerId=4ecfd1f2-ca65-4fd8-9233-b40afeb85d5d, eventNumber=31, eventCount=1, data=CompositeByteBuf(ridx: 0, widx: 54, cap: 54, components=2), expectedLength=null, flowId=8589934592)
2019-04-15 06:02:58,367 59058 [BookieFailoverTest-main-2] DEBUG i.p.t.system.AbstractReadWriteTest - Event write count before flush 2232

loverStream/4.#epoch.0, offset=33495, suggestedLength=1048521, delegationToken=, requestId=266287972352)
2019-04-15 06:03:18,363 79054 [Time-limited test] INFO  i.p.test.system.BookieFailoverTest - Write count is 3175 after 40 seconds sleep after bookie failover.
2019-04-15 06:03:18,363 79054 [Time-limited test] ERROR i.p.t.system.AbstractReadWriteTest - Read write count mismatch => readCount = 3106, writeCount = 3175
2019-04-15 06:03:18,364 79055 [Time-limited test] ERROR i.p.t.system.AbstractReadWriteTest - Error while reading events:
java.util.concurrent.CancellationException: null
        at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
        at io.pravega.test.system.AbstractReadWriteTest$TestState.lambda$cancelAllPendingWork$0(AbstractReadWriteTest.java:153)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062)
        at io.pravega.test.system.AbstractReadWriteTest$TestState.cancelAllPendingWork(AbstractReadWriteTest.java:151)
        at io.pravega.test.system.BookieFailoverTest.tearDown(BookieFailoverTest.java:138)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:745)
```
Complete logs are available at Jenkins build `https://asd-nautilus-jenkins.isus.emc.com/view/Pravega/job/docker-test-pravega-continuous/137/`
**Problem location**
Docker swarm system tests

**Suggestions for an improvement**

**Comment by shrids** [comment]
`bookkeeper.bkAckQuorumSize` should configured to 3 for the test to pass.
Could check the property on the SSS?

**Comment by anishakj** [comment]
After changing `bkAckQuorumSize` to `3` writes are not performed while scaling down. But test is failing to bring the bookie instances to `3`
bookie logs:
```
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | 2019-04-15 10:07:04,742 - INFO  - [main:Environment@100] - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | 2019-04-15 10:07:04,742 - INFO  - [main:Environment@100] - Client environment:java.io.tmpdir=/tmp
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | 2019-04-15 10:07:04,742 - INFO  - [main:Environment@100] - Client environment:java.compiler=<NA>
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | 2019-04-15 10:07:04,742 - INFO  - [main:Environment@100] - Client environment:os.name=Linux
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | 2019-04-15 10:07:04,743 - INFO  - [main:Environment@100] - Client environment:os.arch=amd64
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | 2019-04-15 10:07:04,743 - INFO  - [main:Environment@100] - Client environment:os.version=3.10.0-693.17.1.el7.x86_64
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | 2019-04-15 10:07:04,743 - INFO  - [main:Environment@100] - Client environment:user.name=bookkeeper
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | 2019-04-15 10:07:04,743 - INFO  - [main:Environment@100] - Client environment:user.home=/home/bookkeeper
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | 2019-04-15 10:07:04,743 - INFO  - [main:Environment@100] - Client environment:user.dir=/opt/bookkeeper
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | 2019-04-15 10:07:04,744 - INFO  - [main:ZooKeeper@442] - Initiating client connection, connectString=10.0.0.27:2181 sessionTimeout=10000 watcher=org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase@41fecb8b
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | 2019-04-15 10:07:04,756 - INFO  - [main-SendThread(zookeeper.1.ncjwom1f75csdx0f0jwmrd3o7.docker-network:2181):ClientCnxn$SendThread@1029] - Opening socket connection to server zookeeper.1.ncjwom1f75csdx0f0jwmrd3o7.docker-network/10.0.0.27:2181. Will not attempt to authenticate using SASL (unknown error)
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | 2019-04-15 10:07:04,760 - INFO  - [main-SendThread(zookeeper.1.ncjwom1f75csdx0f0jwmrd3o7.docker-network:2181):ClientCnxn$SendThread@879] - Socket connection established to zookeeper.1.ncjwom1f75csdx0f0jwmrd3o7.docker-network/10.0.0.27:2181, initiating session
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | 2019-04-15 10:07:04,764 - INFO  - [main-SendThread(zookeeper.1.ncjwom1f75csdx0f0jwmrd3o7.docker-network:2181):ClientCnxn$SendThread@1303] - Session establishment complete on server zookeeper.1.ncjwom1f75csdx0f0jwmrd3o7.docker-network/10.0.0.27:2181, sessionid = 0x100fb687aed004a, negotiated timeout = 10000
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | 2019-04-15 10:07:04,765 - INFO  - [main-EventThread:ZooKeeperWatcherBase@130] - ZooKeeper client is connected now.
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | 2019-04-15 10:07:04,833 - INFO  - [main:BookieNettyServer@396] - Shutting down BookieNettyServer
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | 2019-04-15 10:07:04,872 - ERROR - [main:Main@221] - Failed to build bookie server
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | org.apache.bookkeeper.bookie.BookieException$InvalidCookieException: Cookie [4
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | bookieHost: "10.0.0.40:3181"
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | journalDir: "/bk/journal"
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | ledgerDirs: "1\t/bk/ledgers"
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | instanceId: "2f031a53-b882-4f7d-a69a-c7e0ff872321"
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | ] is not matching with [4
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | bookieHost: "10.0.0.31:3181"
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | journalDir: "/bk/journal"
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | ledgerDirs: "1\t/bk/ledgers"
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | instanceId: "2f031a53-b882-4f7d-a69a-c7e0ff872321"
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    | ]
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    |         at org.apache.bookkeeper.bookie.Cookie.verifyInternal(Cookie.java:136)
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    |         at org.apache.bookkeeper.bookie.Cookie.verify(Cookie.java:147)
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    |         at org.apache.bookkeeper.bookie.Bookie.verifyAndGetMissingDirs(Bookie.java:376)
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    |         at org.apache.bookkeeper.bookie.Bookie.checkEnvironmentWithStorageExpansion(Bookie.java:445)
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    |         at org.apache.bookkeeper.bookie.Bookie.checkEnvironment(Bookie.java:257)
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    |         at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:641)
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    |         at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:131)
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    |         at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:100)
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    |         at org.apache.bookkeeper.server.service.BookieService.<init>(BookieService.java:43)
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    |         at org.apache.bookkeeper.server.Main.buildBookieServer(Main.java:299)
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    |         at org.apache.bookkeeper.server.Main.doMain(Main.java:219)
bookkeeper.3.xwzu2x6alb9v@redhook-master-2    |         at org.apache.bookkeeper.server.Main.main(Main.java:201)
```

**Comment by adrianmo** [comment]
@anishakj this is issue is related to https://github.com/pravega/pravega-operator/issues/116. The problem is that the bookie is trying to reuse its identity from the data volumes when it is recreated, but it's facing conflicts because the IP address has changed. Going forward, we want bookies to use their host name instead of their IP address as their identifier so that they can safely reuse their identify and data.

This did not happening before (Pravega <= 0.4) because bookies performed a data and metadata format when they were recreated.

You can configure the bookies to use their host name as bookie ID as below:

```
...
services:
  bookkeeper:
    image: pravega/bookkeeper
    environment:
      ZK_URL: ${ZK_URL:-zookeeper:2181}
      BK_useHostNameAsBookieID: true
    deploy:
      replicas: 3
...
```
