### ISSUE TITLE
pravega-segmentstore Issue :- Throwing IOException: Bad file descriptor

### ISSUE THREAD

**Issue by Ranjan-Padhi** [pravega/pravega#3646]
Observing IOException (i.p.s.server.writer.StorageWriter - StorageWriter[1]: Iteration[1].Error. java.io.IOException: Bad file descriptor) after deploying pravega segmentstore. There is no IO running background

Deployment Details:-
```
bookkeeper:0.5.0-2222.8ba5431
pravega:0.5.0-2222.8ba5431
zookeeper:3.5.4-beta-operator
pravega/pravega-operator:0.3.2
pravega/zookeeper-operator:0.2.1
```

Environment details: PKS / K8 with medium cluster:
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```

POD Details
```
NAMESPACE     NAME                                                 READY     STATUS      RESTARTS   AGE
default       pravega-bookie-0                                     1/1       Running     0          35m
default       pravega-bookie-1                                     1/1       Running     0          35m
default       pravega-bookie-2                                     1/1       Running     0          35m
default       pravega-bookie-3                                     1/1       Running     0          35m
default       pravega-operator-779879b48-fj8h7                     1/1       Running     0          36m
default       pravega-pravega-controller-84948d8895-fhw8m          1/1       Running     0          35m
default       pravega-pravega-controller-84948d8895-h6drh          1/1       Running     0          35m
default       pravega-pravega-segmentstore-0                       1/1       Running     0          35m
default       pravega-pravega-segmentstore-1                       1/1       Running     0          34m
default       pravega-pravega-segmentstore-2                       1/1       Running     0          33m
default       pravega-zk-0                                         1/1       Running     0          1h
default       pravega-zk-1                                         1/1       Running     0          1h
default       pravega-zk-2                                         1/1       Running     0          1h
default       pravega-zk-3                                         1/1       Running     0          1h
default       shaka-zulu-nfs-client-provisioner-59d7f8f84c-jrxkz   1/1       Running     0          38m
default       zookeeper-operator-685bfcbbc5-twxkm                  1/1       Running     0          1h
```
SegmentStore Log
```
R:/172.24.75.9:57030]
2019-04-17 13:33:33,109 12656 [epollEventLoopGroup-11-4] INFO  i.p.s.server.CacheManager - CacheManager Registered ReadIndex[4-36] (_system/_requeststream/0.#epoch.0).
2019-04-17 13:33:33,519 13066 [storage-io-2] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[1-1]: State changed from NotInitialized to Closed.
2019-04-17 13:33:33,520 13067 [storage-io-2] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[1]: Iteration[1].Error.
java.io.IOException: Bad file descriptor
        at sun.nio.ch.FileDispatcherImpl.pread0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.pread(FileDispatcherImpl.java:52)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:220)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:741)
        at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:727)
        at io.pravega.storage.filesystem.FileSystemStorage.doRead(FileSystemStorage.java:245)
        at io.pravega.storage.filesystem.FileSystemStorage.lambda$read$1(FileSystemStorage.java:129)
        at io.pravega.storage.filesystem.FileSystemStorage.execute(FileSystemStorage.java:405)
        at io.pravega.storage.filesystem.FileSystemStorage.read(FileSystemStorage.java:129)
        at io.pravega.segmentstore.storage.rolling.RollingStorage.readHeader(RollingStorage.java:714)
        at io.pravega.segmentstore.storage.rolling.RollingStorage.openHandle(RollingStorage.java:668)
        at io.pravega.segmentstore.storage.rolling.RollingStorage.openWrite(RollingStorage.java:289)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$openWrite$0(AsyncStorageWrapper.java:83)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-04-17 13:33:33,563 13110 [core-27] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[16-1]: SegmentMetadata has a StorageLength (0) that is different than the actual one (385) - updating metadata.
2019-04-17 13:33:33,563 13110 [core-27] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[16-1]: Initialized. StorageLength = 385, Sealed = false.
2019-04-17 13:33:33,563 13110 [core-27] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[16-1]: State changed from NotInitialized to Writing.
``

**Comment by Ranjan-Padhi** [comment]
[pravega-segmentstore-2.txt](https://github.com/pravega/pravega/files/3090109/pravega-segmentstore-2.txt)

**Comment by Ranjan-Padhi** [comment]
[kubectl-get-po-svc-pvc-all-namespace_output.zip](https://github.com/pravega/pravega/files/3090115/kubectl-get-po-svc-pvc-all-namespace_output.zip)

**Comment by adrianmo** [comment]
@Ranjan-Padhi I've checked the configuration and it looks good. Also, judging from the logs, the segment store seems to keep working normally. Is this error log causing Pravega not to work?

**Comment by andreipaduroiu** [comment]
It can't tell from the logs if this persists or if it goes away. I do see it for 3 different files though, but other files at the same time work well.

**Comment by sumit-bm** [comment]
@andreipaduroiu @adrianmo This issue is related to exception handling, code should not throw exceptions and it would take care softly rather than showing java traces. If proper logs are not there i would suggest have more logging in private code and fix the issue / get into code base and see why code is throwing exception and handle it properly. These issues are not very likelihood of functionality breakage and more towards how customer would see a look and feel of the product.

**Comment by andreipaduroiu** [comment]
@sumit-bm I never said proper logs are not there. What I said is that the snippet provided is insufficient to determine if this is a transient issue or not. You need to provide a longer timespan of logs to do a proper determination.

**Comment by sumit-bm** [comment]
@andreipaduroiu I think Ranjan placed complete log in `kubectl-get-po-svc-pvc-all-namespace_output.zip`. This is complete log of all pods, till the point exception came and I see there are segementstore logs are present. This might be useful to understand what happens in longer timespan of things and you will see what all sequences happened before and after of the scenario. Please let us know if this would be sufficient to find exception cause and softly handle it.

**Comment by sachin-j-joshi** [comment]
The exception is coming from the NFS provider and usually seen during directory mounting. (i.e during pod setup itself.) 
It does not look like this issue is caused by or is a result of any specific operations performed by Pravega code. 
iava. nio is bubbling this exception and the pravega code is faithfully reporting this exception in logs. 
This is a transient issue and system successfully recovers from this exception. 
I do not think we should hide this exception. (At the time we encountered it, it is a legitimate IO Error).

**Comment by sumit-bm** [comment]
@sachin-j-joshi Thanks for detailed explanation. We would not like to hide any exception but could we soft handle it rather than just publishing the stack trace to our customer?

**Comment by andreipaduroiu** [comment]
Same as #3748. Let's continue the discussion there.

**Comment by sachin-j-joshi** [comment]
To be correct the IO related issue is captured here #3747.
