### ISSUE TITLE
Exception in CommandEncoder

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#3657]
**Problem description**
CommandEncoder.encode when dealing with an append, validates that the append has enough room to write a header in the current block. That is occasionally failing resulting in a connection drop. The exception is:
```
WARN  i.p.c.s.i.SegmentOutputStreamImpl - Connection c91d5970-ac09-4c93-8587-5d8aafe25878 failed due to: 
io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Bug in CommandEncoder.encode, block is too small.
    at io.pravega.common.concurrent.Futures.getAndHandleExceptions(Futures.java:180)
    at io.pravega.client.netty.impl.ClientConnectionImpl.send(ClientConnectionImpl.java:60)
    at io.pravega.client.segment.impl.SegmentOutputStreamImpl.write(SegmentOutputStreamImpl.java:444)
    at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEventInternal(EventStreamWriterImpl.java:122)
    at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEvent(EventStreamWriterImpl.java:106)
    at io.pravega.test.system.AbstractReadWriteTest.lambda$startWriting$1(AbstractReadWriteTest.java:189)
    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Bug in CommandEncoder.encode, block is too small.
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
    at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
    at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081)
    at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1128)
    at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    ... 1 common frames omitted
Caused by: java.lang.IllegalStateException: Bug in CommandEncoder.encode, block is too small.
    at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
    at io.pravega.shared.protocol.netty.CommandEncoder.validateAppend(CommandEncoder.java:158)
    at io.pravega.shared.protocol.netty.CommandEncoder.encode(CommandEncoder.java:89)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
    ... 12 common frames omitted
```

**Problem location**
CommandEncoder.validateAppend

**Suggestions for an improvement**

**Comment by tkaitchuck** [comment]
This appears to be caused by an earlier exception:
```
[epollEventLoopGroup-4-2] WARN  i.p.c.s.i.SegmentOutputStreamImpl - bd8adb12-c26a-453f-8831-1bd081429fa2 Failed to connect: 
java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:874)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl$State.failConnection(SegmentOutputStreamImpl.java:202)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl$State.access$700(SegmentOutputStreamImpl.java:94)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl.failConnection(SegmentOutputStreamImpl.java:516)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl.access$500(SegmentOutputStreamImpl.java:68)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl$ResponseProcessor.lambda$appendSetup$1(SegmentOutputStreamImpl.java:366)
	at io.pravega.client.netty.impl.ClientConnectionImpl.lambda$sendAsync$1(ClientConnectionImpl.java:108)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.util.concurrent.PromiseCombiner.tryPromise(PromiseCombiner.java:126)
	at io.netty.util.concurrent.PromiseCombiner.finish(PromiseCombiner.java:121)
	at io.pravega.client.netty.impl.ClientConnectionImpl.sendAsync(ClientConnectionImpl.java:110)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl$ResponseProcessor.appendSetup(SegmentOutputStreamImpl.java:362)
	at io.pravega.shared.protocol.netty.WireCommands$AppendSetup.process(WireCommands.java:666)
	at io.pravega.shared.protocol.netty.ReplyProcessor.process(ReplyProcessor.java:20)
	at io.pravega.client.netty.impl.FlowHandler.lambda$channelRead$2(FlowHandler.java:204)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.pravega.client.netty.impl.FlowHandler.channelRead(FlowHandler.java:202)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0
	... 42 common frames omitted
Caused by: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:704)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1056)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:290)
	at io.pravega.client.netty.impl.ClientConnectionImpl.sendAsync(ClientConnectionImpl.java:102)
	... 34 common frames omitted
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1446)
	at io.netty.buffer.AbstractByteBuf.slice(AbstractByteBuf.java:1216)
	at io.netty.buffer.AbstractByteBuf.slice(AbstractByteBuf.java:1206)
	at io.pravega.shared.protocol.netty.CommandEncoder.encode(CommandEncoder.java:108)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	... 42 common frames omitted
```
