### ISSUE TITLE
DataCorruptionException in all Segment Stores after running long term IO for more than 3 days.

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#3664]
**Problem description**
I started long term IO operation with following configurations for more than 3 days:

IO workload (Total - 4 readers, 3 writers, 120 events/sec, ~ 100 KB/sec IO)
After 3 days, Read operation failed with following exceptions in all the segment stores:

```
2019-04-22 07:43:10,511 251793424 [core-17] ERROR i.p.s.s.s.StreamSegmentContainerRegistry - Critical failure for SegmentContainer Container Id = 1, State = FAILED. {}
io.pravega.segmentstore.server.DataCorruptionException: Segment 'longevity/smallScale/1593.#epoch.1037' is sealed in Storage but not in the metadata.
        at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$initialize$0(SegmentAggregator.java:274)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
Environment details: PKS / K8 with medium cluster:

```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
5 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Deployment Details:

```
Pravega-Operator image: pravega/pravega-operator:0.3.2
Pravega build used : 0.5.0-2222.8ba5431
Zookeeper-operator image: pravega/zookeeper-operator:0.2.1
```
Following are the Cluster details:

```
root@osboxes:/home/osboxes# kubectl get po
NAME                                                 READY     STATUS    RESTARTS   AGE
pravega-bookie-0                                     1/1       Running   0          2d
pravega-bookie-1                                     1/1       Running   0          4d
pravega-bookie-2                                     1/1       Running   0          4d
pravega-bookie-3                                     1/1       Running   0          4d
pravega-operator-779879b48-6j28t                     1/1       Running   0          4d
pravega-pravega-controller-84948d8895-k6mrm          1/1       Running   1          2d
pravega-pravega-controller-84948d8895-krxpq          1/1       Running   2          4d
pravega-pravega-segmentstore-0                       1/1       Running   0          2d
pravega-pravega-segmentstore-1                       1/1       Running   0          2d
pravega-pravega-segmentstore-2                       1/1       Running   0          2d
pravega-zk-0                                         1/1       Running   0          2d
pravega-zk-1                                         0/1       Running   0          4d
pravega-zk-2                                         0/1       Running   0          4d
pravega-zk-3                                         0/1       Running   0          4d
shaka-zulu-nfs-client-provisioner-59d7f8f84c-942d2   1/1       Running   0          4d
zookeeper-operator-685bfcbbc5-wzchs                  1/1       Running   0          4d
```
Logs for all the Pravega Pods are available in DataCorruptionAllPodsLog.zip

**Comment by andreipaduroiu** [comment]
Do you have a link to the log file?

**Comment by sumit-bm** [comment]
@andreipaduroiu I have posted it in slack due to size of the log is quite big

**Comment by andreipaduroiu** [comment]
This was accompanied by some `IO Errors` coming out of Tier 2. If we still see this after we resolve our Isilon Tier 2 problems then we can reopen it.
