### ISSUE TITLE
All pravega-segmentstores are showing IllegalArgumentException frequently after starting IO client

### ISSUE THREAD

**Issue by Ranjan-Padhi** [pravega/pravega#3665]
Observing **IllegalArgumentException** execption frequently in all segmentstores(ERROR i.p.s.server.writer.StorageWriter - StorageWriter[28]: Iteration[9873].Error.) after starting IO client

It looks like after starting IO client all the segmentstores start throwing below exceptions and due to this after some time all readers are move to dead state

Deployment Details:-

```
bookkeeper:0.5.0-2222.8ba5431
pravega:0.5.0-2222.8ba5431
zookeeper:3.5.4-beta-operator
pravega-operator:0.3.2
zookeeper-operator:0.2.1
```

Environment details: PKS / K8 with medium cluster:

```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Segmentstore Exception log, For complete log please find the attachment
```
2019-04-19 13:03:26,584 1698786 [storage-io-104] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[28]: Iteration[9875].Error.
java.lang.IllegalArgumentException: Offset 213617384 + length 34960256 is beyond the last offset 213617384 of the segment.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:458)
        at io.pravega.segmentstore.storage.rolling.RollingStorage.read(RollingStorage.java:151)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$read$8(AsyncStorageWrapper.java:128)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-04-19 13:03:28,098 1700300 [core-20] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[28]: Iteration[9876].Error.
java.lang.IllegalArgumentException: Offset 213617384 + length 34960256 is beyond the last offset 213617384 of the segment.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:458)
        at io.pravega.segmentstore.storage.rolling.RollingStorage.read(RollingStorage.java:151)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$read$8(AsyncStorageWrapper.java:128)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-04-19 13:03:28,212 1700414 [core-1] INFO  i.p.s.server.logs.DurableLog - DurableLog[28]: MetadataCheckpointOperation durably stored.

2019-04-19 13:12:57,420 2269622 [epollEventLoopGroup-11-3] INFO  i.p.s.s.h.handler.AppendProcessor - Received hello from connection: [id: 0xf5f8bafe, L:/172.24.75.15:12345 - R:/172.24.114.3:56706]
2019-04-19 13:12:57,420 2269622 [epollEventLoopGroup-11-3] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: 29c1b333-1cad-44c2-b8f2-a772de3ef543 on segment: longevity/smallKey/0.#epoch.0
2019-04-19 13:12:57,423 2269625 [epollEventLoopGroup-11-3] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection:
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
        at io.pravega.shared.protocol.netty.WireCommandType.readFrom(WireCommandType.java:122)
        at io.pravega.shared.protocol.netty.CommandDecoder.parseCommand(CommandDecoder.java:55)
        at io.pravega.shared.protocol.netty.CommandDecoder.decode(CommandDecoder.java:36)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
        ... 26 common frames omitted
2019-04-19 13:12:57,424 2269626 [epollEventLoopGroup-11-3] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection:
io.netty.handler.codec.DecoderException: io.pravega.shared.protocol.netty.InvalidMessageException: Unknown wire command: -1393754107
```

**Comment by Ranjan-Padhi** [comment]
[segmentstore_2019-04-19.0.log](https://github.com/pravega/pravega/files/3103207/segmentstore_2019-04-19.0.log)

**Comment by andreipaduroiu** [comment]
I saw a few instances of this for different containers and segments, but all exhibit the same pattern:

1. An unknown IO error during Tier 2 write:
```
2019-04-19 13:43:56,567 4128769 [storage-io-144] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[30]: Iteration[23003].Error.
java.io.IOException: I/O error
	at sun.nio.ch.FileDispatcherImpl.force0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.force(FileDispatcherImpl.java:76)
	at sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:388)
	at io.pravega.storage.filesystem.FileSystemStorage.doWrite(FileSystemStorage.java:323)
	at io.pravega.storage.filesystem.FileSystemStorage.lambda$write$6(FileSystemStorage.java:155)
	at io.pravega.storage.filesystem.FileSystemStorage.execute(FileSystemStorage.java:405)
	at io.pravega.storage.filesystem.FileSystemStorage.write(FileSystemStorage.java:155)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.write(RollingStorage.java:323)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$write$2(AsyncStorageWrapper.java:93)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$runAsync$12(AsyncStorageWrapper.java:171)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
```

2. Then the Storage Writer encounters a BadOffsetException.
```
2019-04-19 13:43:57,572 4129774 [storage-io-79] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[30]: Iteration[23004].Error.
io.pravega.segmentstore.contracts.BadOffsetException: [Segment 'longevity/smallKey/10.#epoch.5$offset.0'] Bad Offset. Expected 75982007, given 73884855.
	at io.pravega.storage.filesystem.FileSystemStorage.doWrite(FileSystemStorage.java:310)
	at io.pravega.storage.filesystem.FileSystemStorage.lambda$write$6(FileSystemStorage.java:155)
	at io.pravega.storage.filesystem.FileSystemStorage.execute(FileSystemStorage.java:405)
	at io.pravega.storage.filesystem.FileSystemStorage.write(FileSystemStorage.java:155)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.write(RollingStorage.java:323)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$write$2(AsyncStorageWrapper.java:93)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$runAsync$12(AsyncStorageWrapper.java:171)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
```

3. Then the Storage Writer correctly enters Reconciliation Mode
```
2019-04-19 13:43:57,572 4129774 [storage-io-79] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[30-57]: State changed from Writing to ReconciliationNeeded.
StorageWriter[30-57]: State changed from ReconciliationNeeded to Reconciling.
```

4. Then it keeps trying to read from the segment, but it gets this:
2019-04-19 13:43:58,589 4130791 [core-5] INFO  i.p.s.s.writer.SegmentAggregator - ```
2019-04-19 13:43:58,592 4130794 [storage-io-9] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[30]: Iteration[23005].Error.
java.lang.IllegalArgumentException: Offset 73884855 + length 2097152 is beyond the last offset 73884855 of the segment.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:458)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.read(RollingStorage.java:151)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$read$8(AsyncStorageWrapper.java:128)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
```


Leading theory is:
1. The IO error hid the fact that the write succeeded (due to the fact that BadOffsetException occurred)
2. We reuse the write handle for reconciliation, but when trying to read extra data, it gets prematurely failed due to the fact that the handle cached the last known offset, which differs from the real offset of the segment.

We probably either auto-refresh the handle in this situation, use a new read handle or disable the check altogether.
