### ISSUE TITLE
Getting Null Pointer Exception Logs inside Controller after pod deletion

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#3672]
**Problem description**
After deletion of few pods while IO was running with small load(IO workload (`Total - 4 readers, 3 writers, 120 events/sec, ~ 100 KB/sec IO)`):
`kubectl delete po/pravega-pravega-segmentstore-1 po/pravega-bookie-3 po/pravega-bookie-2 po/pravega-zk-0`
Getting following Null pointer exception inside Pravega Controller:
```
2019-04-23 06:05:44,019 45599386 [ControllerServiceMain-EventThread] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background exception was not retry-able or retry gave up
java.lang.NullPointerException: null
        at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:179)
        at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:200)
        at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50)
        at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:144)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:865)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:635)
        at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152)
        at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:587)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:499)
```
Environment details: PKS / K8 with medium cluster:
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
5 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```

Deployment Details:

```
Pravega-Operator image: pravega/pravega-operator:0.3.2
Pravega build used : 0.5.0-2222.8ba5431
Zookeeper-operator image: pravega/zookeeper-operator:0.2.1
```
Following are the Cluster details:
```
root@osboxes:/usr/local/go/bin/src/github.com/benchmark# kubectl get po --all-namespaces
NAMESPACE           NAME                                                 READY     STATUS      RESTARTS   AGE
default             pravega-bookie-0                                     1/1       Running     0          19h
default             pravega-bookie-1                                     1/1       Running     0          19h
default             pravega-bookie-2                                     1/1       Running     0          43m
default             pravega-bookie-3                                     1/1       Running     0          43m
default             pravega-operator-779879b48-6kw42                     1/1       Running     0          19h
default             pravega-pravega-controller-84948d8895-7wjp5          1/1       Running     1          19h
default             pravega-pravega-controller-84948d8895-qstsf          1/1       Running     1          19h
default             pravega-pravega-segmentstore-0                       1/1       Running     0          19h
default             pravega-pravega-segmentstore-1                       1/1       Running     0          43m
default             pravega-pravega-segmentstore-2                       1/1       Running     0          19h
default             pravega-zk-0                                         1/1       Running     0          43m
default             pravega-zk-1                                         1/1       Running     0          19h
default             pravega-zk-2                                         1/1       Running     0          19h
default             pravega-zk-3                                         1/1       Running     0          19h
default             shaka-zulu-nfs-client-provisioner-59d7f8f84c-t9cmg   1/1       Running     0          19h
default             zookeeper-operator-685bfcbbc5-5vldv                  1/1       Running     0          19h
kube-system         heapster-85647cf566-t46rl                            1/1       Running     0          6d
kube-system         kube-dns-7559c96fc4-kq5n9                            3/3       Running     0          6d
kube-system         kubernetes-dashboard-5f4b59b97f-hrwmz                1/1       Running     0          3d
kube-system         metrics-server-555d98886f-cp9k6                      1/1       Running     0          6d
kube-system         monitoring-influxdb-cdcf4674-cgxzp                   1/1       Running     0          6d
kube-system         tiller-deploy-95d654d46-2rjfw                        1/1       Running     0          19h
pks-system          cert-generator-v0.11-6hg96                           0/1       Completed   0          6d
pks-system          event-controller-56f9597df8-hq2nq                    2/2       Running     1          6d
pks-system          fluent-bit-6l4hv                                     2/2       Running     0          6d
pks-system          fluent-bit-8hfpj                                     2/2       Running     0          6d
pks-system          fluent-bit-svnb2                                     2/2       Running     0          3d
pks-system          fluent-bit-tdxnj                                     2/2       Running     0          6d
pks-system          fluent-bit-vml52                                     2/2       Running     0          6d
pks-system          sink-controller-65595c498b-k685f                     1/1       Running     3          6d
```
Detailed logs from Pravega all pods are available in NullPointerExceptionAllPodLog.zip
[NullPointerExceptionAllPodLog.zip](https://github.com/pravega/pravega/files/3106263/NullPointerExceptionAllPodLog.zip)

**Comment by shiveshr** [comment]
The stack is from curator. We may be hitting a bug on curator here. 
Need more context of when this error occurs. Like is it during creation of curator client, or after a session expiration or in the normal course of using curator client?

**Comment by Richa-Srivastava** [comment]
Complete logs for all the pods are attached in the issue. Please take a look.

**Comment by shiveshr** [comment]
Also, what is the consequence of this NPE? is it affecting any scenarios? Could you please describe the scenario.

**Comment by Richa-Srivastava** [comment]
It didn't affect any scenario. 
IO was running properly and I deleted few pods(mentioned above in the issue). After that I got this exception in both the controllers but it didn't affect IO operation.

**Comment by RaulGracia** [comment]
@Richa-Srivastava I have observed this kind of stack traces in the Controller when Zookeeper sessions expire (e.g., upon restart). As you have mentioned, IO was able to proceed after recovering from induced failures, which is the expected behavior of the system. 

I see that the stack traces you posted are preceded from a Zookeeper reconfiguration event:
```
2019-04-23 06:05:44,018 45597058 [ControllerServiceMain-EventThread] INFO  o.a.c.f.imps.EnsembleTracker - New config event received: {server.1=pravega-zk-0.pravega-zk-headless.default.svc.cluster.local:2888:3888:observer;0.0.0.0:2181, version=3000000e7, server.4=pravega-zk-3.pravega-zk-headless.default.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, server.3=pravega-zk-2.pravega-zk-headless.default.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, server.2=pravega-zk-1.pravega-zk-headless.default.svc.cluster.local:2888:3888:participant;0.0.0.0:2181}
```

The way Zookeeper is reconfigured via the Operator is being substantially improved in this PR: https://github.com/pravega/zookeeper-operator/pull/69. Maybe we can check if this Curator error trace are still there after using the changes from that PR. Anyway, this seems not to be a `bug` as the issue label suggests, so I'm inclined to close this issue.
