### ISSUE TITLE
"Scale Operation Task failed in the segments" error occurred in the Pravega controller

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega#3676]
Observing **Scale operation task failed** issue for segments under the Pravega Controller leading to `EpochTransitionOperationExceptions` accompanied with `PreConditionFailureException` and `ConcurrentEventProcessor Processing failed` messages, thereby preventing IO's to populate events in the streams, i.e., even though the writers and readers are in a stable condition the event size is not increasing within the segment store.
This Error is being observed while running IO work load for 3+ days (writers: 4, readers: 8, size: 100 bytes, max events/sec: 1000, min segments: 8, stream: 1, scale factor: 2, scaling: based on "Events per second") experienced both controllers restart in Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.

Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Zookeeper Operator : spiegela/zookeeper-operator:latest
Pravega Operator: adrianmo/pravega-operator:issue-134-5
```
Found Error messages and Exceptions like following: -
```
2019-04-09 11:59:48,852 9858235 [controllerpool-6] WARN  i.p.c.s.stream.PersistentStreamBase - scale precondition failed [223338299482, 266287972460]
2019-04-09 11:59:48,853 9858236 [controllerpool-6] WARN  i.p.c.s.e.r.ScaleOperationTask - [requestId=2494526755290369145] processing scale request for longevity/smallScale segments [223338299482, 266287972460] failed {}
io.pravega.controller.store.stream.EpochTransitionOperationExceptions$PreConditionFailureException: null
        at io.pravega.controller.store.stream.PersistentStreamBase.lambda$null$90(PersistentStreamBase.java:683)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at io.pravega.controller.store.stream.ZKStoreHelper.lambda$setData$12(ZKStoreHelper.java:177)
        at io.pravega.controller.store.stream.ZKStoreHelper.lambda$callback$24(ZKStoreHelper.java:319)
        at org.apache.curator.framework.imps.Backgrounding$1$1.run(Backgrounding.java:158)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-04-09 11:59:48,854 9858237 [controllerpool-18] WARN  i.p.c.e.i.ConcurrentEventProcessor - ConcurrentEventProcessor Processing failed java.util.concurrent.CompletionException
2019-04-09 11:59:48,854 9858237 [controllerpool-18] ERROR i.p.c.e.i.ConcurrentEventProcessor - ConcurrentEventProcessor Processing failed, exiting {}
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.EpochTransitionOperationExceptions$PreConditionFailureException
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
        at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
        at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:899)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.pravega.controller.server.eventProcessor.requesthandlers.ScaleOperationTask.lambda$execute$0(ScaleOperationTask.java:73)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.controller.store.stream.EpochTransitionOperationExceptions$PreConditionFailureException: null
        at io.pravega.controller.store.stream.PersistentStreamBase.lambda$null$90(PersistentStreamBase.java:683)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at io.pravega.controller.store.stream.ZKStoreHelper.lambda$setData$12(ZKStoreHelper.java:177)
        at io.pravega.controller.store.stream.ZKStoreHelper.lambda$callback$24(ZKStoreHelper.java:319)
        at org.apache.curator.framework.imps.Backgrounding$1$1.run(Backgrounding.java:158)
        ... 7 common frames omitted

```

**Comment by shiveshr** [comment]
This is expected in case the segment has already been sealed as part of a previous scale. We can suppress the warning

**Comment by sumit-bm** [comment]
@shiveshr Thanks for the explanation, we would like to suppress the warning only.

**Comment by SomeshJoshi19** [comment]
@shiveshr I'm repeatedly getting the above mentioned exceptions for moderate longevity IO run in the same setup. Can this warnings be soft handled ?
```
Pravega version: 0.5.0-2269.6f8a820
```

log from controller pod
```
2019-06-06 22:56:02,046 45739921 [controllerpool-2] WARN  i.p.c.s.stream.PersistentStreamBase - scale precondition failed [2495375999888]
2019-06-06 22:56:02,047 45739922 [controllerpool-2] WARN  i.p.c.s.e.r.ScaleOperationTask - [requestId=6246339464424256818] processing scale request for longevity/mediumScale segments [2495375999888] failed {}
io.pravega.controller.store.stream.EpochTransitionOperationExceptions$PreConditionFailureException: null
        at io.pravega.controller.store.stream.PersistentStreamBase.lambda$null$91(PersistentStreamBase.java:706)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-06-06 22:56:02,048 45739923 [controllerpool-1] WARN  i.p.c.e.i.ConcurrentEventProcessor - ConcurrentEventProcessor Processing failed java.util.concurrent.CompletionException
2019-06-06 22:56:02,049 45739924 [controllerpool-1] ERROR i.p.c.e.i.ConcurrentEventProcessor - ConcurrentEventProcessor Processing failed, exiting {}
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.EpochTransitionOperationExceptions$PreConditionFailureException
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
        at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
        at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:899)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.pravega.controller.server.eventProcessor.requesthandlers.ScaleOperationTask.lambda$execute$0(ScaleOperationTask.java:73)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.controller.store.stream.EpochTransitionOperationExceptions$PreConditionFailureException: null
        at io.pravega.controller.store.stream.PersistentStreamBase.lambda$null$91(PersistentStreamBase.java:706)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580)
        ... 8 common frames omitted
```

**Comment by shiveshr** [comment]
changing priority because we have all other soft handling logging related issues as P3
