### ISSUE TITLE
"Exception thrown during Garbage Collection iteration" error message observed in Pravega controller

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega#3677]
Observing **Garbage Collection Failure** throwing `ERROR i.p.c.s.stream.ZKGarbageCollector` and `StoreException$StoreConnectionException` as error messages, causing IO failure thus stopping the population of events in segments and also preventing IOs to pass during the sample test runs over Pravega.

This Error is being observed while running IO work load for 3+ days (writers: 4, readers: 8, size: 100 bytes, max events/sec: 1000, min segments: 8, stream: 1, scale factor: 2, scaling: based on "Events per second") experienced one controllers restart for 4 times and the other for 2 times in Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.

Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Pravega version : 0.5.0-2222.8ba5431
Zookeeper Operator : spiegela/zookeeper-operator:latest
Pravega Operator: adrianmo/pravega-operator:issue-134-5
```
Found Error messages and Exceptions like following: -
```
2019-04-22 17:45:15,365 172816230 [controllerpool-10] ERROR i.p.c.s.stream.ZKGarbageCollector - Exception thrown during Garbage Collection iteration for completedTxnGC. Log and ignore.
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$StoreConnectionException: /garbagecollection/completedTxnGC/guard
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:943)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.pravega.controller.store.stream.ZKStoreHelper.lambda$callback$27(ZKStoreHelper.java:371)
        at org.apache.curator.framework.imps.Backgrounding$1$1.run(Backgrounding.java:158)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.controller.store.stream.StoreException$StoreConnectionException: /garbagecollection/completedTxnGC/guard
        at io.pravega.controller.store.stream.StoreException.create(StoreException.java:105)
        at io.pravega.controller.store.stream.StoreException.create(StoreException.java:70)
        ... 9 common frames omitted
```

**Comment by shiveshr** [comment]
This is a consequence of losing connection with zookeeper. Its not the cause. Its an expected log in case zk connection is failing or session has expired.

**Comment by shiveshr** [comment]
changing label to P3 as this is about soft handling the logging
