### ISSUE TITLE
Ledger fenced while writing entry Exception inside BookKeeper 

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#3681]
**Problem description**
While running small IO workload `(Total - 4 readers, 3 writers, 120 events/sec, ~ 100 KB/sec IO)` for more than 2 days, following exception occurred inside BookKeeper:

```
2019-04-22 17:27:05,213 - ERROR - [BookieWriteThreadPool-OrderedExecutor-0-0:WriteEntryProcessorV3@138] - Ledger fenced while writing entry:42345 to ledger:56
org.apache.bookkeeper.bookie.BookieException$LedgerFencedException
        at org.apache.bookkeeper.bookie.BookieException.create(BookieException.java:57)
        at org.apache.bookkeeper.bookie.Bookie.addEntry(Bookie.java:1240)
        at org.apache.bookkeeper.proto.WriteEntryProcessorV3.getAddResponse(WriteEntryProcessorV3.java:123)
        at org.apache.bookkeeper.proto.WriteEntryProcessorV3.safeRun(WriteEntryProcessorV3.java:163)
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
``` 
Environment details: PKS / K8 with medium cluster:

```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
5 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Deployment Details:

```
Pravega-Operator image: pravega/pravega-operator:0.3.2
Pravega build used : 0.5.0-2222.8ba5431
Zookeeper-operator image: pravega/zookeeper-operator:0.2.1

```
Following are the Cluster details:

```
root@osboxes:/home/osboxes# kubectl get po
NAME                                                 READY     STATUS    RESTARTS   AGE
pravega-bookie-0                                     1/1       Running   0          2d
pravega-bookie-1                                     1/1       Running   0          4d
pravega-bookie-2                                     1/1       Running   0          4d
pravega-bookie-3                                     1/1       Running   0          4d
pravega-operator-779879b48-6j28t                     1/1       Running   0          4d
pravega-pravega-controller-84948d8895-k6mrm          1/1       Running   1          2d
pravega-pravega-controller-84948d8895-krxpq          1/1       Running   2          4d
pravega-pravega-segmentstore-0                       1/1       Running   0          2d
pravega-pravega-segmentstore-1                       1/1       Running   0          2d
pravega-pravega-segmentstore-2                       1/1       Running   0          2d
pravega-zk-0                                         1/1       Running   0          2d
pravega-zk-1                                         0/1       Running   0          4d
pravega-zk-2                                         0/1       Running   0          4d
pravega-zk-3                                         0/1       Running   0          4d
shaka-zulu-nfs-client-provisioner-59d7f8f84c-942d2   1/1       Running   0          4d
zookeeper-operator-685bfcbbc5-wzchs                  1/1       Running   0          4d
```
Detailed logs for all the pods are available as Ledger fenced.zip
[Ledger fenced.zip](https://github.com/pravega/pravega/files/3111765/Ledger.fenced.zip)

**Comment by andreipaduroiu** [comment]
The segment store logs indicate there was a container failover when these happened. It is expected to fence ledgers during this process. After this, the segment store proceeded as normal.
