### ISSUE TITLE
Pravega Controller  giving `AbstractChannel$AnnotatedConnectException` Exception and dropping few frames

### ISSUE THREAD

**Issue by Praveen-Kanade** [pravega/pravega#3686]
Pravega Controller is throwing `AbstractChannel$AnnotatedConnectException` Exception and dropping few frames
IO was running load of(10 writer, 10 Readers, 200 events /sec ,100kb) 

This was observed when  one of the node was drained. While recreating the pod the exception is thrown. Once the pod was recreated all the IO operation were completed smoothly.

```
bookkeeper:0.5.0-2222.8ba5431
pravega:0.5.0-2222.8ba5431
zookeeper:3.5.4-beta-operator
pravega-operator:0.3.2
zookeeper-operator:0.2.1
```

Environment details: PKS / K8 with medium cluster:

```
PKS / K8 with medium cluster:
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioned using Isilon as backend
```
Snippet of error log:
```

2019-04-24 05:09:00,247 830822 [epollEventLoopGroup-2-4] WARN  i.p.client.netty.impl.RawClient - Closing connection to segment _system/_RGscaleGroup/0.#epoch.0 with exception: {}
java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: /172.24.102.14:12345
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1088)
	at java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1070)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.pravega.client.netty.impl.ConnectionPoolImpl.lambda$establishConnection$4(ConnectionPoolImpl.java:201)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:629)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:648)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:522)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:411)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: /172.24.102.14:12345
	... 14 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: /172.24.102.14:12345
	at io.netty.channel.unix.Socket.finishConnect(..)(Unknown Source)
Caused by: io.netty.channel.unix.Errors$NativeConnectException: syscall:getsockopt(..) failed: Connection refused
	... 1 common frames omitted
```

[pravega-k8s-logging-2019-04-24-10-50-34 (2).zip](https://github.com/pravega/pravega/files/3112204/pravega-k8s-logging-2019-04-24-10-50-34.2.zip)

**Comment by shiveshr** [comment]
These are expected stack traces. What is the issue here?

**Comment by ravisharda** [comment]
When searching for the exception string `AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: ` in another context, found that the same exception was also discussed in issue #479.

**Comment by shiveshr** [comment]
soft handling of expected error logs. changing the priority to P3
