### ISSUE TITLE
OutOfDirectMemoryError exception observed in Bookkeepers

### ISSUE THREAD

**Issue by Ranjan-Padhi** [pravega/pravega#3687]
Observing OutOfDirectMemoryError exception (Unhandled exception occurred in I/O thread or handler
`io.netty.util.internal.OutOfDirectMemoryError`: failed to allocate 16777216 byte(s) of direct memory (used: 1073741824, max: 1073741824)) in bookkeeper after restarting one of the bookkeeper out of 3 bookkeeper while IO also running in background with 3 writers and 6 Readers

Deployment Details:-
```
bookkeeper:0.5.0-2222.8ba5431
pravega:0.5.0-2222.8ba5431
zookeeper:3.5.4-beta-operator
pravega-operator:0.3.2
zookeeper-operator:0.2.1
```

Environment details: PKS / K8 with medium cluster:
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```

Bookkeeper exception log
```
2019-04-24 09:08:39,719 - ERROR - [bookie-io-1-2:BookieRequestHandler@70] - Unhandled exception occurred in I/O thread or handler
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 1073741824, max: 1073741824)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:226)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
        at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
        at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
        at io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:71)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:791)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
2019-04-24 09:08:39,751 - INFO  - [bookie-io-1-1:AuthHandler$ServerSideHandler$AuthHandshakeCompleteCallback@211] - Authentication success on server side
2019-04-24 09:08:39,751 - INFO  - [bookie-io-1-1:BookieRequestHandler@50] - Channel connected  [id: 0x5600908a, L:/172.24.75.8:3181 - R:/172.24.75.15:47388]
```
```
2019-04-24 09:34:58,733 - INFO  - [bookie-io-1-1:BookieRequestHandler@61] - Channels disconnected: [id: 0xb2c71cb9, L:/172.24.75.8:3181 ! R:/172.24.75.8:42598]
2019-04-24 09:35:00,957 - ERROR - [bookie-io-1-2:BookieRequestHandler@70] - Unhandled exception occurred in I/O thread or handler
io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
        at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
2019-04-24 09:35:00,962 - INFO  - [bookie-io-1-2:BookieRequestHandler@61] - Channels disconnected: [id: 0x6dfab5cc, L:/172.24.75.8:3181 ! R:/172.24.75.13:51790]
```

**Comment by Ranjan-Padhi** [comment]
[pravega-bookie-0.log](https://github.com/pravega/pravega/files/3112172/pravega-bookie-0.log)

**Comment by RaulGracia** [comment]
@Ranjan-Padhi, I have a couple of question regarding this problem:
1) Was IO stopped after restarting the Bookie or the Pravega client could make progress?
2) I don't know if it is related, but the Bookie log you posted contains a lot of `No ledger found while reading entry` messages for ledger 81. Wondering if this is related to the issue, which may be related to a segment store reading data to recover a container. There have been few fixes recently in the segment store, so please could you execute again this experiment with version `0.5.0-2269.6f8a820` to see if the issue persists?

**Comment by Ranjan-Padhi** [comment]
@RaulGracia, here is the update of issue verification in current version `0.5.0-2269.6f8a820`

1. IO was not stopped in previous release as well as current release, only bookkeeper exception was highlighted
2. In current release we re-tested same scenario more than 5 times but unable to get the exception in bookies.
Issue was reported in `0.5.0-2222.8ba5431` release in which we had multiple issues in SegmentStore and Controller which was fixed in later version, so it looks like the bookies exception was coming because of SegmentStore issues. In current release all the previous issues in SegmentStore has resolved so this issue also resolved

But we needs to identify for which issue this has been fixed.

**Comment by RaulGracia** [comment]
Thanks @Ranjan-Padhi for confirming that this issue cannot be reproduced with the last version of Pravega. It is difficult to identify which is the precise change (or changes) that improved the interaction with Bookkeeper and avoid this problem to appear, as the version you tests is +40 commits behind the current `0.5`. In any case, I think that we can close this issue as the problem cannot be reproduced.
