### ISSUE TITLE
Cleanup Exception handling "Curator-ConnectionStateManager - Could not inject session expiration"

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega#3689]
Observing `ERROR o.a.c.f.s.ConnectionStateManager` along with `java.lang.IllegalArgumentException` and `java.net.UnknownHostException` exceptions in Pravega controller due to Zookeeper session expiry. Zookeeper may not be able to reconnect to the controller with the same IP after controller faced restarts, throws **A HostProvider may not be empty!** and **No IP address found for server: pravega-example-zk-client:2181** as exception messages for the above two exceptions respectively on passing the domain name of the zk-client in place of ZK host IP under `pravega.yaml` file.

This Error is being observed while running IO work load for 4+ days (writers: 4, readers: 8, size: 100 bytes, max events/sec: 1000, min segments: 8, stream: 1, scale factor: 2, scaling: based on "Events per second") experienced one controllers restart for 4 times and the other for 2 times in Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.

Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Pravega version : 0.5.0-2222.8ba5431
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```
Found Error messages and Exceptions like following: -
```
2019-04-22 17:23:50,469 171531334 [Curator-ConnectionStateManager-0] INFO  o.a.zookeeper.ZooKeeperTestable - injectSessionExpiration() called
2019-04-22 17:23:50,469 171531334 [Curator-ConnectionStateManager-0] WARN  o.a.c.f.s.ConnectionStateManager - Session timeout has elapsed while SUSPENDED. Injecting a session expiration. Elapsed ms: 15005. Adjusted session timeout ms: 10000
2019-04-22 17:23:50,469 171531334 [ControllerServiceMain-EventThread] WARN  org.apache.curator.ConnectionState - Session expired event received
2019-04-22 17:23:50,469 171531334 [Curator-PathChildrenCache-0] INFO  org.apache.curator.ConnectionState - Connection string changed to: pravega-example-zk-client:2181
2019-04-22 17:23:50,469 171531334 [Curator-ConnectionStateManager-0] ERROR o.a.c.f.s.ConnectionStateManager - Could not inject session expiration
java.lang.IllegalArgumentException: A HostProvider may not be empty!
        at org.apache.zookeeper.client.StaticHostProvider.updateServerList(StaticHostProvider.java:157)
        at org.apache.zookeeper.ZooKeeper.updateServerList(ZooKeeper.java:215)
        at org.apache.curator.ConnectionState.handleNewConnectionString(ConnectionState.java:355)
        at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:229)
        at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:96)
        at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:141)
        at org.apache.curator.framework.state.ConnectionStateManager.checkSessionExpiration(ConnectionStateManager.java:310)
        at org.apache.curator.framework.state.ConnectionStateManager.processEvents(ConnectionStateManager.java:284)
        at org.apache.curator.framework.state.ConnectionStateManager.access$000(ConnectionStateManager.java:44)
        at org.apache.curator.framework.state.ConnectionStateManager$1.call(ConnectionStateManager.java:120)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-04-22 17:23:50,469 171531334 [Curator-ConnectionStateManager-0] WARN  o.a.c.f.s.ConnectionStateManager - Session timeout has elapsed while SUSPENDED. Injecting a session expiration. Elapsed ms: 15005. Adjusted session timeout ms: 10000
2019-04-22 17:23:50,469 171531334 [Curator-PathChildrenCache-0] WARN  o.a.z.client.StaticHostProvider - No IP address found for server: pravega-example-zk-client:2181
java.net.UnknownHostException: pravega-example-zk-client
        at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at org.apache.zookeeper.client.StaticHostProvider.resolveAndShuffle(StaticHostProvider.java:114)
        at org.apache.zookeeper.client.StaticHostProvider.updateServerList(StaticHostProvider.java:155)
        at org.apache.zookeeper.ZooKeeper.updateServerList(ZooKeeper.java:215)
        at org.apache.curator.ConnectionState.handleNewConnectionString(ConnectionState.java:355)
        at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:229)
        at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:96)
        at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:141)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:951)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:620)
        at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:215)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:41)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache.refresh(PathChildrenCache.java:521)
        at org.apache.curator.framework.recipes.cache.RefreshOperation.invoke(RefreshOperation.java:35)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$9.run(PathChildrenCache.java:786)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by sumit-bm** [comment]
@shiveshr could we handle exceptions softly over here?

**Comment by shiveshr** [comment]
This is on curator's stack.

> Zookeeper may not be able to reconnect to the controller with the same IP after controller faced restarts

zookeeper doesnt connect to controller. it connects to other zookeepers. Curator is not able to resolve the zk address `No IP address found for server: pravega-example-zk-client:2181 ` and that is the reason the service failed. 

Closing this issue.
