### ISSUE TITLE
"ERROR Leader Selector - The leader threw an exception" error observed in Pravega controller

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega#3690]
Observing `ERROR o.a.c.f.r.leader.LeaderSelector` along with `java.lang.InterruptedException: null` as exception under Pravega controller maybe due to interruption in Zookeeper client connection by some connection blockage or timeout while attempting to seal the reader group entry from checkpoint store.

This Error is being observed while running IO work load for 4+ days (writers: 4, readers: 8, size: 100 bytes, max events/sec: 1000, min segments: 8, stream: 1, scale factor: 2, scaling: based on "Events per second") experienced both controllers restart 2 times in Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.

Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```
Found Error messages and Exceptions like following: -
```
2019-04-05 15:04:00,297 102874193 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.e.i.EventProcessorGroupImpl - Attempting to seal the reader group entry from checkpoint store
2019-04-05 15:04:00,298 102874194 [Curator-LeaderSelector-0] ERROR o.a.c.f.r.leader.LeaderSelector - The leader threw an exception
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
        at org.apache.curator.CuratorZookeeperClient.internalBlockUntilConnectedOrTimedOut(CuratorZookeeperClient.java:394)
        at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:56)
        at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)
        at org.apache.curator.framework.imps.DeleteBuilderImpl.pathInForeground(DeleteBuilderImpl.java:265)
        at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:249)
        at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:34)
        at org.apache.curator.framework.recipes.locks.LockInternals.deleteOurPath(LockInternals.java:347)
        at org.apache.curator.framework.recipes.locks.LockInternals.releaseLock(LockInternals.java:124)
        at org.apache.curator.framework.recipes.locks.InterProcessMutex.release(InterProcessMutex.java:154)
        at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:449)
        at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:466)
        at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:65)
        at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:246)
        at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:240)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by sumit-bm** [comment]
@shiveshr We are more worried on exception handling over here rather than functional areas. So would be good if we could handle exceptions softly.

**Comment by shiveshr** [comment]
This is an expected log message if the controller service is shutting down. This comes from curator's log and not pravega log as we close the curator client.
