### ISSUE TITLE
Intermittent failures in BookKeeperLogTests

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#3691]
**Problem description**
This test sometimes fails with:
```
io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogTests$RegularBookKeeperLogTests > classMethod FAILED
    org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
        at org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase.waitForConnection(ZooKeeperWatcherBase.java:159)
        at org.apache.bookkeeper.zookeeper.ZooKeeperClient$Builder.build(ZooKeeperClient.java:257)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperServiceRunner.initializeZookeeper(BookKeeperServiceRunner.java:187)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperServiceRunner.startAll(BookKeeperServiceRunner.java:172)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogTests.setUpBookKeeper(BookKeeperLogTests.java:103)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogTests$RegularBookKeeperLogTests.startUp(BookKeeperLogTests.java:423)
```

**Comment by RaulGracia** [comment]
Fixed via #4999.
