### ISSUE TITLE
Missing asynchronous read event and byte stream write methods

### ISSUE THREAD

**Issue by akurilov** [pravega/pravega#3697]
Reopening #3587 

The methods to read event / write bytes to the stream are buffered, while not asynchronous generally. The buffering may help to avoid the blocking or may not, depending on the buffer state. The client application is able to keep the write buffer filled if it writes faster than flushing. Nearly all calls would be blocking in this case. Generally, buffered I/O is not the same as asynchronous I/O. The OutputStream interface compatibility could be preserved by adding a method instead of changing one.

**Problem description**
Asynchronous data path I/O methdos allow the client to rely on the Pravega client thread/connection pool and write more resource-effective client code using some reactive approach. However, the following methods:
- event read
- byte stream write

are blocking. Moreover, these blocking methods are wrapping the underlying asynchronous calls likely reducing the client side performance, e.g. package private class https://github.com/pravega/pravega/blob/3fd167ecd36603251d92d9da09adeebc5293981d/client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java#L42

**Problem location**
https://github.com/pravega/pravega/blob/3fd167ecd36603251d92d9da09adeebc5293981d/client/src/main/java/io/pravega/client/stream/EventStreamReader.java#L42
https://github.com/pravega/pravega/blob/3fd167ecd36603251d92d9da09adeebc5293981d/client/src/main/java/io/pravega/client/byteStream/ByteStreamWriter.java#L51

**Suggestions for an improvement**
Provide/expose the asynchronous methods to the client for:
- event read
- byte stream write

**Comment by akurilov** [comment]
The same issue relates to the transactional event writing. 
1. It's expected that the event write call inside the transaction won't block while it does:
```
java.lang.Thread.State: WAITING
	at java.base@11.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	- parking to wait for <163b3cd4> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.base@11.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
	at java.base@11.0.3/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998)
	at io.pravega.common.concurrent.Futures.getThrowingException(Futures.java:152)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl.write(SegmentOutputStreamImpl.java:434)
	- locked <7958b3c9> (a java.lang.Object)
	at io.pravega.client.stream.impl.SegmentTransactionImpl.writeEvent(SegmentTransactionImpl.java:49)
	- locked <6bf9cd52> (a java.lang.Object)
	at io.pravega.client.stream.impl.TransactionalEventStreamWriterImpl$TransactionImpl.writeEvent(TransactionalEventStreamWriterImpl.java:103)
	at io.pravega.client.stream.impl.TransactionalEventStreamWriterImpl$TransactionImpl.writeEvent(TransactionalEventStreamWriterImpl.java:93)
```
2. The transaction's `commit` method should be asynchronous (returning the compleatable future instance).

**Comment by tkaitchuck** [comment]
> The client application is able to keep the write buffer filled if it writes faster than flushing. Nearly all calls would be blocking in this case

This is back pressure. How would we slow down a writer in an async case? Are you ok with the async call simply being queued and delayed resulting in an unbounded increase in the latency between the api call and the future being completed? It seems like such an API would need to block or start throwing exceptions at some point or the process will be run out of memory.

**Comment by tkaitchuck** [comment]
Take a look at the ByteStreamReader method `onDataAvailable()`. It provides a way to get notified to avoid blocking when using the buffered API. Would a similar API on the writer side `onCapacityAvailable()` be a solution to your issue?
