### ISSUE TITLE
Sporadic test failure OperationProcessorTests.testWithDataCorruptionFailures

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#3718]
**Problem description**
We are getting sporadic test failures in Jenkins related to `OperationProcessorTests.testWithDataCorruptionFailures`:
```
java.lang.AssertionError: Unexpected truncation marker for Operation SeqNo 100 when it spans multiple DataFrames. expected:<Sequence = 0> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at io.pravega.segmentstore.server.logs.OperationProcessorTests.performLogOperationChecks(OperationProcessorTests.java:541)
	at io.pravega.segmentstore.server.logs.OperationProcessorTests.testWithDataCorruptionFailures(OperationProcessorTests.java:439)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Problem location**
`OperationProcessorTests.testWithDataCorruptionFailures`

**Suggestions for an improvement**
Fix the test.

**Comment by andreipaduroiu** [comment]
This happens when there are multiple (N) Tier 1 commits in-flight, where commit M (0<M<=N) fails, but at least one commit C (0<=C<M) still hasn't been ack-ed (most likely due to thread scheduling issues). This is not a bug in the code, rather an inability for the test to detect the issue.
