### ISSUE TITLE
Cleanup Exception Handling: Getting `java.util.concurrent.CancellationException: OperationProcessor is shutting down` exception while stopping segment Container

### ISSUE THREAD

**Issue by Ranjan-Padhi** [pravega/pravega#3736]
Showing `java.util.concurrent.CancellationException: OperationProcessor is shutting down` exeption in one of segmentstore while IO is running

As per log Exception is coming while stopping segmentWritter and segmentContainer of `Tostop contener`(ToStop = [0, 1, 2, 3, 4]) , out of 5 containers, it's showing CancellationException for 3 containers

Environment details: PKS / K8 with medium cluster:
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Deployment Details:-
```
bookkeeper:0.5.0-2236.5228e2d
pravega:0.5.0-2236.5228e2d
zookeeper:3.5.4-beta-operator
pravega-operator:0.3.2
zookeeper-operator:0.2.1
```
Exception log :-
```
2019-05-02 06:49:51,077 2436687 [core-12] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [16, 17, 18, 19, 20, 21, 23, 25, 27, 29, 31], Current = [0, 1, 2, 3, 4, 16, 17, 18, 19, 20, 21, 23, 25, 27, 29, 31], PendingTasks = [], ToStart = [], ToStop = [0, 1, 2, 3, 4].
```
```
2019-05-02 06:49:51,077 2436687 [core-12] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Stopping Container 0.
2019-05-02 06:49:51,078 2436688 [core-12] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Stopping.
2019-05-02 06:49:51,079 2436689 [core-12] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[0]: Stopping.
2019-05-02 06:49:51,079 2436689 [core-12] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[0]: Stopped.
2019-05-02 06:49:51,079 2436689 [core-12] INFO  i.p.c.c.AbstractThreadPoolService - StorageWriter[0]: Stopping.
2019-05-02 06:49:51,082 2436692 [core-12] INFO  i.p.s.server.logs.DurableLog - DurableLog[0]: Stopping.
2019-05-02 06:49:51,083 2436693 [core-12] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[0]: Stopping.
2019-05-02 06:49:51,083 2436693 [core-12] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[0]: Stopped.
2019-05-02 06:49:51,084 2436694 [core-12] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Stopping Container 1.
2019-05-02 06:49:51,084 2436694 [core-12] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[1]: Stopping.
2019-05-02 06:49:51,084 2436694 [core-12] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[1]: Stopping.
2019-05-02 06:49:51,084 2436694 [core-12] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[1]: Stopped.
2019-05-02 06:49:51,084 2436694 [core-12] INFO  i.p.c.c.AbstractThreadPoolService - StorageWriter[1]: Stopping.
2019-05-02 06:49:51,085 2436695 [core-12] INFO  i.p.s.server.logs.DurableLog - DurableLog[1]: Stopping.
2019-05-02 06:49:51,087 2436697 [core-9] INFO  i.p.s.server.writer.StorageWriter - StorageWriter[0]: StorageWriter intercepted CancellationException while shutting down.
2019-05-02 06:49:51,088 2436698 [core-12] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[1]: Stopping.
2019-05-02 06:49:51,088 2436698 [core-12] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[1]: Stopped.
2019-05-02 06:49:51,088 2436698 [core-12] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Stopping Container 2.
2019-05-02 06:49:51,088 2436698 [core-12] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[2]: Stopping.
2019-05-02 06:49:51,088 2436698 [core-16] INFO  i.p.s.server.writer.StorageWriter - StorageWriter[1]: StorageWriter intercepted CancellationException while shutting down.
2019-05-02 06:49:51,088 2436698 [core-12] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[2]: Stopping.
2019-05-02 06:49:51,088 2436698 [core-12] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[2]: Stopped.
2019-05-02 06:49:51,088 2436698 [core-12] INFO  i.p.c.c.AbstractThreadPoolService - StorageWriter[2]: Stopping.
2019-05-02 06:49:51,088 2436698 [core-13] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[0-1]: State changed from Writing to Closed.
2019-05-02 06:49:51,088 2436698 [core-12] INFO  i.p.s.server.logs.DurableLog - DurableLog[2]: Stopping.
2019-05-02 06:49:51,088 2436698 [core-13] INFO  i.p.s.s.tables.WriterTableProcessor - TableProcessor[0-1]: Closed.
2019-05-02 06:49:51,088 2436698 [core-12] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[2]: Stopping.
2019-05-02 06:49:51,088 2436698 [core-12] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[2]: Stopped.
2019-05-02 06:49:51,088 2436698 [core-13] INFO  i.p.c.c.AbstractThreadPoolService - StorageWriter[0]: Stopped.
2019-05-02 06:49:51,088 2436698 [core-12] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Stopping Container 3.
2019-05-02 06:49:51,088 2436698 [core-12] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[3]: Stopping.
2019-05-02 06:49:51,088 2436698 [core-13] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[1-1]: State changed from Writing to Closed.
2019-05-02 06:49:51,088 2436698 [core-13] INFO  i.p.s.s.tables.WriterTableProcessor - TableProcessor[1-1]: Closed.
2019-05-02 06:49:51,088 2436698 [core-13] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[1-4]: State changed from Writing to Closed.
2019-05-02 06:49:51,088 2436698 [core-13] INFO  i.p.s.s.tables.WriterTableProcessor - TableProcessor[1-4]: Closed.
2019-05-02 06:49:51,088 2436698 [core-12] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[3]: Stopping.
2019-05-02 06:49:51,088 2436698 [core-13] INFO  i.p.c.c.AbstractThreadPoolService - StorageWriter[1]: Stopped.
2019-05-02 06:49:51,088 2436698 [core-12] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[3]: Stopped.
2019-05-02 06:49:51,088 2436698 [core-12] INFO  i.p.c.c.AbstractThreadPoolService - StorageWriter[3]: Stopping.
2019-05-02 06:49:51,088 2436698 [core-13] INFO  i.p.s.server.writer.StorageWriter - StorageWriter[2]: StorageWriter intercepted CancellationException while shutting down.
2019-05-02 06:49:51,088 2436698 [core-12] INFO  i.p.s.server.logs.DurableLog - DurableLog[3]: Stopping.
2019-05-02 06:49:51,089 2436699 [core-12] ERROR i.p.s.s.h.handler.AppendProcessor - Error (Segment = 'longevity/smallKey/6.#epoch.3', Operation = 'append')
java.util.concurrent.CancellationException: OperationProcessor is shutting down.
        at io.pravega.segmentstore.server.logs.OperationProcessor.doStop(OperationProcessor.java:151)
        at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:280)
        at io.pravega.common.concurrent.Services.stopAsync(Services.java:61)
        at io.pravega.segmentstore.server.logs.DurableLog.doStop(DurableLog.java:245)
        at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:280)
        at io.pravega.common.concurrent.Services.stopAsync(Services.java:61)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainer.doStop(StreamSegmentContainer.java:281)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainer.doStop(StreamSegmentContainer.java:263)
        at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:280)
        at io.pravega.common.concurrent.Services.stopAsync(Services.java:61)
        at io.pravega.segmentstore.server.store.StreamSegmentContainerRegistry.stopContainer(StreamSegmentContainerRegistry.java:132)
        at io.pravega.segmentstore.server.host.ZKSegmentContainerMonitor.stopContainer(ZKSegmentContainerMonitor.java:207)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at io.pravega.segmentstore.server.host.ZKSegmentContainerMonitor.checkAssignment(ZKSegmentContainerMonitor.java:184)
		at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:326)
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:320)
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-05-02 06:49:51,090 2436700 [core-12] ERROR i.p.s.s.h.handler.AppendProcessor - Error (Segment = 'longevity/smallKey/6.#epoch.3', Operation = 'append')
java.util.concurrent.CancellationException: OperationProcessor is shutting down.
        at io.pravega.segmentstore.server.logs.OperationProcessor.doStop(OperationProcessor.java:151)
        at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:280)
```

**Comment by Ranjan-Padhi** [comment]
[pravega-pravega-segmentstore.log](https://github.com/pravega/pravega/files/3137968/pravega-pravega-segmentstore.log)

**Comment by Ranjan-Padhi** [comment]
[pravega-k8s-logging-2019-05-02-07-37-12.zip](https://github.com/pravega/pravega/files/3137970/pravega-k8s-logging-2019-05-02-07-37-12.zip)

**Comment by andreipaduroiu** [comment]
This exception is correctly thrown. All outstanding operations are cancelled when the Operation Processor shuts down.

The log cleanup should be done in `AppendProcessor` and `PravegaRequestProcessor` and should likely be an INFO-level message saying "An <operation-type> has been cancelled".
