### ISSUE TITLE
Oberving "AsyncSegmentInputStreamImpl - Error while sending request WireCommands.ReadSegment.." error in Pravega Controller

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega#3744]
Observing `ERROR i.p.c.s.i.AsyncSegmentInputStreamImpl` with error message **Error while sending request WireCommands.ReadSegment(type=READ_SEGMENT)** causing `io.pravega.shared.protocol.netty.ConnectionFailedException` exception. This Error is being observed in both the deployed controllers after restarting one SegmentStore pod out of three SegmentStores pods over Pravega cluster.

This Error is being observed while running IO work load for 1+ days (writer: 1, reader: 1, size: 100 bytes, events/sec: 1, segments: 1000, stream: 2) experienced in Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.

Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Pravega version : 0.5.0-2236.5228e2d
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```
Found Error messages and Exceptions like following: -
```
019-05-02 07:45:03,919 8146645 [epollEventLoopGroup-2-2] INFO  i.p.client.netty.impl.FlowHandler - Closing Flow 8 for endpoint 172.24.10.10
2019-05-02 07:45:03,919 8146645 [epollEventLoopGroup-2-1] INFO  i.p.client.netty.impl.FlowHandler - Closing Flow 6 for endpoint 172.24.10.10
2019-05-02 07:45:03,919 8146645 [epollEventLoopGroup-2-2] ERROR i.p.c.s.i.AsyncSegmentInputStreamImpl - Error while sending request
WireCommands.ReadSegment(type=READ_SEGMENT, segment=_system/_commitStream/1.#epoch.0, offset=0, suggestedLength=1048576, delegationToken=, requestId=94489280512)
io.pravega.shared.protocol.netty.ConnectionFailedException: java.nio.channels.ClosedChannelException
        at io.pravega.client.netty.impl.ClientConnectionImpl.lambda$sendAsync$0(ClientConnectionImpl.java:75)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:987)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:869)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1391)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
        at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081)
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1128)
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.ClosedChannelException: null
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
```

**Comment by shrids** [comment]
This has been fixed with https://github.com/pravega/pravega/pull/3654 as part of fixing Issue 3638
> Ensure AsyncSegmentInputStreamImpl closes the connection incase a ConnectionFailedException is observed during io.pravega.client.netty.impl.ClientConnection#sendAsync()

@sumit-bm could you share the version with which this was observed?

**Comment by sumit-bm** [comment]
@SomeshJoshi19 filed with `Pravega version : 0.5.0-2236.5228e2d`

**Comment by shrids** [comment]
The behavior of `AsyncSegmentInputStream` is as follows. 
1. It obtains a client connection (it fetches the end point from the controller and establishes a Flow with the right SegmentStore.) and in case of any connection failures it retries it.
2. With the obtained client connection, the request is sent asynchronously over the wire using `io.pravega.client.netty.impl.ClientConnection#sendAsync(io.pravega.shared.protocol.netty.WireCommand, io.pravega.client.netty.impl.ClientConnection.CompletedCallback)` in case of exceptions observed while sending this the retry logic will ensure the command is resent.

The log snippet posted here points to an error while sending a request. On this exception the reader will retry sending it to the segment store after reestablishing a connection. 

Closing this issue since this a log message indicating a failure while sending a WireCommand over the network connection and will be retried.
