### ISSUE TITLE
Cleanup Exception Handling: `NullPointerException` is thrown inside controller while scaling up ZK

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#3752]
**While trying scaling up zookeeper from 4->7 and 7->10, each time `NPE` is thrown inside controller logs.
Even though zookeeper got scaled up successfully but following error was observed:**
```
2019-05-06 06:15:07,595 329876193 [ControllerServiceMain-EventThread] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background exception was not retry-able or retry gave up
java.lang.NullPointerException: null
        at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:179)
        at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:200)
        at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50)
        at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:144)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:865)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:635)
        at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152)
        at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:587)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:499)
```
Environment details: PKS / K8 with medium cluster:
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
```
Pravega version: 0.5.0-2236.5228e2d
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```
Logs of all the pods for reference are kept at shared location.

**Comment by sumit-bm** [comment]
Ref: #3105

**Comment by shiveshr** [comment]
This is in Curator and not pravega. 
This is not our issue and we cannot do much about it. Please open an issue on apache curator.
