### ISSUE TITLE
Sporadic Test Failure: DurableLogTests.testTruncateWithoutRecovery

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#3772]
**Problem description**
DurableLogTests.testTruncateWithoutRecovery
```
java.lang.AssertionError: Unexpected number of operations added after full truncation. expected:<3> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at io.pravega.segmentstore.server.logs.DurableLogTests.testTruncateWithoutRecovery(DurableLogTests.java:1142)
```

**Problem location**
DurableLogTests.

**Suggestions for an improvement**
Fix unit test

**Comment by andreipaduroiu** [comment]
fixed with #3773
