### ISSUE TITLE
AutoScale System Tests fail when authentication is enabled on Controller and Segment Store

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#3777]
**Problem description**
When authentication is enabled on Controller and Segment Store these system tests fail because of auth failure between controller and segment store:
AutoScaleTest 
Readtxnwriteautoscalewithfailovertest

**Problem location**
When controller tries to getCurrentSegments from segment store the call fails with auth error..

```
2019-05-03 11:58:59,057 65611 [grpc-default-executor-0] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getCurrentSegments called for stream _system/_requeststream.
2019-05-03 11:58:59,059 65613 [grpc-default-executor-0] ERROR i.p.c.s.r.g.v.ControllerServiceImpl - Controller api failed with authenticator error
java.lang.RuntimeException: io.pravega.auth.AuthorizationException: Access not allowed
        at io.pravega.controller.server.rpc.auth.AuthHelper.checkAuthorization(AuthHelper.java:55)
        at io.pravega.controller.server.rpc.auth.AuthHelper.checkAuthorizationAndCreateToken(AuthHelper.java:61)
        at io.pravega.controller.server.rpc.grpc.v1.ControllerServiceImpl.lambda$getCurrentSegments$13(ControllerServiceImpl.java:171)
        at io.pravega.controller.server.rpc.grpc.v1.ControllerServiceImpl.authenticateExecuteAndProcessResults(ControllerServiceImpl.java:440)
        at io.pravega.controller.server.rpc.grpc.v1.ControllerServiceImpl.authenticateExecuteAndProcessResults(ControllerServiceImpl.java:470)
        at io.pravega.controller.server.rpc.grpc.v1.ControllerServiceImpl.getCurrentSegments(ControllerServiceImpl.java:171)
        at io.pravega.controller.stream.api.grpc.v1.ControllerServiceGrpc$MethodHandlers.invoke(ControllerServiceGrpc.java:1858)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
```
**Suggestions for an improvement**

**Comment by pbelgundi** [comment]
https://emcnautilus.slack.com/files/UHA203HHU/FJD0AL6KW/testlogs.zip

**Comment by pbelgundi** [comment]
To reproduce run  system test - AutoScaleTest with -DsecurityEnabled=true flag
