### ISSUE TITLE
PravegaReader - Reader finished with Error java.io.UTFDataFormatException 

### ISSUE THREAD

**Issue by sumit-bm** [pravega/pravega#3778]
While exercising small workload IO (4 Reader, 3 Writer, scale type as EVENTS_PER_SECOND with retention enabled) experiencing readers are getting exhausted with `java.io.UTFDataFormatException` after few hours of operation.

Environment details: PKS / K8 with medium cluster:
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
```
Pravega version: issue-3747-and-3726-cherry-pick-0.5.0-2238.3cc4cf4
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```
Exception:
```
2019-05-11 10:30:40,166 97224155 [pool-7-thread-4] ERROR i.p.l.t.w.readers.PravegaReader - Reader finished with Error
java.lang.RuntimeException: java.io.UTFDataFormatException
        at io.pravega.client.stream.impl.JavaSerializer.deserialize(JavaSerializer.java:57)
        at io.pravega.client.stream.impl.JavaSerializer.deserialize(JavaSerializer.java:26)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:134)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:90)
        at io.pravega.longevity.testworker.workers.readers.PravegaReader.start(PravegaReader.java:99)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.UTFDataFormatException: null
        at java.io.ObjectInputStream$BlockDataInputStream.readUTFSpan(Unknown Source)
        at java.io.ObjectInputStream$BlockDataInputStream.readUTFBody(Unknown Source)
        at java.io.ObjectInputStream$BlockDataInputStream.readUTF(Unknown Source)
        at java.io.ObjectInputStream.readString(Unknown Source)
        at java.io.ObjectInputStream.readObject0(Unknown Source)
        at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
        at java.io.ObjectInputStream.readSerialData(Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
        at java.io.ObjectInputStream.readObject0(Unknown Source)
        at java.io.ObjectInputStream.readObject(Unknown Source)
        at io.pravega.client.stream.impl.JavaSerializer.deserialize(JavaSerializer.java:55)
        ... 7 common frames omitted
```

**Comment by shrids** [comment]
The reason for deserialization error has been fixed as part https://github.com/pravega/pravega/pull/3820
. Could you verify it with this fix?

**Comment by shrids** [comment]
Please reopen this issue if it is observed again.
