### ISSUE TITLE
ControllerRESTApi System Test fails when authentication is enabled.

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#3779]
**Problem description**
On enabling authentication in controller and segment store, ControllerRestAPI system test fails.
Default authentication credentials are being sent via jersey client.

**Problem location**
Test case fails with assertion error:
```
2019-05-13 12:03:25,458 2931 [OkHttp https://10.15.240.1/api/v1/namespaces/default/pods?pretty=false&includeUninitialized=true&labelSelector=component%3Dpravega-controller&watch=false] DEBUG i.p.t.s.f.kubernetes.K8sClient - 1 pod(s) found with label component=pravega-controller.
2019-05-13 12:03:25,465 2938 [Time-limited test] INFO  i.p.t.system.ControllerRestApiTest - REST Server URI: http://10.12.1.24:10080
2019-05-13 12:03:27,253 4726 [Time-limited test] INFO  i.p.t.system.ControllerRestApiTest - REST Server is running. Ping successful.
2019-05-13 12:04:51,296 88769 [main] ERROR i.p.t.s.f.TestFrameworkException - TestFramework Exception. Type: InternalError, Details: Exception while running test method: restApiTests
java.lang.AssertionError: Create scope status expected:<201> but was:<500>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at io.pravega.test.system.ControllerRestApiTest.restApiTests(ControllerRestApiTest.java:146)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)
```
**Suggestions for an improvement**

**Comment by Prabhaker24** [comment]
I am not able to reproduce this issue with pravega code after https://github.com/pravega/pravega/pull/4281 pr so we can close this issue

**Comment by Prabhaker24** [comment]
close #3779
