### ISSUE TITLE
IO request failed while starting IO client after successfully pravega deploy in one cluster

### ISSUE THREAD

**Issue by Ranjan-Padhi** [pravega/pravega#3784]
Starting IO client as well as creating scope after Pravega application deployed successfully in one cluster

Observation :-
IO request failed with showing scope create issue `io.pravega.client.stream.impl.ControllerFailureException: Failed to create scope: Scope`
 
As per log, the communication between controller and segmentstore during scope creation failed due to below exception

NOTE :- This issue observed in one particular cluster, where pravega deployed successfully but IO request failing, we have re-installed pravega but same behavior

Environment details: PKS / K8 with medium cluster:
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
5 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend 
```
Pravega details:
```
Pravega version : 0.5.0-2236.5228e2d
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```
Controler log:-
```
2019-05-16 11:58:58,233 2065910 [controllerpool-14] ERROR i.p.c.s.r.g.v.ControllerServiceImpl - Controller api failed with error:
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$UnknownException: get entry: key: _system table: _system/_tables/scopes
        at io.pravega.controller.store.stream.PravegaTablesStoreHelper.lambda$null$49(PravegaTablesStoreHelper.java:515)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.pravega.controller.server.SegmentHelper.handleError(SegmentHelper.java:1179)
        at io.pravega.controller.server.SegmentHelper.access$100(SegmentHelper.java:65)
        at io.pravega.controller.server.SegmentHelper$14.processingFailure(SegmentHelper.java:988)
        at io.pravega.controller.server.SegmentStoreConnectionManager$ReusableReplyProcessor.execute(SegmentStoreConnectionManager.java:235)
        at io.pravega.controller.server.SegmentStoreConnectionManager$ReusableReplyProcessor.processingFailure(SegmentStoreConnectionManager.java:368)
        at io.pravega.client.netty.impl.FlowHandler.lambda$channelRead$2(FlowHandler.java:198)
        at java.util.Optional.ifPresent(Optional.java:159)
        at io.pravega.client.netty.impl.FlowHandler.channelRead(FlowHandler.java:194)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.controller.store.stream.StoreException$UnknownException: get entry: key: _system table: _system/_tables/scopes
        at io.pravega.controller.store.stream.StoreException.create(StoreException.java:108)
        at io.pravega.controller.store.stream.PravegaTablesStoreHelper.lambda$null$49(PravegaTablesStoreHelper.java:512)
        ... 40 common frames omitted
Caused by: java.lang.IllegalStateException: Segment already exists: _system/_tables/scopes
        at io.pravega.shared.protocol.netty.FailingReplyProcessor.segmentAlreadyExists(FailingReplyProcessor.java:75)
        at io.pravega.controller.server.SegmentStoreConnectionManager$ReusableReplyProcessor.execute(SegmentStoreConnectionManager.java:235)
        at io.pravega.controller.server.SegmentStoreConnectionManager$ReusableReplyProcessor.segmentAlreadyExists(SegmentStoreConnectionManager.java:258)
        at io.pravega.shared.protocol.netty.WireCommands$SegmentAlreadyExists.process(WireCommands.java:238)
        at io.pravega.shared.protocol.netty.ReplyProcessor.process(ReplyProcessor.java:20)
        at io.pravega.client.netty.impl.FlowHandler.lambda$channelRead$2(FlowHandler.java:196)
```
But as per tar2 directory structure in segmentstore there is no `_tables/scopes` folder under _system folder
```
root@osboxes:~/K8_Full_Log/pravega-k8s-logs# kubectl exec -it pravega-pravega-segmentstore-0 -- /bin/sh
/opt/pravega #
/opt/pravega # cd /mnt/tier2/_system/
/mnt/tier2/_system # ls -lrt
total 2
drwxr-xr-x    2 nobody   42949672        53 May 16 11:25 containers
```

SegmentStore Log:-
```
ystem/_tables/scopes, delegationToken=, keys=[WireCommands.TableKey(data=UnpooledHeapByteBuf(ridx: 0, widx: 7, cap: 7/7), keyVersion=-9223372036854775808)]).
2019-05-16 12:02:59,845 2261322 [storage-io-50] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=462] Segment '_system/_tables/scopes' already exists and cannot perform operation 'readTable'.
2019-05-16 12:02:59,849 2261326 [grpc-default-executor-0] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getCurrentSegments with trace id 0 failed with server error.
io.grpc.StatusRuntimeException: INTERNAL: get entry: key: _system table: _system/_tables/scopes
        at io.grpc.Status.asRuntimeException(Status.java:530)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-05-16 12:03:02,343 2263820 [epollEventLoopGroup-11-2] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=673] Reading from table WireCommands.ReadTable(type=READ_TABLE, requestId=673, segment=_system/_tables/scopes, delegationToken=, keys=[WireCommands.TableKey(data=UnpooledHeapByteBuf(ridx: 0, widx: 7, cap: 7/7), keyVersion=-9223372036854775808)]).
```

**Comment by Ranjan-Padhi** [comment]
Find the attached K8 log
[pravega-k8s-logging-2019-05-16-07-55-06.zip](https://github.com/pravega/pravega/files/3187258/pravega-k8s-logging-2019-05-16-07-55-06.zip)

**Comment by andreipaduroiu** [comment]
The most interesting part was just above your snippet:

**Comment by sachin-j-joshi** [comment]
This issue is caused by hardware that is not in healthy state. 
At this point there is nothing actionable to be done at the code level.
CC: @sumit-bm

**Comment by shiveshr** [comment]
@sachin-j-joshi @andreipaduroiu 
The response from segment store in case of encountering the error could be made relevant. Currently its sending back SegmentAlreadyExists, which is out of context. It causes read failure for stream metadata. 
In worst case it can cause workflow failure on controller. Which can leave metadata in some intermediate state and no progress could be made on stream because of it. For example a failed partially completed scale operation could be left hanging and no subsequent scales on the stream would be performed. 

So this warrants code level fix to send back appropriate response from segment store.

**Comment by andreipaduroiu** [comment]
It sends that exception back because its is an unexpected exception. Any exception which doesn't make sense is propagated up the call stack. This includes IOException, Exception, IllegalArgException, etc.

Like @sachin-j-joshi said, this is due to Tier 2 throwing some abnormal errors back at us. Since we don't expect those on this path, we bubble them up. In this case it happened to be `SegmentAlreadyExistsException`.

**Comment by shiveshr** [comment]
I understand the argument. However, my concern is that the exception that i see is a generic one - `FileSystemException/IO error`. 
And from the logs i am not able to determine how this gets translated into SegmentAlreadyExists. 
I would expect SegmentAlreadyExists translation to happen for File Exists like error messages for our attempts to create files. 
So maybe i am missing something in the logs. It would be good if you could point out the link there.

**Comment by andreipaduroiu** [comment]
This was caused due to faulty hardware, which has since been fixed. Please create a new issue if you notice this again.
