### ISSUE TITLE
Soft Handle Exception: Observing Controller api failed error with "ERROR i.p.c.s.r.g.v.ControllerServiceImpl" and exception "concurrent.CompletionException: io.pravega.controller.store.task.LockFailedException" while creating IO stream 

### ISSUE THREAD

**Issue by vedanthh** [pravega/pravega#3798]
**Observing Controller api failed error with "ERROR i.p.c.s.r.g.v.ControllerServiceImpl" and exception "concurrent.CompletionException: io.pravega.controller.store.task.LockFailedException" while creating IO stream using Longevity**

Environment details: PKS / K8 with medium cluster:
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
```
Pravega version: 0.5.0-2251.e0e61de
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```
**Controller log error:** 
[pravega-k8s-logging-2019-05-20-05-42-02.zip](https://github.com/pravega/pravega/files/3197343/pravega-k8s-logging-2019-05-20-05-42-02.zip)

```
2019-05-20 09:00:42,231 15123884 [grpc-default-executor-3] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=5869384100952760020] createStream called for stream longevity/midScale.
2019-05-20 09:00:42,304 15123957 [controllerpool-15] ERROR i.p.c.s.r.g.v.ControllerServiceImpl - Controller api failed with error:
java.util.concurrent.CompletionException: io.pravega.controller.store.task.LockFailedException: Failed locking resource longevity/midScale.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.controller.store.task.LockFailedException: Failed locking resource longevity/midScale.
        at io.pravega.controller.store.task.ZKTaskMetadataStore.acquireLock(ZKTaskMetadataStore.java:56)
        at io.pravega.controller.store.task.AbstractTaskMetadataStore.lambda$lock$0(AbstractTaskMetadataStore.java:56)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        ... 7 common frames omitted
Caused by: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /pravega/pravega/taskIndex/longevity_%_midScale
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:123)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1525)
        at org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1181)
        at org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1158)
        at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64)
        at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)
        at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:1155)
        at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:605)
        at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:595)
        at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:49)
        at io.pravega.controller.store.task.ZKTaskMetadataStore.acquireLock(ZKTaskMetadataStore.java:53)
        ... 9 common frames omitted
```

**Comment by shiveshr** [comment]
this is expected if multiple concurrent attempts to create the same stream are attempted.

**Comment by vedanthh** [comment]
With earlier build i haven't seen this issue and I'm running only one longevity workload i.e midscale, I haven't performed any  multiple concurrent attempts to create the same stream.

**Comment by fpj** [comment]
Check this out:

```
2019-05-20 04:50:57,185 138996 [clientInternal-1] INFO  i.p.client.netty.impl.FlowHandler - Creating Flow 47 for endpoint 172.24.24.16. The current Channel is [id: 0x16b6eee1, L:/172.24.24.7:37872 - R:172.24.24.16/172.24.24.16:12345].
2019-05-20 09:00:43,416 15125227 [Curator-PathChildrenCache-2] INFO  i.p.c.server.bucket.BucketService - RetentionService: New stream longevity/midScale added to bucket 6 
2019-05-20 09:00:43,498 15125309 [grpc-default-executor-2] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=163542902758856790] createStream called for stream longevity/_RGLongevityMidScale.
```

Look at the timestamps of the two first log lines I posted, there is a 4-hour difference! Most likely another controller instance took over during that period and completed the task. The locking is reflecting the failover. There is nothing in the logs explaining why that instance was stalled for this long, though.

Following the logs, I see that the controller instance operating regular until I start seeing errors related to scaling:

```
2019-05-20 09:18:55,192 16217003 [controllerpool-2] WARN  i.p.c.s.stream.PersistentStreamBase - scale precondition failed [6]
2019-05-20 09:18:55,193 16217004 [controllerpool-2] WARN  i.p.c.s.e.r.ScaleOperationTask - [requestId=6707420427774582119] processing scale request for longevity/midScale segments [6] failed {}
io.pravega.controller.store.stream.EpochTransitionOperationExceptions$PreConditionFailureException: null
	at io.pravega.controller.store.stream.PersistentStreamBase.lambda$null$91(PersistentStreamBase.java:706)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

and I keep seeing them for quite some time. Unfortunately, that's not the issue reported here. The issue reported here does not seem to be an issue for me, except for the 4-hour stall, which is also not part of the issue reported here. For completeness, this is the log file I'm looking at:

[controller.log](https://github.com/pravega/pravega/files/3197861/controller.log)

**Comment by shiveshr** [comment]
@vedanthh 
I can see multiple createStreams being called for the said stream:

pravega-pravega-controller-78dbbc46f9:
```
2019-05-20 09:00:42,216 15123869 [grpc-default-executor-3] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=5869384100952760020] createStream called for stream longevity/midScale.
2019-05-20 09:00:42,231 15123884 [grpc-default-executor-3] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=5869384100952760020] createStream called for stream longevity/midScale.
2019-05-20 09:00:42,314 15123967 [grpc-default-executor-3] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=5869384100952760020] createStream called for stream longevity/midScale.
2019-05-20 09:00:42,337 15123990 [grpc-default-executor-3] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=5869384100952760020] createStream called for stream longevity/midScale.
2019-05-20 09:00:42,451 15124104 [grpc-default-executor-3] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=5869384100952760020] createStream called for stream longevity/midScale.
2019-05-20 09:00:43,470 15125123 [grpc-default-executor-3] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=213817962207249657] createStream called for stream longevity/midScale.
```

```
java.util.concurrent.CompletionException: io.pravega.controller.store.task.LockFailedException: Failed locking resource longevity/midScale.
Caused by: io.pravega.controller.store.task.LockFailedException: Failed locking resource longevity/midScale.
java.util.concurrent.CompletionException: io.pravega.controller.store.task.LockFailedException: Failed locking resource longevity/midScale.
Caused by: io.pravega.controller.store.task.LockFailedException: Failed locking resource longevity/midScale.
java.util.concurrent.CompletionException: io.pravega.controller.store.task.LockFailedException: Failed locking resource longevity/midScale.
Caused by: io.pravega.controller.store.task.LockFailedException: Failed locking resource longevity/midScale.
java.util.concurrent.CompletionException: io.pravega.controller.store.task.LockFailedException: Failed locking resource longevity/midScale.
Caused by: io.pravega.controller.store.task.LockFailedException: Failed locking resource longevity/midScale.
```

**Comment by shiveshr** [comment]
@fpj what you are looking at is creation of multiple readergroups for this stream being attempted concurrently. 

Secondly, the precondition failure log during scale is a log that should not be logged at error level.. there is already an issue for it.. we will tone down the log level for those errors.

**Comment by fpj** [comment]
From another controller log file in the zip, I suppose this is from a different controller instance. Same gap, and the error is about the stream you are referring to:

```
2019-05-20 04:50:48,305 129958 [epollEventLoopGroup-2-4] INFO  i.p.s.p.netty.FailingReplyProcessor - Received hello: WireCommands.Hello(type=HELLO, highVersion=8, lowVersion=5)
2019-05-20 09:00:42,159 15123812 [grpc-default-executor-2] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=1422773730211995944] createScope called for scope longevity.
2019-05-20 09:00:42,160 15123813 [grpc-default-executor-3] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=1422773730211995944] createScope called for scope longevity.
2019-05-20 09:00:42,165 15123818 [controllerpool-5] INFO  i.p.client.netty.impl.FlowHandler - Closing Flow -1 for endpoint 172.24.24.16
2019-05-20 09:00:42,165 15123818 [controllerpool-15] INFO  i.p.client.netty.impl.FlowHandler - Closing Flow -1 for endpoint 172.24.24.14
2019-05-20 09:00:42,165 15123818 [controllerpool-15] INFO  i.p.client.netty.impl.FlowHandler - Closing Flow -1 for endpoint 172.24.24.14
2019-05-20 09:00:42,165 15123818 [controllerpool-15] INFO  i.p.client.netty.impl.FlowHandler - Closing Flow -1 for endpoint 172.24.24.14
2019-05-20 09:00:42,165 15123818 [controllerpool-15] INFO  i.p.client.netty.impl.FlowHandler - Closing Flow -1 for endpoint 172.24.24.14
2019-05-20 09:00:42,165 15123818 [controllerpool-15] INFO  i.p.client.netty.impl.FlowHandler - Closing Flow -1 for endpoint 172.24.24.14
2019-05-20 09:00:42,165 15123818 [controllerpool-15] INFO  i.p.client.netty.impl.FlowHandler - Closing Flow -1 for endpoint 172.24.24.14
2019-05-20 09:00:42,166 15123819 [controllerpool-15] INFO  i.p.client.netty.impl.FlowHandler - Creating a new connection with flow disabled for endpoint 172.24.24.14. The current Channel is null.
2019-05-20 09:00:42,166 15123819 [controllerpool-5] INFO  i.p.client.netty.impl.FlowHandler - Creating a new connection with flow disabled for endpoint 172.24.24.14. The current Channel is null.
2019-05-20 09:00:42,166 15123819 [epollEventLoopGroup-2-2] INFO  i.p.client.netty.impl.FlowHandler - Connection established with endpoint 172.24.24.14 on ChannelId [id: 0x9c542993]
2019-05-20 09:00:42,167 15123820 [epollEventLoopGroup-2-1] INFO  i.p.client.netty.impl.FlowHandler - Connection established with endpoint 172.24.24.14 on ChannelId [id: 0xaddaf0b6]
2019-05-20 09:00:42,171 15123824 [epollEventLoopGroup-2-2] INFO  i.p.s.p.netty.FailingReplyProcessor - Received hello: WireCommands.Hello(type=HELLO, highVersion=8, lowVersion=5)
2019-05-20 09:00:42,171 15123824 [epollEventLoopGroup-2-1] INFO  i.p.s.p.netty.FailingReplyProcessor - Received hello: WireCommands.Hello(type=HELLO, highVersion=8, lowVersion=5)
2019-05-20 09:00:42,179 15123832 [epollEventLoopGroup-2-2] INFO  i.p.controller.server.SegmentHelper - [requestId=244] updateTableEntries request for _system/_tables/scopes tableSegment completed.
2019-05-20 09:00:42,180 15123833 [epollEventLoopGroup-2-1] WARN  i.p.controller.server.SegmentHelper - [requestId=245] updateTableEntries request for _system/_tables/scopes tableSegment failed with TableKeyBadVersion.
2019-05-20 09:00:42,184 15123837 [controllerpool-4] INFO  i.p.client.netty.impl.FlowHandler - Creating a new connection with flow disabled for endpoint 172.24.24.16. The current Channel is null.
2019-05-20 09:00:42,185 15123838 [epollEventLoopGroup-2-3] INFO  i.p.client.netty.impl.FlowHandler - Connection established with endpoint 172.24.24.16 on ChannelId [id: 0x217d9655]
2019-05-20 09:00:42,206 15123859 [epollEventLoopGroup-2-3] INFO  i.p.s.p.netty.FailingReplyProcessor - Received hello: WireCommands.Hello(type=HELLO, highVersion=8, lowVersion=5)
2019-05-20 09:00:42,216 15123869 [grpc-default-executor-3] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=5869384100952760020] createStream called for stream longevity/midScale.
2019-05-20 09:00:42,223 15123876 [epollEventLoopGroup-2-3] INFO  i.p.controller.server.SegmentHelper - [requestId=247] CreateTableSegment _system/_tables/longevity/streamsInScope.#.c3698e5a-1f8a-45c2-b124-d7d0a0e79df0 SegmentCreated
2019-05-20 09:00:42,231 15123884 [grpc-default-executor-3] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=5869384100952760020] createStream called for stream longevity/midScale.
2019-05-20 09:00:42,304 15123957 [controllerpool-15] ERROR i.p.c.s.r.g.v.ControllerServiceImpl - Controller api failed with error: 
java.util.concurrent.CompletionException: io.pravega.controller.store.task.LockFailedException: Failed locking resource longevity/midScale.
```

I don't know what caused the gaps in the logs.

**Comment by EronWright** [comment]
Saw a contemporary example of this today.  The error percolates back to the caller, which retries and again fails.   Is the call supposed to be idempotent?
