### ISSUE TITLE
Observing "java.util.concurrent.TimeoutException" on scaling up segments in Pravega

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega#3799]
**Problem description**
On scaling up segments from 10 to 1000 in a single stream, observed `java.util.concurrent.TimeoutException` and IOs failed to write or read any events. Again on an attempt to pass IOs in the above scaled up stream, instability is observed.
On scaling up the segments, the output is:
```
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.100.200.25:9090
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.100.200.25:9090
[main] INFO io.pravega.client.admin.impl.StreamManagerImpl - Creating scope: Scope
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=-9135526021934813531] Tagging client request (createScope-Scope).
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[[/10.100.200.25:9090]/{}]]
[grpc-default-executor-0] WARN io.pravega.client.stream.impl.ControllerImpl - [requestId=-9135526021934813531] Scope already exists: Scope
[main] INFO io.pravega.client.admin.impl.StreamManagerImpl - Creating scope/stream: Scope/scaleTest1 with configuration: StreamConfiguration(scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=1000), retentionPolicy=null)
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=2577659839454995752] Tagging client request (createStream-Scope-scaleTest1).
[grpc-default-executor-0] WARN io.pravega.client.stream.impl.ControllerImpl - [requestId=2577659839454995752] Stream already exists: scaleTest1
[pool-1-thread-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[[/10.100.200.25:9090]/{}]]
Current segments of the stream: scaleTest1 = 10
The stream: scaleTest1 will be manually scaling to 1000 segments
[main] INFO io.pravega.client.admin.impl.StreamManagerImpl - Updating scope/stream: Scope/scaleTest1 with configuration: StreamConfiguration(scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=1000), retentionPolicy=null)
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=7524702109985043683] Tagging client request (updateStream-Scope-scaleTest1).
[grpc-default-executor-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=7524702109985043683] Successfully updated stream: scaleTest1
[pool-1-thread-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=1645663703453408204] Tagging client request (scaleStream-Scope-scaleTest1-1558204288435).
[grpc-default-executor-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=1645663703453408204] Successfully started scale stream: scaleTest1
java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
        at com.emc.pravega.perf.PravegaStreamHandler.scale(PravegaStreamHandler.java:115)
        at com.emc.pravega.perf.PravegaPerfTest.main(PravegaPerfTest.java:125)
```
On passing a workload of 10 writers, 10 readers, 1000 bytes data, 100 events/sec and runtime as 300secs on the above scaled up stream, the results are :
```
1 records Writing,       0.1 records/sec,     0.000 MB/sec, 9819.0000 ms avg latency.
3 records Writing,       1.1 records/sec,     0.001 MB/sec, 934.0000 ms avg latency.
1 records Writing,       0.5 records/sec,     0.001 MB/sec, 1854.0000 ms avg latency.
7 records Writing,       3.0 records/sec,     0.003 MB/sec, 333.2857 ms avg latency.
2 records Writing,       1.3 records/sec,     0.001 MB/sec, 757.0000 ms avg latency.
1 records Writing,       0.3 records/sec,     0.000 MB/sec, 3720.0000 ms avg latency.
3 records Writing,       2.2 records/sec,     0.002 MB/sec, 462.6667 ms avg latency.
```
Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.
Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Pravega version : 0.5.0-2236.5228e2d
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```

**Comment by fpj** [comment]
If you observe the stack trace, it is not Pravega that is throwing, but the benchmark code that is being used here:

```
java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
        at com.emc.pravega.perf.PravegaStreamHandler.scale(PravegaStreamHandler.java:115)
        at com.emc.pravega.perf.PravegaPerfTest.main(PravegaPerfTest.java:125)
```

Even though the line numbers do not match, I suspect that the block throwing is this one because of the timed get:

```
if (!scaleStatus.get(timeout, TimeUnit.SECONDS)) {
            throw new TimeoutException("ERROR : Scale operation on stream " + stream + " did not complete");
        }
```

https://github.com/pravega/pravega-benchmark/blame/master/src/main/java/io/pravega/perf/PravegaStreamHandler.java#L111

but the line code mismatch implies that the code used might be stale. 

The timeout is determined by the caller, and I don't know what has been used for this test. At this point, I can't tell whether that's an issue or not, there isn't enough information to determine.

**Comment by shiveshr** [comment]
@SomeshJoshi19 can you please share logs from this run.

**Comment by SomeshJoshi19** [comment]
The above seen exception `java.util.concurrent.TimeoutException` occurs within 15-30 secs of running the tool. Even though the run time input being given for the run was 300 secs and even 600 secs, this issue was observed during scaling up process. We have not for normal stream runs using the same tool with same workload for 60 secs this exception was not observed. I will try the same to run with the latest Benchmark tool and update.

**Comment by SomeshJoshi19** [comment]
@shiveshr Uploaded K8s logs at the shared location.

**Comment by SomeshJoshi19** [comment]
As discussed I have tried to retest this issue using latest pravega version : `0.5.0-2269.6f8a820`, benchmark Feb build with the client same as pravega version and found the same exception getting  again as reported before `java.util.concurrent.TimeoutException` on scaling down the segments from 3500 to 90. 

The IO workload being supplied during all the scale operations is: -
10 readers, 10 writers, 100 events/sec rate, 1000 bytes data size and run time as 300 secs.

Output log from the tool:
```
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.100.200.225:9090
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.100.200.225:9090
[main] INFO io.pravega.client.admin.impl.StreamManagerImpl - Creating scope: NewScope
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=-2555002699232085963] Tagging client request (createScope-NewScope).
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[[/10.100.200.225:9090]/{}]]
[grpc-default-executor-0] WARN io.pravega.client.stream.impl.ControllerImpl - [requestId=-2555002699232085963] Scope already exists: NewScope
[main] INFO io.pravega.client.admin.impl.StreamManagerImpl - Creating scope/stream: NewScope/testSegScale2 with configuration: StreamConfiguration(scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=90), retentionPolicy=null)
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=4114079145797667538] Tagging client request (createStream-NewScope-testSegScale2).
[grpc-default-executor-0] WARN io.pravega.client.stream.impl.ControllerImpl - [requestId=4114079145797667538] Stream already exists: testSegScale2
[pool-1-thread-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[[/10.100.200.225:9090]/{}]]
Current segments of the stream: testSegScale2 = 3500
The stream: testSegScale2 will be manually scaling to 90 segments
[main] INFO io.pravega.client.admin.impl.StreamManagerImpl - Updating scope/stream: NewScope/testSegScale2 with configuration: StreamConfiguration(scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=90), retentionPolicy=null)
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=-6463462318003313142] Tagging client request (updateStream-NewScope-testSegScale2).
[grpc-default-executor-0] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=-6463462318003313142] Successfully updated stream: testSegScale2
[pool-1-thread-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=-8947718337821630076] Tagging client request (scaleStream-NewScope-testSegScale2-1559919726152).
[grpc-default-executor-0] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=-8947718337821630076] Successfully started scale stream: testSegScale2
java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
        at com.emc.pravega.perf.PravegaStreamHandler.scale(PravegaStreamHandler.java:119)
        at com.emc.pravega.perf.PravegaPerfTest.main(PravegaPerfTest.java:116)
```

Observations from the retest: -

**a)** The basic scenarios of scaling operations over segments such as:  {1 -> 10, 10 -> 1}, {10 -> 20, 20 -> 10}, {10 -> 100, 100 -> 10}  works fine with the current Pravega version. IOs are able to read and write events properly as per expected results along with successful segment creation attempts. **[1]**

**b)** Whereas in case of increasing the segment scaling load and on carrying out multiple iterations, it is observed that there is instability in the system to perform these operations successfully. As the IO read and write operations seems to under perform on these scenarios by exhibiting higher latency values and lesser number of event generation on comparing it with the results of normal runs. **[2]**

**c)** While performing these tests it is also being observed that the controller stalls multiple times for 2 mins to 10 mins in a 5 mins run after getting updated for some iterations . **[3]**

**[1]**
```
     595 records Reading,     119.0 records/sec,   0.11 MB/sec,     2.0 ms avg latency,    13.0 ms max latency
     490 records Writing,      98.0 records/sec,   0.09 MB/sec,     7.8 ms avg latency,   107.0 ms max latency
     491 records Reading,      98.2 records/sec,   0.09 MB/sec,     2.3 ms avg latency,    10.0 ms max latency
     490 records Writing,      97.9 records/sec,   0.09 MB/sec,     6.8 ms avg latency,   106.0 ms max latency
     487 records Reading,      97.4 records/sec,   0.09 MB/sec,     2.3 ms avg latency,    15.0 ms max latency
     489 records Writing,      97.7 records/sec,   0.09 MB/sec,     7.5 ms avg latency,   107.0 ms max latency
     487 records Reading,      97.4 records/sec,   0.09 MB/sec,     1.8 ms avg latency,    10.0 ms max latency 
     487 records Writing,      97.2 records/sec,   0.09 MB/sec,     7.7 ms avg latency,   107.0 ms max latency 
30238 records Writing, 101.064 records/sec, 1000 bytes record size, 0.10 MB/sec, 7.8 ms avg latency, 258.0 ms max latency, 5 ms 50th, 18 ms 95th, 77 ms 99th, 173 ms 99.9th.
30237 records Reading, 100.877 records/sec, 1000 bytes record size, 0.10 MB/sec, 2.2 ms avg latency, 874.0 ms max latency, 0 ms 50th, 10 ms 95th, 10 ms 99th, 19 ms 99.9th.
```

**[2]**
```
 19 records Reading,       3.8 records/sec,   0.00 MB/sec,   113.3 ms avg latency,  1199.0 ms max latency
      32 records Writing,       6.4 records/sec,   0.01 MB/sec,   331.2 ms avg latency,   887.0 ms max latency
      28 records Reading,       5.6 records/sec,   0.01 MB/sec,   821.1 ms avg latency,  5744.0 ms max latency
      18 records Writing,       3.4 records/sec,   0.00 MB/sec,   465.9 ms avg latency,  2464.0 ms max latency
       2 records Writing,       0.0 records/sec,   0.00 MB/sec,  1821.5 ms avg latency,  2973.0 ms max latency
       0 records Writing,       0.0 records/sec,   0.00 MB/sec,     NaN ms avg latency,     0.0 ms max latency
      11 records Reading,       0.1 records/sec,   0.00 MB/sec,   733.1 ms avg latency,  4169.0 ms max latency
       5 records Writing,       0.1 records/sec,   0.00 MB/sec, 47096.6 ms avg latency, 101201.0 ms max latency
       0 records Reading,       0.0 records/sec,   0.00 MB/sec,     NaN ms avg latency,     0.0 ms max latency
       8 records Reading,       1.6 records/sec,   0.00 MB/sec,  4930.5 ms avg latency, 39419.0 ms max latency
      46 records Writing,       8.1 records/sec,   0.01 MB/sec,  2228.5 ms avg latency, 38631.0 ms max latency
      25 records Reading,       5.0 records/sec,   0.00 MB/sec,   515.6 ms avg latency,  4933.0 ms max latency
      27 records Writing,       5.3 records/sec,   0.01 MB/sec,   554.6 ms avg latency,  1557.0 ms max latency
      25 records Reading,       5.0 records/sec,   0.00 MB/sec,  1159.7 ms avg latency, 10448.0 ms max latency
      32 records Writing,       4.9 records/sec,   0.00 MB/sec,  1216.3 ms avg latency,  3778.0 ms max latency
      53 records Writing,       7.0 records/sec,   0.01 MB/sec,  4895.3 ms avg latency,  9574.0 ms max latency
       4 records Reading,       0.4 records/sec,   0.00 MB/sec,  1566.5 ms avg latency,  6265.0 ms max latency
      80 records Reading,      16.0 records/sec,   0.02 MB/sec,  1300.5 ms avg latency, 25764.0 ms max latency
      23 records Writing,       4.1 records/sec,   0.00 MB/sec,  5913.5 ms avg latency, 13327.0 ms max latency
      30 records Reading,       5.8 records/sec,   0.01 MB/sec,  1030.9 ms avg latency, 24266.0 ms max latency
      23 records Writing,       4.5 records/sec,   0.00 MB/sec,   632.1 ms avg latency,  2242.0 ms max latency
       9 records Reading,       1.7 records/sec,   0.00 MB/sec,  1404.7 ms avg latency,  4184.0 ms max latency
      23 records Writing,       4.2 records/sec,   0.00 MB/sec,   638.1 ms avg latency,  1971.0 ms max latency
      16 records Reading,       3.2 records/sec,   0.00 MB/sec,  1407.3 ms avg latency,  7092.0 ms max latency
      17 records Writing,       3.1 records/sec,   0.00 MB/sec,   779.8 ms avg latency,  3495.0 ms max latency
15447 records Writing, 25.960 records/sec, 1000 bytes record size, 0.02 MB/sec, 2590.4 ms avg latency, 101201.0 ms max latency, 1940 ms 50th, 7037 ms 95th, 7923 ms 99th, 9573 ms 99.9th.
15400 records Reading, 25.819 records/sec, 1000 bytes record size, 0.02 MB/sec, 24.1 ms avg latency, 39419.0 ms max latency, 0 ms 50th, 1 ms 95th, 1 ms 99th, 7086 ms 99.9th.
```

**[3]**
```
2019-06-07 12:43:44,839 108580497 [grpc-default-executor-2878] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getDelegationToken called for stream NewScope/testSegScale2.
2019-06-07 12:43:44,839 108580497 [grpc-default-executor-2853] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getURI called for segment NewScope/testSegScale2/47244646184.
2019-06-07 12:43:44,841 108580499 [grpc-default-executor-2853] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getURI called for segment NewScope/testSegScale2/47244645808.
2019-06-07 12:43:44,843 108580501 [grpc-default-executor-2853] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getURI called for segment NewScope/testSegScale2/47244645808.
2019-06-07 12:43:44,843 108580501 [grpc-default-executor-2878] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getURI called for segment NewScope/testSegScale2/47244645808.
2019-06-07 12:46:54,620 108770278 [grpc-default-executor-2963] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getDelegationToken called for stream NewScope/testSegScale2.
2019-06-07 12:46:54,643 108770301 [grpc-default-executor-2963] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getURI called for segment NewScope/testSegScale2/47244645770.
2019-06-07 12:46:54,644 108770302 [grpc-default-executor-2964] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getDelegationToken called for stream NewScope/testSegScale2.
2019-06-07 12:46:54,698 108770356 [grpc-default-executor-2963] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getURI called for segment NewScope/testSegScale2/47244645770.
2019-06-07 12:46:54,698 108770356 [grpc-default-executor-2964] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getDelegationToken called for stream NewScope/testSegScale2.
```

```
2019-06-07 12:05:41,413 106297071 [grpc-default-executor-2693] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - isSegmentValid called for segment NewScope/_RGtestSegScale2/0.
2019-06-07 12:05:41,421 106297079 [grpc-default-executor-2693] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getDelegationToken called for stream NewScope/_RGtestSegScale2.
2019-06-07 12:05:41,424 106297082 [grpc-default-executor-2693] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getURI called for segment NewScope/_RGtestSegScale2/0.
2019-06-07 12:05:41,426 106297084 [grpc-default-executor-2693] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getDelegationToken called for stream NewScope/_RGtestSegScale2.
2019-06-07 12:05:41,426 106297084 [grpc-default-executor-2694] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getURI called for segment NewScope/_RGtestSegScale2/0.
2019-06-07 12:05:41,431 106297089 [grpc-default-executor-2693] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getURI called for segment NewScope/_RGtestSegScale2/0.
2019-06-07 12:15:27,904 106883562 [controllerpool-1] INFO  i.p.client.netty.impl.FlowHandler - Closing Flow -1 for endpoint 172.24.10.17
2019-06-07 12:15:27,904 106883562 [controllerpool-12] INFO  i.p.client.netty.impl.FlowHandler - Closing Flow -1 for endpoint 172.24.10.16
2019-06-07 12:15:27,904 106883562 [controllerpool-1] INFO  i.p.client.netty.impl.FlowHandler - Closing Flow -1 for endpoint 172.24.10.17
2019-06-07 12:15:27,904 106883562 [controllerpool-12] INFO  i.p.client.netty.impl.FlowHandler - Closing Flow -1 for endpoint 172.24.10.16
```

**Comment by shiveshr** [comment]
Few questions:
1. Have you updated the tool to have a higher timeout than 10 seconds?

2. You mentioned controller stalls? What exactly do you mean by controller stalls for 2 to 10 minutes? 
>While performing these tests it is also being observed that the controller stalls multiple times for 2 mins to 10 mins in a 5 mins run after getting updated for some iterations . 

Lack of logs for those time windows that you have posted do not indicate a stall. It merely indicates that clients may not be requesting any information from controller during that window. So there is no activity on controller. 
If it coincides with clients making requests and controller not processing them then it would be a matter of concern.

**Comment by SomeshJoshi19** [comment]
@shiveshr 
ans 1)  No, I didn't update the tool for higher timeout value. It follows fixed number of segments function.

ans 2)  By mentioning Controller stalls, I meant that client stalls to send IO read and write request and at the same time there is no GRPC call activity being observed in any of the two deployed controllers.

ans 3) By instability I mean for higher values of segment scaling operations  ( like 2000 - 3000 segments ) frequent occurrence of error messages like `https://github.com/pravega/pravega/issues/3676` and connection loss exception along with performance related issues.

**Comment by shiveshr** [comment]
This is not a pravega issue. It is a benchmark tool issue. Please address it there. I am closing this issue.
