### ISSUE TITLE
IO Failure observed on docker swarm setup while scaling segment store using "docker service scale pravega_segmentstore=N"

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#3800]
**IO Failure observed on docker swarm setup while scaling segment store using "docker service scale pravega_segmentstore=N"**

In a Docker Swarm environment, started moderate IO with Pravega Benchmark tool and tried scale up segment store from 1 to 2 using docker service scale pravega_segmentstore=2. IO failures had been observed (console snip below)

Docker swarm setup
```
1 Node - 1 Master Deployment:
1 Controller
1 Zookeeper
1 Segment Store
3 BookKeeper
1 Pravega_HDFS
```
Pravega details:
```
Pravega version : 0.5.0-2236.5228e2d
```
Steps Followed
```
1. Created Docker swarm setup
2. Started IO using pravega-benchmark tool
3. Scaled up segment store to 2 using "docker service scale pravega_segmentstore=2"
```
Getting following exception in scaled up Segment store:
```
2019-05-20 11:18:35,589 410944 [storage-io-187] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[3]: Iteration[382].Error.
io.pravega.segmentstore.storage.StorageNotPrimaryException: [Segment 'Scope/_RGtest2/0.#epoch.0$offset.0'] The current instance is no longer the primary writer for this StreamSegment.null
        at io.pravega.storage.hdfs.HDFSStorage.write(HDFSStorage.java:349)
        at io.pravega.segmentstore.storage.rolling.RollingStorage.write(RollingStorage.java:324)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$write$2(AsyncStorageWrapper.java:93)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$runAsync$12(AsyncStorageWrapper.java:171)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
Snip of  Benchmark console
```
java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=343597383680, segment=Scope/test2/3.#epoch.0, correctHost=, serverStackTrace=)
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:874)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl$State.failConnection(SegmentOutputStreamImpl.java:202)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl$State.access$700(SegmentOutputStreamImpl.java:94)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl.failConnection(SegmentOutputStreamImpl.java:516)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl.access$500(SegmentOutputStreamImpl.java:68)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl$ResponseProcessor.wrongHost(SegmentOutputStreamImpl.java:291)
        at io.pravega.shared.protocol.netty.WireCommands$WrongHost.process(WireCommands.java:125)
        at io.pravega.shared.protocol.netty.ReplyProcessor.process(ReplyProcessor.java:20)
        at io.pravega.client.netty.impl.FlowHandler.lambda$channelRead$2(FlowHandler.java:196)
        at java.util.Optional.ifPresent(Optional.java:159)
        at io.pravega.client.netty.impl.FlowHandler.channelRead(FlowHandler.java:194)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=343597383680, segment=Scope/test2/3.#epoch.0, correctHost=, serverStackTrace=)
        ... 36 more
[epollEventLoopGroup-4-1] INFO io.pravega.client.netty.impl.FlowHandler - Closing Flow 80 for endpoint 10.246.154.55
[epollEventLoopGroup-4-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Received AppendSetup WireCommands.AppendSetup(type=APPEND_SETUP, requestId=597000454144, segment=Scope/test2/2.#epoch.0, writerId=6dd423b2-4a6e-4ba8-8efa-a1c065cc83c6, lastEventNumber=23573)
[clientInternal-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Fetching endpoint for segment Scope/test2/3.#epoch.0, writerID: 0fd3921e-502d-4a2c-8ed2-e5a57a9a13e6
[clientInternal-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=10.246.154.55, port=12345) for Scope/test2/8.#epoch.0, writerID: 3690ac35-0d18-4678-8b90-29f6ac2babbe
[clientInternal-1] INFO io.pravega.client.netty.impl.ConnectionPoolImpl - Reusing connection: Connection(uri=PravegaNodeUri(endpoint=10.246.154.55, port=12345), flowHandler=io.pravega.client.netty.impl.FlowHandler@601f6b44, connected=java.util.concurrent.CompletableFuture@8117c28[Completed normally])
[clientInternal-1] INFO io.pravega.client.netty.impl.FlowHandler - Creating Flow 115 for endpoint 10.246.154.55. The current Channel is [id: 0x2c4270db, L:/10.0.2.15:47102 - R:10.246.154.55/10.246.154.55:12345].
[epollEventLoopGroup-4-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Received AppendSetup WireCommands.AppendSetup(type=APPEND_SETUP, requestId=579820584960, segment=Scope/test2/8.#epoch.0, writerId=a5e8e995-afb7-4021-b5e2-b2ffae150e90, lastEventNumber=-9223372036854775808)
[epollEventLoopGroup-4-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection setup complete for writer a5e8e995-afb7-4021-b5e2-b2ffae150e90
[epollEventLoopGroup-4-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Received AppendSetup WireCommands.AppendSetup(type=APPEND_SETUP, requestId=382252089344, segment=Scope/test2/2.#epoch.0, writerId=663f5a94-23c8-4d98-a307-defb0ec6cba9, lastEventNumber=-9223372036854775808)
[epollEventLoopGroup-4-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection setup complete for writer 663f5a94-23c8-4d98-a307-defb0ec6cba9
[clientInternal-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=10.246.154.55, port=12345) for Scope/test2/3.#epoch.0, writerID: 0fd3921e-502d-4a2c-8ed2-e5a57a9a13e6
[clientInternal-1] INFO io.pravega.client.netty.impl.ConnectionPoolImpl - Reusing connection: Connection(uri=PravegaNodeUri(endpoint=10.246.154.55, port=12345), flowHandler=io.pravega.client.netty.impl.FlowHandler@601f6b44, connected=java.util.concurrent.CompletableFuture@8117c28[Completed normally])
[clientInternal-1] INFO io.pravega.client.netty.impl.FlowHandler - Creating Flow 80 for endpoint 10.246.154.55. The current Channel is [id: 0x2c4270db, L:/10.0.2.15:47102 - R:10.246.154.55/10.246.154.55:12345].
[epollEventLoopGroup-4-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Received AppendSetup WireCommands.AppendSetup(type=APPEND_SETUP, requestId=493921239040, segment=Scope/test2/8.#epoch.0, writerId=3690ac35-0d18-4678-8b90-29f6ac2babbe, lastEventNumber=25321)
[epollEventLoopGroup-4-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Failing connection for writer 0fd3921e-502d-4a2c-8ed2-e5a57a9a13e6 with exception io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=343597383680, segment=Scope/test2/3.#epoch.0, correctHost=, serverStackTrace=)
[epollEventLoopGroup-4-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Handling exception io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=343597383680, segment=Scope/test2/3.#epoch.0, correctHost=, serverStackTrace=) for connection io.pravega.client.netty.impl.ClientConnectionImpl@65e3cea5 on writer 0fd3921e-502d-4a2c-8ed2-e5a57a9a13e6. SetupCompleted: false, Closed: false
```

**Comment by Richa-Srivastava** [comment]
Uploading logs for all the pods
[issue_3800.zip](https://github.com/pravega/pravega/files/3201908/issue_3800.zip)

**Comment by andreipaduroiu** [comment]
These are expected during failovers. Nothing here looks out of the ordinary. #3805 will address the log spam from the StorageWriter.

**Comment by sumit-bm** [comment]
@andreipaduroiu we haven't done any failover in this case, this case is scale up segmentstore from 1 to 2 with IO. As soon as segmentstore scaled up to 2 or 3 IO failure are getting detected with lot of exception in SS

**Comment by andreipaduroiu** [comment]
When you scale the Segment Store hosts, you trigger Segment Container failovers.

**Comment by shrids** [comment]
@sumit-bm @shiveshr Going through the logs observe that the test uses the same `-Dpravegaservice.publishedIPAddress` for both the segment store instances, both have the IP. ref: [1]

This would cause both the segment store instances to receive identical segment store mappings ref: [2] and this is the reason why this issue was not seen on the Kubernetes setup since the pod IP is used for the publishedIPAddress.

[1]
```
// SSS1
Line 14: -Dpravegaservice.publishedIPAddress=10.246.154.55
// SSS2
Line 6: -Dpravegaservice.publishedIPAddress=10.246.154.55
```
[2]
```
SSS 2:
2019-05-20 11:11:45,631 986  [core-1] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 1, 2, 3], Current = [], PendingTasks = [], ToStart = [0, 1, 2, 3], ToStop = [].
SSS 1:
2019-05-20 11:11:40,387 6111184 [core-23] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 1, 2, 3], Current = [0, 1, 2, 3], PendingTasks = [], ToStart = [], ToStop = []. 
```

*Details:*
From the logs we see that the test started with one segment store instance (SSS1 @ `09:29:49,223`) and one Controller (ctrl1 @ `09:29:29,450`)
Controller 1 became the Segment Monitor leader and recieved an event indicating the SSS1 has been added @ `09:29:50`
```
2019-05-20 09:29:30,454 1026 [Curator-LeaderSelector-0] INFO  i.p.c.fault.SegmentMonitorLeader - Obtained leadership to monitor the Host to Segment Container Mapping
2019-05-20 09:29:50,110 20682 [Curator-PathChildrenCache-0] INFO  i.p.c.fault.SegmentMonitorLeader - Received event: HOST_ADDED for host: 10.246.154.55:12345:. Wake up leader for rebalancing
```

Now SSS2 which started @ `11:11:44,666` joined the cluster with the same address as SSS1 @ `11:11:45,599 95` The controller logged and error, indicating this invalid usage.
```
2019-05-20 11:11:45,605 6136177 [Curator-PathChildrenCache-0] WARN  i.p.c.cluster.zkImpl.ClusterZKImpl - Invalid usage: Node 10.246.154.55:12345: updated externally for cluster
```
