### ISSUE TITLE
Getting NPE while scaling up segments on docker swarm Setup

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#3802]
**Getting `NPE` while scaling up and scaling down segments**
Docker swarm setup
```
1 Node - 1 Master Deployment:
1 Controller
1 Zookeeper
1 Segment Store
3 BookKeeper
1 Pravega_HDFS
```
Pravega details:

`Pravega version : 0.5.0-2236.5228e2d`
Steps Followed
```
1. Created Docker swarm setup
2. Started Benchmark IO with segment=10 and after running IO for sometime, scaled the segments from 10->1000.
3. After sometime, scaled down the segments from 1000-> 200
```
Got following exception inside segment store:
```
2019-05-18 14:36:14,466 364985 [ForkJoinPool.commonPool-worker-22] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[3]: Iteration[8].Error.
java.lang.NullPointerException: null
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.write(AsyncStorageWrapper.java:93)
        at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$flushPendingAppends$17(SegmentAggregator.java:775)
        at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$createSegmentIfNecessary$40(SegmentAggregator.java:1138)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
        at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Problem location**

**Suggestions for an improvement**

**Comment by fpj** [comment]
Without logs, it will be difficult to tell what the problem is, perhaps @andreipaduroiu can tell from the stack trace.

**Comment by andreipaduroiu** [comment]
@sachin-j-joshi found this somewhere else. Looks like some null reference is coming from one of the Tier 2 adapters.

**Comment by sumit-bm** [comment]
Logs: 
[pravega-docker-swarm-logs_05182019.zip](https://github.com/pravega/pravega/files/3198997/pravega-docker-swarm-logs_05182019.zip)

**Comment by sachin-j-joshi** [comment]
This might be similar to https://github.com/pravega/pravega/issues/3724 given the stack trace.
