### ISSUE TITLE
"io.pravega.auth.AuthenticationException: Handler does not exist for method Bearer" error while trying to access/create scopes from UI

### ISSUE THREAD

**Issue by deenav** [pravega/pravega#3822]
**Problem description**
While trying to create a scope from management-UI with the name of "test", observed `Controller api failed with authenticator error` and "Get scopes", "List streams" are failing  with the following stack trace

```
2019-05-22 10:59:20,947 3441610 [grpc-default-executor-11] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=-5728591677854143996] createScope called for scope test.
2019-05-22 10:59:20,947 3441610 [grpc-default-executor-11] ERROR i.p.c.s.r.g.v.ControllerServiceImpl - Controller api failed with authenticator error
2019-05-22 10:59:40,972 3461635 [grpc-default-executor-11] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=-5728591677854143996] createScope called for scope test.
2019-05-22 10:59:40,973 3461636 [grpc-default-executor-11] ERROR i.p.c.s.r.g.v.ControllerServiceImpl - Controller api failed with authenticator error
2019-05-22 11:03:06,597 3667260 [grizzly-http-server-1] WARN  i.p.c.s.r.r.StreamMetadataResourceImpl - Get scopes failed due to authentication failure.
io.pravega.auth.AuthenticationException: Handler does not exist for method Bearer
        at io.pravega.controller.server.rpc.auth.PravegaAuthManager.getHandler(PravegaAuthManager.java:51)
        at io.pravega.controller.server.rpc.auth.PravegaAuthManager.authenticate(PravegaAuthManager.java:98)
        at io.pravega.controller.server.rpc.auth.RESTAuthHelper.authenticate(RESTAuthHelper.java:90)
        at io.pravega.controller.server.rest.resources.StreamMetadataResourceImpl.listScopes(StreamMetadataResourceImpl.java:474)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:183)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:377)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
        at java.lang.Thread.run(Thread.java:748)
2019-05-22 11:04:05,040 3725703 [grizzly-http-server-0] WARN  i.p.c.s.r.r.StreamMetadataResourceImpl - List streams for longevity failed due to authentication failure.
2019-05-22 11:04:05,123 3725786 [grizzly-http-server-1] WARN  i.p.c.s.r.r.StreamMetadataResourceImpl - List streams for longevity failed due to authentication failure.
```
**Deployment details:**
```
pravega-operator:0.3.2
Pravega version: 0.5.0-2252.c180711
Bookkeeper version: 0.5.0-2252.c180711
```
Attached controller logs 
[pravega-controller-authentication-error.log](https://github.com/pravega/pravega/files/3207790/pravega-controller-authentication-error.log)

**Comment by ravisharda** [comment]
@deenav could you please share the effective environment variables and Controller Java process system properties? Please obtain them by running commands inside the Controller pod, if possible. I am trying to find out what triggered the use of a Bearer AuthHandler method, and the info I am asking for might help in figuring this out.

**Comment by ravisharda** [comment]
Since the issue was resolved after using the appropriate image, I believe we could close this issue now.

**Comment by deenav** [comment]
This issue was resolved after trying it with the appropriate Pravega image (with the auth handler which can handle the "Bearer" oauth tokens ), I am able to create Scopes from the management UI now.
