### ISSUE TITLE
Writers failed with NoSuchSegmentException: Segment does not exist

### ISSUE THREAD

**Issue by sumit-bm** [pravega/pravega#3835]
While exercising longevity IO workload (4 Reader, 3 Writer, scale type as EVENTS_PER_SECOND with retention enabled) all writers have been failed with `NoSuchSegmentException: Segment does not exist` and `ERROR i.p.l.t.w.writers.PravegaWriter - Writer finished with Error`

Environment details: PKS / K8 with medium cluster:
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
```
Pravega version: 0.5.0-2260.b477eec
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2 
```
All 3 writer failed after ~ 5hours of operation
```
INFO  [2019-05-26 00:42:41,885] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 5h 35m
INFO  [2019-05-26 00:42:41,885] io.pravega.longevity.utils.PerformanceUtils: Writers (0/3): events:774,207, events/sec:38, KB/sec:29.486328
```
Following are exception on `PravegaWriter - Writer finished with Error`
```
2019-05-26 00:42:27,081 20122492 [ScalingRetransmition-longevity/smallScale-85] ERROR i.p.l.t.w.writers.PravegaWriter - Writer finished with Error
io.pravega.client.segment.impl.NoSuchSegmentException: Segment does not exist:longevity/smallScale/775.#epoch.486
        at io.pravega.client.stream.impl.SegmentSelector.lambda$refreshSegmentEventWritersUponSealed$1(SegmentSelector.java:95)
        at java.util.ArrayList.forEach(Unknown Source)
        at io.pravega.client.stream.impl.SegmentSelector.refreshSegmentEventWritersUponSealed(SegmentSelector.java:94)
        at io.pravega.client.stream.impl.EventStreamWriterImpl.lambda$null$1(EventStreamWriterImpl.java:159)
        at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:173)
        at io.pravega.client.stream.impl.EventStreamWriterImpl.lambda$handleLogSealed$2(EventStreamWriterImpl.java:146)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```
```
2019-05-26 00:42:27,082 20122493 [grpc-default-executor-515] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getSuccessors with trace id 0 failed with server error.
io.grpc.StatusRuntimeException: UNAVAILABLE: Keepalive failed. The connection is likely gone
        at io.grpc.Status.asRuntimeException(Status.java:530)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by fpj** [comment]
This exception is thrown when the stream is deleted:

https://github.com/pravega/pravega/blob/465a0026541e9cd1ddf4e704481dfecd4136371d/client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java#L95

Assuming that the stream wasn't deleted, we need to see the exact interaction with the controller to determine how we got there. The controller grpc exception posted has a slightly late timestamp compared to the `NoSuchSegmentException`. It is probably related, but doesn't tell the whole story.

**Comment by shiveshr** [comment]
> This exception is thrown when the stream is deleted:
It may also be thrown when stream segment is deleted as part of truncation.

**Comment by shrids** [comment]
My findings from the logs:

- a.  The writer is trying to fetch the successors for a given segment by contacting the controller.
- b.  The controller `getSuccessor` call failed. (the controller client has internal retries configured in case of an error and the retries to contact the controller failed too indicating that the controller is not reachable). The client logs this error ref [1]
- c. Incase of an error or an actual `null` returned by the controller (in case stream is deleted) the client 
propagates this error to all the segment writers and ensures `NoSuchSegmentException` exception is thrown. The writer cannot proceed further if the call to the controller fails. ref [2]

[1]
```
2019-05-26 00:42:27,078 20122489 [ScalingRetransmition-longevity/smallScale-85] ERROR i.p.c.stream.impl.SegmentSelector - Error while fetching successors for segment: longevity/smallScale/775.#epoch.
486
io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: UNAVAILABLE: Keepalive failed. The connection is likely gone
        at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$6(Retry.java:245)
        at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
        at io.pravega.client.stream.impl.ControllerImpl$RPCAsyncCallback.onError(ControllerImpl.java:1018)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: UNAVAILABLE: Keepalive failed. The connection is likely gone
        at java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeRelay(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniRelay(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniRelay.tryFire(Unknown Source)
        ... 25 common frames omitted
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Keepalive failed. The connection is likely gone
        at io.grpc.Status.asRuntimeException(Status.java:530)
        ... 22 common frames omitted
```
[2]
```
2019-05-26 00:42:27,081 20122492 [ScalingRetransmition-longevity/smallScale-85] ERROR i.p.l.t.w.writers.PravegaWriter - Writer finished with Error
io.pravega.client.segment.impl.NoSuchSegmentException: Segment does not exist:longevity/smallScale/775.#epoch.486
        at io.pravega.client.stream.impl.SegmentSelector.lambda$refreshSegmentEventWritersUponSealed$1(SegmentSelector.java:95)
        at java.util.ArrayList.forEach(Unknown Source)
        at io.pravega.client.stream.impl.SegmentSelector.refreshSegmentEventWritersUponSealed(SegmentSelector.java:94)
        at io.pravega.client.stream.impl.EventStreamWriterImpl.lambda$null$1(EventStreamWriterImpl.java:159)
        at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:173)
        at io.pravega.client.stream.impl.EventStreamWriterImpl.lambda$handleLogSealed$2(EventStreamWriterImpl.java:146)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by shrids** [comment]
@sumit-bm @shiveshr Observing that there are no pravega-controller logs around timestamp `2019-05-26 00:42:`. Without these logs it will not be possible to figure out if this was a `Pravega-controller`  issue or the issue was due to `Pravega-controller` pods not running.
(The behavior from the client is on expected lines as updated in the previous comment.)

**Comment by fpj** [comment]
@shrids it is confusing me that the block of code in `SegmentSelector` refers to stream being deleted:

```
if (successors == null) {
            // Stream is deleted, complete all pending writes exceptionally.
            log.error("Stream is deleted, all pending writes will be completed exceptionally");
            removeAllWriters().forEach(event -> event.getAckFuture()
                    .completeExceptionally(new NoSuchSegmentException(sealedSegment.toString())));
            return Collections.emptyList();
        } else {
            return updateSegmentsUponSealed(successors, sealedSegment, segmentSealedCallback);
        }
```

is there any other situation in which the controller is supposed to return `null` and the stream is not deleted? if the stream has been truncated, there are successors, so I wouldn't expect a `null` response, but maybe there is an intermediate step I'm missing.

**Comment by shrids** [comment]
The log statement is misleading as `successors`  can be be null when the controller call fails too.
The current flow of `refreshSegmentEventWritersUponSealed` is as follows

1. Fetch the successors from for the sealed segment from the controller.
```
  StreamSegmentsWithPredecessors successors = Futures.getAndHandleExceptions(
                controller.getSuccessors(sealedSegment), t -> {
                    log.error("Error while fetching successors for segment: {}", sealedSegment, t);
                    return null;
                });
```
`successors` is a null if the stream has been deleted or in case the controller api `getSuccessor` fails.
From the logs we can observe that the call to the controller failed.

2.  Now incase the `successors` is `null` all the segment write futures are completed exceptionally and the writer throw the exception.
