### ISSUE TITLE
Both Controller restarted with error "org.apache.zookeeper.KeeperException$ConnectionLossException" while running IO

### ISSUE THREAD

**Issue by vedanthh** [pravega/pravega#3836]
**Controller restarted with error "org.apache.zookeeper.KeeperException$ConnectionLossException" while running IO using Longevity with moderate workload (Total - 4 readers, 3 writers, ~50 events/sec, ~  40 KB/s IO)** 

**Observed that 2 reader has been exhausted and 3 writers has failed during this longevity operation** 
```
INFO  [2019-05-26 00:42:41,885] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 5h 35m
INFO  [2019-05-26 00:42:41,885] io.pravega.longevity.utils.PerformanceUtils: Writers (0/3): events:774,207, events/sec:38, KB/sec:29.486328
```
```
INFO  [2019-05-26 03:52:11,910] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-05-26 03:52:11,910] io.pravega.longevity.utils.PerformanceUtils: Readers (2/4): events:1,270,173, events/sec:40, KB/sec:30.91504
```

**Environment details: PKS / K8 with medium cluster:**
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
```
Pravega version: 0.5.0-2260.b477eec
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2 
```
**# kubectl get po**
```
default             pod/pravega-bookie-0                                 1/1       Running   0          9h
default             pod/pravega-bookie-1                                 1/1       Running   0          9h
default             pod/pravega-bookie-2                                 1/1       Running   0          9h
default             pod/pravega-bookie-3                                 1/1       Running   0          9h
default             pod/pravega-operator-779879b48-9lzcb                 1/1       Running   0          9h
default             pod/pravega-pravega-controller-77b789dc4d-fwxjl      1/1       Running   7          9h
default             pod/pravega-pravega-controller-77b789dc4d-r4s2t      1/1       Running   8          9h
default             pod/pravega-pravega-segmentstore-0                   1/1       Running   0          9h
default             pod/pravega-pravega-segmentstore-1                   1/1       Running   0          9h
default             pod/pravega-pravega-segmentstore-2                   1/1       Running   0          9h
default             pod/pravega-zk-0                                     1/1       Running   0          10h
default             pod/pravega-zk-1                                     1/1       Running   0          10h
default             pod/pravega-zk-2                                     1/1       Running   0          10h
default             pod/zookeeper-operator-685bfcbbc5-sp5qs              1/1       Running   0          10h

```
**Snip of Error**
```
2019-05-26 01:56:11,484 1524622 [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background operation retry gave up
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:844)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:972)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:925)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:73)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:322)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by sumit-bm** [comment]
@shiveshr could we get an update on this?

**Comment by shiveshr** [comment]
There are three issues open about controller restarts upon zk connection loss, namely:
#3954 #3770 
They all have the same cause. 
@RaulGracia has updated here. https://github.com/pravega/pravega/issues/3954#issuecomment-507346851

**Comment by RaulGracia** [comment]
Superseded by https://github.com/pravega/zookeeper-operator/issues/72.

**Comment by pbelgundi** [comment]
Since 1 controller restart was noticed on GKE recovery time as low as 1-2 mins, we should consider testing this after applying the fix provided by Shivesh to remedy this problem :
https://github.com/shiveshr/pravega-1/commits/controller-restart-time
