### ISSUE TITLE
Soft handle Exception: Observing "java.net.UnknownHostException" in Zookeeper

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega#3840]
**Problem Description**
Observed `java.net.UnknownHostException` along with warning messages as **Failed to resolve address** from **Quorum Peer** server in one of the zookeeper out of three deployed zookeepers.
The above problems in Quorum Peer led to errors like `Error writing next dynamic config file to disk`, `Error closing file` and `Restarting Leader Election`.

**Problem Location**
`In Zookeeper`

Found following error messages and exceptions: -
```
2019-05-24 05:35:59,224 [myid:2] - WARN  [QuorumPeer[myid=2](plain=/0.0.0.0:2181)(secure=disabled):QuorumPeer$QuorumServer@173] - Failed to resolve address: pravega-example-zk-2.pravega-example-zk-headless.default.svc.cluster.local
java.net.UnknownHostException: pravega-example-zk-2.pravega-example-zk-headless.default.svc.cluster.local
        at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at java.net.InetAddress.getByName(InetAddress.java:1076)
        at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:171)
        at org.apache.zookeeper.server.quorum.QuorumPeer.recreateSocketAddresses(QuorumPeer.java:727)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:682)
        at org.apache.zookeeper.server.quorum.QuorumPeer.connectNewPeers(QuorumPeer.java:1519)
        at org.apache.zookeeper.server.quorum.QuorumPeer.setLastSeenQuorumVerifier(QuorumPeer.java:1556)
        at org.apache.zookeeper.server.quorum.Follower.processPacket(Follower.java:135)
        at org.apache.zookeeper.server.quorum.Follower.followLeader(Follower.java:93)
        at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:1214)
2019-05-24 05:35:59,225 [myid:2] - WARN  [QuorumPeer[myid=2](plain=/0.0.0.0:2181)(secure=disabled):QuorumCnxManager@660] - Cannot open channel to 3 at election address pravega-example-zk-2.pravega-example-zk-headless.default.svc.cluster.local:3888
java.net.UnknownHostException: pravega-example-zk-2.pravega-example-zk-headless.default.svc.cluster.local
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:638)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:695)
        at org.apache.zookeeper.server.quorum.QuorumPeer.connectNewPeers(QuorumPeer.java:1519)
        at org.apache.zookeeper.server.quorum.QuorumPeer.setLastSeenQuorumVerifier(QuorumPeer.java:1556)
        at org.apache.zookeeper.server.quorum.Follower.processPacket(Follower.java:135)
        at org.apache.zookeeper.server.quorum.Follower.followLeader(Follower.java:93)
        at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:1214)
2019-05-24 05:35:59,225 [myid:2] - ERROR [QuorumPeer[myid=2](plain=/0.0.0.0:2181)(secure=disabled):QuorumPeer@1564] - Error writing next dynamic config file to disk:
2019-05-24 05:35:59,229 [myid:2] - ERROR [QuorumPeer[myid=2](plain=/0.0.0.0:2181)(secure=disabled):QuorumPeer@1596] - Error closing file:
2019-05-24 05:35:59,229 [myid:2] - WARN  [QuorumPeer[myid=2](plain=/0.0.0.0:2181)(secure=disabled):QuorumPeer@1527] - Restarting Leader Election
```

Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.
Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Pravega version : 0.5.0-2252.c180711
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```

**Comment by RaulGracia** [comment]
@sumit-bm if I understood the issue correctly, this is a Zookeeper log, right? Assuming that, could you clarify the following:
i) Was this problem preventing Pravega/Bookkeeper to continue working? 
ii) Considering that Zookeeper is a third-party project, how do you suggest that we change the way an exception is presented? Externally, the only thing that comes to my mind is to set the log level to `ERROR` to discard `WARN` messages, but this would be even counter-productive in the case of doing debug.

**Comment by RaulGracia** [comment]
This kind of errors are indicating that one of the Zookeeper servers is down or that its name cannot be resolved (e.g., pod crashed, evicted, DNS problem). So, they are useful for us to understand if a connectivity issued was there. Also, these logs are from Zookeeper, for which we have no control other than specifying the log level (3rd party service).
