### ISSUE TITLE
Observing all readers failed in longevity run with "DataCorruptionException"

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega#3855]
**Problem description**

All reader (0/8) failure observed while running IO workload of ~6 Mbps having readers: 8, writers: 4, scaleFactor: 2, maxEventsPerSecond: 1000, targetRate: 200, scalingType: EVENTS_PER_SECOND for 1+ days. Since all the readers have failed so there is no event population for readers. Writers did not fail (4/4) but the event rate is very low (~1000 events/sec), which was (~3000 events/sec) in the start.

In client manager-log during first reader failure (7/8) observed `RetriesExhaustedException` on `segment=longevity/mediumScale/1001.#epoch.646`, following is the log from that instance : -
```
INFO  [2019-05-28 21:16:59,690] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:195,558,248, events/sec:3,969, KB/sec:3043.7207
INFO  [2019-05-28 21:16:59,690] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-05-28 21:16:59,690] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-05-28 21:16:59,691] io.pravega.longevity.utils.PerformanceUtils: Readers (8/8): events:195,551,721, events/sec:3,969, KB/sec:3043.6191
172.24.37.2 - - [28/May/2019:21:16:59 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 2720 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 12
INFO  [2019-05-28 21:17:04,002] io.pravega.longevity.testmanager.manager.TestPerformanceCollector: Received Error From task taskID : io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=27577985007616, segment=longevity/mediumScale/1001.#epoch.646, correctHost=, serverStackTrace=)
java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=27577985007616, segment=longevity/mediumScale/1001.#epoch.646, correctHost=, serverStackTrace=)
        at java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
        at java.util.concurrent.CompletableFuture.join(Unknown Source)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.handleRequest(SegmentInputStreamImpl.java:137)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.read(SegmentInputStreamImpl.java:122)
        at io.pravega.client.segment.impl.EventSegmentReaderImpl.readEvent(EventSegmentReaderImpl.java:75)
        at io.pravega.client.segment.impl.EventSegmentReaderImpl.read(EventSegmentReaderImpl.java:62)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:121)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:94)
        at io.pravega.longevity.testworker.workers.readers.PravegaReader.start(PravegaReader.java:99)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=27577985007616, segment=longevity/mediumScale/1001.#epoch.646, correctHost=, serverStackTrace=)
        at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$6(Retry.java:245)
        at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.failAllInflight(AsyncSegmentInputStreamImpl.java:265)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.closeConnection(AsyncSegmentInputStreamImpl.java:237)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.access$100(AsyncSegmentInputStreamImpl.java:42)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.wrongHost(AsyncSegmentInputStreamImpl.java:70)
        at io.pravega.shared.protocol.netty.WireCommands$WrongHost.process(WireCommands.java:125)
        at io.pravega.shared.protocol.netty.ReplyProcessor.process(ReplyProcessor.java:20)
        at io.pravega.client.netty.impl.FlowHandler.lambda$channelRead$2(FlowHandler.java:209)
        at java.util.Optional.ifPresent(Unknown Source)
        at io.pravega.client.netty.impl.FlowHandler.channelRead(FlowHandler.java:207)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 more
Caused by: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=27577985007616, segment=longevity/mediumScale/1001.#epoch.646, correctHost=, serverStackTrace=)
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
        ... 39 more
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=27577985007616, segment=longevity/mediumScale/1001.#epoch.646, correctHost=, serverStackTrace=)
        ... 34 more
172.24.37.2 - - [28/May/2019:21:17:04 +0000] "POST /v1/longevity/error HTTP/1.1" 200 6971 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 324
INFO  [2019-05-28 21:17:29,733] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 13h 42m
INFO  [2019-05-28 21:17:29,734] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:195,558,248, events/sec:3,965, KB/sec:3040.0186
INFO  [2019-05-28 21:17:29,734] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-05-28 21:17:29,734] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-05-28 21:17:29,734] io.pravega.longevity.utils.PerformanceUtils: Readers (7/8): events:195,555,720, events/sec:3,965, KB/sec:3039.9785
INFO  [2019-05-28 21:17:29,734] io.pravega.longevity.utils.PerformanceUtils: New runtime for 8a9c3312-b2be-4d31-853a-76e6c79ab402  Running for 13h 42m
INFO  [2019-05-28 21:17:29,734] io.pravega.longevity.utils.PerformanceUtils: Dumping stats for stream longevity/mediumScale
INFO  [2019-05-28 21:17:29,734] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:195,558,248, events/sec:3,965, KB/sec:3040.0186
INFO  [2019-05-28 21:17:29,734] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-05-28 21:17:29,734] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-05-28 21:17:29,734] io.pravega.longevity.utils.PerformanceUtils: Readers (7/8): events:195,555,720, events/sec:3,965, KB/sec:3039.9785

```

In segment store found  `segment=longevity/mediumScale/1001.#epoch.646`, observed `ERROR i.p.s.server.writer.StorageWriter - StorageWriter[5]: Iteration[40].CriticalError` and `ERROR i.p.s.s.s.StreamSegmentContainerRegistry - Critical failure for SegmentContainer` along with `io.pravega.segmentstore.server.DataCorruptionException` in Segment Store.
Following are the exceptions from segment store: -
```
2019-05-28 21:15:35,769 114639189 [core-17] INFO  i.p.s.server.CacheManager - CacheManager Registered AttributeIndex[102458].
2019-05-28 21:15:35,781 114639201 [core-23] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[5]: Iteration[40].CriticalError.
io.pravega.segmentstore.server.DataCorruptionException: Unable to retrieve CacheContents for 'AggregatedAppend: SegmentId = 102403, Offsets = [461052-461160), SeqNo = 770486'.
        at io.pravega.segmentstore.server.writer.SegmentAggregator.getFlushArgs(SegmentAggregator.java:826)
        at io.pravega.segmentstore.server.writer.SegmentAggregator.flushPendingAppends(SegmentAggregator.java:754)
        at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$flushExcess$14(SegmentAggregator.java:696)
        at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:712)
        at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:681)
        at io.pravega.common.concurrent.Futures.runOrFail(Futures.java:572)
        at io.pravega.common.concurrent.Futures$Loop.run(Futures.java:725)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-05-28 21:15:35,781 114639201 [core-23] INFO  i.p.c.c.AbstractThreadPoolService - StorageWriter[5]: Stopping.
2019-05-28 21:15:35,781 114639201 [core-23] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[5-102401]: State changed from Writing to Closed.
2019-05-28 21:15:35,781 114639201 [core-23] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[5-102400]: State changed from Writing to Closed.
```

```
2019-05-28 21:15:35,839 114639259 [core-29] INFO  i.p.s.s.s.StreamSegmentContainerRegistry - Unregistered SegmentContainer 5.
2019-05-28 21:15:35,839 114639259 [core-29] ERROR i.p.s.s.s.StreamSegmentContainerRegistry - Critical failure for SegmentContainer Container Id = 5, State = FAILED. {}
io.pravega.segmentstore.server.DataCorruptionException: Unable to retrieve CacheContents for 'AggregatedAppend: SegmentId = 102403, Offsets = [461052-461160), SeqNo = 770486'.
        at io.pravega.segmentstore.server.writer.SegmentAggregator.getFlushArgs(SegmentAggregator.java:826)
        at io.pravega.segmentstore.server.writer.SegmentAggregator.flushPendingAppends(SegmentAggregator.java:754)
        at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$flushExcess$14(SegmentAggregator.java:696)
        at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:712)
        at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:681)
        at io.pravega.common.concurrent.Futures.runOrFail(Futures.java:572)
        at io.pravega.common.concurrent.Futures$Loop.run(Futures.java:725)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-05-28 21:15:35,975 114639395 [epollEventLoopGroup-11-6] WARN  i.p.s.s.h.handler.AppendProcessor - Wrong host. Segment 'Scope/test1/97.#epoch.0' (Container 5) is not owned and 84ffb4dd-e22f-436b-b076-cab51c3e253f cannot perform operation 'appending data'.
```

Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.
Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Pravega version : 0.5.0-2260.b477eec
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```

**Comment by SomeshJoshi19** [comment]
shared logs for this issue in internal channel

**Comment by SomeshJoshi19** [comment]
Observing one of the container component failure warning messages in segment store : -
```
019-05-28 21:15:35,782 114639202 [core-23] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[5-102398]: State changed from Writing to Closed.
2019-05-28 21:15:35,782 114639202 [core-17] WARN  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[5]: Writer failed. Shutting down StreamSegmentContainer.
java.util.concurrent.CompletionException: io.pravega.segmentstore.server.DataCorruptionException: Unable to retrieve CacheContents for 'AggregatedAppend: SegmentId = 102403, Offsets = [461052-461160), SeqNo = 770486'.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:975)
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
        at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$flushExcess$14(SegmentAggregator.java:697)
        at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:712)
        at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:681)
        at io.pravega.common.concurrent.Futures.runOrFail(Futures.java:572)
        at io.pravega.common.concurrent.Futures$Loop.run(Futures.java:725)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.segmentstore.server.DataCorruptionException: Unable to retrieve CacheContents for 'AggregatedAppend: SegmentId = 102403, Offsets = [461052-461160), SeqNo = 770486'.
        at io.pravega.segmentstore.server.writer.SegmentAggregator.getFlushArgs(SegmentAggregator.java:826)
        at io.pravega.segmentstore.server.writer.SegmentAggregator.flushPendingAppends(SegmentAggregator.java:754)
        at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$flushExcess$14(SegmentAggregator.java:696)
        ... 11 common frames omitted
2019-05-28 21:15:35,782 114639202 [core-17] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[5]: Stopping.
2019-05-28 21:15:35,783 114639203 [core-17] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[5]: Stopping.
2019-05-28 21:15:35,783 114639203 [core-17] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[5]: Stopped.
2019-05-28 21:15:35,783 114639203 [core-17] INFO  i.p.s.server.logs.DurableLog - DurableLog[5]: Stopping.
2019-05-28 21:15:35,783 114639203 [core-17] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[5]: Stopping.
2019-05-28 21:15:35,783 114639203 [core-17] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[5]: Stopped.
2019-05-28 21:15:35,782 114639202 [core-23] INFO  i.p.c.c.AbstractThreadPoolService - StorageWriter[5]: Stopped.
2019-05-28 21:15:35,786 114639206 [core-17] INFO  i.p.s.s.i.bookkeeper.BookKeeperLog - Log[5]: Closed.
2019-05-28 21:15:35,786 114639206 [core-17] INFO  i.p.s.server.logs.DurableLog - DurableLog[5]: Stopped.
2019-05-28 21:15:35,786 114639206 [core-29] WARN  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[5]: Failed due to component failure.
2019-05-28 21:15:35,787 114639207 [core-29] INFO  i.p.s.server.CacheManager - CacheManager Unregistered io.pravega.segmentstore.server.tables.ContainerKeyCache@2f62aace.
2019-05-28 21:15:35,788 114639208 [core-29] INFO  i.p.s.s.impl.rocksdb.RocksDBCache - RocksDBCache[Container_5_TableKeys]: Closed.
2019-05-28 21:15:35,788 114639208 [core-29] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[5]: Closed.
2019-05-28 21:15:35,788 114639208 [core-29] INFO  i.p.c.c.AbstractThreadPoolService - StorageWriter[5]: Closed.
2019-05-28 21:15:35,788 114639208 [core-29] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[5]: Closed.
2019-05-28 21:15:35,788 114639208 [core-29] INFO  i.p.s.server.logs.DurableLog - DurableLog[5]: Closed.
```

**Comment by andreipaduroiu** [comment]
This is what happens here:
1. Segment A is mapped to memory. It has SegmentMetadata instance SM1, SegmentAggregator instance SA1, SegmentReadIndex instance SRI1.
2. Segment A begins eviction process. It is removed from the metadata.
3. Segment A is remapped to metadata (external request). It now has Segment Metadata instance SM2.
4. StorageWriter correctly determines that SA1's metadata (pointing to SM1) is now inactive and cleans up SA1.
5. ReadIndex DOES NOT determine that SRI1's metadata is inactive because it queries the main Container Metadata, which now has SM2. Hence nothing is cleaned up.
6. Segment A's eviction process (begun in #2) is now complete.
7. An operation (append) is received. SM2 is updated correctly with the new length, but when adding the append to SRI1, it still points to the stale SM1, which has the old length. Error.


Relevant log snippets to prove the above:
```
-- This is how a normal map-evict cycle should look like
2019-05-28 20:48:35,333 113018753 [core-24] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[5]: MapStreamSegment SegmentId = 102428, Name = 'Scope/test2/483.#epoch.0', Active = 65
2019-05-28 20:48:43,935 113027355 [core-16] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[5-102428]: Initialized. StorageLength = 439776, Sealed = false.
2019-05-28 20:51:27,137 113190557 [core-22] INFO  i.p.s.s.reading.ContainerReadIndex - ReadIndex[5]: Cleaned up ReadIndices for deleted Segments [102428, 102433, 102435, 102438, 102397].
2019-05-28 20:51:27,178 113190598 [core-9] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[5-102428]: State changed from Writing to Closed.


-- This is a broken map-eviction cycle (see above for interpretation).
2019-05-28 20:51:38,179 113201599 [core-27] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[5]: MapStreamSegment SegmentId = 102428, Name = 'Scope/test2/483.#epoch.0', Active = 64
2019-05-28 20:51:38,179 113201599 [core-27] INFO  i.p.s.server.CacheManager - CacheManager Registered ReadIndex[5-102428] (Scope/test2/483.#epoch.0).
2019-05-28 20:51:53,565 113216985 [core-13] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[5-102428]: Initialized. StorageLength = 440208, Sealed = false.

2019-05-28 20:54:27,203 113370623 [core-7] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[5]: EvictedStreamSegments Count = 10, Active = 56
2019-05-28 20:54:27,274 113370694 [core-27] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[5]: MapStreamSegment SegmentId = 102428, Name = 'Scope/test2/483.#epoch.0', Active = 57
2019-05-28 20:54:27,630 113371050 [core-12] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[5-102428]: State changed from Writing to Closed.
2019-05-28 20:54:27,633 113371053 [core-7] INFO  i.p.s.server.CacheManager - CacheManager Unregistered AttributeIndex[102428].
2019-05-28 20:55:27,654 113431074 [core-26] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[5]: EvictedStreamSegments Count = 1, Active = 65
2019-05-28 20:56:27,686 113491106 [core-28] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[5]: EvictedStreamSegments Count = 1, Active = 65
2019-05-28 20:54:27,690 113371110 [core-11] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[5-102428]: Initialized. StorageLength = 440532, Sealed = false.
2019-05-28 20:57:27,707 113551127 [core-25] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[5]: EvictedStreamSegments Count = 1, Active = 65
2019-05-28 20:58:27,728 113611148 [core-16] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[5]: EvictedStreamSegments Count = 3, Active = 63

2019-05-28 20:54:27,743 113371163 [core-30] ERROR i.p.s.s.logs.OperationProcessor - OperationProcessor[5]: MemoryStateUpdater.process failure.
java.lang.IllegalArgumentException: offset: The given range of bytes (440532-440640) is beyond the StreamSegment Length (440532).
	at io.pravega.common.Exceptions.checkArgument(Exceptions.java:210)
	at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.append(StreamSegmentReadIndex.java:350)
	at io.pravega.segmentstore.server.reading.ContainerReadIndex.append(ContainerReadIndex.java:130)
	at io.pravega.segmentstore.server.logs.MemoryStateUpdater.addToReadIndex(MemoryStateUpdater.java:172)
	at io.pravega.segmentstore.server.logs.MemoryStateUpdater.process(MemoryStateUpdater.java:135)
	at io.pravega.segmentstore.server.logs.MemoryStateUpdater.process(MemoryStateUpdater.java:106)
	at io.pravega.segmentstore.server.logs.OperationProcessor.processCommits(OperationProcessor.java:417)
```
