### ISSUE TITLE
Fail to create scope after deploying pravega with two zookeeper in docker swarm setup

### ISSUE THREAD

**Issue by Ranjan-Padhi** [pravega/pravega#3875]
Deployed `pravega:0.5.0-2260.b477eec` release in docker swarm setup (single node master setup) with two zookeeper containers
```
1 hdfs
2 zookeepers
1 segmentstore
1 controller
4 bookkeepers
```

After deploying successfully controller failed to create scope `java.util.concurrent.CompletionException: io.pravega.client.stream.impl.ControllerFailureException: Failed to create scope: _system` and due to this also failed allocate segment container to segmentstore

NOTE :- If deploying same release with one zookeepers, then no issue observed in controller and segmentstore and IO running successfully

Controller log :-
```
019-06-04 08:46:41,260 84412 [controllerpool-4] WARN  i.p.c.s.s.PravegaTablesStoreHelper - Host Store exception Could not find host for container id: 3
2019-06-04 08:46:41,270 84422 [controllerpool-4] WARN  i.p.c.s.e.ControllerEventProcessors - Error creating event processor scope _system
java.util.concurrent.CompletionException: io.pravega.client.stream.impl.ControllerFailureException: Failed to create scope: _system
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$6(Retry.java:245)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:929)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.client.stream.impl.ControllerFailureException: Failed to create scope: _system
        at io.pravega.controller.server.eventProcessor.LocalController.lambda$createScope$0(LocalController.java:72)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        ... 17 common frames omitted
```

Segmentstore log :-
```
2019-06-04 08:46:18,483 11141 [fetch-controllers-1] INFO  i.p.c.s.i.ControllerResolverFactory - Updating client with controllers: [[[controller/10.0.0.14:9090]/{}]]
2019-06-04 08:46:18,573 11231 [fetch-controllers-1] INFO  i.p.c.s.i.ControllerResolverFactory - Rescheduling ControllerNameResolver task for after 120000 ms
2019-06-04 08:46:28,202 20860 [core-19] WARN  i.p.s.s.h.ZKSegmentContainerMonitor - No segment container assignments found
2019-06-04 08:46:38,203 30861 [core-4] WARN  i.p.s.s.h.ZKSegmentContainerMonitor - No segment container assignments found
2019-06-04 08:46:48,204 40862 [core-12] WARN  i.p.s.s.h.ZKSegmentContainerMonitor - No segment container assignments found
2019-06-04 08:46:58,204 50862 [core-27] WARN  i.p.s.s.h.ZKSegmentContainerMonitor - No segment container assignments found
2019-06-04 08:47:08,205 60863 [core-12] WARN  i.p.s.s.h.ZKSegmentContainerMonitor - No segment container assignments found
2019-06-04 08:47:18,206 70864 [core-9] WARN  i.p.s.s.h.ZKSegmentContainerMonitor - No segment container assignments found
2019-06-04 08:47:28,206 80864 [core-28] WARN  i.p.s.s.h.ZKSegmentContainerMonitor - No segment container assignments found
2019-06-04 08:47:38,207 90865 [core-12] WARN  i.p.s.s.h.ZKSegmentContainerMonitor - No segment container assignments found
2019-06-04 08:47:41,509 94167 [grpc-default-executor-1] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getCurrentSegments with trace id 0 failed with server error.
io.grpc.StatusRuntimeException: INTERNAL: java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$StoreConnectionException: get entry: key: _system table: _system/_tables/scopes
        at io.grpc.Status.asRuntimeException(Status.java:530)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-06-04 08:47:48,207 100865 [core-4] WARN  i.p.s.s.h.ZKSegmentContainerMonitor - No segment container assignments found
2019-06-04 08:47:58,208 110866 [core-28] WARN  i.p.s.s.h.ZKSegmentContainerMonitor - No segment container assignments found
```

**Comment by Ranjan-Padhi** [comment]
[pravega_docker_swarm_containers_log.zip](https://github.com/pravega/pravega/files/3251710/pravega_docker_swarm_containers_log.zip)

**Comment by fpj** [comment]
ZooKeeper needs to run with an odd number of servers, please use at least 3 to tolerate a server crash or 1 if you don't plan to tolerate crashes (for testing purposes).

**Comment by Ranjan-Padhi** [comment]
Thank you @fpj for your update, but in document no where it mentioned to support odd number of zookeepers server (1 or 3), needs to be update in document

We also verified with 3 zookeepers and we face different bookie restart issue which we will report in different issue

**Comment by fpj** [comment]
> in document no where it mentioned to support odd number of zookeepers server (1 or 3), needs to be update in document

@Ranjan-Padhi what document are you referring to? In any case, from the apache zookeeper documentation:

> For reliable ZooKeeper service, you should deploy ZooKeeper in a cluster known as an ensemble. As long as a majority of the ensemble are up, the service will be available. Because Zookeeper requires a majority, it is best to use an odd number of machines. For example, with four machines ZooKeeper can only handle the failure of a single machine; if two machines fail, the remaining two machines do not constitute a majority. However, with five machines ZooKeeper can handle the failure of two machines.

http://zookeeper.apache.org/doc/r3.5.5/zookeeperAdmin.html

**Comment by sachin-j-joshi** [comment]
@sumit-bm @Ranjan-Padhi Is this still a valid issue ? if not should we close this issue ?
Also, do we need any updates to the docs ?

**Comment by Ranjan-Padhi** [comment]
As per provide document we have successfully deployed 3 (odd number) zookeeper in docker swarm setup and able to create scope as well as IO running successfully
