### ISSUE TITLE
Observing StorageWriter[]: Iteration[] Error in segment  store logs

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#3876]
Tried this with new tier-2 mounting points.
Saw this ERROR i.p.s.server.writer.StorageWriter in segment store logs.

Environment details: PKS / K8 with medium cluster:
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```

Build details
```
bookkeeper:0.5.0-2260.b477eec
pravega:0.5.0-2260.b477eec
zookeeper:3.5.4-beta-operator
pravega/pravega-operator:0.3.2
pravega/zookeeper-operator:0.2.1
```

Error from segment store:
```
2019-06-03 20:57:17,544 19381581 [core-9] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[7]: Iteration[294551].Error.
io.pravega.segmentstore.storage.DataLogWriterNotPrimaryException: Unable to acquire exclusive write lock for log (path = 'pravega/pravega/segmentstore/containers/7/0/7').
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.persistMetadata(BookKeeperLog.java:802)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.tryTruncate(BookKeeperLog.java:675)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.lambda$truncate$4(BookKeeperLog.java:323)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /pravega/pravega/segmentstore/containers/7/0/7
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.setData(ZooKeeper.java:2272)
        at org.apache.curator.framework.imps.SetDataBuilderImpl$4.call(SetDataBuilderImpl.java:291)
        at org.apache.curator.framework.imps.SetDataBuilderImpl$4.call(SetDataBuilderImpl.java:287)
        at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64)
        at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)
        at org.apache.curator.framework.imps.SetDataBuilderImpl.pathInForeground(SetDataBuilderImpl.java:284)
        at org.apache.curator.framework.imps.SetDataBuilderImpl.forPath(SetDataBuilderImpl.java:270)
        at org.apache.curator.framework.imps.SetDataBuilderImpl.forPath(SetDataBuilderImpl.java:33)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.persistMetadata(BookKeeperLog.java:794)
        ... 10 common frames omitted
```

PS:
Previously , segment store logs had large number of  'StorageWriter[]: Iteration[] Error'. Now, frequency of this error is drastically decreased with new tier-2 mounting.

**Comment by Raghuveera-Rao** [comment]
Issue is related to https://github.com/pravega/pravega/issues/3747

**Comment by andreipaduroiu** [comment]
This is not related to #3747.

This is not an error. It's normal when fencing.
