### ISSUE TITLE
Sporadic test failure ControllerClusterListenerTest.clusterListenerStarterTest

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#3882]
**Problem description**
We have seen in our Jenkins build 4 times in a row `ControllerClusterListenerTest.clusterListenerStarterTest` failing: 
```
rg.mockito.exceptions.verification.NeverWantedButInvoked: 
requestSweeper.handleFailedProcess(
    <any string>
);
Never wanted here:
-> at io.pravega.controller.fault.ControllerClusterListenerTest.clusterListenerStarterTest(ControllerClusterListenerTest.java:278)
But invoked here:
-> at io.pravega.controller.fault.ControllerClusterListenerTest.clusterListenerStarterTest(ControllerClusterListenerTest.java:254)

	at io.pravega.controller.fault.ControllerClusterListenerTest.clusterListenerStarterTest(ControllerClusterListenerTest.java:278)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
We observed this problem after merging a related PR #3871.
[failure_log.txt](https://github.com/pravega/pravega/files/3260923/failure_log.txt)

**Problem location**
`ControllerClusterListenerTest.clusterListenerStarterTest`

**Suggestions for an improvement**
Fix the test.

**Comment by andreipaduroiu** [comment]
FYI this also happens in Travis
