### ISSUE TITLE
Verification: hdfs writer issue found while verifying issue# 3859 in private build

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#3883]
While verifying modified scaling script from the following: 
https://github.com/pravega/pravega/blob/26bacf2076c46c9b3d4a0dd3dab9a5483011ea7e/docker/compose/swarm/scale_segmentstore
I observed that scaleup of segment store is happening properly with containers getting distributed as expected with the modified scaleup script but `StorageWriter` exception was occuring in scaled up segment store.

```
2019-06-06 07:00:11,651 69561 [storage-io-61] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[1-1]: State changed from NotInitialized to Closed.
2019-06-06 07:00:11,651 69561 [storage-io-61] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[1]: Iteration[58].Error.
java.net.ConnectException: Call From 01d369915267/10.0.0.16 to localhost:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
        at sun.reflect.GeneratedConstructorAccessor11.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:801)
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:732)
        at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1493)
        at org.apache.hadoop.ipc.Client.call(Client.java:1435)
        at org.apache.hadoop.ipc.Client.call(Client.java:1345)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:227)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
        at com.sun.proxy.$Proxy13.getListing(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getListing(ClientNamenodeProtocolTranslatorPB.java:597)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:409)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:163)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:155)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:346)
        at com.sun.proxy.$Proxy14.getListing(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.listPaths(DFSClient.java:1630)
        at org.apache.hadoop.hdfs.DFSClient.listPaths(DFSClient.java:1614)
        at org.apache.hadoop.hdfs.DistributedFileSystem.listStatusInternal(DistributedFileSystem.java:900)
        at org.apache.hadoop.hdfs.DistributedFileSystem.access$600(DistributedFileSystem.java:114)
        at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:964)
        at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:961)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.listStatus(DistributedFileSystem.java:961)
        at org.apache.hadoop.fs.Globber.listStatus(Globber.java:76)
        at org.apache.hadoop.fs.Globber.doGlob(Globber.java:234)
        at org.apache.hadoop.fs.Globber.glob(Globber.java:148)
        at org.apache.hadoop.fs.FileSystem.globStatus(FileSystem.java:1686)
        at io.pravega.storage.hdfs.HDFSStorage.findAllRaw(HDFSStorage.java:526)
        at io.pravega.storage.hdfs.HDFSStorage.findStatusForSegment(HDFSStorage.java:568)
        at io.pravega.storage.hdfs.HDFSStorage.lambda$getStreamSegmentInfo$0(HDFSStorage.java:160)
        at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:173)
        at io.pravega.storage.hdfs.HDFSStorage.getStreamSegmentInfo(HDFSStorage.java:159)
        at io.pravega.segmentstore.storage.rolling.RollingStorage.getHeaderInfo(RollingStorage.java:704)
        at io.pravega.segmentstore.storage.rolling.RollingStorage.openHandle(RollingStorage.java:665)
        at io.pravega.segmentstore.storage.rolling.RollingStorage.openWrite(RollingStorage.java:290)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$openWrite$0(AsyncStorageWrapper.java:83)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
        at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:531)
        at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:685)
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:788)
        at org.apache.hadoop.ipc.Client$Connection.access$3500(Client.java:410)
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1550)
        at org.apache.hadoop.ipc.Client.call(Client.java:1381)
        ... 44 common frames omitted
```
After discussing with Sandeep, we came to conclusion that the script had issue to get correct hdfs uri.

**Comment by sumit-bm** [comment]
Related to https://github.com/pravega/pravega/pull/3868/commits/0c78ad04e8507375eb1fdfcfb2c7aa10e0571775

**Comment by Richa-Srivastava** [comment]
Verified in the private build (https://raw.githubusercontent.com/pravega/pravega/0c78ad04e8507375eb1fdfcfb2c7aa10e0571775/docker/compose/swarm/scale_segmentstore) scale_segmentStore script is working fine with scaling segment stores and distributing segment containers properly to each SS. Also, no HDFS writeup issues found in scaled up SS.
