### ISSUE TITLE
ReadTxnWriteScaleWithFailoverTest is failing in docker swarm

### ISSUE THREAD

**Issue by anishakj** [pravega/pravega#3896]
**Problem description**
Test is failing with scaling timeout exception
```
 - TestFramework Exception. T019-06-07 07:27:23,092 1920187 [Time-limited test] ERROR i.p.t.system.AbstractReadWriteTest - Read write count mismatch => readCount = 103050, writeCount = 86750ype: InternalError, Details: Exception while running test method: readTxnWriteScaleWithFailoverTest
org.junit.runners.model.TestTimedOutException: test timed out after 1920 seconds
    at sun.misc.Unsafe.park(Native Method)
    at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
    at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1695)
    at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
    at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1775)
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
    at io.pravega.common.concurrent.Futures.lambda$await$0(Futures.java:68)
    at io.pravega.common.concurrent.Futures$$Lambda$450/776641930.run(Unknown Source)
    at io.pravega.common.Exceptions.handleInterrupted(Exceptions.java:115)
    at io.pravega.common.concurrent.Futures.await(Futures.java:66)
    at io.pravega.common.concurrent.Futures.await(Futures.java:53)
    at io.pravega.test.system.ReadTxnWriteScaleWithFailoverTest.readTxnWriteScaleWithFailoverTest(ReadTxnWriteScaleWithFailoverTest.java:174)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
Scaling has taken `52` minutes to complete the operation
```
grep -r testReadTxnWriteScaleStream | grep " scale "
controller_2019-06-07.22.log:2019-06-07 07:00:36,086 2430565 [grpc-default-executor-37] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=-7239537295852908700] scale called for stream testReadTxnWriteScaleScope104937671/testReadTxnWriteScaleStream.
controller_2019-06-07.22.log:2019-06-07 07:00:36,105 2430584 [controllerpool-19] INFO  i.p.c.s.stream.PersistentStreamBase - scale for stream testReadTxnWriteScaleScope104937671/testReadTxnWriteScaleStream accepted. Segments to seal = [0]
controller_2019-06-07.22.log:2019-06-07 07:00:36,257 2430736 [controllerpool-79] INFO  i.p.c.t.Stream.StreamMetadataTasks - [requestId=-7239537295852908700] scale for stream testReadTxnWriteScaleScope104937671/testReadTxnWriteScaleStream started successfully
controller_2019-06-07.22.log:2019-06-07 07:00:36,260 2430739 [controllerpool-80] INFO  i.p.c.s.e.r.ScaleOperationTask - [requestId=-7239537295852908700] starting scale request for testReadTxnWriteScaleScope104937671/testReadTxnWriteScaleStream segments [0] to new ranges [0.6=0.8, 0.0=0.2, 0.8=1.0, 0.4=0.6, 0.2=0.4]
controller_2019-06-07.38.log:2019-06-07 07:52:06,192 2070 [controllerpool-7] INFO  i.p.c.s.e.r.ScaleOperationTask - [requestId=-7239537295852908700] starting scale request for testReadTxnWriteScaleScope104937671/testReadTxnWriteScaleStream segments [0] to new ranges [0.6=0.8, 0.0=0.2, 0.8=1.0, 0.4=0.6, 0.2=0.4]
controller_2019-06-07.38.log:2019-06-07 07:52:06,340 2218 [controllerpool-61] INFO  i.p.c.s.e.r.ScaleOperationTask - [requestId=-7239537295852908700] scale processing for testReadTxnWriteScaleScope104937671/testReadTxnWriteScaleStream epoch 0 completed.
controller_2019-06-07.38.log:2019-06-07 07:52:06,340 2218 [controllerpool-61] INFO  i.p.c.s.e.r.ScaleOperationTask - [requestId=-7239537295852908700] scale request for testReadTxnWriteScaleScope104937671/testReadTxnWriteScaleStream segments [0] to new ranges [0.6=0.8, 0.0=0.2, 0.8=1.0, 0.4=0.6, 0.2=0.4] completed successfully.
```
**Problem location**
System tests

**Suggestions for an improvement**

**Comment by shiveshr** [comment]
From the logs, it appears controller started the scale successfully at 7:00:36 and attempted to send requests to segment stores to create new segments.
However, two of the requests never reached segment store. It is unclear from the logs why their futures were not completed, but there must be a code path in which it so happened. 
52 minutes later, when controller instance was shutdown and a new instance started, the new controller took over the responsibility for scale and completed it. 

I am trying to determine why the two requests didnt reach segment store and why they were stuck without completion. 
I will update my findings here.

**Comment by andreipaduroiu** [comment]
Would a timeout + retry have solved this problem?

**Comment by shiveshr** [comment]
Yes, a timeout can be a blanket fix for such issues either in controller or segment store.

**Comment by RaulGracia** [comment]
We have consistent green builds in all system tests builds, so closing this issue :)
