### ISSUE TITLE
Observed RocksDBException (I/O error, Read-only file system) in segment store log

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#3902]
Deployment details:
```
bookkeeper:0.5.0-2260.b477eec
pravega:0.5.0-2260.b477eec
zookeeper:3.5.4-beta-operator
pravega-operator:0.3.2
zookeeper-operator:0.2.1
```
Environment details: PKS / K8 with medium cluster:
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
6 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend

```
Running  longevity test (4 writer & 8 Reader) for 7d 19h.

After that observed this error in segment store
```
2019-06-11 10:50:19,066 674163103 [core-27] ERROR i.p.s.s.logs.OperationProcessor - OperationProcessor[15]: MemoryStateUpdater.process failure.
io.pravega.segmentstore.storage.CacheException: Unable to insert key 'SegmentId = 8444765, Offset = 1411876067' (CacheId=Container_15).
        at io.pravega.segmentstore.storage.impl.rocksdb.RocksDBCache.convert(RocksDBCache.java:277)
        at io.pravega.segmentstore.storage.impl.rocksdb.RocksDBCache.insert(RocksDBCache.java:179)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.append(StreamSegmentReadIndex.java:354)
        at io.pravega.segmentstore.server.reading.ContainerReadIndex.append(ContainerReadIndex.java:130)
        at io.pravega.segmentstore.server.logs.MemoryStateUpdater.addToReadIndex(MemoryStateUpdater.java:172)
        at io.pravega.segmentstore.server.logs.MemoryStateUpdater.process(MemoryStateUpdater.java:135)
        at io.pravega.segmentstore.server.logs.MemoryStateUpdater.process(MemoryStateUpdater.java:106)
        at io.pravega.segmentstore.server.logs.OperationProcessor.processCommits(OperationProcessor.java:417)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.rocksdb.RocksDBException: While fdatasync: /tmp/pravega/cache/cache_Container_15/002579.sst: I/O error
        at org.rocksdb.RocksDB.put(Native Method)
        at org.rocksdb.RocksDB.put(RocksDB.java:488)
        at io.pravega.segmentstore.storage.impl.rocksdb.RocksDBCache.insert(RocksDBCache.java:177)
        ... 16 common frames omitted
```
 Error states it is caused by 
**org.rocksdb.RocksDBException: While fdatasync: /tmp/pravega/cache/cache_Container_15/002579.sst: I/O error**

I/O which was running fine dropped to Writers (3/4) after this.

PS: complete log ~100 MB, will be sharing in slack separately.

**Comment by fpj** [comment]
@Raghuveera-Rao is it possible that the volume is full?

**Comment by Raghuveera-Rao** [comment]
> @Raghuveera-Rao is it possible that the volume is full?

Please let me know which volume are you looking for ?

**Comment by Raghuveera-Rao** [comment]
$ free -g
in segment store is giving this

```
  total       used       free     shared    buffers     cached
Mem:            31         13         17          1          0          7
-/+ buffers/cache:          5         25
Swap:           31          0         31

```

**Comment by RaulGracia** [comment]
@Raghuveera-Rao I think that @fpj refers to the PVC for the Segment Store cache, which is the one related to the I/O error with RocksDB.

**Comment by andreipaduroiu** [comment]
Please share the logs. This is usually indicative of some disk error or volume full, which means Pravega was misconfigured during deployment, or it could indicate that we are unable to make progress writing to Tier 2 and thus filling up the cache.

**Comment by andreipaduroiu** [comment]
I looked at the logs and I can conclude this is not due to a problem in Pravega, at least not due to not being able to write data to Tier 2. The Cache size is kept in check, but out of a sudden all cache operations (not just writes) for all Containers started failing with IO Errors.

A more indicative exception was doing a `remove`:

```
io.pravega.segmentstore.storage.CacheException: Unable to remove key 'SegmentId = 8286018, Offset = 9468801' (CacheId=Container_9).
	at io.pravega.segmentstore.storage.impl.rocksdb.RocksDBCache.convert(RocksDBCache.java:277)
	at io.pravega.segmentstore.storage.impl.rocksdb.RocksDBCache.remove(RocksDBCache.java:212)
	at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.lambda$updateGenerations$4(StreamSegmentReadIndex.java:237)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.updateGenerations(StreamSegmentReadIndex.java:235)
	at io.pravega.segmentstore.server.CacheManager.updateClients(CacheManager.java:273)
	at io.pravega.segmentstore.server.CacheManager.applyCachePolicy(CacheManager.java:216)
	at io.pravega.segmentstore.server.CacheManager.runOneIteration(CacheManager.java:120)
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:195)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.rocksdb.RocksDBException: While open a file for appending: /tmp/pravega/cache/cache_Container_9/002642.sst: Read-only file system
	at org.rocksdb.RocksDB.delete(Native Method)
	at org.rocksdb.RocksDB.delete(RocksDB.java:1145)
	at io.pravega.segmentstore.storage.impl.rocksdb.RocksDBCache.remove(RocksDBCache.java:210)
	... 15 common frames omitted
```


Looks like something happened to the volume on which RocksDB was operating on. Perhaps it is full?

**Comment by fpj** [comment]
Thanks everyone for reporting and analyzing the issue. There is no indication that this is an issue with Pravega that requires fixing. The errors reported here are due to the environment, and if anything, the investigation needs to be on why operations against the rocksdb volume started failing.
