### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded Error while running I/O

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#3903]
Deployment details:
```
bookkeeper:0.5.0-2260.b477eec
pravega:0.5.0-2260.b477eec
zookeeper:3.5.4-beta-operator
pravega-operator:0.3.2
zookeeper-operator:0.2.1
```

Environment details: PKS / K8 with medium cluster:
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
6 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```

Running longevity test (4 writer & 8 Reader) for 7d 19h.

Error in I/O client(longevity medium scale manager log)-
```
172.24.41.3 - - [11/Jun/2019:10:49:54 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 2722 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 1
INFO  [2019-06-11 10:50:19,078] io.pravega.longevity.testmanager.manager.TestPerformanceCollector: Received Error From task taskID : GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.io.ObjectOutputStream$BlockDataOutputStream.<init>(Unknown Source)
        at java.io.ObjectOutputStream.<init>(Unknown Source)
        at io.pravega.client.stream.impl.JavaSerializer.serialize(JavaSerializer.java:36)
        at io.pravega.client.stream.impl.JavaSerializer.serialize(JavaSerializer.java:26)
        at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEventInternal(EventStreamWriterImpl.java:114)
        at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEvent(EventStreamWriterImpl.java:108)
        at io.pravega.longevity.testworker.workers.writers.PravegaWriterState.doWrite(PravegaWriterState.kt:64)
        at io.pravega.longevity.testworker.workers.writers.PravegaWriter.writeEvent(PravegaWriter.java:196)
        at io.pravega.longevity.testworker.workers.writers.PravegaWriter.start(PravegaWriter.java:144)
        at io.pravega.longevity.testworker.workers.writers.WriterWorkerManager.lambda$start$0(WriterWorkerManager.java:134)
        at io.pravega.longevity.testworker.workers.writers.WriterWorkerManager$$Lambda$253/212874257.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

After this error, I/O got affected. The writer dropped to Writers (3/4).

PS: complete log ~100 MB, will be sharing in slack separately.

**Comment by fpj** [comment]
@Raghuveera-Rao if you observe in the stack trace you posted, this is an OOM error in your test harness, not in Pravega.

**Comment by sumit-bm** [comment]
@fpj is right, let us analyze the logs collected and let see why writer failed
