### ISSUE TITLE
Deadlock found when call ReaderGroupManager.withScope and StreamManager.create concurrently.

### ISSUE THREAD

**Issue by jingjinglll** [pravega/pravega#3912]
**Problem description**
Two different threads call ReaderGroupManager.withScope and StreamManager.create concurrently at the first time may lead to deadlock.
From the stacktrace you can see the BootstrapSender obtains Runtime lock but wait for IOUtil clinit. The Main thread hangs at IOUtil clinit but waits for the Runtime lock.

Stacktrace:
```
"BootstrapSender-#0" #10 prio=5 os_prio=0 tid=0x00007efe70a80800 nid=0x24 in Object.wait() [0x00007efe3734f000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.FileChannelImpl.<clinit>(FileChannelImpl.java:1224)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	- locked <0x00000000d972cb80> (a java.util.Vector)
	- locked <0x00000000d9847c28> (a java.util.Vector)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	- locked <0x00000000d9730fc0> (a java.lang.Runtime)
	at java.lang.System.load(System.java:1086)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:229)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:221)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:207)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:167)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:199)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:61)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:33)
	at io.pravega.client.netty.impl.ConnectionFactoryImpl.getEventLoopGroup(ConnectionFactoryImpl.java:97)
	at io.pravega.client.netty.impl.ConnectionFactoryImpl.<init>(ConnectionFactoryImpl.java:86)
	at io.pravega.client.netty.impl.ConnectionFactoryImpl.<init>(ConnectionFactoryImpl.java:79)
	at io.pravega.client.admin.ReaderGroupManager.withScope(ReaderGroupManager.java:46)
	at com.dell.pravegasearch.common.streaming.pravega.PravegaStream.<init>(PravegaStream.java:79)
	at com.dell.pravegasearch.common.streaming.pravega.PravegaStream.lambda$getInstance$0(PravegaStream.java:113)
	at com.dell.pravegasearch.common.streaming.pravega.PravegaStream$$Lambda$18/1492733469.apply(Unknown Source)
	at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:324)
	at com.dell.pravegasearch.common.streaming.pravega.PravegaStream.getInstance(PravegaStream.java:112)
	at com.dell.pravegasearch.common.resourcemanager.stream.AbstractStreamManager.createStream(AbstractStreamManager.java:69)
	at com.dell.pravegasearch.common.bootstrap.Bootstrap.sender(Bootstrap.java:57)
	at com.dell.pravegasearch.common.membership.MembershipFactory.lambda$getActionRunner$0(MembershipFactory.java:48)
	at com.dell.pravegasearch.common.membership.MembershipFactory$$Lambda$8/990679445.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000000d9656bf0> (a java.util.concurrent.ThreadPoolExecutor$Worker)
"main" #1 prio=5 os_prio=0 tid=0x00007efe7000e800 nid=0x18 waiting for monitor entry [0x00007efe7976f000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.Runtime.loadLibrary0(Runtime.java:862)
	- waiting to lock <0x00000000d9730fc0> (a java.lang.Runtime)
	at java.lang.System.loadLibrary(System.java:1122)
	at sun.nio.ch.IOUtil$1.run(IOUtil.java:359)
	at sun.nio.ch.IOUtil$1.run(IOUtil.java:357)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.nio.ch.IOUtil.<clinit>(IOUtil.java:356)
	at sun.nio.ch.Util.<clinit>(Util.java:48)
	at sun.nio.ch.SelectorImpl.<init>(SelectorImpl.java:57)
	at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:64)
	at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:173)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:149)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at io.grpc.netty.Utils$DefaultEventLoopGroupResource.create(Utils.java:184)
	at io.grpc.netty.Utils$DefaultEventLoopGroupResource.create(Utils.java:168)
	at io.grpc.internal.SharedResourceHolder.getInternal(SharedResourceHolder.java:104)
	- locked <0x00000000d5e597a0> (a io.grpc.internal.SharedResourceHolder)
	at io.grpc.internal.SharedResourceHolder.get(SharedResourceHolder.java:74)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:466)
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:313)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:331)
	at io.pravega.client.stream.impl.ControllerImpl.<init>(ControllerImpl.java:172)
	at io.pravega.client.stream.impl.ControllerImpl.<init>(ControllerImpl.java:127)
	at io.pravega.client.admin.impl.StreamManagerImpl.<init>(StreamManagerImpl.java:46)
	at io.pravega.client.admin.StreamManager.create(StreamManager.java:40)
	at com.dell.pravegasearch.common.clustermap.sharedmap.WorkloadSharedMap.<clinit>(WorkloadSharedMap.java:88)
	at com.dell.pravegasearch.common.clustermap.ClusterMapManager$WorkloadMap.hasJoined(ClusterMapManager.java:53)
	at com.dell.pravegasearch.common.membership.MembershipHelper.awaitRegistration(MembershipHelper.java:40)
	at com.dell.pravegasearch.shardworker.ShardWorker.startUp(ShardWorker.java:92)
	at com.dell.pravegasearch.common.workload.AbstractWorkload.start(AbstractWorkload.java:75)
	at com.dell.pravegasearch.shardworker.Main.main(Main.java:104)
```
**Problem location**
Found in starting PravegaSearch workloads concurrently.

**Suggestions for an improvement**
There is a similar jdk bug
https://bugs.openjdk.java.net/browse/JDK-8194653
It is fixed in 8u231 which will be released in Oct 2019.
A workaround is to preload IOUtil

**Comment by jingjinglll** [comment]
Workaround this issue.
