### ISSUE TITLE
Transactions unexpectedly aborted during failovers

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#3918]
**Problem description**
In `MultiReaderTxnWriterWithFailoverTest` (and in other txn tests involving Transactions), we find Transactions being unexpectedly aborted after failovers, which make the test to fail. This is an instance of this problem:
1) All the transactions are being committed and read successfully through the test (873 transactions), until the failovers leave the test with 1 controller and 1 segment store.

2) The origin of the problems is at the end of the test, in which I see a failure committing a transaction: 

```
2019-05-24 14:28:26,347 284243 [Time-limited test] INFO  i.p.t.system.AbstractReadWriteTest - Unable to commit transaction:
io.pravega.client.stream.TxnFailedException: io.pravega.client.segment.impl.SegmentSealedException: SegmentSealed Exception for segment:testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/4.#epoch.0#transaction.0000000000000000000000000000768d sealed for writer 60bc7324-0356-411f-a095-eb92f849b512
    at io.pravega.client.stream.impl.SegmentTransactionImpl.flush(SegmentTransactionImpl.java:94)
    at io.pravega.client.stream.impl.SegmentTransactionImpl.close(SegmentTransactionImpl.java:100)
    at io.pravega.client.stream.impl.TransactionalEventStreamWriterImpl$TransactionImpl.commit(TransactionalEventStreamWriterImpl.java:111)
```

3) Inspecting what happened immediately before, we can see that the writer was able to correctly write events to that transaction for some time:
```
2019-05-24 14:28:25,356 283252 [MultiReaderTxnWriterWithFailoverTest-main-5] DEBUG i.p.t.system.AbstractReadWriteTest - Writing event: 00000000-0000-0000-0000-00000000768d:0 into transaction: 00000000-0000-0000-0000-00000000768d
...
2019-05-24 14:28:25,357 283253 [MultiReaderTxnWriterWithFailoverTest-main-5] DEBUG i.p.t.system.AbstractReadWriteTest - Writing event: 00000000-0000-0000-0000-00000000768d:24 into transaction: 00000000-0000-0000-0000-00000000768d
```
Note that these events were being written to segment (`3.#epoch.0#transaction.0000000000000000000000000000768d`):

```
2019-05-24 14:28:25,357 283253 [MultiReaderTxnWriterWithFailoverTest-main-5] TRACE i.p.c.s.i.SegmentOutputStreamImpl - Sending append request: Append(segment=testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/3.#epoch.0#transaction.0000000000000000000000000000768d, writerId=694e38d6-4857-4239-981e-47c51dfecc6f, eventNumber=25, eventCount=1, data=CompositeByteBuf(ridx: 0, widx: 54, cap: 54, components=2), expectedLength=null, flowId=18945100742656)
```

4) The test code is done in a way that the writer changes the routing key "within a transaction" after 25 events, meaning that if the transaction has more than one segment, there are chances for the writer to write events in more than one segment:
```
2019-05-24 14:28:25,357 283253 [MultiReaderTxnWriterWithFailoverTest-main-5] INFO  i.p.t.system.AbstractReadWriteTest - Renew transaction writer routing key and reinitialize seqNumber at event 25.
```

5) Then, the writer tries to connect to the new segment to write events within the transaction (`4.#epoch.0#transaction.0000000000000000000000000000768d`):
```
2019-05-24 14:28:25,359 283255 [clientInternal-23] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=10.0.0.166, port=12345) for testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/4.#epoch.0#transaction.0000000000000000000000000000768d, writerID: 60bc7324-0356-411f-a095-eb92f849b512
...
2019-05-24 14:28:25,359 283255 [epollEventLoopGroup-4-12] TRACE i.p.s.protocol.netty.CommandEncoder - Encoding message to send over the wire WireCommands.SetupAppend(type=SETUP_APPEND, requestId=18949395709952, writerId=60bc7324-0356-411f-a095-eb92f849b512, segment=testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/4.#epoch.0#transaction.0000000000000000000000000000768d, delegationToken=)
```

6) But at this point is where things start to go wrong, as the segment store replies to the writer with `NoSuchSegment`:
```
2019-05-24 14:28:25,806 283702 [epollEventLoopGroup-4-12] DEBUG i.p.client.netty.impl.FlowHandler - 10.0.0.166 processing reply No such segment: testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/4.#epoch.0#transaction.0000000000000000000000000000768d with flow Flow(flowId=4412, requestSequenceNumber=0)
```
7) Apparently, the reason is that the transaction has been inadvertently aborted:
```
2019-05-24 14:28:25,806 283702 [epollEventLoopGroup-4-12] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Transaction Segment: testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/4.#epoch.0#transaction.0000000000000000000000000000768d no longer exists since the txn is aborted.
```
But the writer is not aware of that and tries to re-connect to that segment:
```
2019-05-24 14:28:25,806 283702 [MultiReaderTxnWriterWithFailoverTest-main-5] DEBUG i.p.c.s.i.SegmentOutputStreamImpl - (Re)connect invoked, Segment: testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/4.#epoch.0#transaction.0000000000000000000000000000768d, writerID: 60bc7324-0356-411f-a095-eb92f849b512
...
2019-05-24 14:28:25,807 283703 [MultiReaderTxnWriterWithFailoverTest-main-5] DEBUG i.p.c.s.i.SegmentOutputStreamImpl - (Re)connect invoked, Segment: testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/4.#epoch.0#transaction.0000000000000000000000000000768d, writerID: 60bc7324-0356-411f-a095-eb92f849b512
```

8 ) The writer tries to commit the transaction anyway, but the Controller returns an error, given that the transaction has been already committed/aborted (`SegmentSealed Exception`):
```
2019-05-24 14:28:25,807 283703 [MultiReaderTxnWriterWithFailoverTest-main-5] WARN  i.p.c.s.i.SegmentOutputStreamImpl - Exception observed during a flush on a transaction segment, this indicates that the transaction is commited/aborted. Details: SegmentSealed Exception for segment:testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/4.#epoch.0#transaction.0000000000000000000000000000768d
2019-05-24 14:28:25,807 283703 [MultiReaderTxnWriterWithFailoverTest-main-5] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Failing connection for writer 60bc7324-0356-411f-a095-eb92f849b512 with exception io.pravega.client.segment.impl.SegmentSealedException: SegmentSealed Exception for segment:testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/4.#epoch.0#transaction.0000000000000000000000000000768d
2019-05-24 14:28:25,807 283703 [MultiReaderTxnWriterWithFailoverTest-main-5] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Handling exception io.pravega.client.segment.impl.SegmentSealedException: SegmentSealed Exception for segment:testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/4.#epoch.0#transaction.0000000000000000000000000000768d for connection null on writer 60bc7324-0356-411f-a095-eb92f849b512. SetupCompleted: null, Closed: false
```

This connects with the bullet number 2).
9) So, the question is, why this transaction has been aborted behind the scenes? Looking into the server logs, we see that the Controller properly creates the transaction and its segments:

```
2019-05-24 14:26:08,701 1619371 [controllerpool-59] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-00000000768d, added txn to host-txn index of host=controller-61a3554c-985b-40ee-882b-fc82d331cfec
2019-05-24 14:26:08,707 1619377 [controllerpool-44] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-00000000768d, created in store
2019-05-24 14:26:08,713 1619383 [epollEventLoopGroup-2-43] DEBUG i.p.client.netty.impl.FlowHandler - 10.0.0.225 processing reply WireCommands.SegmentCreated(type=SEGMENT_CREATED, requestId=398409, segment=testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/0.#epoch.0#transaction.0000000000000000000000000000768d) with flow Flow(flowId=0, requestSequenceNumber=398409)
2019-05-24 14:26:08,713 1619383 [epollEventLoopGroup-2-43] DEBUG i.p.controller.server.SegmentHelper - createTransaction testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/0.#epoch.0#transaction.0000000000000000000000000000768d TransactionCreated
2019-05-24 14:26:08,722 1619392 [epollEventLoopGroup-2-69] DEBUG i.p.client.netty.impl.FlowHandler - 10.0.0.225 processing reply WireCommands.SegmentCreated(type=SEGMENT_CREATED, requestId=398408, segment=testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/3.#epoch.0#transaction.0000000000000000000000000000768d) with flow Flow(flowId=0, requestSequenceNumber=398408)
2019-05-24 14:26:08,722 1619392 [epollEventLoopGroup-2-60] DEBUG i.p.client.netty.impl.FlowHandler - 10.0.0.225 processing reply WireCommands.SegmentCreated(type=SEGMENT_CREATED, requestId=398410, segment=testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/4.#epoch.0#transaction.0000000000000000000000000000768d) with flow Flow(flowId=0, requestSequenceNumber=398410)
2019-05-24 14:26:08,722 1619392 [epollEventLoopGroup-2-60] DEBUG i.p.controller.server.SegmentHelper - createTransaction testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/4.#epoch.0#transaction.0000000000000000000000000000768d TransactionCreated
2019-05-24 14:26:08,722 1619392 [epollEventLoopGroup-2-68] DEBUG i.p.client.netty.impl.FlowHandler - 10.0.0.225 processing reply WireCommands.SegmentCreated(type=SEGMENT_CREATED, requestId=398406, segment=testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/1.#epoch.0#transaction.0000000000000000000000000000768d) with flow Flow(flowId=0, requestSequenceNumber=398406)
2019-05-24 14:26:08,722 1619392 [epollEventLoopGroup-2-69] DEBUG i.p.controller.server.SegmentHelper - createTransaction testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/3.#epoch.0#transaction.0000000000000000000000000000768d TransactionCreated
2019-05-24 14:26:08,722 1619392 [epollEventLoopGroup-2-68] DEBUG i.p.controller.server.SegmentHelper - createTransaction testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/1.#epoch.0#transaction.0000000000000000000000000000768d TransactionCreated
2019-05-24 14:26:08,757 1619427 [epollEventLoopGroup-2-118] DEBUG i.p.client.netty.impl.FlowHandler - 10.0.0.166 processing reply WireCommands.SegmentCreated(type=SEGMENT_CREATED, requestId=398407, segment=testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/2.#epoch.0#transaction.0000000000000000000000000000768d) with flow Flow(flowId=0, requestSequenceNumber=398407)
2019-05-24 14:26:08,757 1619427 [epollEventLoopGroup-2-118] DEBUG i.p.controller.server.SegmentHelper - createTransaction testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/2.#epoch.0#transaction.0000000000000000000000000000768d TransactionCreated
```

10) In the segment store side, we see that these segments are managed by 2 instances: (editado)
(SS 1 - running in master-1) - Containers 2, 3

```
2019-05-24 14:26:08,726 6370954 [epollEventLoopGroup-11-43] DEBUG i.p.s.s.c.StreamSegmentContainer - SegmentContainer[2]: createStreamSegment [testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/2.#epoch.0#transaction.0000000000000000000000000000768d]
```

11) However, just after the creation of these segments in SS 2 we observe problems in its containers:
```
2019-05-24 14:26:08,916 206926 [core-24] ERROR i.p.s.s.h.handler.AppendProcessor - Error (Segment = 'testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/0.#epoch.0#transaction.0000000000000000000000000000768a', Operation = 'append')
io.pravega.segmentstore.server.IllegalContainerStateException: Container 1 is in an invalid state for this operation. Expected: RUNNING; Actual: TERMINATED.
    at io.pravega.segmentstore.server.logs.DurableLog.ensureRunning(DurableLog.java:388)
    at io.pravega.segmentstore.server.logs.DurableLog.add(DurableLog.java:295)
...
2019-05-24 14:26:08,929 206939 [core-13] ERROR i.p.s.s.h.handler.AppendProcessor - Error (Segment = 'testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/4.#epoch.0#transaction.0000000000000000000000000000768c', Operation = 'append')
io.pravega.segmentstore.server.IllegalContainerStateException: Container 0 is in an invalid state for this operation. Expected: RUNNING; Actual: TERMINATED.
    at io.pravega.segmentstore.server.logs.DurableLog.ensureRunning(DurableLog.java:388)
    at io.pravega.segmentstore.server.logs.DurableLog.add(DurableLog.java:295)
```

As well as some networking problem trying to contact the controller before that:
```
2019-05-24 14:26:09,879 207889 [grpc-default-executor-2] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getCurrentSegments with trace id 0 failed with server error.
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
...
Caused by: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: Host is unreachable: /10.0.0.162:9090
```
That seem to be related to the fact that the SS 2 stops owning the containers for segment (`4.#epoch.0#transaction.0000000000000000000000000000768d`):
```
2019-05-24 14:26:09,883 207893 [epollEventLoopGroup-11-44] WARN  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=10115] Wrong host. Segment = '_system/_tables/testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/transactionsInEpoch-0.#.10d7b3d2-1723-4617-b5e8-c2b2b0252c2f' (Container 0) is not owned. Operation = 'readTable').
2019-05-24 14:26:09,883 207893 [epollEventLoopGroup-11-46] WARN  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=10116] Wrong host. Segment = '_system/_tables/testMultiReaderWriterTxnScope1599605987/testMultiReaderWriterTxnStream/transactionsInEpoch-0.#.10d7b3d2-1723-4617-b5e8-c2b2b0252c2f' (Container 0) is not owned. Operation = 'readTable').
```

**Problem location**
Transaction (segment?) management during failovers.

**Suggestions for an improvement**
Understand and fix the issue.

**Comment by RaulGracia** [comment]
I'm debugging one failure in Docker Swarm tests (`ReadTxnWriteScaleWithFailoverTest`), and it looks like the Controller was stuck for a long time without being able to create transactions when the failovers started.
```
2019-06-13 18:05:46,775 2605 [Time-limited test] INFO  i.p.t.system.AbstractFailoverTests - Read count: 0, write count: 0 without any failover
2019-06-13 18:06:26,775 42605 [Time-limited test] INFO  i.p.t.system.AbstractFailoverTests - Read count: 120600, write count: 120350 without any failover after sleep before scaling
2019-06-13 18:07:16,925 92755 [Time-limited test] INFO  i.p.t.system.AbstractFailoverTests - Read count: 192750, write count: 192450 after Segment Store  failover after sleep
2019-06-13 18:08:02,010 137840 [Time-limited test] INFO  i.p.t.system.AbstractFailoverTests - Read count: 306350, write count: 306150 after controller failover after sleep

(PROBLEMS STARTED HERE, UNDER CONTROLLER AND SEGMENT STORE FAILOVERS)

2019-06-13 18:09:12,156 207986 [Time-limited test] INFO  i.p.t.system.AbstractFailoverTests - Read count: 315050, write count: 315050 with Segment Store  and controller failover after sleep
2019-06-13 18:11:02,442 318272 [Time-limited test] INFO  i.p.t.system.AbstractFailoverTests - Read count: 315050, write count: 315050 without any failover
2019-06-13 18:11:42,443 358273 [Time-limited test] INFO  i.p.t.system.AbstractFailoverTests - Read count: 315050, write count: 315050 without any failover after sleep before scaling
2019-06-13 18:12:32,504 408334 [Time-limited test] INFO  i.p.t.system.AbstractFailoverTests - Read count: 315050, write count: 315050 after Segment Store  failover after sleep
2019-06-13 18:13:27,574 463404 [Time-limited test] INFO  i.p.t.system.AbstractFailoverTests - Read count: 315050, write count: 315050 after controller failover after sleep
2019-06-13 18:14:37,693 533523 [Time-limited test] INFO  i.p.t.system.AbstractFailoverTests - Read count: 315050, write count: 315050 with Segment Store  and controller failover after sleep
2019-06-13 18:37:19,573 1895403 [Time-limited test] INFO  i.p.t.system.AbstractFailoverTests - Read count: 315050, write count: 346550 without any failover
```

This is one of the  transactions that was stuck there:
```
2019-06-13 18:08:48,332 2307159 [controllerpool-66] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-0000000030fd, added txn to host-txn index of host=controller-c95dcc82-3e4c-4726-a720-5e201f1500b7
2019-06-13 18:08:48,338 2307165 [controllerpool-40] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-0000000030fd, created in store
2019-06-13 18:35:28,085 3906912 [controllerpool-33] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-0000000030fd, added txn to host-txn index of host=controller-c95dcc82-3e4c-4726-a720-5e201f1500b7
2019-06-13 18:35:28,561 3907388 [controllerpool-52] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-0000000030fd, sealed successfully, commit=true
2019-06-13 18:35:28,565 3907392 [controllerpool-62] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-0000000030fd, removed from timeout service
2019-06-13 18:35:28,566 3907393 [controllerpool-40] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-0000000030fd, removed txn from host-txn index of host=controller-c95dcc82-3e4c-4726-a720-5e201f1500b7
```
Visibly, during the Transaction creation, it took almost 30 minutes to create the transaction metadata in the Segment Store, which happens during failover scenarios. At the beginning of this time for which transactions are stuck, I see one Controller showing a huge amount log messages from `ContinuationTokenAsyncIterator`, but apparently without making any progress:

```
2019-06-13 18:08:48,362 2307189 [controllerpool-15] DEBUG i.p.c.u.ContinuationTokenAsyncIterator - Received the following collection after calling the function: [00000000-0000-0000-0000-0000000057bb, 00000000-0000-0000-0000-0000000030fd, 00000000-0000-0000-0000-0000000030fa, 00000000-0000-0000-0000-0000000030fb, 00000000-0000-0000-0000-0000000030fc, 00000000-0000-0000-0000-0000000030f9] with continuation token: UnpooledHeapByteBuf(ridx: 0, widx: 24, cap: 24/24)

... 3.3K calls...

18:09:23,717 2342544 [controllerpool-2] DEBUG i.p.c.u.ContinuationTokenAsyncIterator - Received the following collection after calling the function: [00000000-0000-0000-0000-0000000057bb, 00000000-0000-0000-0000-0000000030fd, 00000000-0000-0000-0000-0000000030fa, 00000000-0000-0000-0000-0000000030fb, 00000000-0000-0000-0000-0000000030fc, 00000000-0000-0000-0000-0000000030f9] with continuation token: UnpooledHeapByteBuf(ridx: 0, widx: 24, cap: 24/24)
```

Apart from that, it looks that there is some problem with communication between Controller and Segment Stores, as the Controller tries up to 6 times to create the Transaction Segment, which is not answered until 30 minutes after the first request:
```
(REQUESTS)
2019-06-13 18:14:16,818 2844390 [epollEventLoopGroup-11-50] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=307782] Creating stream segment WireCommands.CreateSegment(type=CREATE_SEGMENT, requestId=307782, segment=testReadTxnWriteScaleScope1358271482/testReadTxnWriteScaleStream/0.#epoch.0#transaction.000000000000000000000000000030fd, scaleType=0, targetRate=0, delegationToken=).
2019-06-13 18:08:48,338 2515910 [epollEventLoopGroup-11-68] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Processing request: WireCommands.CreateSegment(type=CREATE_SEGMENT, requestId=238003, segment=testReadTxnWriteScaleScope1358271482/testReadTxnWriteScaleStream/0.#epoch.0#transaction.000000000000000000000000000030fd, scaleType=0, targetRate=0, delegationToken=)
2019-06-13 18:10:09,174 20888 [epollEventLoopGroup-11-9] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=302186] Creating stream segment WireCommands.CreateSegment(type=CREATE_SEGMENT, requestId=302186, segment=testReadTxnWriteScaleScope1358271482/testReadTxnWriteScaleStream/0.#epoch.0#transaction.000000000000000000000000000030fd, scaleType=0, targetRate=0, delegationToken=).
2019-06-13 18:10:10,178 21892 [epollEventLoopGroup-11-23] INFO
i.p.s.s.h.h.PravegaRequestProcessor - [requestId=302192] Creating stream segment WireCommands.CreateSegment(type=CREATE_SEGMENT, requestId=302192, segment=testReadTxnWriteScaleScope1358271482/testReadTxnWriteScaleStream/0.#epoch.0#transaction.000000000000000000000000000030fd, scaleType=0, targetRate=0, delegationToken=).

(RESPONSE)
2019-06-13 18:35:27,855 3906682 [epollEventLoopGroup-2-138] DEBUG i.p.client.netty.impl.FlowHandler - 10.0.0.19 processing reply WireCommands.SegmentCreated(type=SEGMENT_CREATED, requestId=307782, segment=testReadTxnWriteScaleScope1358271482/testReadTxnWriteScaleStream/0.#epoch.0#transaction.000000000000000000000000000030fd) with flow Flow(flowId=0, requestSequenceNumber=307782)
``` 
This behavior is quite odd, and looks like that a response from `PravegaRequestProcessor` got stuck and left the client waiting for it until, after some retries, the request completed. In fact, note that the reply from `PravegaRequestProcessor` is issues by the Segment Store at `2019-06-13 18:35:27,855`, which corresponds to a request from the Controller issued at `2019-06-13 18:14:16,818` (see `requestId=307782`)
