### ISSUE TITLE
SegmentHelper should not throw a ConnectionFailedException incase of TableSegmentIsEmpty response for deleteTableSegment

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#3921]
**Problem description**
Observing the following stack trace with the latest master.

```
2019-06-18 01:50:06,489 3487457 [epollEventLoopGroup-2-1] WARN  i.p.c.s.s.PravegaTablesStoreHelper - exception of unknown type thrown delete table: _system/_tables/testReadTxnWriteAutoScaleScope34623
0808/testReadTxnWriteAutoScaleStream/transactionsInEpoch-4.#.fb7c1f21-b793-4761-adf7-655e5f417d36
io.pravega.shared.protocol.netty.ConnectionFailedException: Unexpected reply of Table Segment is not empty: _system/_tables/testReadTxnWriteAutoScaleScope346230808/testReadTxnWriteAutoScaleStream/transactionsInEpoch-4.#.fb7c1f21-b793-4761-adf7-655e5f417d36 when expecting one of class io.pravega.shared.protocol.netty.WireCommands$SegmentDeleted, class io.pravega.shared.protocol.netty.WireCommands
$NoSuchSegment
        at io.pravega.controller.server.SegmentHelper.transformReply(SegmentHelper.java:1105)
        at io.pravega.controller.server.SegmentHelper.lambda$deleteTableSegment$5(SegmentHelper.java:519)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at io.pravega.client.netty.impl.RawClient.reply(RawClient.java:104)
        at io.pravega.client.netty.impl.RawClient.access$300(RawClient.java:36)
        at io.pravega.client.netty.impl.RawClient$ResponseProcessor.process(RawClient.java:63)
        at io.pravega.client.netty.impl.FlowHandler.lambda$channelRead$2(FlowHandler.java:209)
        at java.util.Optional.ifPresent(Optional.java:159)
        at io.pravega.client.netty.impl.FlowHandler.channelRead(FlowHandler.java:207)
```

**Problem location**

SegmentHelper.java

**Suggestions for an improvement**
We should throw a `new WireCommandFailedException(type, WireCommandFailedException.Reason.TableSegmentNotEmpty)` instead of throwing a blanket 
`ConnectionFailedException` .

All other operations on SegmentHelper should be reviewed accordingly.

**Comment by huide9** [comment]
thank you Sandeep for pointing this out. 
Checked the committed code, the exception and the replies need to be handled so far are listed below:
*WireCommands.TableSegmentNotEmpty* was missing.  correction will be commit soon. 
```
exceptions / unexpected replies::
        connectionDropped()
	processingFailure()
	authTokenCheckFailed()
	WireCommands.WrongHost wrongHost
       	WireCommands.TableSegmentNotEmpty
expected replies:
	WireCommands.SegmentAlreadyExists
	WireCommands.SegmentCreated
	WireCommands.NoSuchSegment
	WireCommands.SegmentDeleted
	WireCommands.SegmentTruncated
	WireCommands.SegmentIsTruncated
	WireCommands.SegmentSealed
	WireCommands.SegmentIsSealed
	WireCommands.SegmentAlreadyExisted
	WireCommands.SegmentCreated
```
