### ISSUE TITLE
Observed reader failure and SegmentContainer failed with "ERROR i.p.s.s.s.StreamSegmentContainerRegistry - Critical failure for SegmentContainer Container Id = 29, State = FAILED." while running IO

### ISSUE THREAD

**Issue by vedanthh** [pravega/pravega#3931]
**Observed reader failure and SegmentContainer failed with "ERROR i.p.s.s.s.StreamSegmentContainerRegistry - Critical failure for SegmentContainer Container Id = 29, State = FAILED. {} io.pravega.segmentstore.contracts.StreamingException: OperationProcessor stopped unexpectedly (no error) but DurableLog was not currently stopping" while running IO using Longevity with moderate workload (Total - 4 readers, 3 writers, ~50 events/sec, ~ 40 KB/s IO)** 

**Observed 1 reader failure as well out of 4 during this run**
```
INFO  [2019-06-20 06:29:21,650] io.pravega.longevity.utils.PerformanceUtils: Readers (3/4): events:475,309,330, events/sec:946, KB/sec:725.89355
```

**Environment details: PKS / K8 with medium cluster:**
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
```
Pravega version: 0.5.0-2269.6f8a820
Zookeeper Operator : tristan1900/zookeeper:0.2
Pravega Operator: pravega/pravega-operator:0.3.2 
```
**Snip of Error:**
```
2019-06-19 22:43:10,543 487252969 [core-23] WARN  i.p.s.s.i.bookkeeper.BookKeeperLog - Log[29]: Too many rollover failures; closing.
java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.segmentstore.storage.DataLogWriterNotPrimaryException: Unable to acquire exclusive write lock for log (path = 'pravega/pravega/segmentstore/containers/9/2/29').
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:874)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:690)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.segmentstore.storage.DataLogWriterNotPrimaryException: Unable to acquire exclusive write lock for log (path = 'pravega/pravega/segmentstore/containers/9/2/29').
        at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$3(Retry.java:214)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
        ... 12 common frames omitted
Caused by: java.util.concurrent.CompletionException: io.pravega.segmentstore.storage.DataLogWriterNotPrimaryException: Unable to acquire exclusive write lock for log (path = 'pravega/pravega/segmentstore/containers/9/2/29').
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:708)
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687)
        ... 8 common frames omitted
Caused by: io.pravega.segmentstore.storage.DataLogWriterNotPrimaryException: Unable to acquire exclusive write lock for log (path = 'pravega/pravega/segmentstore/containers/9/2/29').
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.persistMetadata(BookKeeperLog.java:802)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.updateMetadata(BookKeeperLog.java:756)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.rollover(BookKeeperLog.java:856)
        at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705)
        ... 9 common frames omitted
Caused by: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /pravega/pravega/segmentstore/containers/9/2/29
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.setData(ZooKeeper.java:2272)
        at org.apache.curator.framework.imps.SetDataBuilderImpl$4.call(SetDataBuilderImpl.java:291)
        at org.apache.curator.framework.imps.SetDataBuilderImpl$4.call(SetDataBuilderImpl.java:287)
        at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64)
        at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)
        at org.apache.curator.framework.imps.SetDataBuilderImpl.pathInForeground(SetDataBuilderImpl.java:284)
        at org.apache.curator.framework.imps.SetDataBuilderImpl.forPath(SetDataBuilderImpl.java:270)
        at org.apache.curator.framework.imps.SetDataBuilderImpl.forPath(SetDataBuilderImpl.java:33)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.persistMetadata(BookKeeperLog.java:794)
        ... 12 common frames omitted
2019-06-19 22:43:10,543 487252969 [core-23] ERROR i.p.s.s.h.handler.AppendProcessor - Error (Segment = 'longevity/small/1.#epoch.0', Operation = 'append')
java.util.concurrent.CancellationException: BookKeeperLog has been closed.
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.lambda$close$1(BookKeeperLog.java:170)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.close(BookKeeperLog.java:170)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.handleRolloverFailure(BookKeeperLog.java:146)
        at io.pravega.common.function.Callbacks.invokeSafely(Callbacks.java:54)
        at io.pravega.segmentstore.storage.impl.bookkeeper.SequentialAsyncProcessor.lambda$runInternal$0(SequentialAsyncProcessor.java:85)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.pravega.common.concurrent.Futures$Loop.handleException(Futures.java:729)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:690)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

```
2019-06-19 22:43:11,741 487254167 [core-13] ERROR i.p.s.s.s.StreamSegmentContainerRegistry - Critical failure for SegmentContainer Container Id = 29, State = FAILED. {}
io.pravega.segmentstore.contracts.StreamingException: OperationProcessor stopped unexpectedly (no error) but DurableLog was not currently stopping.
        at io.pravega.segmentstore.server.logs.DurableLog.queueStoppedHandler(DurableLog.java:405)
        at io.pravega.common.concurrent.Services$ShutdownListener.terminated(Services.java:120)
        at com.google.common.util.concurrent.AbstractService$3.call(AbstractService.java:95)
        at com.google.common.util.concurrent.AbstractService$3.call(AbstractService.java:92)
        at com.google.common.util.concurrent.ListenerCallQueue$PerListenerQueue.run(ListenerCallQueue.java:205)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
```
2019-06-19 22:44:26,710 487329136 [core-16] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], Current = [21, 22, 23, 24, 25, 26, 27, 28, 30, 31], PendingTasks = [29], ToStart = [], ToStop = [].
2019-06-19 22:44:35,551 487337977 [epollEventLoopGroup-11-7] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection:
io.pravega.segmentstore.server.IllegalContainerStateException: Container 29 is in an invalid state for this operation. Expected: RUNNING; Actual: STARTING.
```

**Comment by fpj** [comment]
Change of segment container ownership isn't a problem, so the exception indicating a loss of ownership is expected behavior. As long as the segment container started correctly elsewhere, this is not an issue.

About the reader failing, why did it fail exactly?

**Comment by vedanthh** [comment]
@fpj Looks like reader failed due to `RetriesExhaustedException`, I have posted complete cluster logs in internal channel.

Note: In this cluster Longevity IO was Running fine for ~ 5d 11h

**Snip from worker log**
```
2019-06-19 22:44:53,107 474189354 [pool-7-thread-2] ERROR i.p.l.t.w.r.ReaderWorkerManager - Reader Finished with Error
java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
        at java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
        at java.util.concurrent.CompletableFuture.join(Unknown Source)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.handleRequest(SegmentInputStreamImpl.java:137)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.read(SegmentInputStreamImpl.java:122)
        at io.pravega.client.segment.impl.EventSegmentReaderImpl.readEvent(EventSegmentReaderImpl.java:75)
        at io.pravega.client.segment.impl.EventSegmentReaderImpl.read(EventSegmentReaderImpl.java:62)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:121)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:94)
        at io.pravega.longevity.testworker.workers.readers.PravegaReader.start(PravegaReader.java:99)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
        at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$6(Retry.java:245)
        at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.failAllInflight(AsyncSegmentInputStreamImpl.java:265)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.closeConnection(AsyncSegmentInputStreamImpl.java:237)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.access$100(AsyncSegmentInputStreamImpl.java:42)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.connectionDropped(AsyncSegmentInputStreamImpl.java:65)
```

**Comment by RaulGracia** [comment]
@vedanthh note that the `StorageWriter` problem may be related to #3929 for which there is a PR out already #3930 (this may not be the only problem hitting your experiment).

**Comment by andreipaduroiu** [comment]
This is not related #3929. If you observe the stacks are different. This is a normal message indicating that the StorageWriter encountered a `CancellationException` from one of its components that was shutting down. The `DurableLog` (from which the writer reads) shut down due to a problem with BK. It is by design that the entire Container will follow suit in this case.

**Comment by andreipaduroiu** [comment]
If you grep for ` ERROR ` you will see a ton of messages saying that both Tier 1 and Tier 2 have been fenced out. This means some other instance of these containers started somewhere else without waiting for their previous instances to shut down. The exceptions are totally expected on the server-side; it detected that and it shut down in order to protect data. The Segment Store worked as designed here.

**Comment by shrids** [comment]
The reader behavior is as expected, it retries establishing a connection incase of a failure and the number of retries is  based on the Retry configuration. When all the retries have failed it will throw a `RetriesExhaustedException`.

Relevant log snippets:

[1] Reader logs of connection failure (--> indicates the reason for failure)

```
./controller_server_2019-06-19.243.log:2019-06-19 22:43:11,661 474087908 [epollEventLoopGroup-4-3] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : longevity/small/1.#epoch.0
-> this failed due to WRONG_HOST

./controller_server_2019-06-19.243.log:2019-06-19 22:43:11,692 474087939 [epollEventLoopGroup-4-3] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : longevity/small/1.#epoch.0
-> this failed due to WRONG_HOST

./controller_server_2019-06-19.243.log:2019-06-19 22:43:11,710 474087957 [epollEventLoopGroup-4-3] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : longevity/small/1.#epoch.0
-> this failed due to WRONG_HOST

./controller_server_2019-06-19.243.log:2019-06-19 22:43:11,816 474088063 [epollEventLoopGroup-4-3] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : longevity/small/1.#epoch.0
-> this failed due to WRONG_HOST

./controller_server_2019-06-19.243.log:2019-06-19 22:43:12,823 474089070 [epollEventLoopGroup-4-3] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : longevity/small/1.#epoch.0
-> this failed due to WRONG_HOST

./controller_server_2019-06-19.243.log:2019-06-19 22:43:22,832 474099079 [epollEventLoopGroup-4-3] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : longevity/small/1.#epoch.0
->connectionDropped

./controller_server_2019-06-19.243.log:2019-06-19 22:43:52,840 474129087 [epollEventLoopGroup-4-16] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : longevity/small/1.#epoch.0
connectionDropped

./controller_server_2019-06-19.243.log:2019-06-19 22:44:22,848 474159095 [epollEventLoopGroup-4-1] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : longevity/small/1.#epoch.0
->connectionDropped
 
./controller_server_2019-06-19.243.log:2019-06-19 22:44:52,855 474189102 [epollEventLoopGroup-4-4] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : longevity/small/1.#epoch.0
->connectionDropped
```

[2] After all the retries failed the reader throws a `RetriesExhaustedException` which is expected.
```
2019-06-19 22:44:53,107 474189354 [pool-7-thread-2] ERROR i.p.l.t.w.r.ReaderWorkerManager - Reader Finished with Error
java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
	at java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
	at java.util.concurrent.CompletableFuture.join(Unknown Source)
	...
Caused by: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
	at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$6(Retry.java:245)
	at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.failAllInflight(AsyncSegmentInputStreamImpl.java:265)
```
[3] Why did the connection attempt fail ? 
The reader attempts to establish connection between `2019-06-19 22:43:11,661` to `2019-06-19 22:44:52,855` , all the attempts failed since the SegmentContainer has still not started.
e.g: @ `2019-06-19 22:45:01,949 `  the segment container is still in a Starting state.

```
2019-06-19 22:44:01,883 487304309 [epollEventLoopGroup-11-4] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection:
io.pravega.segmentstore.server.IllegalContainerStateException: Container 29 is in an invalid state for this operation. Expected: RUNNING; Actual: STARTING.

2019-06-19 22:45:01,949 487364375 [epollEventLoopGroup-11-2] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection:
io.pravega.segmentstore.server.IllegalContainerStateException: Container 29 is in an invalid state for this operation. Expected: RUNNING; Actual: STARTING.
```

**Comment by sumit-bm** [comment]
@shrids Thanks for the details, the question here is why SegmentContainer has still not started? Note that longevity was running for a few days before reader failure has occurred, so the expectation is, if segment container due to some reason need restart it should come back online and no IO failure should have been observed. Is it something wrong in this case? One more question does there any defined time limit present for segment container restart?

**Comment by shrids** [comment]
The segment container did recover, it recovered `11 seconds` after the last retry by the reader.
The segment container recovery took `107 seconds` and it recovered `439908` items. The recovery time of a segment container depends on the number items to recovered among others.

```
2019-06-19 22:45:03,846 487366272 [core-7] INFO  i.p.s.server.logs.RecoveryProcessor - RecoveryProcessor[29] Recovery completed. Epoch = 5, Items Recovered = 439908, Time = 107012ms.
2019-06-19 22:45:03,846 487366272 [core-7] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[29]: Exit RecoveryMode.
2019-06-19 22:45:03,846 487366272 [core-7] INFO  i.p.s.s.reading.ContainerReadIndex - ReadIndex[29] Exit RecoveryMode.
2019-06-19 22:45:03,846 487366272 [core-7] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[29]: Started.
2019-06-19 22:45:03,846 487366272 [core-7] INFO  i.p.s.server.logs.DurableLog - DurableLog[29]: Started (Online).
2019-06-19 22:45:03,847 487366273 [core-7] INFO  i.p.s.s.c.TableMetadataStore - MetadataStore[29]: Metadata Segment pinned. Name = '_system/containers/metadata_29', Id = '1'
2019-06-19 22:45:03,847 487366273 [core-7] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[29]: Started.
2019-06-19 22:45:03,847 487366273 [core-7] INFO  i.p.c.c.AbstractThreadPoolService - StorageWriter[29]: Started.
2019-06-19 22:45:03,847 487366273 [core-7] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container 29 has been registered.
2019-06-19 22:45:03,847 487366273 [core-7] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[29]: Started.
```

**Comment by RaulGracia** [comment]
Thanks @shrids, this looks as a pretty high number of items to recover. Specially taking into account that the total (data) workload on the system is 150 write events/second, right? 
I have a couple of questions here:
- Would this long recovery time be an indication that we are moving data to Tier 2 in a slow pace? Also, I assume that PR #3928 only helps to get Table Segments ready after a container recovery, so if in this case readers died during the container recovery, it may not help much, right? cc/ @andreipaduroiu 
- Would it be reasonable to increase attempts/timeouts in the reader retry policy to handle these sporadic long recoveries? I understand that recoveries shouldn't take too long, but if in some circumstances this is the case, maybe the retry policy should be modified accordingly.
- @vedanthh Could you please share (via Slack) the Isilon endpoint being used?

**Comment by vedanthh** [comment]
@RaulGracia I have posted Isilon endpoint details in internal channel.

**Comment by shrids** [comment]
Looking at the logs observing we can also observe a `StorageWriter` due to 
`org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /pravega/pravega/segmentstore/containers/9/2/29`
Would this cause a high number of items to recover?

Log File: [log_pod_pravega-pravega-segmentstore-0_previous.zip](https://github.com/pravega/pravega/files/3334075/log_pod_pravega-pravega-segmentstore-0_previous.zip)

*Relavant Log Snippets* :
a. Storage Writer error which is observed for 5+ hours.
```
2019-06-19 17:40:52,184 469114610 [core-30] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[29]: Iteration[3874087].Error.
io.pravega.segmentstore.storage.DataLogWriterNotPrimaryException: Unable to acquire exclusive write lock for log (path = 'pravega/pravega/segmentstore/containers/9/2/29').
Caused by: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /pravega/pravega/segmentstore/containers/9/2/29
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
 ```
upto 
```
2019-06-19 22:42:54,661 487237087 [core-7] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[29]: Iteration[3891355].Error.
io.pravega.segmentstore.storage.DataLogWriterNotPrimaryException: Unable to acquire exclusive write lock for log (path = 'pravega/pravega/segmentstore/containers/9/2/29').	
Caused by: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /pravega/pravega/segmentstore/containers/9/2/29
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
```

b.  Then the segment container is restarted
```
2019-06-19 22:43:10,543 487252969 [core-23] WARN  i.p.s.s.i.bookkeeper.BookKeeperLog - Log[29]: Too many rollover failures; closing.
2019-06-19 22:43:11,741 487254167 [core-13] ERROR i.p.s.s.s.StreamSegmentContainerRegistry - Critical failure for SegmentContainer Container Id = 29, State = FAILED. {}
io.pravega.segmentstore.contracts.StreamingException: OperationProcessor stopped unexpectedly (no error) but DurableLog was not currently stopping.
```
Then recovery happens and the container is restart is complete @ `2019-06-19 22:45:03,847`

**Comment by fpj** [comment]
The behavior described here looks correct. The reader gets an exception after waiting for the recovery of a segment container to complete, and that particular recovery took a while. The exception does not indicate an unrecoverable error, but instead the inability of getting a response within a bounded amount of time. This will happen occasionally in production use and the application needs to be able to deal with it. How to deal with it is application-specific.

It is possible that we need to improve the recovery so that we shorten recovery time, but it does not strike me as a `P0`. It is also possible that recent commits fix this issue.

I'm dropping the priority and moving it to `0.6`.
