### ISSUE TITLE
Cleanup Exception Handling `java.util.concurrent.CancellationException: OperationProcessor is shutting down` from ERROR to INFO

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#3932]
The bug https://github.com/pravega/pravega/issues/3736 is resurfacing in pravega build 0.5.0-2269.6f8a820
Also have tracking issue for this https://github.com/pravega/pravega/pull/3766

Environment details: PKS / K8 with medium cluster:
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```

Deployment details:
```
bookkeeper:0.5.0-2269.6f8a820
pravega:0.5.0-2269.6f8a820
zookeeper:3.5.4-beta-operator
pravega-operator:0.3.2
zookeeper-operator:0.2.1
```

Error in segment store:
```
2019-06-20 09:44:24,051 86517133 [core-17] ERROR i.p.s.s.h.handler.AppendProcessor - Error (Segment = 'longevity/mediumScale/1709.#epoch.1103', Operation = 'append')
java.util.concurrent.CancellationException: OperationProcessor is shutting down.
        at io.pravega.segmentstore.server.logs.OperationProcessor.doStop(OperationProcessor.java:151)
        at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:280)
        at io.pravega.common.concurrent.Services.stopAsync(Services.java:61)
        at io.pravega.segmentstore.server.logs.DurableLog.doStop(DurableLog.java:245)
        at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:280)
        at io.pravega.common.concurrent.Services.stopAsync(Services.java:61)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainer.doStop(StreamSegmentContainer.java:282)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainer.doStop(StreamSegmentContainer.java:264)
        at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:280)
        at io.pravega.common.concurrent.Services.stopAsync(Services.java:61)
        at io.pravega.segmentstore.server.store.StreamSegmentContainerRegistry.stopContainer(StreamSegmentContainerRegistry.java:132)
        at io.pravega.segmentstore.server.host.ZKSegmentContainerMonitor.stopContainer(ZKSegmentContainerMonitor.java:207)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at io.pravega.segmentstore.server.host.ZKSegmentContainerMonitor.checkAssignment(ZKSegmentContainerMonitor.java:184)
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:326)
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:320)
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

PS: complete logs ~170 MB, will share separately in slack.

**Comment by andreipaduroiu** [comment]
I suggest making this a `WARN` and drop the stack trace. Similarly to how we handled `IllegalContainerStateException`.

**Comment by shrids** [comment]
The fix for issue (https://github.com/pravega/pravega/issues/3736) PR: https://github.com/pravega/pravega/pull/3766 has not been merged to 0.5 branch. (ref: https://github.com/pravega/pravega/commits/r0.5)

This is the reason why you are observing this ERROR log. Please verify it once this fix  has been cherrypicked to 0.5 branch.

**Comment by RaulGracia** [comment]
Fixed via https://github.com/pravega/pravega/pull/3766. Please, reopen this issue if the log message still appears.

**Comment by Raghuveera-Rao** [comment]
> #3766

Which build version #3766 is fixed and is it QA testable ?

**Comment by RaulGracia** [comment]
@Raghuveera-Rao The next one to the one you tested, and subsequent ones.
