### ISSUE TITLE
Sporadic failure of EndToEndChannelLeakTest.testDetectChannelLeakMultiReader

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#3935]
**Problem description**
We are seeing some Jenkins builds in which `EndToEndChannelLeakTest.testDetectChannelLeakMultiReader` is failing:
```
org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:64)
	at io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:46)
	at io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest.assertChannelCount(EndToEndChannelLeakTest.java:508)
	at io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest.testDetectChannelLeakMultiReader(EndToEndChannelLeakTest.java:438)
```
[Full log here.](https://github.com/pravega/pravega/files/3311065/failure_log.txt)

**Problem location**
`EndToEndChannelLeakTest.testDetectChannelLeakMultiReader` 

**Suggestions for an improvement**
Fix the test.

**Comment by RaulGracia** [comment]
Haven't seen this test failing in a while. Closing the issue, if the issue appears again we can reopen it.
