### ISSUE TITLE
Observing 'Unexpected throwable caught' and NPE in segment store logs

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#3944]
Environment details: PKS / K8 with medium cluster:
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```

Deployment details:
```
bookkeeper:0.5.0-2269.6f8a820
pravega:0.5.0-2269.6f8a820
zookeeper:3.5.4-beta-operator
pravega-operator:0.3.2
zookeeper-operator:0.2.1
```

Error in segment store:
```
2019-06-21 05:39:13,725 158206807 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR o.a.b.common.util.SafeRunnable - Unexpected throwable caught
java.lang.NullPointerException: null
        at org.apache.bookkeeper.client.PendingAddOp.writeComplete(PendingAddOp.java:252)
        at org.apache.bookkeeper.proto.PerChannelBookieClient$AddCompletion.writeComplete(PerChannelBookieClient.java:1787)
        at org.apache.bookkeeper.proto.PerChannelBookieClient$AddCompletion.lambda$errorOut$0(PerChannelBookieClient.java:1810)
        at org.apache.bookkeeper.proto.PerChannelBookieClient$CompletionValue$1.safeRun(PerChannelBookieClient.java:1414)
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

I/O running is not impacted. 
Have to soft handle the NPE and throwable caught errors.

**Comment by Raghuveera-Rao** [comment]
[segmentstore_2019-06-21.29.log](https://github.com/pravega/pravega/files/3313981/segmentstore_2019-06-21.29.log)

**Comment by andreipaduroiu** [comment]
This is what line 252 looks like in `PendingAddOp.java` inside BookKeeper:

```
247    @Override
248    public void writeComplete(int rc, long ledgerId, long entryId, BookieSocketAddress addr, Object ctx) {
249        int bookieIndex = (Integer) ctx;
250        --pendingWriteRequests;
251
252        if (!lh.metadata.currentEnsemble.get(bookieIndex).equals(addr)) {
```

**Comment by Raghuveera-Rao** [comment]
Seeing this error again in build **0.5.0-2299.8779f22**
```
2019-07-15 04:20:51,714 240095860 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR o.a.b.common.util.SafeRunnable - Unexpected throwable caught
java.lang.NullPointerException: null
        at org.apache.bookkeeper.client.PendingAddOp.writeComplete(PendingAddOp.java:252)
        at org.apache.bookkeeper.proto.PerChannelBookieClient$AddCompletion.writeComplete(PerChannelBookieClient.java:1787)
        at org.apache.bookkeeper.proto.PerChannelBookieClient$AddCompletion.lambda$errorOut$0(PerChannelBookieClient.java:1810)
        at org.apache.bookkeeper.proto.PerChannelBookieClient$CompletionValue$1.safeRun(PerChannelBookieClient.java:1414)
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```
