### ISSUE TITLE
All Segmentstores encountered OOM and can't be restarted

### ISSUE THREAD

**Issue by jingjinglll** [pravega/pravega#3964]
**Problem description**
When running psearch longevity test for a few hours, all the segmentstores encountered oom due to heap space:
```
2019-06-26 02:31:33,114 68421614 [core-6] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [1], Current = [1], PendingTasks = [], ToStart = [], ToStop = [].
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid1.hprof ...
Heap dump file created [1125019134 bytes in 5.186 secs]
Aborting due to java.lang.OutOfMemoryError: Java heap space
```
Then the workload restarted but encounter authentication error:
```
019-06-26 10:03:20,829 1496593 [grpc-default-executor-2] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getEndpointForSegment with trace id 0 failed with server error.
io.grpc.StatusRuntimeException: UNAUTHENTICATED: Authentication failed
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:418)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:663)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:443)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:525)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:446)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:557)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-06-26 10:03:20,830 1496594 [grpc-default-executor-2] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getEndpointForSegment with trace id 0 failed with server error.
io.grpc.StatusRuntimeException: UNAUTHENTICATED: Authentication failed
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:418)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:663)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:443)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:525)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:446)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:557)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-06-26 10:03:25,874 1501638 [core-30] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [], Current = [], PendingTasks = [], ToStart = [], ToStop = [].
``` 

I have 3 segmentstores and 2 controllers, the segmentstores crashed almost at the same time.
I built the latest pravega from master

**Problem location**

**Suggestions for an improvement**

**Comment by RaulGracia** [comment]
@jingjinglll a couple of questions about this issue:
1) Could you please share the Pravega manifest `yml` used in this deployment? We need to know the resources you have provisioned to the different pods.
2) How many Zookeeper instances do you have in this deployment? Have they restarted? Maybe a `kubectl describe pods` can shed some light here.

**Comment by andreipaduroiu** [comment]
Please attach the heap dump for any OOM errors encountered. Stacks and logs aren't very useful in this case.

**Comment by jingjinglll** [comment]
The environment is already deleted. But I found I was still using version 0.4.0, is it fixed in recent build?

**Comment by RaulGracia** [comment]
@jingjinglll we need the manifest and logs to know if this was a provisioning problem or an actual Pravega issue.

**Comment by jingjinglll** [comment]
I will try to reproduce it and provide more info. 
But the threaddump will be lost after container restarted, is there a way to persist it?

**Comment by andreipaduroiu** [comment]
I believe @sumit-bm was able to fetch them last time for us. He said it wasn't quite straightforward. Would you mind asking him how he pulled that out?

**Comment by sumit-bm** [comment]
@andreipaduroiu @jingjinglll I have posted a generic procedure to Liu in the internal channel to collect heap dump

**Comment by jingjinglll** [comment]
@andreipaduroiu You can get the threaddump from one drive.https://dell-my.sharepoint.com/:f:/g/personal/julius_zhu_emc_com/Eopu1-DIgH1Pke84qPXRRNABlV7vnZ5APHWQNNv8MpCL9g?e=WKL8df

**Comment by andreipaduroiu** [comment]
How are you provisioning the cluster? I see the heap dump has about 1GB of data and it looks like it was in the middle of a recovery and was unable to allocate more heap space while doing so.

**Comment by jingjinglll** [comment]
Attached the yaml file for your reference.

```kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pravega-tier2
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 160Gi
---
apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "pravega"
spec:
  zookeeperUri: zk-client:2181

  bookkeeper:
    image:
      repository: jirnsr/bookkeeper
      tag: 0.4.0
      pullPolicy: Always

    replicas: 3

    storage:
      ledgerVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 40Gi

      journalVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 40Gi

    autoRecovery: true

  pravega:
    controllerReplicas: 1
    segmentStoreReplicas: 3
    options:
      metrics.enableStatistics: "true"
      metrics.statsdHost: "telegraph.default"
      metrics.statsdPort: "8125"

    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 40Gi

    image:
      repository: jirnsr/pravega
      tag: 0.4.0
      pullPolicy: Always

    tier2:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2
```

**Comment by RaulGracia** [comment]
@jingjinglll there are least 3 points that may lead to problems with your provisioning:
1) You are not defining the pod resources to be provisioned, so Pravega is using the default ones which are modest.
2) You are also not configuring neither the Segment Store nor the Controller (under the `options` section), so things like the Segment Store cache will use very low defaults.
3) Also, you are using the `zookeeper-client:2181` endpoint in `zookeeperUri`, which is theoretically correct. But we have observed sporadic connectivity problems in PKS using this load balancer service endpoint, which can be mitigated by using the `zookeeper-headless` name of individual Zookeeper servers.
4) I have also realized that you are using a very old version of Pravega. If this is not a hard constraint, I suggest you to try the latest `0.5` version.

I attach a manifest sample that you can try to reproduce if you still see this problem:
```
apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "pravega"
spec:
  zookeeperUri: zookeeper-0.zookeeper-headless.default.svc.cluster.local:2181,zookeeper-1.zookeeper-headless.default.svc.cluster.local:2181,zookeeper-2.zookeeper-headless.default.svc.cluster.local:2181,zookeeper-3.zookeeper-headless.default.svc.cluster.local:2181,zookeeper-4.zookeeper-headless.default.svc.cluster.local:2181

  bookkeeper:
    image:
      repository: devops-repo.isus.emc.com:8116/nautilus/bookkeeper
      tag: 0.5.0-2284.8c6c176
      pullPolicy: Always

    replicas: 3
    resources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"

    storage:
      ledgerVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 100Gi

      journalVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 100Gi

      indexVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi 

    autoRecovery: true
    options:
      useHostNameAsBookieID: "true"

  pravega:
    controllerReplicas: 1
    controllerResources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "3Gi"
        cpu: "2000m"

    segmentStoreReplicas: 1
    segmentStoreResources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "6Gi"
        cpu: "4000m"

    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 30Gi

    image:
      repository: devops-repo.isus.emc.com:8116/nautilus/pravega
      tag: 0.5.0-2284.8c6c176
      pullPolicy: Always

    options:
      bookkeeper.bkWriteQuorumSize: "3"
      bookkeeper.bkAckQuorumSize: "2"
      pravegaservice.cacheMaxSize: "21474836480"
      pravegaservice.writeBufferSizeMB: "512"
      pravegaservice.readCacheSizeMB: "2048"
      hdfs.blockSize: "67108864"
      pravegaservice.containerCount: "32"
      controller.containerCount: "32"
      controller.retention.bucketCount: "10"
      controller.service.asyncTaskPoolSize: "20"
      controller.retention.threadCount: "4"

    tier2:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2
```

In this manifest, you will need to add your metrics-related options, and modify the `zookeeperUri` based on the size of your Zookeeper cluster.
