### ISSUE TITLE
Readers failed with "ERROR i.p.l.t.w.readers.PravegaReader - Reader finished with Error"

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega#3965]
**Problem description**

On running **4 parallel Pravega streams** having IO workload of **8 workers** ( 8 readers and 4 writers ), max event rate: 4000 events/sec, target rate: 2000, scale factor: 2, scaling: based on "Events per second" for each stream and **3 hours runtime, observed reader failure ( 0/8 readers** running ) for all 4 streams together with **`ERROR i.p.l.t.w.readers.PravegaReader - Reader finished with Error`** and **`io.pravega.client.stream.TruncatedDataException: null` exception**. 

Observations upon the failure: -

**1)** **Reader failure ( 0/8 ) for all the 4 streams running parallelly**: -
```
INFO  [2019-06-26 12:24:48,609] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 3h 1m
INFO  [2019-06-26 12:24:48,609] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:44,605,532, events/sec:4,107, KB/sec:3149.0674
INFO  [2019-06-26 12:24:48,609] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-06-26 12:24:48,609] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 3,080, average block time (ms): 18
INFO  [2019-06-26 12:24:48,609] io.pravega.longevity.utils.PerformanceUtils: Readers (0/8): events:29,732,852, events/sec:2,737, KB/sec:2099.079
```
```
INFO  [2019-06-26 12:25:12,359] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 3h 1m
INFO  [2019-06-26 12:25:12,359] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:47,625,907, events/sec:4,373, KB/sec:3353.0273
INFO  [2019-06-26 12:25:12,359] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-06-26 12:25:12,359] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 16,815, average block time (ms): 13
INFO  [2019-06-26 12:25:12,359] io.pravega.longevity.utils.PerformanceUtils: Readers (0/8): events:71,775,891, events/sec:6,590, KB/sec:5053.2803
```
```
INFO  [2019-06-26 12:25:20,490] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 3h 1m
INFO  [2019-06-26 12:25:20,490] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:45,556,025, events/sec:4,183, KB/sec:3207.3213
INFO  [2019-06-26 12:25:20,490] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-06-26 12:25:20,490] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 2,317, average block time (ms): 22
INFO  [2019-06-26 12:25:20,490] io.pravega.longevity.utils.PerformanceUtils: Readers (0/8): events:26,294,863, events/sec:2,414, KB/sec:1851.2529
```
```
INFO  [2019-06-26 12:25:15,634] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 3h 1m
INFO  [2019-06-26 12:25:15,634] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:45,671,230, events/sec:4,193, KB/sec:3215.4219
INFO  [2019-06-26 12:25:15,634] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-06-26 12:25:15,634] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 1,539, average block time (ms): 21
INFO  [2019-06-26 12:25:15,634] io.pravega.longevity.utils.PerformanceUtils: Readers (0/8): events:48,283,270, events/sec:4,433, KB/sec:3399.33
```
**2)** The error observed commonly for all the 4 worker pods: -
```
2019-06-26 12:24:26,318 10852076 [pool-7-thread-3] ERROR i.p.l.t.w.readers.PravegaReader - Reader finished with Error
io.pravega.client.stream.TruncatedDataException: null
        at io.pravega.client.stream.impl.EventStreamReaderImpl.handleSegmentTruncated(EventStreamReaderImpl.java:281)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:127)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:94)
        at io.pravega.longevity.testworker.workers.readers.PravegaReader.start(PravegaReader.java:99)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```
**3)** One of the controller shows **`ScaleOperationTask `** failed tasks messages before the reader failure being observed and **`ConcurrentEventProcessor`**  error

```
2019-06-26 12:01:13,952 10228705 [controllerpool-5] WARN  i.p.c.s.stream.PersistentStreamBase - scale precondition failed [193273528395]
2019-06-26 12:01:13,953 10228706 [controllerpool-5] WARN  i.p.c.s.e.r.ScaleOperationTask - [requestId=7435269961392781634] processing scale request for longevity/midScale segments [193273528395] failed {}
io.pravega.controller.store.stream.EpochTransitionOperationExceptions$PreConditionFailureException: null
        at io.pravega.controller.store.stream.PersistentStreamBase.lambda$null$91(PersistentStreamBase.java:706)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-06-26 12:01:13,956 10228709 [controllerpool-13] WARN  i.p.c.e.i.ConcurrentEventProcessor - ConcurrentEventProcessor Processing failed java.util.concurrent.CompletionException
2019-06-26 12:01:13,957 10228710 [controllerpool-13] ERROR i.p.c.e.i.ConcurrentEventProcessor - ConcurrentEventProcessor Processing failed, exiting {}
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.EpochTransitionOperationExceptions$PreConditionFailureException
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
        at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
        at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:899)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.pravega.controller.server.eventProcessor.requesthandlers.ScaleOperationTask.lambda$execute$0(ScaleOperationTask.java:73)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.controller.store.stream.EpochTransitionOperationExceptions$PreConditionFailureException: null
        at io.pravega.controller.store.stream.PersistentStreamBase.lambda$null$91(PersistentStreamBase.java:706)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580)
        ... 8 common frames omitted
```

Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.
Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Pravega version : 0.5.0-2284.8c6c176
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```

**Comment by SomeshJoshi19** [comment]
Sharing logs for the issue on internal channel due to size limit

**Comment by SomeshJoshi19** [comment]
4) One of the worker pods gives `SegmentTruncatedException` at the time of reader failure

```
2019-06-26 12:24:25,174 10849648 [epollEventLoopGroup-4-3] DEBUG i.p.client.netty.impl.FlowHandler - 172.24.24.10 processing reply 
No such segment: longevity/midScale/72.#epoch.42 with flow Flow(flowId=384, requestSequenceNumber=0)
2019-06-26 12:24:25,174 10849648 [epollEventLoopGroup-4-3] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Received noSuchSegment No such segment: longevity/midScale/72.#epoch.42
2019-06-26 12:24:25,174 10849648 [epollEventLoopGroup-4-3] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : longevity/midScale/72.#epoch.42
io.pravega.client.segment.impl.SegmentTruncatedException: Segment no longer exists.
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.noSuchSegment(AsyncSegmentInputStreamImpl.java:78)
        at io.pravega.shared.protocol.netty.WireCommands$NoSuchSegment.process(WireCommands.java:279)
        at io.pravega.shared.protocol.netty.ReplyProcessor.process(ReplyProcessor.java:20)
        at io.pravega.client.netty.impl.FlowHandler.lambda$channelRead$2(FlowHandler.java:209)
        at java.util.Optional.ifPresent(Unknown Source)
        at io.pravega.client.netty.impl.FlowHandler.channelRead(FlowHandler.java:207)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
```
5)  Segmentstore-0 gives warning messages  to perform `readSegment` and `getStreamSegmentInfo` at the time of reader failure

```
2019-06-26 12:24:22,186 11571094 [epollEventLoopGroup-11-1] WARN  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=1490353651712] Segment 'longevity/midScale/72.#epoch.42' does not exist and cannot perform operation 'readSegment'.
2019-06-26 12:24:22,207 11571115 [epollEventLoopGroup-11-2] WARN  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=1666447310849] Segment 'longevity/midScale/72.#epoch.42' does not exist and cannot perform operation 'getStreamSegmentInfo'.
```

**Comment by andreipaduroiu** [comment]
@shrids @shiveshr This doesn't smell like it's coming from the segment store. The exception stacks posted here indicate they're coming from the client and/or controller.

**Comment by shrids** [comment]
After going through the logs I do not see any issue with Pravega here; please find the reasons for this conclusion below.

a. The test creates a stream called `longevity/midScale` with retention policy of an hour.
```
INFO  [2019-06-26 09:23:36,767] io.pravega.client.admin.impl.StreamManagerImpl: Creating scope/stream: 
longevity/midScale with configuration: StreamConfiguration(scalingPolicy=ScalingPolicy(scaleType=BY_RATE_IN_EVENTS_PER_SEC, targetRate=2000, scaleFactor=2, minNumSegments=8), 
retentionPolicy=RetentionPolicy(retentionType=TIME, retentionParam=3600000))
```

b. The logs indicates that there are 4 midScale workers ( your description indicates 8 workers), where each worker has 8 Readers and 4 writers.
This implies 16 event writers are writing events to the same stream and all the readers are attempting to read events written by all the writers...

c. Also, 
`EventStreamReader.readNextEvent()` will throw a `TruncatedDataException` if the data to be read next has been truncated away and no longer be read. If following this a `readNextEvent()` is again invoked the reader will resume from the next available event. In this case the truncation is due to the Retention policy of the stream.

**Comment by SomeshJoshi19** [comment]
@shrids

1) On discussion to conclusion point "a.", if there is no issue in Pravega then why did the readers failed ( 0/8 ) and could not recover from the failure then after along with generating huge amount of error logs in worker pods of longevity run.

2) On discussion to conclusion point "b.", are 16 (or 32) event writers not a stable run over same stream and testing beyond this limit will definitely produce problems ?

3) i. On discussion to conclusion point "c.", if readNextEvent()throws TruncatedDataException in failed attempts to access data for reading event operation then it is not a problem.

ii. And even if we consider that readNextEvent() will resume from the next available event then, how long that wait may continue before loosing the actual event because I kept the cluster ideal for more than 24 hours of observing this issue and until now the readers doesn't seems to get recovered from failed state ( 0/8).

iii. If retention policy of the stream is reason for getting this problem then it would be very helpful if you could give suggestions on how can it be corrected .

**Comment by shrids** [comment]
Ensuring that the readers attempt reading from the stream (`readNextEvent()`) after receiving `TruncatedDataException` should resolve the issue.
