### ISSUE TITLE
Observing Critical failure for Segment Container on Object "DataFrameBuilder" closure in Pravega Segment Store

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega#3978]
**Problem description**

After running for **16 hours, 4 parallel Pravega streams** having IO workload of **8 workers** ( 8 readers and 4 writers ), max event rate: 4000 events/sec, target rate: 2000, scale factor: 2, scaling: based on "Events per second" for each stream, observed **Critical failure for Segment Container** on object **`DataFrameBuilder`** closure in segment store causing **writers to stop event population**  and **complete reader failure ( 0/8 )**.

Observations for the following: -

1)  **Segment store points to Critical failure of Segment Container on Object `DataFrameBuilder` closure** for SegmentContainer [22]

```
2019-06-28 02:51:48,213 69301799 [core-16] INFO  i.p.s.s.s.StreamSegmentContainerRegistry - Unregistered SegmentContainer 22.
2019-06-28 02:51:48,213 69301799 [core-16] ERROR i.p.s.s.s.StreamSegmentContainerRegistry - 
Critical failure for SegmentContainer Container Id = 22, State = FAILED. {}
io.pravega.common.ObjectClosedException: Object 'DataFrameBuilder' has been closed and cannot be accessed anymore.
        at io.pravega.common.Exceptions.checkNotClosed(Exceptions.java:255)
        at io.pravega.segmentstore.server.logs.DataFrameBuilder.append(DataFrameBuilder.java:130)
        at io.pravega.segmentstore.server.logs.OperationProcessor.processOperation(OperationProcessor.java:362)
        at io.pravega.segmentstore.server.logs.OperationProcessor.processOperations(OperationProcessor.java:282)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

 2) **Writing operation stopped for all the 4 streams, i.e., no event population taking place in their respective streams** and not able to come over from the failure.

```
172.24.186.6 - - [28/Jun/2019:02:51:13 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 2701 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 2
INFO  [2019-06-28 02:51:39,514] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 16h 21m
INFO  [2019-06-28 02:51:39,514] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:341,363,106, events/sec:5,796, KB/sec:4444.2344
INFO  [2019-06-28 02:51:39,514] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-06-28 02:51:39,514] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 139, average block time (ms): 36
INFO  [2019-06-28 02:51:39,514] io.pravega.longevity.utils.PerformanceUtils: Readers (8/8): events:332,981,978, events/sec:5,654, KB/sec:4335.119
INFO  [2019-06-28 02:51:39,514] io.pravega.longevity.utils.PerformanceUtils: New runtime for 896739b7-6955-4216-b657-b2d742a72749  Running for 16h 21m
INFO  [2019-06-28 02:51:39,514] io.pravega.longevity.utils.PerformanceUtils: Dumping stats for stream longevity/midScale
INFO  [2019-06-28 02:51:39,514] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:341,363,106, events/sec:5,799, KB/sec:4446.499
INFO  [2019-06-28 02:51:39,514] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
```

```
172.24.186.5 - - [28/Jun/2019:02:51:41 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 2701 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 2
INFO  [2019-06-28 02:51:41,844] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 16h 21m
INFO  [2019-06-28 02:51:41,844] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:320,379,199, events/sec:5,440, KB/sec:4171.043
INFO  [2019-06-28 02:51:41,844] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-06-28 02:51:41,844] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 147, average block time (ms): 45
INFO  [2019-06-28 02:51:41,844] io.pravega.longevity.utils.PerformanceUtils: Readers (8/8): events:364,502,422, events/sec:6,189, KB/sec:4745.4863
INFO  [2019-06-28 02:51:41,844] io.pravega.longevity.utils.PerformanceUtils: New runtime for 896739b7-6955-4216-b657-b2d742a72749  Running for 16h 21m
INFO  [2019-06-28 02:51:41,844] io.pravega.longevity.utils.PerformanceUtils: Dumping stats for stream longevity/midScale
INFO  [2019-06-28 02:51:41,844] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:320,379,199, events/sec:5,443, KB/sec:4173.169
INFO  [2019-06-28 02:51:41,844] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
```

```
172.24.186.3 - - [28/Jun/2019:02:51:41 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 2704 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 1
INFO  [2019-06-28 02:51:43,515] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 16h 21m
INFO  [2019-06-28 02:51:43,516] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:311,618,775, events/sec:5,291, KB/sec:4056.9873
INFO  [2019-06-28 02:51:43,516] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-06-28 02:51:43,516] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 43, average block time (ms): 96
INFO  [2019-06-28 02:51:43,516] io.pravega.longevity.utils.PerformanceUtils: Readers (8/8): events:254,183,051, events/sec:4,316, KB/sec:3309.2314
INFO  [2019-06-28 02:51:43,516] io.pravega.longevity.utils.PerformanceUtils: New runtime for 896739b7-6955-4216-b657-b2d742a72749  Running for 16h 21m
INFO  [2019-06-28 02:51:43,516] io.pravega.longevity.utils.PerformanceUtils: Dumping stats for stream longevity/midScale
INFO  [2019-06-28 02:51:43,516] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:311,618,775, events/sec:5,294, KB/sec:4059.0557
INFO  [2019-06-28 02:51:43,516] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
```
 
```
172.24.186.4 - - [28/Jun/2019:02:52:09 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 2705 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 1
INFO  [2019-06-28 02:52:11,552] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 16h 22m
INFO  [2019-06-28 02:52:11,552] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:321,388,447, events/sec:5,454, KB/sec:4182.0566
INFO  [2019-06-28 02:52:11,552] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-06-28 02:52:11,552] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 51, average block time (ms): 83
INFO  [2019-06-28 02:52:11,552] io.pravega.longevity.utils.PerformanceUtils: Readers (8/8): events:343,082,074, events/sec:5,822, KB/sec:4464.341
INFO  [2019-06-28 02:52:11,552] io.pravega.longevity.utils.PerformanceUtils: New runtime for 896739b7-6955-4216-b657-b2d742a72749  Running for 16h 22m
INFO  [2019-06-28 02:52:11,552] io.pravega.longevity.utils.PerformanceUtils: Dumping stats for stream longevity/midScale
INFO  [2019-06-28 02:52:11,552] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:321,388,447, events/sec:5,454, KB/sec:4182.0566
INFO  [2019-06-28 02:52:11,552] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
```

3) **Readers failed ( 0/8 ) soon after write operation stopped for all the 4 streams together**

```
172.24.186.6 - - [28/Jun/2019:03:07:06 +0000] "POST /v1/longevity/error HTTP/1.1" 200 2426 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 0
INFO  [2019-06-28 03:07:09,518] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 16h 37m
INFO  [2019-06-28 03:07:09,518] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:341,363,106, events/sec:5,706, KB/sec:4375.1416
INFO  [2019-06-28 03:07:09,518] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-06-28 03:07:09,518] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 139, average block time (ms): 36
INFO  [2019-06-28 03:07:09,518] io.pravega.longevity.utils.PerformanceUtils: Readers (0/8): events:332,981,978, events/sec:5,566, KB/sec:4267.7227
```

Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.
Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Pravega version : 0.5.0-2284.8c6c176
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```

**Comment by SomeshJoshi19** [comment]
4) **Not able to create any Pravega stream/scope to read or write data after the failure being observed** from pravega client tools like benchmark and pravega-samples

```
main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.100.200.208:9090
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.100.200.208:9090
[main] INFO io.pravega.client.admin.impl.StreamManagerImpl - Creating scope: Scope
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=-3758330425547581338] Tagging client request (createScope-Scope).
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[[/10.100.200.208:9090]/{}]]
[grpc-default-executor-1] WARN io.pravega.client.stream.impl.ControllerImpl - [requestId=-3758330425547581338] Failed to create scope: Scope
[grpc-default-executor-1] WARN io.pravega.client.stream.impl.ControllerImpl - [requestId=-3758330425547581338] createScope failed:
java.util.concurrent.CompletionException: io.pravega.client.stream.impl.ControllerFailureException: Failed to create scope: Scope
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at io.pravega.client.stream.impl.ControllerImpl$RPCAsyncCallback.onCompleted(ControllerImpl.java:1028)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:432)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.client.stream.impl.ControllerFailureException: Failed to create scope: Scope
        at io.pravega.client.stream.impl.ControllerImpl.lambda$createScope$1(ControllerImpl.java:208)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        ... 30 more
```
```
root@pravega-benchmark-new1:/pravega-client-examples# ./bin/helloWorldWriter -u tcp://10.100.200.208:9090
Exception in thread "main" io.pravega.client.stream.impl.ControllerFailureException: Failed to create scope: examples
        at io.pravega.client.stream.impl.ControllerImpl.lambda$createScope$1(ControllerImpl.java:208)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at io.pravega.client.stream.impl.ControllerImpl$RPCAsyncCallback.onCompleted(ControllerImpl.java:1028)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:432)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by SomeshJoshi19** [comment]
Sharing logs on internal channel due to size limit

**Comment by SomeshJoshi19** [comment]
While debugging found bookie ledgers got exhausted and I'll be updating after retesting the workload for higher resource values to bookie

**Comment by fpj** [comment]
Thanks for reporting this issue, @SomeshJoshi19 . Please do post more info once you have it.

**Comment by andreipaduroiu** [comment]
That means the Segment Container is shutting down. What else is going on here?

**Comment by andreipaduroiu** [comment]
That error means the Segment Container is shutting down. Have you searched **just above** that stack trace to see what else is causing it? It could be the Container is normally shutting down or, as you said, it could be because BK ran out of resources and we couldn't write to it anymore.

**Comment by andreipaduroiu** [comment]
The logs indicate that BK wasn't available and recovery couldn't complete. This is not a Segment Store issue.

**Comment by vedanthh** [comment]
Observing same issue (Critical failure for Segment Container on object **DataFrameBuilder**) while running different workloads.

**Note: In this case 3 readers failed out of 4 after ~ 4 days 10 hours and IO read/write events are increasing with 1 reader and 3 writers**

```
2019-06-28 19:00:33,165 398204628 [core-26] ERROR i.p.s.s.s.StreamSegmentContainerRegistry - Critical failure for SegmentContainer Container Id = 13, State = FAILED. {}
io.pravega.common.ObjectClosedException: Object 'DataFrameBuilder' has been closed and cannot be accessed anymore.
        at io.pravega.common.Exceptions.checkNotClosed(Exceptions.java:255)
        at io.pravega.segmentstore.server.logs.DataFrameBuilder.append(DataFrameBuilder.java:130)
        at io.pravega.segmentstore.server.logs.OperationProcessor.processOperation(OperationProcessor.java:362)
        at io.pravega.segmentstore.server.logs.OperationProcessor.processOperations(OperationProcessor.java:282)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
```
INFO  [2019-07-01 07:07:39,558] io.pravega.longevity.utils.PerformanceUtils: New runtime for 7e28cdd1-aad1-42b9-b876-16a74a74a22e  Running for 7d 2h
INFO  [2019-07-01 07:07:39,558] io.pravega.longevity.utils.PerformanceUtils: Dumping stats for stream longevity/smallScaleBytes
INFO  [2019-07-01 07:07:39,558] io.pravega.longevity.utils.PerformanceUtils: Writers (3/3): events:24,245,653, events/sec:39, KB/sec:30.296875
INFO  [2019-07-01 07:07:39,558] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-07-01 07:07:39,558] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-07-01 07:07:39,558] io.pravega.longevity.utils.PerformanceUtils: Readers (1/4): events:25,640,832, events/sec:41, KB/sec:32.04004
172.24.161.2 - - [01/Jul/2019:07:07:39 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 2119 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 1
```
```
INFO  [2019-07-01 07:08:09,560] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 7d 2h
INFO  [2019-07-01 07:08:09,560] io.pravega.longevity.utils.PerformanceUtils: Writers (3/3): events:24,246,782, events/sec:39, KB/sec:30.294922
INFO  [2019-07-01 07:08:09,560] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-07-01 07:08:09,560] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-07-01 07:08:09,560] io.pravega.longevity.utils.PerformanceUtils: Readers (1/4): events:25,641,927, events/sec:41, KB/sec:32.038086
```

**Comment by sumit-bm** [comment]
@vedanthh could you post the logs to @andreipaduroiu

**Comment by vedanthh** [comment]
@sumit-bm I have shared the logs in internal channel.

**Comment by andreipaduroiu** [comment]
Thanks @vedanthh for the logs. The interesting parts of the log that give a hint to the root cause for this are summarized in the following snippets:

```
2019-06-28 18:37:34,453 396825916 [core-13] INFO  i.p.s.server.logs.DurableLog - DurableLog[7]: Truncate (OperationSequenceNumber = 5058229, DataFrameAddress = Sequence = 373662188115, LedgerId = 181471, EntryId = 33363).
2019-06-28 18:37:34,670 396826133 [core-26] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[7]: Iteration[3723676].Error.
io.pravega.segmentstore.storage.DataLogWriterNotPrimaryException: Unable to acquire exclusive write lock for log (path = 'pravega/pravega/segmentstore/containers/7/0/7').
	at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.persistMetadata(BookKeeperLog.java:802)
	at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.tryTruncate(BookKeeperLog.java:675)
	at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.lambda$truncate$4(BookKeeperLog.java:323)
Caused by: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /pravega/pravega/segmentstore/containers/7/0/7
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.setData(ZooKeeper.java:2272)
	at org.apache.curator.framework.imps.SetDataBuilderImpl$4.call(SetDataBuilderImpl.java:291)
	at org.apache.curator.framework.imps.SetDataBuilderImpl$4.call(SetDataBuilderImpl.java:287)
	at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)
	at org.apache.curator.framework.imps.SetDataBuilderImpl.pathInForeground(SetDataBuilderImpl.java:284)
	at org.apache.curator.framework.imps.SetDataBuilderImpl.forPath(SetDataBuilderImpl.java:270)
	at org.apache.curator.framework.imps.SetDataBuilderImpl.forPath(SetDataBuilderImpl.java:33)
	at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.persistMetadata(BookKeeperLog.java:794)
	... 10 common frames omitted
```

AND

```
2019-06-28 18:37:53,672 396845135 [core-21] WARN  i.p.s.s.i.bookkeeper.BookKeeperLog - Log[7]: Too many rollover failures; closing.
java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.segmentstore.storage.DataLogWriterNotPrimaryException: Unable to acquire exclusive write lock for log (path = 'pravega/pravega/segmentstore/containers/7/0/7').
```

I may have found a reason for this, but I'll need to confirm.
