### ISSUE TITLE
Docker Swarm: Scaled up Segment store doesn't get any container assignment

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#3981]
**I scaled up segment store for published IP, single node installation using script `scale_segmentstore`. Scale up is done successfully but container reassignment is not done properly while IO was running in backend.**

After scale up, IO didn't get affected but following `WARN` was seen inside scaled up SSS:
```
2019-07-01 08:45:03,511 710915 [core-29] WARN  i.p.s.s.h.ZKSegmentContainerMonitor - Failed to monitor the segmentcontainer assignment:
org.apache.commons.lang.SerializationException: java.io.StreamCorruptedException: invalid stream header: 00000100
        at org.apache.commons.lang.SerializationUtils.deserialize(SerializationUtils.java:168)
        at org.apache.commons.lang.SerializationUtils.deserialize(SerializationUtils.java:193)
        at io.pravega.segmentstore.server.host.ZKSegmentContainerMonitor.getDesiredContainerList(ZKSegmentContainerMonitor.java:279)
        at io.pravega.segmentstore.server.host.ZKSegmentContainerMonitor.checkAssignment(ZKSegmentContainerMonitor.java:165)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.StreamCorruptedException: invalid stream header: 00000100
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:866)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
        at org.apache.commons.lang.SerializationUtils.deserialize(SerializationUtils.java:162)
        ... 10 common frames omitted
```
Meanwhile Controller was throwing:
```
2019-07-01 08:33:13,475 288678 [Curator-PathChildrenCache-0] ERROR o.a.c.f.r.cache.PathChildrenCache -
io.pravega.common.io.SerializationException: Unsupported format version 172.
        at io.pravega.common.io.serialization.VersionedSerializer.ensureCondition(VersionedSerializer.java:162)
        at io.pravega.common.io.serialization.VersionedSerializer.processHeader(VersionedSerializer.java:154)
        at io.pravega.common.io.serialization.VersionedSerializer$SingleType.deserialize(VersionedSerializer.java:371)
        at io.pravega.common.io.serialization.VersionedSerializer$WithBuilder.deserialize(VersionedSerializer.java:539)
        at io.pravega.common.io.serialization.VersionedSerializer$WithBuilder.deserialize(VersionedSerializer.java:551)
        at io.pravega.common.cluster.Host.fromBytes(Host.java:53)
        at io.pravega.common.cluster.zkImpl.ClusterZKImpl.lambda$pathChildrenCacheListener$1(ClusterZKImpl.java:190)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:535)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:529)
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)
        at org.apache.curator.shaded.com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache.callListeners(PathChildrenCache.java:527)
        at org.apache.curator.framework.recipes.cache.EventOperation.invoke(EventOperation.java:35)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$9.run(PathChildrenCache.java:786)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
Also, first SSS logs show that all 4 containers are still with first SSS:

```
2019-07-01 08:45:46,063 1041095 [core-22] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 1, 2, 3], Current = [0, 1, 2, 3], PendingTasks = [], ToStart = [], ToStop = [].
```
Following is the installation details:
```
[root@nautilus-master-3 swarm]# d service ls
ID            NAME                    MODE        REPLICAS  IMAGE
0001hgipf06s  pravega_segmentstore_2  replicated  1/1       pravega/pravega:latest
5pvxab8jygji  pravega_controller      replicated  1/1       devops-repo.isus.emc.com:8116/nautilus/pravega:0.5.0-2284.8c6c176
bez0i20ikxre  pravega_segmentstore    replicated  1/1       devops-repo.isus.emc.com:8116/nautilus/pravega:0.5.0-2284.8c6c176
pwgybs26ratz  pravega_bookkeeper      replicated  4/4       devops-repo.isus.emc.com:8116/nautilus/bookkeeper:0.5.0-2284.8c6c176
r7h0vsfxz5fz  pravega_hdfs            replicated  1/1       pravega/hdfs:2.7.7
w9sjhhmqr9xl  pravega_zookeeper       replicated  1/1       zookeeper:3.5.4-beta
```
P.S: I've used latest `scale_segmentstore` script for scaling up SSS.

Attaching logs for reference.
[sss_scale_2284_dockerswarm.zip](https://github.com/pravega/pravega/files/3344675/sss_scale_2284_dockerswarm.zip)

**Comment by shrids** [comment]
This is not an issue since different versions of the image are being used.

`pravega_segmentstore_2 `  service instance is using an image which is 5 month old
while `pravega_segmentstore` service instance is using `pravega:0.5.0-2284.8c6c176`.
```
[root@nautilus-master-3 swarm]# d service ls
ID            NAME                    MODE        REPLICAS  IMAGE
0001hgipf06s  pravega_segmentstore_2  replicated  1/1       pravega/pravega:latest
bez0i20ikxre  pravega_segmentstore    replicated  1/1       devops-repo.isus.emc.com:8116/nautilus/pravega:0.5.0-2284.8c6c176
```

**Comment by shrids** [comment]
Both the `pravega.yml` and `scale_segmentstore` are configured to use the latest pravega/pravega from docker hub. 
If you have modified `pravega.yml` to use a custom version of Pravega then you need to modify the `scale_segmentstore` script accordingly with the new image .
Please try it by modifying the `scale_segmentstore` script. and reopen in case of issues.
