### ISSUE TITLE
Seeing Storage Writer Iteration Error in segment store logs

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#3998]
Deployment details:
```
bookkeeper:0.5.0-2291.3ccff63
pravega:0.5.0-2291.3ccff63
pravega/pravega-operator:0.3.2
pravega/zookeeper:0.2.2
pravega/zookeeper-operator:latest
```

Environment details: PKS / K8 with medium cluster:
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
5 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend 
```

segment store log error snippet:
```
2019-07-03 07:49:06,180 91970 [storage-io-179] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[24-21]: State changed from NotInitialized to Writing.
2019-07-03 07:49:06,182 91972 [core-22] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[24]: Iteration[331].Error.
io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment '_system/_tables/myScope20190703T034215.552/myStream/transactionsInEpoch-0.#.bbe3f119-4f34-4a8f-94f3-7ea4cb03fa3b'] The StreamSegment does not exist.
        at io.pravega.segmentstore.server.containers.MetadataStore.getOrAssignSegmentId(MetadataStore.java:342)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainer.forSegment(StreamSegmentContainer.java:544)
        at io.pravega.segmentstore.server.tables.ContainerTableExtensionImpl$TableWriterConnectorImpl.getSegment(ContainerTableExtensionImpl.java:392)
        at io.pravega.segmentstore.server.tables.WriterTableProcessor.flush(WriterTableProcessor.java:165)
        at io.pravega.segmentstore.server.writer.StorageWriter$ProcessorCollection.lambda$flush$0(StorageWriter.java:619)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at io.pravega.segmentstore.server.writer.StorageWriter$ProcessorCollection.flush(StorageWriter.java:619)
        at io.pravega.segmentstore.server.writer.StorageWriter.lambda$flush$8(StorageWriter.java:301)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1625)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
```

**Comment by Raghuveera-Rao** [comment]
[pravega-k8s-logging-2019-07-03-05-26-41.zip](https://github.com/pravega/pravega/files/3354300/pravega-k8s-logging-2019-07-03-05-26-41.zip)
pls find k8s complete log

**Comment by andreipaduroiu** [comment]
This is normal behavior.
