### ISSUE TITLE
The DeleteStream should delete the closed readergroups also

### ISSUE THREAD

**Issue by kmgowda** [pravega/pravega#4035]
**Problem description**
Currently deleting the stream is not deleting the any of the existing CLOSED readers groups for the stream. Because of this , createReaderGroup API returns existing readergroup.
But, this readergroup when the read is performed, the  "Nosuch segment " error is observed

**Problem location**
Controller/Client

**Suggestions for an improvement**
whenever the stream is deleted, then all closed reader groups should be deleted.
this make the user application to use the same readergroup name for the recreated stream.

Full error when the reader group tries to read the stream which is recreated is as follows:
[epollEventLoopGroup-5-6] INFO io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl - Received noSuchSegment No such segment: Scope/topic-t1-111/0.#epoch.0
[epollEventLoopGroup-5-6] WARN io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl - Exception while reading from Segment : Scope/topic-t1-111/0.#epoch.0
io.pravega.client.segment.impl.SegmentTruncatedException: Segment no longer exists.
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.noSuchSegment(AsyncSegmentInputStreamImpl.java:78)
        at io.pravega.shared.protocol.netty.WireCommands$NoSuchSegment.process(WireCommands.java:279)
        at io.pravega.shared.protocol.netty.ReplyProcessor.process(ReplyProcessor.java:20)
        at io.pravega.client.netty.impl.FlowHandler.lambda$channelRead$2(FlowHandler.java:241)
        at java.util.Optional.ifPresent(Optional.java:159)
        at io.pravega.client.netty.impl.FlowHandler.channelRead(FlowHandler.java:239)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
[ForkJoinPool-2-worker-1] INFO io.pravega.client.stream.impl.EventStreamReaderImpl - EventStreamReaderImpl( id=0) encountered truncation for segment Scope/topic-t1-111/0.#epoch.0
[epollEventLoopGroup-5-6] INFO io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl - Received noSuchSegment No such segment: Scope/topic-t1-111/0.#epoch.0
[epollEventLoopGroup-5-6] WARN io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl - Exception while reading from Segment : Scope/topic-t1-111/0.#epoch.0
io.pravega.client.segment.impl.SegmentTruncatedException: Segment no longer exists.
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.noSuchSegment(AsyncSegmentInputStreamImpl.java:78)
        at io.pravega.shared.protocol.netty.WireCommands$NoSuchSegment.process(WireCommands.java:279)
        at io.pravega.shared.protocol.netty.ReplyProcessor.process(ReplyProcessor.java:20)
        at io.pravega.client.netty.impl.FlowHandler.lambda$channelRead$2(FlowHandler.java:241)
        at java.util.Optional.ifPresent(Optional.java:159)
        at io.pravega.client.netty.impl.FlowHandler.channelRead(FlowHandler.java:239)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
[grpc-default-executor-0] INFO io.pravega.client.netty.impl.ConnectionPoolImpl - Creating a new connection to PravegaNodeUri(endpoint=10.240.135.51, port=12345)
[grpc-default-executor-0] INFO io.pravega.client.netty.impl.FlowHandler - Creating Flow 13 for endpoint 10.240.135.51. The current Channel is null.
[epollEventLoopGroup-5-7] INFO io.pravega.client.netty.impl.FlowHandler - Connection established with endpoint 10.240.135.51 on ChannelId [id: 0x11ae8bf8]
[epollEventLoopGroup-5-7] INFO io.pravega.shared.protocol.netty.FailingReplyProcessor - Received hello: WireCommands.Hello(type=HELLO, highVersion=8, lowVersion=5)
[epollEventLoopGroup-5-7] INFO io.pravega.client.segment.impl.SegmentMetadataClientImpl - Closing connection as a result of receiving: No such segment: Scope/topic-t1-111/0.#epoch.0
[epollEventLoopGroup-5-7] INFO io.pravega.client.netty.impl.FlowHandler - Closing Flow 13 for endpoint 10.240.135.51
[ForkJoinPool-2-worker-1] INFO io.pravega.client.stream.impl.EventStreamReaderImpl - EventStreamReaderImpl( id=0) encountered end of segment Scope/topic-t1-111/0.#epoch.0
[ForkJoinPool-2-worker-1] INFO io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl - Closing reader for Scope/topic-t1-111/0.#epoch.0
[ForkJoinPool-2-worker-1] INFO io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl - Closing connection to segment: Scope/topic-t1-111/0.#epoch.0
[ForkJoinPool-2-worker-1] INFO io.pravega.client.netty.impl.FlowHandler - Closing Flow 12 for endpoint 10.240.135.51
[ForkJoinPool-2-worker-1] INFO io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl - Connection failed due to a io.pravega.client.stream.impl.ConnectionClosedException. Read requests will be retransmitted.
[ForkJoinPool-2-worker-1] INFO io.pravega.client.segment.impl.SegmentMetadataClientImpl - Closing segment metadata connection for Scope/topic-t1-111/0.#epoch.0
[ForkJoinPool-2-worker-1] INFO io.pravega.client.stream.impl.EventStreamReaderImpl - Closing reader EventStreamReaderImpl( id=0) at position Scope/topic-t1-111/0.#epoch.0=-1.
[ForkJoinPool-2-worker-1] INFO io.pravega.client.state.impl.StateSynchronizerImpl - Closing stateSynchronizer StateSynchronizerImpl(currentState=ReaderGroupState{ CheckpointState { ongoingCheckpoints: [eaec5989-a022-47c1-9076-38599e854f2d],  readersBlockingEachCheckpoint: {} } futureSegments: {} assignedSegments: {} unassignedSegments: {Scope/topic-t1-111/0.#epoch.0=-1} }, segment=Scope/_RGtopic-t1-111/0.#epoch.0)
[ForkJoinPool-2-worker-1] INFO io.pravega.client.netty.impl.FlowHandler - Closing Flow 9 for endpoint 10.240.135.50
[ForkJoinPool-2-worker-1] INFO io.pravega.client.segment.impl.ConditionalOutputStreamImpl - Closing segment metadata connection for Scope/_RGtopic-t1-111/0.#epoch.0
[ForkJoinPool-2-worker-1] INFO io.pravega.client.netty.impl.FlowHandler - Closing Flow 11 for endpoint 10.240.135.50
[ForkJoinPool-2-worker-1] INFO io.pravega.client.segment.impl.SegmentMetadataClientImpl - Closing segment metadata connection for Scope/_RGtopic-t1-111/0.#epoch.0
[ForkJoinPool-2-worker-1] INFO io.pravega.client.netty.impl.FlowHandler - Closing Flow 10 for endpoint 10.240.135.50
[ForkJoinPool-2-worker-1] INFO io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl - Closing reader for Scope/_RGtopic-t1-111/0.#epoch.0
[ForkJoinPool-2-worker-1] INFO io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl - Closing connection to segment: Scope/_RGtopic-t1-111/0.#epoch.0
[ForkJoinPool-2-worker-1] INFO io.pravega.client.netty.impl.FlowHandler - Closing Flow 8 for endpoint 10.240.135.50
[ForkJoinPool-2-worker-1] INFO io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl - Connection failed due to a io.pravega.client.stream.impl.ConnectionClosedException. Read requests will be retransmitted.

**Comment by shiveshr** [comment]
This will require a broader discussion so including @tkaitchuck  and @fpj.
This is because controller doesnt know about reader groups associated with a stream.
