### ISSUE TITLE
Reader Group Recreation failures

### ISSUE THREAD

**Issue by kmgowda** [pravega/pravega#4062]
**Problem description**
here is  the flow :
createReaderGroup -> deleteReaderGroup -> createReaderGroup  [Error] 

The 2nd invocation of createReaderGroup  fails with error

io.pravega.client.stream.InvalidStreamException: Segment does not exist: Scope/_RGtopic-t1-104RdGrp/0.#epoch.0
        at io.pravega.client.stream.impl.ClientFactoryImpl.createStateSynchronizer(ClientFactoryImpl.java:200)
        at io.pravega.client.admin.impl.ReaderGroupManagerImpl.createReaderGroup(ReaderGroupManagerImpl.java:95)
        at io.pravega.perf.PravegaStreamHandler.createReaderGroup(PravegaStreamHandler.java:153)
        at io.pravega.perf.PravegaPerfTest$PravegaTest.<init>(PravegaPerfTest.java:415)
        at io.pravega.perf.PravegaPerfTest.createTest(PravegaPerfTest.java:155)
        at io.pravega.perf.PravegaPerfTest.main(PravegaPerfTest.java:100)

**Problem location**
Controller/Client

**Suggestions for an improvement**
I could see that "createStateSynchronizer"  always uses the segment ID  set to 0.
If the readergroup is deleted and recreated , the segment id would differ with standard segment id 0. hence this bug.
Needs further investigation.

**Comment by shiveshr** [comment]
recreated streams have higher segment numbers. Readergroup should not assume any naming convention (like segment 0) on a stream segment name. Rather fetch the segment details from controller for the reader group stream.

**Comment by Richa-Srivastava** [comment]
@shrids Please share the verification steps to verify the issue.
