### ISSUE TITLE
Writer/Txn failure observed while running `small-scale-tx-bytes` longevity

### ISSUE THREAD

**Issue by deenav** [pravega/pravega#4072]
**Problem description**
Observed Writer failure (0/1) and a transaction aborted while running `small-scale-tx-bytes` longevity with `JDK11` client on Pravega build `0.5.0-2305.31c34b9`

Error log from `small-scale-tx-bytes-worker-8644b7b5c7-9h2zf ` 
```
INFO  [2019-07-26 15:16:31,937] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:206,987, events/sec:19, KB/sec:15.134766
INFO  [2019-07-26 15:16:31,937] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 13914, perSec:0.6416206261510129, committed:6968, failed:0, aborted:6945, aborted but read: 0
INFO  [2019-07-26 15:16:31,937] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 46,865, average block time (ms): 181
INFO  [2019-07-26 15:16:31,937] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:206,987, events/sec:19, KB/sec:15.134766
10.200.35.11 - - [26/Jul/2019:15:16:31 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 1225 "-" "Jersey/2.25.1 (HttpUrlConnection 11.0.3)" 4
INFO  [2019-07-26 15:16:41,350] io.pravega.longevity.testmanager.manager.TestPerformanceCollector: Received Error From task taskID : io.pravega.client.segment.impl.SegmentSealedException: SegmentSealed Exception
 for segment:longevity/smallScaleTxBytes/25.#epoch.42#transaction.0000002a00000000000000000000365a sealed for writer 9270ae1c-eb7f-4fbe-98cf-3692e3afe773
io.pravega.client.stream.TxnFailedException: io.pravega.client.segment.impl.SegmentSealedException: SegmentSealed Exception for segment:longevity/smallScaleTxBytes/25.#epoch.42#transaction.0000002a00000000000000
000000365a sealed for writer 9270ae1c-eb7f-4fbe-98cf-3692e3afe773
        at io.pravega.client.stream.impl.SegmentTransactionImpl.flush(SegmentTransactionImpl.java:94)
        at io.pravega.client.stream.impl.SegmentTransactionImpl.close(SegmentTransactionImpl.java:100)
        at io.pravega.client.stream.impl.EventStreamWriterImpl$TransactionImpl.commit(EventStreamWriterImpl.java:263)
        at io.pravega.longevity.testworker.workers.writers.PravegaWriterState.afterWrite(PravegaWriterState.kt:74)
        at io.pravega.longevity.testworker.workers.writers.PravegaWriter.start(PravegaWriter.java:151)
        at io.pravega.longevity.testworker.workers.writers.WriterWorkerManager.lambda$start$0(WriterWorkerManager.java:134)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.pravega.client.segment.impl.SegmentSealedException: SegmentSealed Exception for segment:longevity/smallScaleTxBytes/25.#epoch.42#transaction.0000002a00000000000000000000365a sealed for writer 9270a
e1c-eb7f-4fbe-98cf-3692e3afe773
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl.flush(SegmentOutputStreamImpl.java:517)
        at io.pravega.client.stream.impl.SegmentTransactionImpl.flush(SegmentTransactionImpl.java:88)
        ... 8 more

10.200.35.11 - - [26/Jul/2019:15:16:41 +0000] "POST /v1/longevity/error HTTP/1.1" 200 1896 "-" "Jersey/2.25.1 (HttpUrlConnection 11.0.3)" 4
INFO  [2019-07-26 15:17:01,937] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 3h 1m
INFO  [2019-07-26 15:17:01,937] io.pravega.longevity.utils.PerformanceUtils: Writers (0/1): events:206,987, events/sec:19, KB/sec:15.09375
INFO  [2019-07-26 15:17:01,937] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 13914, perSec:0.6398530762167126, committed:6968, failed:1, aborted:6945, aborted but read: 0
INFO  [2019-07-26 15:17:01,937] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 46,865, average block time (ms): 181
```
`kubectl get po` output
```
NAMESPACE           NAME                                                READY   STATUS      RESTARTS   AGE
default             pod/pravega-bookie-0                                1/1     Running     0          4d20h
default             pod/pravega-bookie-1                                1/1     Running     0          4d20h
default             pod/pravega-bookie-2                                1/1     Running     1          4d20h
default             pod/pravega-bookie-3                                1/1     Running     1          4d20h
default             pod/pravega-nfs-server-provisioner-0                1/1     Running     0          4d20h
default             pod/pravega-operator-78976dcb8c-rrhfp               1/1     Running     1          4d20h
default             pod/pravega-pravega-controller-b48f9f7cd-65bbt      1/1     Running     0          4d20h
default             pod/pravega-pravega-controller-b48f9f7cd-vrwhs      1/1     Running     0          4d20h
default             pod/pravega-pravega-segmentstore-0                  1/1     Running     0          4d20h
default             pod/pravega-pravega-segmentstore-1                  1/1     Running     0          4d19h
default             pod/pravega-pravega-segmentstore-2                  1/1     Running     0          4d19h
default             pod/pravega-zk-0                                    1/1     Running     0          4d20h
default             pod/pravega-zk-1                                    1/1     Running     0          4d20h
default             pod/pravega-zk-2                                    1/1     Running     0          4d20h
```
Pravega & client logs had been already shared in the slack & internal location

**Comment by shrids** [comment]
From the logs we can observe that the test pod running the pravega client and the controller pod were not able to contact the Segment store for a duration of 100seconds.

Details:
From the worker logs we can observe that the Append_Setup requests that were sent by the client @ `15:14:56,0541`  was received by the SSS only @ `15:16:41,270`.  (Similar to the delay observed by the controllers attempting to talk to the Segment stores for metadata)

[1]: The client attempts to send APPEND_SETUP to segment store. (Note: The client attempts to establish a connection to a segment only when a write is performed. When a flush/commit would establish connections toall the segments managed by TransactionalEventStreamWriter.)
```
/controller_server_2019-07-26.169.log:2019-07-26 15:14:56,052 10771147 [pool-3-thread-1] DEBUG i.p.c.s.i.SegmentOutputStreamImpl - (Re)connect invoked, Segment: longevity/smallScaleTxBytes/29.#epoch.42#transaction.0000002a00000000000000000000365a, writerID: 546329af-c3a4-45b9-a605-99149a87a75b
2019-07-26 15:14:56,052 10771147 [clientInternal-1-1] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Fetching endpoint for segment longevity/smallScaleTxBytes/29.#epoch.42#transaction.0000002a00000000000000000000365a, writer 546329af-c3a4-45b9-a605-99149a87a75b
2019-07-26 15:14:56,054 10771149 [clientInternal-1-1] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=10.200.22.11, port=12345) for longevity/smallScaleTxBytes/29.#epoch.42#transaction.0000002a00000000000000000000365a, writerID: 546329af-c3a4-45b9-a605-99149a87a75b
```
[2] The Segment store recieves it after 100+ seconds.
```
./segmentstore_2019-07-26.17.log:2019-07-26 15:16:41,270 191811601 [epollEventLoopGroup-11-8] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: e4eae486-ae95-4203-a555-94930ceec614 on segment: longevity/smallScaleTxBytes/30.#epoch.42#transaction.0000002a00000000000000000000365a
```
[3] The SSS responds to it, now the segment is ready to recieve appends.
```
2019-07-26 15:16:41,266 10876361 [epollEventLoopGroup-2-2] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Received AppendSetup WireCommands.AppendSetup(type=APPEND_SETUP, requestId=343691872960512, segment=longevity/smallScaleTxBytes/29.#epoch.42#transaction.0000002a00000000000000000000365a, writerId=546329af-c3a4-45b9-a605-99149a87a75b, lastEventNumber=-9223372036854775808)
2019-07-26 15:16:41,266 10876361 [epollEventLoopGroup-2-2] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Connection setup complete for writer 546329af-c3a4-45b9-a605-99149a87a75b
```

**Comment by fpj** [comment]
In the absence of further detail about the problem, I don't see what needs to be investigated here. If this reproduces consistently, then perhaps we can look into adding more information to be able to debug it, including enabling metrics.

If it doesn't reproduce consistently of it is not a problem with the Pravega code, then we should look into closing this issue.

**Comment by deenav** [comment]
This issue is not consistently reproducible, `small-scale-tx-bytes` longevity with JDK11 client on Pravega build `0.5.0-2306.a5a5cdf` ran fine for more than `4+ days` 

```
INFO  [2019-08-10 15:15:52,506] io.pravega.longevity.utils.PerformanceUtils: New runtime for a708d4cc-ca9c-403b-ab9f-812d023f3a9b  Running for 4d 1h
INFO  [2019-08-10 15:15:52,506] io.pravega.longevity.utils.PerformanceUtils: Dumping stats for stream longevity/smallScaleTxBytes
INFO  [2019-08-10 15:15:52,506] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:4,273,703, events/sec:12, KB/sec:9.673828
INFO  [2019-08-10 15:15:52,506] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 285498, perSec:0.40609947270913493, committed:142480, failed:0, aborted:143017, aborted but read: 0
INFO  [2019-08-10 15:15:52,506] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 890,285, average block time (ms): 181
INFO  [2019-08-10 15:15:52,507] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:4,273,701, events/sec:12, KB/sec:9.673828
```

**Comment by shrids** [comment]
@deenav, thanks for the update. Closing this issue on the above findings.
