### ISSUE TITLE
Observing "Controller API call with tag none failed with error" in controller logs

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#4108]
Observing this error in controller log:
```
2019-08-14 12:19:24,623 87567 [controllerpool-13] ERROR i.p.c.s.r.g.v.ControllerServiceImpl - Controller API call with tag none failed with error: 
io.pravega.controller.store.stream.StoreException$DataNotFoundException: get entry: key: state table: _system/_tables/_system/_requeststream/metadata.#.32b66093-f362-4c54-abb3-459e7fc329e9
        at io.pravega.controller.store.stream.StoreException.create(StoreException.java:90)
        at io.pravega.controller.store.stream.StoreException.create(StoreException.java:70)
        at io.pravega.controller.store.stream.PravegaTablesStoreHelper.lambda$getEntry$22(PravegaTablesStoreHelper.java:278)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
		

Environment details: PKS / K8 with medium cluster:
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend

```
Deployment details:
```
bookkeeper:0.6.0-2333.fed6fd5
pravega:0.6.0-2333.fed6fd5
pravega-operator:0.4.2-rc0
pravega/zookeeper:0.2.2
pravega/zookeeper-operator:0.2.2

```
PS: However, i/o failure isn't observed..  

Comeplete k8s logs will be shared in internal channel as logs size > 10 MB.

**Comment by shiveshr** [comment]
I dont think there is any behaviour problem here. 
We expect such logs if internal stream's metadata access is attempted before it is created. 
So is it about muting the expected logging or is there a behaviour problem?

**Comment by Raghuveera-Rao** [comment]
> I dont think there is any behaviour problem here.
> We expect such logs if internal stream's metadata access is attempted before it is created.
> So is it about muting the expected logging or is there a behaviour problem?

There is no I/O failure with this error. However, the error "Controller API call with tag none failed with error"  needs to have more clarity at logging. I did not get much from this "tag none failed".

**Comment by shiveshr** [comment]
The exception is present in the log snippet posted above. I am closing the issue as there is nothing to do here.
