### ISSUE TITLE
Seeing this error 'Could not find host for container' in controller log

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#4139]
Observing this error in controller log:

**ERROR i.p.c.s.r.g.v.ControllerServiceImpl - Could not find host for container id: 16**

Error snippet:
```
2019-08-22 15:39:38,826 703307630 [grpc-default-executor-9563] ERROR i.p.c.s.r.g.v.ControllerServiceImpl - Could not find host for container id: 16
io.pravega.controller.store.host.HostStoreException: Could not find host for container id: 16
        at io.pravega.controller.store.host.ZKHostStore.getHostForContainer(ZKHostStore.java:131)
        at io.pravega.controller.store.host.ZKHostStore.getHostForSegment(ZKHostStore.java:143)
        at io.pravega.controller.server.SegmentHelper.getSegmentUri(SegmentHelper.java:119)
        at io.pravega.controller.server.ControllerService.getURI(ControllerService.java:283)
        at io.pravega.controller.server.rpc.grpc.v1.ControllerServiceImpl.lambda$getURI$33(ControllerServiceImpl.java:288)
        at io.pravega.controller.server.rpc.grpc.v1.ControllerServiceImpl.authenticateExecuteAndProcessResults(ControllerServiceImpl.java:493)
        at io.pravega.controller.server.rpc.grpc.v1.ControllerServiceImpl.authenticateExecuteAndProcessResults(ControllerServiceImpl.java:522)
        at io.pravega.controller.server.rpc.grpc.v1.ControllerServiceImpl.getURI(ControllerServiceImpl.java:285)
        at io.pravega.controller.stream.api.grpc.v1.ControllerServiceGrpc$MethodHandlers.invoke(ControllerServiceGrpc.java:1968)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

Environment details: PKS / K8 with medium cluster:

```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```

Deployment details:

```
bookkeeper:0.6.0-2333.fed6fd5
pravega:0.6.0-2333.fed6fd5
pravega-operator:0.4.2-rc0
pravega/zookeeper:0.2.2
pravega/zookeeper-operator:0.2.2
```

This happened during Segment store scaling up and then scaling down test.

PS: However, i/o failure isn't observed..

Comeplete k8s logs will be shared in internal channel as logs size > 10 MB.

**Comment by fpj** [comment]
If this:

> Could not find host for container id: 16

happened " during Segment store scaling up and then scaling down test.", then how is it an issue? It is expected that the segment container is unavailable during failover.
