### ISSUE TITLE
Writers failed and reader events stalled due to aborted transactions 

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega#4147]
**Problem description**

**Writers failed (1/4 )and writer & reader events stalled from `events:9,093,571`** due to aborted transactions on running the same stream with a workload of 
writers: 4, readers: 8, routing keys: 256, max events/sec: 1000, scaling policy: events_per_sec, target rate: 200, scale factor: 2, min segments: 4, record size: 100 bytes after running for **`23 hours`**.

Stream manager pod log:
```
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 23h 7m
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:9,093,548, events/sec:109, KB/sec:83.74609
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 607922, perSec:3.642942942942943, committed:303275, failed:0, aborted:304643, aborted but read: 0
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils: Readers (8/8): events:9,093,540, events/sec:109, KB/sec:83.74609
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils: New runtime for 057a643e-e83f-4bb9-8b05-b6809ee3dd95  Running for 23h 7m
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils: Dumping stats for stream longevity/mediumScaleTx
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:9,093,548, events/sec:109, KB/sec:83.77637
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 607922, perSec:3.642942942942943, committed:303275, failed:0, aborted:304643, aborted but read: 0
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils: Readers (8/8): events:9,093,540, events/sec:109, KB/sec:83.77637

INFO  [2019-08-28 13:13:06,680] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-08-28 13:13:06,680] io.pravega.longevity.utils.PerformanceUtils: Readers (8/8): events:9,093,541, events/sec:109, KB/sec:83.71582
172.28.1.3 - - [28/Aug/2019:13:13:06 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 1875 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 1
INFO  [2019-08-28 13:13:25,509] io.pravega.longevity.testmanager.manager.TestPerformanceCollector: 
Received Error From task taskID : Got an aborted transaction, didn't expect that
java.lang.IllegalStateException: Got an aborted transaction, didn't expect that
        at io.pravega.longevity.testworker.workers.writers.PravegaWriterState$forkWatchProcess$watchProcess$1.run(PravegaWriterState.kt:147)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

INFO  [2019-08-28 13:16:26,908] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-08-28 13:16:26,908] io.pravega.longevity.utils.PerformanceUtils: Readers (8/8): events:9,093,569, events/sec:108, KB/sec:83.53613
172.28.1.3 - - [28/Aug/2019:13:16:26 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 1869 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 1
INFO  [2019-08-28 13:16:45,621] io.pravega.longevity.testmanager.manager.TestPerformanceCollector: 
Received Error From task taskID : io.pravega.client.segment.impl.SegmentSealedException: 
SegmentSealed Exception for segment:longevity/mediumScaleTx/1.#epoch.0#transaction.000000000000000000000000000946b1 sealed for writer 8511bfbe-f840-42e5-85b9-f52b36a954f8
io.pravega.client.stream.TxnFailedException: 
io.pravega.client.segment.impl.SegmentSealedException: 
SegmentSealed Exception for segment:longevity/mediumScaleTx/1.#epoch.0#transaction.000000000000000000000000000946b1 sealed for writer 8511bfbe-f840-42e5-85b9-f52b36a954f8
        at io.pravega.client.stream.impl.SegmentTransactionImpl.flush(SegmentTransactionImpl.java:94)
        at io.pravega.client.stream.impl.SegmentTransactionImpl.close(SegmentTransactionImpl.java:100)
        at io.pravega.client.stream.impl.EventStreamWriterImpl$TransactionImpl.commit(EventStreamWriterImpl.java:263)
        at io.pravega.longevity.testworker.workers.writers.PravegaWriterState.afterWrite(PravegaWriterState.kt:74)
        at io.pravega.longevity.testworker.workers.writers.PravegaWriter.start(PravegaWriter.java:151)
        at io.pravega.longevity.testworker.workers.writers.WriterWorkerManager.lambda$start$0(WriterWorkerManager.java:134)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: io.pravega.client.segment.impl.SegmentSealedException: 
SegmentSealed Exception for segment:longevity/mediumScaleTx/1.#epoch.0#transaction.000000000000000000000000000946b1 sealed for writer 8511bfbe-f840-42e5-85b9-f52b36a954f8
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl.flush(SegmentOutputStreamImpl.java:521)
        at io.pravega.client.stream.impl.SegmentTransactionImpl.flush(SegmentTransactionImpl.java:88)
        ... 8 more

```

Controller logs during the writer failure occured:
```
2019-08-28 13:04:16,226 85097099 [epollEventLoopGroup-2-2] INFO  i.p.client.netty.impl.FlowHandler - Closing Flow 40518164 for endpoint 172.28.69.12
2019-08-28 13:04:16,226 85097099 [epollEventLoopGroup-2-2] INFO  i.p.controller.server.SegmentHelper - ReadTable _system/_tables/longevity/mediumScaleTx/transactionsInEpoch-0.#.8fb1379a-2996-4e87-a793-9b0c179bdb38 TableRead 174024189273964544.
2019-08-28 13:04:16,227 85097100 [controllerpool-8] ERROR i.p.c.s.r.g.v.ControllerServiceImpl - Controller API call with tag none failed with error:
io.pravega.controller.store.stream.StoreException$DataNotFoundException: get entry: key: 00000000-0000-0000-0000-0000000945c9 table: _system/_tables/longevity/mediumScaleTx/transactionsInEpoch-0.#.8fb1379a-2996-4e87-a793-9b0c179bdb38
        at io.pravega.controller.store.stream.StoreException.create(StoreException.java:90)
        at io.pravega.controller.store.stream.StoreException.create(StoreException.java:70)
        at io.pravega.controller.store.stream.PravegaTablesStoreHelper.lambda$getEntry$22(PravegaTablesStoreHelper.java:278)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2019-08-28 13:12:51,049 85611922 [controllerpool-6] WARN  i.p.c.server.ControllerService - Transaction commit failed
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$IllegalStateException: Stream: mediumScaleTx Transaction: 00000000-0000-0000-0000-0000000946af State: ABORTED
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.controller.store.stream.StoreException$IllegalStateException: Stream: mediumScaleTx Transaction: 00000000-0000-0000-0000-0000000946af State: ABORTED
        at io.pravega.controller.store.stream.StoreException.create(StoreException.java:99)
        at io.pravega.controller.store.stream.StoreException.create(StoreException.java:70)
        at io.pravega.controller.store.stream.PersistentStreamBase.lambda$validateCompletedTxn$152(PersistentStreamBase.java:1250)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        ... 12 common frames omitted
```

Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.
Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Pravega version : 0.6.0-2345.298015f
Zookeeper Operator : pravega/zookeeper:0.2.2
Pravega Operator:  pravega/zookeeper-operator:0.2.2
```

**Comment by SomeshJoshi19** [comment]
Sharing the log location in internal channel due to size limit

**Comment by shrids** [comment]
*Summary:* The test uses a transaction timeout of 30seconds, which is small.

*Details:*
The midscale txn manager observed that the a transaction has been aborted causing the writer to fail
```
INFO  [2019-08-28 13:13:25,509] io.pravega.longevity.testmanager.manager.TestPerformanceCollector: Received Error From task taskID : Got an aborted transaction, didn't expect that
java.lang.IllegalStateException: Got an aborted transaction, didn't expect that
        at io.pravega.longevity.testworker.workers.writers.PravegaWriterState$forkWatchProcess$watchProcess$1.run(PravegaWriterState.kt:147)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
```
From the worker logs we can observe that the txn `000000000000000000000000000946b2` was aborted .

a. The txn was created @ `13:12:12`

```
Controller Logs:
2019-08-28 13:12:12,089 85572962 [epollEventLoopGroup-2-1] INFO  i.p.controller.server.SegmentHelper - Closing connection as a result of receiving: WireCommands.SegmentCreated(type=SEGMENT_CREATED, requestId=174049379257155584, segment=longevity/mediumScaleTx/0.#epoch.0#transaction.000000000000000000000000000946b2)
2019-08-28 13:12:12,091 85572964 [epollEventLoopGroup-2-2] INFO  i.p.controller.server.SegmentHelper - Closing connection as a result of receiving: WireCommands.SegmentCreated(type=SEGMENT_CREATED, requestId=174049374962188288, segment=longevity/mediumScaleTx/1.#epoch.0#transaction.000000000000000000000000000946b2)
2019-08-28 13:12:12,136 85573009 [epollEventLoopGroup-2-2] INFO  i.p.controller.server.SegmentHelper - Closing connection as a result of receiving: WireCommands.SegmentCreated(type=SEGMENT_CREATED, requestId=174049370667220992, segment=longevity/mediumScaleTx/3.#epoch.0#transaction.000000000000000000000000000946b2)
2019-08-28 13:12:12,146 85573019 [epollEventLoopGroup-2-2] INFO  i.p.controller.server.SegmentHelper - Closing connection as a result of receiving: WireCommands.SegmentCreated(type=SEGMENT_CREATED, requestId=174049366372253696, segment=longevity/mediumScaleTx/2.#epoch.0#transaction.000000000000000000000000000946b2)
```

b. From the Segment store logs the txn segments we deleted around 30 seconds later @ `13:12:44`

```
./segmentstore.log:2019-08-28 13:12:44,036 85561549 [epollEventLoopGroup-11-3] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=48479383224057856] Deleting segment WireCommands.DeleteSegment(type=DELETE_SEGMENT, requestId=48479383224057856, segment=longevity/mediumScaleTx/2.#epoch.0#transaction.000000000000000000000000000946b2, delegationToken=)
./segmentstore.log:2019-08-28 13:12:44,036 85561549 [epollEventLoopGroup-11-6] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=48479387519025152] Deleting segment WireCommands.DeleteSegment(type=DELETE_SEGMENT, requestId=48479387519025152, segment=longevity/mediumScaleTx/3.#epoch.0#transaction.000000000000000000000000000946b2, delegationToken=)
```

c. The first ping was sent by the client @ `13:12:34` which is correct.
```
 2019-08-28 13:12:34,177 83274833 [clientInternal-1-4] DEBUG i.pravega.client.stream.impl.Pinger - Sending ping request for txn ID: 00000000-0000-0000-0000-0000000946b2 with lease: 30000
```

d. The client logs indicate that the txn had already timedout when the client trying to establish a connection with the segment store.
```
// Client attempting to connect
2019-08-28 13:12:23,932 83264588 [pool-3-thread-4] DEBUG i.p.c.s.i.SegmentOutputStreamImpl - (Re)connect invoked, Segment: longevity/mediumScaleTx/2.#epoch.0#transaction.000000000000000000000000000946b2, writerID: 30d5a7a9-507d-4966-afc5-c97f808a8da8
2019-08-28 13:12:34,794 83275450 [clientInternal-1-5] DEBUG i.p.c.s.i.SegmentOutputStreamImpl - Running reconnect for segment longevity/mediumScaleTx/2.#epoch.0#transaction.000000000000000000000000000946b2 writer 30d5a7a9-507d-4966-afc5-c97f808a8da8

// Client fetching endpoint of the segment from controller
2019-08-28 13:12:34,794 83275450 [clientInternal-1-5] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Fetching endpoint for segment longevity/mediumScaleTx/2.#epoch.0#transaction.000000000000000000000000000946b2, writer 30d5a7a9-507d-4966-afc5-c97f808a8da8

//Received a response from Controller with endpoint after 17 seconds.
2019-08-28 13:12:51,991 83292647 [clientInternal-1-4] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=172.28.69.12, port=12345) for longevity/mediumScaleTx/2.#epoch.0#transaction.000000000000000000000000000946b2, writerID: 30d5a7a9-507d-4966-afc5-c97f808a8da8

// response from SSS recieved indicating the segment does not exist as the txn has been aborted.
2019-08-28 13:12:57,922 83298578 [epollEventLoopGroup-2-2] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Received noSuchSegment for writer 30d5a7a9-507d-4966-afc5-c97f808a8da8
```
e. From the available logs observe that first ping request received by the controller @ `13:12:50` while the client logs indicate that the ping was sent at `13:12:34`

```
[root@mdw oldlogs_pravega-pravega-controller-5f495b99b9-44lzg]#  grep -r "2019-08-28 13:12" ./ | grep "607922"
./controller_2019-08-28.2748.log:2019-08-28 13:12:50,171 85611044 [grpc-default-executor-602] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - pingTransaction called for stream longevity/mediumScaleTx, txnId=lowBits: 607922
./controller_2019-08-28.2748.log:2019-08-28 13:12:50,172 85611045 [grpc-default-executor-602] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - pingTransaction called for stream longevity/mediumScaleTx, txnId=lowBits: 607922
```

@SomeshJoshi19 Could you try running this with a higher transaction timeout? The longevity suite has hardcoded the value to 30seconds.

I have also raised a PR to change the default timeout to 90 seconds @ #4150

**Comment by SomeshJoshi19** [comment]
@shrids On following to the above findings for the reported issue, I'll retest the scenario with the updated test code and check if issue persists or not.
