### ISSUE TITLE
Configuration flag to allow TLS-disabled Controller to connect to TLS-enabled Segment Store

### ISSUE THREAD

**Issue by ravisharda** [pravega/pravega#4157]
**Problem description**
In some deployment configurations, TLS is disabled for Controller service endpoints, while it is enabled for Segment Store service endpoints. This happens when you terminate TLS at a reverse proxy or a Kubernetes Ingress for Controller service instances, while you terminate TLS directly at the service for Segment Store instances. 

Under such a configuration, TLS is configured as disabled for the Controller. But then, Controller assumes that TLS is also disabled for the Segment Store, and therefore encounters an exception of the following form when it attempts to connect to the Segment Store: 

```
Caused by: java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$StoreConnectionException: get entry: key: _system table: _system/_tables/scopes
	at io.pravega.controller.store.stream.PravegaTablesStoreHelper.lambda$null$49(PravegaTablesStoreHelper.java:515)
	... 36 common frames omitted
Caused by: io.pravega.controller.store.stream.StoreException$StoreConnectionException: get entry: key: _system table: _system/_tables/scopes
	at io.pravega.controller.store.stream.StoreException.create(StoreException.java:105)
	at io.pravega.controller.store.stream.PravegaTablesStoreHelper.lambda$null$49(PravegaTablesStoreHelper.java:483)
	... 36 common frames omitted
Caused by: io.pravega.controller.server.WireCommandFailedException: WireCommandFailed with type READ_TABLE reason ConnectionFailed
	at io.pravega.controller.server.SegmentHelper.lambda$sendRequest$26(SegmentHelper.java:639)
	... 36 common frames omitted
```

Correspondigly, on the Segment Store side, one'd observe exceptions as shown below: 

```
2019-09-06 07:02:16,435 19060160 [epollEventLoopGroup-11-2] ERROR i.p.s.p.n.ExceptionLoggingHandler - Uncaught exception on connection /100.64.65.143:16317
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1140)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1101)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1169)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1212)
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:216)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:
```

**Problem location**

**Suggestions for an improvement**
Introduce a new optional configuration flag that tells a Controller that TLS is enabled for Segment Store, even if that is not the case for itself.

**Comment by gaddamas** [comment]
Also noticed that -Dauth.tlsEnabled=false is not effective.
```
JAVA_OPTS = -Xms512m -XX:+ExitOnOutOfMemoryError -XX:+CrashOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/dumpfile/heap -Dpravegaservice.clusterName=nautilus -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2 -Dcontroller.metrics.influxDBUserName=admin -Dpravega.client.auth.token=YWRtaW46MTExMV9hYWFh -DUSER_PASSWORD_FILE=/opt/pravega/conf/passwd -Dpravega.client.auth.method=Basic -Dmetrics.influxDBRetention=two_hour -Dpravegaservice.certFile=/etc/secret-volume/tls.crt -Dcontroller.auth.tlsEnabled=true -Dcontroller.auth.tlsKeyFile=/etc/secret-volume/tls.key -DautoScale.authEnabled=true -Dbookkeeper.tlsEnabled=false -Drest.tlsKeyStoreFile=/etc/secret-volume/tls.crt -Dcontroller.auth.accessTokenTtlSeconds=-1 -DAUTHORIZATION_ENABLED=true -Dcontroller.metrics.influxDBURI=http://nautilus-pravega-influxdb:8086 -Dcontroller.metrics.outputFrequencySeconds=10 -Dcontroller.metrics.influxDBPassword=password -DautoScale.tokenSigningKey=mysecretkey -Dmetrics.influxDBPassword=password -Dcontroller.metrics.enableStatistics=true -Dmetrics.outputFrequencySeconds=10 -DTOKEN_SIGNING_KEY=mysecretkey -Dcontroller.metrics.influxDBName=pravega -DautoScale.validateHostName=false -Dauth.tlsEnabled=false -Dpravegaservice.enableTlsReload=true -Dcontroller.auth.tlsCertFile=/etc/secret-volume/tls.crt -DautoScale.tlsCertFile=/etc/secret-volume/tls.crt -DautoScale.tlsEnabled=true -Dmetrics.influxDBName=pravega -Dmetrics.enableStatistics=true -Dcontroller.auth.tlsTrustStore=/etc/secret-volume/tls.crt -DTLS_ENABLED=false -Dpravegaservice.keyFile=/etc/secret-volume/tls.key -Dmetrics.enableInfluxDBReporter=true -Dpravegaservice.enableTls=true -Dcontroller.metrics.influxDBRetention=two_hour -Dmetrics.influxDBURI=http://nautilus-pravega-influxdb:8086 -Dcontroller.metrics.enableInfluxDBReporter=true -Dmetrics.influxDBUserName=admin -Dcontroller.metrics.metricsPrefix=nautilus-pravega-controller-6cb5bc5864-b6dpz -Dcontroller.zk.url=nautilus-pravega-zookeeper-0.nautilus-pravega-zookeeper-headless.nautilus-pravega:2181,nautilus-pravega-zookeeper-1.nautilus-pravega-zookeeper-headless.nautilus-pravega:2181,nautilus-pravega-zookeeper-2.nautilus-pravega-zookeeper-headless.nautilus-pravega:2181 -Dcontroller.server.store.host.type=Zookeeper
2019-09-06 20:45:40,963 1103 [main] INFO  io.pravega.controller.util.Config - java.vendor.url = http://java.oracle.com/
2019-09-06 20:45:40,963 1103 [main] INFO  io.pravega.controller.util.Config - sun.os.patch.level = unknown
2019-09-06 20:45:40,963 1103 [main] INFO  io.pravega.controller.util.Config - KUBERNETES_SERVICE_PORT = 443
2019-09-06 20:45:40,963 1103 [main] INFO  io.pravega.controller.util.Config - NAUTILUS_PRAVEGA_ZOOKEEPER_CLIENT_SERVICE_PORT_CLIENT = 2181
2019-09-06 20:45:40,963 1103 [main] INFO  io.pravega.controller.util.Config - config.file = /opt/pravega/conf/controller.config.properties
2019-09-06 20:45:40,963 1103 [main] INFO  io.pravega.controller.util.Config - metrics.influxDBUserName = admin
2019-09-06 20:45:40,964 1104 [main] INFO  io.pravega.controller.util.Config - NAUTILUS_PRAVEGA_SEGMENTSTORE_0_SERVICE_PORT_SERVER = 12345
2019-09-06 20:45:40,964 1104 [main] INFO  io.pravega.controller.util.Config - java.endorsed.dirs = /usr/lib/jvm/java-1.8-openjdk/jre/lib/endorsed
2019-09-06 20:45:40,964 1104 [main] INFO  io.pravega.controller.util.Config - KUBERNETES_PORT_443_TCP_PROTO = tcp
2019-09-06 20:45:40,964 1104 [main] INFO  io.pravega.controller.util.Config - controller.auth.tlsKeyFile = /etc/secret-volume/tls.key
2019-09-06 20:45:40,964 1104 [main] INFO  io.pravega.controller.util.Config - PWD = /opt/pravega
2019-09-06 20:45:40,964 1104 [main] INFO  io.pravega.controller.util.Config - NAUTILUS_PRAVEGA_SEGMENTSTORE_0_PORT_12345_TCP_ADDR = 10.100.200.169
2019-09-06 20:45:40,964 1104 [main] INFO  io.pravega.controller.util.Config - controller.metrics.enableStatistics = true
2019-09-06 20:45:40,964 1104 [main] INFO  io.pravega.controller.util.Config - java.home = /usr/lib/jvm/java-1.8-openjdk/jre
2019-09-06 20:45:40,964 1104 [main] INFO  io.pravega.controller.util.Config - NAUTILUS_PRAVEGA_SEGMENTSTORE_0_PORT = tcp://10.100.200.169:12345
2019-09-06 20:45:40,964 1104 [main] INFO  io.pravega.controller.util.Config - NAUTILUS_PRAVEGA_SEGMENTSTORE_1_SERVICE_PORT_SERVER = 12345
2019-09-06 20:45:40,965 1105 [main] INFO  io.pravega.controller.util.Config - bookkeeper.tlsEnabled = false
2019-09-06 20:45:40,965 1105 [main] INFO  io.pravega.controller.util.Config - file.encoding.pkg = sun.io
2019-09-06 20:45:40,965 1105 [main] INFO  io.pravega.controller.util.Config - KUBERNETES_PORT_443_TCP = tcp://10.100.200.1:443
2019-09-06 20:45:40,965 1105 [main] INFO  io.pravega.controller.util.Config - KUBERNETES_PORT_443_TCP_ADDR = 10.100.200.1
2019-09-06 20:45:40,973 1113 [main] INFO  io.pravega.controller.util.Config - publishedRPCHost is not configured, will use default value
2019-09-06 20:45:40,983 1123 [main] INFO  i.p.s.metrics.StatsProviderProxy - Stats enabled
2019-09-06 20:45:41,273 1413 [main] INFO  i.p.s.metrics.StatsProviderImpl - Metrics prefix: nautilus-pravega-controller-6cb5bc5864-b6dpz
2019-09-06 20:45:41,357 1497 [main] INFO  i.p.s.metrics.RegistryConfigUtil - Configuring stats with statsD at localhost:8125
2019-09-06 20:45:42,165 2305 [main] INFO  i.p.s.metrics.RegistryConfigUtil - Configuring stats with direct InfluxDB at http://nautilus-pravega-influxdb:8086
2019-09-06 20:45:42,168 2308 [main] INFO  i.m.influx.InfluxMeterRegistry - publishing metrics to influx every 10s
2019-09-06 20:45:42,361 2501 [main] ERROR io.pravega.controller.server.Main - Controller service failed
java.lang.IllegalArgumentException: TLS: KeyFilePath should not be empty when TLS is enabled. 
	at io.pravega.common.Exceptions.checkArgument(Exceptions.java:210)
	at io.pravega.controller.server.rest.impl.RESTServerConfigImpl.<init>(RESTServerConfigImpl.java:33)
	at io.pravega.controller.server.rest.impl.RESTServerConfigImpl$RESTServerConfigImplBuilder.build(RESTServerConfigImpl.java:29)
	at io.pravega.controller.server.Main.main(Main.java:92)
```

**Comment by jkhalack** [comment]
> Also noticed that -Dauth.tlsEnabled=false is not effective.
> 
@gaddamas Did you try with `-Dcontroller.auth.tlsEnabled=false` ?

**Comment by ravisharda** [comment]
@gaddamas the right configuration to disable TLS in Controller is `-Dcontroller.auth.tlsEnabled=false`, not `-Dauth.tlsEnabled=false`.

**Comment by gaddamas** [comment]
it worked with -Dcontroller.auth.tlsEnabled=true, however I had to give “controller.rest.tlsKeyStoreFile”: “/etc/secret-volume/tls.crt”, as well, since rest endpoint of controller is looking for keystore.
