### ISSUE TITLE
Gradle task startStandalone does not work on Java 9+

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#4176]
**Problem description**
Invoking `gradlew startStandlone` in Java 11 fails with the following error 
```
2019-09-18 01:34:41,570 564  [main] ERROR i.p.local.LocalPravegaEmulator - Exception occurred running emulator
java.io.FileNotFoundException: /home/osboxes/.gradle/daemon/4.10.2/config/standalone-config.properties (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at io.pravega.segmentstore.server.store.ServiceBuilderConfig$Builder.include(ServiceBuilderConfig.java:140)
	at io.pravega.local.LocalPravegaEmulator.main(LocalPravegaEmulator.java:83)

```

**Problem location**
build.gradle

**Suggestions for an improvement**
Fix the issue.

**Comment by fpj** [comment]
One question about this issue, @shrids . I remember that we had this error when running standalone on pravega compiled with Java 9+ (not Java 8):

```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer
```

The error you are reporting happens when compiling with Java 8 and running with Java 11? Or are you compiling and running with Java 11?

Please clarify.

**Comment by shrids** [comment]
The issue happens in both the following cases.
- Compile with Java 11 and run with `gradlew startStandalone` on Java 11.
- Compile with Java 8 and run `gradlew startStandalone` on Java 11.
