### ISSUE TITLE
Race condition in Netty client code.

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#4192]
**Problem description**
When data is returned from the server to and passed to the client it first goes through the:
`LengthFieldBasedFrameDecoder` which reads the length (4 bytes in) and parses it, then allocates a buffer of that size, and fills it and returns it up to the next layer. This includes the length value which it read. 
The next layer in the stack is `CommandDecoder` which reads the type (those first 4 bytes that were skipped) and then it re-reads the length. It asserts that this length is the length of the buffer it was given. It should be as otherwise there is a bug in `LengthFieldBasedFrameDecoder`. (Which is netty code) or it was modified between these calls. (But as there is not code between them this would have to occur in another thread.)

We see this assertion triggering. It manifests in two different ways:
```
03:22:39  INFO  [2019-09-19 10:22:12,068] io.pravega.longevity.utils.PerformanceUtils: Readers (6/6): events:0, events/sec:0, KB/sec:0.0
03:22:39  172.28.141.4 - - [19/Sep/2019:10:22:12 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 848 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 5
03:23:05  INFO  [2019-09-19 10:22:38,110] io.pravega.longevity.testmanager.manager.TestPerformanceCollector: Received Error From task taskID : io.netty.handler.codec.DecoderException: io.pravega.shared.protocol.netty.InvalidMessageException: Header indicated more bytes than exist.
03:23:05  io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.handler.codec.DecoderException: io.pravega.shared.protocol.netty.InvalidMessageException: Header indicated more bytes than exist.
03:23:05    at io.pravega.client.netty.impl.ClientConnectionInboundHandler.exceptionCaught(ClientConnectionInboundHandler.java:106)
03:23:05    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
03:23:05    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
03:23:05    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
03:23:05    at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
03:23:05    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
03:23:05    at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:850)
03:23:05    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:247)
03:23:05    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
03:23:05    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
03:23:05    at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
03:23:05    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
03:23:05    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
03:23:05    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
03:23:05    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
03:23:05    at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
03:23:05    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
03:23:05    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
03:23:05    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
03:23:05    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1354)
03:23:05    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
03:23:05    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
03:23:05    at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:917)
03:23:05    at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
03:23:05    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
03:23:05    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
03:23:05    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
03:23:05    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
03:23:05    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
03:23:05    at java.lang.Thread.run(Unknown Source)
03:23:05  Caused by: io.netty.handler.codec.DecoderException: io.pravega.shared.protocol.netty.InvalidMessageException: Header indicated more bytes than exist.
03:23:05    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
03:23:05    at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392)
03:23:05    at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:359)
03:23:05    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
03:23:05    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
03:23:05    ... 22 more
03:23:05  Caused by: io.pravega.shared.protocol.netty.InvalidMessageException: Header indicated more bytes than exist.
03:23:05    at io.pravega.shared.protocol.netty.CommandDecoder.readLength(CommandDecoder.java:65)
03:23:05    at io.pravega.shared.protocol.netty.CommandDecoder.parseCommand(CommandDecoder.java:54)
03:23:05    at io.pravega.shared.protocol.netty.CommandDecoder.decode(CommandDecoder.java:36)
03:23:05    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
03:23:05    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
03:23:05    ... 26 more
```

and as:
```
02:05:27  INFO  [2019-09-19 00:04:54,699] io.pravega.client.netty.impl.RawClient: Received hello: WireCommands.Hello(type=HELLO, highVersion=8, lowVersion=5)
02:05:27  WARN  [2019-09-19 00:04:54,718] io.pravega.client.netty.impl.RawClient: Processing failure: 
02:05:27  ! io.pravega.shared.protocol.netty.InvalidMessageException: Length read from wire was negitive.
02:05:27  ! at io.pravega.shared.protocol.netty.CommandDecoder.readLength(CommandDecoder.java:62)
02:05:27  ! at io.pravega.shared.protocol.netty.CommandDecoder.parseCommand(CommandDecoder.java:54)
02:05:27  ! at io.pravega.shared.protocol.netty.CommandDecoder.decode(CommandDecoder.java:36)
02:05:27  ! at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
02:05:27  ! at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
02:05:27  ! ... 24 common frames omitted
02:05:27  ! Causing: io.netty.handler.codec.DecoderException: io.pravega.shared.protocol.netty.InvalidMessageException: Length read from wire was negitive.
02:05:27  ! at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
02:05:27  ! at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
02:05:27  ! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
02:05:27  ! ... 22 common frames omitted
02:05:27  ! Causing: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.handler.codec.DecoderException: io.pravega.shared.protocol.netty.InvalidMessageException: Length read from wire was negitive.
```
In both cases the value in the buffer must have changed between `CommandDecoder` and `LengthFieldBasedFrameDecoder`. 

**Problem location**
Netty

**Comment by tkaitchuck** [comment]
Fixed in https://github.com/pravega/pravega/commit/d4a22be5cc17894e1450e49f81e1accace544628
