### ISSUE TITLE
Incorrect assertion in ContainerKeyIndexTests

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#4193]
**Problem description**
ContainerKeyIndexTests expects `ContainerKeyIndex.getBucketOffsets()` not to block even though it is an async method.
```
io.pravega.segmentstore.server.tables.ContainerKeyIndexTests > testRecovery FAILED
    java.lang.AssertionError: Expected getBucketOffsets() to block.
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertFalse(Assert.java:64)
        at io.pravega.segmentstore.server.tables.ContainerKeyIndexTests.testRecovery(ContainerKeyIndexTests.java:469)
```

**Problem location**
ContainerKeyIndexTests

**Suggestions for an improvement**
The test should be changed to make a more accurate assertion about what the code does.

**Comment by tkaitchuck** [comment]
This same test also is failing as:
```
io.pravega.segmentstore.server.tables.ContainerKeyIndexTests > testRecoveryTimeout FAILED
    java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Table Segment 0 recovery timed out.
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
        at io.pravega.segmentstore.server.tables.ContainerKeyIndexTests.testRecoveryTimeout(ContainerKeyIndexTests.java:590)
        Caused by:
        java.util.concurrent.TimeoutException: Table Segment 0 recovery timed out.
```
