### ISSUE TITLE
Intermittent test failure: testAppendWithOffset

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#4235]
**Problem description**

```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testAppendWithOffset FAILED
    java.lang.AssertionError: expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:68)
        at io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:46)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkAppendLeaks(StreamSegmentContainerTests.java:1907)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testAppendWithOffset(StreamSegmentContainerTests.java:772)
```

**Problem location**
Segment store tests.

**Suggestions for an improvement**
Determine the cause of the test failure and fix it.

**Comment by tkaitchuck** [comment]
This is still occuring:
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testAppendWithOffset FAILED
    java.util.concurrent.TimeoutException: Expected value: 0 observed: 1
        at io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:76)
        at io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:53)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkAppendLeaks(StreamSegmentContainerTests.java:2713)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testAppendWithOffset(StreamSegmentContainerTests.java:1046)
```
