### ISSUE TITLE
IO stalled for around 1hr and resumed with only writer events when Pravega cluster upgraded from 0.5.0 to 0.6.0

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#4249]
**Once Pravega Cluster was upgraded from `0.5.0-2299.8779f22` to `0.6.0-2378.3ae8db3` with IO running with `0.5.0-2299.8779f22`, Upgrade went successful but IO got halted for around 1 hr and once it resumed, only writer events were going on, Reader events were 0 **

For reference I am attaching Metrics screenshot for `Writer` and `reader` events.

Following `NPE` I am getting inside `controller` logs:
```
2019-10-04 09:02:53,670 8321751 [ControllerEventProcessors STARTING] WARN  i.p.c.s.e.ControllerEventProcessors - Error creating commit event processor group
java.lang.NullPointerException: null
        at io.pravega.client.stream.impl.ReaderGroupState$UpdateDistanceToTail.update(ReaderGroupState.java:866)
        at io.pravega.client.stream.impl.ReaderGroupState$ReaderGroupStateUpdate.applyTo(ReaderGroupState.java:575)
        at io.pravega.client.stream.impl.ReaderGroupState$ReaderGroupStateUpdate.applyTo(ReaderGroupState.java:569)
        at io.pravega.client.state.impl.StateSynchronizerImpl.applyUpdates(StateSynchronizerImpl.java:133)
        at io.pravega.client.state.impl.StateSynchronizerImpl.fetchUpdates(StateSynchronizerImpl.java:90)
        at io.pravega.client.state.impl.StateSynchronizerImpl.initialize(StateSynchronizerImpl.java:175)
        at io.pravega.client.admin.impl.ReaderGroupManagerImpl.createReaderGroup(ReaderGroupManagerImpl.java:98)
        at io.pravega.controller.eventProcessor.impl.EventProcessorGroupImpl.createIfNotExists(EventProcessorGroupImpl.java:107)
        at io.pravega.controller.eventProcessor.impl.EventProcessorGroupImpl.initialize(EventProcessorGroupImpl.java:95)
        at io.pravega.controller.eventProcessor.impl.EventProcessorSystemImpl.createEventProcessorGroup(EventProcessorSystemImpl.java:71)
        at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.lambda$initialize$24(ControllerEventProcessors.java:340)
        at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:173)
        at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.initialize(ControllerEventProcessors.java:339)
        at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.startUp(ControllerEventProcessors.java:145)
        at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
        at java.lang.Thread.run(Thread.java:748)
```
Following is the `Pravega` configuration:
```
root@osboxes:/home/osboxes# kubectl get po -o jsonpath={...image}|tr -s [[:space:]] "\n"|sort|uniq
bookkeeper:0.6.0-2378.3ae8db3
pravega:0.6.0-2378.3ae8db3
openjdk:8
pravega/pravega-operator:0.4.2-rc2
pravega/zookeeper:0.2.2
pravega/zookeeper-operator:0.2.2
quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
pravega-grafana:latest
pravega-influxdb:latest
```

Keeping K8 logs at shared location since the file size is more.

**Comment by Richa-Srivastava** [comment]
![reader events](https://user-images.githubusercontent.com/48912640/66196678-9503c780-e6b6-11e9-80a7-a699ed946745.png)
![Writer_event](https://user-images.githubusercontent.com/48912640/66196680-9503c780-e6b6-11e9-8d9e-5474a98d2525.png)

**Comment by shiveshr** [comment]
following is what ails controller and should also be ailing readers. 
```
java.lang.NullPointerException: null
        at io.pravega.client.stream.impl.ReaderGroupState$UpdateDistanceToTail.update(ReaderGroupState.java:866)
        at io.pravega.client.stream.impl.ReaderGroupState$ReaderGroupStateUpdate.applyTo(ReaderGroupState.java:575)
        at io.pravega.client.stream.impl.ReaderGroupState$ReaderGroupStateUpdate.applyTo(ReaderGroupState.java:569)
        at io.pravega.client.state.impl.StateSynchronizerImpl.applyUpdates(StateSynchronizerImpl.java:133)
        at io.pravega.client.state.impl.StateSynchronizerImpl.fetchUpdates(StateSynchronizerImpl.java:90)
        at io.pravega.client.state.impl.StateSynchronizerImpl.initialize(StateSynchronizerImpl.java:175)
        at io.pravega.client.admin.impl.ReaderGroupManagerImpl.createReaderGroup(ReaderGroupManagerImpl.java:98)
        at io.pravega.controller.eventProcessor.impl.EventProcessorGroupImpl.createIfNotExists(EventProcessorGroupImpl.java:107)
        at io.pravega.controller.eventProcessor.impl.EventProcessorGroupImpl.initialize(EventProcessorGroupImpl.java:95)
        at io.pravega.controller.eventProcessor.impl.EventProcessorSystemImpl.createEventProcessorGroup(EventProcessorSystemImpl.java:71)
        at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.lambda$initialize$24(ControllerEventProcessors.java:340)
        at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:173)
        at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.initialize(ControllerEventProcessors.java:339)
        at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.startUp(ControllerEventProcessors.java:145)
        at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
        at java.lang.Thread.run(Thread.java:748)
```
