### ISSUE TITLE
 Unable to create database 'pravega' in influxdb in Pravega external connectivity set up

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#4250]
Deployment details:-
```
bookkeeper:0.6.0-2378.3ae8db3
pravega:0.6.0-2378.3ae8db3
pravega-operator:0.4.2-rc2
pravega/zookeeper:0.2.3
pravega/zookeeper-operator:0.2.2
raulgracia/pravega-grafana:latest
raulgracia/pravega-influxdb:latest
```

Environment details: PKS / K8 with medium cluster:
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
5 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```

Influx db and grafana are set up:-
```
kubectl create deployment influxdb --image=raulgracia/pravega-influxdb:latest
kubectl create deployment grafana --image=raulgracia/pravega-grafana:latest
kubectl expose deployment grafana --port=3000 --target-port=3000 --type=LoadBalancer
```
$kubectl get pod influxdb-84bcfc9789-glsth -o wide
```
NAME                        READY   STATUS    RESTARTS   AGE   IP             NODE                                   NOMINATED NODE   READINESS GATES
influxdb-84bcfc9789-glsth   1/1     Running   0          8h    172.28.12.10   f2be1982-e3f8-479f-94be-ef2c3287d9f9   <none>           <none>
```

Modify the pravega manifest with influx db IP :- 172.28.12.10
   ```
metrics.dynamicCacheSize: "100000"
     metrics.enableStatistics: "true"
     metrics.enableStatsDReporter: "false"
     metrics.statsdHost: "telegraph.default"
     metrics.statsdPort: "8125"
     metrics.enableInfluxDBReporter: "true"
     metrics.outputFrequencySeconds: "10"
     metrics.influxDBURI: "http://172.28.12.10:8086"   <--- Influxdb IP here
     controller.metrics.dynamicCacheSize: "100000"
     controller.metrics.enableStatistics: "true"
     controller.metrics.enableStatsDReporter: "false"
     controller.metrics.statsdHost: "telegraph.default"
     controller.metrics.statsdPort: "8125"
     controller.metrics.enableInfluxDBReporter: "true"
     controller.metrics.outputFrequencySeconds: "10"
     controller.metrics.influxDBURI: "http://172.28.12.10:8086"   <-- Influxdb IP
``` 

Deploy pravega with External connectivity using Load Balancer:-
$kubectl get svc
```
NAME                                    TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                          AGE
grafana                                 LoadBalancer   10.100.200.168   10.240.119.88    3000:31143/TCP                   8h
kubernetes                              ClusterIP      10.100.200.1     <none>           443/TCP                          11d
pravega-bookie-headless                 ClusterIP      None             <none>           3181/TCP                         4h55m
pravega-pravega-controller              LoadBalancer   10.100.200.98    10.240.119.245   10080:31420/TCP,9090:30564/TCP   4h55m
pravega-pravega-segmentstore-0          LoadBalancer   10.100.200.178   10.240.119.246   12345:31337/TCP                  4h55m
pravega-pravega-segmentstore-1          LoadBalancer   10.100.200.90    10.240.119.249   12345:30912/TCP                  4h55m
pravega-pravega-segmentstore-2          LoadBalancer   10.100.200.162   10.240.119.251   12345:30649/TCP                  4h55m
pravega-pravega-segmentstore-headless   ClusterIP      None             <none>           12345/TCP                        4h55m
pravega-webhook-svc                     ClusterIP      10.100.200.24    <none>           443/TCP                          4h55m
pravega-zk-client                       ClusterIP      10.100.200.87    <none>           2181/TCP                         5h2m
pravega-zk-headless                     ClusterIP      None             <none>           2888/TCP,3888/TCP                5h2m

```

Getting this error in controller logs:-
```
2019-10-04 13:44:17,058 20436 [influx-metrics-publisher] ERROR i.m.influx.InfluxMeterRegistry - unable to create database 'pravega'
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
        at io.micrometer.core.ipc.http.HttpUrlConnectionSender.send(HttpUrlConnectionSender.java:94)
        at io.micrometer.core.ipc.http.HttpSender$Request$Builder.send(HttpSender.java:284)
        at io.micrometer.influx.InfluxMeterRegistry.createDatabaseIfNecess
```

Due to this , Not able to create data source and influx db credentials in grafana.

**Comment by Raghuveera-Rao** [comment]
I will share logs separately in corresponding JIRA issue. Logs size is huge, can't attach here

**Comment by kevinhan88** [comment]
@Raghuveera-Rao please share the cluster name and the user/password to access Grafana

**Comment by andreipaduroiu** [comment]
@Raghuveera-Rao Please do not share it on GitHub. Use a direct message.

**Comment by Raghuveera-Rao** [comment]
> @Raghuveera-Rao please share the cluster name and the user/password to access Grafana

I shared logs in jira issue (PRAVEGA-314)

**Comment by kevinhan88** [comment]
Observed different Influxdb IP in controller logs than the one deployed, mis-config issue.
