### ISSUE TITLE
Readers failed while running mid-scale longevity on PKS cluster

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#4272]
**Problem description**
While running mid-scale longevity on PKS cluster, Readers failed (0/8) from worker pods after around1.30hr of run. Following Exception I am getting inside Longevity Manager pod:
```
NFO  [2019-10-11 06:41:55,051] io.pravega.longevity.testmanager.manager.TestPerformanceCollector: Received Error From task taskID : null
io.pravega.client.stream.TruncatedDataException
        at io.pravega.client.stream.impl.EventStreamReaderImpl.handleSegmentTruncated(EventStreamReaderImpl.java:302)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:137)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:104)
        at io.pravega.longevity.testworker.workers.readers.PravegaReader.start(PravegaReader.java:99)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
Getting following info during the same timeframe inside bookkeeper logs:
```
2019-10-11 06:41:07,971 - INFO  - [SortedLedgerStorage-0:SortedLedgerStorage$1@211] - Started flushing mem table.
2019-10-11 06:41:08,227 - INFO  - [GarbageCollectorThread-8-1:EntryLogCompactor@59] - Removing entry log 2841 after compaction
2019-10-11 06:41:08,290 - INFO  - [GarbageCollectorThread-8-1:GarbageCollectorThread@514] - Removing entry log metadata for 2841
2019-10-11 06:41:08,290 - INFO  - [GarbageCollectorThread-8-1:GarbageCollectorThread@482] - Compaction: entry log usage buckets[10% 20% 30% 40% 50% 60% 70% 80% 90% 100%] = [0, 17, 9, 10, 11, 3, 1, 6, 1, 1]
2019-10-11 06:41:08,291 - INFO  - [GarbageCollectorThread-8-1:GarbageCollectorThread@567] - Extracting entry log meta from entryLogId: 2851
2019-10-11 06:41:08,297 - INFO  - [GarbageCollectorThread-8-1:GarbageCollectorThread@567] - Extracting entry log meta from entryLogId: 2852
2019-10-11 06:41:08,299 - INFO  - [GarbageCollectorThread-8-1:GarbageCollectorThread@567] - Extracting entry log meta from entryLogId: 2853
2019-10-11 06:41:08,303 - INFO  - [GarbageCollectorThread-8-1:GarbageCollectorThread@567] - Extracting entry log meta from entryLogId: 2854
2019-10-11 06:41:08,306 - INFO  - [GarbageCollectorThread-8-1:GarbageCollectorThread@567] - Extracting entry log meta from entryLogId: 2855
```
Attaching the Metrics screenshot:
![image](https://user-images.githubusercontent.com/48912640/66664978-323c9e00-ec6b-11e9-9618-0a2f5ab58776.png)
Here I am not getting any data for `Read Bytes` under `Stream Dashboard`.
![image](https://user-images.githubusercontent.com/48912640/66664994-38cb1580-ec6b-11e9-9a6f-8f1f7855bbbb.png)
![image](https://user-images.githubusercontent.com/48912640/66665018-41bbe700-ec6b-11e9-8da5-7c978ed3e0b1.png)
![image](https://user-images.githubusercontent.com/48912640/66665030-47b1c800-ec6b-11e9-85c5-7cef562b55cd.png)
External IP for this metrics is: http://10.240.119.101:3030
Following is the Pravega config detail:
```
root@osboxes:/usr/local/go/bin/src/github.com# kubectl get po -o jsonpath={...image}|tr -s [[:space:]] "\n"|sort|uniq
bookkeeper:0.6.0-2378.3ae8db3
pravega:0.6.0-2378.3ae8db3
pravega/pravega-operator:0.4.2-rc2
pravega/zookeeper:0.2.3
pravega/zookeeper-operator:0.2.2
quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
pravega-grafana:latest
pravega-influxdb:latest
```
Pods status:
```
root@osboxes:/usr/local/go/bin/src/github.com# k get po --all-namespaces
NAMESPACE           NAME                                                            READY   STATUS      RESTARTS   AGE
default             grafana-5c4689f447-q4cvl                                        1/1     Running     0          2d4h
default             influxdb-84bcfc9789-sz8gt                                       1/1     Running     0          2d4h
default             pravega-bookie-0                                                1/1     Running     0          2d3h
default             pravega-bookie-1                                                1/1     Running     1          2d3h
default             pravega-bookie-2                                                1/1     Running     0          2d3h
default             pravega-bookie-3                                                1/1     Running     0          2d3h
default             pravega-operator-5f45c98857-g5cbj                               1/1     Running     0          2d3h
default             pravega-pravega-controller-5d84d58f8b-dhjjj                     1/1     Running     0          2d3h
default             pravega-pravega-controller-5d84d58f8b-rpm4t                     1/1     Running     0          2d3h
default             pravega-pravega-segmentstore-0                                  1/1     Running     0          2d3h
default             pravega-pravega-segmentstore-1                                  1/1     Running     0          2d3h
default             pravega-pravega-segmentstore-2                                  1/1     Running     0          2d3h
default             pravega-zk-0                                                    1/1     Running     0          2d4h
default             pravega-zk-1                                                    1/1     Running     0          2d4h
default             pravega-zk-2                                                    1/1     Running     0          2d3h
default             pravega-zk-3                                                    1/1     Running     0          2d3h
default             pravega-zk-4                                                    1/1     Running     0          2d3h
default             shaka-zulu-nfs-client-provisioner-755996548f-6rt6v              1/1     Running     0          2d3h
default             zookeeper-operator-5946b99494-s7hm6                             1/1     Running     0          2d4h
kube-system         coredns-95489c5c9-64nws                                         1/1     Running     0          2d6h
kube-system         coredns-95489c5c9-rhrtt                                         1/1     Running     0          2d6h
kube-system         coredns-95489c5c9-sjlcw                                         1/1     Running     0          2d6h
kube-system         kubernetes-dashboard-558689fc66-g4wxk                           1/1     Running     0          2d6h
kube-system         metrics-server-867b8fdb7d-gd8c6                                 1/1     Running     0          2d6h
kube-system         tiller-deploy-59cff884b4-w6vdx                                  1/1     Running     0          2d3h
pks-system          cert-generator-dea87263fc8e6d3a2a122f5f5e31b36afbeef369-m7995   0/1     Completed   0          2d6h
pks-system          event-controller-646d78b9b8-7rlhl                               2/2     Running     0          2d6h
pks-system          fluent-bit-524z9                                                2/2     Running     0          2d6h
pks-system          fluent-bit-k588r                                                2/2     Running     0          2d6h
pks-system          fluent-bit-km5mq                                                2/2     Running     0          2d6h
pks-system          fluent-bit-lnnjn                                                2/2     Running     0          2d6h
pks-system          fluent-bit-mhgsm                                                2/2     Running     0          2d6h
pks-system          metric-controller-c998cb5bf-676qn                               1/1     Running     0          2d6h
pks-system          observability-manager-64f749cd4c-l646j                          1/1     Running     0          2d6h
pks-system          sink-controller-6774fd95f7-b9qkk                                1/1     Running     0          2d6h
pks-system          telegraf-6ng84                                                  1/1     Running     0          2d6h
pks-system          telegraf-h5n6j                                                  1/1     Running     0          2d6h
pks-system          telegraf-jc6fw                                                  1/1     Running     0          2d6h
pks-system          telegraf-llt5v                                                  1/1     Running     0          2d6h
pks-system          telegraf-zfgtk                                                  1/1     Running     0          2d6h
pks-system          telemetry-agent-858446f4ff-whv62                                2/2     Running     0          2d6h
pks-system          validator-6b677f49d4-hbdpb                                      1/1     Running     0          2d6h
pravega-longevity   mid-scale-manager-7b9f79dccd-q627s                              1/1     Running     0          9h
pravega-longevity   mid-scale-worker-56877b6fcc-c78nv                               1/1     Running     0          9h
pravega-longevity   mid-scale-worker-56877b6fcc-hflqw                               1/1     Running     0          9h
pravega-longevity   mid-scale-worker-56877b6fcc-mwgzd                               1/1     Running     0          9h
pravega-longevity   mid-scale-worker-56877b6fcc-zjkw5                               1/1     Running     0          9h
```
K8 logs details are available in Jira: PRAVEGA-325

**Comment by shrids** [comment]
***Summary:***
The longevity test was run against a Stream with pre-existing events where the stream's retention policy is set to 60 mins.  
The readers fail with `TruncatedDataException` in longevity run within 6 mins of the run since the Stream is truncated. Invoking the `readNextEvent()` against would cause the reader 
to read events from the stream post truncation.

Given that the stream already had 1 hour of data and readers of one of the worker pods were not reading events the readers lagged behind the writers and were playing catch up. Hence the `TruncatedDataException` was seen. 

***Details:***

- The manager logs indicate the longevity run was started @ `2019-10-11 06:36:16,412`

```
INFO  [2019-10-11 06:36:16,412] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@455f4483{/,null,AVAILABLE}
```

- The test creates a stream called `longevity/midScale`. The logs indicate that the stream was already present (and it did have data, proof below)

```
INFO  [2019-10-11 06:36:18,245] io.pravega.client.admin.impl.StreamManagerImpl: Creating scope/stream: longevity/midScale with configuration: StreamConfiguration(scalingPolicy=ScalingPolicy(scaleType=BY_RATE_IN_EVENTS_PER_SEC, targetRate=2000, scaleFactor=2, minNumSegments=8), retentionPolicy=RetentionPolicy(retentionType=TIME, retentionParam=3600000), timestampAggregationTimeout=0)
WARN  [2019-10-11 06:36:18,790] io.pravega.client.stream.impl.ControllerImpl: [requestId=-6711476645321243824] Stream already exists: midScale
INFO  [2019-10-11 06:36:18,790] io.pravega.longevity.utils.PravegaStreamHelper: Created Stream longevity/midScale with 8 minimal segments
```

-  The test starts 4 worker pods and each worker pods creates 4 writers and 8 readers.
- All the 4 workers pods attempt to write to the same stream. i.e. there are 16 writers pumping events into this stream.
- The readers are configured to read from the start of the stream (which was already there) upto the tail of the stream.

- Observing that readers from one of the worker pods is not able to read events at all...
```
INFO  [2019-10-11 06:41:10,259] io.pravega.longevity.utils.PerformanceUtils: New runtime for b6538c53-be64-458b-be9c-9287cf944ce1  Running for 4m 42s
INFO  [2019-10-11 06:41:10,259] io.pravega.longevity.utils.PerformanceUtils: Dumping stats for stream longevity/midScale
INFO  [2019-10-11 06:41:10,259] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:2,454,211, events/sec:10,225, KB/sec:7839.9023
INFO  [2019-10-11 06:41:10,259] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-10-11 06:41:10,259] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 127, average block time (ms): 260
INFO  [2019-10-11 06:41:10,259] io.pravega.longevity.utils.PerformanceUtils: Readers (8/8): events:0, events/sec:0, KB/sec:0.0
``` 
Other worker pods have been able to read  4 million events during that time period.
e.g:
```
INFO  [2019-10-11 06:41:27,874] io.pravega.longevity.utils.PerformanceUtils: Readers (8/8): events:4,796,336, events/sec:15,987, KB/sec:12257.562
INFO  [2019-10-11 06:41:28,349] io.pravega.longevity.utils.PerformanceUtils: Readers (8/8): events:5,711,983, events/sec:19,039, KB/sec:14597.805       
```

- Given the above scenario the readers were playing catch up with the events in the stream (which previously existed) the controller trunctated the stream after the retention policy of 60 mins
This leads to the reader facing truncatedException within 5 mins of the experiment.
```
INFO  [2019-10-11 06:41:55,051] io.pravega.longevity.testmanager.manager.TestPerformanceCollector: Received Error From task taskID : null                                                              io.pravega.client.stream.TruncatedDataException                                                                                                                                                                at io.pravega.client.stream.impl.EventStreamReaderImpl.handleSegmentTruncated(EventStreamReaderImpl.java:302)                                                                                          at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:137)                                                                                           at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:104)                                                                                                   at io.pravega.longevity.testworker.workers.readers.PravegaReader.start(PravegaReader.java:99)                             
```

- Controller logs processing truncation of stream
```
2019-10-11 06:41:52,212 154511751 [controllerpool-10] INFO  i.p.c.s.e.r.TruncateStreamTask - [requestId=-4661560491044916021] Truncating stream longevity/midScale at stream cut: {5446018533281=1271608772, 5437428598687=1268940618, 5411658794904=2106636853, 5424543696796=1587289545, 5428838664093=1722590723, 5450313500578=1652241220, 5433133631390=1361683798, 5441723565984=1069337805} 
```

- Checked the worker logs and do not see the reason why one worker pod was able to read the events.

**Comment by shrids** [comment]
Closing this issue since throwing a `TruncatedDataException` is part of the reader APIs and given the test environment (described in the previous comment), it is expected.
