### ISSUE TITLE
Restarts and Error :Unexpected exception, exiting abnormally while zookeeper instances scaled up from 3 to 5 

### ISSUE THREAD

**Issue by ipsDocker** [pravega/pravega#4289]
**Problem description**
```
Had a pravega installation with 7 zookeeper . 
scaled down zk from 7 to 5 and then 3 .
IO was running fine .No pod restarts were observed.
Later on scaled up from 3 instances of zookeeper to 5 instances .
observed zookeeper pods restarts 
```
error observered:
```
2019-10-17 10:05:58,998 [myid:6] - ERROR [main:QuorumPeerMain@101] - Unexpected exception, exiting abnormally
java.lang.RuntimeException: My id 6 not in the peer list
        at org.apache.zookeeper.server.quorum.QuorumPeer.start(QuorumPeer.java:903)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:205)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:123)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)
```
**Problem location**
```
K8 log location will be mentioned in the related jira and updated here
```
cluster pod state
```
root@osboxes:~/long# kubectl get po --all-namespaces                                     
NAMESPACE           NAME                                                            READY   STATUS      RESTARTS   AGE
default             pravega-bookie-0                                                1/1     Running     0          26h
default             pravega-bookie-1                                                1/1     Running     0          26h
default             pravega-bookie-2                                                1/1     Running     0          26h
default             pravega-bookie-3                                                1/1     Running     0          26h
default             pravega-operator-5f45c98857-q5gbn                               1/1     Running     0          26h
default             pravega-pravega-controller-9dbc95bb-kzfmw                       1/1     Running     0          26h
default             pravega-pravega-controller-9dbc95bb-tp65l                       1/1     Running     2          26h
default             pravega-pravega-segmentstore-0                                  1/1     Running     0          26h
default             pravega-pravega-segmentstore-1                                  1/1     Running     0          26h
default             pravega-pravega-segmentstore-2                                  1/1     Running     0          26h
default             pravega-pravega-segmentstore-3                                  1/1     Running     0          25h
default             pravega-pravega-segmentstore-4                                  1/1     Running     0          25h
default             pravega-zk-0                                                    1/1     Running     0          26h
default             pravega-zk-1                                                    1/1     Running     0          26h
default             pravega-zk-2                                                    1/1     Running     0          26h
default             pravega-zk-3                                                    1/1     Running     1          105m
default             pravega-zk-4                                                    1/1     Running     1          104m
default             pravega-zk-5                                                    1/1     Running     1          56m
default             pravega-zk-6                                                    1/1     Running     1          56m
default             shaka-zulu-nfs-client-provisioner-755996548f-zgzx8              1/1     Running     0          26h
default             zookeeper-operator-b7c699ffb-srs8x                              1/1     Running     0          26h
```
pravega image details
```
osboxes@osboxes:~$ kubectl get po -o jsonpath={...image}|tr -s [[:space:]] "\n"|sort|uniq
devops-repo.isus.emc.com:8116/nautilus/bookkeeper:0.6.0-2391.97363b3
devops-repo.isus.emc.com:8116/nautilus/pravega:0.6.0-2391.97363b3
pravega/pravega-operator:0.4.2-rc2
pravega/zookeeper:0.2.4
pravega/zookeeper-operator:0.2.4
quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
```

**Comment by pbelgundi** [comment]
This is a zookeeper operator issue and should not be in Pravega queue.
Closing this please refer issue #[94 ](https://github.com/pravega/zookeeper-operator/issues/94)on zookeeper-operator instead.
