### ISSUE TITLE
ERROR i.p.c.s.e.r.CommitRequestHandler - Exception while attempting to commit transaction

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#4290]
Deployment details:-

```
bookkeeper:0.6.0-2391.97363b3
pravega:0.6.0-2391.97363b3
openjdk:8
pravega/pravega-operator:0.4.2-rc2
pravega/zookeeper:0.2.4
pravega/zookeeper-operator:0.2.4
quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
raulgracia/pravega-grafana:latest
raulgracia/pravega-influxdb:latest
```

Environment details: PKS / K8 with medium cluster:

```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
5 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Influx db and grafana are set up:-

```
kubectl create deployment influxdb --image=raulgracia/pravega-influxdb:latest
kubectl create deployment grafana --image=raulgracia/pravega-grafana:latest
kubectl expose deployment grafana --port=3000 --target-port=3000 --type=LoadBalancer
```

Run longevity small-scale-tx-bytes . It is running in scope longevity

Seeing this error in controller log :-
```
2019-10-17 05:38:11,960 48480786 [controllerpool-14] ERROR i.p.c.s.e.r.CommitRequestHandler - Exception while attempting to commit transaction on stream longevity/smallScaleTxBytes
java.util.concurrent.CompletionException: java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$WriteConflictException: updateEntry: key: 999cb6ac-b109-4942-8064-770094f0939d table: _system/_tables/longevity/smallScaleTxBytes/writersPositions.#.466b8e11-882a-418d-87fa-c2f81b6d4b99
        at io.pravega.common.concurrent.Futures.lambda$exceptionallyExpecting$6(Futures.java:301)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$6(Retry.java:242)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at io.pravega.client.netty.impl.RawClient.reply(RawClient.java:104)
        at io.pravega.client.netty.impl.RawClient.access$300(RawClient.java:36)
        at io.pravega.client.netty.impl.RawClient$ResponseProcessor.process(RawClient.java:63)
        at io.pravega.client.netty.impl.FlowHandler.lambda$channelRead$2(FlowHandler.java:260)
        at java.util.Optional.ifPresent(Optional.java:159)
        at io.pravega.client.netty.impl.FlowHandler.channelRead(FlowHandler.java:258)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)

```

**Comment by shiveshr** [comment]
Opened #4291 which fixes the root cause of the harmless error we see.
