### ISSUE TITLE
Overriding Service Type for Controller=ClusterIP and SS=NodePort:- I/O not working 

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#4297]
Environment details: PKS / K8 with medium cluster:
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
5 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```

Deployment details:

```
bookkeeper:0.6.0-2391.97363b3
pravega:0.6.0-2391.97363b3
openjdk:8
pravega/pravega-operator:0.4.2-rc2
pravega/zookeeper:0.2.4
pravega/zookeeper-operator:0.2.4
```
Pravega deployed with external connectivity Overriding service types.
```
externalAccess:
    enabled: true
    type: LoadBalancer
     . . .

pravega:
    controllerExtServiceType: ClusterIP
    segmentStoreExtServiceType: NodePort
```

Pravega deployed properly
$kubectl get all -l pravega_cluster=pravega                                                                               

```
NAME                                              READY   STATUS    RESTARTS   AGE
pod/pravega-bookie-0                              1/1     Running   0          51m
pod/pravega-bookie-1                              1/1     Running   0          51m
pod/pravega-bookie-2                              1/1     Running   0          51m
pod/pravega-bookie-3                              1/1     Running   1          51m
pod/pravega-pravega-controller-7d9fbf86d6-f2j7v   1/1     Running   0          51m
pod/pravega-pravega-controller-7d9fbf86d6-fzqz7   1/1     Running   0          51m
pod/pravega-pravega-segmentstore-0                1/1     Running   0          51m
pod/pravega-pravega-segmentstore-1                1/1     Running   0          49m
pod/pravega-pravega-segmentstore-2                1/1     Running   0          48m

NAME                                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)              AGE
service/pravega-bookie-headless                 ClusterIP   None             <none>        3181/TCP             51m
service/pravega-pravega-controller              ClusterIP   10.100.200.137   <none>        10080/TCP,9090/TCP   51m
service/pravega-pravega-segmentstore-0          NodePort    10.100.200.37    <none>        12345:32631/TCP      51m
service/pravega-pravega-segmentstore-1          NodePort    10.100.200.64    <none>        12345:32632/TCP      51m
service/pravega-pravega-segmentstore-2          NodePort    10.100.200.52    <none>        12345:31800/TCP      51m
service/pravega-pravega-segmentstore-headless   ClusterIP   None             <none>        12345/TCP            51m

NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/pravega-pravega-controller   2/2     2            2           51m

NAME                                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/pravega-pravega-controller-7d9fbf86d6   2         2         2       51m

NAME                                            READY   AGE
statefulset.apps/pravega-bookie                 4/4     51m
statefulset.apps/pravega-pravega-segmentstore   3/3     51m


```

Error in controller:-
```
2019-10-18 11:51:35,480 1879256 [nioEventLoopGroup-2-4] WARN  i.p.client.netty.impl.FlowHandler - Keep alive failed, killing connection 172.24.0.7 due to java.nio.channels.NotYetConnectedException
2019-10-18 11:51:35,480 1879256 [nioEventLoopGroup-2-4] INFO  i.p.client.netty.impl.FlowHandler - Closing connection with endpoint 172.24.0.7 on channel [id: 0x7bd2788c]
2019-10-18 11:51:35,480 1879256 [nioEventLoopGroup-2-4] WARN  i.p.client.netty.impl.RawClient - Processing failure: 
io.pravega.shared.protocol.netty.ConnectionFailedException: io.pravega.client.stream.impl.ConnectionClosedException
        at io.pravega.client.netty.impl.FlowHandler.lambda$invokeProcessingFailureForAllFlows$3(FlowHandler.java:277)
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
        at io.pravega.client.netty.impl.FlowHandler.invokeProcessingFailureForAllFlows(FlowHandler.java:274)
        at io.pravega.client.netty.impl.FlowHandler.close(FlowHandler.java:295)
        at io.pravega.client.netty.impl.FlowHandler$KeepAliveTask.run(FlowHandler.java:315)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:133)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.client.stream.impl.ConnectionClosedException: null
        ... 10 common frames omitted
2019-10-18 11:51:35,480 1879256 [nioEventLoopGroup-2-4] WARN  i.p.client.netty.impl.FlowHandler - 1 AppendBatchSizeTrackers are not closed
2019-10-18 11:51:35,480 1879256 [nioEventLoopGroup-2-4] WARN  i.p.controller.server.SegmentHelper - [requestId=996432412672] Connection dropped
2019-10-18 11:51:35,480 1879256 [nioEventLoopGroup-2-4] INFO  i.p.client.netty.impl.FlowHandler - Connection drop observed with endpoint 172.24.0.7
2019-10-18 11:51:40,131 1883907 [controllerpool-4] INFO  i.p.c.netty.impl.ConnectionPoolImpl - Creating a new connection to PravegaNodeUri(endpoint=172.24.0.7, port=32631)
2019-10-18 11:51:40,131 1883907 [controllerpool-4] INFO  i.p.client.netty.impl.FlowHandler - Creating Flow 234 for endpoint 172.24.0.7. The current Channel is null.
2019-10-18 11:51:40,133 1883909 [nioEventLoopGroup-2-2] INFO  i.p.client.netty.impl.FlowHandler - Connection established with endpoint 172.24.0.7 on channel [id: 0xcf238112]
2019-10-18 11:51:41,881 1885657 [controllerpool-7] INFO  i.p.c.netty.impl.ConnectionPoolImpl - Creating a new connection to PravegaNodeUri(endpoint=172.24.0.7, port=32631)
2019-10-18 11:51:41,881 1885657 [controllerpool-7] INFO  i.p.client.netty.impl.FlowHandler - Creating Flow 235 for endpoint 172.24.0.7. The current Channel is null.
2019-10-18 11:51:41,882 1885658 [nioEventLoopGroup-2-3] INFO  i.p.client.netty.impl.FlowHandler - Connection established with endpoint 172.24.0.7 on channel [id: 0xf2bb8914]
2019-10-18 11:51:43,655 1887431 [controllerpool-8] WARN  i.p.c.f.ControllerClusterListener - java.lang.RuntimeException: sweeper class io.pravega.controller.task.Stream.TxnSweeper not ready


```

Controller REsT api is not working
$kubectl exec pravega-bookie-0 -- curl -s -X GET 'http://10.100.200.164:10080/v1/scopes/' -H 'accept: application/json'

```
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Length: 0
```

I/O tried to run with benchmark failed.
Benchmark is inside a pod
$./bin/pravega-benchmark -consumers 1 -controller tcp://10.100.200.137:9090 -events 100 -producers 1 -readWatermarkPeriodMillis 1000 -scope Scope1 -segments 10 -size 100 -stream test1 -time 300 -writeWatermarkPeriodMillis 100 

```
ad.java:748)2019-10-18 12:01:57:321 +0000 [main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.100.200.137:9090
2019-10-18 12:01:57:326 +0000 [main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.100.200.137:9090
2019-10-18 12:01:57:359 +0000 [main] INFO io.pravega.client.admin.impl.StreamManagerImpl - Creating scope: Scope1
2019-10-18 12:01:57:374 +0000 [StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=-7226352989621400702] Tagging client request (createScope-Scope1).
2019-10-18 12:01:57:415 +0000 [StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[[/10.100.200.137:9090]/{}]]
2019-10-18 12:08:20:636 +0000 [grpc-default-executor-1] WARN io.pravega.client.stream.impl.ControllerImpl - [requestId=-7226352989621400702] Failed to create scope: Scope1
2019-10-18 12:08:20:636 +0000 [grpc-default-executor-1] WARN io.pravega.client.stream.impl.ControllerImpl - [requestId=-7226352989621400702] createScope failed: 
java.util.concurrent.CompletionException: io.pravega.client.stream.impl.ControllerFailureException: Failed to create scope: Scope1
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at io.pravega.client.stream.impl.ControllerImpl$RPCAsyncCallback.onCompleted(ControllerImpl.java:1147)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:432)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.client.stream.impl.ControllerFailureException: Failed to create scope: Scope1
        at io.pravega.client.stream.impl.ControllerImpl.lambda$createScope$2(ControllerImpl.java:246)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        ... 30 more
io.pravega.client.stream.impl.ControllerFailureException: Failed to create scope: Scope1
        at io.pravega.client.stream.impl.ControllerImpl.lambda$createScope$2(ControllerImpl.java:246)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at io.pravega.client.stream.impl.ControllerImpl$RPCAsyncCallback.onCompleted(ControllerImpl.java:1147)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:432)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thre
```

**Comment by kevinhan88** [comment]
Potential inconsistency between Pravega-operator scripts and Readme.md, on the following two properties:
controller*ExtServiceType <-- is this "controllerExternal*ServiceType"?
segmentStore*ExtServiceType <-- is this "segmentStoreExternal*ServiceType"?

QE has been asked to double confirm and re-test.

**Comment by Raghuveera-Rao** [comment]
@pbelgundi  Please confirm External service type string is proper.

**Comment by pbelgundi** [comment]
I don't see any issue with `keynames` for external service types.
Operator documentation and code are consistent and as specified in the test manifest, the right types of services have been created for Controller and Segment Store :
```
service/pravega-pravega-controller              ClusterIP   10.100.200.137   <none>        10080/TCP,9090/TCP   51m
service/pravega-pravega-segmentstore-0          NodePort    10.100.200.37    <none>        12345:32631/TCP      51m
service/pravega-pravega-segmentstore-1          NodePort    10.100.200.64    <none>        12345:32632/TCP      51m
service/pravega-pravega-segmentstore-2          NodePort    10.100.200.52    <none>        12345:31800/TCP      51m
```
If I understand it correctly, Issue here is that after the services have come up, connect to Controller service is failing with the stated exception.
@Raghuveera-Rao please confirm if this is the problem to be addressed here.

**Comment by Raghuveera-Rao** [comment]
yes.. I/O is failing.. 'Failed to create scope: Scope1'..

**Comment by kevinhan88** [comment]
Assign this to @shiveshr

**Comment by shiveshr** [comment]
can you share controller logs for the requests you are sending. Is controller able to talk to segment store correctly?

**Comment by Raghuveera-Rao** [comment]
logs attached in jira
