### ISSUE TITLE
Pravega cluster uninstall (without zookeeper uninstall) and reinstall pravega :- not able to create scope and  I/O fails

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#4300]
Environment details: PKS / K8 with medium cluster:
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
5 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```

Deployment details:
```
bookkeeper:0.6.0-2391.97363b3
pravega:0.6.0-2391.97363b3
openjdk:8
pravega/pravega-operator:0.4.2-rc2
pravega/zookeeper:0.2.4
pravega/zookeeper-operator:0.2.4
```

Pravega installed successfully using kubectl (not with helm charts) and read/write I/O also went fine.
$kubectl get pods
```
pravega-benchmark                                    1/1     Running   0          22h
pravega-bookie-0                                     1/1     Running   0          5m47s
pravega-bookie-1                                     1/1     Running   0          5m47s
pravega-bookie-2                                     1/1     Running   0          5m47s
pravega-bookie-3                                     1/1     Running   0          5m47s
pravega-operator-5f45c98857-w6qh2                    1/1     Running   0          6m6s
pravega-pravega-controller-9dbc95bb-h4wvb            1/1     Running   0          5m47s
pravega-pravega-controller-9dbc95bb-lfgs8            1/1     Running   0          5m47s
pravega-pravega-segmentstore-0                       1/1     Running   0          5m47s
pravega-pravega-segmentstore-1                       1/1     Running   0          4m8s
pravega-pravega-segmentstore-2                       1/1     Running   0          3m39s
pravega-zk-0                                         1/1     Running   0          9m31s
pravega-zk-1                                         1/1     Running   0          8m50s
pravega-zk-2                                         1/1     Running   0          8m12s
shaka-zulu-nfs-client-provisioner-755996548f-8klmp   1/1     Running   0          6m30s
zookeeper-operator-b7c699ffb-h9mgr                   1/1     Running   0          9m46s
```

Logs for before uninstall will be attached.

I uninstalled only pravega cluster :-
$kubectl delete -f pravega.yaml
$kubectl delete -f pvc.yaml
$kubectl delete -f deploy

This is POD config after uninstall:-
$kubectl get pods
```
pravega-benchmark                                    1/1     Running   0          22h
pravega-zk-0                                         1/1     Running   0          25m
pravega-zk-1                                         1/1     Running   0          25m
pravega-zk-2                                         1/1     Running   0          24m
shaka-zulu-nfs-client-provisioner-755996548f-8klmp   1/1     Running   0          22m
zookeeper-operator-b7c699ffb-h9mgr                   1/1     Running   0          26m
```

$kubectl get svc
```
kubernetes            ClusterIP   10.100.200.1     <none>        443/TCP             28h
pravega-webhook-svc   ClusterIP   10.100.200.226   <none>        443/TCP             23m
pravega-zk-client     ClusterIP   10.100.200.122   <none>        2181/TCP            26m
pravega-zk-headless   ClusterIP   None             <none>        2888/TCP,3888/TCP   26m
```

Also, deleted svc of webhook of pravega operator(as it was still showing up)-
$kubectl delete svc pravega-webhook-svc

$kubectl get pvc
```
data-pravega-zk-0                       Bound    pvc-e39b701f-f255-11e9-8f07-005056b626c0   20Gi       RWO            standard       27m
data-pravega-zk-1                       Bound    pvc-fc062048-f255-11e9-8f07-005056b626c0   20Gi       RWO            standard       26m
data-pravega-zk-2                       Bound    pvc-128539da-f256-11e9-8f07-005056b626c0   20Gi       RWO            standard       25m
pvc-shaka-zulu-nfs-client-provisioner   Bound    pv-shaka-zulu-nfs-client-provisioner       10Mi       RWO                           24m
```

--------------------------------------------------------------------

Install pravega cluster using kubectl

$kubectl create -f deploy
$kubectl create -f pvc.yaml
$kubectl create -f pravega.yaml

$kubectl get pods
```
pravega-benchmark                                    1/1     Running   0          22h
pravega-bookie-0                                     1/1     Running   0          2m22s
pravega-bookie-1                                     1/1     Running   0          2m22s
pravega-bookie-2                                     1/1     Running   0          2m22s
pravega-bookie-3                                     1/1     Running   0          2m22s
pravega-operator-5f45c98857-24cbk                    1/1     Running   0          3m24s
pravega-pravega-controller-9dbc95bb-688n8            1/1     Running   0          2m22s
pravega-pravega-controller-9dbc95bb-7p24c            1/1     Running   0          2m22s
pravega-pravega-segmentstore-0                       1/1     Running   0          2m21s
pravega-pravega-segmentstore-1                       1/1     Running   0          74s
pravega-pravega-segmentstore-2                       1/1     Running   0          50s
pravega-zk-0                                         1/1     Running   0          31m
pravega-zk-1                                         1/1     Running   0          30m
pravega-zk-2                                         1/1     Running   0          30m
shaka-zulu-nfs-client-provisioner-755996548f-8klmp   1/1     Running   0          28m
zookeeper-operator-b7c699ffb-h9mgr                   1/1     Running   0          31m

```

$kubectl get svc
```
kubernetes                              ClusterIP   10.100.200.1     <none>        443/TCP              29h
pravega-bookie-headless                 ClusterIP   None             <none>        3181/TCP             3m10s
pravega-pravega-controller              ClusterIP   10.100.200.155   <none>        10080/TCP,9090/TCP   3m10s
pravega-pravega-segmentstore-headless   ClusterIP   None             <none>        12345/TCP            3m10s
pravega-webhook-svc                     ClusterIP   10.100.200.226   <none>        443/TCP              28m
pravega-zk-client                       ClusterIP   10.100.200.122   <none>        2181/TCP             32m
pravega-zk-headless                     ClusterIP   None             <none>        2888/TCP,3888/TCP    32m

```

Pravega installation is fine. But no I/O read/write is happening. Error is "Failed to create scope"
Ran benchamark inside the pod.

$./pravega-benchmark -consumers 1 -controller tcp://10.100.200.155:9090 -events 100 -producers 1 -scope Scope1 -stream st1 -segments 10 -size 100 -time 180

Failed to create scope

o/p:-
```
2019-10-19 10:24:22:920 +0000 [main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.100.200.155:9090
2019-10-19 10:24:22:925 +0000 [main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.100.200.155:9090
2019-10-19 10:24:22:955 +0000 [main] INFO io.pravega.client.admin.impl.StreamManagerImpl - Creating scope: Scope1
2019-10-19 10:24:22:966 +0000 [StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=-5723153523399914182] Tagging client request (createScope-Scope1).
2019-10-19 10:24:23:005 +0000 [StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[[/10.100.200.155:9090]/{}]]
2019-10-19 10:25:46:215 +0000 [grpc-default-executor-1] WARN io.pravega.client.stream.impl.ControllerImpl - [requestId=-5723153523399914182] Failed to create scope: Scope1
2019-10-19 10:25:46:216 +0000 [grpc-default-executor-1] WARN io.pravega.client.stream.impl.ControllerImpl - [requestId=-5723153523399914182] createScope failed: 
java.util.concurrent.CompletionException: io.pravega.client.stream.impl.ControllerFailureException: Failed to create scope: Scope1
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at io.pravega.client.stream.impl.ControllerImpl$RPCAsyncCallback.onCompleted(ControllerImpl.java:1147)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:432)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.client.stream.impl.ControllerFailureException: Failed to create scope: Scope1
        at io.pravega.client.stream.impl.ControllerImpl.lambda$createScope$2(ControllerImpl.java:246)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        ... 30 more
io.pravega.client.stream.impl.ControllerFailureException: Failed to create scope: Scope1
        at io.pravega.client.stream.impl.ControllerImpl.lambda$createScope$2(ControllerImpl.java:246)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at io.pravega.client.stream.impl.ControllerImpl$RPCAsyncCallback.onCompleted(ControllerImpl.java:1147)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:432)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

I have atleast 3 times in different clusters, same issue.

Logs for after uninstall will be attached.

**Comment by Raghuveera-Rao** [comment]
[pravega-k8s-logging-2019-10-19-04-11-20.zip](https://github.com/pravega/pravega/files/3746547/pravega-k8s-logging-2019-10-19-04-11-20.zip)
Before uninstalling pravega logs

**Comment by Raghuveera-Rao** [comment]
[pravega-k8s-logging-2019-10-19-04-28-04.zip](https://github.com/pravega/pravega/files/3746548/pravega-k8s-logging-2019-10-19-04-28-04.zip)
After uninstall pravega logs (Final log)

**Comment by pbelgundi** [comment]
@Raghuveera-Rao could you please try to reproduce this with the last 0.6.0 build.
The client in `0.6.0-2391.97363b3` seems to have a problem which was fixed in a later build.
