### ISSUE TITLE
WriteEvent call is blocked for approx 90% of the time

### ISSUE THREAD

**Issue by akurilov** [pravega/pravega#4303]
**Problem description**
The client performance is expected to be degrading due to producer calls blocking.

**Problem location**
`io.pravega.client.segment.impl.SegmentOutputStreamImpl#write`
method calls `send` method which blocks

**Suggestions for an improvement**
Use something like `io.pravega.client.netty.impl.ClientConnection#sendAsync(java.util.List<io.pravega.shared.protocol.netty.Append>, io.pravega.client.netty.impl.ClientConnection.CompletedCallback)`
instead

**Comment by akurilov** [comment]
Compare the call tree for:

- Pravega http://i.piccy.info/i9/84c495a8f440c089c5ab34548a462a6e/1571731165/72072/722110/Screenshot_20191022_093232.png
- Kafka http://i.piccy.info/i9/5dde6aea83d470383632a81a84b97b7f/1571731216/117460/722110/Screenshot_20191022_102514.png
- Pulsar http://i.piccy.info/i9/6b310aeb52705fc4e034be0cc2488537/1571731232/141830/722110/Screenshot_20191022_103347.png

**Comment by RaulGracia** [comment]
May be related with #4294.

**Comment by akurilov** [comment]
The change in this PR makes call tree picture much better:
http://i.piccy.info/i9/82305cc1909a06b77727566344c58d42/1571734665/139290/722110/pravega_client_non_blocking_evt_write_call_tree.png

**Comment by RaulGracia** [comment]
I just tested your branch on Pravega Benchmark, and it does not work well. After few seconds of writing 100B events (1 writer, 1 segment), the benchmark gets stuck and retrieves an OOM error:
```
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
        at io.pravega.perf.PerfStats.shutdown(PerfStats.java:357)
        at io.pravega.perf.PravegaPerfTest$Test.shutdown(PravegaPerfTest.java:373)
        at io.pravega.perf.PravegaPerfTest.main(PravegaPerfTest.java:140)
Caused by: java.lang.OutOfMemoryError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        ... 3 more
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by akurilov** [comment]
@RaulGracia created the separate issue for this: #4305

**Comment by RaulGracia** [comment]
We observe a 10x performance improvement with #4294 for small even writes, so I assume that the issue presented here is mitigated with that PR.
