### ISSUE TITLE
Problem with HDFS when Segment Store is saturated (AlreadyBeingCreatedException)

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#4339]
**Problem description**
During a performance  benchmarking session, we observed that the Segment Store stopped accepting storage requests. Looking into the Segment Store logs, it looks like some segment containers cannot run correctly due to the following error in `StorageWriter`:
```
2019-11-06 15:18:11,490 43835338 [storage-io-32] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[8]: Iteration[67003].Error.
io.pravega.segmentstore.contracts.StreamSegmentExistsException: [Segment '_system/containers/metadata_8$offset.0'] The StreamSegment exists already
        at io.pravega.storage.hdfs.HDFSExceptionHelpers.convertException(HDFSExceptionHelpers.java:44)
        at io.pravega.storage.hdfs.HDFSStorage.write(HDFSStorage.java:386)
        at io.pravega.segmentstore.storage.rolling.RollingStorage.write(RollingStorage.java:324)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$write$2(AsyncStorageWrapper.java:93)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$runAsync$12(AsyncStorageWrapper.java:171)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hdfs.protocol.AlreadyBeingCreatedException: Failed to APPEND_FILE /proot/_system/containers/metadata_8$offset.0_1 for DFSClient_NONMAPREDUCE_-224508419_32 on 172.16.0.23 because DFSClient_NONMAPREDUCE_-224508419_32 is already the current lease holder.
```
Note that his happens for different segments:
```
2019-11-06 15:23:04,694 44128542 [storage-io-127] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[2]: Iteration[63757].Error.
io.pravega.segmentstore.contracts.StreamSegmentExistsException: [Segment '_system/containers/metadata_2$offset.0'] The StreamSegment exists already
        at io.pravega.storage.hdfs.HDFSExceptionHelpers.convertException(HDFSExceptionHelpers.java:44)
        at io.pravega.storage.hdfs.HDFSStorage.write(HDFSStorage.java:386)
        at io.pravega.segmentstore.storage.rolling.RollingStorage.write(RollingStorage.java:324)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$write$2(AsyncStorageWrapper.java:93)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$runAsync$12(AsyncStorageWrapper.java:171)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hdfs.protocol.AlreadyBeingCreatedException: Failed to APPEND_FILE /proot/_system/containers/metadata_2$offset.0_1 for DFSClient_NONMAPREDUCE_999836622_51 on 172.16.0.23 because DFSClient_NONMAPREDUCE_999836622_51 is already the current lease holder.
```

This issue is preceded by very high latency from a client perspective and it can be reproduced with Pravega 0.6 using RocksDB (on disk).

**Problem location**
Tier 2 management of HDFS.

**Suggestions for an improvement**
Ensure that Tier 2 is not left in inconsistent state.

**Comment by sachin-j-joshi** [comment]
@RaulGracia If you are using a small cluster, then please run with hdfs.replaceDataNodesOnFailure=false

Please see this ...
https://github.com/pravega/pravega/blob/master/config/config.properties#L365

**Comment by RaulGracia** [comment]
Thanks @sachin-j-joshi, closing the issue then.
