### ISSUE TITLE
Bookies restart and gives OOMKilled and hence Readers start dying. 

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#4362]
**mid-scale IO readers  start dying with `RetriesExhaustedException` and Bookkeepers restart**:
```
root@osboxes:/usr/local/go/bin/src/github.com# k get po
NAME                                                 READY   STATUS    RESTARTS   AGE
grafana-5c4689f447-2gljm                             1/1     Running   0          2d20h
influxdb-84bcfc9789-b995m                            1/1     Running   0          2d20h
pravega-bookie-0                                     1/1     Running   0          24h
pravega-bookie-1                                     1/1     Running   1          24h
pravega-bookie-2                                     1/1     Running   1          24h
pravega-bookie-3                                     1/1     Running   1          24h
pravega-operator-7f54698659-fmglh                    1/1     Running   0          24h
pravega-pravega-controller-6cbf86b5f4-r5lvp          1/1     Running   0          24h
pravega-pravega-controller-6cbf86b5f4-x4sd6          1/1     Running   0          24h
pravega-pravega-segmentstore-0                       1/1     Running   0          24h
pravega-pravega-segmentstore-1                       1/1     Running   0          24h
pravega-pravega-segmentstore-2                       1/1     Running   0          24h
pravega-zk-0                                         1/1     Running   0          24h
pravega-zk-1                                         1/1     Running   0          24h
pravega-zk-2                                         1/1     Running   0          24h
pravega-zk-3                                         1/1     Running   0          24h
pravega-zk-4                                         1/1     Running   0          24h
shaka-zulu-nfs-client-provisioner-85f6f98759-lc78h   1/1     Running   0          24h
zookeeper-operator-b7c699ffb-kv5bj                   1/1     Running   0          24h
```
After checking for bookkeeper decription, it gives `OOMKilled`:
```
root@osboxes:/usr/local/go/bin/src/github.com# k describe po pravega-bookie-1
Name:           pravega-bookie-1
Namespace:      default
Priority:       0
Node:           07ae94ad-1a4f-4605-8f09-b2d9e8232c8a/172.24.4.6
Start Time:     Wed, 13 Nov 2019 10:48:05 +0530
Labels:         app=pravega-cluster
                component=bookie
                controller-revision-hash=pravega-bookie-5b5f94498c
                pravega_cluster=pravega
                statefulset.kubernetes.io/pod-name=pravega-bookie-1
Annotations:    pravega.version: 0.6.0-2408.7312399
Status:         Running
IP:             172.28.33.17
Controlled By:  StatefulSet/pravega-bookie
Containers:
  bookie:
    Container ID:   docker://38a5be341d2668ce2ee876281b5e10915b9539a59f2b52bc50e6fa83777c6144
    Image:          devops-repo.isus.emc.com:8116/nautilus/bookkeeper:0.6.0-2408.7312399
    Image ID:       docker-pullable://devops-repo.isus.emc.com:8116/nautilus/bookkeeper@sha256:aec5cb20c695c87452e0ea211e74d418b8c842b83d6465f4aa055e872b7908d9
    Port:           3181/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Thu, 14 Nov 2019 03:30:49 +0530
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 13 Nov 2019 10:48:23 +0530
      Finished:     Thu, 14 Nov 2019 03:30:23 +0530
    Ready:          True
    Restart Count:  1
    Limits:
      cpu:     2
      memory:  6Gi
    Requests:
      cpu:      1
      memory:   2Gi
    Liveness:   exec [/bin/sh -c netstat -ltn 2> /dev/null | grep 3181 || ss -ltn 2> /dev/null | grep 3181] delay=60s timeout=1s period=15s #success=1 #failure=4
    Readiness:  exec [/bin/sh -c /opt/bookkeeper/bin/bookkeeper shell bookiesanity] delay=20s timeout=1s period=10s #success=1 #failure=9
    Environment Variables from:
      pravega-bookie  ConfigMap  Optional: false
    Environment:      <none>
    Mounts:
      /bk/index from index (rw)
      /bk/journal from journal (rw)
      /bk/ledgers from ledger (rw)
      /tmp/dumpfile/heap from heap-dump (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-slxdc (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  journal:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  journal-pravega-bookie-1
    ReadOnly:   false
  ledger:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  ledger-pravega-bookie-1
    ReadOnly:   false
  index:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  index-pravega-bookie-1
    ReadOnly:   false
  heap-dump:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  default-token-slxdc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-slxdc
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age   From                                           Message
  ----     ------     ----  ----                                           -------
  Warning  Unhealthy  51m   kubelet, 07ae94ad-1a4f-4605-8f09-b2d9e8232c8a  Readiness probe failed: 04:36:59,358 INFO  Created ledger 35249
04:37:01,168 ERROR Could not get additional bookie to remake ensemble, closing ledger: 35249
04:37:01,168 ERROR Closing ledger 35249 due to NotEnoughBookiesException: Not enough non-faulty bookies available
04:37:01,169 ERROR Write of ledger entry to quorum failed: L35249 E0
04:37:01,170 WARN  Error in bookie sanity test
org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: Not enough non-faulty bookies available
  at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:83)
  at org.apache.bookkeeper.client.SyncCallbackUtils$SyncAddCallback.addComplete(SyncCallbackUtils.java:251)
  at org.apache.bookkeeper.client.AsyncCallback$AddCallback.addCompleteWithLatency(AsyncCallback.java:91)
  at org.apache.bookkeeper.client.PendingAddOp.submitCallback(PendingAddOp.java:361)
  at org.apache.bookkeeper.client.LedgerHandle.errorOutPendingAdds(LedgerHandle.java:1546)
  at org.apache.bookkeeper.client.LedgerHandle$5.safeRun(LedgerHandle.java:523)
  at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.lang.Thread.run(Thread.java:748)
04:37:01,622 INFO  Deleted ledger 35249
  Warning  Unhealthy  39m  kubelet, 07ae94ad-1a4f-4605-8f09-b2d9e8232c8a  Readiness probe failed: 04:49:19,496 INFO  Created ledger 35564
04:49:20,012 INFO  Written 10 entries in ledger 35564
04:49:21,646 ERROR Read of ledger entry failed: L35564 E0-E9, Sent to [pravega-bookie-1.pravega-bookie-headless.default.svc.cluster.local:3181], Heard from [] : bitset = {}. First unread entry is 0
04:49:21,735 WARN  Error in bookie sanity test
org.apache.bookkeeper.client.BKException$BKTimeoutException: Bookie operation timeout
  at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:83)
  at org.apache.bookkeeper.client.SyncCallbackUtils$SyncReadCallback.readComplete(SyncCallbackUtils.java:231)
  at org.apache.bookkeeper.client.LedgerHandle$6.onFailure(LedgerHandle.java:800)
  at org.apache.bookkeeper.common.concurrent.FutureEventListener.accept(FutureEventListener.java:38)
  at org.apache.bookkeeper.common.concurrent.FutureEventListener.accept(FutureEventListener.java:26)
  at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
  at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
  at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.lang.Thread.run(Thread.java:748)
04:49:22,638 INFO  Deleted ledger 35564
  Warning  Unhealthy  18m  kubelet, 07ae94ad-1a4f-4605-8f09-b2d9e8232c8a  Readiness probe failed: 05:09:49,503 INFO  Created ledger 36069
05:09:50,050 INFO  Written 10 entries in ledger 36069
05:09:51,286 ERROR Could not get additional bookie to remake ensemble, closing ledger: 36069
05:09:51,287 ERROR Write of ledger entry to quorum failed: L36069 E9
05:09:51,287 ERROR Failure NotEnoughBookiesException: Not enough non-faulty bookies available while writing entry: 10 while recovering ledger: 36069
05:09:51,288 WARN  Error in bookie sanity test
org.apache.bookkeeper.client.BKException$BKLedgerRecoveryException: Error while recovering ledger
  at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:83)
  at org.apache.bookkeeper.client.SyncCallbackUtils$SyncOpenCallback.openComplete(SyncCallbackUtils.java:157)
  at org.apache.bookkeeper.client.LedgerOpenOp.openComplete(LedgerOpenOp.java:225)
  at org.apache.bookkeeper.client.LedgerOpenOp$1.safeOperationComplete(LedgerOpenOp.java:194)
  at org.apache.bookkeeper.client.LedgerOpenOp$1.safeOperationComplete(LedgerOpenOp.java:186)
  at org.apache.bookkeeper.util.OrderedGenericCallback.operationComplete(OrderedGenericCallback.java:55)
  at org.apache.bookkeeper.proto.BookkeeperInternalCallbacks$TimedGenericCallback.operationComplete(BookkeeperInternalCallbacks.java:131)
  at org.apache.bookkeeper.client.LedgerRecoveryOp.submitCallback(LedgerRecoveryOp.java:145)
  at org.apache.bookkeeper.client.LedgerRecoveryOp.addComplete(LedgerRecoveryOp.java:247)
  at org.apache.bookkeeper.client.AsyncCallback$AddCallback.addCompleteWithLatency(AsyncCallback.java:91)
  at org.apache.bookkeeper.client.PendingAddOp.submitCallback(PendingAddOp.java:361)
  at org.apache.bookkeeper.client.LedgerHandle.errorOutPendingAdds(LedgerHandle.java:1546)
  at org.apache.bookkeeper.client.LedgerHandle.errorOutPendingAdds(LedgerHandle.java:1531)
  at org.apache.bookkeeper.client.LedgerHandle.handleUnrecoverableErrorDuringAdd(LedgerHandle.java:1511)
  at org.apache.bookkeeper.client.ReadOnlyLedgerHandle.handleBookieFailure(ReadOnlyLedgerHandle.java:141)
  at org.apache.bookkeeper.client.PendingAddOp.writeComplete(PendingAddOp.java:331)
  at org.apache.bookkeeper.proto.PerChannelBookieClient$AddCompletion.writeComplete(PerChannelBookieClient.java:1787)
  at org.apache.bookkeeper.proto.PerChannelBookieClient$AddCompletion.lambda$errorOut$0(PerChannelBookieClient.java:1810)
  at org.apache.bookkeeper.proto.PerChannelBookieClient$CompletionValue$1.safeRun(PerChannelBookieClient.java:1414)
  at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.lang.Thread.run(Thread.java:748)
05:09:51,307 INFO  Deleted ledger 36069
  Warning  Unhealthy  16m  kubelet, 07ae94ad-1a4f-4605-8f09-b2d9e8232c8a  Readiness probe failed: 05:12:29,683 INFO  Created ledger 36141
05:12:31,463 ERROR Could not get additional bookie to remake ensemble, closing ledger: 36141
05:12:31,464 ERROR Closing ledger 36141 due to NotEnoughBookiesException: Not enough non-faulty bookies available
05:12:31,465 ERROR Write of ledger entry to quorum failed: L36141 E9
05:12:31,466 WARN  Error in bookie sanity test
org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: Not enough non-faulty bookies available
  at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:83)
  at org.apache.bookkeeper.client.SyncCallbackUtils$SyncAddCallback.addComplete(SyncCallbackUtils.java:251)
  at org.apache.bookkeeper.client.AsyncCallback$AddCallback.addCompleteWithLatency(AsyncCallback.java:91)
  at org.apache.bookkeeper.client.PendingAddOp.submitCallback(PendingAddOp.java:361)
  at org.apache.bookkeeper.client.LedgerHandle.errorOutPendingAdds(LedgerHandle.java:1546)
  at org.apache.bookkeeper.client.LedgerHandle$5.safeRun(LedgerHandle.java:523)
  at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.lang.Thread.run(Thread.java:748)
05:12:32,207 INFO  Deleted ledger 36141
  Warning  Unhealthy  14m  kubelet, 07ae94ad-1a4f-4605-8f09-b2d9e8232c8a  Readiness probe failed: 05:13:59,853 INFO  Created ledger 36190
05:14:00,257 INFO  Written 10 entries in ledger 36190
05:14:01,548 ERROR While readLastConfirmed ledger: 36190 did not hear success responses from all quorums
05:14:01,556 WARN  Error in bookie sanity test
org.apache.bookkeeper.client.BKException$BKLedgerRecoveryException: Error while recovering ledger
  at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:83)
  at org.apache.bookkeeper.client.SyncCallbackUtils$SyncOpenCallback.openComplete(SyncCallbackUtils.java:157)
  at org.apache.bookkeeper.client.LedgerOpenOp.openComplete(LedgerOpenOp.java:225)
  at org.apache.bookkeeper.client.LedgerOpenOp$1.safeOperationComplete(LedgerOpenOp.java:194)
  at org.apache.bookkeeper.client.LedgerOpenOp$1.safeOperationComplete(LedgerOpenOp.java:186)
  at org.apache.bookkeeper.util.OrderedGenericCallback.operationComplete(OrderedGenericCallback.java:55)
  at org.apache.bookkeeper.proto.BookkeeperInternalCallbacks$TimedGenericCallback.operationComplete(BookkeeperInternalCallbacks.java:131)
  at org.apache.bookkeeper.client.LedgerRecoveryOp.submitCallback(LedgerRecoveryOp.java:145)
  at org.apache.bookkeeper.client.LedgerRecoveryOp.access$100(LedgerRecoveryOp.java:40)
  at org.apache.bookkeeper.client.LedgerRecoveryOp$1.readLastConfirmedDataComplete(LedgerRecoveryOp.java:124)
  at org.apache.bookkeeper.client.ReadLastConfirmedOp.readEntryComplete(ReadLastConfirmedOp.java:134)
  at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadCompletion$1.readEntryComplete(PerChannelBookieClient.java:1556)
  at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadCompletion.lambda$errorOut$0(PerChannelBookieClient.java:1572)
  at org.apache.bookkeeper.proto.PerChannelBookieClient$CompletionValue$1.safeRun(PerChannelBookieClient.java:1414)
  at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.lang.Thread.run(Thread.java:748)
05:14:01,669 INFO  Deleted ledger 36190
```
Logs from IO:
```
INFO  [2019-11-13 12:08:52,857] io.pravega.longevity.utils.PerformanceUtils: Readers (8/8): events:105,561,308, events/sec:4,333, KB/sec:3322.3877
172.28.43.4 - - [13/Nov/2019:12:08:52 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 2702 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 6
INFO  [2019-11-13 12:08:52,923] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 6h 46m
INFO  [2019-11-13 12:08:52,923] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:139,388,622, events/sec:5,714, KB/sec:4381.66
INFO  [2019-11-13 12:08:52,923] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-11-13 12:08:52,923] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 49,846, average block time (ms): 391
INFO  [2019-11-13 12:08:52,923] io.pravega.longevity.utils.PerformanceUtils: Readers (7/8): events:122,866,294, events/sec:5,037, KB/sec:3862.2842
INFO  [2019-11-13 12:08:52,923] io.pravega.longevity.utils.PerformanceUtils: New runtime for 174d6eeb-5bcb-4c16-931a-27c15b818f25  Running for 6h 46m
INFO  [2019-11-13 12:08:52,923] io.pravega.longevity.utils.PerformanceUtils: Dumping stats for stream longevity/midScale
INFO  [2019-11-13 12:08:52,923] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:139,388,622, events/sec:5,722, KB/sec:4387.0566
INFO  [2019-11-13 12:08:52,923] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-11-13 12:08:52,923] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 49,846, average block time (ms): 391
INFO  [2019-11-13 12:08:52,923] io.pravega.longevity.utils.PerformanceUtils: Readers (7/8): events:122,866,294, events/sec:5,043, KB/sec:3867.041
172.28.43.5 - - [13/Nov/2019:12:08:52 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 2700 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 2
INFO  [2019-11-13 12:08:59,147] io.pravega.longevity.testmanager.manager.TestPerformanceCollector: Received Error From task taskID : io.pravega.shared.protocol.netty.ConnectionFailedException
io.pravega.common.util.RetriesExhaustedException: io.pravega.shared.protocol.netty.ConnectionFailedException
        at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:193)
        at io.pravega.client.segment.impl.SegmentMetadataClientImpl.getSegmentInfo(SegmentMetadataClientImpl.java:217)
        at io.pravega.client.state.impl.RevisionedStreamClientImpl.readFrom(RevisionedStreamClientImpl.java:123)
        at io.pravega.client.state.impl.StateSynchronizerImpl.fetchUpdates(StateSynchronizerImpl.java:80)
        at io.pravega.client.stream.impl.ReaderGroupStateManager.fetchUpdatesIfNeeded(ReaderGroupStateManager.java:318)
        at io.pravega.client.stream.impl.ReaderGroupStateManager.getCheckpoint(ReaderGroupStateManager.java:411)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.updateGroupStateIfNeeded(EventStreamReaderImpl.java:192)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:124)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:109)
        at io.pravega.longevity.testworker.workers.readers.PravegaReader.start(PravegaReader.java:99)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException
        at io.pravega.client.netty.impl.RawClient$ResponseProcessor.connectionDropped(RawClient.java:69)
```
Following are the corresponding logs from SSS:
```
2019-11-13 12:08:07,770 24547873 [epollEventLoopGroup-11-5] ERROR i.p.s.p.n.ExceptionLoggingHandler - Uncaught exception on connection /172.28.43.4:41648
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
2019-11-13 12:08:07,770 24547873 [epollEventLoopGroup-11-5] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection: 
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
2019-11-13 12:08:08,463 24548566 [epollEventLoopGroup-10-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x99d93cd7, L:/172.28.33.13:12345] READ: [id: 0x282d679c, L:/172.28.33.13:12345 - R:/172.28.43.4:41656]
2019-11-13 12:08:08,463 24548566 [epollEventLoopGroup-10-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x99d93cd7, L:/172.28.33.13:12345] READ COMPLETE
2019-11-13 12:08:08,463 24548566 [epollEventLoopGroup-11-6] INFO  i.p.s.s.h.handler.AppendProcessor - Received hello from connection: [id: 0x282d679c, L:/172.28.33.13:12345 - R:/172.28.43.4:41656]
2019-11-13 12:08:08,463 24548566 [epollEventLoopGroup-11-6] WARN  i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection: io.pravega.segmentstore.server.IllegalContainerStateException: Container 23 is in an invalid state for this operation. Expected: RUNNING; Actual: STARTING.
2019-11-13 12:08:08,463 24548566 [epollEventLoopGroup-11-6] ERROR i.p.s.p.n.ExceptionLoggingHandler - Uncaught exception on connection /172.28.43.4:41656
java.nio.channels.ClosedChannelException: null
```
Following is the Pravega config:
```
bookkeeper:0.6.0-2408.7312399
pravega:0.6.0-2408.7312399
pravega-operator:0.4.2
zookeeper:0.2.4
zookeeper-operator:0.2.4
```
Uploading k8 logs for reference on Jira.

**Comment by RaulGracia** [comment]
The resources provisioned to Bookies are clearly insufficient:    
```
Limits:
      cpu:     2
      memory:  6Gi
Requests:
      cpu:      1
      memory:   2Gi
```
In this sense, depending on how long it takes the recovery of a container, readers may die or not. But I suspect that also the process of container recovery (which require to perform reads to Bookkeeper and therefore, requires memory to fill the cache) may be also impacted by the under-provisioning. We have a manifest with production-like configuration values, please use it to check if this issue reproduces with proper resource provisioning. Closing this issue at the moment, please re-open it if the same issue reproduces after using the proper manifest configuration.
