### ISSUE TITLE
Readers died during pravega cluster upgrade from 0.6.1-2417.7b9ea59 to 0.6.1-2419.5ae9098

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#4408]
** I upgraded my cluster from 0.6.1-2417.7b9ea59 to 0.6.1-2419.5ae9098 and Readers start dying(became 2/4) with Errors$NativeConnectException**
Also post successful upgrade I am getting 2 versions for bookkeeper:
```
root@osboxes:/home/osboxes# kubectl get po -o jsonpath={...image}|tr -s [[:space:]] "\n"|sort|uniq
devops-repo.isus.emc.com:8116/nautilus/bookkeeper:0.6.1-2417.7b9ea59
devops-repo.isus.emc.com:8116/nautilus/bookkeeper:0.6.1-2419.5ae9098
devops-repo.isus.emc.com:8116/nautilus/pravega:0.6.1-2419.5ae9098
devops-repo.isus.emc.com:8116/nautilus/zookeeper:0.2.5-rc0
openjdk:8
pravega/pravega-operator:0.4.3-rc1
pravega/zookeeper:0.2.5-rc0
pravega/zookeeper-operator:0.2.5-rc0
```
Pods status:
```
root@osboxes:/home/osboxes# k get po --all-namespaces
NAMESPACE           NAME                                                            READY   STATUS      RESTARTS   AGE
default             grafana-5c4689f447-89c2r                                        1/1     Running     0          27h
default             influxdb-84bcfc9789-tmq2d                                       1/1     Running     0          27h
default             pravega-benchmark2                                              1/1     Running     0          34m
default             pravega-bookie-0                                                1/1     Running     0          84m
default             pravega-bookie-1                                                1/1     Running     0          80m
default             pravega-bookie-2                                                1/1     Running     0          78m
default             pravega-bookie-3                                                1/1     Running     0          76m
default             pravega-operator-57c6bc95c9-sbk9r                               1/1     Running     0          23h
default             pravega-pravega-controller-6b58dc54c4-qxqph                     1/1     Running     0          72m
default             pravega-pravega-controller-6b58dc54c4-vshv6                     1/1     Running     0          71m
default             pravega-pravega-segmentstore-0                                  1/1     Running     0          75m
default             pravega-pravega-segmentstore-1                                  1/1     Running     0          74m
default             pravega-pravega-segmentstore-2                                  1/1     Running     0          73m
default             pravega-zk-0                                                    1/1     Running     0          27h
default             pravega-zk-1                                                    1/1     Running     0          27h
default             pravega-zk-2                                                    1/1     Running     0          27h
default             pravega-zk-3                                                    1/1     Running     0          27h
default             pravega-zk-4                                                    1/1     Running     0          27h
default             shaka-zulu-nfs-client-provisioner-85f6f98759-bmr6b              1/1     Running     0          27h
default             zookeeper-operator-f786b75-d6smb                                1/1     Running     0          27h
kube-system         coredns-95489c5c9-8fbzv                                         1/1     Running     0          18d
kube-system         coredns-95489c5c9-cnmhh                                         1/1     Running     0          18d
kube-system         coredns-95489c5c9-nc5kq                                         1/1     Running     0          18d
kube-system         kubernetes-dashboard-558689fc66-nz7f9                           1/1     Running     0          18d
kube-system         metrics-server-867b8fdb7d-wddmt                                 1/1     Running     0          18d
kube-system         tiller-deploy-59cff884b4-sqfdp                                  1/1     Running     0          9d
pks-system          cert-generator-17af10c8087ec8cfc4d69d37b172bef816a3e6f4-kzl29   0/1     Completed   0          18d
pks-system          event-controller-7f4dcc9bb7-qhsbk                               2/2     Running     0          18d
pks-system          fluent-bit-2jdbm                                                2/2     Running     0          18d
pks-system          fluent-bit-4dvj7                                                2/2     Running     0          18d
pks-system          fluent-bit-dvxm7                                                2/2     Running     0          18d
pks-system          fluent-bit-llhbt                                                2/2     Running     0          18d
pks-system          fluent-bit-qc947                                                2/2     Running     0          18d
pks-system          metric-controller-8f67b7868-lqzr6                               1/1     Running     0          18d
pks-system          observability-manager-d777c7d74-879b2                           1/1     Running     0          18d
pks-system          sink-controller-774fb78bbd-xwgv5                                1/1     Running     0          18d
pks-system          telegraf-bbrtf                                                  1/1     Running     0          18d
pks-system          telegraf-cjrsw                                                  1/1     Running     0          18d
pks-system          telegraf-fl2xz                                                  1/1     Running     0          18d
pks-system          telegraf-gtzsh                                                  1/1     Running     0          18d
pks-system          telegraf-mtwg8                                                  1/1     Running     0          18d
pks-system          telemetry-agent-858446f4ff-hxxgc                                2/2     Running     0          18d
pks-system          validator-646dc57cdb-9lrgz                                      1/1     Running     0          18d
pravega-longevity   small-manager-897d96b95-qg7dm                                   1/1     Running     0          26h
pravega-longevity   small-worker-6f5d98f679-7cv62                                   1/1     Running     0          26h
```
Longevity log exceptions:
```
INFO  [2019-11-29 09:15:33,163] io.pravega.client.netty.impl.FlowHandler: Connection established with endpoint 172.28.33.18 on channel [id: 0xe7de89a1]
WARN  [2019-11-29 09:15:33,166] io.pravega.client.segment.impl.SegmentOutputStreamImpl: 1e39249f-32e7-40ce-8c2c-0a9c94277c74 Failed to connect:
! io.netty.channel.unix.Errors$NativeConnectException: syscall:getsockopt(..) failed: Connection refused
! ... 1 common frames omitted
! Causing: io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: /172.28.33.18:12345
! at io.netty.channel.unix.Socket.finishConnect(..)(Unknown Source)
! Causing: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: /172.28.33.18:12345
! ... 14 common frames omitted
```
```
INFO  [2019-11-29 09:16:12,783] io.pravega.longevity.testmanager.manager.TestPerformanceCollector: Received Error From task taskID : io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
        at java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeRelay(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniRelay(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniRelay.tryFire(Unknown Source)
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
        at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$6(Retry.java:245)
        at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.failAllInflight(AsyncSegmentInputStreamImpl.java:269)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.closeConnection(AsyncSegmentInputStreamImpl.java:241)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.access$100(AsyncSegmentInputStreamImpl.java:43)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.connectionDropped(AsyncSegmentInputStreamImpl.java:66)
        at io.pravega.client.netty.impl.FlowHandler.lambda$channelUnregistered$0(FlowHandler.java:221)
        at java.util.concurrent.ConcurrentHashMap.forEach(Unknown Source)
        at io.pravega.client.netty.impl.FlowHandler.channelUnregistered(FlowHandler.java:218)
```
It has become:
```
172.28.43.4 - - [29/Nov/2019:09:16:13 +0000] "POST /v1/longevity/error HTTP/1.1" 200 5504 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 7
INFO  [2019-11-29 09:16:29,891] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 1d 1h
INFO  [2019-11-29 09:16:29,891] io.pravega.longevity.utils.PerformanceUtils: Writers (3/3): events:3,268,194, events/sec:35, KB/sec:27.029297
INFO  [2019-11-29 09:16:29,891] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-11-29 09:16:29,891] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-11-29 09:16:29,891] io.pravega.longevity.utils.PerformanceUtils: Readers (2/4): events:20,197,133, events/sec:217, KB/sec:167.04199
INFO  [2019-11-29 09:16:29,891] io.pravega.longevity.utils.PerformanceUtils: New runtime for 87bd6a15-2ada-4402-b21c-0099102a7add  Running for 1d 1h
INFO  [2019-11-29 09:16:29,891] io.pravega.longevity.utils.PerformanceUtils: Dumping stats for stream longevity/small
INFO  [2019-11-29 09:16:29,891] io.pravega.longevity.utils.PerformanceUtils: Writers (3/3): events:3,268,194, events/sec:35, KB/sec:27.029297
INFO  [2019-11-29 09:16:29,891] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-11-29 09:16:29,891] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-11-29 09:16:29,891] io.pravega.longevity.utils.PerformanceUtils: Readers (2/4): events:20,197,133, events/sec:217, KB/sec:167.04199
```
I am able to create new scope and streams after upgrade.
Logs are available in shared location.

**Comment by RaulGracia** [comment]
@Richa-Srivastava this looks like an old issue, is this problem still there or can we close it?

**Comment by Richa-Srivastava** [comment]
sure @RaulGracia this is very old issue, didn't notice this issue in recent upgrades. We can close this.
