### ISSUE TITLE
Failing SecureConnectionFactoryImplTest after Netty No Flush PR

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#4424]
**Problem description**
We have detected in our Jenkins server that after merging #4294 this test has failed 2 times in a row: `io.pravega.client.netty.impl.SecureConnectionFactoryImplTest.getActiveChannelTestWithoutConnectionPooling`. Note that this error only happens for the JDK 8 build (the JDK 11 does not show this error).

The log for the error is the following:
```
java.lang.AssertionError: Expected active channel count is 1 expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at io.pravega.client.netty.impl.ConnectionFactoryImplTest.getActiveChannelTestWithoutConnectionPooling(ConnectionFactoryImplTest.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Standard Output
2019-12-09 01:06:24,231 1402 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xf1ad45e3] REGISTERED
2019-12-09 01:06:24,245 1416 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xf1ad45e3] BIND: localhost/127.0.0.1:35290
2019-12-09 01:06:24,266 1437 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xf1ad45e3, L:/127.0.0.1:35290] ACTIVE
2019-12-09 01:06:24,324 1495 [Test worker] INFO  i.p.client.netty.impl.FlowHandler - Creating a new connection with flow disabled for endpoint localhost. The current Channel is null.
2019-12-09 01:06:24,360 1531 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xf1ad45e3, L:/127.0.0.1:35290] READ: [id: 0x9e3ee470, L:/127.0.0.1:35290 - R:/127.0.0.1:33694]
2019-12-09 01:06:24,366 1537 [epollEventLoopGroup-4-1] INFO  i.p.client.netty.impl.FlowHandler - Connection established with endpoint localhost on channel [id: 0x9c525d6b, L:/127.0.0.1:33694 - R:localhost/127.0.0.1:35290]
2019-12-09 01:06:24,375 1546 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xf1ad45e3, L:/127.0.0.1:35290] READ COMPLETE
2019-12-09 01:06:24,525 1696 [epollEventLoopGroup-4-1] INFO  i.p.client.netty.impl.FlowHandler - Connection drop observed with endpoint localhost
2019-12-09 01:06:24,527 1698 [Test worker] INFO  i.p.client.netty.impl.FlowHandler - Closing Flow 0 for endpoint localhost
2019-12-09 01:06:24,527 1698 [Test worker] INFO  i.p.c.n.impl.ConnectionFactoryImpl - Shutting down connection factory
2019-12-09 01:06:24,530 1701 [Test worker] INFO  i.p.c.netty.impl.ConnectionPoolImpl - Shutting down connection pool
2019-12-09 01:06:24,538 1709 [epollEventLoopGroup-3-1] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1140)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1101)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1169)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1212)
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:216)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1297)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1211)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1245)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	... 14 common frames omitted
2019-12-09 01:06:24,549 1720 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xf1ad45e3, L:/127.0.0.1:35290] CLOSE
2019-12-09 01:06:24,549 1720 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xf1ad45e3, L:/127.0.0.1:35290] INACTIVE
2019-12-09 01:06:24,549 1720 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xf1ad45e3, L:/127.0.0.1:35290] UNREGISTERED
2019-12-09 01:06:24,638 1809 [epollEventLoopGroup-5-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xbd0603f0] REGISTERED
2019-12-09 01:06:24,640 1811 [epollEventLoopGroup-5-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xbd0603f0] BIND: localhost/127.0.0.1:35291
2019-12-09 01:06:24,640 1811 [epollEventLoopGroup-5-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xbd0603f0, L:/127.0.0.1:35291] ACTIVE
2019-12-09 01:06:24,646 1817 [Test worker] INFO  i.p.c.netty.impl.ConnectionPoolImpl - Creating a new connection to PravegaNodeUri(endpoint=localhost, port=35291)
2019-12-09 01:06:24,646 1817 [Test worker] INFO  i.p.client.netty.impl.FlowHandler - Creating Flow 1 for endpoint localhost. The current Channel is null.
2019-12-09 01:06:24,648 1819 [epollEventLoopGroup-5-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xbd0603f0, L:/127.0.0.1:35291] READ: [id: 0x48969d6f, L:/127.0.0.1:35291 - R:/127.0.0.1:48358]
2019-12-09 01:06:24,648 1819 [epollEventLoopGroup-7-1] INFO  i.p.client.netty.impl.FlowHandler - Connection established with endpoint localhost on channel [id: 0x5c29f0c8, L:/127.0.0.1:48358 - R:localhost/127.0.0.1:35291]
2019-12-09 01:06:24,650 1821 [Test worker] INFO  i.p.client.netty.impl.FlowHandler - Closing Flow 1 for endpoint localhost
2019-12-09 01:06:24,650 1821 [Test worker] INFO  i.p.c.netty.impl.ConnectionPoolImpl - Shutting down connection pool
2019-12-09 01:06:24,651 1822 [epollEventLoopGroup-7-1] INFO  i.p.client.netty.impl.FlowHandler - Connection drop observed with endpoint localhost
2019-12-09 01:06:24,652 1823 [epollEventLoopGroup-5-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xbd0603f0, L:/127.0.0.1:35291] READ COMPLETE
2019-12-09 01:06:24,654 1825 [epollEventLoopGroup-6-1] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1140)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1101)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1169)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1212)
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:216)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1297)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1211)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1245)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	... 14 common frames omitted
2019-12-09 01:06:24,669 1840 [Test worker] INFO  i.p.c.n.impl.ConnectionFactoryImpl - Shutting down connection factory
2019-12-09 01:06:24,670 1841 [Test worker] INFO  i.p.c.netty.impl.ConnectionPoolImpl - Shutting down connection pool
2019-12-09 01:06:24,671 1842 [epollEventLoopGroup-5-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xbd0603f0, L:/127.0.0.1:35291] CLOSE
2019-12-09 01:06:24,671 1842 [epollEventLoopGroup-5-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xbd0603f0, L:/127.0.0.1:35291] INACTIVE
2019-12-09 01:06:24,671 1842 [epollEventLoopGroup-5-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xbd0603f0, L:/127.0.0.1:35291] UNREGISTERED
2019-12-09 01:06:24,723 1894 [epollEventLoopGroup-8-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x9631e796] REGISTERED
2019-12-09 01:06:24,723 1894 [epollEventLoopGroup-8-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x9631e796] BIND: localhost/127.0.0.1:35292
2019-12-09 01:06:24,733 1904 [epollEventLoopGroup-8-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x9631e796, L:/127.0.0.1:35292] ACTIVE
2019-12-09 01:06:24,733 1904 [Test worker] INFO  i.p.client.netty.impl.FlowHandler - Creating a new connection with flow disabled for endpoint localhost. The current Channel is null.
2019-12-09 01:06:24,736 1907 [epollEventLoopGroup-8-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x9631e796, L:/127.0.0.1:35292] READ: [id: 0x638407f0, L:/127.0.0.1:35292 - R:/127.0.0.1:35454]
2019-12-09 01:06:24,739 1910 [epollEventLoopGroup-10-1] INFO  i.p.client.netty.impl.FlowHandler - Connection established with endpoint localhost on channel [id: 0x003a364a, L:/127.0.0.1:35454 - R:localhost/127.0.0.1:35292]
2019-12-09 01:06:24,741 1912 [Test worker] INFO  i.p.client.netty.impl.FlowHandler - Closing Flow 0 for endpoint localhost
2019-12-09 01:06:24,741 1912 [Test worker] INFO  i.p.client.netty.impl.FlowHandler - Closing connection with endpoint localhost on channel [id: 0x003a364a, L:/127.0.0.1:35454 - R:localhost/127.0.0.1:35292]
2019-12-09 01:06:24,741 1912 [Test worker] INFO  i.p.c.n.impl.ConnectionFactoryImpl - Shutting down connection factory
2019-12-09 01:06:24,741 1912 [Test worker] INFO  i.p.c.netty.impl.ConnectionPoolImpl - Shutting down connection pool
2019-12-09 01:06:24,742 1913 [epollEventLoopGroup-10-1] ERROR i.p.s.p.n.ExceptionLoggingHandler - Uncaught exception on connection localhost
javax.net.ssl.SSLException: SSLEngine closed already
	at io.netty.handler.ssl.SslHandler.wrap(...)(Unknown Source)
2019-12-09 01:06:24,746 1917 [epollEventLoopGroup-10-1] INFO  i.p.client.netty.impl.FlowHandler - Connection drop observed with endpoint localhost
2019-12-09 01:06:24,753 1924 [epollEventLoopGroup-8-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x9631e796, L:/127.0.0.1:35292] READ COMPLETE
```

**Problem location**
Client.

**Suggestions for an improvement**
Make the test to pass consistently.

**Comment by tkaitchuck** [comment]
Apparently this is the error you get if you point in SSL client at a non SSL endpoint. So I am guessing we have some odd config kicking around from a previous test.

**Comment by RaulGracia** [comment]
We have not seen this again, so I'm closing it. Please, re-open if the issue re-surfaces again.
