### ISSUE TITLE
Flakey Test: ControllerMetricsTest.zookeeperMetricsTest

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#4441]
**Problem description**
Sometimes `ControllerMetricsTest.zookeeperMetricsTest` fails with the following stack trace:
```
    java.lang.AssertionError: expected:<0.0> but was:<1.0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:553)
        at org.junit.Assert.assertEquals(Assert.java:683)
        at io.pravega.test.integration.ControllerMetricsTest.zookeeperMetricsTest(ControllerMetricsTest.java:245)
```

**Problem location**
ControllerMetricsTest

**Suggestions for an improvement**
Debug test

**Comment by shrids** [comment]
Observing this in the latest travis build on master https://github.com/pravega/pravega/commit/9fbbe28b23e8f9fde05aab03911fcc82bbcae5f8

**Comment by pbelgundi** [comment]
This issue is a duplicate for #4869 which is fixed. So closing this issue.
