### ISSUE TITLE
BTree Data Corruption on NFS mounts

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#4451]
**Problem description**
Found while running load tests:
```
io.pravega.segmentstore.server.DataCorruptionException: BTreeIndex operation failed. Index corrupted.
	at io.pravega.segmentstore.server.attributes.SegmentAttributeBTreeIndex.handleIndexOperationException(SegmentAttributeBTreeIndex.java:647)
...
Caused by: io.pravega.common.util.IllegalDataFormatException: Wrong footer information. RootPage Offset (236958) + Length (974) exceeds Footer Offset (237568).
	at io.pravega.common.util.btree.BTreeIndex.initialize(BTreeIndex.java:215)
	at io.pravega.common.util.btree.BTreeIndex.lambda$null$0(BTreeIndex.java:196)
	... 11 common frames omitted
```

**Problem location**
BTree Index.

**Suggestions for an improvement**
TBD

**Comment by andreipaduroiu** [comment]
Analysis of this problem:
- It occurs repeatedly, always for the same Container+Segment. It always ends up shutting down the Segment Container which leads to a restart, etc.
- Footer claims the Root Page is 974 bytes, but doing arithmetic (Footer Offset - RootPage Offset) indicates it should be 610
    - 974 - 14 (page header) = 960. 
        - 960 / 34 (Index Page entry length) = 25.9.
        - **960 / 24 (Data Page entry length) = 40.**
    - 610 - 14 (page header) = 596. 
        - 596 / 24 (Data Page entry length) = 24.8        - 596 / 24 (Data Page entry length) = 24.8

**Comment by andreipaduroiu** [comment]
Another instance: 

```
2020-01-08 09:38:14,220 36204 [core-28] DEBUG i.p.common.util.btree.BTreeIndex - IndexLength = 389120, RootPageOffset = -8378679224209839878, RootPageLength = 141361152.

...

2020-01-08 09:38:16,154 38138 [core-20] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[11]: Iteration[36].Error.
java.lang.ArrayIndexOutOfBoundsException: Offset (-8378679224209839878) must be non-negative, and bufferOffset (0) and length (141361152) must be valid indices into buffer of size 141361152.
	at io.pravega.segmentstore.storage.rolling.RollingStorage.read(RollingStorage.java:137)

```

**Comment by andreipaduroiu** [comment]
This has been found to be due to the non-atomicity of NFS writes. While for stream segments, which are append only (and we always have the same data to append), this is not an issue, for BTreeIndex, we must have the last 12 bytes of the segment be a footer that points to the root page. Otherwise the BTreeIndex will not know where to start looking.
