### ISSUE TITLE
Unable to retrieve cache contents while sync-ing to Tier2

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#4452]
**Problem description**
This occasionally happens, which causes the container to restart. No data loss.

```
io.pravega.segmentstore.server.DataCorruptionException: Unable to retrieve CacheContents for 'AggregatedAppend: SegmentId = 1, Offsets = [249399-249626), SeqNo = 17626147'.
	at io.pravega.segmentstore.server.writer.SegmentAggregator.getFlushArgs(SegmentAggregator.java:826)
	at io.pravega.segmentstore.server.writer.SegmentAggregator.flushPendingAppends(SegmentAggregator.java:754)
	at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$flushExcess$14(SegmentAggregator.java:696)
	at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:729)
	at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:698)
	at io.pravega.common.concurrent.Futures.runOrFail(Futures.java:589)
	at io.pravega.common.concurrent.Futures$Loop.run(Futures.java:742)
```

**Problem location**
Segment Store.

**Suggestions for an improvement**
TBD

**Comment by andreipaduroiu** [comment]
This has been root-caused to a concurrency between a Read Index Append and Read Index eviction.

Summary:
1. We have a Cache Entry E1 with Generation G1, and its entire contents is in Storage.
    - E1 maps to the end of the Segment.
2. We initiate an append A1, which will update the contents of E1.
    - E1 has been chosen and A1 has been written to the CacheStorage (but it's not done yet)
3. The Cache Manager executes.
    - E1 is identified for eviction and is evicted.
4. Append A1 resumes and updates E1 with its new length.
    - However E1 is no longer part of the Index, and A1 is "leaked" into the Cache Storage and impossible to retrieve without a container restart.
