### ISSUE TITLE
Netty exception in the client logs during event writes upon several rounds of manual scale 

### ISSUE THREAD

**Issue by ravisharda** [pravega/pravega#4475]
**Problem description**

Write an event to a stream. Run manual scales several times (say, 10 or more). Then, try to write an event again to the stream. 

On occasion, you'd see the following inexplicable exception in the logs. 

```
2020-01-07 10:51:49.494 [nioEventLoopGroup-5-11] ERROR i.p.s.p.n.ExceptionLoggingHandler.exceptionCaught(30) - Uncaught exception on connection 13.67.69.131
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
Note the following: 

* The exception didn't cause any problem in functional behavior. The Writes eventually succeed.
* This issue was first observed in `0.6.1`. It may or may not be present in previous or later versions. 

**Problem location**

**Suggestions for an improvement**

**Comment by shrids** [comment]
At the moment Pravega client does not use netty. Closing this issue.
