### ISSUE TITLE
Sporadic test failure StreamSegmentContainerTests.testFutureReads

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#4487]
**Problem description**
We have recently observed sporadic test failures due to timeout of `StreamSegmentContainerTests.testFutureReads`:
```
org.junit.runners.model.TestTimedOutException: test timed out after 100000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1695)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)`
```

**Problem location**
`StreamSegmentContainerTests`

**Suggestions for an improvement**
Make the test to pass consistently.

**Comment by andreipaduroiu** [comment]
Fixed with #5454
