### ISSUE TITLE
Segment store fault causing longevity apps to fail

### ISSUE THREAD

**Issue by ManishKumarKeshri** [pravega/pravega#4541]
**Problem description**
Flink-longevity-0.3.1 was deployed on freshly installed cluster on 1/29 at 14:00 hrs UTC , everything seemed to work until 16:00 hrs UTC when the readers and writers failed. The JM/TM are in crashloopback state, they re unable to connect to the SSS. The pravega controller exhibit similar behavior too.
```
2020-01-23 16:01:12,438 8088662 [storage-io-33] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[15]: Iteration[3].Error.
io.pravega.segmentstore.contracts.StreamSegmentExistsException: [Segment '_system/containers/metadata_15$attributes.index$offset.0'] The StreamSegment exists already.
 at io.pravega.storage.filesystem.FileSystemStorage.throwException(FileSystemStorage.java:428)
 at io.pravega.storage.filesystem.FileSystemStorage.execute(FileSystemStorage.java:418)
 at io.pravega.storage.filesystem.FileSystemStorage.create(FileSystemStorage.java:151)
 at io.pravega.segmentstore.storage.rolling.RollingStorage.createChunk(RollingStorage.java:585)
 at io.pravega.segmentstore.storage.rolling.RollingStorage.rollover(RollingStorage.java:521)
 at io.pravega.segmentstore.storage.rolling.RollingStorage.write(RollingStorage.java:317)
 at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$write$2(AsyncStorageWrapper.java:93)
 at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$runAsync$12(AsyncStorageWrapper.java:171)
 at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
 at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)`

`2020-01-23 16:01:13,446 8089670 [storage-io-131] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[15]: Iteration[4].Error.
io.pravega.segmentstore.contracts.BadOffsetException: [Segment '_system/containers/metadata_15'] Bad Offset. Expected 854, given 411.
 at io.pravega.segmentstore.storage.rolling.RollingStorage.ensureOffset(RollingStorage.java:823)
 at io.pravega.segmentstore.storage.rolling.RollingStorage.write(RollingStorage.java:309)
 at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$write$2(AsyncStorageWrapper.java:93)
 at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$runAsync$12(AsyncStorageWrapper.java:171)
 at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
 at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)`

` 2020-01-23 16:01:11,585 7706561 [core-14] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[21]: Iteration[10].Error.
java.lang.IllegalArgumentException: startOffset must refer to an offset beyond the Segment's StorageLength offset.
 at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
 at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.readDirect(StreamSegmentReadIndex.java:705)
 at io.pravega.segmentstore.server.reading.ContainerReadIndex.readDirect(ContainerReadIndex.java:180)
 at io.pravega.segmentstore.server.writer.StorageWriterFactory$StorageWriterDataSource.getAppendData(StorageWriterFactory.java:146)
 at io.pravega.segmentstore.server.writer.SegmentAggregator.getFlushArgs(SegmentAggregator.java:820)
 at io.pravega.segmentstore.server.writer.SegmentAggregator.flushPendingAppends(SegmentAggregator.java:754)
 at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$flushExcess$14(SegmentAggregator.java:696)
 at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:729)
 at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:698)
 at io.pravega.common.concurrent.Futures.runOrFail(Futures.java:589)
 at io.pravega.common.concurrent.Futures$Loop.run(Futures.java:742)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
```

**Problem location**
segmentstore

**Suggestions for an improvement**
Hann

**Comment by andreipaduroiu** [comment]
Resolved.
