### ISSUE TITLE
DataCorruptionException: Unable to add operation (StreamSegmentAppendOperation) to ReadIndex

### ISSUE THREAD

**Issue by Tristan1900** [pravega/pravega#4573]
**Problem description**
This expcetion has been observed in the Pravega longevity test many times.
```
2020-02-21 00:35:57,581 33980083 [core-21] ERROR i.p.s.s.logs.OperationProcessor - OperationProcessor[19]: MemoryStateUpdater.process failure.
io.pravega.segmentstore.server.DataCorruptionException: Unable to add operation 'StreamSegmentAppendOperation: SequenceNumber = 422077, SegmentId = 405275, Offset = 1307811, Length = 808, Attributes = 2' to ReadIndex.
	at io.pravega.segmentstore.server.logs.MemoryStateUpdater.addToReadIndex(MemoryStateUpdater.java:240)
	at io.pravega.segmentstore.server.logs.MemoryStateUpdater.process(MemoryStateUpdater.java:161)
	at io.pravega.segmentstore.server.logs.MemoryStateUpdater.process(MemoryStateUpdater.java:120)
	at io.pravega.segmentstore.server.logs.OperationProcessor.processCommits(OperationProcessor.java:414)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Given blockId is not allocated.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at io.pravega.segmentstore.storage.cache.DirectMemoryBuffer.tryAppend(DirectMemoryBuffer.java:207)
	at io.pravega.segmentstore.storage.cache.DirectMemoryCache.append(DirectMemoryCache.java:278)
	at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.appendToEntry(StreamSegmentReadIndex.java:539)
	at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.append(StreamSegmentReadIndex.java:371)
	at io.pravega.segmentstore.server.reading.ContainerReadIndex.append(ContainerReadIndex.java:126)
	at io.pravega.segmentstore.server.logs.MemoryStateUpdater.addToReadIndex(MemoryStateUpdater.java:218)
	... 13 common frames omitted
```

The first exception seems occur at `2020-02-21 00:35:57` in segmetnstore-2, the benchmark writer and reader stops working after about 4 hours and there is a `TooManyActiveSegmentsException` error when w/r stops possibly caused by this DataCorruptionException. 

```
io.pravega.segmentstore.contracts.TooManyActiveSegmentsException: [Container 17] The maximum number of active Segments (25000) has been reached..
```

Update: 
There is another longevity test ends up being `TooManyActiveSegmentsException` and writer/reader stopped as well. Both experiments are using `small-scale-tx-bytes` workload in Pravega longevity. 

**Problem location**
SegmentStore, Streaming cache

**Suggestions for an improvement**

**Comment by andreipaduroiu** [comment]
Fixed by #4577. If this recurs, feel free to reopen.
