### ISSUE TITLE
Exception: startOffset must refer to an offset beyond the Segment's StorageLength offset.

### ISSUE THREAD

**Issue by ManishKumarKeshri** [pravega/pravega#4580]
**Problem description**
When event write is scaled to 95 parallel ingestion sources each ingesting 100B payload about 1000events/sec, the following error is seen:
```
ERROR i.p.s.server.writer.StorageWriter - StorageWriter[40]: Iteration[1215].Error.
java.lang.IllegalArgumentException: startOffset must refer to an offset beyond the Segment's StorageLength offset.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.readDirect(StreamSegmentReadIndex.java:705)
        at io.pravega.segmentstore.server.reading.ContainerReadIndex.readDirect(ContainerReadIndex.java:180)
        at io.pravega.segmentstore.server.writer.StorageWriterFactory$StorageWriterDataSource.getAppendData(StorageWriterFactory.java:162)
        at io.pravega.segmentstore.server.writer.SegmentAggregator.getFlushArgs(SegmentAggregator.java:783)
        at io.pravega.segmentstore.server.writer.SegmentAggregator.flushPendingAppends(SegmentAggregator.java:722)
        at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$flushExcess$14(SegmentAggregator.java:664)
        at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:729)
        at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:698)
        at io.pravega.common.concurrent.Futures.runOrFail(Futures.java:589)
        at io.pravega.common.concurrent.Futures$Loop.run(Futures.java:742)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
**Problem location**
SegmentStore

**Suggestions for an improvement**
TBD

**Comment by andreipaduroiu** [comment]
This was resolved with one of the many fixes in the last week or two.
