### ISSUE TITLE
NoOp mode. StorageWriter exception after Segment Store restarting

### ISSUE THREAD

**Issue by OlegKashtanov** [pravega/pravega#4636]
**Problem description**
pravega: **0.8.0-2506.f9a7eaa**
NoOp mode.
Couldn't write to the Segment Store after SS pod restarting.
```
2020-03-22 18:59:23,269 11627 [core-5] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[32]: Iteration[1].Error.
java.lang.IllegalArgumentException: value: New Storage Length cannot be smaller than the previous one.
	at io.pravega.common.Exceptions.checkArgument(Exceptions.java:210)
	at io.pravega.segmentstore.server.containers.StreamSegmentMetadata.setStorageLength(StreamSegmentMetadata.java:216)
	at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$initialize$0(SegmentAggregator.java:259)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Problem location**
```StorageWriter```

**Suggestions for an improvement**

**Comment by andreipaduroiu** [comment]
NoOp mode is not supported between segment store restarts. It is only meant as a happy-path perf testing mode to check the ingestion tput of the system without any potential Tier 2 interference. Since there is no data in Tier 2, there are no guarantees as to what might happen upon a restart.
