### ISSUE TITLE
client.stream.Position.toBytes fails to serialize -1

### ISSUE THREAD

**Issue by claudiofahey** [pravega/pravega#4669]
**Problem description**

Calling `client.stream.Position.toBytes` fails with some events returned by ReadEvents. Events consist of short UTF-8 strings such as "123456789". I believe this problem occurs for streams with multiple segments in which 1 segment has no events.

Stack trace is below.
```
Caused by: java.lang.IllegalArgumentException: writeCompactLong can only serialize longs in the interval [0, 2^62), given -1.
	at io.pravega.common.io.serialization.RevisionDataOutputStream.writeCompactLong(RevisionDataOutputStream.java:104)
	at io.pravega.client.stream.impl.PositionImpl$PositionSerializer.lambda$write00$2(PositionImpl.java:138)
	at io.pravega.common.io.serialization.RevisionDataOutputStream.writeMap(RevisionDataOutputStream.java:343)
	at io.pravega.client.stream.impl.PositionImpl$PositionSerializer.write00(PositionImpl.java:137)
	at io.pravega.common.io.serialization.VersionedSerializer$SingleType.serializeContents(VersionedSerializer.java:336)
	at io.pravega.common.io.serialization.VersionedSerializer$SingleType.serialize(VersionedSerializer.java:304)
	at io.pravega.common.io.serialization.VersionedSerializer$WithBuilder.serialize(VersionedSerializer.java:511)
	at io.pravega.common.io.serialization.VersionedSerializer.serialize(VersionedSerializer.java:130)
	at io.pravega.client.stream.impl.PositionImpl.toBytes(PositionImpl.java:174)
	at io.pravega.example.gateway.grpc.PravegaServerImpl.readEvents(PravegaServerImpl.java:204)
	... 9 common frames omitted
```

Below shows the first event in the stream. position.getBytes returns this exception. The description field is from position.toString() which shows a -1 for one of the segments.
```
event: "1234"
 position {
   description: "examples/memory-eater-in/1.#epoch.0=-1, examples/memory-eater-in/0.#epoch.0=12"
 }
 event_pointer {
   bytes: "\000\000\001\000\000\000\000\'\000#examples/memory-eater-in/0.#epoch.0\000\014"
   description: "examples/memory-eater-in/0.#epoch.0:0-12"
 }
 stream_cut {
   text: "H4sIAAAAAAAAADOwSq1IzC3ISS3Wz03NzS+q1E1NLEkt0s3MszLQMQRiAytDIx1dQwCG5bJbKAAAAA=="
   description: "examples/memory-eater-in:0=12, 1=-1"
 }
```

**Problem location**
Pravega Client 0.7.0

**Suggestions for an improvement**
The serializer must use signed integers.

**Comment by medvedevigorek** [comment]
@shrids is it serious enough to be considered for 0.7.1 release too? Thanks

**Comment by shrids** [comment]
This is a good to have fix. The Position object (io.pravega.client.stream.EventRead#getPosition() ) is used to represent a postion in the stream. This will be used by applications to indicate where a reader died via `ReaderGroup#readerOffline(String, Position)`
