### ISSUE TITLE
Cannot run Pravega Controller 0.7.1  on JDK14: java.lang.NoClassDefFoundError: javax/activation/DataSource

### ISSUE THREAD

**Issue by eolivelli** [pravega/pravega#4833]
**Problem description**
Pravega cannot start on JDK14, this is the error

java.lang.NoClassDefFoundError: javax/activation/DataSource
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3215)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2435)
	at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1354)
	at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1350)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at org.jvnet.hk2.internal.Utilities.getAllConstructors(Utilities.java:1350)
	at org.jvnet.hk2.internal.Utilities.findProducerConstructor(Utilities.java:1293)
	at org.jvnet.hk2.internal.DefaultClassAnalyzer.getConstructor(DefaultClassAnalyzer.java:60)
	at org.glassfish.jersey.inject.hk2.JerseyClassAnalyzer.getConstructor(JerseyClassAnalyzer.java:124)
	at org.jvnet.hk2.internal.Utilities.getConstructor(Utilities.java:156)
	at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:105)
	at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:156)
	at org.jvnet.hk2.internal.SystemDescriptor.internalReify(SystemDescriptor.java:716)
	at org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:670)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:441)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.narrow(ServiceLocatorImpl.java:2287)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.access$1200(ServiceLocatorImpl.java:105)
	at org.jvnet.hk2.internal.ServiceLocatorImpl$10.compute(ServiceLocatorImpl.java:1372)
	at org.jvnet.hk2.internal.ServiceLocatorImpl$10.compute(ServiceLocatorImpl.java:1367)
	at org.glassfish.hk2.utilities.cache.internal.WeakCARCacheImpl.compute(WeakCARCacheImpl.java:105)

**Problem location**
Missing Java Activation Framework dependency on 0.7.1 binary package

**Suggestions for an improvement**
Add the jar to the binary distribution.

**Comment by eolivelli** [comment]
The problem does not affect "pravega-standalone" mode

**Comment by eolivelli** [comment]
I must add that with this error it is not possible to stop praveg controller using crtl-C

**Comment by ravisharda** [comment]
@eolivelli 

This is quite like another issue [3937](https://github.com/pravega/pravega/issues/3937). 

Like JAXB, Standard Java (JDK/JRE) has stopped including Javax Activation (javax.activation:javax.activation-api) since Java 11. From the dependencies graph (generated using `./gradle allDeps`), this jar is a transitive dependency along the following dependency path in the `bindings` Gradle subproject: 

`javax.activation:activation:1.1` > `javax.xml.bind:jaxb-api` > `com.sun.xml.bind:jaxb-impl` > `com.sun.jersey:jersey-json` > `org.apache.hadoop:hadoop-common` (Read `>` as "comes from"). 

So, adding an explicit dependency to `javax.xml.bind:jaxb-api` in `bindings` subproject, like we did in [PR 3943 ](https://github.com/pravega/pravega/pull/3943) for another Gradle project, should resolve this issue. 

Curious, did you encounter this issue when trying to run Pravega with HDFS as tier 2 storage?

**Comment by eolivelli** [comment]
I am just trying to run Pravega, single node, with local disk as tier-2 (hdfs URL file://tmp/pravega)
The Segment store initially appears to work well, even on JDK14.
I am getting other errors, but they are out of the scope of this issue.

I am "just playing" with Pravega 0.7.1.
I am working on an integration with https://emailsuccess.com and so I want to create a demo env.
I am also trying to create a demo about using https://bkvm.org with Pravega 0.7.1, because now we are tagging BookKeeper ledgers with a few metadata.

I am going to record the issues I encounter as tickets here on github.

Currently Pravega has a different kind of users, I am going to make it simple for the customers of my products :-)
They are not using docker or kube, and usually they run on JDK11+

**Comment by ravisharda** [comment]
Thanks @eolivelli, I've raised a draft pull request #4835, which I believe should resolve your issue, but I'm not 100% sure. If possible, could you please try your deployment with this change and see if it resolves your issue?
