### ISSUE TITLE
./gradlew test gets stuck on the EventProcessorTest due to lack of threads

### ISSUE THREAD

**Issue by jameskim0987** [pravega/pravega#4839]
**Problem description**
I have successfully installed and built Pravega and now I'm trying to run the unit tests. 
However, I get stuck on these tests with the following messages:

io.pravega.test.integration.MultiReadersEndToEndTest > testReadersEqualToSegments PASSED

io.pravega.test.integration.MultiReadersEndToEndTest > testReadersGreaterThanSegments PASSED
[370.152s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[370.152s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[370.153s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[370.153s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[370.154s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[370.155s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[370.156s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[370.157s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[370.158s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.

io.pravega.test.integration.MultiReadersEndToEndTest > testMultiStreams FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
        at java.base@11.0.7/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@11.0.7/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.base@11.0.7/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
        at java.base@11.0.7/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
        at java.base@11.0.7/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
        at java.base@11.0.7/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2043)
        at app//io.pravega.client.segment.impl.ConditionalOutputStreamImpl.lambda$write$1(ConditionalOutputStreamImpl.java:81)
        at app//io.pravega.client.segment.impl.ConditionalOutputStreamImpl$$Lambda$1258/0x00000008005e6440.attempt(Unknown Source)
        at app//io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:173)
        at app//io.pravega.client.segment.impl.ConditionalOutputStreamImpl.write(ConditionalOutputStreamImpl.java:69)
        at app//io.pravega.client.state.impl.RevisionedStreamClientImpl.writeConditionally(RevisionedStreamClientImpl.java:92)
        at app//io.pravega.client.state.impl.StateSynchronizerImpl.initialize(StateSynchronizerImpl.java:173)
        at app//io.pravega.client.stream.mock.MockStreamManager.createReaderGroup(MockStreamManager.java:162)
        at app//io.pravega.test.integration.MultiReadersEndToEndTest.runTestUsingMock(MultiReadersEndToEndTest.java:223)
        at app//io.pravega.test.integration.MultiReadersEndToEndTest.testMultiStreams(MultiReadersEndToEndTest.java:101)
[406.190s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[406.190s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[406.190s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[406.191s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[406.191s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[406.191s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[406.192s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[406.192s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[436.082s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[466.067s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[466.303s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.

io.pravega.test.integration.controller.server.EventProcessorTest > testEventProcessor FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
        at java.base@11.0.7/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@11.0.7/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.base@11.0.7/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
        at java.base@11.0.7/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
        at java.base@11.0.7/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
        at java.base@11.0.7/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2043)
        at app//io.pravega.test.integration.controller.server.EventProcessorTest.testEventProcessor(EventProcessorTest.java:225)

    java.lang.IllegalStateException: Expected the service ControllerServiceMain [FAILED] to be TERMINATED, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:366)
        at com.google.common.util.concurrent.AbstractService.awaitTerminated(AbstractService.java:329)
        at com.google.common.util.concurrent.AbstractExecutionThreadService.awaitTerminated(AbstractExecutionThreadService.java:223)
        at io.pravega.test.integration.demo.ControllerWrapper.close(ControllerWrapper.java:195)
        at io.pravega.test.integration.controller.server.EventProcessorTest.tearDown(EventProcessorTest.java:207)

        Caused by:
        java.lang.IllegalStateException: Expected the service ControllerServiceStarter [FAILED] to be TERMINATED, but the service has FAILED

            Caused by:
            java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[516.288s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.

io.pravega.test.integration.controller.server.EventProcessorTest > testEventProcessorFailover FAILED
    java.lang.IllegalStateException: Timed out waiting for watch removal
        at org.apache.curator.test.TestingZooKeeperMain.blockUntilStarted(TestingZooKeeperMain.java:146)
        at org.apache.curator.test.TestingZooKeeperServer.start(TestingZooKeeperServer.java:167)
        at org.apache.curator.test.TestingServer.<init>(TestingServer.java:117)
        at org.apache.curator.test.TestingServer.<init>(TestingServer.java:100)
        at org.apache.curator.test.TestingServer.<init>(TestingServer.java:41)
        at io.pravega.test.common.TestingServerStarter.start(TestingServerStarter.java:29)
        at io.pravega.test.integration.controller.server.EventProcessorTest.setUp(EventProcessorTest.java:181)

    java.lang.NullPointerException
        at io.pravega.test.integration.controller.server.EventProcessorTest.tearDown(EventProcessorTest.java:207)

io.pravega.test.integration.controller.server.EventProcessorTest > testEventProcessorRebalance FAILED
    java.lang.IllegalStateException: Timed out waiting for watch removal
        at org.apache.curator.test.TestingZooKeeperMain.blockUntilStarted(TestingZooKeeperMain.java:146)
        at org.apache.curator.test.TestingZooKeeperServer.start(TestingZooKeeperServer.java:167)
        at org.apache.curator.test.TestingServer.<init>(TestingServer.java:117)
        at org.apache.curator.test.TestingServer.<init>(TestingServer.java:100)
        at org.apache.curator.test.TestingServer.<init>(TestingServer.java:41)
        at io.pravega.test.common.TestingServerStarter.start(TestingServerStarter.java:29)
        at io.pravega.test.integration.controller.server.EventProcessorTest.setUp(EventProcessorTest.java:181)

    java.lang.NullPointerException
        at io.pravega.test.integration.controller.server.EventProcessorTest.tearDown(EventProcessorTest.java:207)
[566.334s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.

io.pravega.test.integration.controller.server.StreamMetadataTest > testMetadataOperations FAILED
    java.lang.IllegalStateException: Timed out waiting for watch removal
        at org.apache.curator.test.TestingZooKeeperMain.blockUntilStarted(TestingZooKeeperMain.java:146)
        at org.apache.curator.test.TestingZooKeeperServer.start(TestingZooKeeperServer.java:167)
        at org.apache.curator.test.TestingServer.<init>(TestingServer.java:117)
        at org.apache.curator.test.TestingServer.<init>(TestingServer.java:100)
        at org.apache.curator.test.TestingServer.<init>(TestingServer.java:41)
        at io.pravega.test.common.TestingServerStarter.start(TestingServerStarter.java:29)
        at io.pravega.test.integration.controller.server.StreamMetadataTest.testMetadataOperations(StreamMetadataTest.java:42)
[616.366s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.

io.pravega.test.integration.controller.server.DebugStreamSegmentsTest > testOutOfSequence FAILED
    java.lang.IllegalStateException: Timed out waiting for watch removal
        at org.apache.curator.test.TestingZooKeeperMain.blockUntilStarted(TestingZooKeeperMain.java:146)
        at org.apache.curator.test.TestingZooKeeperServer.start(TestingZooKeeperServer.java:167)
        at org.apache.curator.test.TestingServer.<init>(TestingServer.java:117)
        at org.apache.curator.test.TestingServer.<init>(TestingServer.java:100)
        at org.apache.curator.test.TestingServer.<init>(TestingServer.java:41)
        at io.pravega.test.common.TestingServerStarter.start(TestingServerStarter.java:29)
        at io.pravega.test.integration.controller.server.DebugStreamSegmentsTest.setUp(DebugStreamSegmentsTest.java:86)

    java.lang.NullPointerException
        at io.pravega.test.integration.controller.server.DebugStreamSegmentsTest.tearDown(DebugStreamSegmentsTest.java:107)
[666.468s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
<===========--> 89% EXECUTING [11m 25s]
> :test:integration:test > 39 tests completed, 6 failed
> :test:integration:test > Executing test io.pravega.test...controller.server.ControllerServiceTest

It has been apparent to me that there are error messages like
- [370.152s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
- or test timed out

**Problem location**
The stack trace is different for every failed test but I think it has to do with thread limit, failing to terminate threads, etc.

**Suggestions for an improvement**
I am completely lost as to how to approach this problem. I'm wondering if anyone has gone through this issue while running the unit tests.

**Comment by derekm** [comment]
What architecture and OS are you using? Is this a memory constrained device or VM? Max threads allowed is typically a dynamic figure based on stack size & total virtual memory available.

If you're running on a constrained device, this test may be exceeding your system resources. Logs above suggest a 1MB stack size.

**Comment by kgh475926** [comment]
The architecture I’m running on is 64-bit architecture on a 8GB RAM Macbook (not virtual machine).

**Comment by derekm** [comment]
@kgh475926 -- How were you able to get passed this issue?

**Comment by shiveshr** [comment]
@andreipaduroiu do you think this may have been fixed with all the thread pool improvements?
