### ISSUE TITLE
GRPC Upgrade to 1.30.0

### ISSUE THREAD

**Issue by diegosalvi** [pravega/pravega#4883]
**Suggestions for an improvement**
Hi, I've noticed that pravega uses an old grpc version 1.17. (Dec 2018)
Can you upgrade to a newer version like 1.30.0
New projects using pravega client cannot use latest grpc due to library incompatibility (when using 1.30.0 for example):
```
Caused by: java.lang.NoSuchMethodError: 'io.grpc.internal.AbstractManagedChannelImplBuilder io.grpc.netty.NettyChannelBuilder.loadBalancerFactory(io.grpc.LoadBalancer$Factory)'
	at io.pravega.client.stream.impl.ControllerImpl.<init>(ControllerImpl.java:146)
	at io.pravega.client.EventStreamClientFactory.withScope(EventStreamClientFactory.java:61)
	at io.pravega.segmentstore.server.host.stat.AutoScaleProcessor.createFactory(AutoScaleProcessor.java:162)
	at io.pravega.segmentstore.server.host.stat.AutoScaleProcessor.<init>(AutoScaleProcessor.java:77)
	at io.pravega.segmentstore.server.host.stat.AutoScaleMonitor.<init>(AutoScaleMonitor.java:45)
	at io.pravega.segmentstore.server.host.ServiceStarter.start(ServiceStarter.java:104)
	at io.pravega.local.InProcPravegaCluster.startLocalSegmentStore(InProcPravegaCluster.java:307)
	at io.pravega.local.InProcPravegaCluster.startLocalSegmentStores(InProcPravegaCluster.java:252)
	at io.pravega.local.InProcPravegaCluster.start(InProcPravegaCluster.java:206)
	at io.pravega.local.LocalPravegaEmulator.start(LocalPravegaEmulator.java:147)
	... 42 more
```

Currently I'm using grpc 1.19.0 and pravega works fine but I cannot upgrade it.

**Comment by derekm** [comment]
We had to back out the gRPC 1.31.0 upgrade due to conflicts and settled on gRPC 1.24.2.

1.24.2 still allows us to be brought into newer environments, but getting all the way to gRPC latest remains forthcoming.

**Comment by RaulGracia** [comment]
Current gRPC version is `1.39.0`, closing this issue.
