### ISSUE TITLE
ExtendedS3IntegrationTest: when s3Objects are listed, their sizes are null

### ISSUE THREAD

**Issue by ManishKumarKeshri** [pravega/pravega#4970]
**Problem description**
This was discovered during data recovery test. In the unit test `testDataRecovery` in `StreamSegmentStoreTestBase`, using different storage types, we had to skip using `ExtendedS3Storage`. This is because when segment list iterator validates `S3Object`'s length, it caused `NullPointerException`.

**Problem location**
Problem is with the mocking system of `ExtendedS3Storage`, and it exists in `ExtendedS3IntegrationTest`.

**Suggestions for an improvement**
Not sure about it.

**Comment by RaulGracia** [comment]
I think we have another instance of this problem: https://github.com/pravega/pravega/pull/5849/checks?check_run_id=2124687543
```
io.pravega.segmentstore.server.host.HDFSIntegrationTest > testDataRecovery FAILED
    java.lang.NullPointerException
        at io.pravega.segmentstore.server.containers.ContainerRecoveryUtils.recoverAllSegments(ContainerRecoveryUtils.java:105)
        at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.testSegmentRestoration(StreamSegmentStoreTestBase.java:236)
        at io.pravega.segmentstore.server.host.HDFSIntegrationTest.testDataRecovery(HDFSIntegrationTest.java:94)
```
[output.log.txt](https://github.com/pravega/pravega/files/6154831/output.log.txt)
