### ISSUE TITLE
DR integration test fails intermittently

### ISSUE THREAD

**Issue by ManishKumarKeshri** [pravega/pravega#4976]
**Problem description**
Data Recovery integration test(Recovery from complete loss of Durable data storage), fails like 1 out of 5 times. Interesting, adding some sleep(as less as 10 milli seconds) makes it not fail, and this issue was never found in travis build.  
```
2020-07-23 13:55:13,881 244419 [pool-161-thread-25] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[0]: Iteration[21].Error.io.pravega.segmentstore.contracts.StreamSegmentTruncatedException: [Segment 
'_system/containers/metadata_0$attributes.index'] Offsets 6000-7000 have been deleted.
	at io.pravega.segmentstore.storage.rolling.RollingStorage.checkTruncatedSegment(RollingStorage.java:793)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.read(RollingStorage.java:193)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$read$8(AsyncStorageWrapper.java:131)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:192)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment '_system/containers/metadata_0$attributes.index$offset.6000'] The StreamSegment does not exist.
	at io.pravega.segmentstore.storage.mocks.InMemoryStorage.getStreamSegmentData(InMemoryStorage.java:236)
	at io.pravega.segmentstore.storage.mocks.InMemoryStorage.openRead(InMemoryStorage.java:114)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.read(RollingStorage.java:185)
	... 10 common frames omitted
```

**Problem location**
`RestoreBackUpDataRecoveryTest.java` in PR#4716

**Suggestions for an improvement**
Some future is not completed, when segments are restored, because it complains about some offsets being not found.

**Comment by ManishKumarKeshri** [comment]
It was fixed by letting the newly created container metadata to be flushed to LTS, before using the dataLog & storage instance to create new segmentstore instance.
