### ISSUE TITLE
Increased intermittent test failures

### ISSUE THREAD

**Issue by derekm** [pravega/pravega#4998]
**Problem description**
Consistently seeing this failure in builds on Actions CI matrix workflows (normal workflows work fine):
```
2020-07-29T18:22:56.5033584Z io.pravega.test.integration.CheckpointTest > testCheckpointAndRestore FAILED
2020-07-29T18:22:56.5033970Z     java.lang.AssertionError: expected:<Hello world
2020-07-29T18:22:56.5034294Z     > but was:<null>
2020-07-29T18:22:56.5034663Z         at org.junit.Assert.fail(Assert.java:88)
2020-07-29T18:22:56.5034994Z         at org.junit.Assert.failNotEquals(Assert.java:834)
2020-07-29T18:22:56.5035327Z         at org.junit.Assert.assertEquals(Assert.java:118)
2020-07-29T18:22:56.5035666Z         at org.junit.Assert.assertEquals(Assert.java:144)
2020-07-29T18:22:56.5036009Z         at io.pravega.test.integration.CheckpointTest.testCheckpointAndRestore(CheckpointTest.java:153)
```

**Problem location**
Several failures here are caused by it: https://github.com/pravega/pravega/actions?query=workflow%3A%22build+merge%22

**Suggestions for an improvement**
Is a constrained environment increasing intermittent failures?

**Comment by derekm** [comment]
Here's all the intermittent failures I'm seeing in Action CI:

```
2020-07-29T20:40:07.1098454Z io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testWriteFenceOut FAILED
2020-07-29T20:40:07.1099041Z     org.junit.runners.model.TestTimedOutException: test timed out after 100000 milliseconds
2020-07-29T20:40:07.1099307Z         at sun.misc.Unsafe.park(Native Method)
2020-07-29T20:40:07.1099506Z         at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
2020-07-29T20:40:07.1099677Z         at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:837)
2020-07-29T20:40:07.1099852Z         at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:872)
2020-07-29T20:40:07.1100031Z         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
2020-07-29T20:40:07.1100196Z         at com.google.common.util.concurrent.Monitor.awaitNanos(Monitor.java:1223)
2020-07-29T20:40:07.1100335Z         at com.google.common.util.concurrent.Monitor.enterWhenUninterruptibly(Monitor.java:648)
2020-07-29T20:40:07.1100499Z         at com.google.common.util.concurrent.AbstractService.awaitTerminated(AbstractService.java:337)
2020-07-29T20:40:07.1100664Z         at io.pravega.segmentstore.server.ServiceListeners.awaitShutdown(ServiceListeners.java:48)
2020-07-29T20:40:07.1100835Z         at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testWriteFenceOut(StreamSegmentContainerTests.java:1514)


2020-07-29T19:09:52.2356403Z io.pravega.test.integration.CheckpointTest > testCheckpointAndRestore FAILED
2020-07-29T19:09:52.2356639Z     java.lang.AssertionError: expected:<Hello world
2020-07-29T19:09:52.2356770Z     > but was:<null>
2020-07-29T19:09:52.2356999Z         at org.junit.Assert.fail(Assert.java:88)
2020-07-29T19:09:52.2357154Z         at org.junit.Assert.failNotEquals(Assert.java:834)
2020-07-29T19:09:52.2357492Z         at org.junit.Assert.assertEquals(Assert.java:118)
2020-07-29T19:09:52.2360475Z         at org.junit.Assert.assertEquals(Assert.java:144)
2020-07-29T19:09:52.2360867Z         at io.pravega.test.integration.CheckpointTest.testCheckpointAndRestore(CheckpointTest.java:153)


2020-07-29T18:22:56.5033584Z io.pravega.test.integration.CheckpointTest > testCheckpointAndRestore FAILED
2020-07-29T18:22:56.5033970Z     java.lang.AssertionError: expected:<Hello world
2020-07-29T18:22:56.5034294Z     > but was:<null>
2020-07-29T18:22:56.5034663Z         at org.junit.Assert.fail(Assert.java:88)
2020-07-29T18:22:56.5034994Z         at org.junit.Assert.failNotEquals(Assert.java:834)
2020-07-29T18:22:56.5035327Z         at org.junit.Assert.assertEquals(Assert.java:118)
2020-07-29T18:22:56.5035666Z         at org.junit.Assert.assertEquals(Assert.java:144)
2020-07-29T18:22:56.5036009Z         at io.pravega.test.integration.CheckpointTest.testCheckpointAndRestore(CheckpointTest.java:153)


2020-07-29T18:18:30.9710746Z io.pravega.test.integration.CheckpointTest > testCheckpointAndRestore FAILED
2020-07-29T18:18:30.9711010Z     java.lang.AssertionError: expected:<Hello world
2020-07-29T18:18:30.9711241Z     > but was:<null>
2020-07-29T18:18:30.9711464Z         at org.junit.Assert.fail(Assert.java:88)
2020-07-29T18:18:30.9711688Z         at org.junit.Assert.failNotEquals(Assert.java:834)
2020-07-29T18:18:30.9711918Z         at org.junit.Assert.assertEquals(Assert.java:118)
2020-07-29T18:18:30.9712164Z         at org.junit.Assert.assertEquals(Assert.java:144)
2020-07-29T18:18:30.9712403Z         at io.pravega.test.integration.CheckpointTest.testCheckpointAndRestore(CheckpointTest.java:153)


2020-07-29T18:50:21.5730529Z io.pravega.segmentstore.server.store.StreamSegmentServiceTests > testEndToEndWithFencing FAILED
2020-07-29T18:50:21.5731226Z     java.lang.AssertionError: Unexpected Read Index length for segment Segment_8 expected:<1190> but was:<1202>


2020-07-29T19:34:49.6376770Z io.pravega.storage.extendeds3.ExtendedS3StorageTest$RollingStorageTests > testOpen FAILED
2020-07-29T19:34:49.6377117Z     java.net.BindException: Address already in use
2020-07-29T19:34:49.6377391Z         at java.base/sun.nio.ch.Net.bind0(Native Method)
2020-07-29T19:34:49.6377668Z         at java.base/sun.nio.ch.Net.bind(Net.java:479)
2020-07-29T19:34:49.6379548Z         at java.base/sun.nio.ch.Net.bind(Net.java:468)
2020-07-29T19:34:49.6382851Z         at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
2020-07-29T19:34:49.6383205Z         at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:88)
2020-07-29T19:34:49.6383519Z         at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
2020-07-29T19:34:49.6383847Z         at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
2020-07-29T19:34:49.6384321Z         at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
2020-07-29T19:34:49.6385056Z         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
2020-07-29T19:34:49.6385547Z         at org.eclipse.jetty.server.Server.doStart(Server.java:366)
2020-07-29T19:34:49.6386042Z         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
2020-07-29T19:34:49.6387180Z         at org.gaul.s3proxy.S3Proxy.start(S3Proxy.java:389)
2020-07-29T19:34:49.6387548Z         at io.pravega.storage.extendeds3.S3ProxyImpl.start(S3ProxyImpl.java:83)
2020-07-29T19:34:49.6387911Z         at io.pravega.storage.extendeds3.ExtendedS3StorageTest$TestContext.<init>(ExtendedS3StorageTest.java:336)
2020-07-29T19:34:49.6388536Z         at io.pravega.storage.extendeds3.ExtendedS3StorageTest$RollingStorageTests.setUp(ExtendedS3StorageTest.java:299)


2020-07-29T21:09:53.3336290Z io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testForcedMetadataCleanup FAILED
2020-07-29T21:09:53.3336487Z     java.lang.AssertionError: CacheManager closed with 1 outstanding bytes.
2020-07-29T21:09:53.3336666Z         at io.pravega.segmentstore.server.CacheManager.close(CacheManager.java:129)
2020-07-29T21:09:53.3336875Z         at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests$TestContext.close(StreamSegmentContainerTests.java:2240)
2020-07-29T21:09:53.3337072Z         at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testForcedMetadataCleanup(StreamSegmentContainerTests.java:1379)


2020-07-29T23:19:43.7878644Z io.pravega.segmentstore.server.logs.DurableLogTests > testTruncateWithoutRecovery FAILED
2020-07-29T23:19:43.7878986Z     java.lang.AssertionError:  Unexpected Sequence Number expected:<353> but was:<253>
2020-07-29T23:19:43.7879294Z         at org.junit.Assert.fail(Assert.java:88)
2020-07-29T23:19:43.7879583Z         at org.junit.Assert.failNotEquals(Assert.java:834)
2020-07-29T23:19:43.7880340Z         at org.junit.Assert.assertEquals(Assert.java:645)
2020-07-29T23:19:43.7880670Z         at io.pravega.segmentstore.server.logs.operations.OperationComparer.assertSame(OperationComparer.java:78)
2020-07-29T23:19:43.7881244Z         at io.pravega.segmentstore.server.logs.operations.OperationComparer.assertEquals(OperationComparer.java:66)
2020-07-29T23:19:43.7881617Z         at io.pravega.segmentstore.server.logs.DurableLogTests.testTruncateWithoutRecovery(DurableLogTests.java:1177)


2020-07-29T19:57:08.5692338Z io.pravega.segmentstore.server.mocks.SynchronousStreamSegmentStoreTests > testEndToEndWithFencing FAILED
2020-07-29T19:57:08.5692517Z     java.lang.AssertionError: Unexpected Read Index length for segment Segment_8 expected:<1190> but was:<1202>
```

**Comment by derekm** [comment]
These failures were caused by trying to use the matrix builds feature in GitHub Actions.

Matrix builds constrain container resources such that our time-sensitive tests begin to fail (dumb sleeps become too short or execution time timeouts are exhausted).

Separate workflows can be used instead of matrix builds, but this results in a lot of copy/paste.

Tests ought to be improved so that they don't rely so much on brute timing. This ticket could be repurposed for that our closed. Apparently it is easy enough to reproduce our intermittent test failures in Actions CI, just turn on matrix builds (even if there's only 1 value in the matrix)!

**Comment by derekm** [comment]
I have observed in the Travis CI build the same intermittent failure as reported in the OP:

https://travis-ci.org/github/pravega/pravega/jobs/714694163#L11143

```
io.pravega.test.integration.CheckpointTest > testCheckpointAndRestore FAILED
    java.lang.AssertionError: expected:<Hello world
    > but was:<null>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.pravega.test.integration.CheckpointTest.testCheckpointAndRestore(CheckpointTest.java:153)
```

This failure occurred in PR #5016.

**Comment by derekm** [comment]
Also was this failure in Travis CI:

```
io.pravega.segmentstore.server.reading.ContainerReadIndexTests > testFutureReads FAILED
    java.lang.AssertionError: Unexpected error happened while processing Segment 2: java.util.concurrent.CancellationException
        at org.junit.Assert.fail(Assert.java:88)
        at io.pravega.segmentstore.server.reading.ContainerReadIndexTests.testFutureReads(ContainerReadIndexTests.java:539)
```

**Comment by derekm** [comment]
A few more intermittent failures I've since observed:

https://travis-ci.org/github/pravega/pravega/jobs/714620050#L8352
```
2020-08-03 22:14:09,021 167702 [clientInternal-22-2] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while establishing connection with Pravega node null: 
java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: java.net.ConnectException: Connection refused (Connection refused)
```
Separately:
```
io.pravega.controller.eventProcessor.impl.SerializedRequestHandlerTest > testCancellation FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.pravega.controller.eventProcessor.impl.SerializedRequestHandlerTest.testCancellation(SerializedRequestHandlerTest.java:333)
```

**Comment by andreipaduroiu** [comment]
This issue is superseded by others which address the tests individually.
