### ISSUE TITLE
PDP-34 SLTS - flaky test - testEndToEndWithFencingWithChunkedStorage

### ISSUE THREAD

**Issue by sachin-j-joshi** [pravega/pravega#5010]
**Problem description**
StreamSegmentStoreTestBase::testEndToEndWithFencingWithChunkedStorage test fails intermittently because it can not make progress with `waitForSegmentsInStorage` .
It fails with 
```
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.endToEndProcessWithFencing(StreamSegmentStoreTestBase.java:388)
	at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.testEndToEndWithFencingWithChunkedStorage(StreamSegmentStoreTestBase.java:337)

```

The root cause seems to be related to ChunkNotFoundException thrown at claimOnwership called from openWrite. 

**Problem location**
StreamSegmentStoreTestBase::testEndToEndWithFencingWithChunkedStorage 
Possibly ChunkedSegmentStorage

**Suggestions for an improvement**
1. Short term ignore test.
2. The root cause for ChunkNotFoundException  must be identified and fixed.

**Comment by andreipaduroiu** [comment]
Root caused to #5009. Let's follow up in that issue.
