### ISSUE TITLE
Non blocking call EventStreamWriterImpl#writeEvent blocks current thread in case of unreachability of Segmentstore

### ISSUE THREAD

**Issue by eolivelli** [pravega/pravega#5139]
**Problem description**
We are using Pravega client 0.7.1 and Pravega server 0.7.1.
The  **EventStreamWriterImpl#writeEvent** is an asynchronous method the returns a CompletableFuture, the caller expects it to not perform significant blocking operations.

In case of Pravega cluster failure (see below), simple this method blocks the current thread.
Blocking the caller thread is bad because it is potentially holding resources and it prevents the system to work.
In the case of the stacktrace below the thread is serving an HTTP request.

It is quite easy to reproduce the problem, just by starting a single machine Pravega cluster (controller + segmentstore on the same machine + FILESYSTEM tier2, BK and ZK cluster are replicated and shared with other components of the application) and then **stopping gracefully the segmentstore service**.

**Problem location**
Pravega client code

This is a stacktrace (Pravega client 0.7.1)

 ```
java.lang.Thread.State: BLOCKED (on object monitor)
	at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEventInternal(EventStreamWriterImpl.java:118)
	- waiting to lock <0x0000000601dcd298> (a java.lang.Object)
	at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEvent(EventStreamWriterImpl.java:104)
	at magnews.gateway.pravega.PravegaOutputCollector.collect(PravegaOutputCollector.java:244)
	at magnews.gateway.logger.OutputCollectorFactoryFacade$OutputCollectorWrapper.collect(OutputCollectorFactoryFacade.java:369)
	at magnews.gateway.logger.InputEventsCollectors.collect(InputEventsCollectors.java:128)
	at magnews.gateway.logger.InputCollector.log(InputCollector.java:540)
	at magnews.gateway.messagemanager.MessageManager.acceptMessage(MessageManager.java:1204)
       ......
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	- locked <0x000000079cc635f0> (a org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@13.0.1/ThreadPoolExecutor.java:1128)

```

**Suggestions for an improvement**
Do not block the current thread, leave the control as soon as possible and defer the execution to other internal Pravega client thread.

**Comment by eolivelli** [comment]
This is the stacktrace of the thread that is holding the lock

```
"grpc-channel-server-2" #361 daemon prio=5 os_prio=0 cpu=42793.59ms elapsed=5077.77s tid=0x00007fd228020000 nid=0x13701 waiting on condition  [0x00007fd1ed15c000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@13.0.1/Native Method)
	- parking to wait for  <0x0000000769a28288> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(java.base@13.0.1/LockSupport.java:194)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@13.0.1/CompletableFuture.java:1867)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@13.0.1/ForkJoinPool.java:3137)
	at java.util.concurrent.CompletableFuture.waitingGet(java.base@13.0.1/CompletableFuture.java:1894)
	at java.util.concurrent.CompletableFuture.get(java.base@13.0.1/CompletableFuture.java:2069)
	at io.pravega.common.concurrent.Futures.getThrowingException(Futures.java:153)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl.write(SegmentOutputStreamImpl.java:470)
	- locked <0x000000060215ecd8> (a java.lang.Object)
	at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEventInternal(EventStreamWriterImpl.java:126)
	- locked <0x0000000601dcd2a8> (a java.lang.Object)
	- locked <0x0000000601dcd298> (a java.lang.Object)
	at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEvent(EventStreamWriterImpl.java:104)
	at magnews.gateway.pravega.PravegaOutputCollector.collect(PravegaOutputCollector.java:244)
	at magnews.gateway.logger.OutputCollectorFactoryFacade$OutputCollectorWrapper.collect(OutputCollectorFactoryFacade.java:369)
	at magnews.gateway.logger.InputEventsCollectors.collect(InputEventsCollectors.java:128)
	at magnews.gateway.logger.InputCollector.log(InputCollector.java:540)
	at magnews.gateway.messagemanager.MessageManager.acceptMessage(MessageManager.java:1204)
	at magnews.gateway.messagemanager.MessageManager.acceptMessage(MessageManager.java:1006)
	at magnews.gateway.messagemanager.MessageManager.acceptMessageFromInterfaces(MessageManager.java:818)
	at magnews.gateway.messagemanager.MessageManager.acceptMessageFromInterfaces(MessageManager.java:673)
	at magnews.gateway.messagemanager.GRPCServerMessageManager.submitWithTransaction(GRPCServerMessageManager.java:269)
	at magnews.gateway.remote.grpc.MessageServiceGrpc$MethodHandlers.invoke(MessageServiceGrpc.java:423)
```

**Comment by hamadodene** [comment]
This issue is **blocker** for us, is there any plan to fix it in the upcoming release?

**Comment by tkaitchuck** [comment]
It is intended that the write event call provide back pressure. It is not a completely non-blocking call. It's writing to an in-memory buffer and if no progress can be made (such as because the cluster is down) it blocks. This is to prevent an out of memory situation. 

I understand the desire to not have it blocking, but I am not clear on what the alternative is. We could perhaps delay this blocking a bit by making that connection acquisition occur in the background. But it would still end up in the same state after 1 or 2 mb of data were written. Surely don't want that to grow unbounded and run out of memory.

Is your preference that the method throw or perhaps the future should throw?

**Comment by eolivelli** [comment]
I would expect that the Future throws after some timeout (immediately is a good option as well).

**Comment by shrids** [comment]
I was dabbling with the thought of adding a timeout  @ 
https://github.com/pravega/pravega/blob/7e191fb8b3aedf9440028d6a639cb3c084510a1b/client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java#L477

This would imply that the `EventStreamWriter `would still have the current backpressure mechanism but on a `TimeOutException `thrown by the segment writer, the event writer would stop all writes and ensure the completable futures for the un-acked events are completed exceptionally. This would also imply the retransmission of inflight events in the event of a SealedSegment should also be stopped.

But in the case of Segment container failovers, the writers would not be able to establish a connection with just a few of the segments. In this scenario a `EventStreamWriter.flush()` API invocation should throw an Exception indicating a connection failure only after retrying for the Segment container recovery duration. My understanding is that the timeout should be in the order of minutes. 
(Also, This change would impact all the transaction writer, ByteStreamWriter, and the RevisionedStreamClient)

@tkaitchuck @eolivelli let me know your thoughts.

**Comment by eolivelli** [comment]
From the caller perspective it is important that the method does not block for a significant amount of time.

A timeout in the order of minutes is good, as far as we see it as a result of the CompletableFuture.
In fact I would expect that behavior: the client waits/retries depending on the configuration and it gives up after a configurable amount of time.

It will be important that the user is able to understand that the error returned on the CompletableFuture indicates that the event was not sent (like a Connection error) and that it can be safely retransmitted.

**Comment by eolivelli** [comment]
If a connection is not available we should defer the block to another thread or something like that.

**Comment by tkaitchuck** [comment]
I think we can achieve this. @shrids I am assigning this to you.

**Comment by shrids** [comment]
The client maintains the list of inflight events which have been transmitted until it receives an ack from the Segment store. 
So with the `TimeoutException `approach, the user will see that the `CompletableFuture`s for all the inflight events terminating with a `TimeoutException `since the writer is not able to connect back to the Segment store. But this implies that application will not know for sure if the inflight events are persisted or not.

@tkaitchuck Can this mechanism be improved further?

**Comment by eolivelli** [comment]
@shrids are we also performing the "connection" handshake in the application thread ?

My from point of view it would be better that the application thread does not perform any kind of blocking operation,
ideally a "write" should be as simple as submitting a task to a queue, nothing more.

**Comment by shrids** [comment]
No, we are not performing the connection handshake in the application thread; it is performed on the internal executor.

**Comment by tkaitchuck** [comment]
We could have logic to where if a connection is not established and it is in progress, and the inflight is below a certain amount we could simply add to the inflight and return. This would reduce the latency for the first several calls to write before a connection can be established. However in the situation above where the cluster is down, we don't want to silently accept messages forever only to run out of memory. We need a mechanism to give up on connecting because too many attempts have been made, and fail all inflight events. This is highly undesirable because it can leave events in an unknown state as they may have been sent and not acked but in fact persisted. However it may be preferable to blocking forever depending on the application.

**Comment by eolivelli** [comment]
From an  user point I expect tunables like `blockIfQueueFull`, `sendTimeoutMs`, `maxPendingMessages` in [Pulsar Java Client](https://pulsar.apache.org/docs/en/client-libraries-java/)

**Comment by shrids** [comment]
Thanks for your inputs @tkaitchuck @eolivelli . 
My plan of action for this issue is to ensure we do not infinitely retry attempting to establish a connection and use the same retry count as specified in the EventWriterConfig. Post which the CompletableFutures would be exceptionally completed incase all the attempts fail. 
The change also needs to ensure the resend logic of inflight events to successor segments (sealed segment handling) during such a connection failure scenario is also terminated. This part of the code is proving to be tricky to validate all possible corner cases.

Also, the plan is to first fix it on the main line (0.9.0) client which has no dependency on netty. Porting this change back to 0.7.x which uses netty needs further validation and perhaps more changes.

**Comment by eolivelli** [comment]
@shrids probably it is enough to see a fix in 0.9.0 and in 0.8.2.
As soon as we release 0.8.2, 0.7.x client would become obsolete.

I am not aware of an EOF policy for Pravega client, but if there is one it should be stated on the website (cc @derekm )

**Comment by eolivelli** [comment]
@diegosalvi @hamadodene it looks like @shrids pushed #5139 that addresses our issue !
thank you @shrids

**Comment by hamadodene** [comment]
Good, thank you @shrids
