### ISSUE TITLE
Flaky test StreamMetadataTest#testMetadataOperations on 0.8.0rc1 code

### ISSUE THREAD

**Issue by eolivelli** [pravega/pravega#5211]
**Problem description**
While testing 0.8.0rc1 I saw this flaky test.
I am using JDK11 on Mac

i```
o.pravega.test.integration.controller.server.StreamMetadataTest > testMetadataOperations FAILED
    java.lang.NullPointerException
        at io.pravega.controller.task.Stream.StreamMetadataTasks.sealStream(StreamMetadataTasks.java:494)
        at io.pravega.controller.server.ControllerService.sealStream(ControllerService.java:224)
        at io.pravega.controller.server.eventProcessor.LocalController.sealStream(LocalController.java:212)
        at io.pravega.test.integration.controller.server.StreamMetadataTest.testMetadataOperations(StreamMetadataTest.java:93)
```

**Problem location**
The test

**Suggestions for an improvement**
Make the test consistently pass

**Comment by RaulGracia** [comment]
Found another instance of this test failing for this PR #5471 (https://travis-ci.org/github/pravega/pravega/builds/753548875):
```
io.pravega.test.integration.controller.server.StreamMetadataTest > testMetadataOperations FAILED
    java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Scope does not exist: StreamConfiguration(scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=2), retentionPolicy=null, timestampAggregationTimeout=0)
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at io.pravega.test.integration.controller.server.StreamMetadataTest.testMetadataOperations(StreamMetadataTest.java:81)
        Caused by:
        java.lang.IllegalArgumentException: Scope does not exist: StreamConfiguration(scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=2), retentionPolicy=null, timestampAggregationTimeout=0)
            at io.pravega.controller.server.eventProcessor.LocalController.lambda$createStream$11(LocalController.java:161)
            at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
            at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
            at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
            at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
            at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:834)
            ```

**Comment by shiveshr** [comment]
The first instance is because of introduction of eventHelper in streammetadatatasks that is not necessarily initialized in the constructor but after creating the object and with an explicit initialize method. 
this can cause the race that if the request is received before this initialize can happen, then we could get NPE. So this is not just a test issue but a code bug. 
@pbelgundi

**Comment by shiveshr** [comment]
For second instance, the DATA_NOT_FOUND is translated to scope does not exist.
i think there is another race there which is causing DATA_NOT_FOUND exception getting thrown during create stream.
