### ISSUE TITLE
Flaky Junit tests

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#5321]
**Problem description**
The following junits are flaky and causes multiple Travis build failures.
1. 
```
io.pravega.controller.server.eventProcessor.ControllerEventProcessorsTest > testTruncate FAILED

    org.mockito.exceptions.misusing.UnfinishedStubbingException: 

    Unfinished stubbing detected here:

    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessorsTest.testTruncate(ControllerEventProcessorsTest.java:296)

    E.g. thenReturn() may be missing.

    Examples of correct stubbing:

        when(mock.isOk()).thenReturn(true);

        when(mock.isOk()).thenThrow(exception);

        doThrow(exception).when(mock).someVoidMethod();

    Hints:

     1. missing thenReturn()

     2. you are trying to stub a final method, which is not supported

     3. you are stubbing the behaviour of another mock inside before 'thenReturn' instruction is completed

        at io.pravega.controller.server.eventProcessor.ControllerEventProcessorsTest.testTruncate(ControllerEventProcessorsTest.java:296)
```

2. 
```
io.pravega.test.integration.endtoendtest.EndToEndTruncationTest > testParallelSegmentOffsetTruncation FAILED
    java.lang.AssertionError: Expected read events:  expected:<50> but was:<75>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at io.pravega.test.integration.endtoendtest.EndToEndTruncationTest.testParallelSegmentOffsetTruncation(EndToEndTruncationTest.java:542)
```

**Problem location**
Controller and integration tests.

**Suggestions for an improvement**
fix it.

**Comment by shrids** [comment]
This issue has been fixed via https://github.com/pravega/pravega/pull/5322
