### ISSUE TITLE
(SLTS) NullPointerException in ReadIndexCache::evictChunks

### ISSUE THREAD

**Issue by sachin-j-joshi** [pravega/pravega#5347]
**Problem description**
NullPointerException is observed ReadIndexCache::evictChunks

**Problem location**
ReadIndexCache::evictChunks

**Suggestions for an improvement**
Check for null value

**Logs**
```
2020-11-04 05:01:07,734 79467372 [core-5] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[6]: Iteration[125261].Error.
java.lang.NullPointerException: null
        at io.pravega.segmentstore.storage.chunklayer.ReadIndexCache.evictChunks(ReadIndexCache.java:337)
        at io.pravega.segmentstore.storage.chunklayer.ReadIndexCache.evictChunks(ReadIndexCache.java:292)
        at io.pravega.segmentstore.storage.chunklayer.ReadIndexCache.addIndexEntry(ReadIndexCache.java:158)
        at io.pravega.segmentstore.storage.chunklayer.ReadOperation.lambda$findChunkForOffset$11(ReadOperation.java:205)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by sachin-j-joshi** [comment]
Closing this as, it should be superseded by new code #5363
