### ISSUE TITLE
Updating a KeyValueTable throws an InvalidClaimException against standalone with auth and TLS enabled

### ISSUE THREAD

**Issue by anirudhkovuru** [pravega/pravega#5374]
**Problem description**
The scope name is `SecureTestScope` and the table name is `SecureKvtTestTable`. When trying to update this `KeyValueTable` in the standalone with auth and TLS enabled, the following `InvalidClaimException` is thrown 
```
io.pravega.auth.InvalidClaimException: No matching claim found for resource: [SecureTestScope/SecureKvtTestTable_kvtable/2.#epoch.0] and permission: [READ] in the delegation token.
	at io.pravega.segmentstore.server.host.delegationtoken.TokenVerifierImpl.verifyToken(TokenVerifierImpl.java:68)
	at io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor.verifyToken(PravegaRequestProcessor.java:212)
	at io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor.updateTableEntries(PravegaRequestProcessor.java:640)
	at io.pravega.shared.protocol.netty.DelegatingRequestProcessor.updateTableEntries(DelegatingRequestProcessor.java:120)
	at io.pravega.shared.protocol.netty.WireCommands$UpdateTableEntries.process(WireCommands.java:1745)
	at io.pravega.segmentstore.server.host.handler.ServerConnectionInboundHandler.channelRead(ServerConnectionInboundHandler.java:57)
```
Looking further into the issue, the token used for the request is as follows,
```json
{
  "sub": "segmentstoreresource",
  "aud": "segmentstore",
  "iat": 1606299686,
  "prn::/scope:SecureTestScope/stream:SecureKvtTestTable": "READ_UPDATE",
  "exp": 1606300286
}
``` 
There is a mismatch in the permissions as inferred from the token and the exception.

**Problem location**
In the delegation token logic.

**Suggestions for an improvement**
Check the token related workflows when auth and TLS are enabled.

**Comment by ravisharda** [comment]
Confirming that this issue is a preexisting one and shows up in `r0.8` as well.
