### ISSUE TITLE
Issue when recreating a ReaderGroup with the same name as a previously deleted ReaderGroup

### ISSUE THREAD

**Issue by anirudhkovuru** [pravega/pravega#5465]
**Problem description**
After deleting a `ReaderGroup` on the controller using `controller.deleteReaderGroup`, recreating the group using the same name with the call `controller.createReaderGroup` fails with the following stacktrace:
```
io.pravega.controller.store.stream.StoreException$DataNotFoundException: addNewEntry: key: creationTime table: _system/_tables/test/_readergroups/group/metadata.#.6210110a-41f9-4ee9-b41b-709c640f5c49
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$DataNotFoundException: addNewEntry: key: creationTime table: _system/_tables/test/_readergroups/group/metadata.#.6210110a-41f9-4ee9-b41b-709c640f5c49
	at io.pravega.controller.task.Stream.StreamMetadataTasks.lambda$createReaderGroupTasks$34(StreamMetadataTasks.java:406)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at io.pravega.common.concurrent.Futures.lambda$completeOn$0(Futures.java:62)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.pravega.controller.store.stream.StoreException$DataNotFoundException: addNewEntry: key: creationTime table: _system/_tables/test/_readergroups/group/metadata.#.6210110a-41f9-4ee9-b41b-709c640f5c49
	at io.pravega.controller.store.stream.StoreException.create(StoreException.java:90)
	at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$exceptionalCallback$55(PravegaTablesStoreHelper.java:550)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.pravega.client.connection.impl.RawClient.reply(RawClient.java:126)
	at io.pravega.client.connection.impl.RawClient.access$300(RawClient.java:39)
	at io.pravega.client.connection.impl.RawClient$ResponseProcessor.process(RawClient.java:72)
	at io.pravega.client.connection.impl.FlowHandler.process(FlowHandler.java:204)
	at io.pravega.client.connection.impl.TcpClientConnection$ConnectionReader.run(TcpClientConnection.java:121)
	... 1 more
Caused by: io.pravega.controller.server.WireCommandFailedException: WireCommandFailed with type UPDATE_TABLE_ENTRIES reason SegmentDoesNotExist
	at io.pravega.controller.server.SegmentHelper.handleReply(SegmentHelper.java:680)
	at io.pravega.controller.server.SegmentHelper.lambda$updateTableEntries$13(SegmentHelper.java:419)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 8 more
```  
This can be recreated using the following snippet of code:
```java
Controller controller = controllerWrapper.getController();
String scope = "test";
String stream = "test";
controller.createScope(scope).join();
StreamConfiguration config = StreamConfiguration.builder().scalingPolicy(ScalingPolicy.fixed(1)).build();
controller.createStream(scope, stream, config).join();
String rgName = "myreadergroup";
controller.createReaderGroup(scope, rgName, ReaderGroupConfig.builder().disableAutomaticCheckpoints()
                                                                    .stream("test/test").build()).join();
ReaderGroupConfig rgConfig = controller.getReaderGroupConfig(scope, rgName).join();
controller.deleteReaderGroup(scope, rgName, rgConfig.getReaderGroupId(), rgConfig.getGeneration()).join();
controller.createReaderGroup(scope, rgName, ReaderGroupConfig.builder().disableAutomaticCheckpoints()
                                                                     .stream("test/test").build()).join();
```

**Problem location**
Controller

**Suggestions for an improvement**

**Comment by anirudhkovuru** [comment]
**Problem description**
When updating a `ReaderGroup` on the controller using `controller.updateReaderGroup` from a config with subscription to a config with no subscription, the program seems to hang and time out with the following stacktrace
```
java.util.concurrent.TimeoutException
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
	at io.pravega.controller.util.RetryHelper.lambda$loopWithTimeout$3(RetryHelper.java:72)
	at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:782)
	at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:753)
	at io.pravega.common.concurrent.Futures.runOrFail(Futures.java:644)
	at io.pravega.common.concurrent.Futures$Loop.run(Futures.java:797)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.TimeoutException
	... 13 more
```
This can be recreated using the following snippet
```
StreamConfiguration config = getStreamConfig();
Controller controller = controllerWrapper.getController();
controllerWrapper.getControllerService().createScope("test").get();
controller.createStream("test", "test", config).get();
// Create a ReaderGroup
ReaderGroupConfig rgconfig = ReaderGroupConfig.builder().disableAutomaticCheckpoints()
.stream("test/test").retentionType(ReaderGroupConfig.StreamDataRetention.MANUAL_RELEASE_AT_USER_STREAMCUT)
.build();
ReaderGroupConfig rgconfig2 = ReaderGroupConfig.builder().disableAutomaticCheckpoints()
.stream("test/test").readerGroupId(rgconfig.getReaderGroupId()).generation(rgconfig.getGeneration())
.build();
controller.createReaderGroup("test", "group", rgconfig).join();
controller.updateReaderGroup("test", "group", rgconfig2).join();
```

**Problem location**
Controller
