### ISSUE TITLE
updateReaderGroup hangs when changing ReaderGroup config from subscriber to non-subscriber

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#5467]
**Problem description**
When updating a ReaderGroup on the controller using controller.updateReaderGroup from a config with subscription to a config with no subscription, the program seems to hang and time out with the following stacktrace
```
java.util.concurrent.TimeoutException
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
	at io.pravega.controller.util.RetryHelper.lambda$loopWithTimeout$3(RetryHelper.java:72)
	at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:782)
	at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:753)
	at io.pravega.common.concurrent.Futures.runOrFail(Futures.java:644)
	at io.pravega.common.concurrent.Futures$Loop.run(Futures.java:797)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.TimeoutException
	... 13 more
```
**Problem location**
Controller

**Suggestions for an improvement**

**Comment by pbelgundi** [comment]
Issue can be reproduced suing following code snippet:
```
StreamConfiguration config = getStreamConfig();
Controller controller = controllerWrapper.getController();
controllerWrapper.getControllerService().createScope("test").get();
controller.createStream("test", "test", config).get();
// Create a ReaderGroup
ReaderGroupConfig rgconfig = ReaderGroupConfig.builder().disableAutomaticCheckpoints()
.stream("test/test").retentionType(ReaderGroupConfig.StreamDataRetention.MANUAL_RELEASE_AT_USER_STREAMCUT)
.build();
ReaderGroupConfig rgconfig2 = ReaderGroupConfig.builder().disableAutomaticCheckpoints()
.stream("test/test").readerGroupId(rgconfig.getReaderGroupId()).generation(rgconfig.getGeneration())
.build();
controller.createReaderGroup("test", "group", rgconfig).join();
controller.updateReaderGroup("test", "group", rgconfig2).join();
```
