### ISSUE TITLE
Unit test failure: StreamSegmentContainerTests.testTransactionOperations

### ISSUE THREAD

**Issue by derekm** [pravega/pravega#5480]
**Problem description**
1st stack trace:
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testTransactionOperations FAILED
    java.lang.UnsupportedOperationException: fail() not supported on RedirectedReadResultEntry
        at io.pravega.segmentstore.server.reading.RedirectedReadResultEntry.fail(RedirectedReadResultEntry.java:123)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadResult.close(StreamSegmentReadResult.java:136)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2026)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2011)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2006)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testTransactionOperations(StreamSegmentContainerTests.java:1256)
```
2nd stack trace:
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testTransactionOperations FAILED
    io.pravega.common.ObjectClosedException: Object 'StreamSegmentReadIndex' has been closed and cannot be accessed anymore.
        at io.pravega.common.Exceptions.checkNotClosed(Exceptions.java:255)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.getSingleReadResultEntry(StreamSegmentReadIndex.java:884)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.createRedirectedRead(StreamSegmentReadIndex.java:1042)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.getSingleReadResultEntry(StreamSegmentReadIndex.java:928)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.getMultiReadResultEntry(StreamSegmentReadIndex.java:955)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadResult.next(StreamSegmentReadResult.java:189)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadResult.next(StreamSegmentReadResult.java:26)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2032)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2011)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2006)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testTransactionOperations(StreamSegmentContainerTests.java:1256)
```

**Problem location**
`StreamSegmentContainerTests.testTransactionOperations`

**Suggestions for an improvement**
Test should pass reliably.

**Comment by andreipaduroiu** [comment]
Second one is related to #5485.
