### ISSUE TITLE
Test failure: RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking

### ISSUE THREAD

**Issue by derekm** [pravega/pravega#5481]
**Problem description**
1st stack trace:
```
io.pravega.test.integration.RestoreBackUpDataRecoveryTest > testDurableDataLogFailRecoveryWatermarking FAILED
    java.lang.IllegalStateException: The number of back-up metadata segments and containers should match.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
        at io.pravega.segmentstore.server.containers.ContainerRecoveryUtils.updateCoreAttributes(ContainerRecoveryUtils.java:310)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.runRecovery(RestoreBackUpDataRecoveryTest.java:684
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking(RestoreBackUpDataRecoveryTest.java:778)
```
2nd stack trace:
```
io.pravega.test.integration.RestoreBackUpDataRecoveryTest > testDurableDataLogFailRecoveryWatermarking FAILED
    java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.stopDebugSegmentContainersPostFlush(RestoreBackUpDataRecoveryTest.java:541)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.runRecovery(RestoreBackUpDataRecoveryTest.java:687)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking(RestoreBackUpDataRecoveryTest.java:778)

        Caused by:
        java.lang.NullPointerException
            at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2086)
            at io.pravega.segmentstore.storage.impl.bookkeeper.Write.fail(Write.java:199)
            at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.lambda$close$1(BookKeeperLog.java:181)
            at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
            at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.close(BookKeeperLog.java:181)
            at io.pravega.segmentstore.server.logs.DurableLog.lambda$doStop$5(DurableLog.java:249)
            at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
            at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
            at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:834)
```

**Problem location**
`RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking`

**Suggestions for an improvement**
Test should pass reliably.

**Comment by RaulGracia** [comment]
Found another instance:
```
io.pravega.test.integration.RestoreBackUpDataRecoveryTest > testDurableDataLogFailRecoveryWatermarking FAILED
    java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.stopDebugSegmentContainersPostFlush(RestoreBackUpDataRecoveryTest.java:541)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.runRecovery(RestoreBackUpDataRecoveryTest.java:687)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking(RestoreBackUpDataRecoveryTest.java:778)
        Caused by:
        java.lang.NullPointerException
            at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2086)
            at io.pravega.segmentstore.storage.impl.bookkeeper.Write.fail(Write.java:199)
            at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.lambda$close$1(BookKeeperLog.java:181)
            at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
            at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.close(BookKeeperLog.java:181)
            at io.pravega.segmentstore.server.logs.DurableLog.lambda$doStop$5(DurableLog.java:249)
            at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
            at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
            at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:834)
            ```

**Comment by ManishKumarKeshri** [comment]
This PR #5513 should fix that error.

**Comment by shrids** [comment]
One more instance 

```
2021-02-10T09:51:11.2371409Z io.pravega.test.integration.RestoreBackUpDataRecoveryTest > testDurableDataLogFailRecoveryWatermarking FAILED
2021-02-10T09:51:11.2374085Z     java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Timeout expired while waiting for the Service to shut down.
2021-02-10T09:51:11.2376315Z         at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
2021-02-10T09:51:11.2378003Z         at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
2021-02-10T09:51:11.2381223Z         at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.stopDebugSegmentContainersPostFlush(RestoreBackUpDataRecoveryTest.java:541)
2021-02-10T09:51:11.2434045Z         at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.runRecovery(RestoreBackUpDataRecoveryTest.java:687)
2021-02-10T09:51:11.2438391Z         at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking(RestoreBackUpDataRecoveryTest.java:778)
2021-02-10T09:51:11.2441146Z 
2021-02-10T09:51:11.2441467Z         Caused by:
2021-02-10T09:51:11.2442324Z         java.util.concurrent.TimeoutException: Timeout expired while waiting for the Service to shut down.
2021-02-10T09:51:11.2444520Z             at io.pravega.common.concurrent.AbstractThreadPoolService.lambda$doStop$1(AbstractThreadPoolService.java:115)
2021-02-10T09:51:11.2446995Z             at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
2021-02-10T09:51:11.2448940Z             at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
2021-02-10T09:51:11.2450974Z             at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
2021-02-10T09:51:11.2453151Z             at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
2021-02-10T09:51:11.2455237Z             at io.pravega.common.concurrent.Futures.lambda$delayedFuture$23(Futures.java:588)
2021-02-10T09:51:11.2456694Z             at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2021-02-10T09:51:11.2458515Z             at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
2021-02-10T09:51:11.2460677Z             at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-02-10T09:51:11.2462417Z             at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-02-10T09:51:11.2463584Z             at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by RaulGracia** [comment]
@ManishKumarKeshri what is the status of your PR fixing the flaky data recovery tests? DR are tests are among the ones that are currently making our builds to fail sporadically.

**Comment by ManishKumarKeshri** [comment]
The first trace in  this issue
```
io.pravega.test.integration.RestoreBackUpDataRecoveryTest > testDurableDataLogFailRecoveryWatermarking FAILED
    java.lang.IllegalStateException: The number of back-up metadata segments and containers should match.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
        at io.pravega.segmentstore.server.containers.ContainerRecoveryUtils.updateCoreAttributes(ContainerRecoveryUtils.java:310)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.runRecovery(RestoreBackUpDataRecoveryTest.java:684
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking(RestoreBackUpDataRecoveryTest.java:778)
```
was not fixed by this #5481, rest all are fixed with this.

was not fixed. Else,

**Comment by ManishKumarKeshri** [comment]
All kind of failures are fixed with PR #5513

**Comment by RaulGracia** [comment]
Saw the test failing again: https://github.com/pravega/pravega/runs/2032856146
```
io.pravega.test.integration.RestoreBackUpDataRecoveryTest > testDurableDataLogFailRecoveryWatermarking FAILED
    java.lang.IllegalStateException: The number of back-up metadata segments and containers should match.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
        at io.pravega.segmentstore.server.containers.ContainerRecoveryUtils.updateCoreAttributes(ContainerRecoveryUtils.java:310)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.runRecovery(RestoreBackUpDataRecoveryTest.java:681)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking(RestoreBackUpDataRecoveryTest.java:765)
```

**Comment by RaulGracia** [comment]
Another instance:
```
io.pravega.test.integration.RestoreBackUpDataRecoveryTest > testDurableDataLogFailRecoveryWatermarking FAILED
    java.lang.IllegalStateException: The number of back-up metadata segments and containers should match.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
        at io.pravega.segmentstore.server.containers.ContainerRecoveryUtils.updateCoreAttributes(ContainerRecoveryUtils.java:310)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.runRecovery(RestoreBackUpDataRecoveryTest.java:681)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking(RestoreBackUpDataRecoveryTest.java:765)
```

**Comment by shrids** [comment]
Another instance @ https://github.com/pravega/pravega/pull/5943/checks?check_run_id=2396569502

```
io.pravega.test.integration.RestoreBackUpDataRecoveryTest > testDurableDataLogFailRecoveryWatermarking FAILED
2021-04-21T02:48:40.5318566Z     java.lang.IllegalStateException: The number of back-up metadata segments and containers should match.
2021-04-21T02:48:40.5320231Z         at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
```
