### ISSUE TITLE
Unit test failure: ControllerEventProcessorsTest.testTruncate

### ISSUE THREAD

**Issue by derekm** [pravega/pravega#5483]
**Problem description**
1st stack trace:
```
io.pravega.controller.server.eventProcessor.ControllerEventProcessorsTest > testTruncate FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
        at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
        at java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1039)
        at java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
        at java.base@11.0.9.1/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
        at app//io.pravega.controller.server.eventProcessor.ControllerEventProcessorsTest.testTruncate(ControllerEventProcessorsTest.java:336)
```
2nd stack trace:
```
io.pravega.controller.server.eventProcessor.ControllerEventProcessorsTest > testTruncate FAILED
    Argument(s) are different! Wanted:
    checkpointStore.getPositions(
        "p1",
        "abortStreamReaders"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessorsTest.testTruncate(ControllerEventProcessorsTest.java:346)
    Actual invocations have different arguments:
    checkpointStore.getProcesses(
    
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:333)
    checkpointStore.getProcesses(
    
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:333)
    checkpointStore.getPositions(
        "p1",
        "scaleGroup"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:334)
    checkpointStore.getPositions(
        "p2",
        "scaleGroup"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:334)
    checkpointStore.getPositions(
        "p3",
        "scaleGroup"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:334)
    checkpointStore.getProcesses(
    
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:333)
    checkpointStore.getPositions(
        "p1",
        "kvtStreamReaders"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:334)
    checkpointStore.getPositions(
        "p2",
        "kvtStreamReaders"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:334)
    checkpointStore.getPositions(
        "p3",
        "kvtStreamReaders"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:334)
    checkpointStore.getProcesses(
    
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:333)
    checkpointStore.getPositions(
        "p1",
        "commitStreamReaders"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:334)
    checkpointStore.getPositions(
        "p2",
        "commitStreamReaders"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:334)
    checkpointStore.getPositions(
        "p3",
        "commitStreamReaders"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:334)
        at io.pravega.controller.server.eventProcessor.ControllerEventProcessorsTest.testTruncate(ControllerEventProcessorsTest.java:346)
```

**Problem location**
`ControllerEventProcessorsTest.testTruncate`

**Suggestions for an improvement**
Test should pass reliably.

**Comment by shiveshr** [comment]
i am able to reproduce it locally and get the stack trace:
```
2021-01-18 23:35:04,747 2232 [pool-1-thread-4] DEBUG i.p.c.s.e.ControllerEventProcessors - Encountered exception attempting to truncate stream _kvTableStream. {}
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.mockito.internal.invocation.InterceptedInvocation.getArgument(InterceptedInvocation.java:122)
	at io.pravega.controller.server.eventProcessor.ControllerEventProcessorsTest.lambda$testTruncate$6(ControllerEventProcessorsTest.java:304)
```

the failure happens here:
```
        when(checkpointStore.getPositions(any(), anyString())).thenAnswer(i -> {
            String key = i.getArgument(0);
```
this looks to be a mocking issue. i will try to see what is causing this.
