### ISSUE TITLE
Test failure: RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking

### ISSUE THREAD

**Issue by derekm** [pravega/pravega#5486]
**Problem description**
Stack trace:
```
io.pravega.test.integration.RestoreBackUpDataRecoveryTest > testDurableDataLogFailRecoveryWatermarking FAILED
    java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.stopDebugSegmentContainersPostFlush(RestoreBackUpDataRecoveryTest.java:541)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.runRecovery(RestoreBackUpDataRecoveryTest.java:687)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking(RestoreBackUpDataRecoveryTest.java:778)

        Caused by:
        java.lang.NullPointerException
            at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2086)
            at io.pravega.segmentstore.storage.impl.bookkeeper.Write.fail(Write.java:199)
            at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.lambda$close$1(BookKeeperLog.java:181)
            at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
            at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.close(BookKeeperLog.java:181)
            at io.pravega.segmentstore.server.logs.DurableLog.lambda$doStop$5(DurableLog.java:249)
            at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
            at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
            at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:834)
```

**Problem location**
`RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking`

**Suggestions for an improvement**
Test should pass reliably.

**Comment by derekm** [comment]
combined with #5481
