### ISSUE TITLE
Unit test failure: StreamCommandTest.classMethod

### ISSUE THREAD

**Issue by derekm** [pravega/pravega#5488]
**Problem description**
Stack trace:
```
io.pravega.cli.user.stream.StreamCommandTest > classMethod FAILED
    java.lang.IllegalStateException: Expected the service ControllerServiceStarter [FAILED] to be RUNNING, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:366)
        at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:302)
        at com.google.common.util.concurrent.AbstractIdleService.awaitRunning(AbstractIdleService.java:165)
        at io.pravega.test.integration.demo.ControllerWrapper.awaitRunning(ControllerWrapper.java:219)
        at io.pravega.test.integration.demo.ClusterWrapper.startController(ClusterWrapper.java:197)
        at io.pravega.test.integration.demo.ClusterWrapper.start(ClusterWrapper.java:152)
        at io.pravega.cli.user.stream.StreamCommandTest.start(StreamCommandTest.java:41)

        Caused by:
        java.lang.IllegalStateException: Expected the service GRPCServer [FAILED] to be RUNNING, but the service has FAILED
            at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:366)
            at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:302)
            at com.google.common.util.concurrent.AbstractIdleService.awaitRunning(AbstractIdleService.java:165)
            at io.pravega.controller.server.ControllerServiceStarter.startUp(ControllerServiceStarter.java:333)
            at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
            at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
            at java.base/java.lang.Thread.run(Thread.java:834)

            Caused by:
            java.io.IOException: Failed to bind
                at io.grpc.netty.NettyServer.start(NettyServer.java:246)
                at io.grpc.internal.ServerImpl.start(ServerImpl.java:184)
                at io.grpc.internal.ServerImpl.start(ServerImpl.java:90)
                at io.pravega.controller.server.rpc.grpc.GRPCServer.startUp(GRPCServer.java:80)
                ... 3 more

                Caused by:
                io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
```

**Problem location**
`StreamCommandTest.classMethod`

**Suggestions for an improvement**
Test should pass reliably.

**Comment by RaulGracia** [comment]
Closing this in favor of #5008.
