### ISSUE TITLE
Unit test failure: StreamCommandTest.testAppendAndReadStream

### ISSUE THREAD

**Issue by derekm** [pravega/pravega#5489]
**Problem description**
1st stack trace:
```
io.pravega.cli.user.stream.StreamCommandTest$SecureStreamCommandsTest > testAppendAndReadStream FAILED
    java.lang.OutOfMemoryError: Java heap space
        at io.pravega.common.util.CircularBuffer.<init>(CircularBuffer.java:33)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.<init>(SegmentInputStreamImpl.java:71)
        at io.pravega.client.segment.impl.SegmentInputStreamFactoryImpl.getEventSegmentReader(SegmentInputStreamFactoryImpl.java:64)
        at io.pravega.client.segment.impl.SegmentInputStreamFactoryImpl.getEventSegmentReader(SegmentInputStreamFactoryImpl.java:58)
        at io.pravega.client.segment.impl.SegmentInputStreamFactoryImpl.createEventReaderForSegment(SegmentInputStreamFactoryImpl.java:48)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.acquireSegmentsIfNeeded(EventStreamReaderImpl.java:348)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.updateGroupStateIfNeeded(EventStreamReaderImpl.java:292)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:140)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:125)
        at io.pravega.cli.user.stream.StreamCommand$Read.execute(StreamCommand.java:260)
        at io.pravega.cli.user.TestUtils.executeCommand(TestUtils.java:42)
        at io.pravega.cli.user.stream.StreamCommandTest.testAppendAndReadStream(StreamCommandTest.java:122)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
2nd stack trace:
```
io.pravega.cli.user.stream.StreamCommandTest$SecureStreamCommandsTest > testAppendAndReadStream FAILED
    java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

        Caused by:
        java.lang.OutOfMemoryError: Java heap space
            at io.netty.util.internal.PlatformDependent.allocateUninitializedArray(PlatformDependent.java:281)
            at io.netty.buffer.UnpooledUnsafeHeapByteBuf.allocateArray(UnpooledUnsafeHeapByteBuf.java:39)
            at io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf.allocateArray(UnpooledByteBufAllocator.java:144)
            at io.netty.buffer.UnpooledHeapByteBuf.<init>(UnpooledHeapByteBuf.java:59)
            at io.netty.buffer.UnpooledUnsafeHeapByteBuf.<init>(UnpooledUnsafeHeapByteBuf.java:34)
            at io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf.<init>(UnpooledByteBufAllocator.java:139)
            at io.netty.buffer.UnpooledByteBufAllocator.newHeapBuffer(UnpooledByteBufAllocator.java:82)
            at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:168)
            at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:159)
            at io.netty.buffer.Unpooled.buffer(Unpooled.java:118)
            at io.pravega.client.connection.impl.CommandEncoder.<init>(CommandEncoder.java:78)
            at io.pravega.client.connection.impl.TcpClientConnection.lambda$connect$1(TcpClientConnection.java:200)
            at io.pravega.client.connection.impl.TcpClientConnection$$Lambda$570/0x00000001005ce840.get(Unknown Source)
            at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
            ... 6 more
```
3rd stack trace:
```
io.pravega.cli.user.stream.StreamCommandTest > testAppendAndReadStream FAILED
    java.lang.OutOfMemoryError: Java heap space
        at io.pravega.common.util.CircularBuffer.<init>(CircularBuffer.java:33)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.<init>(SegmentInputStreamImpl.java:71)
        at io.pravega.client.segment.impl.SegmentInputStreamFactoryImpl.getEventSegmentReader(SegmentInputStreamFactoryImpl.java:64)
        at io.pravega.client.segment.impl.SegmentInputStreamFactoryImpl.getEventSegmentReader(SegmentInputStreamFactoryImpl.java:58)
        at io.pravega.client.segment.impl.SegmentInputStreamFactoryImpl.createEventReaderForSegment(SegmentInputStreamFactoryImpl.java:48)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.acquireSegmentsIfNeeded(EventStreamReaderImpl.java:348)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.updateGroupStateIfNeeded(EventStreamReaderImpl.java:292)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:140)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:125)
        at io.pravega.cli.user.stream.StreamCommand$Read.execute(StreamCommand.java:260)
        at io.pravega.cli.user.TestUtils.executeCommand(TestUtils.java:42)
        at io.pravega.cli.user.stream.StreamCommandTest.testAppendAndReadStream(StreamCommandTest.java:117)
```

**Problem location**
`StreamCommandTest.testAppendAndReadStream`
`StreamCommandTest$SecureStreamCommandsTest.testAppendAndReadStream`

**Suggestions for an improvement**
Test should pass without additional heap space. A workaround was applied for this issue in #4988 by giving all Gradle Test tasks 2GB of heap instead of default 512MB.

**Comment by RaulGracia** [comment]
I don't remember to see this issue in the last months, so I assume it has been fixed with all the build refactoring we have done at the beginning of this year. Please, reopen if you remember any recent occurrence of it.
