### ISSUE TITLE
Unit test failure: SerializedRequestHandlerTest.testCancellation

### ISSUE THREAD

**Issue by derekm** [pravega/pravega#5496]
**Problem description**
Stack trace:
```
io.pravega.controller.eventProcessor.impl.SerializedRequestHandlerTest > testCancellation FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.pravega.controller.eventProcessor.impl.SerializedRequestHandlerTest.testCancellation(SerializedRequestHandlerTest.java:333)
```

**Problem location**
`SerializedRequestHandlerTest.testCancellation`

**Suggestions for an improvement**
Test should pass reliably.

**Comment by RaulGracia** [comment]
Fixed via #5566.
