### ISSUE TITLE
Unit test failure: deadlock after StreamSegmentServiceTests.testEndToEndWithChunkedStorage

### ISSUE THREAD

**Issue by derekm** [pravega/pravega#5499]
**Problem description**
Build got locked-up on a test and took more than 6 hours to fail.

**Problem location**
After `StreamSegmentServiceTests.testEndToEndWithChunkedStorage` as seen here: https://github.com/pravega/pravega/runs/1673700574?check_suite_focus=true

**Suggestions for an improvement**
Test should pass reliably.

**Comment by RaulGracia** [comment]
Found another kind of failure in the same test:
``` 
io.pravega.segmentstore.server.host.ExtendedS3IntegrationTest > testEndToEndWithChunkedStorage FAILED
    java.lang.AssertionError: CacheManager closed with 207 outstanding bytes.
        at io.pravega.segmentstore.server.CacheManager.close(CacheManager.java:130)
        at io.pravega.segmentstore.server.store.ServiceBuilder.close(ServiceBuilder.java:151)
        at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.endToEndProcess(StreamSegmentStoreTestBase.java:403)
        at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.testEndToEndWithChunkedStorage(StreamSegmentStoreTestBase.java:284)
```

**Comment by derekm** [comment]
@RaulGracia -- a similar "CacheManager closed with outstanding bytes" failure observed in #5491.
