### ISSUE TITLE
Unit test failure: io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testExtendedAttributesConditionalUpdates

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#5505]
**Problem description**
Found failure in the following unit test:
```
java.util.concurrent.ExecutionException: io.pravega.segmentstore.server.IllegalContainerStateException: Container 1234567 is in an invalid state for this operation. Expected: RUNNING; Actual: FAILED.
Stacktrace
java.util.concurrent.ExecutionException: io.pravega.segmentstore.server.IllegalContainerStateException: Container 1234567 is in an invalid state for this operation. Expected: RUNNING; Actual: FAILED.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testExtendedAttributesConditionalUpdates(StreamSegmentContainerTests.java:804)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.pravega.segmentstore.server.IllegalContainerStateException: Container 1234567 is in an invalid state for this operation. Expected: RUNNING; Actual: FAILED.
	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.ensureRunning(StreamSegmentContainer.java:852)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.append(StreamSegmentContainer.java:398)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests$MetadataCleanupContainer.lambda$appendRandomly$4(StreamSegmentContainerTests.java:2512)
	at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:784)
	at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:753)
	at io.pravega.common.concurrent.Futures.runOrFail(Futures.java:644)
	at io.pravega.common.concurrent.Futures$Loop.run(Futures.java:797)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
```

**Problem location**
`StreamSegmentContainerTests`

**Suggestions for an improvement**
Understand whether this is a test issue or a real bug and fix it.

**Comment by andreipaduroiu** [comment]
Same root cause as #5485.
