### ISSUE TITLE
Integration test failure: io.pravega.test.integration.ReadTest.testReceivingReadCall

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#5507]
**Problem description**
Found this integration test failing: https://travis-ci.org/github/pravega/pravega/jobs/753908662
```
io.pravega.test.integration.ReadTest > testReceivingReadCall FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.pravega.test.integration.ReadTest.testReceivingReadCall(ReadTest.java:166)
```

**Problem location**
`ReadTest.testReceivingReadCall`

**Suggestions for an improvement**
Make the test to pass consistently.

**Comment by RaulGracia** [comment]
Another reproduction:
```
io.pravega.test.integration.ReadTest > testReceivingReadCall FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.pravega.test.integration.ReadTest.testReceivingReadCall(ReadTest.java:166)
        ```
