### ISSUE TITLE
Test failures in RestoreBackUpDataRecoveryTest and admin CLI DataRecoveryTest

### ISSUE THREAD

**Issue by anirudhkovuru** [pravega/pravega#5510]
**Problem description**
The tests in the `RestoreBackUpDataRecoveryTest` (integration tests) and `DataRecoveryTest` (CLI admin tests) classes are failing after applying the changes from PR #5439. Following is the stacktrace from one of the tests:
```
addNewEntry: key: RG557894633 table: _system/_tables/testMetricsScope/readerGroupsInScope.#.cc5db182-ee86-4171-ad91-59e8f3a421fe
io.pravega.controller.store.stream.StoreException$DataNotFoundException: addNewEntry: key: RG557894633 table: _system/_tables/testMetricsScope/readerGroupsInScope.#.cc5db182-ee86-4171-ad91-59e8f3a421fe
	at io.pravega.controller.store.stream.StoreException.create(StoreException.java:90)
	at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$exceptionalCallback$55(PravegaTablesStoreHelper.java:550)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.pravega.client.connection.impl.RawClient.reply(RawClient.java:126)
	at io.pravega.client.connection.impl.RawClient.access$300(RawClient.java:39)
	at io.pravega.client.connection.impl.RawClient$ResponseProcessor.process(RawClient.java:72)
	at io.pravega.client.connection.impl.FlowHandler.process(FlowHandler.java:204)
	at io.pravega.client.connection.impl.TcpClientConnection$ConnectionReader.run(TcpClientConnection.java:121)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.pravega.controller.server.WireCommandFailedException: WireCommandFailed with type UPDATE_TABLE_ENTRIES reason SegmentDoesNotExist
	at io.pravega.controller.server.SegmentHelper.handleReply(SegmentHelper.java:680)
	at io.pravega.controller.server.SegmentHelper.lambda$updateTableEntries$13(SegmentHelper.java:419)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 8 more
```  

**Problem location**

**Suggestions for an improvement**

**Comment by derekm** [comment]
Similar `StoreException$DataNotFoundException` errors observed in #5497 & #5498.

Other failures of `RestoreBackUpDataRecoveryTest` observed in #5481.

**Comment by ManishKumarKeshri** [comment]
Thanks for reporting.

**Comment by ManishKumarKeshri** [comment]
In data recovery related tests, we write some data -> shut down zk/bk/controller/ss -> recover -> start a new instances of zk/bk/controller/ss and read the events back. Will this change cause a problem in starting the new controller instance and creating a reader with it to read the events back? @RaulGracia @anirudhkovuru @sachin-j-joshi

**Comment by pbelgundi** [comment]
@ManishKumarKeshri if the shutdown and restart of all components has completed successfully and is done in the right order, then there should not be any problem in reading events back.

**Comment by ManishKumarKeshri** [comment]
Thanks. I see that stack trace complains about a segment doesn't exist. We actually recover all segments, but need to look why it complains.

**Comment by ManishKumarKeshri** [comment]
Tests in `RestoreBackUpDataRecoveryTest` fail after recovery when we finally try to read all the events by [creating a reader group this point](https://github.com/pravega/pravega/blob/d4b1ef75484434c2e93822220ac9196245c08ebd/test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java#L1019).
The reason is:
```
Segment '_system/_tables/testMetricsScope/readerGroupsInScope.#.a01e351c-1e27-479a-96eb-3b4183c45a21' does not exist and cannot perform operation 'updateTableEntries'.
```
This segment was not present while we iterate over all segments in the storage, and therefore it was not recovered. Even without including this PR as before, this segment was not being recovered, but we could still create the reader group and read all events back. 
I have some questions and would be glad if you can answer @andreipaduroiu @sachin-j-joshi @pbelgundi 
This segment was not present in the storage, suggests that `flushToStorage` couldn't find it or it was never created?
When is this segment created?

**Comment by andreipaduroiu** [comment]
It gets created in LTS when the first byte is written to LTS.

**Comment by pbelgundi** [comment]
I have found the root cause for this issue and will raise a PR for the fix shortly.
