### ISSUE TITLE
Flaky Test StreamSegmentContainerTests > testTransactionOperations

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#5533]
**Problem description**

```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testTransactionOperations FAILED
    java.lang.AssertionError: getContent() did not return a completed future for segmentSegment_92
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2040)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2016)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2011)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testTransactionOperations(StreamSegmentContainerTests.java:1256)
```

**Problem location**

**Suggestions for an improvement**

**Comment by tkaitchuck** [comment]
I've seen with a different segment number.

```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testTransactionOperations FAILED
    java.lang.AssertionError: getContent() did not return a completed future for segmentSegment_42
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2049)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2025)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2020)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testTransactionOperations(StreamSegmentContainerTests.java:1256)
```

**Comment by RaulGracia** [comment]
Another occurrence: https://github.com/pravega/pravega/runs/2147802827
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testTransactionOperations FAILED
    java.lang.AssertionError: getContent() did not return a completed future for segmentSegment_36
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2050)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2026)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2021)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testTransactionOperations(StreamSegmentContainerTests.java:1257)
```

**Comment by RaulGracia** [comment]
Another repro: https://github.com/pravega/pravega/pull/5252/checks?check_run_id=2173695803
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testTransactionOperations FAILED
    java.lang.AssertionError: getContent() did not return a completed future for segmentSegment_20
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2050)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2026)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2021)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testTransactionOperations(StreamSegmentContainerTests.java:1257)
        ```
