### ISSUE TITLE
Flaky test: ContainerReadIndexTests > testCacheFullDeadlock

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#5534]
**Problem description**
```
io.pravega.segmentstore.server.reading.ContainerReadIndexTests > testCacheFullDeadlock FAILED
    java.util.concurrent.ExecutionException: io.pravega.segmentstore.storage.cache.CacheFullException: DirectMemoryCache full: Stored = 2093056, Used = 2097152, Reserved = 4096, Allocated = 2097152, Max = 2097152.
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
        at io.pravega.segmentstore.server.reading.ContainerReadIndexTests.testCacheFullDeadlock(ContainerReadIndexTests.java:2200)

        Caused by:
        io.pravega.segmentstore.storage.cache.CacheFullException: DirectMemoryCache full: Stored = 2093056, Used = 2097152, Reserved = 4096, Allocated = 2097152, Max = 2097152.
            at io.pravega.segmentstore.storage.cache.DirectMemoryCache.getNextAvailableBuffer(DirectMemoryCache.java:414)
            at io.pravega.segmentstore.storage.cache.DirectMemoryCache.insert(DirectMemoryCache.java:223)
            at io.pravega.segmentstore.server.reading.ContainerReadIndexTests$TestCacheStorage.insert(ContainerReadIndexTests.java:2569)
            at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.appendSingleEntryToCacheAndIndex(StreamSegmentReadIndex.java:577)
            at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.addToCacheAndIndex(StreamSegmentReadIndex.java:554)
            at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.append(StreamSegmentReadIndex.java:380)
            at io.pravega.segmentstore.server.reading.ContainerReadIndex.append(ContainerReadIndex.java:126)
            at io.pravega.segmentstore.server.reading.ContainerReadIndexTests.lambda$testCacheFullDeadlock$80(ContainerReadIndexTests.java:2192)
```

**Problem location**

**Suggestions for an improvement**

**Comment by RaulGracia** [comment]
Another reproduction here: https://github.com/pravega/pravega/runs/1858306361
