### ISSUE TITLE
Flaky Test: StreamMetricsTest > testStreamsAndScopesBasicMetricsTests

### ISSUE THREAD

**Issue by anirudhkovuru** [pravega/pravega#5543]
**Problem description**
The test fails with the following stacktrace:
```
io.pravega.test.integration.StreamMetricsTest > testStreamsAndScopesBasicMetricsTests FAILED
    java.lang.AssertionError: expected:<1> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.pravega.test.integration.StreamMetricsTest.testStreamsAndScopesBasicMetricsTests(StreamMetricsTest.java:202)
```

**Problem location**
Controller

**Suggestions for an improvement**
Debug the test.

**Comment by pbelgundi** [comment]
Fixed in PR 5439
