### ISSUE TITLE
Sporadic failure in ExtendedS3IntegrationTest.testEndToEnd

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#5565]
**Problem description**
```
io.pravega.segmentstore.server.host.ExtendedS3IntegrationTest > testEndToEnd FAILED
    io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to establish connection to ZooKeeper or BookKeeper.
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogFactory.initialize(BookKeeperLogFactory.java:116)
        at io.pravega.segmentstore.server.store.ServiceBuilder.initialize(ServiceBuilder.java:240)
        at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.createBuilder(StreamSegmentStoreTestBase.java:506)
        at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.endToEndProcess(StreamSegmentStoreTestBase.java:306)
        at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.testEndToEnd(StreamSegmentStoreTestBase.java:267)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Problem location**
ExtendedS3IntegrationTest

**Suggestions for an improvement**
Fix the flakey test

**Comment by RaulGracia** [comment]
Fixed via #4999.
