### ISSUE TITLE
Missing gradle dependency on netty-transport-native-epoll

### ISSUE THREAD

**Issue by leapsky** [pravega/pravega#5589]
**Problem description**

Pravega client (built with the new `build.gradle`) crashes throwing this exception...

```
11:33:09.637 [main] INFO io.pravega.client.connection.impl.SocketConnectionFactoryImpl - Shutting down connection factory
Exception in thread "main" java.lang.NoSuchMethodError: 'io.netty.buffer.ByteBuf io.netty.buffer.Unpooled.wrappedUnmodifiableBuffer(io.netty.buffer.ByteBuf[])'
        at io.pravega.shared.protocol.netty.WireCommands$Event.getAsByteBuf(WireCommands.java:496)
        at io.pravega.client.stream.impl.PendingEvent.getByteBuf(PendingEvent.java:85)
        at io.pravega.client.stream.impl.PendingEvent.withHeader(PendingEvent.java:60)
        at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEventInternal(EventStreamWriterImpl.java:125)
        at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEvent(EventStreamWriterImpl.java:114)
        at io.openmessaging.benchmark.driver.pravega.PravegaBenchmarkProducer.writeEvent(PravegaBenchmarkProducer.java:68)
        at io.openmessaging.benchmark.driver.pravega.PravegaBenchmarkProducer.sendAsync(PravegaBenchmarkProducer.java:62)
        at io.openmessaging.benchmark.worker.LocalWorker.lambda$probeProducers$8(LocalWorker.java:217)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at io.openmessaging.benchmark.worker.LocalWorker.probeProducers(LocalWorker.java:216)
        at io.openmessaging.benchmark.WorkloadGenerator.ensureTopicsAreReady(WorkloadGenerator.java:143)
        at io.openmessaging.benchmark.WorkloadGenerator.run(WorkloadGenerator.java:81)
        at io.openmessaging.benchmark.Benchmark.lambda$main$0(Benchmark.java:142)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at io.openmessaging.benchmark.Benchmark.lambda$main$1(Benchmark.java:127)
        at java.base/java.util.TreeMap.forEach(TreeMap.java:1002)
        at io.openmessaging.benchmark.Benchmark.main(Benchmark.java:126)
```

**Problem location**

`build.gradle`

**Suggestions for an improvement**

Revert PR **#5138** (Issue 5137: Remove dependency on netty-transport-native-epoll)

**Comment by shrids** [comment]
Tried the following snippet with Pravega client as a dependency.

```   
 WireCommands.Event e1 = new WireCommands.Event(Unpooled.wrappedBuffer("123".getBytes(StandardCharsets.UTF_8)));   
 System.out.println(new String(e1.getAsByteBuf().toString(StandardCharsets.UTF_8)));
```
It does work fine. 
Note:  `netty-buffer-4.1.50.Final.jar` is a dependency for the Pravega client.

**Comment by leapsky** [comment]
Thanks for your insight, Sandeep. The Pravega client works fine after adding `netty-buffer` as a dependency.
