### ISSUE TITLE
Flaky integration test EndToEndTruncationTest.testWriteDuringScaleAndTruncation

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#5599]
**Problem description**
We are recently seeing frequent failure of this integration test:
```
io.pravega.test.integration.endtoendtest.EndToEndTruncationTest > testWriteDuringScaleAndTruncation FAILED
    java.lang.RuntimeException: io.pravega.client.control.impl.ControllerFailureException: Failed to createing stream: StreamConfiguration(scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=1), retentionPolicy=null, timestampAggregationTimeout=0)
        at io.pravega.common.concurrent.Futures.getAndHandleExceptions(Futures.java:206)
        at io.pravega.client.admin.impl.ReaderGroupManagerImpl.createStreamHelper(ReaderGroupManagerImpl.java:79)
        at io.pravega.client.admin.impl.ReaderGroupManagerImpl.createReaderGroup(ReaderGroupManagerImpl.java:91)
        at io.pravega.test.integration.endtoendtest.EndToEndTruncationTest.testWriteDuringScaleAndTruncation(EndToEndTruncationTest.java:422)

        Caused by:
        io.pravega.client.control.impl.ControllerFailureException: Failed to createing stream: StreamConfiguration(scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=1), retentionPolicy=null, timestampAggregationTimeout=0)
            at io.pravega.controller.server.eventProcessor.LocalController.lambda$createStream$11(LocalController.java:156)
            at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
            at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
            at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
            at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
            at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:834)
```

**Problem location**
Integration tests.

**Suggestions for an improvement**
Fix the test.

**Comment by pbelgundi** [comment]
`ReaderGroupManagerImpl.createStreamHelper` invokes `controller.createStream` on an instance of LocalController which retries createStream only in case of LockFailure ( `LockFailedException`) and not otherwise. As such if stream creation fails due to some other intermittent issue it is not re-tried and causes the test case to fail with above RuntimeException.
This line of code is redundant and not necessary
```
private Stream createStreamHelper(String streamName, StreamConfiguration config) {
getAndHandleExceptions(controller.createStream(scope, streamName, StreamConfiguration.builder()
                                                                          .scalingPolicy(config.getScalingPolicy())
                                                                          .build()),
```

after the controller.createReaderGroup() API call was added and that can take care of doing stream creation with retries.

**Comment by shrids** [comment]
One more instance of this issue observed with additional logs ref: https://github.com/pravega/pravega/pull/5603/checks?check_run_id=1827637940

**Comment by pbelgundi** [comment]
The call to createStreamHelper() is being removed by this PR: https://github.com/pravega/pravega/pull/5720/
So I don;t expect to see this issue once that PR is merged.

**Comment by tkaitchuck** [comment]
We are still seeing issues with this test:
```
io.pravega.test.integration.endtoendtest.EndToEndTruncationTest > testWriteDuringScaleAndTruncation FAILED
    java.lang.IllegalStateException: Error creating StateSynchronizer Stream for Reader Group reader: FAILURE
        at io.pravega.controller.task.Stream.StreamMetadataTasks.lambda$createReaderGroupTasks$35(StreamMetadataTasks.java:422)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at io.pravega.controller.task.TaskBase.lambda$execute$1(TaskBase.java:136)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by pbelgundi** [comment]
Test run where the issue manifested again: https://github.com/pravega/pravega/runs/2024494235

**Comment by RaulGracia** [comment]
Another reproduction: https://github.com/pravega/pravega/pull/5832/checks?check_run_id=2085747710

**Comment by RaulGracia** [comment]
@pbelgundi this test seems to be failing quite frequently these days, please let us know if you have done progress to nail down the root cause.
