### ISSUE TITLE
Sporadic test failure OperationProcessorTests.testWithDataLogFailures

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#5642]
**Problem description**
Found a sporadic test failing `OperationProcessorTests.testWithDataLogFailures`:

```
io.pravega.segmentstore.server.logs.OperationProcessorTests > testWithDataLogFailures FAILED
    java.lang.AssertionError: CacheManager closed with 10 outstanding bytes.
        at io.pravega.segmentstore.server.CacheManager.close(CacheManager.java:130)
        at io.pravega.segmentstore.server.logs.OperationProcessorTests$TestContext.close(OperationProcessorTests.java:744)
        at io.pravega.segmentstore.server.logs.OperationProcessorTests.testWithDataLogFailures(OperationProcessorTests.java:332)
```
Note that this test was reported for a different type of failure in #5454.

**Problem location**
`OperationProcessorTests.testWithDataLogFailures`

**Suggestions for an improvement**
Understand if this is a real bug and fix the test.

**Comment by RaulGracia** [comment]
Another instance https://github.com/pravega/pravega/runs/1869538753

**Comment by tkaitchuck** [comment]
Another [here](https://github.com/pravega/pravega/pull/5834/checks?check_run_id=2089574316). Also exactly 10 bytes.

**Comment by kotlasaicharanreddy** [comment]
Another instance: https://github.com/pravega/pravega/runs/2873289795
