### ISSUE TITLE
Sporadic test failure in ReadWriteTest.readWriteTest

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#5659]
**Problem description**
Found test `io.pravega.test.integration.ReadWriteTest.readWriteTest` failing due to:
```
java.util.concurrent.ExecutionException: java.lang.InterruptedException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.pravega.test.integration.ReadWriteTest.readWriteTest(ReadWriteTest.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:385)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.pravega.common.concurrent.Futures.getThrowingException(Futures.java:178)
	at io.pravega.client.segment.impl.SegmentMetadataClientImpl.lambda$getSegmentInfo$13(SegmentMetadataClientImpl.java:239)
	at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:173)
	at io.pravega.client.segment.impl.SegmentMetadataClientImpl.getSegmentInfo(SegmentMetadataClientImpl.java:239)
	at io.pravega.client.state.impl.RevisionedStreamClientImpl.readFrom(RevisionedStreamClientImpl.java:134)
	at io.pravega.client.state.impl.StateSynchronizerImpl.fetchUpdates(StateSynchronizerImpl.java:82)
	at io.pravega.client.stream.impl.ReaderGroupStateManager.readerShutdown(ReaderGroupStateManager.java:155)
	at io.pravega.client.stream.impl.ReaderGroupStateManager.readerShutdown(ReaderGroupStateManager.java:147)
	at io.pravega.client.stream.impl.EventStreamReaderImpl.closeAt(EventStreamReaderImpl.java:414)
	at io.pravega.client.stream.impl.EventStreamReaderImpl.close(EventStreamReaderImpl.java:402)
	at io.pravega.test.integration.ReadWriteTest.lambda$startNewReader$1(ReadWriteTest.java:259)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
```

**Problem location**
`io.pravega.test.integration.ReadWriteTest.readWriteTest`

**Suggestions for an improvement**
Make the test to pass reliably.

**Comment by RaulGracia** [comment]
Noticed another reproduction, need to check if the root cause is the same or not.
