### ISSUE TITLE
Sporadic failure in HDFSIntegrationTest.testEndToEndWithChunkedStorage 

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#5685]
**Problem description**
Observed following unit test failure. 

```
io.pravega.segmentstore.server.host.HDFSIntegrationTest > testEndToEndWithChunkedStorage FAILED
    io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to establish connection to ZooKeeper or BookKeeper.
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogFactory.initialize(BookKeeperLogFactory.java:116)
        at io.pravega.segmentstore.server.store.ServiceBuilder.initialize(ServiceBuilder.java:240)
        at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.createBuilder(StreamSegmentStoreTestBase.java:506)
        at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.endToEndProcess(StreamSegmentStoreTestBase.java:332)
        at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.testEndToEndWithChunkedStorage(StreamSegmentStoreTestBase.java:284)
```

It may have to do with zk emulator not coming up correctly, and perhaps unrelated to pravega code itself. But it requires investigation. 

**Problem location**
HDFSIntegrationTest 

**Suggestions for an improvement**
The test should pass consistently

**Comment by kotlasaicharanreddy** [comment]
One more instance of failure: https://github.com/pravega/pravega/runs/7034675273?check_suite_focus=true
