### ISSUE TITLE
AttributeIndexTests is flakey

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#5701]
**Problem description**
```
io.pravega.segmentstore.server.attributes.AttributeIndexTests > testConcurrentReads FAILED
    java.lang.AssertionError: Expected one attempt to read root page from Storage. expected:<1> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at io.pravega.segmentstore.server.attributes.AttributeIndexTests.testConcurrentReads(AttributeIndexTests.java:591)
```

**Problem location**
AttributeIndexTests.java

**Comment by RaulGracia** [comment]
Another instance of this test failing, this time with:
```
java.lang.AssertionError: Expected a single storage read attempt for 782=782 expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at io.pravega.segmentstore.server.attributes.AttributeIndexTests.testConcurrentReads(AttributeIndexTests.java:617)
	```
