### ISSUE TITLE
Sporadic failure in test integration.ReadTest.testReceivingReadCall

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#5711]
**Problem description**
Found a sporadic in test `io.pravega.test.integration.ReadTest.testReceivingReadCall`:
```
io.pravega.test.integration.ReadTest > testReceivingReadCall FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertFalse(Assert.java:64)
        at org.junit.Assert.assertFalse(Assert.java:74)
        at io.pravega.test.integration.ReadTest.testReceivingReadCall(ReadTest.java:169)
```

**Problem location**
`io.pravega.test.integration.ReadTest.testReceivingReadCall`

**Suggestions for an improvement**
Fix the test.

**Comment by RaulGracia** [comment]
Closing in favor of #5714.
