### ISSUE TITLE
Sporadic test failure in AuthEnabledInProcPravegaClusterTest.testWriteAndReadEventWithValidClientConfig

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#5726]
**Problem description**
Found test `AuthEnabledInProcPravegaClusterTest.testWriteAndReadEventWithValidClientConfig` failing sporadically:
```
org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
	at java.base@11.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1079)
	at java.base@11.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369)
	at java.base@11.0.3/java.util.concurrent.Semaphore.tryAcquire(Semaphore.java:415)
	at app//io.pravega.client.stream.impl.EventStreamReaderImpl.lambda$blockFor$0(EventStreamReaderImpl.java:192)
	at app//io.pravega.client.stream.impl.EventStreamReaderImpl$$Lambda$1643/0x000000010095e040.run(Unknown Source)
	at app//io.pravega.common.Exceptions.handleInterrupted(Exceptions.java:115)
	at app//io.pravega.client.stream.impl.EventStreamReaderImpl.blockFor(EventStreamReaderImpl.java:190)
	at app//io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:147)
	at app//io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:125)
	at app//io.pravega.local.InProcPravegaClusterTest.testWriteAndReadEventWithValidClientConfig(InProcPravegaClusterTest.java:173)
	at java.base@11.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.3/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.3/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base@11.0.3/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.3/java.lang.Thread.run(Thread.java:834)
```
Full log can be found here: [log.txt](https://github.com/pravega/pravega/files/5967681/log.txt)

**Problem location**
`AuthEnabledInProcPravegaClusterTest.testWriteAndReadEventWithValidClientConfig`

**Suggestions for an improvement**
Fix the test.

**Comment by RaulGracia** [comment]
Just found another instance of this issue after the PR above was merged: https://github.com/pravega/pravega/pull/5586/checks?check_run_id=2119830625
```
io.pravega.local.InProcPravegaClusterTest > testWriteAndReadEventWithValidClientConfig FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
        at java.base@11.0.10/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@11.0.10/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.base@11.0.10/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
        at java.base@11.0.10/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
        at java.base@11.0.10/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
        at java.base@11.0.10/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998)
        at app//io.pravega.common.concurrent.Futures.getThrowingException(Futures.java:178)
        at app//io.pravega.client.admin.impl.StreamManagerImpl.createScope(StreamManagerImpl.java:131)
        at app//io.pravega.local.PravegaSanityTests.testWriteAndReadAnEvent(PravegaSanityTests.java:54)
        at app//io.pravega.local.InProcPravegaClusterTest.testWriteAndReadEventWithValidClientConfig(InProcPravegaClusterTest.java:50)
```

**Comment by shrids** [comment]
This issue ( https://github.com/pravega/pravega/pull/5586/checks?check_run_id=2119830625)  is on the file `InProcPravegaClusterTest` where there is no auth enabled.
