### ISSUE TITLE
Sporadic failure in test StreamTransactionMetadataTasksTest.writerInitializationTest

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#5728]
**Problem description**
Found test `StreamTransactionMetadataTasksTest.writerInitializationTest` failing sporadically:
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at io.pravega.controller.task.Stream.StreamTransactionMetadataTasksTest.writerInitializationTest(StreamTransactionMetadataTasksTest.java:714)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Full log can be found here: [log.txt](https://github.com/pravega/pravega/files/5967752/log.txt)

**Problem location**
`StreamTransactionMetadataTasksTest$RegularBookKeeperLogTests.writerInitializationTest`

**Suggestions for an improvement**
Fix the test.

**Comment by RaulGracia** [comment]
This is the comparison of this test in a failed and successful execution:
- Failed case:
```
2021-03-10 11:26:06,906 8444 [test-7] INFO  i.p.c.store.stream.ZkInt96Counter - Refreshing counter range. Current counter is Int96(msb=0, lsb=1). Current limit is Int96(msb=0, lsb=0)
 > 2021-03-10 11:26:06,959 8497 [test-1] INFO  i.p.c.store.stream.ZkInt96Counter - Refreshed counter range. Current counter is Int96(msb=0, lsb=0). Current limit is Int96(msb=0, lsb=10000)
 > 2021-03-10 11:26:07,212 8750 [test-10] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, added txn to host-txn index of host=host
 > 2021-03-10 11:26:07,359 8897 [test-1] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, created in store
 > 2021-03-10 11:26:07,413 8951 [Time-limited test] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, updating txn node in store and extending lease
 > 2021-03-10 11:26:07,441 8979 [test-1] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, added txn to host-txn index of host=host
 > 2021-03-10 11:26:07,507 9045 [test-9] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, updated txn node in store
 > 2021-03-10 11:26:07,519 9057 [test-9] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, extending lease in timeout service
 > 2021-03-10 11:26:07,548 9086 [test-2] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, added txn to host-txn index of host=host
 > 2021-03-10 11:26:07,685 9223 [TimerWheelService-3] DEBUG i.p.c.t.TimerWheelTimeoutService - Executing timeout task for txn scope/stream1/00000000-0000-0000-0000-000000000001
 > 2021-03-10 11:26:07,697 9235 [test-8] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, added txn to host-txn index of host=host
 > 2021-03-10 11:26:07,781 9319 [test-5] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, sealed successfully, commit=false
 > 2021-03-10 11:26:07,833 9371 [test-2] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Transaction 00000000-0000-0000-0000-000000000001 abort event posted
 > 2021-03-10 11:26:07,836 9374 [test-6] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, removed from timeout service
 > 2021-03-10 11:26:07,893 9431 [test-1] DEBUG i.p.c.store.stream.ZkOrderedStore - entity 00000000-0000-0000-0000-000000000001 added for stream scope/stream1 at position 0
 > 2021-03-10 11:26:07,911 9449 [test-9] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, failed sealing txn
 > 2021-03-10 11:26:07,935 9473 [test-6] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, removed txn from host-txn index of host=host
 > 2021-03-10 11:26:07,914 9452 [test-9] DEBUG io.pravega.common.util.Retry - Retrying command io.pravega.controller.task.Stream.StreamTransactionMetadataTasks$$Lambda$445/0x0000000840433440@54698aa3 Retry #2, timestamp=2021-03-10T10:26:07.913727Z
 > 2021-03-10 11:26:07,969 9507 [test-6] DEBUG i.p.c.t.TimerWheelTimeoutService - Successfully executed abort on tx scope/stream1/00000000-0000-0000-0000-000000000001 
 > 2021-03-10 11:26:08,087 9625 [test-1] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, added txn to host-txn index of host=host
 > 2021-03-10 11:26:08,164 9702 [test-7] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, failed sealing txn
 > 2021-03-10 11:26:08,174 9712 [Test worker] DEBUG o.a.c.f.imps.CuratorFrameworkImpl - Closing
 > 2021-03-10 11:26:08,178 9716 [Curator-Framework-0] INFO  o.a.c.f.imps.CuratorFrameworkImpl - backgroundOperationsLoop exiting
 > 2021-03-10 11:26:08,181 9719 [Test worker] DEBUG o.a.c.f.imps.WatcherRemovalManager - Removing watcher for path: /zookeeper/config
 > 2021-03-10 11:26:08,211 9749 [Test worker] DEBUG o.a.curator.CuratorZookeeperClient - Closing
 > 2021-03-10 11:26:08,211 9749 [Test worker] DEBUG org.apache.curator.ConnectionState - Closing
```

- Successful case:
```
2021-03-10 11:16:51,193 35714 [test-1] INFO  i.p.c.store.stream.ZkInt96Counter - Refreshing counter range. Current counter is Int96(msb=0, lsb=1). Current limit is Int96(msb=0, lsb=0)
2021-03-10 11:16:51,210 35731 [test-2] INFO  i.p.c.store.stream.ZkInt96Counter - Refreshed counter range. Current counter is Int96(msb=0, lsb=0). Current limit is Int96(msb=0, lsb=10000)
2021-03-10 11:16:51,315 35836 [test-10] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, added txn to host-txn index of host=host
2021-03-10 11:16:51,380 35901 [test-7] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, created in store
2021-03-10 11:16:51,486 36007 [Time-limited test] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, updating txn node in store and extending lease
2021-03-10 11:16:51,515 36036 [test-2] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, added txn to host-txn index of host=host
2021-03-10 11:16:51,531 36052 [test-5] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, updated txn node in store
2021-03-10 11:16:51,532 36053 [test-5] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, extending lease in timeout service
2021-03-10 11:16:51,543 36064 [test-4] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, added txn to host-txn index of host=host
2021-03-10 11:16:51,696 36217 [test-3] DEBUG i.p.c.store.stream.ZkOrderedStore - entity 00000000-0000-0000-0000-000000000001 added for stream scope/stream1 at position 0
2021-03-10 11:16:51,705 36226 [test-2] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, sealed successfully, commit=true
2021-03-10 11:16:51,712 36233 [test-5] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Transaction 00000000-0000-0000-0000-000000000001 commit event posted
2021-03-10 11:16:51,717 36238 [test-2] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, removed from timeout service
2021-03-10 11:16:51,780 36301 [test-8] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000001, removed txn from host-txn index of host=host
2021-03-10 11:16:51,838 36359 [test-7] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000002, added txn to host-txn index of host=host
2021-03-10 11:16:51,846 36367 [test-1] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000002, created in store
2021-03-10 11:16:51,857 36378 [test-7] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000002, added txn to host-txn index of host=host
2021-03-10 11:16:51,864 36385 [test-8] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000002, sealed successfully, commit=false
2021-03-10 11:16:51,870 36391 [test-8] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Transaction 00000000-0000-0000-0000-000000000002 abort event posted
2021-03-10 11:16:51,870 36391 [test-2] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000002, removed from timeout service
2021-03-10 11:16:51,880 36401 [test-7] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Txn=00000000-0000-0000-0000-000000000002, removed txn from host-txn index of host=host
2021-03-10 11:16:51,889 36410 [Test worker] DEBUG o.a.c.f.imps.CuratorFrameworkImpl - Closing
2021-03-10 11:16:51,891 36412 [Curator-Framework-0] INFO  o.a.c.f.imps.CuratorFrameworkImpl - backgroundOperationsLoop exiting
2021-03-10 11:16:51,892 36413 [Test worker] DEBUG o.a.c.f.imps.WatcherRemovalManager - Removing watcher for path: /zookeeper/config
2021-03-10 11:16:51,946 36467 [Test worker] DEBUG o.a.curator.CuratorZookeeperClient - Closing
2021-03-10 11:16:51,963 36484 [Test worker] DEBUG org.apache.curator.ConnectionState - Closing
```
At first glance, the main difference between the failed and successful execution is the role that `TimerWheelTimeoutService` plays, as it seems to be aborting the transaction before the the commit is executed, so makes the assertion in line 714 to fail. We need to know if there is a way to delay the start of `TimerWheelTimeoutService` or to disable it in these tests to prevent these race conditions. Another option would be to ping the transaction immediately after its creation, so the `TimerWheelTimeoutService` does not abort it. cc/ @shiveshr
