### ISSUE TITLE
testStateTracker failure

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#574]
**Problem description**
Running `StateSynchronizerTest` in a tight loop eventually gave me this:

```
com.emc.pravega.integrationtests.StateSynchronizerTest > testStateTracker FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 20000 milliseconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at com.emc.pravega.common.concurrent.FutureHelpers.lambda$getAndHandleExceptions$1(FutureHelpers.java:85)
        at com.emc.pravega.common.concurrent.FutureHelpers$$Lambda$104/34431269.call(Unknown Source)
        at com.emc.pravega.common.Exceptions.handleInterrupted(Exceptions.java:65)
        at com.emc.pravega.common.concurrent.FutureHelpers.getAndHandleExceptions(FutureHelpers.java:85)
        at com.emc.pravega.stream.mock.MockController.createSegment(MockController.java:111)
        at com.emc.pravega.stream.mock.MockController.createStream(MockController.java:61)
        at com.emc.pravega.stream.mock.MockStreamManager.createStreamHelper(MockStreamManager.java:67)
        at com.emc.pravega.stream.mock.MockStreamManager.createStream(MockStreamManager.java:58)
        at com.emc.pravega.integrationtests.StateSynchronizerTest.testStateTracker(StateSynchronizerTest.java:97)
```

**Problem location**
State synchronizer test case. This is the command I have run to get it:

```
while [ $? = 0 ]; do ./gradlew -Dtest.single=StateSynchronizerTest :integrationtests:clean :integrationtests:test; done
```

**Comment by fpj** [comment]
Doesn't seem to be an issue any longer.
