### ISSUE TITLE
Sporadic test failure DebugStreamSegmentContainerTests.testDataRecoveryContainerLevel

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#5799]
**Describe the bug**
Found test `DebugStreamSegmentContainerTests.testDataRecoveryContainerLevel` failing sporadically due to:
```
java.lang.AssertionError: Unexpected attribute for Segment_9 expected:<50> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at io.pravega.segmentstore.server.containers.DebugStreamSegmentContainerTests.testDataRecoveryContainerLevel(DebugStreamSegmentContainerTests.java:415)
```

**To Reproduce**
Sporadic test failure when executing `gradlew build`.

**Expected behavior**
Test must pass reliably.

**Screenshots**
NA

**Additional context**
NA

**Comment by ManishKumarKeshri** [comment]
Found this error on one build:

```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at java.base@11.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1798)
	at java.base@11.0.3/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1868)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at app//io.pravega.segmentstore.server.containers.ContainerRecoveryUtils.getExistingSegments(ContainerRecoveryUtils.java:186)
	at app//io.pravega.segmentstore.server.containers.ContainerRecoveryUtils.recoverAllSegments(ContainerRecoveryUtils.java:93)
	at app//io.pravega.segmentstore.server.containers.DebugStreamSegmentContainerTests.testDataRecoveryContainerLevel(DebugStreamSegmentContainerTests.java:396)
	at java.base@11.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.3/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.3/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base@11.0.3/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.3/java.lang.Thread.run(Thread.java:834)
```

**Comment by shrids** [comment]
One more failure observed for this test with a different stack trace...
```
2021-05-06T05:37:58.8082205Z io.pravega.segmentstore.server.containers.DebugStreamSegmentContainerTests > testDataRecoveryContainerLevel FAILED
2021-05-06T05:37:58.8086632Z     java.util.concurrent.ExecutionException: io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment '_system/containers/metadata_0$attributes.index'] The StreamSegment does not exist.
2021-05-06T05:37:58.8089287Z         at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
2021-05-06T05:37:58.8090956Z         at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
2021-05-06T05:37:58.8093558Z         at io.pravega.segmentstore.server.containers.ContainerRecoveryUtils.getExistingSegments(ContainerRecoveryUtils.java:192)
2021-05-06T05:37:58.8097368Z         at io.pravega.segmentstore.server.containers.ContainerRecoveryUtils.recoverAllSegments(ContainerRecoveryUtils.java:99)
2021-05-06T05:37:58.8102076Z         at io.pravega.segmentstore.server.containers.DebugStreamSegmentContainerTests.testDataRecoveryContainerLevel(DebugStreamSegmentContainerTests.java:402)
2021-05-06T05:37:58.8104923Z 
2021-05-06T05:37:58.8105237Z         Caused by:
2021-05-06T05:37:58.8107136Z         io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment '_system/containers/metadata_0$attributes.index'] The StreamSegment does not exist.
2021-05-06T05:37:58.8111245Z             at io.pravega.segmentstore.storage.mocks.InMemoryStorage.getStreamSegmentData(InMemoryStorage.java:244)
2021-05-06T05:37:58.8274810Z             at io.pravega.segmentstore.storage.mocks.InMemoryStorage.openRead(InMemoryStorage.java:122)
2021-05-06T05:37:58.8277364Z             at io.pravega.segmentstore.storage.rolling.RollingStorage.openHandle(RollingStorage.java:711)
2021-05-06T05:37:58.8279854Z             at io.pravega.segmentstore.storage.rolling.RollingStorage.openRead(RollingStorage.java:141)
2021-05-06T05:37:58.8282497Z             at io.pravega.segmentstore.storage.rolling.RollingStorage.read(RollingStorage.java:212)
2021-05-06T05:37:58.8284935Z             at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$read$8(AsyncStorageWrapper.java:143)
2021-05-06T05:37:58.8287609Z             at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:204)
2021-05-06T05:37:58.8289620Z             at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
2021-05-06T05:37:58.8291231Z             at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2021-05-06T05:37:58.8292546Z             at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2021-05-06T05:37:58.8294850Z             at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
2021-05-06T05:37:58.8297080Z             at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-05-06T05:37:58.8298856Z             at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-05-06T05:37:58.8300049Z             at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-06T05:37:58.8300485Z 
```
