### ISSUE TITLE
Sporadic test failure StreamMetricsTest.testStreamsAndScopesBasicMetricsTests

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#5803]
**Describe the bug**
Found the test `StreamMetricsTest.testStreamsAndScopesBasicMetricsTests` has been failing sporadically: https://github.com/pravega/pravega/pull/5744/checks?check_run_id=2025218244
```
io.pravega.test.integration.StreamMetricsTest > testStreamsAndScopesBasicMetricsTests FAILED
    java.lang.AssertionError: expected:<1> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.pravega.test.integration.StreamMetricsTest.testStreamsAndScopesBasicMetricsTests(StreamMetricsTest.java:226)
```

**To Reproduce**
Sporadic failure when executing `gradlew build`

**Expected behavior**
Make the test consistently passing.

**Screenshots**
NA

**Additional context**
NA

**Comment by RaulGracia** [comment]
I have done efforts to reproduce this problem locally without luck (after 200 executions in a  row). Still, this is my understanding of what is happenning:
1) The test has 2 parts: the first part tests the Stream metrics using the Controller methods (createStream, deleteStream, etc.). The second part tests the metrics that account for "failed" Controller operations (failure to create a scope, a stream, etc.). As there is no direct way to increment these failed operation counters, the test just directly increments these metrics by executing `StreamMetrics.getInstance().xxxxFailed()`. 
2) In the failures observed, the test consistently fails at the same point `StreamMetricsTest.java:226`. This is the first assertion of the set of metrics tested directly, that is, the metrics for failed operations. This means that the first part of the test works well.
3) At the moment, I only see 2 possible explanations for the test flakiness:  i) Sometimes, perhaps in a very slow environment, the metrics is acknowledged as created (`StreamMetrics.getInstance().xxxxFailed()` finishes its execution) but the global metrics registry has not completely registered it at the moment we execute the assertion. This could explain why the assertion fails as the counter gets a 0 (it does not exist in the global registry) when it expects a 1. ii) Another explanation that I see less plausible is that the metrics cache triggers a time-based cache eviction that removes the metrics from the registry in between they are created and the assertions are executed. However, I would expect the manifestation of this kind of problem to be more random: that is, the test should fail at different points depending on when the cache cleanup is triggered, instead of be consistently failing always at the same point.

Still, there are just hypothesis until we could get the full logs of a reproduction of this problem.
