### ISSUE TITLE
Sporadic failure in test AsyncTableEntryReaderTests.testReadKey

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#5843]
**Describe the bug**
Found test `io.pravega.segmentstore.server.tables.AsyncTableEntryReaderTests.testReadKey` failing sporadically:
```
    java.lang.AssertionError: expected:<30> but was:<10>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.pravega.segmentstore.server.tables.AsyncTableEntryReaderTests.testReadKey(AsyncTableEntryReaderTests.java:68)
 ```

**To Reproduce**
The test fails sometimes when executing `./gradlew build` on Jenkins/Git Actions.

**Expected behavior**
Test should pass consistently.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by RaulGracia** [comment]
Another instance:
```
java.lang.AssertionError: expected:<0> but was:<77>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.pravega.segmentstore.server.tables.AsyncTableEntryReaderTests.testReadEntry(AsyncTableEntryReaderTests.java:141)
```

**Comment by RaulGracia** [comment]
Another occurrence of this error:
```
io.pravega.segmentstore.server.tables.AsyncTableEntryReaderTests > testReadKey FAILED
    java.lang.AssertionError: expected:<101> but was:<59>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.pravega.segmentstore.server.tables.AsyncTableEntryReaderTests.testReadKey(AsyncTableEntryReaderTests.java:74)
        ```

**Comment by shrids** [comment]
Observing this issue again: https://github.com/pravega/pravega/runs/4698479837?check_suite_focus=true
```
2022-01-04T05:22:32.8441306Z io.pravega.segmentstore.server.tables.AsyncTableEntryReaderTests > testReadEntry FAILED
2022-01-04T05:22:32.8442823Z     java.lang.AssertionError: expected:<0> but was:<90>
2022-01-04T05:22:32.8443527Z         at org.junit.Assert.fail(Assert.java:88)
2022-01-04T05:22:32.8444293Z         at org.junit.Assert.failNotEquals(Assert.java:834)
2022-01-04T05:22:32.8445148Z         at org.junit.Assert.assertEquals(Assert.java:645)
2022-01-04T05:22:32.8445978Z         at org.junit.Assert.assertEquals(Assert.java:631)
2022-01-04T05:22:32.8448106Z         at io.pravega.segmentstore.server.tables.AsyncTableEntryReaderTests.testReadEntry(AsyncTableEntryReaderTests.java:151)
```
