### ISSUE TITLE
Sporadic failure in WatermarkingTest.watermarkTest

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#5878]
**Describe the bug**
Found a sporadic failure in test `WatermarkingTest.watermarkTest`: https://github.com/pravega/pravega/runs/2173677972
```
io.pravega.test.integration.WatermarkingTest > watermarkTest FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertNotNull(Assert.java:712)
        at org.junit.Assert.assertNotNull(Assert.java:722)
        at io.pravega.test.integration.WatermarkingTest.watermarkTest(WatermarkingTest.java:189)
```
I don't know if this is related to a recent change to speed up this test: #5836.

**To Reproduce**
The issue occurs sporadically in Git Actions when executing `./gradlew build`

**Expected behavior**
Test should pass consistently.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by RaulGracia** [comment]
Another repro: https://github.com/pravega/pravega/pull/5871/checks?check_run_id=2202864492
```
io.pravega.test.integration.WatermarkingTest > watermarkTest FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertNotNull(Assert.java:712)
        at org.junit.Assert.assertNotNull(Assert.java:722)
        at io.pravega.test.integration.WatermarkingTest.watermarkTest(WatermarkingTest.java:195)
```

**Comment by RaulGracia** [comment]
More occurrences of this failure:
```
io.pravega.test.integration.WatermarkingTest > watermarkTest FAILED
    java.lang.IllegalArgumentException: Segment offset in startStreamCut should be <= segment offset in endStreamCut
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
        at io.pravega.client.stream.ReaderGroupConfig$ReaderGroupConfigBuilder.lambda$verifyStartAndEndStreamCuts$2(ReaderGroupConfig.java:303)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
```
