### ISSUE TITLE
Sporadic failure in test TableBasedMetadataChunkedSegmentStorageTests.testInitialization

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#5879]
**Describe the bug**
Found test `TableBasedMetadataChunkedSegmentStorageTests.testInitialization` sporadically failing with:
```
org.junit.runners.model.TestTimedOutException: test timed out after 30 seconds
	at java.base@11.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1798)
	at java.base@11.0.3/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1868)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at app//io.pravega.common.concurrent.Futures.lambda$await$1(Futures.java:94)
	at app//io.pravega.common.concurrent.Futures$$Lambda$469/0x000000010034bc40.run(Unknown Source)
	at app//io.pravega.common.Exceptions.handleInterrupted(Exceptions.java:115)
	at app//io.pravega.common.concurrent.Futures.await(Futures.java:92)
	at app//io.pravega.common.concurrent.Futures.await(Futures.java:79)
	at app//io.pravega.common.concurrent.AbstractThreadPoolService.close(AbstractThreadPoolService.java:63)
	at app//io.pravega.segmentstore.storage.chunklayer.GarbageCollector.close(GarbageCollector.java:362)
	at app//io.pravega.segmentstore.storage.chunklayer.ChunkedSegmentStorage.close(ChunkedSegmentStorage.java:682)
	at app//io.pravega.segmentstore.storage.chunklayer.ChunkedSegmentStorage.close(ChunkedSegmentStorage.java:672)
	at app//io.pravega.segmentstore.storage.chunklayer.ChunkedSegmentStorageTests.testInitialization(ChunkedSegmentStorageTests.java:170)
	at java.base@11.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.3/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.3/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base@11.0.3/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.3/java.lang.Thread.run(Thread.java:834)
```
Full log available here: 
[TEST-io.pravega.segmentstore.storage.metadata.TableBasedMetadataStoreTests$TableBasedMetadataChunkedSegmentStorageTests.xml.zip](https://github.com/pravega/pravega/files/6188640/TEST-io.pravega.segmentstore.storage.metadata.TableBasedMetadataStoreTests.TableBasedMetadataChunkedSegmentStorageTests.xml.zip)

**To Reproduce**
Sporadic failure on Jenkins when executing `./gradlew build`

**Screenshots**
n/a

**Additional information**
n/a

**Comment by sachin-j-joshi** [comment]
With recent GC redesign I'm not able to repro it. (Looks like we fixed it already)
![image](https://user-images.githubusercontent.com/44757683/130689337-ff8196e8-8d8b-440c-845a-ce4daf63b66b.png)

**Comment by sachin-j-joshi** [comment]
![image](https://user-images.githubusercontent.com/44757683/130690736-9c709285-5580-4d94-b32e-d6c2c0c9223c.png)

**Comment by sachin-j-joshi** [comment]
Closing issue. Not able to repro.
