### ISSUE TITLE
FlakyTest: 

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#5881]
**Describe the bug**
io.pravega.segmentstore.server.host.HDFSIntegrationTest > testDataRecovery FAILED
    java.lang.NullPointerException
        at io.pravega.segmentstore.server.containers.ContainerRecoveryUtils.recoverAllSegments(ContainerRecoveryUtils.java:105)
        at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.testSegmentRestoration(StreamSegmentStoreTestBase.java:236)
        at io.pravega.segmentstore.server.host.HDFSIntegrationTest.testDataRecovery(HDFSIntegrationTest.java:94)

**Additional information**
Part of gradle task :segmentstore:server:host:test

**Comment by tkaitchuck** [comment]
This test also sometime times out. Possibly due to this error:
```
java.lang.RuntimeException: Failed to start SegmentContainerManager
	at io.pravega.segmentstore.server.mocks.LocalSegmentContainerManager.initialize(LocalSegmentContainerManager.java:121)
	at io.pravega.segmentstore.server.store.ServiceBuilder.initialize(ServiceBuilder.java:247)
	at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.createBuilder(StreamSegmentStoreTestBase.java:513)
	at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.testSegmentRestoration(StreamSegmentStoreTestBase.java:198)
	at io.pravega.segmentstore.server.host.HDFSIntegrationTest.testDataRecovery(HDFSIntegrationTest.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at io.pravega.common.concurrent.Futures.lambda$4(Futures.java:207)
	at io.pravega.common.Exceptions.handleInterruptedCall(Exceptions.java:144)
	at io.pravega.common.concurrent.Futures.join(Futures.java:205)
	at io.pravega.segmentstore.server.mocks.LocalSegmentContainerManager.initialize(LocalSegmentContainerManager.java:119)
	... 29 more


```

**Comment by tkaitchuck** [comment]
More up to date stack trace:
```
io.pravega.segmentstore.server.host.HDFSIntegrationTest > testDataRecovery FAILED
    java.lang.NullPointerException
        at io.pravega.segmentstore.server.containers.ContainerRecoveryUtils.recoverAllSegments(ContainerRecoveryUtils.java:112)
        at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.testSegmentRestoration(StreamSegmentStoreTestBase.java:245)
        at io.pravega.segmentstore.server.host.HDFSIntegrationTest.testDataRecovery(HDFSIntegrationTest.java:106)
```

**Comment by kotlasaicharanreddy** [comment]
One more instance of this : https://github.com/pravega/pravega/pull/6114/checks?check_run_id=3238918536#step:5:4225

**Comment by tkaitchuck** [comment]
Another failure:

> java.util.concurrent.CompletionException: io.pravega.common.ObjectClosedException: Object 'StreamSegmentContainer' has been closed and cannot be accessed anymore.
 > 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
 > 	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1113)
 > 	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
 > 	at io.pravega.segmentstore.server.containers.ContainerEventProcessorImpl.lambda$getOrCreateInternalSegment$1(ContainerEventProcessorImpl.java:131)
 > 	at io.pravega.segmentstore.server.containers.ContainerEventProcessorImpl$EventProcessorImpl.refreshSegment(ContainerEventProcessorImpl.java:449)
 > 	at io.pravega.segmentstore.server.containers.ContainerEventProcessorImpl$EventProcessorImpl.processEvents(ContainerEventProcessorImpl.java:419)
 > 	at io.pravega.segmentstore.server.containers.ContainerEventProcessorImpl$EventProcessorImpl.lambda$doRun$4(ContainerEventProcessorImpl.java:386)
 > 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
 > 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
 > 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 > 	at io.pravega.common.concurrent.ThreadPoolScheduledExecutorService$ScheduledRunnable.run(ThreadPoolScheduledExecutorService.java:189)
 > 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 > 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 > 	at java.base/java.lang.Thread.run(Thread.java:829)
 > Caused by: io.pravega.common.ObjectClosedException: Object 'StreamSegmentContainer' has been closed and cannot be accessed anymore.
 > 	at io.pravega.common.Exceptions.checkNotClosed(Exceptions.java:261)
 > 	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.ensureRunning(StreamSegmentContainer.java:938)
 > 	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.forSegment(StreamSegmentContainer.java:664)
 > 	at io.pravega.segmentstore.server.SegmentContainer.forSegment(SegmentContainer.java:85)
 > 	at io.pravega.segmentstore.server.containers.ContainerEventProcessorImpl.lambda$getOrCreateInternalSegment$0(ContainerEventProcessorImpl.java:131)
 > 	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
 > 	... 12 common frames omitted

**Comment by Bhupender-Y** [comment]
One more occurrence of this : https://github.com/pravega/pravega/runs/8182325148?check_suite_focus=true
