### ISSUE TITLE
Sporadic test failure AppendTest.miniBenchmark

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#5893]
**Describe the bug**
Found test `AppendTest.miniBenchmark` failing sporadically on Jenkins:
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at io.pravega.test.integration.AppendTest.miniBenchmark(AppendTest.java:418)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**To Reproduce**
Occurs sporadically when executing `gradlew build` on Jenkins.

**Screenshots**
n/a

**Additional information**
While the test worked well, it looks like is the slowness of the instance the one that caused the assertion error. The test is expecting both sync and async writes to take less than 10 seconds, but in a slow instance they can take more:
```
Max latency: 3039.230622
Blocking took: 10969ms.
Non blocking took: 5426ms.
```
Adding a larger timeout or a larger assertion time would be enough to mitigate this problem.

**Comment by RaulGracia** [comment]
Closed via #7345.
