### ISSUE TITLE
io.pravega.test.system.ReadTxnWriteScaleWithFailoverTest.readTxnWriteScaleWithFailoverTest

### ISSUE THREAD

**Issue by ManishKumarKeshri** [pravega/pravega#5900]
**Describe the bug**
Found that `io.pravega.test.system.ReadTxnWriteScaleWithFailoverTest.readTxnWriteScaleWithFailoverTest` fails sporadically due to:
```
2021-03-18 04:43:12,821 216321 [controllerpool-9] WARN  i.p.c.server.ControllerService - Transaction commit failed
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$UnknownException: get entry: key: 00000001-0000-0000-0000-000000009c6a table: _system/_tables/testReadTxnWriteScaleScope1162564740/testReadTxnWriteScaleStream/transactionsInEpoch-1.#.b83027b8-2a6d-4d76-b5f0-74b797a6634b
        at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$withRetries$58(PravegaTablesStoreHelper.java:604)
        at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
        at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$runAsync$6(Retry.java:246)
        at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.postFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.pravega.controller.store.stream.StoreException$UnknownException: get entry: key: 00000001-0000-0000-0000-000000009c6a table: _system/_tables/testReadTxnWriteScaleScope1162564740/testReadTxnWriteScaleStream/transactionsInEpoch-1.#.b83027b8-2a6d-4d76-b5f0-74b797a6634b
        at io.pravega.controller.store.stream.StoreException.create(StoreException.java:108)
        at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$exceptionalCallback$55(PravegaTablesStoreHelper.java:569)
        ... 12 common frames omitted
Caused by: io.pravega.common.ObjectClosedException: Object 'ConnectionPoolImpl' has been closed and cannot be accessed anymore.
        at io.pravega.common.Exceptions.checkNotClosed(Exceptions.java:255)
        at io.pravega.client.connection.impl.ConnectionPoolImpl.getClientConnection(ConnectionPoolImpl.java:101)
        at io.pravega.client.connection.impl.RawClient.<init>(RawClient.java:101)
        at io.pravega.controller.server.SegmentHelper.readTable(SegmentHelper.java:483)
        at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$getEntry$21(PravegaTablesStoreHelper.java:288)
        at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$exceptionalCallback$54(PravegaTablesStoreHelper.java:527)
        ... 8 common frames omitted
2021-03-18 04:43:12,821 216321 [controllerpool-9] DEBUG i.p.c.s.r.g.v.ControllerServiceImpl - result =  status: FAILURE
{log}
```

**To Reproduce**
Run system tests a few times.

**Screenshots**
n/a

**Additional information**
Here at this [line](https://github.com/pravega/pravega/blob/a5f5d670b7f2340b8388a9a2b216aa7e5b4d7151/controller/src/main/java/io/pravega/controller/server/ControllerService.java#L507), we only retry commit if it fails due to a non `RetryableException` which should have been opposite. 
We should throw non `RetryableException`, and set `TxnStatus.Status.FAILURE` for `RetryableException` for client to retry.

**Comment by ManishKumarKeshri** [comment]
@shiveshr Please have a look. Thanks.
