### ISSUE TITLE
Repeated SegmentTruncatedExceptions when starting my Pravega client application

### ISSUE THREAD

**Issue by kevin-ghd** [pravega/pravega#5932]
**Describe the bug**
I seem to hit thousands of `SegmentTruncatedException` errors (and other exceptions) when starting my Pravega client application after it hasn't run for a few days.  And the app doesn't seem to recover, so it never reads any Pravega events.

I'm used to seeing the `TruncatedDataException` at startup (once) and the app recovers.  This time I'm seeing `SegmentTruncatedExceptions` in the pravega code (not the application code), over and over again, and the app is never able to read any events.

Some example stack traces (~3700 instances over 45 minutes) - scope & stream name has been removed:
```
2021-04-14T09:46:23.69-0400 [APP/PROC/WEB/1] OUT 2021-04-14 13:46:23.698  WARN 16 --- [ocketReaders-19] i.p.c.s.i.AsyncSegmentInputStreamImpl    : Exception while reading from Segment ***scope***/***stream***/1.#epoch.0 at offset 39473934989 :
2021-04-14T09:46:23.69-0400 [APP/PROC/WEB/1] OUT io.pravega.client.segment.impl.SegmentTruncatedException: null
2021-04-14T09:46:23.69-0400 [APP/PROC/WEB/1] OUT 	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.segmentIsTruncated(AsyncSegmentInputStreamImpl.java:100)
2021-04-14T09:46:23.69-0400 [APP/PROC/WEB/1] OUT 	at io.pravega.shared.protocol.netty.WireCommands$SegmentIsTruncated.process(WireCommands.java:207)
2021-04-14T09:46:23.69-0400 [APP/PROC/WEB/1] OUT 	at io.pravega.shared.protocol.netty.ReplyProcessor.process(ReplyProcessor.java:20)
2021-04-14T09:46:23.69-0400 [APP/PROC/WEB/1] OUT 	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.process(AsyncSegmentInputStreamImpl.java:70)
2021-04-14T09:46:23.69-0400 [APP/PROC/WEB/1] OUT 	at io.pravega.client.connection.impl.FlowHandler.process(FlowHandler.java:160)
2021-04-14T09:46:23.69-0400 [APP/PROC/WEB/1] OUT 	at io.pravega.client.connection.impl.TcpClientConnection$ConnectionReader.run(TcpClientConnection.java:119)
2021-04-14T09:46:23.69-0400 [APP/PROC/WEB/1] OUT 	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
1. Source Pravega stream has a retention of 1 day with dynamic scaling (min 3 segments)
2. Pravega reader application works fine in initial tests
3. **Stop the Pravega reader application for a few days**, while source stream is still being written to by a separate application (and being truncated due to 1-day retention)
4. Start the Pravega reader application, and these repeated SegmentTruncatedExceptions are seen.

**Screenshots**
N/A

**Additional information**
I see the same stack trace happen when trying to read from the source Pravega stream and also from the special reader group stream (`_RG...`).  There are other stack traces as well, but this one seems to be the most common.

**Comment by shrids** [comment]
@kevin-ghd I tried simulating this issue with standalone and I am not able to recreate it. Perhaps there is more to the issue.
Is it possible to share the client logs for the reader application?

The logs I would look at are the following :
a.   `log.info("{} encountered truncation for segment {} ", this, segmentId);`  This would indicate the reader observed that the Segment to be read is truncated. (reader log)
b.` log.info("{} encountered end of segment {} ", this, oldSegment.getSegmentId()); `
This would indicate that the segment truncated is at the end of the segment and the successor segment needs to be fetched. (reader log)
c. The controller logs that indicate stream truncated due to the stream retention policy.
 `log.info(requestId, "Truncating stream {}/{} at stream cut: {}", scope, stream, truncationRecord.getStreamCut());`
d. `log.info(request.getRequestId(), "Scale up request received for stream segment {}", qualifiedName);` this controller log that would indicate stream scaling was attempted by the controller.

In the log snip that you have shared the segment number is `1.#epoch.0  offset 39473934989` . This implies that there was no dynamic scaling of the stream here.

**Comment by kevin-ghd** [comment]
Hi @shrids - thanks for the help!  I would have to redact some information before sharing the full logs.  Here's a quick summary of what I see over a 45-minute period:

- 3,716 instances of the `SegmentTruncatedException` exception
- 366 instances of the `encountered truncation for segment` log message
- no instances of the `encountered end of segment` log message
- no instances of the `Truncating stream` log message
- no instances of the `Scale up request received` log message

Here's an example of the `encountered truncation for segment` scenario from the logs:

```
   2021-04-14T09:46:21.17-0400 [APP/PROC/WEB/2] OUT 2021-04-14 13:46:21.176  WARN 20 --- [ocketReaders-17] i.p.c.s.i.AsyncSegmentInputStreamImpl    : Exception while reading from Segment ***scope***/***stream***/2.#epoch.0 at offset 39254614948 :
   2021-04-14T09:46:21.17-0400 [APP/PROC/WEB/2] OUT io.pravega.client.segment.impl.SegmentTruncatedException: null
   2021-04-14T09:46:21.17-0400 [APP/PROC/WEB/2] OUT 	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.segmentIsTruncated(AsyncSegmentInputStreamImpl.java:100)
   2021-04-14T09:46:21.17-0400 [APP/PROC/WEB/2] OUT 	at io.pravega.shared.protocol.netty.WireCommands$SegmentIsTruncated.process(WireCommands.java:207)
   2021-04-14T09:46:21.17-0400 [APP/PROC/WEB/2] OUT 	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.process(AsyncSegmentInputStreamImpl.java:70)
   2021-04-14T09:46:21.17-0400 [APP/PROC/WEB/2] OUT 	at io.pravega.client.connection.impl.FlowHandler.process(FlowHandler.java:160)
   2021-04-14T09:46:21.17-0400 [APP/PROC/WEB/2] OUT 	at io.pravega.client.connection.impl.TcpClientConnection$ConnectionReader.run(TcpClientConnection.java:119)
   2021-04-14T09:46:21.17-0400 [APP/PROC/WEB/2] OUT 2021-04-14 13:46:21.177  INFO 20 --- [ MessageHandler] i.p.c.stream.impl.EventStreamReaderImpl  : EventStreamReaderImpl( id=***app-name***-8c8750a0-b8c5-46d5-b3cd-84a65b5de0ee) encountered truncation for segment ***scope***/***stream***/2.#epoch.0 
```

Regarding the scaling policy...
> This implies that there was no dynamic scaling of the stream here.

The scaling policy was technically `Dynamic` but the stream never scaled beyond its minimum 3 segments:
![image](https://user-images.githubusercontent.com/82527868/115084089-5ae3ca80-9ed6-11eb-94da-1cf6c790e865.png)

**Comment by shrids** [comment]
@kevin-ghd Thanks for providing the logs of slack.
The application closes the reader when truncation is observed and the newer reader will attempt to read from the same truncated position leading to more truncation exceptions. Hence these repeated truncation exceptions were observed in the logs.

**Comment by shrids** [comment]
Closing the issue based on the previous comment. Please feel free to reopen the issue if there is any other issue is observed...

**Comment by kevin-ghd** [comment]
Yes, it was an issue on the application side.  Thanks for the help @shrids!
