### ISSUE TITLE
Sporadic test failure ChunkMetadataStoreTests.testParallelReadsAfterEviction

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#6024]
**Describe the bug**
We found this test sporadically failing:
```
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:878)
	at com.google.common.cache.LocalCache.put(LocalCache.java:4179)
	at com.google.common.cache.LocalCache$LocalManualCache.put(LocalCache.java:4888)
	at io.pravega.segmentstore.storage.metadata.BaseMetadataStore.evictFromBuffer(BaseMetadataStore.java:538)
	at io.pravega.segmentstore.storage.metadata.BaseMetadataStore.evictAllEligibleEntriesFromBuffer(BaseMetadataStore.java:520)
	at io.pravega.segmentstore.storage.metadata.ChunkMetadataStoreTests.evictAll(ChunkMetadataStoreTests.java:1111)
	at io.pravega.segmentstore.storage.metadata.ChunkMetadataStoreTests.testParallelReadsAfterEviction(ChunkMetadataStoreTests.java:1080)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
``` 

**To Reproduce**
Run `gradlew build` and the failure appears sporadically. 

**Screenshots**
n/a

**Additional information**
We need to verify whether this is a real bug or just a flaky test.

**Comment by sachin-j-joshi** [comment]
closed by #6209
