### ISSUE TITLE
Pravega examples doesn't build with openjdk 15.0 / Error execution failed for task ':scenarios/turbine-heat-processor:compileScala'.

### ISSUE THREAD

**Issue by moorthi07** [pravega/pravega#6025]
Tried running the samples on openjdk15 + linux. The scala build fails it is due to a compiler bug https://github.com/scala/bug/issues/11608The the stack trace can be obtained by running ./gradlew clean installDist --stacktrace
Could you please file an issue in the Pravega-samples?
As a workaround for the scala compiler bug please use a lower version of jdk.

// Log snip.
Execution failed for task ':scenarios/turbine-heat-processor:compileScala'.
> java.lang.RuntimeException: /packages cannot be represented as URI
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':scenarios/turbine-heat-processor:compileScala'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
		...//snipped
		Caused by: java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
        at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
        at scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:204)

**Comment by moorthi07** [comment]
These steps from  [works](https://pravega.io/docs/nightly/getting-started/) with openjdk11
Download the Pravega-Samples git repo

$ git clone https://github.com/pravega/pravega-samples
$ cd pravega-samples

Generate the scripts to run the applications

$ ./gradlew installDist
