### ISSUE TITLE
SLTS - Confusing assert in MetadataTransaction.update

### ISSUE THREAD

**Issue by sachin-j-joshi** [pravega/pravega#6047]
**Describe the bug**
The assert in io.pravega.segmentstore.storage.metadata.BaseMetadataStore.update(BaseMetadataStore.java:772)  is confusing and unhelpful and probably wrong. 
This needs to be fixed with proper error message.

**To Reproduce**
This should be possible to create this scenario in unit tests.
**Logs**
```
2021-05-20 15:10:12,031 67561 [storage-io-195] ERROR i.p.s.s.h.h.PravegaRequestProcessor - [requestId=212343183114240] Error (Segment = '_system/_tables/_system/readerGroupsInScope.#.b0b57b3e-4df7-40b7-8808-a8239186104a', Operation = 'readTable')
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:492)
        at io.pravega.segmentstore.storage.metadata.BaseMetadataStore.update(BaseMetadataStore.java:772)
        at io.pravega.segmentstore.storage.metadata.MetadataTransaction.update(MetadataTransaction.java:152)
        at io.pravega.segmentstore.storage.chunklayer.ChunkedSegmentStorage.lambda$claimOwnership$9(ChunkedSegmentStorage.java:325)
```

**Additional information**
None

**Comment by sachin-j-joshi** [comment]
This seems to be outdated task.
Most likely already fixed by #5809
