### ISSUE TITLE
Extra warning log when call getReaderGroup that not yet created

### ISSUE THREAD

**Issue by crazyzhou** [pravega/pravega#6075]
**Describe the bug**
Pravega used to persist the idempotence of the call `createReaderGroup`, so flink connector used to have those part of code like this in the checkpoint hook.
```
readerGroupManager.createReaderGroup(readerGroupName, readerGroupConfig);
readerGroup = readerGroupManager.getReaderGroup(readerGroupName);
```

In a recovery case, the connector would reset the reader group with adding a start streamcut in the config, and when the Flink job recovers, the `createReaderGroup` call would not fail before, but after #5930 fix, it would fail now as the reader group config is not the same as stored.

So in https://github.com/pravega/flink-connectors/pull/516, we changed this into a "get first and then create" way as https://github.com/pravega/flink-connectors/pull/516/files#diff-077ca27a878ae584603740b5a82c4e4d826748be01c56649493eede64e3fb29dR87

When running Flink applications with the new connector, it would always print a warn log like
```
09:38:11,985 WARN  io.pravega.client.control.impl.ControllerImpl                 - gRPC call for getCurrentSegments with trace id 8096979106827907034 and parameters [examples, _RGflinkmbjns4awk3ajmcrvzqeb] failed with server error.
io.pravega.shaded.io.grpc.StatusRuntimeException: NOT_FOUND: get entry: key: _RGflinkmbjns4awk3ajmcrvzqeb table: _system/_tables/examples/streamsInScope.#.5903df2a-4697-432b-a91c-dfa96bbf6623
        at io.pravega.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
        at io.pravega.shaded.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:442)
...
```

This comes from the first `getReaderGroup` call with a non-existing RG. 

Is there a way that we can get rid of such warn logs?

**Additional information**

@shrids has some discussion with me about this problem, and we have some thoughts on this as listed, but still controversial.

1. Add a `boolean checkReaderGroupExists(String rgName)` in the `ReaderGroupManager`
2. Turn down the log level from `log.warn` into `log.debug`
3. Change the GRPC return for this as a normal NOT_FOUND instead of an exception 

We would like to involve more people in the discussion to see how we can solve this.

**Comment by shrids** [comment]
At the moment I do not see a way to selectively disable WARN logs here.
The controller allready returns a grpc status NOT_FOUND in case the RG stream is not found.

**Comment by shrids** [comment]
https://github.com/pravega/pravega/blob/786f25e70eefa50a82321e3376cc30a14bdfbbb8/client/src/main/java/io/pravega/client/control/impl/ControllerImpl.java#L1849

**Comment by hyffrank** [comment]
We also met this warning message in our log when we call getReaderGroup. This behavior was only being noticed recently while previously only a "InvalidStreamException" will be thrown from the client without any warning message.

**Comment by fpj** [comment]
Three things:

1- @crazyzhou it would help if you explained in more detail and focused on the behavior you are trying to implement. My understanding is the following: upon recovery, you want to start an existing reader group with a new stream cut. This is failing with the current behavior of `createReaderGroup`, and to work around it, you are trying to get the reader group, and create upon failure. I don't actually understand why it is correct to get the reader group and proceed if succeeds as I thought that we wanted to resume it from a stream cut, so we need to update the start position. Let's please clarify the behavior we are trying to introduce.
2- It is not necessarily a problem to log that message as a warning. Say that the application really expected the reader group to be there. It is useful to log at warn level to warn the user of a potential issue. Some applications may while some others won't.
3- @shrids It doesn't look great that we have no control over what we are logging out of grpc errors. We might want to differentiate the errors that come through that `onError` call, at least between warn and error.

**Comment by crazyzhou** [comment]
> 1- @crazyzhou it would help if you explained in more detail and focused on the behavior you are trying to implement. My understanding is the following: upon recovery, you want to start an existing reader group with a new stream cut. This is failing with the current behavior of createReaderGroup, and to work around it, you are trying to get the reader group, and create upon failure. I don't actually understand why it is correct to get the reader group and proceed if succeeds as I thought that we wanted to resume it from a stream cut, so we need to update the start position. Let's please clarify the behavior we are trying to introduce.

Yes, your understanding is correct, I will give more details.
First when users start a streaming reader in the Flink application, the connector will help create a `readerGroupConfig` on `FlinkPravegaReader`, this config will include the user specific configurations such as the `maxOutstandingCheckpointRequest`, `groupRefreshTime`, `starting/end streamcut`, etc. This should be static in the application.
When Flink checkpoints start, a `ReaderCheckpointHook` will be instantiated to deal with the Pravega checkpoint initialization or restore. This hook will accept the `readerGroupConfig` from the reader as a parameter, when a recovery is needed, this hook will take the last successful checkpoint, and reset the reader group by only changing the starting streamcut in the passed `readerGroupConfig`. The Flink API does not allow and I also don't think it's appropriate to let the hook to tell the readers and update the user-specified configuration in the readers.

For the implementattion, I checked the detail of `getReaderGroup()` call in `ReaderGroupManagerImpl` with @hyffrank together, and we think this issue should be fixed in this level, not directly in the logging of GRPC.
Now in the `getReaderGroup` call, it will try to instantiate a instance of `ReaderGroupImpl` and this will create a state synchronizer internally. Imagine if some users are just calling this `getReaderGroup`, we will result in multiple orphan state synchronizers left in the system that cannot be deleted.
Then, this state synchonizer will call `controller.getCurrentSegments` which causes the exact warn log here.
I would propose that we change this `getReaderGroup()` call, we can add some additional checks before we create the `ReaderGroupImpl` and ask for segments here. We can ask the controller earlier here and return a `null` or throw the `ReaderGroupNotFoundException` early.

**Comment by fpj** [comment]
@crazyzhou I still don't understand the behavior here:

https://github.com/pravega/flink-connectors/pull/516/files#diff-077ca27a878ae584603740b5a82c4e4d826748be01c56649493eede64e3fb29dR87

With this code, we have:

```
try {
             readerGroup = readerGroupManager.getReaderGroup(readerGroupName);
         } catch (ReaderGroupNotFoundException e) {
             readerGroupManager.createReaderGroup(readerGroupName, readerGroupConfig);
             readerGroup = readerGroupManager.getReaderGroup(readerGroupName);
         }
```

which means that in the case the reader group exists, we are not initializing the reader group to the appropriate checkpoint in `initializeReaderGroup` as the `readerGroupConfig` passed as a parameter and containing the checkpoint is not being used. Isn't `initializeReaderGroup` supposed to be resetting the stream to the checkpoint position?

> we will result in multiple orphan state synchronizers left in the system that cannot be deleted.

Note that this is not creating synchronizer streams (I assume you are talking about the new state synchronizer instance in the constructor of `ReaderGroupImpl`), it is creating only a client instance.

**Comment by shrids** [comment]
@crazyzhou @fpj I have removed the `ConfigMismatchException `from the signature for `createReaderGroup `API.
I think this should simplify the usage pattern on the flink-connector side. ref: https://github.com/pravega/pravega/pull/6136
