### ISSUE TITLE
EventStreamWriter unable to write again to the same Stream if application shut down abruptly

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#6076]
**Describe the bug**
While developing some sample application, we realized that it is easy to get into the problem in which the writer cannot write again to the same Stream if the application is closed abruptly without properly closing the resources (e.g., `Ctrl+C`). Once the application is interrupted, the next execution we get the following exceptions continusouly:
```
io.pravega.common.ObjectClosedException: Object 'EventStreamWriterImpl' has been closed and cannot be accessed anymore.
        at io.pravega.common.Exceptions.checkNotClosed(Exceptions.java:255)
        at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEventInternal(EventStreamWriterImpl.java:119)
        at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEvent(EventStreamWriterImpl.java:108)
        at io.pravega.example.gettingstarted.testdata.lambda$ingestData$0(testdata.java:104)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
The only way to be able to write to the same Stream is to restart the server side (e.g., Pravega standalone in this case, despite the problem also happens in a regular Pravega server deployment). Also, the same application can write to a different Stream without restarting the server.

**To Reproduce**
1. Deploy Pravega Standalone
2. Use a sample application that writes continuously to the server.
3. Press `Ctrl+C` to abort the client application
The behavior is consistent and easy to reproduce.

**Screenshots**
n/a

**Additional information**
n/a

**Comment by RaulGracia** [comment]
Found the problem, and it is related to the application:
1. That application creates a writer and reader and giving it as input to some tasks in an Executor to do IO.
2. All the resources use a `@Cleanup` Lombok annotation (instead of a try-with-resources statement).
3. The name for reader was always the same.
4. With this, the first time the application gets executed it works fine. However, if the application does not complete and it is interrupted, the ReaderGroup is closed but the hardcoded reader is not removed from it.
5. The next time the application gets executed, the attempt to create the reader fails (because there is already a reader with that name in the ReaderGroup) and the main thread terminates, closing all the resources before exiting (due to the `@Cleanup` annotation).
6. However, it looks like the executor was not properly closed in that situation and the writer task was left with a closed `EventStreamWriter`. This was the reason for the continuous `ObjectClosedException`.

All in all, looks like this can be fixed by making doing a better job handling interruptions and closing resources properly in the application side.
