### ISSUE TITLE
Bookkeeper upgrade causes API mismatch from its transitive dependencies in pravega-standalone

### ISSUE THREAD

**Issue by thekingofcity** [pravega/pravega#6129]
**Describe the bug**
After #6079 is fixed, the version of bookeeper is upgraded to 4.14.1. This transitively updates the zookeeper version from the old 3.5 to 3.6.2. Flink connectors is using pravega-standalone dependency to perform the integration tests, but internally pravega uses zk 3.5 api, which would fail with API mismatch.

**`pravega-standalone` should be a *standalone working* package**, which is not true currently since some dependecies' version(like zookeeper 3.5.9 and netty-all 4.1.50.Final) are hardcoded in the pravega and won't be in effect in other scenario(like the Flink connectors).

**Additional information**
Zookeeper 3.6 adds one more parameter for the `configure` method in `org.apache.zookeeper.server.ServerCnxnFactory`. See this [change](https://github.com/apache/zookeeper/commit/8f3fbf25c63af54e00bad927a606f79ef0bf7fbf). It will crash when called by the current `io.pravega.segmentstore.storage.impl.bookkeeper#start` method with fewer parameters.

```
org.apache.zookeeper.server.ServerCnxnFactory.configure(Ljava/net/InetSocketAddress;IZ)V
java.lang.NoSuchMethodError: org.apache.zookeeper.server.ServerCnxnFactory.configure(Ljava/net/InetSocketAddress;IZ)V
	at io.pravega.segmentstore.storage.impl.bookkeeper.ZooKeeperServiceRunner.start(ZooKeeperServiceRunner.java:112)
	at io.pravega.local.InProcPravegaCluster.startLocalZK(InProcPravegaCluster.java:231)
	at io.pravega.local.InProcPravegaCluster.start(InProcPravegaCluster.java:203)
	at io.pravega.connectors.flink.utils.SetupUtils$InProcPravegaGateway.start(SetupUtils.java:348)
	at io.pravega.connectors.flink.utils.SetupUtils.startAllServices(SetupUtils.java:113)
	at io.pravega.connectors.flink.dynamic.table.FlinkPravegaDynamicTableITCase.setupPravega(FlinkPravegaDynamicTableITCase.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Also, the `closeAll` method now need a `DisconnectReason`.

**Comment by medvedevigorek** [comment]
@RaulGracia  any thoughts on this one? Why didn't we see this in our tests?

**Comment by thekingofcity** [comment]
> 
> 
> @RaulGracia any thoughts on this one? Why didn't we see this in our tests?

I updated the description. It is because the pravega's gradle.properties [specified the zookeeper at 3.5.9](https://github.com/pravega/pravega/blob/master/gradle.properties#L25).

In other projects that use pravega-standalone, the zookeeper version is not specified and the default version will be higher than this.

**Comment by eolivelli** [comment]
IMHO The only way is to update ZooKeeper to 3.6.x the full stack.

**Comment by RaulGracia** [comment]
@thekingofcity let me see if I understand the problem:
1. Pravega sets a specific Zookeeper client version here: https://github.com/pravega/pravega/blob/62b60f44c5f3c02a538843e9735112e0e9bee0bf/build.gradle#L112
2. Bookkeeper 4.14.x upgrades internally Zookeeper client to 3.6.x
3. Integration tests in Flink connectors are failing because they are using Zookeeper 3.6.x instead of 3.5.x, right?

If the above is true, this could be solved in at least 2 ways: i) upgrade Pravega to Zookeeper 3.6.x (as posted above), ii) forcing the Zookeeper version to the same as in Pravega. To me, the fact that Pravega sets a explicit Zookeeper version seems reasonable, as otherwise that dependency can be transitively changed.

Please, let me know if my understanding is right or not before attemting to fix the problem.

**Comment by RaulGracia** [comment]
@thekingofcity @medvedevigorek I will work on the upgrade of Zookeeper, which also will need to upgrade Curator as well. But in the above PR it may require to adapt several files to the new changes in APIs, so I would defer that to 0.11 rather than changing that in the tail end of the release.

**Comment by thekingofcity** [comment]
I tested with the PR branch and see no failings without a specific zookeeper version, nice work😀

PS: The problem here is not whether `pravega` specifies some versions but `pravega-standalone`. So when some projects like `flink-connectors` use `pravega-standalone`, because of no zookeeper version specifies in `pravega-standalone`, gradle will pull the latest zookeeper where `pravega` is not ready for. For this particular error, zk 3.6 is pulled due some requirements inside `pravega-standalone`, however the `pravega` is only for 3.5.
