### ISSUE TITLE
CommitRequestHandler may get stuck throwing NPE

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#6340]
**Describe the bug**
Some debug on one of the failed system tests we had recently:

- The Controller starts working on `testReadTxnWriteAutoScaleStream` and few seconds later starts trying to commit transactions:
```
2021-09-22 10:33:51,710 142230 [eventprocessor-49] DEBUG i.p.c.s.e.r.CommitRequestHandler - [requestId=-4778385706480942802] Attempting to commit available transactions on stream testReadTxnWriteAutoScaleScope2024571197/testReadTxnWriteAutoScaleStream
```
- As part of that process, there are some table reads that need to be issued to resume committing transactions for this new controller:
```
2021-09-22 10:33:51,719 142239 [ClientSocketReaders-8] DEBUG i.p.controller.server.SegmentHelper - [requestId=-4778385706480942802] ReadTable _system/_tables/testReadTxnWriteAutoScaleScope2024571197/testReadTxnWriteAutoScaleStream/metadata.#.eefe0628-bdc8-427d-9aa6-9719279e95c2 TableRead 1116691496960.
2021-09-22 10:33:51,722 142242 [controllerpool-19] DEBUG i.p.c.store.host.ZKHostStore - Found owning host: 172.26.48.21:12345: for containerId: 0
...
2021-09-22 10:33:51,732 142252 [ClientSocketReaders-1] DEBUG i.p.controller.server.SegmentHelper - [requestId=-4778385706480942802] ReadTable _system/_tables/testReadTxnWriteAutoScaleScope2024571197/testReadTxnWriteAutoScaleStream/transactionsInEpoch-1.#.eefe0628-bdc8-427d-9aa6-9719279e95c2 TableRead 1125281431552.
```

- Reads seem to have completed correctly. However, the Controller has some problem when processing the data read from that table (`transactionsInEpoch`), as it seems to be either incomplete or directly null:
```
2021-09-22 10:33:51,732 142252 [ClientSocketReaders-1] DEBUG i.p.controller.server.SegmentHelper - [requestId=-4778385706480942802] ReadTable _system/_tables/testReadTxnWriteAutoScaleScope2024571197/testReadTxnWriteAutoScaleStream/transactionsInEpoch-1.#.eefe0628-bdc8-427d-9aa6-9719279e95c2 TableRead 1125281431552.
2021-09-22 10:33:51,735 142255 [eventprocessor-41] WARN  i.p.c.s.e.r.CommitRequestHandler - [requestId=-4778385706480942802] Exception while attempting to commit transaction on stream testReadTxnWriteAutoScaleScope2024571197/testReadTxnWriteAutoScaleStream
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$getEntries$45(PravegaTablesStoreHelper.java:557)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at io.pravega.common.concurrent.ThreadPoolScheduledExecutorService$ScheduledRunnable.run(ThreadPoolScheduledExecutorService.java:186)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
	at io.pravega.controller.store.stream.records.ActiveTxnRecord.getCommitOrder(ActiveTxnRecord.java:93)
	at io.pravega.controller.store.stream.PravegaTablesStream.lambda$getVersionedTransactionRecords$86(PravegaTablesStream.java:912)
	... 12 common frames omitted
```
- In method `PravegaTablesStream:getVersionedTransactionRecords` (which has been recently added as part of PR #6283) there is no logic to expect a null active transaction record, so the problem is persistently there. Now, the question is: why the data stored in transactionsInEpoch is null or incomplete? If this cannot be accepted, maybe we need how this data has been written and if it is a valid case, we may need to do a better handling.

**To Reproduce**
Appears sporadically on system tests.

**Screenshots**
n/a

**Additional information**
n/a

**Comment by pbelgundi** [comment]
This exception is seen not because ActiveTxnRecord is null but because its data member commitOffsets is null in an ActiveTxnRecord.EMPTY record. Will send out PR to fix this shortly.

**Comment by pbelgundi** [comment]
> In method PravegaTablesStream:getVersionedTransactionRecords (which has been recently added as part of PR Issue 6061,6109: Transaction performance improvements #6283) there is no logic to expect a null active transaction record, so the problem is persistently there. 

@RaulGracia  This issue was not created because of changes in Txn perf improvements PR, but was a pre-existing issue that surfaced because of changes made here. Also it is a super corner case, where this failure would be seen only when metadata for a txn is not found in segment store.
