### ISSUE TITLE
ZKCounterTest fails intermittently

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#6411]
**Describe the bug**
ZKCounter test fails intermittently

**To Reproduce**
Not known

**Additional information**
Stacktrace:
```
io.pravega.controller.store.stream.ZKCounterTest > testCounter FAILED
    java.util.concurrent.CompletionException: java.lang.StackOverflowError
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1113)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
        at io.pravega.controller.store.stream.ZkInt96Counter.getNextCounter(ZkInt96Counter.java:75)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630.getNextCounter$accessor$qi9kN80G(Unknown Source)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630$auxiliary$SlJ9UO7t.call(Unknown Source)
        at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
        at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
        at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:152)
        at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:44)
        at org.mockito.Answers.answer(Answers.java:100)
        at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
        at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
        at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:33)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:61)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:108)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630.getNextCounter(Unknown Source)
        at io.pravega.controller.store.stream.ZkInt96Counter.lambda$getNextCounter$0(ZkInt96Counter.java:75)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
        at io.pravega.controller.store.stream.ZkInt96Counter.getNextCounter(ZkInt96Counter.java:75)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630.getNextCounter$accessor$qi9kN80G(Unknown Source)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630$auxiliary$SlJ9UO7t.call(Unknown Source)
        at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
        at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
        at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:152)
        at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:44)
        at org.mockito.Answers.answer(Answers.java:100)
        at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
        at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
        at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:33)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:61)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:108)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630.getNextCounter(Unknown Source)
        at io.pravega.controller.store.stream.ZkInt96Counter.lambda$getNextCounter$0(ZkInt96Counter.java:75)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
        at io.pravega.controller.store.stream.ZkInt96Counter.getNextCounter(ZkInt96Counter.java:75)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630.getNextCounter$accessor$qi9kN80G(Unknown Source)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630$auxiliary$SlJ9UO7t.call(Unknown Source)
        at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
        at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
        at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:152)
        at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:44)
        at org.mockito.Answers.answer(Answers.java:100)
        at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
        at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
        at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:33)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:61)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:108)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630.getNextCounter(Unknown Source)
        at io.pravega.controller.store.stream.ZkInt96Counter.lambda$getNextCounter$0(ZkInt96Counter.java:75)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
        at io.pravega.controller.store.stream.ZkInt96Counter.getNextCounter(ZkInt96Counter.java:75)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630.getNextCounter$accessor$qi9kN80G(Unknown Source)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630$auxiliary$SlJ9UO7t.call(Unknown Source)
        at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
        at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
        at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:152)
        at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:44)
        at org.mockito.Answers.answer(Answers.java:100)
        at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
        at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
        at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:33)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:61)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:108)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630.getNextCounter(Unknown Source)
        at io.pravega.controller.store.stream.ZkInt96Counter.lambda$getNextCounter$0(ZkInt96Counter.java:75)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
        at io.pravega.controller.store.stream.ZkInt96Counter.getNextCounter(ZkInt96Counter.java:75)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630.getNextCounter$accessor$qi9kN80G(Unknown Source)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630$auxiliary$SlJ9UO7t.call(Unknown Source)
        at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
        at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
        at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:152)
        at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:44)
        at org.mockito.Answers.answer(Answers.java:100)
        at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
        at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
        at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:33)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:61)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:108)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630.getNextCounter(Unknown Source)
        at io.pravega.controller.store.stream.ZkInt96Counter.lambda$getNextCounter$0(ZkInt96Counter.java:75)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
        at io.pravega.controller.store.stream.ZkInt96Counter.getNextCounter(ZkInt96Counter.java:75)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630.getNextCounter$accessor$qi9kN80G(Unknown Source)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630$auxiliary$SlJ9UO7t.call(Unknown Source)
        at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
        at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
        at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:152)
        at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:44)
        at org.mockito.Answers.answer(Answers.java:100)
        at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
        at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
        at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:33)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:61)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:108)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630.getNextCounter(Unknown Source)
        at io.pravega.controller.store.stream.ZkInt96Counter.lambda$getNextCounter$0(ZkInt96Counter.java:75)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
        at io.pravega.controller.store.stream.ZkInt96Counter.getNextCounter(ZkInt96Counter.java:75)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630.getNextCounter$accessor$qi9kN80G(Unknown Source)
        at io.pravega.controller.store.stream.ZkInt96Counter$MockitoMock$1063454630$auxiliary$SlJ9UO7t.call(Unknown Source)
        at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
        at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
        at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:152)
        at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:44)
        at org.mockito.Answe...

```

**Comment by RaulGracia** [comment]
Another repro:
```
io.pravega.controller.store.stream.ZKCounterTest > testCounter FAILED
    java.util.concurrent.CompletionException: java.lang.StackOverflowError
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1113)
        ```

**Comment by ShwethaSNayak** [comment]
Another reproduction of this issue :
```
 io.pravega.controller.store.stream.ZKCounterTest > testCounter FAILED
    java.util.concurrent.CompletionException: java.lang.StackOverflowError
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1113)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
        at io.pravega.controller.store.stream.ZkInt96Counter.getNextCounter(ZkInt96Counter.java:75)
```
