### ISSUE TITLE
Duplicate DataFrames detected upon ledger rollover

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#6444]
**Describe the bug**
In one of our test cluster, we observed the following some time back:
- This is a partial DU issue. All the user and system data are still present in the system after the fix.
- Segment Container 12 was stuck in an unrecoverable state permanently.
- The reason for Segment Container 12 to be unrecoverable was the duplication of 2 entries (Data Frames) in the associated Durable Log + the need to recover the container while the data duplication was in place.
- The fact that the duplicate entries are the 2 last ones of one ledger and the 2 first ones of the next ledger suggest that the problem could have happened during ledger rollover.
- Network glitches could be also a contributing factor for this issue; i.e., it is also possible that the root cause is associated with Segment Store's Bookkeeper client retrying writes during network glitches/partitions.

We have modified the code of the CLI to recover all entries, irrespective of whether they have the right sequence ids or not (i.e., we skip the actual recovery, we just want to see the DataFrames output). With this, we have been able to locate the problem: there are exactly 2 DataFrames repeated (374119, 374120) in consecutive ledgers 1020740 and 1068746: 

```
Begin DataFrame: Sequence = 17179884211, LedgerId = 1020740, EntryId = 15027.
 @[11,191]: UpdateAttributesOperation: SequenceNumber = 374118, SegmentId = 12, Attributes = 5.
End DataFrame: Length=191/202.
Begin DataFrame: Sequence = 17179884212, LedgerId = 1020740, EntryId = 15028.
 @[11,92]: UpdateAttributesOperation: SequenceNumber = 374119, SegmentId = 12, Attributes = 2.
End DataFrame: Length=92/103.
Begin DataFrame: Sequence = 17179884213, LedgerId = 1020740, EntryId = 15029.
 @[11,190]: StreamSegmentAppendOperation: SequenceNumber = 374120, SegmentId = 12, Offset = 30393482, Length = 154, Attributes = 0.
End DataFrame: Length=190/201.
Begin DataFrame: Sequence = 21474836480, LedgerId = 1068746, EntryId = 0.
 @[11,92]: UpdateAttributesOperation: SequenceNumber = 374119, SegmentId = 12, Attributes = 2.
End DataFrame: Length=92/103.
Begin DataFrame: Sequence = 21474836481, LedgerId = 1068746, EntryId = 1.
 @[11,190]: StreamSegmentAppendOperation: SequenceNumber = 374120, SegmentId = 12, Offset = 30393482, Length = 154, Attributes = 0.
End DataFrame: Length=190/201.
Begin DataFrame: Sequence = 21474836482, LedgerId = 1068746, EntryId = 2.
 @[11,111]: StreamSegmentAppendOperation: SequenceNumber = 374121, SegmentId = 12, Offset = 30393636, Length = 76, Attributes = 0.
End DataFrame: Length=111/122.
```

[container-recover-all-entries.log](https://github.com/pravega/pravega/files/7588719/container-recover-all-entries.log)

The rest of entries seem ok. This problem seems related to handling outstanding writes while rolling over ledgers (perhaps while Bookkeeper connectivity failures happen).

**To Reproduce**
Hard to do, only observed once. We have build this tool to detect this kind of issues proactively: https://github.com/pravega/pravega/pull/6427

**Screenshots**
n/a

**Additional information**
n/a

**Comment by RaulGracia** [comment]
@andreipaduroiu @abhinb tried to reproduce this problem locally with the following test (setting `BK_LEDGER_MAX_SIZE` to 100 to force frequent rollovers), but couldn't see the issue after +1hour of execution:
```
@Test
    public void testBookkeeperRollover() throws DurableDataLogException {
        val log = (BookKeeperLog) createDurableDataLog();
        log.initialize(TIMEOUT);
        AtomicBoolean duplicateFound = new AtomicBoolean(false);
        AtomicLong sequence = new AtomicLong(0);
        AtomicLong readSequence = new AtomicLong(0);

        // Start a process just writing data.
        CompletableFuture<Void> writer = CompletableFuture.runAsync(() -> {
            while (!duplicateFound.get()) {
                for (int i = 0; i < 100; i++) {
                    ByteBuffer buffer = ByteBuffer.allocate(Long.BYTES);
                    buffer.putLong(sequence.getAndIncrement());
                    log.append(new CompositeByteArraySegment(buffer.array()), TIMEOUT).join();
                }
                System.err.println("WRITING " + sequence.get());
                LogAddress toTruncate = null;
                try {
                    DebugDurableDataLogWrapper wrapper = this.factory.get().createDebugLogWrapper(CONTAINER_ID);
                    @Cleanup
                    val iterator = wrapper.asReadOnly().getReader();
                    DurableDataLog.ReadItem item = iterator.getNext();
                    while (item != null) {
                        //System.err.println("READING " + item);
                        ByteBuffer buffer = ByteBuffer.allocate(Long.BYTES);
                        byte[] payload = item.getPayload().readAllBytes();
                        buffer.put(payload);
                        buffer.flip();
                        long result = buffer.getLong();
                        if (readSequence.getAndIncrement() != result) {
                            System.err.println("FOUND DUPLICATE ELEMENT IN LOG!!! " + (readSequence.get() - 1));
                            duplicateFound.set(true);
                            Assert.fail();
                        }
                        toTruncate = item.getAddress();
                        item = iterator.getNext();
                    }
                    System.err.println("READING " + (readSequence.get() + 1));
                    if (toTruncate != null) {
                        log.truncate(toTruncate, TIMEOUT);
                    }
                } catch (DurableDataLogException | IOException e) {
                    e.printStackTrace();
                }
            }
        });
        writer.join();
    }
```
Since the same operations are written to 2 different ledgers of the same log, my suspicion is that the problem might be related to how  `setWriteLedger(currentLedger)` is executed on the writes of the queue upon `handleClosedLedgers()` is executed. Hoped to find the same situation locally with the above code, but I have not been lucky yet.

**Comment by RaulGracia** [comment]
Good news, I think I have been able to reproduce the problem locally. With the same test above, just adding some sporadic ZK session expiration before the `log.append()`:
```
if (random.nextInt(100) == 50) {
    try {
        System.err.println("INJECTING SESSION EXPIRATION");
        log.getZkClient().getZookeeperClient().getZooKeeper().getTestable().injectSessionExpiration();
    } catch (Exception e) {
        System.err.println("Problem restarting Bookkeeper");
    }
}
```
The issue reproduces between 30 seconds and 2-3 minutes:
```
WRITING 15400
FOUND DUPLICATE ELEMENT IN LOG!!! 15299
```
The fact that the entry that is repeated coincides with the last entry of the ledger points exactly to the problem we ar elooking for.

**Comment by RaulGracia** [comment]
We have been able to reproduce the issue during some testing and get debug-level logs for it at the moment the duplication of entries happened: [2-pravega-segmentstore-39761bc0-2022-05-12T08-25-43Z.log](https://github.com/pravega/pravega/files/8688506/2-pravega-segmentstore-39761bc0-2022-05-12T08-25-43Z.log)

In the attached file, we have 2 instances of the same problem:
- _Container 19_: During the rollover of ledger `4461` and `5124`, the last entry (`1862`) of `4461` is duplicated as entry `0` in `5124`.
- _Container 20_: During the rollover of ledger `4993` and `5116`, the two last entries of `4993` (entries `119` and `120`) are duplicated in entries `0` and `1` of ledger `5116`.

The pattern is similar in both cases. Let's pick Container 19:
- The previous entry to the problematic one has been written correctly:
```
2022-05-12 08:23:21,558 1500443 [BookKeeperClientWorker-OrderedExecutor-1-0] DEBUG o.a.b.proto.PerChannelBookieClient - Got Add response from bookie:bookkeeper-bookie-2-16357 rc:EOK, ledger:4461:entry:1861
2022-05-12 08:23:21,558 1500443 [BookKeeperClientWorker-OrderedExecutor-1-0] DEBUG o.a.b.proto.PerChannelBookieClient - Got Add response from bookie:bookkeeper-bookie-3-2585 rc:EOK, ledger:4461:entry:1861
2022-05-12 08:23:21,559 1500444 [BookKeeperClientWorker-OrderedExecutor-1-0] DEBUG o.a.b.proto.PerChannelBookieClient - Got Add response from bookie:bookkeeper-bookie-0-17273 rc:EOK, ledger:4461:entry:1861
2022-05-12 08:23:21,559 1500444 [BookKeeperClientWorker-OrderedExecutor-1-0] DEBUG o.a.bookkeeper.client.PendingAddOp - Submit callback (lid:4461, eid: 1861). rc:0
2022-05-12 08:23:21,559 1500444 [core-24] DEBUG i.p.s.s.logs.OperationProcessor - OperationProcessor[19]: CommitSuccess (TxnId = 1861, LastFullySerializedSN = 3320, LastStartedSN = 3320, Address = Sequence = 17179871045, LedgerId = 4461, EntryId = 1861, Length = 109)
```
- Then, for entry `1862` we get response from Bookie `bookkeeper-bookie-0-17273`:
```
2022-05-12 08:23:49,576 1528461 [BookKeeperClientWorker-OrderedExecutor-1-0] DEBUG o.a.b.proto.PerChannelBookieClient - Got Add response from bookie:bookkeeper-bookie-0-17273 rc:EOK, ledger:4461:entry:1862
```
- But for the other 2 Bookies, we get timeouts when doing the append:
```
2022-05-12 08:24:50,338 1589223 [BookKeeperClientWorker-OrderedExecutor-1-0] DEBUG o.a.b.proto.PerChannelBookieClient - Could not write Add request to bookie bookkeeper-bookie-3.bookkeeper-bookie-headless.default.svc.cluster.local/172.28.39.24:3181 for ledger 4461, entry 1862
2022-05-12 08:24:50,338 1589223 [BookKeeperClientScheduler-OrderedScheduler-0-0] INFO  o.a.b.proto.PerChannelBookieClient - Timed-out 2 operations to channel [id: 0x84676dee, L:/172.28.39.28:33582 - R:bookkeeper-bookie-3.bookkeeper-bookie-headless.default.svc.cluster.local/172.28.39.24:3181] for bookkeeper-bookie-3-2585
2022-05-12 08:24:50,338 1589223 [BookKeeperClientWorker-OrderedExecutor-1-0] WARN  o.a.bookkeeper.client.PendingAddOp - Failed to write entry (4461, 1862): Bookie operation timeout
2022-05-12 08:24:50,338 1589223 [BookKeeperClientScheduler-OrderedScheduler-0-0] INFO  o.a.b.proto.PerChannelBookieClient - Timed-out 2 operations to channel [id: 0x9613f3e1, L:/172.28.39.28:44254 - R:bookkeeper-bookie-2.bookkeeper-bookie-headless.default.svc.cluster.local/172.28.39.21:3181] for bookkeeper-bookie-2-16357
2022-05-12 08:24:50,338 1589223 [BookKeeperClientWorker-OrderedExecutor-1-0] DEBUG o.a.bookkeeper.client.LedgerHandle - [EnsembleChange(ledger:4461, change-id:0000000002)] Replacing {0=bookkeeper-bookie-3-2585} in [bookkeeper-bookie-3-2585, bookkeeper-bookie-2-16357, bookkeeper-bookie-0-17273]
2022-05-12 08:24:50,338 1589223 [BookKeeperClientWorker-OrderedExecutor-1-0] DEBUG o.a.b.client.MetadataUpdateLoop - UpdateLoop(ledgerId=4461,loopId=2f9d1da9) starting write loop iteration, attempt 1
2022-05-12 08:24:50,338 1589223 [BookKeeperClientWorker-OrderedExecutor-1-0] DEBUG o.a.bookkeeper.client.EnsembleUtils - [EnsembleChange(ledger:4461, change-id:0000000002)] replacing bookie: bookkeeper-bookie-3-2585 index: 0
2022-05-12 08:24:50,338 1589223 [BookKeeperClientWorker-OrderedExecutor-1-0] DEBUG o.a.bookkeeper.client.LedgerHandle - [EnsembleChange(ledger:4461, change-id:0000000002)][attempt:1] changing ensemble from: [bookkeeper-bookie-3-2585, bookkeeper-bookie-2-16357, bookkeeper-bookie-0-17273] to: [bookkeeper-bookie-1-2554, bookkeeper-bookie-2-16357, bookkeeper-bookie-0-17273] starting at entry: 1862
2022-05-12 08:24:50,339 1589224 [BookKeeperClientWorker-OrderedExecutor-1-0] DEBUG o.a.b.meta.LedgerMetadataSerDe - Serialized with format 3: Qm9va2llTWV0YWRhdGFGb3JtYXRWZXJzaW9uCTMKxwIIAxADGAAg////////////ASgBMlIKGGJvb2trZWVwZXItYm9va2llLTEtMjU1NAoZYm9va2tlZXBlci1ib29raWUtMi0xNjM1NwoZYm9va2tlZXBlci1ib29raWUtMC0xNzI3MxAAMlIKGGJvb2trZWVwZXItYm9va2llLTMtMjU4NQoZYm9va2tlZXBlci1ib29raWUtMi0xNjM1NwoZYm9va2tlZXBlci1ib29raWUtMC0xNzI3MxBhMlMKGGJvb2trZWVwZXItYm9va2llLTEtMjU1NAoZYm9va2tlZXBlci1ib29raWUtMi0xNjM1NwoZYm9va2tlZXBlci1ib29raWUtMC0xNzI3MxDGDjgDQgBIA1oWCgthcHBsaWNhdGlvbhIHUHJhdmVnYVoVCg9Cb29rS2VlcGVyTG9nSWQSAjE5YAA=
2022-05-12 08:24:50,339 1589224 [BookKeeperClientWorker-OrderedExecutor-1-0] DEBUG o.a.b.proto.PerChannelBookieClient - Could not write Add request to bookie bookkeeper-bookie-2.bookkeeper-bookie-headless.default.svc.cluster.local/172.28.39.21:3181 for ledger 4461, entry 1862
2022-05-12 08:24:50,339 1589224 [BookKeeperClientWorker-OrderedExecutor-1-0] WARN  o.a.bookkeeper.client.PendingAddOp - Failed to write entry (4461, 1862): Bookie operation timeout
```
- At this point, we get a `BKMetadataVersionException` while trying to close the ledger:
```
2022-05-12 08:24:50,341 1589226 [main-SendThread(zookeeper-client:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply session id: 0x201fbeaaa9705c9, packet:: clientPath:/pravega/pravega/bookkeeper/ledgers/00/0000/L4461 serverPath:/pravega/pravega/bookkeeper/ledgers/00/0000/L4461 finished:false header:: 290,5  replyHeader:: 290,4295015160,-103  request:: '/pravega/pravega/bookkeeper/ledgers/00/0000/L4461,#426f6f6b69654d65746164617461466f726d617456657273696f6e933affffffc728310318020ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff12813252a18626f6f6b6b65657065722d626f6f6b69652d312d32353534a19626f6f6b6b65657065722d626f6f6b69652d322d3136333537a19626f6f6b6b65657065722d626f6f6b69652d302d31373237331003252a18626f6f6b6b65657065722d626f6f6b69652d332d32353835a19626f6f6b6b65657065722d626f6f6b69652d322d3136333537a19626f6f6b6b65657065722d626f6f6b69652d302d313732373310613253a18626f6f6b6b65657065722d626f6f6b69652d312d32353534a19626f6f6b6b65657065722d626f6f6b69652d322d3136333537a19626f6f6b6b65657065722d626f6f6b69652d302d313732373310ffffffc6e3834204835a16ab6170706c69636174696f6e127507261766567615a15af426f6f6b4b65657065724c6f6749641223139600,1  response::
2022-05-12 08:24:50,341 1589226 [main-EventThread] INFO  o.a.b.client.MetadataUpdateLoop - UpdateLoop(ledgerId=4461,loopId=2f9d1da9) conflict writing metadata to store, update local value and try again
2022-05-12 08:24:50,342 1589227 [main-SendThread(zookeeper-client:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply session id: 0x201fbeaaa9705c9, packet:: clientPath:/pravega/pravega/bookkeeper/ledgers/00/0000/L4461 serverPath:/pravega/pravega/bookkeeper/ledgers/00/0000/L4461 finished:false header:: 291,4  replyHeader:: 291,4295015160,0  request:: '/pravega/pravega/bookkeeper/ledgers/00/0000/L4461,F  response:: #426f6f6b69654d65746164617461466f726d617456657273696f6e933affffffc128310318ffffff95ffffff851b20ffffffc6e2833252a18626f6f6b6b65657065722d626f6f6b69652d312d32353534a19626f6f6b6b65657065722d626f6f6b69652d322d3136333537a19626f6f6b6b65657065722d626f6f6b69652d302d31373237331003252a18626f6f6b6b65657065722d626f6f6b69652d332d32353835a19626f6f6b6b65657065722d626f6f6b69652d322d3136333537a19626f6f6b6b65657065722d626f6f6b69652d302d313732373310613253a18626f6f6b6b65657065722d626f6f6b69652d312d32353534a19626f6f6b6b65657065722d626f6f6b69652d322d3136333537a19626f6f6b6b65657065722d626f6f6b69652d302d313732373310ffffffc6e3834204835a16ab6170706c69636174696f6e127507261766567615a15af426f6f6b4b65657065724c6f6749641223139600,s{4295005893,4295014889,1652342315748,1652343857385,3,0,0,0,353,0,4295005893}
2022-05-12 08:24:50,342 1589227 [main-EventThread] DEBUG o.a.b.meta.LedgerMetadataSerDe - Deserializing Qm9va2llTWV0YWRhdGFGb3JtYXRWZXJzaW9uCTMKwQIIAxADGJWFGyDGDigDMlIKGGJvb2trZWVwZXItYm9va2llLTEtMjU1NAoZYm9va2tlZXBlci1ib29raWUtMi0xNjM1NwoZYm9va2tlZXBlci1ib29raWUtMC0xNzI3MxAAMlIKGGJvb2trZWVwZXItYm9va2llLTMtMjU4NQoZYm9va2tlZXBlci1ib29raWUtMi0xNjM1NwoZYm9va2tlZXBlci1ib29raWUtMC0xNzI3MxBhMlMKGGJvb2trZWVwZXItYm9va2llLTEtMjU1NAoZYm9va2tlZXBlci1ib29raWUtMi0xNjM1NwoZYm9va2tlZXBlci1ib29raWUtMC0xNzI3MxDGDjgDQgBIA1oWCgthcHBsaWNhdGlvbhIHUHJhdmVnYVoVCg9Cb29rS2VlcGVyTG9nSWQSAjE5YAA=
2022-05-12 08:24:50,342 1589227 [main-EventThread] DEBUG o.a.b.meta.LedgerMetadataSerDe - Format version 3 detected
2022-05-12 08:24:50,342 1589227 [main-EventThread] DEBUG o.a.b.client.MetadataUpdateLoop - UpdateLoop(ledgerId=4461,loopId=2f9d1da9) starting write loop iteration, attempt 2
2022-05-12 08:24:50,342 1589227 [main-EventThread] DEBUG o.a.b.client.MetadataUpdateLoop - UpdateLoop(ledgerId=4461,loopId=2f9d1da9) Update not needed, completing
2022-05-12 08:24:50,342 1589227 [BookKeeperClientWorker-OrderedExecutor-1-0] DEBUG o.a.bookkeeper.client.LedgerHandle - [EnsembleChange(ledger:4461, change-id:0000000002)][attempt:1] Metadata closed during attempt to replace bookie. Another client must have recovered the ledger.
2022-05-12 08:24:50,343 1589228 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR o.a.bookkeeper.client.LedgerHandle - Closing ledger 4461 due to LedgerClosedException: Attempt to write to a closed ledger
2022-05-12 08:24:50,343 1589228 [BookKeeperClientWorker-OrderedExecutor-1-0] DEBUG o.a.bookkeeper.client.PendingAddOp - Submit callback (lid:4461, eid: 1862). rc:-11
2022-05-12 08:24:50,343 1589228 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR o.a.bookkeeper.client.PendingAddOp - Write of ledger entry to quorum failed: L4461 E1862
2022-05-12 08:24:50,343 1589228 [BookKeeperClientWorker-OrderedExecutor-1-0] DEBUG o.a.bookkeeper.client.LedgerHandle - Closing ledger: 4461 at entryId 1862 with 441940 bytes
2022-05-12 08:24:50,343 1589228 [BookKeeperClientWorker-OrderedExecutor-1-0] DEBUG o.a.b.client.MetadataUpdateLoop - UpdateLoop(ledgerId=4461,loopId=2249bbab) starting write loop iteration, attempt 1
2022-05-12 08:24:50,343 1589228 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR o.a.bookkeeper.client.LedgerHandle - Metadata conflict when closing ledger 4461. Another client may have recovered the ledger while there were writes outstanding. (local lastEntry:1862 length:441940)  (metadata lastEntry:1862 length:443029)
2022-05-12 08:24:50,343 1589228 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR o.a.b.client.MetadataUpdateLoop - UpdateLoop(ledgerId=4461,loopId=2249bbab) Exception updating
org.apache.bookkeeper.client.BKException$BKMetadataVersionException: Bad ledger metadata version
	at org.apache.bookkeeper.client.LedgerHandle$5.lambda$safeRun$1(LedgerHandle.java:600)
	at org.apache.bookkeeper.client.MetadataUpdateLoop.writeLoop(MetadataUpdateLoop.java:133)
	at org.apache.bookkeeper.client.MetadataUpdateLoop.run(MetadataUpdateLoop.java:123)
	at org.apache.bookkeeper.client.LedgerHandle$5.safeRun(LedgerHandle.java:612)
	at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-05-12 08:24:50,343 1589228 [BookKeeperClientWorker-OrderedExecutor-1-0] WARN  o.a.bookkeeper.client.LedgerHandle - Close failed: MetadataVersionException: Bad ledger metadata version
```
- A rollover is triggered, so the new ledger `5124` is created:
```
2022-05-12 08:24:50,345 1589230 [main-SendThread(zookeeper-client:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply session id: 0x201fbeaaa9705c9, packet:: clientPath:/pravega/pravega/bookkeeper/ledgers/idgen/ID- serverPath:/pravega/pravega/bookkeeper/ledgers/idgen/ID- finished:false header:: 292,1  replyHeader:: 292,4295015161,0  request:: '/pravega/pravega/bookkeeper/ledgers/idgen/ID-,,v{s{31,s{'world,'anyone}}},3  response:: '/pravega/pravega/bookkeeper/ledgers/idgen/ID-0000005124
2022-05-12 08:24:50,345 1589230 [main-EventThread] DEBUG o.a.b.meta.LedgerMetadataSerDe - Serialized with format 3: Qm9va2llTWV0YWRhdGFGb3JtYXRWZXJzaW9uCTMKpgEIAxADGAAg////////////ASgBMlIKGGJvb2trZWVwZXItYm9va2llLTEtMjU1NAoZYm9va2tlZXBlci1ib29raWUtMi0xNjM1NwoZYm9va2tlZXBlci1ib29raWUtMC0xNzI3MxAAOANCAEgDWhYKC2FwcGxpY2F0aW9uEgdQcmF2ZWdhWhUKD0Jvb2tLZWVwZXJMb2dJZBICMTlgwe6Our+L88RZ
2022-05-12 08:24:50,348 1589233 [main-SendThread(zookeeper-client:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply session id: 0x201fbeaaa9705c9, packet:: clientPath:/pravega/pravega/bookkeeper/ledgers/00/0000/L5124 serverPath:/pravega/pravega/bookkeeper/ledgers/00/0000/L5124 finished:false header:: 293,1  replyHeader:: 293,4295015163,0  request:: '/pravega/pravega/bookkeeper/ledgers/00/0000/L5124,#426f6f6b69654d65746164617461466f726d617456657273696f6e933affffffa618310318020ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff12813252a18626f6f6b6b65657065722d626f6f6b69652d312d32353534a19626f6f6b6b65657065722d626f6f6b69652d322d3136333537a19626f6f6b6b65657065722d626f6f6b69652d302d31373237331003834204835a16ab6170706c69636174696f6e127507261766567615a15af426f6f6b4b65657065724c6f674964122313960ffffffc1ffffffeeffffff8effffffbaffffffbfffffff8bfffffff3ffffffc459,v{s{31,s{'world,'anyone}}},0  response:: '/pravega/pravega/bookkeeper/ledgers/00/0000/L5124
2022-05-12 08:24:50,348 1589233 [main-SendThread(zookeeper-client:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply session id: 0x201fbeaaa9705c9, packet:: clientPath:/pravega/pravega/bookkeeper/ledgers/idgen/ID-0000005124 serverPath:/pravega/pravega/bookkeeper/ledgers/idgen/ID-0000005124 finished:false header:: 294,2  replyHeader:: 294,4295015164,0  request:: '/pravega/pravega/bookkeeper/ledgers/idgen/ID-0000005124,-1  response:: null
2022-05-12 08:24:50,348 1589233 [main-EventThread] INFO  o.a.b.client.LedgerCreateOp - Ensemble: [bookkeeper-bookie-1-2554, bookkeeper-bookie-2-16357, bookkeeper-bookie-0-17273] for ledger: 5124
2022-05-12 08:24:50,348 1589233 [main-EventThread] DEBUG o.a.b.meta.ZkLedgerIdGenerator - Deleting znode for id generation : /pravega/pravega/bookkeeper/ledgers/idgen/ID-0000005124
2022-05-12 08:24:50,348 1589233 [core-18] DEBUG i.p.s.s.i.bookkeeper.BookKeeperLog - Log[19]: Rollover: created new ledger 5124.
2022-05-12 08:24:50,353 1589238 [main-SendThread(zookeeper-client:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply session id: 0x201fbeaaa9705c8, packet:: clientPath:null serverPath:null finished:false header:: 126,5  replyHeader:: 126,4295015165,0  request:: '/pravega/pravega/segmentstore/containers/9/1/19,#00100001515ffffffc00040077516d2516d4054450,10  response:: s{4294969408,4295015165,1652331647161,1652343890350,11,0,0,0,29,0,4294969408}
2022-05-12 08:24:50,353 1589238 [core-18] INFO  i.p.s.s.i.bookkeeper.BookKeeperLog - Log[19] Metadata persisted (Version = 11, Epoch = 5, LedgerCount = 2, Truncate = (4461-1799)).
2022-05-12 08:24:50,353 1589238 [core-18] INFO  i.p.s.s.i.bookkeeper.BookKeeperLog - Log[19] Metadata updated (Version = 11, Epoch = 5, LedgerCount = 2, Truncate = (4461-1799)).
2022-05-12 08:24:50,354 1589239 [core-18] DEBUG i.p.s.s.i.bookkeeper.BookKeeperLog - Log[19]: Rollover: updated metadata 'Version = 11, Epoch = 5, LedgerCount = 2, Truncate = (4461-1799).
2022-05-12 08:24:50,354 1589239 [core-18] DEBUG io.pravega.common.util.Retry - Retrying command io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog$$Lambda$627/0x0000000800610440@7f74ce1c Retry #2, timestamp=2022-05-12T08:24:50.354222Z
2022-05-12 08:24:50,354 1589239 [main-SendThread(zookeeper-client:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply session id: 0x201fbeaaa9705c9, packet:: clientPath:/pravega/pravega/bookkeeper/ledgers/00/0000/L4461 serverPath:/pravega/pravega/bookkeeper/ledgers/00/0000/L4461 finished:false header:: 295,4  replyHeader:: 295,4295015165,0  request:: '/pravega/pravega/bookkeeper/ledgers/00/0000/L4461,F  response:: #426f6f6b69654d65746164617461466f726d617456657273696f6e933affffffc128310318ffffff95ffffff851b20ffffffc6e2833252a18626f6f6b6b65657065722d626f6f6b69652d312d32353534a19626f6f6b6b65657065722d626f6f6b69652d322d3136333537a19626f6f6b6b65657065722d626f6f6b69652d302d31373237331003252a18626f6f6b6b65657065722d626f6f6b69652d332d32353835a19626f6f6b6b65657065722d626f6f6b69652d322d3136333537a19626f6f6b6b65657065722d626f6f6b69652d302d313732373310613253a18626f6f6b6b65657065722d626f6f6b69652d312d32353534a19626f6f6b6b65657065722d626f6f6b69652d322d3136333537a19626f6f6b6b65657065722d626f6f6b69652d302d313732373310ffffffc6e3834204835a16ab6170706c69636174696f6e127507261766567615a15af426f6f6b4b65657065724c6f6749641223139600,s{4295005893,4295014889,1652342315748,1652343857385,3,0,0,0,353,0,4295005893}
2022-05-12 08:24:50,355 1589240 [main-EventThread] DEBUG o.a.b.meta.LedgerMetadataSerDe - Deserializing Qm9va2llTWV0YWRhdGFGb3JtYXRWZXJzaW9uCTMKwQIIAxADGJWFGyDGDigDMlIKGGJvb2trZWVwZXItYm9va2llLTEtMjU1NAoZYm9va2tlZXBlci1ib29raWUtMi0xNjM1NwoZYm9va2tlZXBlci1ib29raWUtMC0xNzI3MxAAMlIKGGJvb2trZWVwZXItYm9va2llLTMtMjU4NQoZYm9va2tlZXBlci1ib29raWUtMi0xNjM1NwoZYm9va2tlZXBlci1ib29raWUtMC0xNzI3MxBhMlMKGGJvb2trZWVwZXItYm9va2llLTEtMjU1NAoZYm9va2tlZXBlci1ib29raWUtMi0xNjM1NwoZYm9va2tlZXBlci1ib29raWUtMC0xNzI3MxDGDjgDQgBIA1oWCgthcHBsaWNhdGlvbhIHUHJhdmVnYVoVCg9Cb29rS2VlcGVyTG9nSWQSAjE5YAA=
2022-05-12 08:24:50,355 1589240 [main-EventThread] DEBUG o.a.b.meta.LedgerMetadataSerDe - Format version 3 detected
```

- Then, the container retries whatever pending writes that were yet to be completed. In this case, entry `0` written to the new ledger `5124` is the same as entry `1862` of the previous ledger:
```
2022-05-12 08:24:50,356 1589241 [core-20] INFO  i.p.s.s.i.bookkeeper.BookKeeperLog - Log[19]: Fetched actual LastAddConfirmed (1862) for LedgerId 4461.
2022-05-12 08:24:50,356 1589241 [core-20] DEBUG i.p.s.s.i.bookkeeper.BookKeeperLog - Log[19]: Executing 1 writes.
2022-05-12 08:24:50,359 1589244 [BookKeeperClientWorker-OrderedExecutor-0-0] DEBUG o.a.b.proto.PerChannelBookieClient - Got Add response from bookie:bookkeeper-bookie-0-17273 rc:EOK, ledger:5124:entry:0
2022-05-12 08:24:50,360 1589245 [BookKeeperClientWorker-OrderedExecutor-0-0] DEBUG o.a.b.proto.PerChannelBookieClient - Got Add response from bookie:bookkeeper-bookie-1-2554 rc:EOK, ledger:5124:entry:0
```

- The problem comes later on, if a container recovery is triggered, Pravega checks that entries written to Bookkeeper follow a strict monotonically increasing order: https://github.com/pravega/pravega/blob/e72018d70f790365ea7d857921af8d7b4cef5d25/segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java#L108
And, in fact, we can see that during the container recovery process (see attached log [0-pravega-segmentstore-5ba2c83d-2022-05-12T09-12-28Z.log.gz](https://github.com/pravega/pravega/files/8688765/0-pravega-segmentstore-5ba2c83d-2022-05-12T09-12-28Z.log.gz)), the Bookie `bookkeeper-bookie-0-17273` is the one replying with entry `1862` from ledger `4461`, which was not acknowledged by the client and therefore re-written to the next ledger `5124`:
```
2022-05-12 09:12:11,099 3111453 [BookKeeperClientWorker-OrderedExecutor-1-0] DEBUG o.a.b.proto.PerChannelBookieClient - Got Read response from bookie:bookkeeper-bookie-0-17273 rc:EOK, ledger:4461:entry:1862:entryLength:1125
```

- The interesting thing is that, if we revisit the logs, the `BookkeeperLog` class queries the `lastAddConfirmed` of the previous ledger, and it actually outputs `1862`, which is the last entry written to ledger `4461` in Bookie 0:
```
2022-05-12 08:24:50,356 1589241 [core-20] INFO  i.p.s.s.i.bookkeeper.BookKeeperLog - Log[19]: Fetched actual LastAddConfirmed (1862) for LedgerId 4461
```

While now `BookkeeperLog` class only uses `entryId` in Bookkeeper "after" the write succeeds, maybe we can use this information to prevent this from happening. What do you think @andreipaduroiu @eolivelli @abhinb?
