### ISSUE TITLE
Flaky test GarbageCollectorTests.testMaxAttempts()

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#6483]
**Describe the bug**
Found test failing sporadically in Git Actions:
```
io.pravega.segmentstore.storage.chunklayer.GarbageCollectorTests > testMaxAttempts FAILED
    java.lang.AssertionError: expected:<1> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.pravega.segmentstore.storage.chunklayer.GarbageCollectorTests.assertQueueEquals(GarbageCollectorTests.java:1325)
        at io.pravega.segmentstore.storage.chunklayer.GarbageCollectorTests.testMaxAttempts(GarbageCollectorTests.java:1194)
```

**To Reproduce**
Sporadically reproducible running `./gradlew build`

**Screenshots**
n/a

**Additional information**
n/a

**Comment by RaulGracia** [comment]
Another instance:
```
io.pravega.segmentstore.storage.chunklayer.GarbageCollectorTests > testMaxAttempts FAILED
    java.lang.AssertionError: expected:<1> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.pravega.segmentstore.storage.chunklayer.GarbageCollectorTests.assertQueueEquals(GarbageCollectorTests.java:1325)
        at io.pravega.segmentstore.storage.chunklayer.GarbageCollectorTests.testMaxAttempts(GarbageCollectorTests.java:1194)
```

**Comment by RaulGracia** [comment]
Another similar test failing, not the same though:
```
io.pravega.segmentstore.storage.chunklayer.GarbageCollectorTests > testIOException FAILED
    java.lang.AssertionError: expected:<1> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.pravega.segmentstore.storage.chunklayer.GarbageCollectorTests.assertQueueEquals(GarbageCollectorTests.java:1325)
        at io.pravega.segmentstore.storage.chunklayer.GarbageCollectorTests.testIOException(GarbageCollectorTests.java:644)
```
