### ISSUE TITLE
problem with startup 

### ISSUE THREAD

**Issue by 2779382063** [pravega/pravega#6630]
After installing zookeeper-3.6.3 and bookkeeper4.1.1 according to the manual installation steps，Install pravega error 
1、The error message when starting pravega-controller is as follows ：

2022-03-10 17:19:15,254 355042 [controllerpool-6] WARN  i.p.c.s.PravegaTablesStoreHelper - [requestId=-2807520946765370725] Host Store exception Could not find host for container id: 3
2022-03-10 17:19:16,855 356643 [controllerpool-54] WARN  i.p.c.s.PravegaTablesStoreHelper - [requestId=-2807520946765370725] Host Store exception Could not find host for container id: 3
2022-03-10 17:19:20,056 359844 [controllerpool-54] WARN  i.p.c.s.PravegaTablesStoreHelper - [requestId=-2807520946765370725] Host Store exception Could not find host for container id: 3
2022-03-10 17:19:24,462 364250 [controllerpool-62] WARN  i.p.c.f.ControllerClusterListener - java.lang.RuntimeException: sweeper class io.pravega.controller.server.eventProcessor.ControllerEventProcessors not ready, retrying with exponential backoff.

2、The error message when starting pravega-segmentstore is as follows ：

2022-03-10 17:13:46,379 1228 [main] ERROR o.a.b.client.BookieWatcherImpl - Failed to get bookie list :
org.apache.bookkeeper.client.BKException$ZKException: Error while using ZooKeeper
        at org.apache.bookkeeper.discover.ZKRegistrationClient.lambda$getChildren$4(ZKRegistrationClient.java:351)
        at org.apache.bookkeeper.zookeeper.ZooKeeperClient$25$1.processResult(ZooKeeperClient.java:1177)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:630)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:510)
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /pravega/pravega-cluster/bookkeeper/ledgers/available
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:118)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at org.apache.bookkeeper.discover.ZKRegistrationClient.lambda$getChildren$4(ZKRegistrationClient.java:350)
        ... 3 common frames omitted
2022-03-10 17:13:46,379 1228 [main] ERROR i.p.s.server.host.ServiceStarter - Could not start the Service, Aborting.
io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to establish connection to ZooKeeper or BookKeeper.
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogFactory.initialize(BookKeeperLogFactory.java:123)
        at io.pravega.segmentstore.server.store.ServiceBuilder.initialize(ServiceBuilder.java:248)
        at io.pravega.segmentstore.server.host.ServiceStarter.start(ServiceStarter.java:128)
        at io.pravega.segmentstore.server.host.ServiceStarter.main(ServiceStarter.java:347)
Caused by: org.apache.bookkeeper.client.BKException$ZKException: Error while using ZooKeeper
        at org.apache.bookkeeper.discover.ZKRegistrationClient.lambda$getChildren$4(ZKRegistrationClient.java:351)
        at org.apache.bookkeeper.zookeeper.ZooKeeperClient$25$1.processResult(ZooKeeperClient.java:1177)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:630)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:510)
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /pravega/pravega-cluster/bookkeeper/ledgers/available
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:118)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at org.apache.bookkeeper.discover.ZKRegistrationClient.lambda$getChildren$4(ZKRegistrationClient.java:350)
        ... 3 common frames omitted

**Comment by 2779382063** [comment]
I know what went wrong in the tutorial, but how do I run the service in the background without printing the log directly

**Comment by andreipaduroiu** [comment]
@2779382063 Thanks for trying out Pravega. 

The error from the Controller is due to the one in the Segment Store. The Segment Store can't bootstrap because, while it can connect to ZK, it can't read the appropriate paths from there. 

Have you followed the instructions on this page? 
https://github.com/pravega/pravega/blob/master/documentation/src/docs/deployment/manual-install.md#initializing-zookeeper-paths

A quick note that this is different than Standalone; Standalone is a local sandbox that doesn't use ZK, so you will need to properly set up the ZK config as instructed in the above wiki doc.

**Comment by 2779382063** [comment]
The startup method of the tutorial will continue to print the log to the console. Can you run pravega in the background without printing out the log?

**Comment by andreipaduroiu** [comment]
Pravega prints logs to the console. That's how they're captured by K8s and logged (to where they should be logged in production - user's choice). 

Have you tried editing or creating a `logback.xml` in your classpath where you configure Log4j to write to files instead of `STDOUT`? 

If you can provide more details about your deployment setup, then we may be able to offer more help in getting your issue resolved.

**Comment by 2779382063** [comment]
Installed following this tutorial : https://pravega.io/docs/latest/deployment/manual-install/
In this way, starting pravega will print out the log to the console, and closing the session service will also close, I want to start it by daemon.

**Comment by 2779382063** [comment]
Installed following this tutorial : https://pravega.io/docs/latest/deployment/manual-install/
In this way, starting pravega will print out the log to the console, and closing the session service will also close, I want to start it by daemon.

**Comment by andreipaduroiu** [comment]
Ah I see. So you're trying to start from the command line. If you're running in Linux/Mac, I think adding `&` at the end of the command (in the terminal/shell script) will cause the process to start separately and give you back control of your terminal.

**Comment by RaulGracia** [comment]
Hi @2779382063,

As @andreipaduroiu mentioned, the problem in these logs are probably related to Segment Store not finding the Bookkeeper ledger path. If you have started Bookkeeper as a separate process in your machine (like `bin/bookkeeper standalone`), it will probably create the metadata path in Zookeeper under `/ledgers` zNode. However, Pravega is expecting Bookkeeper metadata to be stored in under `/pravega/pravega-cluster/bookkeeper/` zNode in Zookeeper.

My suggestion: change the `bookkeeper.ledger.path` property in Pravega ([see the property here](https://github.com/pravega/pravega/blob/b4a615e821b949891f73aa8c1a873fcf17df8700/config/config.properties#L350)) to `/ledgers`. Note that the Bookkeeper Operator we have contributed takes care of these details, if you are thinking of deploying Pravega in Kubernetes.

Let us know if it works for you.

**Comment by RaulGracia** [comment]
Assuming this issue is fixed, as there is no more feedback provided.
