### ISSUE TITLE
write test

### ISSUE THREAD

**Issue by 2779382063** [pravega/pravega#6652]
Follow this process to deploy a 3-node cluster :  https://pravega.io/docs/latest/deployment/manual-install/

A large amount of data writing test is performed through the following program, and the result is not ideal. The concurrency of 100 rows/second is too low. Is my test method wrong? Or is there a testing tool for stress testing.

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pravega.test;

import java.net.URI;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.concurrent.CompletableFuture;

import io.pravega.client.ClientConfig;
import io.pravega.client.EventStreamClientFactory;
import io.pravega.client.admin.ReaderGroupManager;
import io.pravega.client.admin.StreamManager;
import io.pravega.client.stream.EventStreamReader;
import io.pravega.client.stream.EventStreamWriter;
import io.pravega.client.stream.EventWriterConfig;
import io.pravega.client.stream.ReaderConfig;
import io.pravega.client.stream.ReaderGroupConfig;
import io.pravega.client.stream.ScalingPolicy;
import io.pravega.client.stream.Stream;
import io.pravega.client.stream.StreamConfiguration;
import io.pravega.client.stream.impl.JavaSerializer;
import io.pravega.client.stream.impl.UTF8StringSerializer;

class RunnableDemo implements Runnable {
	   private Thread t;
	   private String threadName;
	   private String routingKey;
	 //  private String streamName;
	   RunnableDemo( String name,String Key) {
		      threadName = name;
		  //    message = mes;
		      routingKey = Key;
		  //    streamName = stname;
		     // System.out.println("Creating " +  threadName );
		   }
	   
	   public void run() {
		   	String scope="demo";
		   	String streamName="demo";
		   	URI controllerURI = URI.create("tcp://172.16.3.179:9090");
		    
		    for (int i = 0; i < 10000; i++) {
		    	long time = new Date().getTime(); 
		    	String message = String.valueOf(time);
		    	try (EventStreamClientFactory clientFactory = EventStreamClientFactory.withScope(scope,
		    			ClientConfig.builder().controllerURI(controllerURI).build());
		    			EventStreamWriter<String> writer = clientFactory.createEventWriter(streamName,
		    					new JavaSerializer<String>(),
		    					EventWriterConfig.builder().build()))
		    	{
		    		System.out.format("Writing message: '%s' with routing-key: '%s' to stream '%s / %s'%n",
		    				message, routingKey, scope, streamName);
		    		final CompletableFuture<Void> writeFuture = writer.writeEvent(routingKey, message);
		    	}
		    }
		}
	   
	   public void start () {
	      
	      if (t == null) {
	    //	  System.out.println("Stag " );
	         t = new Thread (this, threadName);
	         t.start ();
	         
	      }
	   }

	}

public class Library {
	public static void main(String[] args) throws Exception {
		String scope="demo";
	   	String streamName="demo";
	   	URI controllerURI = URI.create("tcp://172.16.3.179:9090");
	    StreamManager streamManager = StreamManager.create(controllerURI);

	    final boolean scopeCreation = streamManager.createScope(scope);
	    StreamConfiguration streamConfig = StreamConfiguration.builder()
	            .scalingPolicy(ScalingPolicy.fixed(1))
	            .build();
	    final boolean streamCreation = streamManager.createStream(scope, streamName, streamConfig);
	//    int i=10;
	//   	String s = String.valueOf(i);
	//   	s=scope+s;
		 //System.out.format("%s",s);
		 System.out.println("begin");
		 for (int i = 1; i < 100; i++) {
			 String s = String.valueOf(i);
			// String name=streamName+s;
			 RunnableDemo R1 = new RunnableDemo(s,s);
			 R1.start();
		 }
	//	 System.out.println("ok");
		
	}
    
}

**Comment by andreipaduroiu** [comment]
hi @2779382063 !

Have you checked the [Local Stress Tester](https://github.com/pravega/pravega/wiki/Local-Stress-Testing)?

This is the tool that we have been using to benchmark anything from BK itself to the Segment Store, Client, wire protocol, etc. It has many knobs and can test writes, reads, transactions, etc.

**Comment by andreipaduroiu** [comment]
You can also check our official benchmark tools:

https://github.com/pravega/openmessaging-benchmark

https://github.com/pravega/pravega-benchmark

**Comment by 2779382063** [comment]
Hello, when using the test tool (https://github.com/pravega/pravega-benchmark) to perform the writing test, the running command is as follows. When the writing is halfway through, the database crashes and the pravega-segmentstore service reports an error message as follows:



2022-03-22 09:22:34,810 84033639 [core-22] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[3]: Closed.
2022-03-22 09:22:34,810 84033639 [core-24] ERROR i.p.s.s.s.StreamSegmentContainerRegistry - Critical failure for SegmentContainer Container Id = 2, State = FAILED. {}
io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to create new BookKeeper Ledger.
        at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.create(Ledgers.java:101)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.initialize(BookKeeperLog.java:243)
        at io.pravega.segmentstore.server.logs.DurableLog.performRecovery(DurableLog.java:217)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at io.pravega.common.concurrent.ThreadPoolScheduledExecutorService$ScheduledRunnable.run(ThreadPoolScheduledExecutorService.java:189)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: Not enough non-faulty bookies available
        at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:83)
        at org.apache.bookkeeper.client.SyncCallbackUtils$SyncCreateCallback.createComplete(SyncCallbackUtils.java:106)
        at org.apache.bookkeeper.client.LedgerCreateOp.createComplete(LedgerCreateOp.java:272)
        at org.apache.bookkeeper.client.LedgerCreateOp.initiate(LedgerCreateOp.java:166)
        at org.apache.bookkeeper.client.LedgerCreateOp$CreateBuilderImpl.create(LedgerCreateOp.java:403)
        at org.apache.bookkeeper.client.LedgerCreateOp$CreateBuilderImpl.execute(LedgerCreateOp.java:383)
        at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.create(Ledgers.java:98)
        ... 8 common frames omitted
2022-03-22 09:22:34,810 84033639 [core-22] INFO  i.p.c.c.AbstractThreadPoolService - StorageWriter[3]: Closed.
2022-03-22 09:22:34,811 84033640 [core-22] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[3]: Closed.
2022-03-22 09:22:34,811 84033640 [core-22] INFO  i.p.s.s.i.bookkeeper.BookKeeperLog - Log[3]: Closed.
2022-03-22 09:22:34,811 84033640 [core-22] INFO  i.p.s.server.logs.DurableLog - DurableLog[3]: Closed.
2022-03-22 09:22:34,811 84033640 [core-22] INFO  i.p.s.s.reading.ContainerReadIndex - ReadIndex[3]: Closed.
2022-03-22 09:22:34,811 84033640 [core-22] INFO  i.p.s.s.a.ContainerAttributeIndexImpl - ContainerAttributeIndex[3]: Closed.
2022-03-22 09:22:34,811 84033640 [core-22] INFO  i.p.s.s.c.ChunkedSegmentStorage - null Closed metadataStore
2022-03-22 09:22:34,811 84033640 [core-22] INFO  i.p.s.s.c.ChunkedSegmentStorage - null Closed garbageCollector
2022-03-22 09:22:34,811 84033640 [core-22] INFO  i.p.s.s.c.ChunkedSegmentStorage - null Closed taskQueue
2022-03-22 09:22:34,811 84033640 [core-22] INFO  i.p.s.s.c.ContainerEventProcessorImpl - ContainerEventProcessor[3]: Closing ContainerEventProcessor service.
2022-03-22 09:22:34,811 84033640 [core-22] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[3]: Closed.
2022-03-22 09:22:34,811 84033640 [core-22] INFO  i.p.s.s.s.StreamSegmentContainerRegistry - Unregistered SegmentContainer 3.

**Comment by 2779382063** [comment]
Hello, when using the test tool (https://github.com/pravega/pravega-benchmark) to perform the writing test, the running command is as follows：
run/pravega-benchmark/bin/pravega-benchmark -controller tcp://172.16.3.181:9090  -stream demo -segments 1 -producers 100 -size 100 -throughput -1 -events 100000000

When the writing is halfway through, the database crashes and the pravega-segmentstore service reports an error message as follows:
-------------------------------------------------------------------------
2022-03-22 09:22:34,810 84033639 [core-22] INFO i.p.c.c.AbstractThreadPoolService - SegmentContainer[3]: Closed.
2022-03-22 09:22:34,810 84033639 [core-24] ERROR i.p.s.s.s.StreamSegmentContainerRegistry - Critical failure for SegmentContainer Container Id = 2, State = FAILED. {}
io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to create new BookKeeper Ledger.
at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.create(Ledgers.java:101)
at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.initialize(BookKeeperLog.java:243)
at io.pravega.segmentstore.server.logs.DurableLog.performRecovery(DurableLog.java:217)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at io.pravega.common.concurrent.ThreadPoolScheduledExecutorService$ScheduledRunnable.run(ThreadPoolScheduledExecutorService.java:189)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: Not enough non-faulty bookies available
at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:83)
at org.apache.bookkeeper.client.SyncCallbackUtils$SyncCreateCallback.createComplete(SyncCallbackUtils.java:106)
at org.apache.bookkeeper.client.LedgerCreateOp.createComplete(LedgerCreateOp.java:272)
at org.apache.bookkeeper.client.LedgerCreateOp.initiate(LedgerCreateOp.java:166)
at org.apache.bookkeeper.client.LedgerCreateOp$CreateBuilderImpl.create(LedgerCreateOp.java:403)
at org.apache.bookkeeper.client.LedgerCreateOp$CreateBuilderImpl.execute(LedgerCreateOp.java:383)
at io.pravega.segmentstore.storage.impl.bookkeeper.Ledgers.create(Ledgers.java:98)
... 8 common frames omitted
2022-03-22 09:22:34,810 84033639 [core-22] INFO i.p.c.c.AbstractThreadPoolService - StorageWriter[3]: Closed.
2022-03-22 09:22:34,811 84033640 [core-22] INFO i.p.c.c.AbstractThreadPoolService - OperationProcessor[3]: Closed.
2022-03-22 09:22:34,811 84033640 [core-22] INFO i.p.s.s.i.bookkeeper.BookKeeperLog - Log[3]: Closed.
2022-03-22 09:22:34,811 84033640 [core-22] INFO i.p.s.server.logs.DurableLog - DurableLog[3]: Closed.
2022-03-22 09:22:34,811 84033640 [core-22] INFO i.p.s.s.reading.ContainerReadIndex - ReadIndex[3]: Closed.
2022-03-22 09:22:34,811 84033640 [core-22] INFO i.p.s.s.a.ContainerAttributeIndexImpl - ContainerAttributeIndex[3]: Closed.
2022-03-22 09:22:34,811 84033640 [core-22] INFO i.p.s.s.c.ChunkedSegmentStorage - null Closed metadataStore
2022-03-22 09:22:34,811 84033640 [core-22] INFO i.p.s.s.c.ChunkedSegmentStorage - null Closed garbageCollector
2022-03-22 09:22:34,811 84033640 [core-22] INFO i.p.s.s.c.ChunkedSegmentStorage - null Closed taskQueue
2022-03-22 09:22:34,811 84033640 [core-22] INFO i.p.s.s.c.ContainerEventProcessorImpl - ContainerEventProcessor[3]: Closing ContainerEventProcessor service.
2022-03-22 09:22:34,811 84033640 [core-22] INFO i.p.s.s.c.StreamSegmentContainer - SegmentContainer[3]: Closed.
2022-03-22 09:22:34,811 84033640 [core-22] INFO i.p.s.s.s.StreamSegmentContainerRegistry - Unregistered SegmentContainer 3.
------------------------------------------------------------------------------------------------------------------


When the writing is halfway through, the database crashes and the pravega-controller service reports an error message as follows:
-------------------------------------------------------------------------------------------------------------------
2022-03-22 09:36:44,884 84832567 [ClientSocketReaders-34] WARN  i.p.c.s.i.SegmentOutputStreamImpl - Failing connection for writer d8e29fe4-3975-4cc6-a2ef-fbb7d0deb854 with exception io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=743029342208, segment=_system/_kvTableStream/2.#epoch.0, correctHost=, serverStackTrace=)
2022-03-22 09:36:44,884 84832567 [ClientSocketReaders-34] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Handling exception io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=743029342208, segment=_system/_kvTableStream/2.#epoch.0, correctHost=, serverStackTrace=) for connection io.pravega.client.connection.impl.FlowClientConnection@47f3ec20 on writer d8e29fe4-3975-4cc6-a2ef-fbb7d0deb854. SetupCompleted: false, Closed: false
2022-03-22 09:36:44,884 84832567 [ClientSocketReaders-34] WARN  i.p.c.s.i.SegmentOutputStreamImpl - Connection for segment _system/_kvTableStream/2.#epoch.0 on writer d8e29fe4-3975-4cc6-a2ef-fbb7d0deb854 failed due to: WireCommands.WrongHost(type=WRONG_HOST, requestId=743029342208, segment=_system/_kvTableStream/2.#epoch.0, correctHost=, serverStackTrace=)
2022-03-22 09:36:44,884 84832567 [clientInternal-1-11] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Fetching endpoint for segment _system/_kvTableStream/4.#epoch.0, writer 67278902-b0c4-4782-ab26-1f715624d2c7
2022-03-22 09:36:44,884 84832567 [clientInternal-1-11] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Establishing connection to 172.16.3.179:12345 for _system/_kvTableStream/4.#epoch.0, writerID: 67278902-b0c4-4782-ab26-1f715624d2c7
2022-03-22 09:36:44,884 84832567 [clientInternal-1-4] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Fetching endpoint for segment _system/_abortStream/0.#epoch.0, writer a5c05fb3-2e86-418b-9aee-6ed3cbeaf226
2022-03-22 09:36:44,884 84832567 [clientInternal-1-2] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Establishing connection to 172.16.3.179:12345 for _system/_abortStream/0.#epoch.0, writerID: a5c05fb3-2e86-418b-9aee-6ed3cbeaf226
2022-03-22 09:36:44,885 84832568 [ClientSocketReaders-34] WARN  i.p.c.s.i.SegmentOutputStreamImpl - Failing connection for writer 33b2671b-4756-4e54-b23d-b2006a234727 with exception io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=313532612608, segment=_system/_commitStream/1.#epoch.0, correctHost=, serverStackTrace=)
2022-03-22 09:36:44,885 84832568 [ClientSocketReaders-34] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Handling exception io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=313532612608, segment=_system/_commitStream/1.#epoch.0, correctHost=, serverStackTrace=) for connection io.pravega.client.connection.impl.FlowClientConnection@2d1f4db6 on writer 33b2671b-4756-4e54-b23d-b2006a234727. SetupCompleted: false, Closed: false
--------------------------------------------------------------------------------------------------------

**Comment by RaulGracia** [comment]
Hi @2779382063,

the problem you have with the code above is that you are creating a `EventStreamClientFactory` and a `EventStreamWriter` event written (the `try` block that creates these resources is inside the `for` loop). This is unnecessary and completely justifies that you only can write 100 events per second.

As @andreipaduroiu suggested, if you want to test performance, please use any of the aforementioned tools that we have that have been extensively used in the last years to this end. Also, if you are curious, there are some performance numbers we have published comparing Pravega against Kafka/Pulsar on AWS:
[When Speeding Makes Sense: Fast, Consistent, Durable, and Scalable Streaming Data with Pravega](https://cncf.pravega.io/blog/2020/10/01/when-speeding-makes-sense-fast-consistent-durable-and-scalable-streaming-data-with-pravega)
[When Speed Meets Parallelism - Pravega Performance under Parallel Streaming Workloads](https://cncf.pravega.io/blog/2021/03/10/when-speed-meets-parallelism-pravega-performance-under-parallel-streaming-workloads/)
