### ISSUE TITLE
Flaky test S3ChunkStorageSystemJournalTests.testSimpleOperationSequence

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#6683]
**Describe the bug**
Sporadically, we see the following test failing in our builds:
```
java.util.concurrent.CompletionException: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Chunk metadata must not be null.
	at io.pravega.segmentstore.storage.chunklayer.SystemJournal.lambda$applySystemLogOperations$51(SystemJournal.java:892)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Chunk metadata must not be null.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	... 7 more
Caused by: java.lang.IllegalStateException: Chunk metadata must not be null.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at io.pravega.segmentstore.storage.chunklayer.SystemJournal.lambda$validateChunksInSegmentSnapshot$32(SystemJournal.java:715)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 7 more
```

Also, we see another interesting trace claiming `taskQueue` to be null: 
[test-failure-trace.log](https://github.com/pravega/pravega/files/8449472/test-failure-trace.log)

**To Reproduce**
Run `./gradlew check` to run the tests, this error may happen sporadically.

**Screenshots**
n/a

**Additional information**
n/a

**Comment by sachin-j-joshi** [comment]
https://github.com/pravega/pravega/pull/6566 already fixes noise generated by `taskQueue` being null:

**Comment by RaulGracia** [comment]
@sachin-j-joshi oh, you are right. Forgot that we have not cherry picked that one. Closing this issue then.
