### ISSUE TITLE
NPE in ServerTransportListenerImpl

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#6690]
**Describe the bug**
When running the standalone it throws an NPE repeatedly when attempting to startup and shutdown. This prevents some tests from working. In particular all Integration tests for the Rust client fail due to this issue.
```
Mar 02, 2022 1:25:18 AM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated@450526dd
java.lang.NullPointerException: startCall() returned a null listener for method io.pravega.controller.stream.api.grpc.v1.ControllerService/getCurrentSegments
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:636)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startCall(ServerImpl.java:612)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$1800(ServerImpl.java:402)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInternal(ServerImpl.java:543)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInContext(ServerImpl.java:518)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by tkaitchuck** [comment]
An example of this is here: https://github.com/pravega/pravega-client-rust/runs/5636969184?check_suite_focus=true

**Comment by tkaitchuck** [comment]
Fixed in https://github.com/pravega/pravega-client-rust/pull/427
