### ISSUE TITLE
Corrupted BTreeIndex footer found after a segment container recovery when cache is full

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#6712]
**Describe the bug**
In a longevity workload (heavy workload mixing transactions and regular events), an issue was found after 24 days of uninterrupted operation. The sequence of steps:
1. All segment stores were working normally, until one of them started to show symptoms of cache being full:
```
2022-04-18 01:24:35,584 2138732271 [core-27] INFO  i.p.s.server.CacheManager - CacheManager: Cache full. Forcing cache policy.
...
2022-04-18 01:24:36,091 2138732778 [core-1] WARN  i.p.s.s.logs.MemoryStateUpdater - Not adding operation 'StreamSegmentAppendOperation: SequenceNumber = 866200873, SegmentId = 476901, Offset = 1784640543791, Length = 27594, Attributes = 2' to ReadIndex because the Cache is full.
2022-04-18 01:24:36,093 2138732780 [core-8] INFO  i.p.s.server.CacheManager - CacheManager: Cache full. Forcing cache policy.
2022-04-18 01:24:36,093 2138732780 [core-29] ERROR i.p.s.s.logs.OperationProcessor - OperationProcessor[1]: MemoryStateUpdater.process failure.
io.pravega.segmentstore.server.ServiceHaltException: Unable to add operation 'StreamSegmentAppendOperation: SequenceNumber = 866200874, SegmentId = 476901, Offset = 1784640571385, Length = 45651, Attributes = 2' to ReadIndex.
	at io.pravega.segmentstore.server.logs.MemoryStateUpdater.addToReadIndex(MemoryStateUpdater.java:276)
	at io.pravega.segmentstore.server.logs.MemoryStateUpdater.process(MemoryStateUpdater.java:196)
	at io.pravega.segmentstore.server.logs.MemoryStateUpdater.process(MemoryStateUpdater.java:158)
	at io.pravega.segmentstore.server.logs.OperationProcessor.processCommits(OperationProcessor.java:479)
	at io.pravega.segmentstore.server.logs.OperationProcessor.handleProcessCommits(OperationProcessor.java:188)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at io.pravega.common.concurrent.ThreadPoolScheduledExecutorService$ScheduledRunnable.run(ThreadPoolScheduledExecutorService.java:189)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: The given range of bytes (Offset=1784640571385) does not start right after the last appended offset (1784640543790).
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:385)
	at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.append(StreamSegmentReadIndex.java:399)
```
2. At this point, containers in this segment store were restarting. For the sake of conciseness, we can see that recoveries of Segment Container 32 complete normally, including the recovery of the SegmentAttributeIndex of Segment `476467211`:
```
2022-04-18 01:24:53,013 2138749700 [core-2] INFO  i.p.s.server.logs.RecoveryProcessor - RecoveryProcessor[32] Recovery started.
...
2022-04-18 01:24:37,109 2138733796 [core-17] INFO  i.p.s.server.CacheManager - CacheManager Unregistered ReadIndex[32-476467211] (_system/_tables/completedTransactionsBatch-24).
...
2022-04-18 01:24:55,916 2138752603 [core-2] INFO  i.p.s.server.logs.RecoveryProcessor - RecoveryProcessor[32] Recovery completed. Epoch = 9501, Items Recovered = 6575, Time = 2902ms.
...
2022-04-18 01:25:13,514 2138770201 [core-18] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[32-476467211]: Initialized. StorageLength = 83189810, Sealed = false.
2022-04-18 01:25:13,514 2138770201 [core-18] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[32-476467211]: State changed from NotInitialized to Writing.
2022-04-18 01:25:13,550 2138770237 [core-9] INFO  i.p.common.util.btree.BTreeIndex - AttributeIndex[32-476467211]: Initialized. State = Length = 12619552104, RootOffset = 12619519506, RootLength = 32586, Stats = null.
2022-04-18 01:25:13,550 2138770237 [core-9] INFO  i.p.s.server.CacheManager - CacheManager Registered AttributeIndex[32-476467211].
```
3. Note that this SegmentAttributeIndex (`476467211`) gets initialized multiple times. Also, we can observe the length progressing, probably due to the progress of segment attributes being written to LTS:
```
2022-04-18 01:32:01,462 2139178149 [core-30] INFO  i.p.common.util.btree.BTreeIndex - AttributeIndex[32-476467211]: Initialized. State = Length = 12700724422, RootOffset = 12700724328, RootLength = 82, Stats = null.
2022-04-18 01:32:01,462 2139178149 [core-30] INFO  i.p.s.server.CacheManager - CacheManager Registered AttributeIndex[32-476467211].
...
2022-04-18 01:38:11,425 2139548112 [core-30] INFO  i.p.common.util.btree.BTreeIndex - AttributeIndex[32-476467211]: Initialized. State = Length = 12778338702, RootOffset = 12778338608, RootLength = 82, Stats = null.
2022-04-18 01:38:11,425 2139548112 [core-30] INFO  i.p.s.server.CacheManager - CacheManager Registered AttributeIndex[32-476467211].
```

4. However, after 20 minutes in this situation, we observe that there is a `DataCorruptionException` initializing the SegmentAttributeIndex for Segment `476467211` in Segment Container 32:

```
2022-04-18 01:44:13,832 2139910519 [core-29] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[32-476467211]: Initialized. StorageLength = 84588130, Sealed = false.
2022-04-18 01:44:13,832 2139910519 [core-29] INFO  i.p.s.s.writer.SegmentAggregator - StorageWriter[32-476467211]: State changed from NotInitialized to Writing.
...
2022-04-18 01:44:13,934 2139910621 [core-25] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[32]: Iteration[6].CriticalError.
io.pravega.segmentstore.server.DataCorruptionException: BTreeIndex operation failed. Index corrupted.
	at io.pravega.segmentstore.server.attributes.SegmentAttributeBTreeIndex.handleIndexOperationException(SegmentAttributeBTreeIndex.java:808)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at io.pravega.common.concurrent.ThreadPoolScheduledExecutorService$ScheduledRunnable.run(ThreadPoolScheduledExecutorService.java:189)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.pravega.common.util.IllegalDataFormatException: [AttributeIndex[32-476467211]] Wrong footer information. RootPage Offset (6805637576853986517) + Length (-1140654080) exceeds Footer Offset (12845447554).
	at io.pravega.common.util.btree.BTreeIndex.initialize(BTreeIndex.java:235)
	at io.pravega.common.util.btree.BTreeIndex.lambda$initialize$0(BTreeIndex.java:213)
	... 7 common frames omitted
```

5. When inspecting the footer contents from the storage (i.e., reading the last 30 bytes of that BTreeIndex on LTS), we see that the wrong lengths seen in the above error can be also found there:
```
7500802929515823104,  1207,  8556285034968135232,  6805637576853986517,  -1140654080
```
This implies that the last write for the footer may be writing wrong/corrupted data, which impedes the initialization of the BTreeIndex in the next recovery.

**To Reproduce**
Hard to do, the code has been there for years and it is the first time we find this issue. Probably related to write the footer of a BTree under complete cache full situation, but we still need to reproduce it via tests.

**Screenshots**
n/a

**Additional information**
Apart from finding the root cause, it would be interesting to see if we can come up with a repair process for this particular BTreeIndex.
Also, it could also be the case that the LTS storage could have corrupted the data, but this looks more unlikely.

**Comment by andreipaduroiu** [comment]
#5521 solved some issues around this area a while back. Hopefully that can help with RCA-ing this down.

**Comment by RaulGracia** [comment]
We are attempting to analyze the index files' content. At the moment, we have tried with the following test code to try parsing `BTreePages` from the non corrupted index file (`main()` method in `BTreePage` class for testing):
```
public static void main(String[] args) throws IOException {
         /** Format: Header|Data|Footer
                * * Header: FormatVersion(1)|Flags(1)|Id(4)|Count(4)
                * * Data: List{Key(KL)|Value(VL)}
                * Footer: Id(4)*/
        byte[] contents = Files.readAllBytes(Path.of("/home/raul//Documents/workspace/PRAVEGA-2145/batch24/" +
                "completedTransactionsBatch-24$attributes.index.E-9503-O-12767833286.5793f919-338d-4dd1-9ea6-b2eb0e2bb883"));
        ByteArraySegment byteArraySegment = new ByteArraySegment(contents);
        val indexPageConfig = new BTreePage.Config(16, 8, Config.MAX_PAGE_SIZE, true);
        val leafPageConfig = new BTreePage.Config(16, 8, Config.MAX_PAGE_SIZE, false);
        for (int indexContentsOffset = 0; indexContentsOffset < byteArraySegment.getLength(); indexContentsOffset++) {
            for (int pageLength = 0; pageLength < Config.MAX_PAGE_SIZE; pageLength++) {
                BTreePage page;
                try {
                    page = new BTreePage(leafPageConfig, byteArraySegment.slice(indexContentsOffset, pageLength), true);
                    if (page.getCount() > 0 && page.getCount() < 100000) {
                        System.err.println("LEAF FOUND! " + page.getCount() + " " + UUID.nameUUIDFromBytes(page.getEntryAt(0).getKey().array()) + " " + page.getEntryAt(0).getValue().getLong(0));
                    }
                } catch (Exception ex) {}

                try {
                    page = new BTreePage(indexPageConfig, byteArraySegment.slice(indexContentsOffset, pageLength), true);
                    if (page.getCount() > 0 && page.getCount() < 100000) {
                        System.err.println("INDEX FOUND! " + page.getCount() + " " + UUID.nameUUIDFromBytes(page.getEntryAt(0).getKey().array()) + " " + page.getEntryAt(0).getValue().getLong(0));
                    }
                } catch (Exception ex) {}
            }
        }
    }
```
As we do not know exactly the right offset to start reading the file, we have to look for it. For this reason, this code snippet loads from memory the index file (10MB) and attempts to create a `BTreePage` with validation of sizes from 0 up to `Config.MAX_PAGE_SIZE` (32KB).

Running this code for some time, we see multiple `BTreePage` objects passing the validation (i.e., that the random id generated in the `BTreePage` header corresponds to that written at the end of the page). But this looks a required condition but not sufficient to ensure that we are reading an actual correct `BTreePage`. When running this code, we can see logs like:
```
INDEX FOUND! 36733 0b114903-7b41-3c36-a335-720583e1a1f0 -2377900603251305699
LEAF FOUND! 36733 0b114903-7b41-3c36-a335-720583e1a1f0 -2377900603251305699
...
LEAF FOUND! 88087 0b114903-7b41-3c36-a335-720583e1a1f0 -5044031582654808764
INDEX FOUND! 88087 0b114903-7b41-3c36-a335-720583e1a1f0 -5044031582654808764
...
LEAF FOUND! 29464 0b114903-7b41-3c36-a335-720583e1a1f0 -2017612633061787365
INDEX FOUND! 29464 0b114903-7b41-3c36-a335-720583e1a1f0 -2017612633061787365`
```

The first number in the output is related to the `page.getCount()`. If we consider that each page has a max size of 32KB and each entry is composed by a UUID key (16 bytes) plus a long value (8 byes), entry counts like the ones in the output clearly exceed the max page size. Which indicates that the scanning approach or the data itself is not correct.

**Comment by RaulGracia** [comment]
@abhinb has done a scan for valid footers on the chunks we collected from the impacted cluster for ` completedTransactionsBatch-24`:
```
index completedTransactionsBatch-24$attributes.index.E-9503-O-12734278854.bb40edc9-f7cf-4b28-81a2-db2ff26dee91
Maybe a valid footer starting at 12735976550 with footer length 82 at indexoffset 1697778
Maybe a valid footer starting at 12739454628 with footer length 82 at indexoffset 5175856
Maybe a valid footer starting at 12743019704 with footer length 82 at indexoffset 8740932
Maybe a valid footer starting at 12746547394 with footer length 82 at indexoffset 12268622
Maybe a valid footer starting at 12749957052 with footer length 82 at indexoffset 15678280
Maybe a valid footer starting at 12753298816 with footer length 82 at indexoffset 19020044
Maybe a valid footer starting at 12756906400 with footer length 82 at indexoffset 22627628
Maybe a valid footer starting at 12760477404 with footer length 82 at indexoffset 26198632
Maybe a valid footer starting at 12764069768 with footer length 82 at indexoffset 29790996
Maybe a valid footer starting at 12767625614 with footer length 82 at indexoffset 33346842
Last offset of this index is 12767833286



index completedTransactionsBatch-24$attributes.index.E-9503-O-12767833286.5793f919-338d-4dd1-9ea6-b2eb0e2bb883
Maybe a valid footer starting at 12771307050 with footer length 82 at indexoffset 3473846
Maybe a valid footer starting at 12774773646 with footer length 82 at indexoffset 6940442
Maybe a valid footer starting at 12778338608 with footer length 82 at indexoffset 10505404
Last offset of this index is 12801387718


index completedTransactionsBatch-24$attributes.index.E-9505-O-12778338702.03126410-9edf-4c1d-9f0c-0e8e95d91105
Maybe a valid footer starting at 12781803160 with footer length 82 at indexoffset 3464540
Maybe a valid footer starting at 12785192152 with footer length 82 at indexoffset 6853532
Maybe a valid footer starting at 12788866222 with footer length 82 at indexoffset 10527602
Maybe a valid footer starting at 12792337948 with footer length 82 at indexoffset 13999328
Maybe a valid footer starting at 12795938928 with footer length 82 at indexoffset 17600308
Maybe a valid footer starting at 12799464368 with footer length 82 at indexoffset 21125748
Maybe a valid footer starting at 12802983884 with footer length 82 at indexoffset 24645264
Maybe a valid footer starting at 12806495892 with footer length 82 at indexoffset 28157272
Maybe a valid footer starting at 12810169094 with footer length 82 at indexoffset 31830474
Last offset of this index is 12811893134

output:-
size of contents 33554432 for index completedTransactionsBatch-24$attributes.index.E-9505-O-12811893134.505f8c83-25ea-49ef-aff8-b27bb0ab8b4e
Footers:-
Maybe a valid footer starting at 12813613474 with footer length 82 at indexoffset 1720422
Maybe a valid footer starting at 12817209632 with footer length 82 at indexoffset 5316580
Maybe a valid footer starting at 12820699524 with footer length 82 at indexoffset 8806472
Maybe a valid footer starting at 12824365502 with footer length 82 at indexoffset 12472450
Maybe a valid footer starting at 12827753932 with footer length 82 at indexoffset 15860880
Maybe a valid footer starting at 12831248250 with footer length 82 at indexoffset 19355198
Maybe a valid footer starting at 12834799292 with footer length 82 at indexoffset 22906240
Maybe a valid footer starting at 12838412144 with footer length 82 at indexoffset 26519092
Maybe a valid footer starting at 12841877186 with footer length 82 at indexoffset 29984134
```
Also, he has been able to rescue some print of the storage metadata for this index segment, which demonstrates that all the chunks are valid for this segment (i.e., starting from `E-9503-O-12734278854` and ending at `E-9505-O-12811893134.505f8c83`). However, the last chunk either had garbage written at the end or there was some error related to rolling over these chunks (as its size is exactly 32MB, which is the default rollover size for attribute segment chanuks):
```
> table-segment get _system/containers/storage_metadata_32 _system/_tables/completedTransactionsBatch-24$attributes.index 10.129.1.137
For the given key: _system/_tables/completedTransactionsBatch-24$attributes.index
SLTS metadata info: 
key = _system/_tables/completedTransactionsBatch-24$attributes.index;
version = 1650870025368;
metadataType = SegmentMetadata;
name = _system/_tables/completedTransactionsBatch-24$attributes.index;
length = 12845447596;
chunkCount = 4;
startOffset = 12746801052;
status = 9;
maxRollingLength = 33554432;
firstChunk = _system/_tables/completedTransactionsBatch-24$attributes.index.E-9503-O-12734278854.bb40edc9-f7cf-4b28-81a2-db2ff26dee91;
lastChunk = _system/_tables/completedTransactionsBatch-24$attributes.index.E-9505-O-12811893134.505f8c83-25ea-49ef-aff8-b27bb0ab8b4e;
lastModified = 0;
firstChunkStartOffset = 12734278854;
lastChunkStartOffset = 12811893134;
ownerEpoch = 20163;
```

**Comment by andreipaduroiu** [comment]
Footer is 12 bytes in length. Why do you say it's 82 bytes?

https://github.com/pravega/pravega/blob/master/common_server/src/main/java/io/pravega/common/util/btree/BTreeIndex.java#L117

**Comment by RaulGracia** [comment]
@andreipaduroiu yes, I think this output actually means "root page length" (will change it for clarity).

**Comment by RaulGracia** [comment]
Looking more in depth to the storage metadata numbers and the actual data that we have, my understanding there are **30 bytes missing** in the last index chunk (which will probably contain the footer that is not there):
```
length = 12845447596;
chunkCount = 4;
startOffset = 12746801052;
status = 9;
maxRollingLength = 33554432;
firstChunk = _system/_tables/completedTransactionsBatch-24$attributes.index.E-9503-O-12734278854.bb40edc9-f7cf-4b28-81a2-db2ff26dee91;
lastChunk = _system/_tables/completedTransactionsBatch-24$attributes.index.E-9505-O-12811893134.505f8c83-25ea-49ef-aff8-b27bb0ab8b4e;
lastModified = 0;
firstChunkStartOffset = 12734278854;
lastChunkStartOffset = 12811893134;
```
That is, my understanding is that `lastChunkStartOffset (12811893134)` + `last chunk size (33554432)` = `length (12845447596)`. However, `12811893134 + 33554432 = 12845447566`, and `12845447566 - 12845447596 = -30`. These last 30 bytes missing seem to be the responsible for the problem we are seeing.

The question is: why have we ended up having 30 bytes less of data on that segment index chunk that the one that the storage metadata thinks we actually have? Shouldn't we have another chunk with these last 30 bytes as `lastChunk` in Storage Metadata? @sachin-j-joshi @andreipaduroiu @tkaitchuck 

Another observation: due to the usage of the Completed Transactions Batch Table Segment (i.e., just store the transaction id and the commit status of the transaction), all the BTreeIndex writes are similar in size (between 3.3MB and 3.7MB):
```
3478078
3565076
3527690
3409658
3341764
3607584
3571004
3592364
3555846
3388992
3674070
3471726
3600980
3525440
3519516
3512008
3673202
```
This has been calculated considering the bytes between consecutive footers in the index chunks. If we see the last footer offset, it is at offset `29984134` for that file, which is `33554432` in size. This means that the last write was `3570298` bytes in size, which is consistent with the history of all previous writes. This may mean that the last write was itself correct, but there are 30 bytes missing at the end for an unknown reason.

**Comment by sachin-j-joshi** [comment]
@abhinb @RaulGracia  As per our discussion earlier,

The original exception info is as below

`Wrong footer information. RootPage Offset (6805637576853986517) + Length (-1140654080) exceeds Footer Offset (12845447554)`


- footer was read at `12845447554` 
- which mean at that point the the segment length in metadata was `12 (footer size) +12845447554(footer offset ) = 12845447566  `
- This length is consistent with[ name and length of last chunk as found on LTS](https://github.com/pravega/pravega/issues/6712#issuecomment-1108672014) `completedTransactionsBatch-24$attributes.index.E-9505-O-12811893134.505f8c83-25ea-49ef-aff8-b27bb0ab8b4` with size of `33554432 (32MB)`
- 12811893134 (start of last chunk) + 33554432 (size of last chunk)= 12845447566  

So based on this, at the time of original exception there was no inconsistence between LTS and metadata and that header was indeed read correctly at the correct offset.



References 
1. How footer length is calculated

- https://github.com/pravega/pravega/blob/0205da84fabd82d94331d3d266a30a7f9b8619ba/common_server/src/main/java/io/pravega/common/util/btree/BTreeIndex.java#L210 
- https://github.com/pravega/pravega/blob/0205da84fabd82d94331d3d266a30a7f9b8619ba/common_server/src/main/java/io/pravega/common/util/btree/BTreeIndex.java#L883

2. The length is directly coming from metadata https://github.com/pravega/pravega/blob/0205da84fabd82d94331d3d266a30a7f9b8619ba/segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java#L715

**Comment by RaulGracia** [comment]
@sachin-j-joshi @andreipaduroiu @abhinb I have tried this test, that basically attempts 10K inserts into the cache after being full, and then checks the data that is in the cache. It works, meaning that irrespective of the insert attempts, whatever is in the cache (address, payloads) does not seem to be corrupted by the fact of keep trying appending to it once it is full:
```
@Test
    public void testOperationsWithCacheFull() {
        final byte[] data = new byte[LAYOUT.bufferSize() * 2];
        int failures = 10000;
        rnd.nextBytes(data);
        val entryData = new HashMap<Integer, Map.Entry<Integer, Integer>>(); // Key=Address, Value={Offset, Length}

        @Cleanup
        val c = new TestCache();

        // Insert until we can no longer insert.
        CacheState cs = c.getState();
        AtomicBoolean finish = new AtomicBoolean(false);

        while (!finish.get()) {
            int offset = rnd.nextInt(data.length - 1);
            int length = (int) Math.min(cs.getMaxBytes() - cs.getUsedBytes(), rnd.nextInt(data.length - offset));
            try {
                int address = c.insert(new ByteArraySegment(data, offset, length));
                entryData.put(address, new AbstractMap.SimpleEntry<>(offset, length));
            } catch (Exception e) {
                failures--;
                System.err.println(e);
                if (failures < 0) {
                    finish.set(true);
                }
            }
        }

        // Verify we've actually filled up the cache.
        AssertExtensions.assertThrows(
                "Cache not full.",
                () -> c.insert(new ByteArraySegment(data, 0, 1)),
                ex -> ex instanceof CacheFullException);

        // Read all the data
        checkData(c, entryData, data);
    }
```
In other words, we see many messages like:
```
io.pravega.segmentstore.storage.cache.CacheFullException: DirectMemoryCache full: Stored = 12521463, Used = 12582912, Reserved = 24576, Allocated = 12582912, Max = 12582912.
```
But the cache contents seem ok considering the entries that have been correctly stored.

In the logs of the original issue, we see the same exception for the impacted segment `476467211`:
```
2022-04-18 01:44:03,710 2139900397 [core-19] INFO  i.p.s.s.logs.OperationProcessor - OperationProcessor[32]: Completing and closing commitProcessor. Is OperationProcessor running? false
2022-04-18 01:44:03,710 2139900397 [core-2] WARN  i.p.s.s.a.SegmentAttributeBTreeIndex - AttributeIndex[32-476467211]: Cache update failed for offset 12746801052, length 18518 (existing entry=null). Cache full.
2022-04-18 01:44:03,710 2139900397 [core-19] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[32]: Stopped.
2022-04-18 01:44:03,710 2139900397 [core-30] WARN  i.p.s.server.logs.DurableLog - DurableLog[32]: QueueProcessor failed with exception {}
io.pravega.segmentstore.storage.cache.CacheFullException: DirectMemoryCache full: Stored = 8696246825, Used = 8765775872, Reserved = 23068672, Allocated = 11811160064, Max = 11811160064.
```

Despite for other Segments in the same container, we have other kind of errors related to cache being full:
```
2022-04-18 01:44:03,709 2139900396 [core-2] INFO  i.p.s.server.CacheManager - CacheManager: Cache full. Forcing cache policy.
2022-04-18 01:44:03,709 2139900396 [core-14] ERROR i.p.s.s.logs.OperationProcessor - OperationProcessor[32]: MemoryStateUpdater.process failure.
io.pravega.segmentstore.server.ServiceHaltException: Unable to add operation 'StreamSegmentAppendOperation: SequenceNumber = 490928687, SegmentId = 124563052, Offset = 1367352227979, Length = 26765, Attributes = 2' to ReadIndex.
	at io.pravega.segmentstore.server.logs.MemoryStateUpdater.addToReadIndex(MemoryStateUpdater.java:276)
...
Caused by: java.lang.IllegalArgumentException: The given range of bytes (Offset=1367352227979) does not start right after the last appended offset (1367352207692).
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:385)
```

@sachin-j-joshi unless the previous error somehow impacts on the cached entries for segment `476467211` (or maybe other segments), I don't know how the fact that `BTreeIndex` pages are cached and we use the last page offset/length to write the footer (https://github.com/pravega/pravega/blob/0205da84fabd82d94331d3d266a30a7f9b8619ba/common_server/src/main/java/io/pravega/common/util/btree/BTreeIndex.java#L852), may induce writing a corrupted footer.
