### ISSUE TITLE
Flaky test: PravegaTest system test failure with createScope failed exception

### ISSUE THREAD

**Issue by ShwethaSNayak** [pravega/pravega#6736]
**Problem description**

We could see that PravegaTest is failed due to createScope error from controller pod 
2022-05-11 01:39:34,390 84547 [grpc-nio-worker-ELG-1-1] WARN  i.p.c.control.impl.ControllerImpl - gRPC call for createScope with trace id -2466363358353903292 and parameters [testScopeSampleYFsGkO] failed with server error.
io.grpc.StatusRuntimeException: INTERNAL: get entry: key: testScopeSampleYFsGkO table: _system/deletingScopes
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)

**Comment by ShwethaSNayak** [comment]
Initial analysis:

**Controller Logs**: From controller logs we can see reason for failure is : "Could not find host for container id"

create scope call at 2022-05-11T01:38:11

`2022-05-11T01:38:11.667128414Z stdout F 2022-05-11 01:38:11,667 35471 [grpc-default-executor-0] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=-2466363358353903292] createScope called for scope testScopeSampleYFsGkO.`

After few retry throws error message 
```
2022-05-11T01:38:24.522291824Z stdout F io.pravega.controller.store.host.HostStoreException: Could not find host for container id: 1
2022-05-11T01:38:24.553170015Z stdout F io.pravega.controller.store.host.HostStoreException: Could not find host for container id: 3
2022-05-11T01:38:24.553173996Z stdout F 	at io.pravega.controller.store.host.ZKHostStore.getHostForContainer(ZKHostStore.java:139)
2022-05-11T01:38:24.553177188Z stdout F 	at io.pravega.controller.store.host.ZKHostStore.getHostForSegment(ZKHostStore.java:151)
2022-05-11T01:38:24.553180515Z stdout F 	at io.pravega.controller.server.SegmentHelper.getSegmentUri(SegmentHelper.java:150)
2022-05-11T01:38:24.553183737Z stdout F 	at io.pravega.controller.server.ControllerService.getURI(ControllerService.java:575)
2022-05-11T01:38:24.553187212Z stdout F 	at io.pravega.controller.server.eventProcessor.LocalController.getEndpointForSegment
```

And finally createSCope call failed with error message

```
2022-05-11T01:39:34.380944146Z stdout F 2022-05-11 01:39:34,378 118182 [controllerpool-68] ERROR i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=-2466363358353903292] Controller API call with tag createScope-testScopeSampleYFsGkO failed with error: 
2022-05-11T01:39:34.380948974Z stdout F io.pravega.controller.store.stream.StoreException$StoreConnectionException: get entry: key: testScopeSampleYFsGkO table: _system/deletingScopes
2022-05-11T01:39:34.380955552Z stdout F 	at io.pravega.controller.store.stream.StoreException.create(StoreException.java:115)

```
**Segment Store Logs**: At the time when createScope call is triggered looks like segment container are stopped .
from logs I can see at 2022-05-11T01:37:43 segment container stopped and it started again at 2022-05-11T01:43:38, so when createScope call is triggered as segment container is not up and running it failed.


Just before stopping container I could see below error messages in log `
2022-05-11T01:37:43.357560022Z stdout F 2022-05-11 01:37:43,357 5289588 [core-14] WARN  i.p.s.s.logs.OperationProcessor - OperationProcessor[0]: commitProcessor completed exceptionally java.util.concurrent.CompletionException: java.util.concurrent.CancellationException.`

post which I can see that all 3 SegmentContainer getting closed at 2022-05-11T01:37:43
```
2022-05-11T01:37:43.366986723Z stdout F 2022-05-11 01:37:43,366 5289597 [core-15] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[1]: Closed.
2022-05-11T01:37:43.366989865Z stdout F 2022-05-11 01:37:43,366 5289597 [core-15] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container 1 has been unregistered.

2022-05-11T01:37:43.387713548Z stdout F 2022-05-11 01:37:43,387 5289618 [core-16] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[3]: Closed.
2022-05-11T01:37:43.387753971Z stdout F 2022-05-11 01:37:43,387 5289618 [core-16] INFO  i.p.s.s.s.StreamSegmentContainerRegistry - Unregistered SegmentContainer 3.

2022-05-11T01:37:43.393069251Z stdout F 2022-05-11 01:37:43,392 5289623 [core-7] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[2]: Closed.
2022-05-11T01:37:43.393095806Z stdout F 2022-05-11 01:37:43,392 5289623 [core-7] INFO  i.p.s.s.s.StreamSegmentContainerRegistry - Unregistered SegmentContainer 2.

```
`And there is no logs available from 2022-05-11T01:38:10 to 2022-05-11T01:43:38`

I can segmentContainer getting started 2022-05-11T01:43:38

```
2022-05-11T01:43:38.559344427Z stdout F 2022-05-11 01:43:38,559 13277 [core-28] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[1]: Started.
2022-05-11T01:43:38.992179546Z stdout F 2022-05-11 01:43:38,992 13710 [core-11] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[2]: Started
2022-05-11T01:43:40.45347786Z stdout F 2022-05-11 01:43:40,453 15171 [core-7] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[3]: Started.
```
