### ISSUE TITLE
Regressions detected with Fault Injection testing in Bookkeeper 4.15

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#6806]
**Describe the bug**
After serveral iterations of failure injection testing (i.e., pod/node restarts, network packet loss), we found a consistent behavior:
- Pravega 0.11 and Pravega 0.12 using Bookkeeper 4.14 branch pass all the test consistently (in terms of data unavailability/loss).
- Pravega 0.12 using Bookkeeper 4.15 (wither only in the client or both in the client and server) frequently shows failures related to ledgers being lost. 

As all the code from other components (Pravega, Zookeeper) as well as the tests are the same, this may be a regression related to the new Bookkeeper 4.15 release, so we need to revert Pravega 0.12 back to Bookkeeper 4.14 for safety reasons.

**To Reproduce**
1. Run IO workload in Pravega
2. Induce 30% packet loss in the cluster
3. You will likely hit an issue like the one below, showing that there are missing ledgers in containers:

```
2022-07-12 13:48:31,332 40324396 [BookKeeperClientWorker-OrderedExecutor-7-0] ERROR o.a.bookkeeper.client.PendingReadOp - Read of ledger entry failed: L200223 E0-E35, Sent to [bookkeeper-bookie-1-19483, bookkeeper-bookie-2-26033], Heard from [] : bitset = {}, Error = 'No such ledger exists on Bookies'. First unread entry is (1, rc = 0)
...
2022-07-12 13:48:31,344 40324408 [core-11] ERROR i.p.s.server.logs.DurableLog - DurableLog[10] Recovery FAILED.
org.apache.bookkeeper.client.BKException$BKNoSuchLedgerExistsException: No such ledger exists on Bookies
	at org.apache.bookkeeper.client.BKException.create(BKException.java:74)

2022-07-12 13:48:31,213 40324277 [BookKeeperClientWorker-OrderedExecutor-2-0] ERROR o.a.bookkeeper.client.PendingReadOp - Read of ledger entry failed: L199701 E0-E6, Sent to [bookkeeper-bookie-2-26033, bookkeeper-bookie-0-25905], Heard from [] : bitset = {}, Error = 'No such ledger exists on Bookies'. First unread entry is (1, rc = 0)
...
2022-07-12 13:48:31,215 40324279 [core-10] ERROR i.p.s.server.logs.DurableLog - DurableLog[32] Recovery FAILED.
org.apache.bookkeeper.client.BKException$BKNoSuchLedgerExistsException: No such ledger exists on Bookies
	at org.apache.bookkeeper.client.BKException.create(BKException.java:74)
```

**Screenshots**
n/a

**Additional information**
We need to collect `DEBUG` level logs about this issue and share it with the Bookkeeper community, as it seems a serious data loss problem from our point of view. cc/ @eolivelli

**Comment by RaulGracia** [comment]
Closed via #6807.
