### ISSUE TITLE
Failure in system test for io.pravega.test.system.LargeEventTest.largeEventSimpleTest

### ISSUE THREAD

**Issue by ShwethaSNayak** [pravega/pravega#6924]
**Problem description**

java.lang.AssertionError: largeEventSimpleTest test failed due to Error with message null
	at io.pravega.test.system.framework.services.kubernetes.K8SequentialExecutor.lambda$startTestExecution$4(K8SequentialExecutor.java:94)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)

**Problem location**

System test : https://osj-ntl-01-prd.cec.lab.emc.com/view/Pravega/job/pravega-system-tests/103/testReport/junit/io.pravega.test.system/LargeEventTest/largeEventSimpleTest/

**Suggestions for an improvement**

**Comment by RaulGracia** [comment]
I have been debugging this issue and added logs to better understand what is going on. At the moment, it looks like the test fails because the `LargeEventWriter` used in the test gets blocked sometimes at this point: https://github.com/pravega/pravega/blob/9215909970de8cb0be2497fa3714ac7ff7874c2f/client/src/main/java/io/pravega/client/stream/impl/LargeEventWriter.java#L187

That is, the payload is split into the appropriate 8MB appends to the transient Segment, but one or more of these append futures seems to never complete. This leaves the `LargeEventWriter` blocked and therefore the test fails due to `TimeoutException`:
```
2022-11-16T16:28:56.56057617Z stdout F 2022-11-16 16:28:56,560 500468 [Time-limited test] INFO  i.pravega.client.stream.impl.Pinger - Closing Pinger periodic task
2022-11-16T16:28:56.561581462Z stdout F 2022-11-16 16:28:56,561 500469 [Time-limited test] INFO  i.p.c.c.impl.ConnectionPoolImpl - Shutting down connection pool
2022-11-16T16:28:56.561615609Z stdout F 2022-11-16 16:28:56,561 500469 [ClientSocketReaders-35] INFO  i.p.c.c.impl.TcpClientConnection - Closing TcpConnection.Reader because socket is closed.
2022-11-16T16:28:56.561708969Z stdout F 2022-11-16 16:28:56,561 500469 [Time-limited test] INFO  i.p.c.c.i.SocketConnectionFactoryImpl - Shutting down connection factory
2022-11-16T16:28:56.564049102Z stdout F 2022-11-16 16:28:56,563 500471 [main] WARN  i.p.t.s.f.TestFrameworkException - TestFramework Exception. Type: InternalError, Details: Exception while running test method: largeEventSimpleTest
2022-11-16T16:28:56.564081181Z stdout F org.junit.runners.model.TestTimedOutException: test timed out after 500 seconds
```

Next step is to understand why sometimes of these 8MB append futures never completes (and also does not timeout with an error).
