### ISSUE TITLE
PravegaTablesStreamMetadataStoreTest testDeleteScopeRecursive is flakey

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#7098]
io.pravega.controller.store.stream.PravegaTablesStreamMetadataStoreTest.testDeleteScopeRecursive 
Sometimes fails with the following output:

 > 2023-05-29 04:52:02,952 75549 [Test worker] DEBUG o.a.c.f.imps.WatcherRemovalManager - Removing watcher for path: /garbagecollection/completedTxnGC/guard
 > 2023-05-29 04:52:03,101 69520 [test-4] ERROR i.p.c.t.Stream.StreamMetadataTasks - [requestId=123] Exception deleting scope scope. Cause: {}
 > java.util.concurrent.CompletionException: org.apache.commons.lang3.NotImplementedException: GetScopeId not implemented for ZK scope
 > 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
 > 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
 > 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1063)
 > 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
 > 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
 > 	at io.pravega.common.concurrent.Futures.lambda$completeOn$0(Futures.java:68)
 > 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
 > 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
 > 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
 > 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 > 	at io.pravega.common.concurrent.ThreadPoolScheduledExecutorService$ScheduledRunnable.run(ThreadPoolScheduledExecutorService.java:197)
 > 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 > 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 > 	at java.base/java.lang.Thread.run(Thread.java:829)
 > Caused by: org.apache.commons.lang3.NotImplementedException: GetScopeId not implemented for ZK scope
 > 	at io.pravega.controller.store.ZKScope.getScopeId(ZKScope.java:382)
 > 	at io.pravega.controller.store.stream.AbstractStreamMetadataStore.getScopeId(AbstractStreamMetadataStore.java:1150)
 > 	at io.pravega.controller.store.stream.ZKStreamMetadataStore$MockitoMock$1317259794.getScopeId$accessor$F93Q7py9(Unknown Source)
 > 	at io.pravega.controller.store.stream.ZKStreamMetadataStore$MockitoMock$1317259794$auxiliary$HXLWxHxc.call(Unknown Source)
 > 	at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
 > 	at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
 > 	at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:152)
 > 	at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:44)
 > 	at org.mockito.Answers.answer(Answers.java:100)
 > 	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
 > 	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
 > 	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:33)
 > 	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:61)
 > 	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49)
 > 	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:108)
 > 	at io.pravega.controller.store.stream.ZKStreamMetadataStore$MockitoMock$1317259794.getScopeId(Unknown Source)
 > 	at io.pravega.controller.task.Stream.StreamMetadataTasks.lambda$deleteScopeRecursive$76(StreamMetadataTasks.java:750)
 > 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
 > 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
 > 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
 > 	at io.pravega.controller.store.ZKStoreHelper.lambda$checkExists$27(ZKStoreHelper.java:397)
 > 	at io.pravega.controller.store.ZKStoreHelper.lambda$callback$29(ZKStoreHelper.java:416)
 > 	at org.apache.curator.framework.imps.Backgrounding$1$1.run(Backgrounding.java:158)
 > 	... 5 common frames omitted
 > 2023-05-29 04:52:03,108 69527 [Test worker] DEBUG o.a.c.f.imps.WatcherRemovalManager - Removing watcher for path: /garbagecollection/completedTxnGC/guard
 > 2023-05-29 04:52:03,108 69527 [Test worker] DEBUG o.a.c.f.imps.CuratorFrameworkImpl - Closing
 > 2023-05-29 04:52:03,108 69527 [Curator-Framework-0] INFO  o.a.c.f.imps.CuratorFrameworkImpl - backgroundOperationsLoop exiting
 > 2023-05-29 04:52:03,108 69527 [Test worker] DEBUG o.a.c.f.imps.WatcherRemovalManager - Removing watcher for path: /zookeeper/config
 > 2023-05-29 04:52:03,108 69527 [Test worker] DEBUG o.a.curator.CuratorZookeeperClient - Closing, waitForShutdownTimeoutMs 0
 > 2023-05-29 04:52:03,108 69527 [Test worker] DEBUG org.apache.curator.ConnectionState - Closing
 > 2023-05-29 04:52:03,112 69531 [Test worker-SendThread(127.0.0.1:46739)] WARN  org.apache.zookeeper.ClientCnxn - An exception was thrown while closing send thread for session 0x1000006a0ae0000.
 > org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x1000006a0ae0000, likely server has closed socket
 > 	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
 > 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
 > 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
```
io.pravega.controller.store.stream.PravegaTablesStreamMetadataStoreTest > testDeleteScopeRecursive FAILED
    java.util.concurrent.CompletionException: java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$DataNotEmptyException: delete table: _system/_tables/testDeleteScopeRec/streamsInScope.#.ea9274a8-c2ef-4a27-99a6-4e736b0e1e98
        at io.pravega.common.concurrent.Futures.lambda$exceptionallyExpecting$10(Futures.java:401)
        at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
        at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
        at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$runAsync$6(Retry.java:255)
        at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
        at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at io.pravega.common.concurrent.ThreadPoolScheduledExecutorService$ScheduledRunnable.run(ThreadPoolScheduledExecutorService.java:197)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

        Caused by:
        java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$DataNotEmptyException: delete table: _system/_tables/testDeleteScopeRec/streamsInScope.#.ea9274a8-c2ef-4a27-99a6-4e736b0e1e98
            at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$withRetries$75(PravegaTablesStoreHelper.java:831)
            ... 14 more

            Caused by:
            io.pravega.controller.store.stream.StoreException$DataNotEmptyException: delete table: _system/_tables/testDeleteScopeRec/streamsInScope.#.ea9274a8-c2ef-4a27-99a6-4e736b0e1e98
                at io.pravega.controller.store.stream.StoreException.create(StoreException.java:103)
                at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$exceptionalCallback$72(PravegaTablesStoreHelper.java:779)
                ... 9 more

                Caused by:
                io.pravega.controller.server.WireCommandFailedException: WireCommandFailed with type DELETE_TABLE_SEGMENT reason TableSegmentNotEmpty
                    at io.pravega.controller.mocks.SegmentHelperMock.lambda$getSegmentHelperMockForTables$4(SegmentHelperMock.java:179)
                    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
                    ... 5 more
```
For an example see: https://github.com/pravega/pravega/actions/runs/5108570519/jobs/9182515631

**Comment by tkaitchuck** [comment]
Also https://github.com/pravega/pravega/actions/runs/7802577445/job/21280500027
