### ISSUE TITLE
TimeoutServiceTest fails frequently

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#716]
**Problem description**
TimeoutServiceTest is time dependent and frequently fails.

**Problem location**
TimeoutServiceTest

**Suggestions for an improvement**
Use an injected clock so the test is not time dependent.

**Comment by Abhijeet-Jadhav** [comment]
Observed this, causing local build failure: 
```
io.pravega.controller.timeout.TimeoutServiceTest > testUnknownTxnPingSuccess FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertNotNull(Assert.java:712)
        at org.junit.Assert.assertNotNull(Assert.java:722)
        at io.pravega.controller.timeout.TimeoutServiceTest.testUnknownTxnPingSuccess(TimeoutServiceTest.java:496)
```

**Comment by Abhijeet-Jadhav** [comment]
Filed https://github.com/pravega/pravega/issues/1455 for the above specific failure.

**Comment by Abhijeet-Jadhav** [comment]
Observed this, causing local build failure:

```
io.pravega.controller.timeout.TimeoutServiceTest > testTimeout FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertNotNull(Assert.java:712)
        at org.junit.Assert.assertNotNull(Assert.java:722)
        at io.pravega.controller.timeout.TimeoutServiceTest.testTimeout(TimeoutServiceTest.java:150)
```

**Comment by shiveshr** [comment]
havent observed this in recent times. closing this.
