### ISSUE TITLE
Flakey test: DataRecoveryTest > testDurableLogInspectCommandException

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#7253]
```
io.pravega.cli.admin.dataRecovery.DataRecoveryTest > testDurableLogInspectCommandException FAILED
    io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to establish connection to ZooKeeper or BookKeeper.
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogFactory.initialize(BookKeeperLogFactory.java:105)
        at io.pravega.cli.admin.dataRecovery.DataRecoveryTest.testDurableLogInspectCommandException(DataRecoveryTest.java:1625)

        Caused by:
        java.io.IOException: Failed to initialize metadata client driver
            at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:464)
            at org.apache.bookkeeper.client.BookKeeper$Builder.build(BookKeeper.java:307)
            at org.apache.bookkeeper.client.impl.BookKeeperBuilderImpl.build(BookKeeperBuilderImpl.java:86)
            at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogFactory.startBookKeeperClient(BookKeeperLogFactory.java:184)
            at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogFactory.initialize(BookKeeperLogFactory.java:93)
            ... 1 more

            Caused by:
            org.apache.bookkeeper.meta.exceptions.MetadataException: Failed to create zookeeper client to localhost:8904
                at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.initialize(ZKMetadataDriverBase.java:236)
                at org.apache.bookkeeper.meta.zk.ZKMetadataClientDriver.initialize(ZKMetadataClientDriver.java:63)
                at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:454)
                ... 5 more

                Caused by:
                org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
                    at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
                    at org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase.waitForConnection(ZooKeeperWatcherBase.java:159)
                    at org.apache.bookkeeper.zookeeper.ZooKeeperClient$Builder.build(ZooKeeperClient.java:260)
                    at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.initialize(ZKMetadataDriverBase.java:216)
                    ... 7 more
```

**Comment by tkaitchuck** [comment]
https://github.com/pravega/pravega/actions/runs/6153432763/job/16697365931?pr=7230
