### ISSUE TITLE
FlakeyTest: FileSystemIntegrationTest > testEndToEndWithChunkedStorage 

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#7254]
```
io.pravega.segmentstore.server.host.FileSystemIntegrationTest > testEndToEndWithChunkedStorage FAILED
    java.lang.AssertionError
        at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.getSingleReadResultEntry(StreamSegmentReadIndex.java:991)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.getMultiReadResultEntry(StreamSegmentReadIndex.java:1024)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadResult.next(StreamSegmentReadResult.java:208)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadResult.next(StreamSegmentReadResult.java:32)
        at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.checkSegmentReads(StreamSegmentStoreTestBase.java:874)
        at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.lambda$checkReads$14(StreamSegmentStoreTestBase.java:858)
        at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:194)
        at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.checkReads(StreamSegmentStoreTestBase.java:855)
        at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.endToEndProcess(StreamSegmentStoreTestBase.java:358)
        at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.testEndToEndWithChunkedStorage(StreamSegmentStoreTestBase.java:276)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by tkaitchuck** [comment]
https://github.com/pravega/pravega/actions/runs/6153432763/job/16697366066?pr=7230
