### ISSUE TITLE
Flaky test StorageLoaderTest.testSlowModeWithInMemoryStorage 

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#7327]
**Describe the bug**
This test is making our builds to fail quite often:
```
io.pravega.segmentstore.server.host.StorageLoaderTest.testSlowModeWithInMemoryStorage FAILED. Output (Last 300 lines):
 > 2023-11-24 08:18:56,959 186185 [Test worker] WARN  i.p.s.s.h.s.TLSConfigChangeEventConsumer - Invoked for null watchEvent
 > 2023-11-24 08:18:56,959 186185 [Test worker] INFO  i.p.s.s.h.s.TLSConfigChangeHandler - Current reload count = 1
 > 2023-11-24 08:19:14,871 190192 [Time-limited test] WARN  i.p.c.c.ExecutorServiceHelpers - One or more threads from pool ThreadPoolScheduledExecutorService(runner=java.util.concurrent.ThreadPoolExecutor@58347e4d[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 62]) did not shutdown properly. Waiting tasks: []
 > 2023-11-24 08:19:14,872 190193 [Time-limited test] WARN  i.p.c.c.ExecutorServiceFactory - Created Thread Pool 'core' with leak detection level set to 'Aggressive'. THE VM WILL BE HALTED IF A LEAK IS DETECTED. DO NOT USE IN PRODUCTION.
 > 2023-11-24 08:19:14,878 190199 [Time-limited test] WARN  i.p.c.c.ExecutorServiceFactory - Created Thread Pool 'storage-io' with leak detection level set to 'Aggressive'. THE VM WILL BE HALTED IF A LEAK IS DETECTED. DO NOT USE IN PRODUCTION.
 > 2023-11-24 08:19:14,894 190215 [Time-limited test] WARN  i.p.c.c.ExecutorServiceFactory - Created Thread Pool 'low-priority-cleanup' with leak detection level set to 'Aggressive'. THE VM WILL BE HALTED IF A LEAK IS DETECTED. DO NOT USE IN PRODUCTION.
 > 2023-11-24 08:19:14,898 190219 [Time-limited test] INFO  i.p.s.server.host.StorageLoader - Loading INMEMORY, trying StorageFactoryInfo(name=FILESYSTEM, storageLayoutType=CHUNKED_STORAGE)
 > 2023-11-24 08:19:14,899 190220 [Time-limited test] INFO  i.p.s.server.host.StorageLoader - Loading INMEMORY, trying StorageFactoryInfo(name=HDFS, storageLayoutType=CHUNKED_STORAGE)
 > 2023-11-24 08:19:14,899 190220 [Time-limited test] INFO  i.p.s.server.host.StorageLoader - Loading INMEMORY, trying StorageFactoryInfo(name=EXTENDEDS3, storageLayoutType=CHUNKED_STORAGE)
 > 2023-11-24 08:19:14,899 190220 [Time-limited test] INFO  i.p.s.server.host.StorageLoader - Loading INMEMORY, trying StorageFactoryInfo(name=S3, storageLayoutType=CHUNKED_STORAGE)
 > 2023-11-24 08:19:14,899 190220 [Time-limited test] INFO  i.p.s.server.host.StorageLoader - Loading INMEMORY, trying StorageFactoryInfo(name=GCP, storageLayoutType=CHUNKED_STORAGE)
 > 2023-11-24 08:19:14,899 190220 [Time-limited test] INFO  i.p.s.server.host.StorageLoader - Loading INMEMORY, trying StorageFactoryInfo(name=AZURE, storageLayoutType=CHUNKED_STORAGE)
 > 2023-11-24 08:19:14,900 190221 [Time-limited test] INFO  i.p.s.server.host.StorageLoader - Loading INMEMORY, trying StorageFactoryInfo(name=INMEMORY, storageLayoutType=CHUNKED_STORAGE)
 > 2023-11-24 08:19:14,900 190221 [Time-limited test] INFO  i.p.s.server.CacheManager - CacheManager Registered io.pravega.segmentstore.server.tables.ContainerKeyCache@47a81781.
 > 2023-11-24 08:19:14,901 190222 [Time-limited test] INFO  i.p.c.concurrent.DelayedProcessor - TableCompactor[0]: Started. Iteration Delay = 30000 ms.
 > 2023-11-24 08:19:14,905 190226 [Time-limited test] INFO  i.p.s.s.s.StreamSegmentContainerRegistry - Registered SegmentContainer 0.
 > 2023-11-24 08:19:14,905 190226 [Time-limited test] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Starting.
 > 2023-11-24 08:19:14,906 190227 [Time-limited test] INFO  i.p.s.server.logs.DurableLog - DurableLog[0]: Starting.
 > 2023-11-24 08:19:14,906 190227 [core-5] INFO  i.p.s.server.logs.RecoveryProcessor - RecoveryProcessor[0] Recovery started.
 > 2023-11-24 08:19:14,906 190227 [core-5] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[0]: Enter RecoveryMode.
 > 2023-11-24 08:19:14,906 190227 [core-5] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[0]: Reset.
 > 2023-11-24 08:19:14,906 190227 [core-5] INFO  i.p.s.s.reading.ContainerReadIndex - ReadIndex[0] Enter RecoveryMode.
 > 2023-11-24 08:19:14,906 190227 [core-5] INFO  i.p.s.s.reading.ContainerReadIndex - ReadIndex[0]: Cleared.
 > 2023-11-24 08:19:14,906 190227 [core-5] WARN  i.p.s.server.logs.RecoveryProcessor - RecoveryProcessor[0]: Reached the end of the DataFrameLog and could not find any MetadataCheckpointOperations after reading 0 Operations and 0 Data Frames.
 > 2023-11-24 08:19:14,906 190227 [core-5] INFO  i.p.s.server.logs.RecoveryProcessor - RecoveryProcessor[0] Recovery completed. Epoch = 1, Items Recovered = 0, Time = 0ms.
 > 2023-11-24 08:19:14,906 190227 [core-5] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[0]: Exit RecoveryMode.
 > 2023-11-24 08:19:14,906 190227 [core-5] INFO  i.p.s.s.reading.ContainerReadIndex - ReadIndex[0] Exit RecoveryMode.
 > 2023-11-24 08:19:14,906 190227 [core-5] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[0]: Started.
 > 2023-11-24 08:19:14,909 190230 [core-5] INFO  i.p.s.server.logs.DurableLog - DurableLog[0]: MetadataCheckpointOperation(1) stored.
 > 2023-11-24 08:19:14,909 190230 [core-5] INFO  i.p.s.server.logs.DurableLog - DurableLog[0]: Started (Online).
 > 2023-11-24 08:19:14,910 190231 [core-12] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: RecoverFromStorage mode is false 
 > 2023-11-24 08:19:14,910 190231 [core-9] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Initializing storage with epoch 1
 > 2023-11-24 08:19:14,910 190231 [core-9] INFO  i.p.s.s.chunklayer.SystemJournal - SystemJournal[0] BOOT started.
 > 2023-11-24 08:19:14,910 190231 [core-9] INFO  i.p.s.s.chunklayer.SystemJournal - SystemJournal[0] reading snapshot info from store.
 > 2023-11-24 08:19:14,910 190231 [test-1] INFO  i.p.s.s.chunklayer.SystemJournal - SystemJournal[0] Read Snapshot info from store. Info = null
 > 2023-11-24 08:19:14,910 190231 [test-1] INFO  i.p.s.s.chunklayer.SystemJournal - Chunk containing SnapshotInfo does not exist. This is ok if this is new installation. Chunk name = _system/containers/_sysjournal.container0.snapshot_info
 > 2023-11-24 08:19:14,910 190231 [test-1] INFO  i.p.s.s.chunklayer.SystemJournal - SystemJournal[0] No Snapshot info available from storage. This is ok if this is new installation
 > 2023-11-24 08:19:14,910 190231 [test-1] INFO  i.p.s.s.chunklayer.SystemJournal - SystemJournal[0] No Snapshot info available. This is ok if this is new installation
 > 2023-11-24 08:19:14,915 190236 [test-1] INFO  i.p.s.s.chunklayer.SystemJournal - SystemJournal[0] BOOT complete - applied 0 records in 10 journals. Total time = 4 ms.
 > 2023-11-24 08:19:14,915 190236 [core-14] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: RecoverFromStorage mode is false 
 > 2023-11-24 08:19:14,915 190236 [core-14] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Initializing Metadata Store.
 > 2023-11-24 08:19:14,917 190238 [core-14] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[0]: MapStreamSegment SegmentId = 1, Name = '_system/containers/metadata_0', Active = 1
 > 2023-11-24 08:19:14,917 190238 [core-14] INFO  i.p.s.s.c.TableMetadataStore - MetadataStore[0]: Metadata Segment pinned. Name = '_system/containers/metadata_0', Id = '1'
 > 2023-11-24 08:19:14,918 190239 [core-17] INFO  i.p.s.s.m.LocalSegmentContainerManager - Container 0 has been registered.
 > 2023-11-24 08:19:14,918 190239 [Time-limited test] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Stopping.
 > 2023-11-24 08:19:14,918 190239 [Time-limited test] INFO  i.p.s.server.logs.DurableLog - DurableLog[0]: Stopping.
 > 2023-11-24 08:19:14,919 190240 [core-14] WARN  i.p.s.s.logs.OperationProcessor - OperationProcessor[0]: Unexpected exception in OperationProcessor while processing items for commitProcessor, rethrowing.
 > java.util.concurrent.CancellationException: null
 > 	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2402)
 > 	at io.pravega.common.util.AbstractDrainingQueue.cancelPendingTake(AbstractDrainingQueue.java:94)
 > 	at io.pravega.segmentstore.server.logs.OperationProcessor.closeQueue(OperationProcessor.java:461)
 > 	at io.pravega.segmentstore.server.logs.OperationProcessor.doStop(OperationProcessor.java:199)
 > 	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:285)
 > 	at io.pravega.common.concurrent.Services.stopAsync(Services.java:67)
 > 	at io.pravega.segmentstore.server.logs.DurableLog.doStop(DurableLog.java:257)
 > 	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:285)
 > 	at io.pravega.common.concurrent.Services.stopAsync(Services.java:67)
 > 	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.doStop(StreamSegmentContainer.java:531)
 > 	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.doStop(StreamSegmentContainer.java:513)
 > 	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:285)
 > 	at io.pravega.common.concurrent.Services.stopAsync(Services.java:67)
 > 	at io.pravega.segmentstore.server.store.StreamSegmentContainerRegistry.stopContainer(StreamSegmentContainerRegistry.java:156)
 > 	at io.pravega.segmentstore.server.mocks.LocalSegmentContainerManager.close(LocalSegmentContainerManager.java:95)
 > 	at io.pravega.segmentstore.server.store.ServiceBuilder.closeComponent(ServiceBuilder.java:347)
 > 	at io.pravega.segmentstore.server.store.ServiceBuilder.close(ServiceBuilder.java:156)
 > 	at io.pravega.segmentstore.server.host.StorageLoaderTest.testSlowModeWithInMemoryStorage(StorageLoaderTest.java:247)
 > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 > 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 > 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
 > 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 > 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
 > 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 > 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
 > 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
 > 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 > 	at java.base/java.lang.Thread.run(Thread.java:829)
 > 2023-11-24 08:19:14,919 190240 [core-14] INFO  i.p.s.s.logs.OperationProcessor - OperationProcessor[0]: Completing and closing commitProcessor. OperationProcessor running? false, queueProcessor running? false.
 > 2023-11-24 08:19:14,919 190240 [core-14] WARN  i.p.s.s.logs.OperationProcessor - OperationProcessor[0]: commitProcessor completed exceptionally java.util.concurrent.CompletionException: java.util.concurrent.CancellationException.
 > 2023-11-24 08:19:14,920 190241 [core-18] WARN  i.p.s.s.logs.OperationProcessor - OperationProcessor[0]: Unexpected exception in OperationProcessor while processing items for queueProcessor, rethrowing.
 > java.util.concurrent.CompletionException: java.util.concurrent.CancellationException
 > 	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
 > 	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
 > 	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
 > 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
 > 	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2404)
 > 	at io.pravega.common.util.AbstractDrainingQueue.close(AbstractDrainingQueue.java:76)
 > 	at io.pravega.segmentstore.server.logs.OperationProcessor.closeQueue(OperationProcessor.java:451)
 > 	at io.pravega.segmentstore.server.logs.OperationProcessor.doStop(OperationProcessor.java:199)
 > 	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:285)
 > 	at io.pravega.common.concurrent.Services.stopAsync(Services.java:67)
 > 	at io.pravega.segmentstore.server.logs.DurableLog.doStop(DurableLog.java:257)
 > 	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:285)
 > 	at io.pravega.common.concurrent.Services.stopAsync(Services.java:67)
 > 	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.doStop(StreamSegmentContainer.java:531)
 > 	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.doStop(StreamSegmentContainer.java:513)
 > 	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:285)
 > 	at io.pravega.common.concurrent.Services.stopAsync(Services.java:67)
 > 	at io.pravega.segmentstore.server.store.StreamSegmentContainerRegistry.stopContainer(StreamSegmentContainerRegistry.java:156)
 > 	at io.pravega.segmentstore.server.mocks.LocalSegmentContainerManager.close(LocalSegmentContainerManager.java:95)
 > 	at io.pravega.segmentstore.server.store.ServiceBuilder.closeComponent(ServiceBuilder.java:347)
 > 	at io.pravega.segmentstore.server.store.ServiceBuilder.close(ServiceBuilder.java:156)
 > 	at io.pravega.segmentstore.server.host.StorageLoaderTest.testSlowModeWithInMemoryStorage(StorageLoaderTest.java:247)
 > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 > 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 > 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
 > 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 > 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
 > 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 > 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
 > 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
 > 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 > 	at java.base/java.lang.Thread.run(Thread.java:829)
 > Caused by: java.util.concurrent.CancellationException: null
 > 	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2402)
 > 	... 29 common frames omitted
 > 2023-11-24 08:19:14,920 190241 [core-18] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: RecoverFromStorage mode is false 
 > 2023-11-24 08:19:14,920 190241 [core-18] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Not recovering from storage. No need to adjust lengths
 > 2023-11-24 08:19:14,920 190241 [core-18] WARN  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Ignoring delayed start error due to Segment Container shutting down.
 > java.util.concurrent.CompletionException: io.pravega.segmentstore.server.IllegalContainerStateException: Container 0 is in an invalid state for this operation. Expected: RUNNING; Actual: STOPPING.
 > 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
 > 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
 > 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1081)
 > 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
 > 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 > 	at io.pravega.common.concurrent.ThreadPoolScheduledExecutorService$ScheduledRunnable.run(ThreadPoolScheduledExecutorService.java:197)
 > 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 > 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 > 	at java.base/java.lang.Thread.run(Thread.java:829)
 > Caused by: io.pravega.segmentstore.server.IllegalContainerStateException: Container 0 is in an invalid state for this operation. Expected: RUNNING; Actual: STOPPING.
 > 	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.ensureRunning(StreamSegmentContainer.java:1219)
 > 	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.createStreamSegment(StreamSegmentContainer.java:670)
 > 	at io.pravega.segmentstore.server.containers.ContainerEventProcessorImpl.tryCreateAndPinInternalSegment(ContainerEventProcessorImpl.java:151)
 > 	at io.pravega.segmentstore.server.containers.ContainerEventProcessorImpl.lambda$getOrCreateInternalSegment$1(ContainerEventProcessorImpl.java:138)
 > 	at io.pravega.segmentstore.server.containers.ContainerEventProcessorImpl.createEventProcessor(ContainerEventProcessorImpl.java:254)
 > 	at io.pravega.segmentstore.server.containers.ContainerEventProcessorImpl.forConsumer(ContainerEventProcessorImpl.java:216)
 > 	at io.pravega.segmentstore.server.containers.StorageEventProcessor.addQueue(StorageEventProcessor.java:90)
 > 	at io.pravega.segmentstore.storage.chunklayer.GarbageCollector.initialize(GarbageCollector.java:185)
 > 	at io.pravega.segmentstore.storage.chunklayer.ChunkedSegmentStorage.finishBootstrap(ChunkedSegmentStorage.java:232)
 > 	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.lambda$startWhenDurableLogOnline$10(StreamSegmentContainer.java:365)
 > 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
 > 	... 6 common frames omitted
 > 2023-11-24 08:19:14,921 190242 [Time-limited test] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[0]: Stopping.
 > 2023-11-24 08:19:14,921 190242 [Time-limited test] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[0]: Stopped.
 > 2023-11-24 08:19:14,922 190243 [core-19] INFO  i.p.s.server.logs.DurableLog - DurableLog[0]: Stopped.
 > 2023-11-24 08:19:14,922 190243 [core-19] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Stopped.
 > 2023-11-24 08:19:14,922 190243 [core-19] INFO  i.p.s.server.CacheManager - CacheManager Unregistered io.pravega.segmentstore.server.tables.ContainerKeyCache@47a81781.
 > 2023-11-24 08:19:14,922 190243 [core-19] INFO  i.p.s.s.tables.ContainerKeyIndex - KeyIndex[0]: Closed.
 > 2023-11-24 08:19:14,922 190243 [core-19] INFO  i.p.c.concurrent.DelayedProcessor - TableCompactor[0]: Closed.
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.s.s.t.FixedKeyLengthTableSegmentLayout - TableExtension[0]: Closed.
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.s.s.t.ContainerTableExtensionImpl - TableExtension[0]: Closed.
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[0]: Closed.
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.c.c.AbstractThreadPoolService - StorageWriter[0]: Closed.
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[0]: Closed.
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.s.server.logs.DurableLog - DurableLog[0]: Closed.
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.s.s.reading.ContainerReadIndex - ReadIndex[0]: Closed.
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.s.s.a.ContainerAttributeIndexImpl - ContainerAttributeIndex[0]: Closed.
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.s.s.c.ChunkedSegmentStorage - ChunkedSegmentStorage[0] Closed metadataStore
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.s.s.c.ChunkedSegmentStorage - ChunkedSegmentStorage[0] Closed garbageCollector
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.s.s.c.ChunkedSegmentStorage - ChunkedSegmentStorage[0] Closed taskQueue
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.s.s.c.ChunkedSegmentStorage - ChunkedSegmentStorage[0] Closed chunkStorage
 > 2023-11-24 08:19:14,923 190244 [Time-limited test] INFO  i.p.s.server.CacheManager - CacheManager Closed.
 > 2023-11-24 08:19:14,924 190245 [core-19] INFO  i.p.s.s.c.ContainerEventProcessorImpl - ContainerEventProcessor[0]: Closing ContainerEventProcessor service.

io.pravega.segmentstore.server.host.StorageLoaderTest > testSlowModeWithInMemoryStorage FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
        at java.base@11.0.21/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@11.0.21/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
        at java.base@11.0.21/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
        at java.base@11.0.21/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1454)
        at app//io.pravega.common.concurrent.ThreadPoolScheduledExecutorService.awaitTermination(ThreadPoolScheduledExecutorService.java:242)
        at app//io.pravega.common.concurrent.ExecutorServiceHelpers.shutdown(ExecutorServiceHelpers.java:197)
        at app//io.pravega.segmentstore.server.store.ServiceBuilder.close(ServiceBuilder.java:162)
        at app//io.pravega.segmentstore.server.host.StorageLoaderTest.testSlowModeWithInMemoryStorage(StorageLoaderTest.java:247)
```

**To Reproduce**
Frequently seen in our builds: https://github.com/pravega/pravega/actions/runs/6969546123/job/18989554932

**Screenshots**
n/a

**Additional information**
n/a

**Comment by tkaitchuck** [comment]
An example of this: https://github.com/pravega/pravega/actions/runs/7802577445/job/21280499728
