### ISSUE TITLE
Run ./pravega-controller in k8s cluster

### ISSUE THREAD

**Issue by zzkww** [pravega/pravega#7348]
# Ask your question away
Why do many of the following warnings appear when running the ./pravega-controller service under a k8s cluster:2024-01-12 17:18:52,403 92138 [ClientSocketReaders-2] WARN  i.p.controller.server.SegmentHelper - [requestId=-3946867873582637250] Connection dropped 85899345920
2024-01-12 17:18:54,005 93740 [ClientSocketReaders-2] INFO  i.p.c.c.impl.TcpClientConnection - Closing TcpClientConnection.Reader because end of input reached.
2024-01-12 17:18:54,009 93744 [ClientSocketReaders-2] WARN  i.p.c.connection.impl.RawClient - Closing connection to segment null with exception
io.pravega.shared.protocol.netty.ConnectionFailedException: null
        at io.pravega.client.connection.impl.RawClient$ResponseProcessor.connectionDropped(RawClient.java:83)
        at io.pravega.client.connection.impl.FlowHandler.lambda$close$3(FlowHandler.java:218)
        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(Unknown Source)
        at io.pravega.client.connection.impl.FlowHandler.close(FlowHandler.java:215)
        at io.pravega.client.connection.impl.FlowHandler.connectionDropped(FlowHandler.java:205)
        at io.pravega.client.connection.impl.TcpClientConnection$ConnectionReader.stop(TcpClientConnection.java:186)
        at io.pravega.client.connection.impl.TcpClientConnection$ConnectionReader.run(TcpClientConnection.java:146)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by RaulGracia** [comment]
Hi @zzkww, thanks for your question!

In a nutshell, the Controller in Pravega uses the Segment Stores to create and orchestrate the streams, as well as to store metadata. Apparently, this error is showing a connection issue in the `SegmentHelper` class, which is the class in the Controller that encapsulates the operations on segments against Segment Stores. So, this may mean that the Controller has problems to connect with a Segment Store, or that Segment Stores are not working well for some reason. It would also be interesting to know if this problem is persistent or transient. Hope it helps, thanks!

**Comment by zzkww** [comment]
> Hi @zzkww, thanks for your question!
> 
> In a nutshell, the Controller in Pravega uses the Segment Stores to create and orchestrate the streams, as well as to store metadata. Apparently, this error is showing a connection issue in the `SegmentHelper` class, which is the class in the Controller that encapsulates the operations on segments against Segment Stores. So, this may mean that the Controller has problems to connect with a Segment Store, or that Segment Stores are not working well for some reason. It would also be interesting to know if this problem is persistent or transient. Hope it helps, thanks!

Thank you for your answer！
There are two lines of related configuration in conf/controller.config.properties, controller.segmentstore.connect.host.nameOrIp=${SERVICE_HOST_IP}: The default value is localhost
controller.segmentstore.connect.port=${SERVICE_HOST_PORT}:The default value is: 12345
Is it related to these two configurations?

**Comment by RaulGracia** [comment]
Hi @zzkww, in my experience, if you are deploying Pravega in Kubernetes you don't need to change this configuration parameter.

One question to begin with: are you using the Pravega Operator to deploy Pravega on Kubernetes? https://github.com/pravega/pravega-operator

Because this is the way to go for deploying Pravega in a Kubernetes cluster. Trying to do that manually as it was a bare metal cluster is not going to work. You have scripts and examples of how to set up a Pravega cluster on Kubernetes that will help you to get started:
- https://github.com/pravega/pravega-operator/tree/master/setup
- https://cncf.pravega.io/docs/latest/admin-guide/operators/
- https://cncf.pravega.io/blog/2020/06/20/deploying-pravega-in-kubernetes/
