### ISSUE TITLE
Flakey test: EndToEndChannelLeakTest.testDetectChannelLeakSegmentSealed

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#7375]
**Describe the bug**
A flakey test has been observed several times:

```
io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest > testDetectChannelLeakSegmentSealed FAILED
    java.util.concurrent.TimeoutException: Timeout expired prior to the condition becoming true. Expected value: 0 observed: 1
        at io.pravega.test.common.TestUtils.awaitEvaluateExpr(TestUtils.java:121)
        at io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:68)
        at io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:53)
        at io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest.assertChannelCount(EndToEndChannelLeakTest.java:513)
        at io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest.testDetectChannelLeakSegmentSealed(EndToEndChannelLeakTest.java:311)
```
An example of this is:
https://github.com/pravega/pravega/actions/runs/7753263574/job/21144325636

**Comment by tkaitchuck** [comment]
An example of this: https://github.com/pravega/pravega/actions/runs/7808051468/job/21343041742
```
io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest > testDetectChannelLeakMultiReader FAILED
    java.lang.AssertionError: expected:<6> but was:<7>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:[835](https://github.com/pravega/pravega/actions/runs/7808051468/job/21343041742#step:6:836))
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest.assertChannelCount(EndToEndChannelLeakTest.java:512)
        at io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest.testDetectChannelLeakMultiReader(EndToEndChannelLeakTest.java:440)
```
