### ISSUE TITLE
Single node doesn't start rest server

### ISSUE THREAD

**Issue by Abhijeet-Jadhav** [pravega/pravega#832]
**Problem description**
SingleNode gradle task doesn't start a rest server.

**Problem location**
SingleNode gradle task.

**Suggestions for an improvement**
Resolve conflicts with Jersey versions and start REST server in SingleNode task.

**Comment by Abhijeet-Jadhav** [comment]
The problem was there are two jersery class files present:

1. HDFS in singleNode adds old - `com.sun.jersey » jersey-core   1.9`
https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-hdfs/2.7.3

2. rest/swagger adds `org.glassfish.jersey.core » jersey-server   2.1`
https://mvnrepository.com/artifact/org.glassfish.jersey.containers/jersey-container-servlet-core/2.1

HDFS depends on old, and doesn't have updates to org.glassfish one. So the because of the conflict the rest server couldn't be started. 

The old stacktrace was:
```
java.lang.NoSuchMethodError: javax.ws.rs.core.Application.getProperties()Ljava/util/Map;
       at org.glassfish.jersey.server.ResourceConfig$WrappingResourceConfig.mergeApplications(ResourceConfig.java:1140)
       at org.glassfish.jersey.server.ResourceConfig$WrappingResourceConfig.<init>(ResourceConfig.java:1060)
       at org.glassfish.jersey.server.ResourceConfig.forApplication(ResourceConfig.java:318)
       at com.emc.pravega.controller.server.rest.RESTServer.start(RESTServer.java:42)
       at com.emc.pravega.local.InProcPravegaCluster.startLocalController(InProcPravegaCluster.java:387)
       at com.emc.pravega.local.InProcPravegaCluster.startLocalControllers(InProcPravegaCluster.java:309)
       at com.emc.pravega.local.InProcPravegaCluster.start(InProcPravegaCluster.java:173)
       at com.emc.pravega.local.LocalPravegaEmulator.start(LocalPravegaEmulator.java:83)
       at com.emc.pravega.local.LocalPravegaEmulator.main(LocalPravegaEmulator.java:59)
```
