### ISSUE TITLE
Transaction commit failed with no reason in the TxnFailedException

### ISSUE THREAD

**Issue by maddisondavid** [pravega/pravega#893]
**Problem description**

Transaction commit failed, but there is no information in the Exception to indicate why it failed.

```
com.emc.pravega.stream.TxnFailedException: com.emc.pravega.stream.TxnFailedException
	at com.emc.pravega.common.concurrent.FutureHelpers.getAndHandleExceptions(FutureHelpers.java:121)
	at com.emc.pravega.stream.impl.EventStreamWriterImpl$TransactionImpl.commit(EventStreamWriterImpl.java:175)
	at com.emc.nautilus.pravega.taskexecutor.turbine.TurbineHeatWriters$TransactionTemperatureSensors.finished(TurbineHeatWriters.java:184)
	at com.emc.nautilus.pravega.taskexecutor.turbine.TurbineHeatWriters$TemperatureSensors.run(TurbineHeatWriters.java:219)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.emc.pravega.stream.TxnFailedException: null
	at com.emc.pravega.common.concurrent.FutureHelpers.expect(FutureHelpers.java:240)
	at com.emc.pravega.common.concurrent.FutureHelpers.lambda$toVoidExpecting$4(FutureHelpers.java:234)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at com.emc.pravega.stream.impl.ControllerImpl$RPCAsyncCallback.onCompleted(ControllerImpl.java:485)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:390)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:422)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:74)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:508)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:425)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:540)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
	... 3 common frames omitted
```

**Problem location**
Whilst attempting to commit a transaction

**Suggestions for an improvement**
Provide information in the Exception as to why the transaction failed to comit

**Comment by chrisdail** [comment]
It has been a very long time since we have seen this issue. Going to close it.
