### ISSUE TITLE
Throw better Exceptions on TX failure

### ISSUE THREAD

**Issue by maddisondavid** [pravega/pravega#941]
**Problem description**
When beginTX fails to get the Transaction Lock the following exception is thrown by the client

```
java.lang.RuntimeException: io.grpc.StatusRuntimeException: INTERNAL: Failed locking resource dave/LoadTest.
    at com.emc.pravega.common.concurrent.FutureHelpers.getAndHandleExceptions(FutureHelpers.java:121)
    at com.emc.pravega.stream.impl.EventStreamWriterImpl.beginTxn(EventStreamWriterImpl.java:215)
    at com.emc.nautilus.pravega.taskexecutor.workers.PravegaWriter.beforeWrite(PravegaWriter.java:91)
    at com.emc.nautilus.pravega.taskexecutor.workers.PravegaWriter.start(PravegaWriter.java:149)
    at com.emc.nautilus.pravega.taskexecutor.workers.WriterWorkerManager.lambda$start$0(WriterWorkerManager.java:146)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Failed locking resource dave/LoadTest.
    at io.grpc.Status.asRuntimeException(Status.java:539)
    at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:392)
    at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:422)
    at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:74)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:508)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:425)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:540)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
    at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
    ... 3 common frames omitted
```

There are two issues:

1. The Exception thrown is not very descriptive and actually looks like a serious internal error due to the `INTERNAL`
2. The Exception is wrapped inside a generic RuntimeException making it more difficult to capture and handle.

**Problem location**
Transaction Locking

**Suggestions for an improvement**
Throw a more meaningful exception back to the client that can be correctly caught

**Comment by shrids** [comment]
Closing this issue based on #1151
