### ISSUE TITLE
Intermittent test failureof ReadIndexSummaryTests

### ISSUE THREAD

**Issue by bhargav-gulavani** [pravega/pravega#990]
**Problem description**
Intermittent failure on Travis
```
com.emc.pravega.service.server.reading.ReadIndexSummaryTests > testAddExplicitGeneration FAILED
    java.lang.AssertionError: Unexpected newest generation. expected:<0> but was:<99>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at com.emc.pravega.service.server.reading.ReadIndexSummaryTests.testRemove(ReadIndexSummaryTests.java:102)
        at com.emc.pravega.service.server.reading.ReadIndexSummaryTests.testAddExplicitGeneration(ReadIndexSummaryTests.java:80)
```
**Problem location**
ReadIndexSummaryTests.

**Suggestions for an improvement**
Fix intermittent failure.

**Comment by andreipaduroiu** [comment]
This has not happened in a while.
